### ISSUE TITLE
docker does not like naming containers uppercase single case letters

### ISSUE THREAD

**Issue by zbanga** [ctubio/Krypto-trading-bot#1]
Changing to a lower-case will help

**Comment by ctubio** [comment]
umf i hate grammar (https://github.com/docker/distribution/blob/master/reference/reference.go#L1) but lets try to be correct, many thanks for the report!

**Comment by ctubio** [comment]
also, many thanks for the solution :sunflower:

**Comment by jaNGOB** [comment]
It's still not working for me. I tried to run it a few days ago and also had the Problem with the uppercase "K". I have redone the whole process but it's still throwing an error at me because of the "k". 

What else could I do?

Thank you for your help.

```
$ docker run -p 3000:3000 --link K-mongo:mongo --name k -d k
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Invalid container name (k), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```

**Comment by ctubio** [comment]
sorry for the confusion, the container name should be k, but the image name K:
```
 $ cd path/to/Dockerfile
 $ docker run -p 27017:27017 --name K-mongo -d mongo
 $ docker build -t k .
 $ docker run -p 3000:3000 --link K-mongo:mongo --name K -d k
```

**Comment by jaNGOB** [comment]
hmm, I still can't get it to work.

First up:
`gobel@DESKTOP-3TC1F6S MINGW64 ~/Documents/Tribeca
$ docker run -p 27017:27017 --name K-mongo -d mongo
e78b5321e676800dfa9c5e6089a86a0e061d1a7e25d03b622b15b31eb8065831`

`gobel@DESKTOP-3TC1F6S MINGW64 ~/Documents/Tribeca
$ docker build -t k .
Sending build context to Docker daemon  4.096kB
Step 1/51 : FROM node:7
 ---> 6c792d919591
Step 2/51 : RUN apt-get update
 ---> Using cache
 ---> 67b7b92fb7d7
Step 3/51 : RUN apt-get install -y git sudo
 ---> Using cache
 ---> c83766fd8c46
Step 4/51 : RUN git clone -b master https://github.com/ctubio/Krypto-trading-bot.git K
 ---> Using cache
 ---> 8172bd1e1315
Step 5/51 : WORKDIR K
 ---> Using cache
 ---> 942054f649b2
Step 6/51 : RUN npm install --unsafe-perm
 ---> Using cache
 ---> dfe53a128ddd
Step 7/51 : EXPOSE 3000 5000
 ---> Using cache
 ---> bc3850043e28
Step 8/51 : ENV BotIdentifier dev
 ---> Using cache
 ---> f0d73081dd77
Step 9/51 : ENV EXCHANGE Coinbase
 ---> Using cache
 ---> 4176f247c5a5
Step 10/51 : ENV TradedPair ETH/BTC
 ---> Using cache
 ---> 9f36cba101d6
Step 11/51 : ENV WebClientUsername jaN
 ---> Using cache
 ---> 8ac3a389a6da
Step 12/51 : ENV WebClientPassword 4101
 ---> Using cache
 ---> 8ed63477f80e
Step 13/51 : ENV WebClientListenPort 3000
 ---> Using cache
 ---> eb774fdcd82f
Step 14/51 : ENV MongoDbUrl mongodb://K-mongo:27017/K
 ---> Using cache
 ---> 884ea08f06b5
Step 15/51 : ENV MatryoshkaUrl https://
 ---> Using cache
 ---> c25d46f9c942
Step 16/51 : ENV CoinbaseRestUrl https://api-public.sandbox.gdax.com
 ---> Using cache
 ---> a556fcd26da3
Step 17/51 : ENV CoinbaseWebsocketUrl wss://ws-feed-public.sandbox.gdax.com
 ---> Using cache
 ---> f5f63a976cc8
Step 18/51 : ENV CoinbasePassphrase tribeca
 ---> Using cache
 ---> 9c53ef74e2c4
Step 19/51 : ENV CoinbaseApiKey 444537b39d79ddd7611c36cd366c97f0
 ---> Using cache
 ---> fc5a5eda9fd8
Step 20/51 : ENV CoinbaseSecret iJN5j+PN9HgYzaKwzjsX2MCY7uW7dGnZemqW/WaUsVxtrypgtXFSLYTPKRqw4dktcG2JqJLsX0p1suGUu6f2AA==
 ---> Using cache
 ---> 5c0cc2be02d5
Step 21/51 : ENV CoinbaseOrderDestination Coinbase
 ---> Using cache
 ---> dac86447474c
Step 22/51 : ENV OkCoinWsUrl wss://real.okcoin.com:10440/websocket/okcoinapi
 ---> Using cache
 ---> 73c33d51dab0
Step 23/51 : ENV OkCoinHttpUrl https://www.okcoin.com/api/v1/
 ---> Using cache
 ---> 33ba2213dfee
Step 24/51 : ENV OkCoinApiKey NULL
 ---> Using cache
 ---> b9c019abb2f3
Step 25/51 : ENV OkCoinSecretKey NULL
 ---> Using cache
 ---> 9daa047082ef
Step 26/51 : ENV OkCoinOrderDestination OkCoin
 ---> Using cache
 ---> f4007dcbf203
Step 27/51 : ENV BitfinexHttpUrl https://api.bitfinex.com/v1
 ---> Using cache
 ---> 2ba2f1bbed08
Step 28/51 : ENV BitfinexWebsocketUrl wss://api.bitfinex.com/ws/2
 ---> Using cache
 ---> efa3cfee1e98
Step 29/51 : ENV BitfinexKey NULL
 ---> Using cache
 ---> fd5a2bb82d36
Step 30/51 : ENV BitfinexSecret NULL
 ---> Using cache
 ---> 40419023d32e
Step 31/51 : ENV BitfinexOrderDestination Bitfinex
 ---> Using cache
 ---> fcb0a4a5dd59
Step 32/51 : ENV PoloniexHttpUrl https://poloniex.com
 ---> Using cache
 ---> a59b74ae7784
Step 33/51 : ENV PoloniexWebsocketUrl wss://api.poloniex.com
 ---> Using cache
 ---> a697dcbb4c99
Step 34/51 : ENV PoloniexApiKey NULL
 ---> Using cache
 ---> 5e895cfbca18
Step 35/51 : ENV PoloniexSecretKey NULL
 ---> Using cache
 ---> c8afb9cf0e37
Step 36/51 : ENV PoloniexOrderDestination Poloniex
 ---> Using cache
 ---> a2c65c3424c4
Step 37/51 : ENV KorbitHttpUrl https://api.korbit.co.kr/v1
 ---> Using cache
 ---> 4e7b901a73e3
Step 38/51 : ENV KorbitApiKey NULL
 ---> Using cache
 ---> deb4d2aab1e6
Step 39/51 : ENV KorbitSecretKey NULL
 ---> Using cache
 ---> eea006b86ac3
Step 40/51 : ENV KorbitUsername NULL
 ---> Using cache
 ---> b36659c396e9
Step 41/51 : ENV KorbitPassword NULL
 ---> Using cache
 ---> 7cfa446581cd
Step 42/51 : ENV KorbitOrderDestination Korbit
 ---> Using cache
 ---> 2836816b7a7f
Step 43/51 : ENV HitBtcPullUrl http://demo-api.hitbtc.com
 ---> Using cache
 ---> 0a0abacaec2b
Step 44/51 : ENV HitBtcOrderEntryUrl ws://demo-api.hitbtc.com:8080
 ---> Using cache
 ---> 86b5bd4acb5a
Step 45/51 : ENV HitBtcMarketDataUrl ws://demo-api.hitbtc.com:80
 ---> Using cache
 ---> 7d1c9f2d0794
Step 46/51 : ENV HitBtcSocketIoUrl https://demo-api.hitbtc.com:8081
 ---> Using cache
 ---> b5c923b0ccde
Step 47/51 : ENV HitBtcApiKey NULL
 ---> Using cache
 ---> dbd512a15727
Step 48/51 : ENV HitBtcSecret NULL
 ---> Using cache
 ---> aae6ee603174
Step 49/51 : ENV HitBtcOrderDestination HitBtc
 ---> Using cache
 ---> 890cae72aa10
Step 50/51 : ENV delayUI 3
 ---> Using cache
 ---> 29c0ca16eb72
Step 51/51 : CMD node_modules/.bin/forever K.js
 ---> Using cache
 ---> a1981dc94430
Successfully built a1981dc94430
Successfully tagged k:latest`

And then again the error:
`gobel@DESKTOP-3TC1F6S MINGW64 ~/Documents/Tribeca
$ docker run -p 3000:3000 --link K-mongo:mongo --name K -d k
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Invalid container name (K), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.`

Im sorry to bother you with this and thanks a lot for your help

**Comment by ctubio** [comment]
i suspect you have an old docker version, may be?
mine is:
```
```

**Comment by ctubio** [comment]
:warning: err well, your msg was send to all people watching the project so allow me to recomend you to change the API key of this exchange asap

**Comment by jaNGOB** [comment]
I run Docker CE and use the Docker version 17.05.0-ce, build 89658be. It's the uptodate version of Docker CE as far as I know.

I've redone everything again and it still doesn't work.

Thank you for the editing my post. I immediately deleted the API key from my account.

**Comment by ctubio** [comment]
well, donno why your version doesn't like single-letter names, but if so try to change K and k to longer names:
```
 $ cd path/to/Dockerfile
 $ docker run -p 27017:27017 --name K-mongo -d mongo
 $ docker build -t k-js .
 $ docker run -p 3000:3000 --link K-mongo:mongo --name K-js -d k-js
```
or something similar, cos your error is just with the namings of the container

**Comment by jaNGOB** [comment]
It worked. I had no problem now with Kjs. You were right, it was only because of the naming.

Thank you again for your patience and help.

**Comment by ctubio** [comment]
thanks for the report'¡ i just updated the docs :dancer:

**Comment by ctubio** [comment]
btw if you use GDAX, you may be interested in the last comment at https://github.com/ctubio/Krypto-trading-bot/issues/3
