### ISSUE TITLE
problem with uncanceled orders on GDAX

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#100]
Hi Charles,

first of al, again, thanks a lot for the hours of work you spent in this project.
Since the transfer to c++ it runs much faster for me.

But one thing i see which might be an error (or something inbetween my ears): As you see on the attached Image, i have open orders in gdax but k is not showing them up. This happens seconds to minutes after i cancel the orders manually, then i get good quotes for some secs since there are uncanceled orders in gdax again.
![bildschirmfoto 2017-07-25 um 13 46 28](https://user-images.githubusercontent.com/540850/28571290-81bcb60a-7142-11e7-8f52-c6747d7ccabd.png)

and btw: look at the memory used. I start at 32MB (which is VERY cool) but after some hours i am at more than 300MB. is that a memory leak?

**Comment by ctubio** [comment]
yea gdax have clearly some memory leak; is in the javascript side for sure, so i hope for it to be fixed soOn while migrating (RAM should be always less than 60MB)

**Comment by ctubio** [comment]
since https://github.com/ctubio/Krypto-trading-bot/commit/41ed3f8ba1206cea894aed98953fb7e97b14daaf the gdax bot should not eat so much ram

**Comment by b-seite** [comment]
Hey Charles,
K is running faster and faster, thank you for that.
Unfortunately i have the same problem with uncanceled orders on GDAX again. Due to some other Problems i had, i cannot exactly say when it started again. atm i am running the latest commit .
the Problem occurred immediately after manually cancelling the orders, sometimes in a minute but sometimes after some seconds.

![bildschirmfoto 2017-08-21 um 12 12 08](https://user-images.githubusercontent.com/540850/29515194-bd8e4e6c-866b-11e7-8aff-35a5a59c1473.png)

Thanks in advance, if i can help with anything, i´ll try so.

btw: because K is soooo incredible fast, is it possible to get decimals for the latency output?  I searched for it to change but i found nothing in the source.  

And YES the memory leak is gone away :) Thanks again for THAT

**Comment by ctubio** [comment]
latency is already in microseconds and can't have decimals, but to make it more accurate a solution is to change microseconds by nanoseconds, that will give 3 more precision digits

About gdax im curently looking at it, hope i can reproduce it

**Comment by b-seite** [comment]
i´ve investigated just a little bit but maybe it´s because of the order ID´s?
i see several orders with the same Order ID when i run ak47 with 2 or more bullets.
![bildschirmfoto 2017-08-21 um 20 05 21](https://user-images.githubusercontent.com/540850/29532254-7fb10300-86ac-11e7-80b5-0a6ff3f16db1.png)
when i switch to just one Bullet it seems that the problem is gone

**Comment by b-seite** [comment]
Hey Charles,

sorry to steal your time again,  still have that problem on gdax. 

Think my previous post is the wrong path because the id is simply splitted before outputted. 
Would be a good idea to revert the split otherwise the output is useless in my opinion.

And another issue: since yesterday i cannot cancel all orders with the cancel order button anymore. Only the orders known by K are cancelled but the zombie-orders stay alive (hmm... sounds strange) 
In the past i cancelled all orders, alive or zombie, with the button. 
would also be great to have that functionality back.

And at least: yeah nanoseconds are great, perhaps if the latency is > 10ms or so

Thanks alot

**Comment by ctubio** [comment]
lets try to split topics in different issues; for instances i can say that the cancel all button worked this way since forever; it only cancels orders known by K. in the other hand, the `cxl` checkbox cancels orders also opened in the exchange every 5 minutes

about the coinbase orders, they are different, but the first 8 characters displayed happend to be equal. (they are 32 characters long)

in case you feel something else is missing consider to open a new issue; if you wanna refer to this issue simply attach a link; so you dont need to reupload your posted images.

thanks'¡
