### ISSUE TITLE
Support KuCoin And KuMEX

### ISSUE THREAD

**Issue by niulingyun** [ctubio/Krypto-trading-bot#1010]
Exchange support for KuCoin and KuMEX as It is one of the top exchanges.

And here is the api dos.

https://docs.kucoin.com/
https://docs.kumex.com/

Thank you.

**Comment by ctubio** [comment]
many thanks for the documentation links, i just checked the APIs and seems niiice, with websocket market data and orders; maybe someday this exchanges will be included if more people support it

:koala: lets keep the issue opened since the APIs are nice, waiting for more people to want this

**Comment by flfsbr** [comment]
I do not use these exchanges particularly but I think it is a great idea to support new exchanges, especially those with rebates, low fees or have a large spread on currencies.

**Comment by purekid** [comment]
Please support KuCoin and KuMEX.

**Comment by hhxsv5** [comment]
So many people are using KuCoin and KuMEX, please support them.

**Comment by inkbx** [comment]
Please support KuCoin and KuMEX.

**Comment by pinguo-huanghao** [comment]
Please support KuCoin and KuMEX!

**Comment by syyongx** [comment]
Please support KuCoin and KuMEX!

**Comment by TorotoXiao** [comment]
Please support KuCoin and KuMEX!

**Comment by ctubio** [comment]
:koala: many thanks for your suggestion''''
