### ISSUE TITLE
 Request for cooperation

### ISSUE THREAD

**Issue by foxxcrypto** [ctubio/Krypto-trading-bot#1011]
Hi Carles, 

your work is interesting.
I would like to collaborate on the project by inserting new strategies, based on machine learning, which make forecasts on book movements based on the flow of orders.
Currently I have written them in python but the bot I'm using is too slow to do market making on bitmex.
Currently I would be interested in working on bitmex, the key to unlocking is the following: 33i5YyTQ4LfoxXmJsu85p6NFH4zYLRHy8S

Hope we can cooperate.
Thank you.
Hello.
Luca
Hope we can cooperate.
Thank you.
Hello.
Luca

**Comment by ctubio** [comment]
morniiing'''
feel free to make a pull request and if it is accepted an unlock will be granted
