### ISSUE TITLE
Autoclean trades?

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#1012]
After a few days with some thousand trades, the K GUI is slowing down, so a nice feature would be some "autoclean" that does a "Clean Trades" after a period of time or a specific amount of trades...

**Comment by ctubio** [comment]
see `Kmemory` quoting parameter:

Timeout in days for Pings (yet unmatched trades) and/or Pongs (K trades) to remain in memory, a value of 0 keeps the history in memory forever; a positive value remove only Pongs after Kmemory days; but a negative value remove both Pings and Pongs after Kmemory days (for example a value of -2 will keep a history of trades no longer than 2 days without matter if Pings are not matched by Pongs; or a value of -0.25 will do so but limited to 6h).
