### ISSUE TITLE
Coinbase not connecting to FIX

### ISSUE THREAD

**Issue by thhrro** [ctubio/Krypto-trading-bot#1013]
I installed and added my Coinbase API keys to the config and when starting up I get the following error:

`Warrrrning: WS CURL connect FIX Error: Weird server reply, reconnecting in 7s..`

I checked and have the cert in /etc/ssl/

**Comment by ctubio** [comment]
here iz working fine, that must be a temporary error, note coinbase had been down lately (https://status.coinbase.com/)

:koala: do you still have this error?

**Comment by thhrro** [comment]
@ctubio Yeah, I'm still getting the error. Any quick tips on where/how to put a logger to maybe see exactly what their FIX API is sending back?

Thanks

**Comment by ctubio** [comment]
the only think you can do is define the api key and api secret and api password.

make sure you defined them correctly, without trailing spaces or stuff like that

if you still wanna debug it, just trace the content of the variable `in` at:
https://github.com/ctubio/Krypto-trading-bot/blob/19b03620258fb2695f916bf414642e67b76e77e4/src/lib/Krypto.ninja-data.h#L458-L462
