### ISSUE TITLE
Web UI Disconnecting Constantly (Cannot read property 'ewmaWidth' of undefined)

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1015]
Using latest Chrome and the web UI constantly displays for a brief moment and disappears immediately showing ~.sh is disconnected screen.
If I leave the UI open for long enough it will randomly connect.
Restarting K doesn't seem to fix it either.
Running latest commit with fully updated debian buster.

Edit: Seeing this in my console log on Brave.
client.min.js:1 ERROR TypeError: Cannot read property 'ewmaWidth' of undefined
    at StatsComponent.updateCharts (client.min.js:1)
    at client.min.js:1
    at ZoneDelegate.invokeTask (client.min.js:1)
    at Object.onInvokeTask (client.min.js:1)
    at ZoneDelegate.invokeTask (client.min.js:1)
    at Zone.runTask (client.min.js:1)
    at ZoneTask.invokeTask (client.min.js:1)
    at ZoneTask.invoke (client.min.js:1)
    at timer (client.min.js:1)
defaultErrorLogger @ client.min.js:1

**Comment by ctubio** [comment]
thanks for the report''''

:koala: i never saw thiz error, lemme try to understand how  can be undefined the object container of `ewmaWidth`

**Comment by MiningInMySleep** [comment]
Haven't run into this issue in a while. Maybe some of the updates pushed recently had an effect? Not really sure.

**Comment by AchimBauer** [comment]
Been having this issue since this afternoon, neither reloading the page or restarting the bot helped :-/

**Comment by onisoc** [comment]
What you can do is remove current .db and start it again.

**Comment by ctubio** [comment]
:bulb: this was attempted to be fixed at https://github.com/ctubio/Krypto-trading-bot/pull/1024
