### ISSUE TITLE
Bitfinex BTC Above 10k

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1017]
When the price of BTC is over 10k the smallest decimal gets reduced so that bids and asks can only be in whole numbers versus tens of cents. Due to this, the bot basically spams orders and I'm constantly over 200 orders/60 seconds because it is expecting to be able to set orders down to the tenth of a cent. E.g.: 10050.2

**Comment by ctubio** [comment]
currently this values are set on boot, so a restart is required to fix it

may be possible to refresh this values somehow when the price changes, will need to look carefully at it cos was never expected this stuation :(

**Comment by MiningInMySleep** [comment]
Yeah, definitely causing some major issues. I reset it while we were above 10k and then everything was going fine until we dropped down under 10k then the calculations started getting all crazy again including how recent trades appear in the table because it rounds everything to the nearest dollar. Bid/Ask prices are also appearing multiple times in the open orders list.

**Comment by eniware-org** [comment]
Let's hope the price will not go lower than 10k ever!
;)

**Comment by ctubio** [comment]
if you ask me i like the values to be constants and to be defined on boot; they are used everywhere nonstop so ima not touch them i think
