### ISSUE TITLE
Question: Latency value of open orders

### ISSUE THREAD

**Issue by bunde83** [ctubio/Krypto-trading-bot#102]
Quick question, the latency value displayed in the open orders area - Is this API latency only, or API+UI?

Just seeing random latency spikes and not sure if this is the exchanges poor API response or possibly just the UI delay being added depending on how close the order entry timestamp is to the UI refresh.

**Comment by ctubio** [comment]
latency = time between server and exchange to place new orders (API only yea, nothing about the UI)
