### ISSUE TITLE
Negative market width?

### ISSUE THREAD

**Issue by eniware-org** [ctubio/Krypto-trading-bot#1020]
This is a second time I notice this in the last couple of days:
![negative market width](https://user-images.githubusercontent.com/34030382/77237138-768a7d80-6bbd-11ea-9d8c-bdda57331ab2.PNG)
Bitfinex exchange, latest build.

**Comment by ctubio** [comment]
Hello,
here is the definition of Market Width value:
https://github.com/ctubio/Krypto-trading-bot/blob/85f89f803f3065d21626dd11c52b99ecd80b2005/src/bin/trading-bot/client/market-quoting.ts#L256
