### ISSUE TITLE
Coinbase Pro FIX

### ISSUE THREAD

**Issue by linucis** [ctubio/Krypto-trading-bot#1021]
Dear @ctubio 
There is no documentation for coinbase pro FIX settings.
But in the source code, some of its features are implemented.(/lib/Krypto.ninja-apis.h)
Please help with this.

**Comment by ctubio** [comment]
im not sure that i understand you, but what i understand by "documentation for coinbase pro fix settings" is at https://docs.pro.coinbase.com/#fix-api

if you mean to configure this application, are you sure that you had read the commented lines in your config file? (or in the destributed one at https://github.com/ctubio/Krypto-trading-bot/blob/master/etc/K.sh.dist?)
