### ISSUE TITLE
AK-47 safety working incorrectly

### ISSUE THREAD

**Issue by eniware-org** [ctubio/Krypto-trading-bot#1029]
On Bitfinex, full GW, latest commit.
3 bullets configured - only 2 per side submitted! Sufficient funds on both sides.
![image](https://user-images.githubusercontent.com/34030382/86413750-fc888b00-bcb9-11ea-8f76-f8f65f81bb68.png)
After ```lifetime``` milliseconds (90000 in my case) - 3 ask, 4 bid!
![image](https://user-images.githubusercontent.com/34030382/86413946-833d6800-bcba-11ea-899b-163818e11fe8.png)
Further, also the range is not respected:
![image](https://user-images.githubusercontent.com/34030382/86419102-33ff3380-bcca-11ea-9d5e-fd0daf08ce28.png)

**Comment by ctubio** [comment]
morniiing'''
AK47 logic is highly variable, the codes are perfect if you ask me..
https://github.com/ctubio/Krypto-trading-bot/blob/939506a866baa99f5eb1d5518307479d0f993968/src/bin/trading-bot/trading-bot.data.h#L2419-L2429
https://github.com/ctubio/Krypto-trading-bot/blob/939506a866baa99f5eb1d5518307479d0f993968/src/bin/trading-bot/trading-bot.data.h#L2222-L2225
