### ISSUE TITLE
Error 403 -> How to fix ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#103]
Hi Carles,

I made a mistake in the password login of one of my instance, and now it can't access it. It gives me a 403 ^^'.

Any idea how to fix that? Restarting/reinstall did not fix it. :S

**Comment by ctubio** [comment]
close and reopen the browser.
browsers saves the passwords just in session data, so closing it effectively makes the browser ask again for it.

**Comment by Camille92** [comment]
Thank you ! That was a bit of a stupid question haha.
Btw your new formula works perfectly :)

**Comment by ctubio** [comment]
thanks for confirm the formula'¡
