### ISSUE TITLE
Bitmex websocket API update

### ISSUE THREAD

**Issue by gusiri** [ctubio/Krypto-trading-bot#1031]
Recently, I found out that the bot keeps sending repeated (and infinite) orders for bitmex,

and I guess the reason is due to bitmex's websocket API update on Aug 24.

Any idea on this?

source: https://blog.bitmex.com/api_announcement/change-to-updates-on-the-order-feed-for-new-and-triggered-orders/

----------------------

Order of messages on the order Websocket API feed for **new order requests** **before** this change (2 messages are sent):

- ordStatus=New, workingIndicator=0b

- ordStatus=New | Filled | PartiallyFilled | Canceled | Rejected, workingIndicator=1b | 0b

Order of messages on the order Websocket API feed for **new orders** **after** this change (1 message is sent):

- ordStatus=New | Filled | PartiallyFilled | Canceled | Rejected, workingIndicator=1b | 0b

----------------------

Order of messages on the order Websocket API feed for **triggered orders** **before** this change (2 messages are sent):

- ordStatus=New, workingIndicator=0b, triggered=StopOrderTriggered

- ordStatus=New | Filled | PartiallyFilled | Canceled | Rejected, workingIndicator=1b | 0b, triggered=StopOrderTriggered

Order of messages on the order Websocket API feed for **triggered orders** **after** this change (1 message is sent):

- ordStatus=New | Filled | PartiallyFilled | Canceled | Rejected, workingIndicator=1b | 0b, triggered=StopOrderTriggered

**Comment by ctubio** [comment]
you are 100% right; sorry for taking me so long

**Comment by Corfucinas** [comment]
commenting so I can follow the discussion (turned off my bot when this started happening).

**Comment by gusiri** [comment]
So glad @ctubio is back!
