### ISSUE TITLE
 com desbloquejar el bot 

### ISSUE THREAD

**Issue by dobermanx8** [ctubio/Krypto-trading-bot#1032]
com desbloquejar el bot de trading per aplicar apys?

**Comment by dobermanx8** [comment]
no encuentro la direccion BTC para el desbloqueo...

**Comment by dobermanx8** [comment]
soy muy nuevo en esto de github y me gustaria ctubio que me ayudes a conectar el bot a hitbtc y los datos para transferir el btc

**Comment by ctubio** [comment]
it is printed on exit...

**Comment by ctubio** [comment]
did you ever run the app?

**Comment by dobermanx8** [comment]
si,actualmente esta en un vps montado,pero no tengo ni idea de como encontrar la direccion btc y los pasos posteriores para apuntar el bot ccon la api al exchange

**Comment by dobermanx8** [comment]
perdona,ya te digo soy un poco noob,puedo entender mejor el catalan que el ingles...jajajaj soy valenciano

**Comment by dobermanx8** [comment]
si pudieses tener un poco de paciencia y me ayudases te lo agradeceria mucho,llevo 2 dias intentando contactar contigo pero estoy perdidisimo.,...:)

**Comment by dobermanx8** [comment]
??

**Comment by ctubio** [comment]
bones'''
no se molt be fins on has arribat; potser pots copiar algun log de pantalla o alguna cosa per a que et pugui dir quin es el següent pas?

per contactar amb mi normalment la gent utilitza l'irc channel, el link esta en el readme (perque aixo del github es un bugtracker no un helpdesk).

**Comment by ctubio** [comment]
la configuracio es al fitxer K.sh (ho posa en el readme), has d'editar-lo

**Comment by dobermanx8** [comment]
vale ,gracias mañana con mas tiempo podre pasarme por el irc ,actualmente tengo el bot activo pero sin apuntar a ningun exchange,imagino que me falta algun codigo tras la donacion para desbloquearlo.gracias por atenderme y espero poder hablar contigo en otro momento un saludo!!:)

**Comment by dobermanx8** [comment]
lo tengo todo supuestamente configurado,el bot ya detecta hitbtc precios y todo,pero no detecta mis fondos....
