### ISSUE TITLE
Add Bitcoin.com Exchange

### ISSUE THREAD

**Issue by flfsbr** [ctubio/Krypto-trading-bot#1034]
Hi Carles,
I realized that Bitcoin.com Exchange uses exactly the same api as HitBTC and Bequant. 
Would it be possible to add this exchange?

https://exchange.bitcoin.com/

**Comment by ctubio** [comment]
:koala: im sorry i dont trust anything under bitcoin.com domain

they may have the same api because of evil reasons

**Comment by ctubio** [comment]
but but but if they use the same api, you could just change the urls in the source and give it a try, at:
https://github.com/ctubio/Krypto-trading-bot/blob/85f89f803f3065d21626dd11c52b99ecd80b2005/src/lib/Krypto.ninja-apis.h#L637-L640
