### ISSUE TITLE
unlocking

### ISSUE THREAD

**Issue by oberon2410** [ctubio/Krypto-trading-bot#1035]
Hi Carles, how can I unlock it? I would even like to add a 37 exchange websoccket and margin operations. Please send me an email or I'll give you mine and we'll talk. asesorfinastur@gmail.com

**Comment by ctubio** [comment]
morniiing'''
im sorry for the confusion, the app explains itself on exit how to be unlocked; but let me know if you have any detailed question.

:koala: hope you have notifications enabled so this text will turn ina email for you.
