### ISSUE TITLE
coinbase three headed monkey

### ISSUE THREAD

**Issue by nonkreon** [ctubio/Krypto-trading-bot#1038]
12/31 14:35:51.811084 GW COINBASE cached handshake:
│ - autoBot: yes                                                           ┌──┐
│ - symbols: BTC/USD (0.00000001/0.01)
│ - gateway: fix.pro.coinbase.com:4198
┌──────┬────┤ K COINBASE UI at https://127.0.0.1:┤ [ESC]: S┬op?, [q]: Quit!
│
│ - autoBot: yes
│ - symbols: BTC/USD (0.00000001/0.01)
│ - minSize: 0.00100000 BTC
│ - makeFee: 0.50%                                                         ┌──┐
│ - takeFee: 0.50%.                                                         │
│ 12/31 14:35:51.811417 DB loaded OK from /var/lib/K/db/K-trading-bot.COIN   
│ BASE.BTC.USD.db.                                                           
│ 12/31 14:35:51.814044 DB loaded last Quoting Parameters OK.                
│ 12/31 14:35:51.814257 DB loaded last EWMA Values OK.                       
│ 12/31 14:35:51.816853 DB loaded 2529 historical Fair Values.               
│ 12/31 14:35:51.817329 DB loaded 101 STDEV Periods.                         
│ 12/31 14:35:51.817513 DB loaded TBP = I removed the number here BTC.                        
│ 12/31 14:35:51.832097 DB loaded 3925 historical Profits.                   
│ 12/31 14:35:51.832683 UI ready at https://127.0.0.1:3000.              
│ 12/31 14:35:52.301889 GW COINBASE FIX success Logon, streaming orders.   └──┘
│ 12/31 14:35:52.302145 GW COINBASE Quoting state changed to CONNECTED.
│ 12/31 14:35:54.274183 GW COINBASE WS Streaming book levels.
│ terminate called after throwing an instance of 'std::invalid_argument'
├───┤< (1) Open Orders while 1 BTC = 29014.15 USD:                        what():  stod0.01009787 BTC at price 29010.41 USD (value 292.94 USD)
12/31 14:36:10.585579 Errrror: Aborted (Three-Headed Monkey found):
- exchange: COINBASE
- currency: BTC/USD
- binbuild: K-trading-bot linux-x86_64
- lastbeat: 14.372180
- tracelog:
  15: K-trading-bot(_start+0x2a) [0x55bc613a0f7a]
  14: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f3ac67260b3]
  13: K-trading-bot(main+0x1e) [0x55bc6139e17e]
  12: K-trading-bot(_ZN3₿6Events4walkEv+0x7f) [0x55bc613affef]
  11: K-trading-bot(_ZN3₿8GwApiFix19wait_for_async_dataEv+0x46b) [0x55bc6144dfdb]
  10: K-trading-bot(_ZN3₿14GwCoinbaseData7consumeEN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS1_14adl_serializerEEE+0xbdc) [0x55bc6144c23c]
  9: K-trading-bot(+0x1cf53f) [0x55bc6140453f]
  8: K-trading-bot(+0x167fcd) [0x55bc6139cfcd]
  7: K-trading-bot(+0x4db4c4) [0x55bc617104c4]
  6: K-trading-bot(+0x4db581) [0x55bc61710581]
  5: K-trading-bot(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x55bc61710546]
  4: K-trading-bot(+0x168321) [0x55bc6139d321]
  3: /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7f3ac6724859]
  2: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f3ac674518b]
  1: /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f3ac6745210]
  0: K-trading-bot(_ZN3₿6Ending3wtfEi+0x293) [0x55bc614006e3]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

12/31 14:36:10.585644 GW COINBASE Attempting to cancel all open orders, please wait..
12/31 14:36:10.726168 GW COINBASE cancel all open orders OK.
12/31 14:36:10.726230 GW COINBASE Quoting state changed to DISCONNECTED.
12/31 14:36:10.726294 GW COINBASE FIX Logout.
double free or corruption (!prev)

**Comment by ctubio** [comment]
lets fix this together with https://github.com/ctubio/Krypto-trading-bot/issues/1039
