### ISSUE TITLE
K won't start :s

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#104]
Hey Carles sorry to bother again, I was all excited to try the last version with forever corrected but it seems there is a bug somewhere:

```
17:25:47.894808 CF settings loaded from JSON file btcusd OK.
nodejs: symbol lookup error: /home/camille/K/app/server/lib/K.linux.51.node: undefined symbol: _ZN1K12sqlite3_openENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPP7sqlite3
```

**Comment by ctubio** [comment]
im testing the libK :( let em recompile it and retry

**Comment by ctubio** [comment]
sorry can you see if is OK now after this last commit?

**Comment by Camille92** [comment]
same problem :s
 K.linux.51
17:53:8.728590 CF settings loaded from JSON file ethusd OK.
nodejs: symbol lookup error: /home/camille/K/app/server/lib/K.linux.51.node: undefined symbol: _ZN1K12sqlite3_openENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPP7sqlite3

**Comment by ctubio** [comment]
ok iSee, sqlite is not the problem but the libK itself, let me try to fix or rollback

**Comment by ctubio** [comment]
what if you run "make"? doesnt then starts OK? :P

**Comment by Camille92** [comment]
nope :s

**Comment by bunde83** [comment]
FWIW - Same issue for me as well on latest:

# node K.js 
K.linux.57
19:5:7.265117 CF settings loaded from JSON file K OK.
node: symbol lookup error: /home/ubuntu/K/app/server/lib/K.linux.57.node: undefined symbol: _ZN1K12sqlite3_openENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPP7sqlite3

THANKS CARLES!!!!!!!!!!!

**Comment by ctubio** [comment]
i just finnished migrating all npm commands to make; ima spin a new fresh server and test this cos it doesnt happen in any computer i have, may take a bit to fix, meanwhile a solution is the last known good working version ee5e863a24b47382bd67198a3e1dc39366774c12, you can install with `$ git checkout ee5e863a24b47382bd67198a3e1dc39366774c12`

**Comment by Camille92** [comment]
Just an update, I ran a "clean" (removing K and redownloading it) and it doesn't work either :S

**Comment by ctubio** [comment]
sorry can you tell me exactly what operating system version are you using?
something liiike:
```
$ uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
```
(im not able to reproduce this today :S and wanna make sure im testing your exact situation)
thanks'¡

**Comment by jantb** [comment]
I also have the same error:

K.linux.57
20:27:52.647196 CF settings loaded from JSON file K OK.
node: symbol lookup error: /root/K/app/server/lib/K.linux.57.node: undefined symbol: _ZN1K12sqlite3_openENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPP7sqlite3

Here is the info you requested:
~/K# uname -a
Linux trader 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
~/K# cat /etc/issue
Ubuntu 16.04.2 LTS \n \l

~/K# node -v
v8.2.1
~/K# g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by ctubio** [comment]
ok many thanks for your time, i think i understood the problem xD will work on it on experimental branch instead of master
