### ISSUE TITLE
Quotes in memory bug

### ISSUE THREAD

**Issue by MrAdamo** [ctubio/Krypto-trading-bot#1042]
Hello,
I use windows and have the bot installed on docker.
While I was running the bot my electricity went out, after restarting the bot again I saw the quotes placed before stay always in "Waiting status update" the same thing happened when the container crashed while there were open orders left.
I had to cancel the orders manually from coinbasepro and after that the bot created working quotes again.
Also the history of trades is always empty even though there are some previous filled orders in coinbasepro.

**Comment by ctubio** [comment]
morniining'''
we do not cancel order on disconnect because we logon to coinbase with `8013 = N` (see https://docs.pro.coinbase.com/#logon-a)
