### ISSUE TITLE
HitBTC K v0.6.0+7 crashes randomly

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#1043]
Hi,

I recently upgraded to K-trading-bot v0.6.0+7 (build on linux-x86_64 at 2021-01-17 03:44:38) running on Debian 10.7

K keeps crashing after some time (usually 3-4 hours) without any log entry, the process just vanishes.

Any ideas? Prior versions ran fine.

Thanks,
Pat

**Comment by ctubio** [comment]
morniing''
are you using coinbase exchange?

**Comment by Pat71** [comment]
No, HitBTC.

**Comment by ctubio** [comment]
ookei
aaand no logs really? even while using `--naked` (and without attaching a screen running in the background)?

(if no logs im afraid i would not be able to do nothing and just close this issue :S)

**Comment by Pat71** [comment]
surprisingly, K is running now for 24 hours, so it seemed to be a temporary problem? Closing issue for the moment...
