### ISSUE TITLE
Pong in Web UI is reporting as Ping in K Output

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1045]
Could this be a problem with my database?
I have the bot on boomerang with -.5 Kmemory option to remove old pings/pongs.

**Comment by ctubio** [comment]
morniing'''
a filled order is a pong if there is a matching ping

a filled order is matching ping if another order filled in the other side exists with a margin higher than witdhPong, see:
https://github.com/ctubio/Krypto-trading-bot/blob/85f89f803f3065d21626dd11c52b99ecd80b2005/src/bin/trading-bot/trading-bot.data.h#L1317-L1319

i dont thing there is a chance for the logic to be wrong

**Comment by MiningInMySleep** [comment]
So does that mean that the web UI is just incorrect then when it marks the trades as Pongs?

**Comment by ctubio** [comment]
mm.. nope, i mean that there are not incorrect pongs. The pong was not a pong cos a matching ping was not found at the time of the a trade to become a ping or pong.
