### ISSUE TITLE
Trades per seconds works only on PING trades

### ISSUE THREAD

**Issue by eniware-org** [ctubio/Krypto-trading-bot#1049]
Is this intended?

**Comment by ctubio** [comment]
morniiing'''
is hard for me to understand this cos:

a trade is decided to be a PING or a PONG onces it is filled.

a trade is rate limited to be placed before it is placed.

there is no relation of nothing in between what happens before a trade is even placed and what happens after the trade is filled.

all trades are rate limited before they are placed.

a filled trade cannot be limited to be placed (my brain hurts xD).

**Comment by ctubio** [comment]
note that before a a trade is filled, the status of PING or PONG is a suggestion; the status will be again reconsidered once it is filled and will be PING or PONG based on the current history of previous trades.

while the order is sitll open, the status is suggested cos the price is expected to change, so the final status may be different (or also other trades may be filled before)

im not sure if you mean PING status in the open orders table or in the history of trades table or in the logs (on orders may change, but on trades and in the logs is what it is)

**Comment by ctubio** [comment]
mmm i think you are refering to:
https://github.com/ctubio/Krypto-trading-bot/blob/e19896d81d05f8a5d2683a808a418c66fcde3ea0/src/bin/trading-bot/trading-bot.data.h#L2456-L2465

maybe you are looking to remove or change the conditionals in the last lines of this function?
