### ISSUE TITLE
Question: Why are trades not sent with websocket if possible ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#105]
Hey Carles,

Just a question, why are trades not sent with websocket ? It's faster and there's no API limit on that channel (so no need to worry about API delay :) ).

**Comment by ctubio** [comment]
what exchange you mean? each exchange has its own reasoning

**Comment by Camille92** [comment]
Bitfi ! Because I think the cause of the 'STOPPED' and the implementation of API delay was because of bitfinex low limit right?

So I was thinking, if we don't use rest API at all and only Websocket, then there is no way to reach a limit because there is none :)

**Comment by ctubio** [comment]
Bitfinex uses websocket api v2 to send/cancel orders, see https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/gateways/bitfinex.ts#L240-L241

**Comment by Camille92** [comment]
Okay but then there is something I don't understand.
Where do we use REST then? and why?

And if we don't use REST then there is really no need for API delay on Bitfi right?

**Comment by ctubio** [comment]
solved in IRC channel; you're right
