### ISSUE TITLE
Negative Market Width (Bitfinex)

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1050]
This was reported last year I think, but I just had the bug where an order on the sell side got stuck in the bot's memory. Checking the actual order book on Finex showed no such order and it was causing a negative market width calculation within the bot itself because buy orders eventually came up above that level. Restarting fixed it, but there should be some kind of sanity check based off the opposing order book and/or recent orders.

**Comment by ctubio** [comment]
:koala: thanks for the explanation (and for reopen the issue), let me try to reproduce it

**Comment by MiningInMySleep** [comment]
You might have some trouble getting it to reproduce actually. I've never seen it before and I didn't have logging enabled so I don't have any info on exactly when it started either.

**Comment by ctubio** [comment]
:koala: next commit implements https://docs.bitfinex.com/docs/ws-websocket-checksum, so we can be sure we dont have an out of sync book
