### ISSUE TITLE
K-0.6.0.31-win64-x86_64 WS CURL connect Error

### ISSUE THREAD

**Issue by MrAdamo** [ctubio/Krypto-trading-bot#1051]
Hello,
I was running an old commit on windows for a couple of days and today I decided to upgrade the bot to the latest commit, but after installing it with `make reinstall` and restarting the bot I have this ssl error:

>02/01 15:16:55.460626 UI 1 client connected, last connection was from 127.0.0.1.
02/01 15:17:02.126143 GW COINBASE Warrrrning: WS CURL connect Error: Problem with the SSL CA cert (path? access rights?), reconnecting in 7s..
02/01 15:17:09.199301 GW COINBASE Warrrrning: WS CURL connect Error: Problem with the SSL CA cert (path? access rights?), reconnecting in 7s..
02/01 15:17:16.318526 GW COINBASE Warrrrning: WS CURL connect Error: Problem with the SSL CA cert (path? access rights?), reconnecting in 7s..
02/01 15:17:23.415171 GW COINBASE Warrrrning: WS CURL connect Error: Problem with the SSL CA cert (path? access rights?), reconnecting in 7s..
02/01 15:17:30.555545 GW COINBASE Warrrrning: WS CURL connect Error: Problem with the SSL CA cert (path? access rights?), reconnecting in 7s..
02/01 15:17:37.643254 GW COINBASE Warrrrning: WS CURL connect Error: Problem with the SSL CA cert (path? access rights?), reconnecting in 7s..

**Comment by ctubio** [comment]
see https://github.com/ctubio/Krypto-trading-bot/commit/78d1f8343443b6433c3d031cdc78f07db4404ac2 (the curl project changed the url of the cert)

a quick fix if you dont wanna upgrade should be:
```
 $ curl https://raw.githubusercontent.com/ctubio/Krypto-trading-bot/master/Makefile > Makefile
 $ make system_install
```

**Comment by ctubio** [comment]
:koala: new release at [K-0.6.0.32-win64-x86_64.tar.gz](https://github.com/ctubio/Krypto-trading-bot/releases/download/0.6.x/K-0.6.0.32-win64-x86_64.tar.gz)
