### ISSUE TITLE
PingAt "Depleted[bid|ask] Side Not Working

### ISSUE THREAD

**Issue by werkkrew** [ctubio/Krypto-trading-bot#1055]
When trying to use "DepletedAskSide" or "DepletedBidSide" as a "pingAt" option both sides of the market say "Waiting Ping"

---
```
app exchange: COINBASE/XLM/USD
app version: K-trading-bot v0.6.0+38 
OS distro: linux-x86_64
```

**Comment by ctubio** [comment]
because your tbp value is not allowing trades

play with yout tbp value and you will see for example sell trades when the bid side is depleted

**Comment by werkkrew** [comment]
Thanks for taking a look, I don't think it is due to tbp, for example if my
tbp is zero (allowing bot to sell) and I have plenty of the base position
asset, the depleted pingAt settings still result in the bot saying "waiting
ping" on both sides.

I will double check my settings, is there any logging I might look at to
help me troubleshoot?
