### ISSUE TITLE
Feature Request: Cancel trades only on traded pairs when reconnecting/restarting bot.

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1057]
Not super high priority, but currently bot cancels all orders regardless of what pairs the bot is actually trading on (I assume) reconnect/restart.

It would be nice to be able to manually trade other pairs by leaving orders in the book that don't get cancelled even if the bot is disconnected/restarted.

Edit: Perhaps have all orders submitted by K set to specific group ID and then Cancel Order Multi can be done with same group ID to not affect manually entered orders?

**Comment by ctubio** [comment]
:koala: on bitfinex you mean?

**Comment by MiningInMySleep** [comment]
Yes, I was specifically referring to Bitfinex, but it would be nice if it worked that way on other exchanges too. Binance in particular would be nice with the large variety of cryptos available.

**Comment by werkkrew** [comment]
+1 for this feature for Kraken (and Coinbase really).

I do some manual trading there and the bot cancels my open orders on other pairs.

**Comment by MiningInMySleep** [comment]
As an addition to this, I think it would be very useful if the bot did not automatically cancel manually submitted orders entered by the "Submit Order" button on the K web UI. I love not having to login to the exchange to place orders, but they disappear after every ping/pong.

**Comment by ctubio** [comment]
@MiningInMySleep maybe your issue is solved with `--dustybot` argument?

**Comment by MiningInMySleep** [comment]
It depends on which orders dustybot deletes. Personally, I think it would be best if the bot deleted all automatically created orders on exit, but any orders manually input via exchange UI or K web UI should not be removed (because they were manually created).

**Comment by ctubio** [comment]
:koala: now we dont have anymore `--dustybot` argument

(and soon maaaybe i will consider to remove the cancel all every 5min UI checkbox)

**Comment by nonkreon** [comment]
hiiii Carles,
I can see the arguments against cxl and respect everybody's decision to turn it off, but can we at least not remove it completely so I can keep it on? Without it I have zombie orders blocking funds as price moves away :(
![image](https://user-images.githubusercontent.com/3709448/109913350-cf8edc80-7c7b-11eb-8461-82f70e6820ee.png)

**Comment by ctubio** [comment]
:koala: i wish i knew why you have so many zombies; incoming revert'¡!

**Comment by nonkreon** [comment]
Luckily price retraced and the zombies that were bid after i cancelled
these were filled 😁😁
