### ISSUE TITLE
Incorrect valPing value in BITFINEX_MARGIN

### ISSUE THREAD

**Issue by eniware-org** [ctubio/Krypto-trading-bot#1058]
![image](https://user-images.githubusercontent.com/34030382/107856879-2777b780-6e23-11eb-8cd4-b424aa0fea9d.png)

**Comment by ctubio** [comment]
:koala: i think i will remove bitfinex margin instead of fixing it

**Comment by eniware-org** [comment]
IMHO, leave it for now as the bot can still be used to increase/decrease position. A bit awkward, but there is a use case. With the usual warnings, of course.

**Comment by ctubio** [comment]
:koala: but but having broken stuff is not fun

**Comment by ctubio** [comment]
mm the plan finally i think will be to support bitfinex margin but in another bot more simple

**Comment by eniware-org** [comment]
Let me know if I could be of any help!
