### ISSUE TITLE
Question about decimals

### ISSUE THREAD

**Issue by Jorman** [ctubio/Krypto-trading-bot#106]
Hi, on USD/BTC no problem, the price is so high that is not a problem, but on crypto I don't know where I can set the decimal precision.

But on pairs like XRP/BTC the actual price is 0.00006676 but the the bot place order at 0.00008 and 0.00007
I can't find a settings to set up the decimals precision.

Jo

**Comment by ctubio** [comment]
https://github.com/ctubio/Krypto-trading-bot/search?utf8=%E2%9C%93&q=round&type=

**Comment by Jorman** [comment]
Hi @ctubio 
I see a lot of function, I've to edit each one and recompile? Or there's another way?
My intent is only to use all 8 decimals and not round to 5, on javascript is simple .toFixed(8) but here I don't know

**Comment by ctubio** [comment]
yea modify at your willing and when done just `make install` again to recompile all

**Comment by Jorman** [comment]
Tnx!
But I don't know what is the right file to modify and for now I don't know how to set the decimal position, I think in some way is already set to 5 but I can't find it

**Comment by ctubio** [comment]
maybe the best is to try and see what happens, i dont think that you will finnish all you wanna do in the very first attempt, so as soon as you start trying as soon you will arrive to the final stage of your idea.

![star-trek-memes-so-nerdy-youll-need-a-tricorder-to-read-them-43-photos-24](https://user-images.githubusercontent.com/1634027/28689205-1b8ece70-7315-11e7-9b14-f37d5ab94bfc.jpg)

**Comment by Jorman** [comment]
I'm not a programmer I don't wanna make a mess.
I only see the orders are placed with this 5 decimal round. The code is not mine so I don't know where, maybe the order is rounded before placing, maybe during.
But never mind I try to see into the code. I don't think to never find to solution.
what do you think about this files?
/src/server/gateways
here I see the coinbase have `size: order.quantity.toFixed(8)`
and poloniex have `amount: order.quantity`
Maybe is only a poloniex "problem"

**Comment by ctubio** [comment]
you need to modify more than 1 single line of code (in multiple files at `src/server`, `src/server/gateway`. src/client` and `src/lib` folders to be able to change the calculation in all places as you desire

usualy non-programmers pay to programmers to get stuff done

**Comment by Jorman** [comment]
@ctubio 
You're perfectly right. Is right to ask money to get stuff done.

In my opinion your program is really good and I wanna contribute, if the bot works good and for that I see is very good, and I can have some profit, I can also contribute with some coins.

I have only 0.031btc and I'm trying to learn some to gain some and for now on poloniex I loss some for now I started with 0.035, I think poloniex is not "good" like others exchange. I read a post where you say that you're not interested to "fix" polo for free, so for this I think is not "full working" but maybe I'm wrong.
You're the owner and you're the programmer, so you make the decision, please don't be offended of my words, I think, if some exchange is not right working why keep it?
In my opinion, the decimal precision is a kind of leak, because many market out there (not on all exchange) have a good volume and great possibility but with this "decimal problem" make all not usable

Man you can make a price to see if I can, I don't think but try

Anyway tnx like always for your support

**Comment by Camille92** [comment]
Hi @Jorman just been reading your post I don't comment on the issue because I don't know how it works but in a few words.

You're going to lose money on Polo with K and the amount of money you have.

You need to aim for a spread of 0.3% to start making money (not taking into account the risk factor or price movement) and that is very rare on Polo's big markets.

**Comment by Jorman** [comment]
Hi @Camille92 I always thanks who reply, I hope to learn some every times.
This because of fee? I don't know if I can set it up on K, I see pingWidth and pongWidth both set to 2 and when a pong was complete I see Kdiff at 0.26$ I think is the gain for this ping-pong
0.3% on btc/usd with the actual price is about $8.5 right?

For those I ask to expand to the full 8 digits decimal, IMHO many pairs have good volume to take some out, but maybe I'm wrong

If I don't abuse on your patience, you have any advice? There's a place to learn some to run the bot in a better way and understand some?

**Comment by ctubio** [comment]
sorry i didnt understood very well; can you please:

show what is the market and the currency pair affected.
show what is the current value.
show what is the new value you would like.

for example, you could say:
```
 okcoin:
- pair: btc_usd
- minTick: 0.00100000
- minSize: 0.01000000
minTick okcoin btc_usd should be 0.0999, minimum size okcoin btc_usd is ok as-is
```

^this way i can get brain in place quick; or are you looking to put 8 decimals in all Poloniex markets?

**Comment by Jorman** [comment]
Tnx, I try to explain better the situation. Sorry if I don't use all technical words but I do the best I can with my knowledge

Some markets like Poloniex, HitBTC, and maybe others, have a lot of pair to trade, not only btc/usd, but for example btc/xrp or btc/dash or btc/eth, all market with a good volume.

So I'll take for example btc/xrp the 1st screen is from the bot
![screen](https://user-images.githubusercontent.com/5203988/28751901-807944b4-7513-11e7-8d33-4e566a8f5a23.PNG)
This is from the Poloniex
![screen2](https://user-images.githubusercontent.com/5203988/28751903-94b660b0-7513-11e7-947c-9c6702941777.PNG)

minTick is the spread right?

From the 1st scree:
I see the Fair Value on bot and is 0.00007000
I see the bidPrice and askPrice and is 0.00006000

But if I look at the market, in this case Poloniex I see:
on sell orders price like 0.00006196, 0.00006199 and so on
And when the bot place an order, this order is always like 0.00006000

Maybe I'm wrong and the bot do the calc in the right way but to me seems that the bot round all and take only the first 5 decimal position, but the decimal for the crypto is 8
On market like usd/btc or when the price is high this's not a problem but on pairs with low price can be a problem, because the bot can't enter on the market 

Maybe I miss some extra motivation and I don't know exactly how the bot works, for this I ask fist!

So, is possible to have an option to set up how many decimal use? or is more simple and quick tell to the program to use always all the 8 decimal for all the crypto in all market?

I hope to have explained myself better.
