### ISSUE TITLE
Bitfinex: XXX/BTC Pairs out-of-sync

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1060]
Seeing some strange behavior with eth/btc and xmr/btc pairs where order book is constantly going out of sync.
The same doesn't seem to happen on USD pairs. For example: btc/usd, eth/usd, xmr/usd.

**Comment by ctubio** [comment]
many thanks for the report'''

the book checksum of bitfinex is certainly a joke (or a festival of decimals in diferent formats), let me check out what is going on in those pairs and fix it or remove the checksum

**Comment by ctubio** [comment]
err.. im on btc/usd on bitfinex and all is fine since days ago

allow me to ask, are you using the latest release?

**Comment by MiningInMySleep** [comment]
Not BTC/USD.  XXX/BTC pairs such as ETH/BTC and XMR/BTC are showing this behavior.

**Comment by ctubio** [comment]
:koala: ooh okok many thanks again for all the info; i will rereview thiz afternoon ETH/BTC and XMR/BTC
