### ISSUE TITLE
KuCoin: Manual Orders Doubling

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1061]
Not sure if it's the same for automated orders since I don't use them for this exchange, but it looks like the orders are getting doubled for manually entered trades.

![putty_2021-02-16_20-18-00](https://user-images.githubusercontent.com/34825846/108056072-2a2d1380-7094-11eb-97af-f63d34702854.png)

Also the trade log seems incorrect as well:
![chrome_2021-02-16_20-19-24](https://user-images.githubusercontent.com/34825846/108056173-4af56900-7094-11eb-8aca-9d00dfff5dea.png)

**Comment by ctubio** [comment]
:koala: umf my bad, thank you for the report''''

**Comment by ctubio** [comment]
sorry this was fixed at https://github.com/ctubio/Krypto-trading-bot/commit/5e81237d4841fadb92b84f5b6e8d6d9c1aa94b54
