### ISSUE TITLE
Question about how to configure min and max value orders properly

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [ctubio/Krypto-trading-bot#1065]
Question:

Considering that we are targeting, for example, a pair like `ETH/BRL` on Binance,
where it has there a minimum order size of 10 BRL.

If we would like to configure the bot to create orders with at least 10 BRL and no more than, let's say, 30 BRL,
is the correct approach to configure the bot like this?

- Use `--min-size 10` when starting the bot
- Configure `bidSize` and `askSize` on the UI with `30` and `30` respectively?

One other question that I'd like to ask, are the `bidSize` and `askSize` always based on BTC or in the targeting pair? (BRL for this case)

Thanks in advance :)

**Comment by ctubio** [comment]
please note --min-size is used to set the custom minimum order size; and "minimum" here is an important word

another thing is the order size, that is a fixed value, not variable between 2 other values

"minimim" meaning as in the exchange market limits; the amount below what you get errores cos is too small
