### ISSUE TITLE
bwSize minimum should be equal to minSize

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1067]
Currently on BTC/USD on Bitfinex trying to set bwSize to 0.0008 (the current minSize is 0.0002) but the field turns red indicating that there is an error. Is this just a graphical UI error or is it actually stopping bwSize setting from working?
![chrome_2021-02-24_19-24-59](https://user-images.githubusercontent.com/34825846/108986924-0b530080-76d6-11eb-951b-5181741a7d71.png)

**Comment by ctubio** [comment]
morniiing'''
if you save a -1 you will see the minimum bwSize allowed value is 0 (not equal no any value)

if you refresh the page you can see the value is saved, so is working yea (is just a graphical UI error)

if you use the arrows you will see the steps of this field, i presume your value is lower than the step of each increment

:koala: hope this helps''
