### ISSUE TITLE
make install failed

### ISSUE THREAD

**Issue by untamedone** [ctubio/Krypto-trading-bot#107]
Tried to make the latest version and it fails when it gets to libpng.

```
test -d build/libpng-1.6.31 || (curl -L https://github.com/glennrp/libpng/archive/v1.6.31.tar.gz | tar xz -C build && cd build/libpng-1.6.31 && ./autogen.sh && ./configure --prefix=/home/untamed/K/build/libpng-1.6.31 && make && sudo make install) && cp lib/libpng16* ../../app/server/lib
cp: cannot stat 'lib/libpng16*': No such file or directory
Makefile:244: recipe for target 'png16' failed
make[3]: *** [png16] Error 1
make[3]: Leaving directory '/home/untamed/K'
Makefile:106: recipe for target 'dist' failed
make[2]: *** [dist] Error 2
make[2]: Leaving directory '/home/untamed/K'
Makefile:132: recipe for target 'packages' failed
make[1]: *** [packages] Error 2
make[1]: Leaving directory '/home/untamed/K'
Makefile:142: recipe for target 'install' failed
make: *** [install] Error 2

```

**Comment by ctubio** [comment]
i think i fixed in the latest commits, can you run "make png16" and try again?

**Comment by ctubio** [comment]
if doesn't fixes it noworry to much, im currently rereviewing it

**Comment by untamedone** [comment]
```
make png16
test -d build/libpng-1.6.31 || (curl -L https://github.com/glennrp/libpng/archive/v1.6.31.tar.gz | tar xz -C build && cd build/libpng-1.6.31 && ./autogen.sh && ./configure --prefix=/home/untamed/K/build/libpng-1.6.31 && make && sudo make install) && cp lib/libpng16* ../../app/server/lib
cp: cannot stat 'lib/libpng16*': No such file or directory
Makefile:244: recipe for target 'png16' failed
make: *** [png16] Error 1
```

**Comment by ctubio** [comment]
try `make latest`

**Comment by untamedone** [comment]
Ok it is fixed. Thanks :)

**Comment by milezzz** [comment]
`make[4]: Entering directory '/var/www/K'`
`test -d build/libpng-1.6.31 || (curl -L https://github.com/glennrp/libpng/archive/v1.6.31.tar.gz | tar xz -C build && cd build/libpng-1.6.31 && ./autogen.sh && ./configure --prefix=/var/www/K/build/libpng-1.6.31 && make && sudo make install)`
`cp build/libpng-1.6.31/lib/libpng16* app/server/lib`
**`cp: cannot stat ‘build/libpng-1.6.31/lib/libpng16*’: No such file or directory`**
`Makefile:235: recipe for target 'png16' failed`
`make[4]: *** [png16] Error 1`

I have the same issue. Can anyone shed some light on how to fix? Was so excited to try this!

It's right in that `build/libpng-1.6.31/lib/libpng16` does not exist. My system is Debian with Nodejs v8.4:

`3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
milezteg@anons:/var/www/K$ cat /etc/issue
Debian GNU/Linux 8 \n \l`

**Comment by ctubio** [comment]
try `make reinstall`

**Comment by milezzz** [comment]
Yes, same result. 

`cp build/libpng-1.6.31/lib/libpng16* app/server/lib`
`cp: cannot stat ‘build/libpng-1.6.31/lib/libpng16*’: No such file or directory`

**Comment by milezzz** [comment]
It's the ./autogen script that is failing in libpng16:

``autoreconf failed: your version of autotools is incompatible
with this libpng version.  Please use a distributed archive
(which includes the autotools generated files) and run configure
instead.``

Running ./configure results in:
`/var/www/K/build/libpng-1.6.31$ ./configure`
`-bash: ./configure: No such file or directory`

**Comment by ctubio** [comment]
you can edit the Makefile and remove all references to png in case you successfully install it manually if is bothering you the automatic install

**Comment by marciogranzotto** [comment]
Hi, I'm having the same problem.
