### ISSUE TITLE
Expose "lifetime" in WebUI

### ISSUE THREAD

**Issue by oorzkws** [ctubio/Krypto-trading-bot#1078]
Depending on the market and situation, this setting can be as essential for tweaking as the other values exposed in the Web UI -- I would say that having it there is worthwhile if you feel there is room.

---
```
app exchange: undisclosed
app version: undisclosed
OS distro: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
:koala: make sense, thank you for the suggestion''''

**Comment by ctubio** [comment]
ok so to not have the same value defined in two places (cos then is not clear what value is in use and what value is ignored), the argument will be used as a minimum (and default) value for the UI value

**Comment by oorzkws** [comment]
That's a good idea. Thanks for implementing it so quickly! ❤️
