### ISSUE TITLE
TBP stay at 0

### ISSUE THREAD

**Issue by Zep18** [ctubio/Krypto-trading-bot#108]
Hey there, 

I'm trying to make your bot work with GDAX, so, I've run the Dockerfile after editing with my settings : 
FROM node:7
RUN apt-get update

RUN apt-get install -y git sudo

# Feel free to choose the branch you want to build:
RUN git clone -b master https://github.com/ctubio/Krypto-trading-bot.git K

WORKDIR K

# Remove the ssl certificate (GUI accessible over plain HTTP, not recommended):
#RUN rm -rf dist/sslcert

RUN make docker

EXPOSE 3000 5000

# General config properties. Replace with your own exchange account information:
ENV BotIdentifier autobot #1
ENV EXCHANGE coinbase
ENV TradedPair BTC/EUR
ENV WebClientUsername **XXXXX**
ENV WebClientPassword **XXXXX**
ENV WebClientListenPort 3000
ENV MatryoshkaUrl https://localhost

# Set options only for your desired EXCHANGE:

## Coinbase GDAX
ENV CoinbaseRestUrl https://api.gdax.com
ENV CoinbaseWebsocketUrl wss://ws-feed.gdax.com
ENV CoinbasePassphrase **XXXXX**
ENV CoinbaseApiKey **XXXXX**
ENV CoinbaseSecret **XXXXX**
ENV CoinbaseOrderDestination Coinbase

## Quoting Parameters
ENV delayUI 3

CMD ["node_modules/.bin/forever", "K.js"]

Then I lauched the container :
docker run -p 5001:5000 -p 3001:3000 --name Kjs -d kjs

The first bug I encoutered was stunnel, so docker exec  "containerID" /bin/bash, and inside : "stunnel dist/K-stunnel.conf"

In the log : coinbase FIX Logon Connected  👏 

But, on the UI, nothing happen, I have funds on my gdax account (BTC & EUR), but the TBP stay at 0.

I also notice 2 "strange" lines in the logs :  stdev Unable to compute value and  tbp recalculated 0

Full logs : 

```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
K.linux.51
19:28:29.352886 DB /data/db/K.3.0.2.db loaded OK.
19:28:29.356425 UI ready over HTTPS on external port 3000.
19:28:30.6967 GW coinbase allows client IP.
19:28:30.793 GW coinbase:
- autoBot: yes
- pair: BTC-EUR
- minTick: 0.01000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
19:28:32.893 coinbase FIX Initiator Start
19:28:32.906 coinbase FIX Logon Disconnected
19:28:33.438 stdev Unable to compute value
19:28:36.713 main Event loop delay 2800ms
19:28:36.714 stdev Unable to compute value
19:28:36.990229 UI authorization success from ::ffff:37.167.32.151
19:28:40.096 main Event loop delay 2400ms
19:28:40.096 stdev Unable to compute value
19:28:42.801 main Event loop delay 2200ms
..
19:28:47.994 main Event loop delay 500ms
19:28:48.362642 1 UI currently connected, last connection was from ::ffff:37.167.32.151
19:28:49.973 main Event loop delay 300ms
..
19:28:53.808 main Event loop delay 300ms
19:28:54.109 coinbase FIX Logon Disconnected
19:28:55.359 main Event loop delay 500ms
...
19:29:12.626 main Event loop delay 200ms
19:29:14.785 coinbase FIX Logon Disconnected
19:29:17.829 main Event loop delay 400ms
...
19:29:32.137 main Event loop delay 300ms
19:29:32.911 tbp recalculated 0
19:29:33.346 main Event loop delay 700ms
19:29:34.178 main Event loop delay 300ms
...
19:29:36.393 main Event loop delay 400ms
19:29:36.601 coinbase FIX Logon Disconnected
19:29:38.448 main Event loop delay 300ms
19:29:39.749 main Event loop delay 300ms
...
19:29:57.157 main Event loop delay 400ms
19:29:57.393 coinbase FIX Logon Connected <--- when i enter stunnel dist/K-stunnel.conf
19:29:57.393777 GW coinbase Changed quoting state to Enabled.
19:29:58.444 main Event loop delay 300ms
```

**Comment by Zep18** [comment]
![image](https://user-images.githubusercontent.com/10077707/28734068-63e05dd6-73df-11e7-9963-d5bf7f971ea6.png)

**Comment by ctubio** [comment]
it seems there is no wallet data, if you already did a manual trade using the webside of gdax (so you validated that your account is verified and able to trade on gdax), try to double check if you api key have enough permissios to see your wallet balances.

**Comment by Zep18** [comment]
Key have view, manage and trade permissions, not enough ? 
And I have already trade with this account

**Comment by ctubio** [comment]
try instead `view`, `trade` and `transfer` permissions

**Comment by Zep18** [comment]
Thanks for the quick answer

Did it, Still the same 

I'll try with "by pass 2fa" checked Tomorrow 
I can also select a profile when creating the key : default or btc-eur-margin, which one should I use ?

**Comment by ctubio** [comment]
`default` i have, with  `view`, `trade` and `transfer` permissions

**Comment by untamedone** [comment]
Make sure your system time is synced, it will timeout requests and not get the wallet data.

**Comment by Zep18** [comment]
Tried both, still this  " tbp recalculated 0"

```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
K.linux.51
17:11:1.41117 DB /data/db/K.3.0.2.db loaded OK.
17:11:1.44199 UI ready over HTTPS on external port 3000.
17:11:1.737632 GW coinbase allows client IP.
17:11:1.737731 GW coinbase:
- autoBot: yes
- pair: BTC-EUR
- minTick: 0.01000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
17:11:04.688 coinbase FIX Initiator Start
17:11:04.696 coinbase FIX Logon Disconnected
17:11:05.198 stdev Unable to compute value
17:11:5.355790 1 UI currently connected, last connection was from ::ffff:37.165.87.173
17:11:09.437 main Event loop delay 3700ms
17:11:09.438 stdev Unable to compute value
17:11:13.396 main Event loop delay 3000ms
17:11:13.396 stdev Unable to compute value
17:11:16.680 main Event loop delay 2800ms
17:11:23.648 main Event loop delay 300ms
17:11:24.990 main Event loop delay 300ms
17:11:25.731 coinbase FIX Logon Connected <-- Here I do "stunnel dist/K-stunnel.conf"
17:11:25.731463 GW coinbase Changed quoting state to Enabled.
17:11:29.042 main Event loop delay 500ms
17:11:31.644 main Event loop delay 300ms
...
17:12:02.160 main Event loop delay 300ms
17:12:03.444 main Event loop delay 300ms
17:12:04.670 tbp recalculated 0
17:12:05.375 main Event loop delay 900ms
```

They are funds on my Gdax account :
![image](https://user-images.githubusercontent.com/10077707/28746846-89e395f8-7492-11e7-87e6-c4aaefa35ede.png)


Is there a way to change the key without havind to rebuild the entire Docker image ?
What can I've miss in the conf ?
Thx

**Comment by ctubio** [comment]
set environment variable with name equal to the config option name you wanna set

**Comment by ctubio** [comment]
i would recommend to not use Docker, is more like for demo proposes, not for production usage

**Comment by Zep18** [comment]
Okey, did manual install, almost there, the last bug I have is that it's stay at "Connecting to exchange" 

Where can I see logs with manual install ?

![image](https://user-images.githubusercontent.com/10077707/28756310-238e9f8e-756c-11e7-9687-272998429721.png)

**Comment by ctubio** [comment]
to see the logs run `node K` insterad of `make start`

**Comment by Zep18** [comment]
yep ofcourse.. 

Weeelll now I have the "coinbase FIX logon disconnected" , but stunnel is already running, stop and restart it doesn't fix the probleme.. I think I'll never be able to make it run correctly ^^

```
cat /var/log/syslog gives me this kind of messages : 
vps436691 stunnel: LOG5[10896]: Service [gdax_stream] accepted connection from 127.0.0.1:35098
vps436691 stunnel: LOG5[10896]: s_connect: connected 34.196.223.137:4198
vps436691 stunnel: LOG5[10896]: Service [gdax_stream] connected remote server from myip:53781
stunnel: LOG5[10896]: Certificate accepted at depth=0: C=US, ST=California, L=San Francisco, O="Coinbase, Inc.", CN=*.gdax.com
stunnel: LOG5[10896]: Connection closed: 195 byte(s) sent to SSL, 149 byte(s) sent to socket

```

**Comment by ctubio** [comment]
maybe you apikey in gdax doesn't have all the permissions required? can you check if there is any permission unchecked in your gdax apikey?

im not sure what else can be otherwise

**Comment by Zep18** [comment]
Yep, that was it, I had view, trade and transfer without 2FA, now  I checked all and it's working
Thank you for your quick support !
