### ISSUE TITLE
KRAKEN Quote status: Disconnected, no orders being placed

### ISSUE THREAD

**Issue by oorzkws** [ctubio/Krypto-trading-bot#1084]
WebUI shows "disconnected" above the order book, console shows quoting status as connected. No new orders are placed, wallet data is present, pings/pongs from previous runs present.

If I remove the contents of /var/lib/K/db/, it will work for one session.
![image](https://user-images.githubusercontent.com/65210810/110431423-b33cd680-80a5-11eb-81bb-1fcb9aafd371.png)

---
```
app exchange: KRAKEN/XXBT/USD
Local running version: ba74968fe2a5d588d3792e0fcf61bce501387724
Latest remote version: ba74968fe2a5d588d3792e0fcf61bce501387724
OS distro: fedora 32
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by oorzkws** [comment]
I have it narrowed down to it happening when I import my config. Doing a diff from stock settings, I have it down to one of the following. More testing after sleep probably.
```
{
  "aprMultiplier": 1,
  "audio": true,
  "bestWidthSize": 0.1,
  "buySize": "0.01",
  "cleanPongsAuto": 3,
  "delayUI": 10,
  "positionDivergence": 0.01,
  "profitHourInterval": 36,
  "quotingStdevBollingerBands": true,
  "range": 0.01,
  "sopSizeMultiplier": 4,
  "sopTradesMultiplier": 5,
  "targetBasePositionPercentageMax": 35,
  "targetBasePositionPercentageMin": 15,
  "tradeRateSeconds": 10,
  "tradeSizeTBPExp": 1.25,
  "tradesPerMinute": 2,
  "widthPing": "52",
  "widthPingPercentage": 0.001,
  "widthPong": "52"
}
```

**Comment by ctubio** [comment]
:koala: soo to allow me to reproduce this, the main problem is that after saving the quoting parameters for the first time then new orders are not placed?

**Comment by oorzkws** [comment]
Correct, sort of - the issue only crops up after restarting the bot. So start bot, save settings, restart

**Comment by oorzkws** [comment]
I was thinking about it and should mention I was still launching the bot with --lifetime=90000

**Comment by ctubio** [comment]
umf im sorry, somehow certainly the disconnected status remain as disconnected after connecting to kraken; i had updated it as all other exchanges to be set as connected as soon as the websocket starts replying (before was only set as connected after the first book snapshot message)
