### ISSUE TITLE
UI Hangs in browser. Can't access elements from inspector

### ISSUE THREAD

**Issue by nithi2023** [ctubio/Krypto-trading-bot#1085]
I am trying to contribute by upgrading its UI (CSS improvements).  but UI is hangs even if no trades are happening (disconnected state). Please let me know why this is happening and any way to resolve it? 

Thanks

**Comment by ctubio** [comment]
:koala: sorry what means hangs?

**Comment by nithi2023** [comment]
If you press F12 and try to select element In the document tree, browser should highlight the element in the view and should show related css on right. But the web page hangs  completely.

**Comment by ctubio** [comment]
:koala: for me the browser only hangs if i inspect the client.min.js file (the solution is to inspect the js file unziped and unminimized so the browser doesnt gets mad).

about css or html inspections i never had any issue

**Comment by nithi2023** [comment]
I use Binance BTC/USDT.

I am currently using `make ` to recompile the .ts files. 
Is there is anyway I can compile only css and js files?

**Comment by ctubio** [comment]
to compile just the assets is:
```
make assets KSRC=trading-bot
```
and to compile the compiled assets (and the c sources) into an executable is:
```
make src KSRC=trading-bot
```
you can do both with:
```
make trading-bot
```
just `make`  compile all for all bots for your platform, and `KALL=1 make` compile all for all bots for all platforms

:koala: there are more targets and combinations but i think thats what you are looking for
