### ISSUE TITLE
QE Warrrrning: Unable to calculate TBP, missing wallet data error on Binance

### ISSUE THREAD

**Issue by foxxcrypto** [ctubio/Krypto-trading-bot#1089]
I am trying to trade on BINANCE, the BTC / USDT pair, the perpetual futures on bitcoin, but despite having balance in the wallet I get the following error : QE Warrrrning: Unable to calculate TBP, missing wallet data.

**Comment by ctubio** [comment]
:koala: im sorry only markets with `isSpotTradingAllowed = true` are supported, see https://api.binance.com/api/v3/exchangeInfo and:
https://github.com/ctubio/Krypto-trading-bot/blob/7f05f027fd4be6d6387b30ba4699101048aacda9/src/lib/Krypto.ninja-apis.h#L588

**Comment by foxxcrypto** [comment]
Sorry, 
so binance is not supported at all? so the wallet is not displayed correctly but the bot works anyway or the bot doesn't work at all? thank you

**Comment by ctubio** [comment]
what is not supported at all is future and margin markets.

the bot works with binance spot markets.

**Comment by nithi2023** [comment]
@ctubio This happens when I run two instance with binance. (BTC/USDT and ETH/BUSD). I even have balances (but, less than min. trade size) on both side.
