### ISSUE TITLE
lifetime on WebUI Reverting on Save

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1094]
There seems to be an issue with lifetime setting on web UI reverting to previous value when attempting to set a new value. It was working before, but maybe something in the recent updates broke it?

**Comment by eniware-org** [comment]
If you remove the parameter from the K.sh it no longer overrides it on save. Hope this helps!

**Comment by ctubio** [comment]
thank you @eniware-org

(yea, the value of **--lifetime** parameter is used as a minium value for the quoting parameter)
