### ISSUE TITLE
uummm.....help me understand this behavior  (order times)

### ISSUE THREAD

**Issue by Corfucinas** [ctubio/Krypto-trading-bot#1096]
@ctubio 
I only intend to put `pings` at `bid size`, 1 trade every 900 seconds and sell them at `short ping aggressive`, even if the FV moved against me, I only wish to sell at a profit the latest `ping`...not sure why it went like this and just went crazy on both sides.

Settings

![image](https://user-images.githubusercontent.com/53630064/113153885-16b3c180-926a-11eb-98da-0f64f5cef3a5.png)

Logs
![image](https://user-images.githubusercontent.com/53630064/113154245-68f4e280-926a-11eb-8c49-f184c5761112.png)

UI

![image](https://user-images.githubusercontent.com/53630064/113153994-2b905500-926a-11eb-8570-d2e547c8af63.png)

**Comment by eniware-org** [comment]
This is connected to the issue https://github.com/ctubio/Krypto-trading-bot/issues/1047#issue-794406528
The bot erroneously treats your orders as pings and there is no Max Trades per seconds for PONG. 
There is a further discussion here:  https://github.com/ctubio/Krypto-trading-bot/discussions/1069#discussion-3238533

**Comment by Corfucinas** [comment]
@eniware-org 

Only affects `boomerang`? I'm noticing something weird, the balance in your wallet goes to 0 from pings if the FV moves against you

ie:

You buy 1 at $10, pong at $11
FB is now $9, you hold "0" in your wallet balance
`pings and pongs do not respect the time and will eat the entire wallet in both sides when possible`
Also, this seems to happen once all pings are matched

**Comment by eniware-org** [comment]
Affects all - see here: https://github.com/ctubio/Krypto-trading-bot/blob/a9ce28ef802fde1837bbda275823a5a46450c5b6/src/bin/trading-bot/trading-bot.data.h#L2458

**Comment by Corfucinas** [comment]
@eniware-org 

Is this something related...?

![image](https://user-images.githubusercontent.com/53630064/113172419-ff310480-927a-11eb-9040-efa5f5b809dd.png)



I just bought with `pingpong` and ping at `BidSide`...the ping is respecting the trade time limit, but my wallet shows 0...and depleted funds

**Comment by Corfucinas** [comment]
@ctubio 

Hola! Como vas? 

Any updates in regards of this ? :<

**Comment by ctubio** [comment]
im trying hard to reproduce this on binance and on bitfinex; i had copied your quoting parameters aaaaand.. hope for it to be reproduced :S (if you have any other hint of how this may be reproduced please lemme know)

thanks for insist on this''

**Comment by ctubio** [comment]
:koala: somehow i reproduced it (but with a few trades instead of so many like you; hope we are infront of the same situation, lemme understand it and provide a fix); seems ping traders are wrongly considered pongs for a brief timespan while another trade has been super recently filled; i suspect the timer each 1 second calculating stats is not fast enough while also filling orders :man_dancing: a bad solution in the worst scenario is to just add a delay somehow after trades are done, to avoid further imminent trades get tangled statuses before stats are reprocessed, but lemme spend some time looking for a faster non-delayed solution

**Comment by eniware-org** [comment]
Excellent! Thank you very much for resolving this @ctubio !
