### ISSUE TITLE
Missing release K-0.6.0.57

### ISSUE THREAD

**Issue by eniware-org** [ctubio/Krypto-trading-bot#1097]
Hi @ctubio. I am missing release 0.6.0.57 in Github and cannot `make install`
Am I right to think this was the last release to support BITFINEX_MARGIN?
I would like to use the latest bot with BITFINEX_MARGIN. Is this possible at all?

**Comment by ctubio** [comment]
i can confirm v0.6.0.57 is not on github anymore

im sorry about margin trading im still not interested into messing around with it
