### ISSUE TITLE
Error when trying install

### ISSUE THREAD

**Issue by ipxs123** [ctubio/Krypto-trading-bot#1099]
I get this error when trying make install 
    1  x86_64-linux-gnu
     2  arm-linux-gnueabihf
     3  aarch64-linux-gnu
     4  x86_64-apple-darwin17
     5  x86_64-w64-mingw32

(Hint! uname says "MSYS_NT-10.0-18363 x86_64")

[1\2\3\4\5]: 5
make[1]: Entering directory '/home/atmos/K/K'
curl -L https://github.com/ctubio/Krypto-trading-bot/releases/download/0.6.x/K-0.6.1.25-win64-x86_64.tar.gz | tar xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0tar.exe: Error opening archive: Failed to open '\\.\tape0'
100   636  100   636    0     0   1322      0 --:--:-- --:--:-- --:--:--  1325
  0 10.7M    0 66000    0     0  66265      0  0:02:50 --:--:--  0:02:50  181k
curl: (23) Failure writing output to destination
make[1]: *** [Makefile:195: download] Error 1
make[1]: Leaving directory '/home/atmos/K/K'
make: *** [Makefile:231: install] Error 2

![Untitled](https://user-images.githubusercontent.com/78660885/114666193-a2b3f780-9d06-11eb-87e4-bbe3505bd9f3.png)

**Comment by ctubio** [comment]
:koala: i donno what is tape0 but is not writable, maybe another install path works better?

**Comment by biyian** [comment]
Getting the same thing testing on windows when running make install. It looks like the tar cmd is missing the -f argument.

**Comment by ctubio** [comment]
why would you want to specify a filename with -f argument? the file comes piped from curl

**Comment by ctubio** [comment]
if you get "Error opening archive: Failed to open '\.\tape0'", see https://github.com/ctubio/Krypto-trading-bot/issues/1099#issuecomment-821911088

**Comment by biyian** [comment]
Not sure why but others are having the same issue with other trying to use tar on windows and that for whatever reason fixed it. I was able to fix it by running.

pacman -S make gettext base-devel

**Comment by ctubio** [comment]
oh, thank you for the info; let me retry the install as of today and see this `pacman -S make gettext base-devel`
