### ISSUE TITLE
make trading-bot error:  build-linux-x86_64/lib/K-linux-x86_64.1.a: No such file or directory

### ISSUE THREAD

**Issue by v-byte-cpu** [ctubio/Krypto-trading-bot#1100]
I try to compile source code using the following commands

```
make dist
make trading-bot
```
`make dist` command completes successfully, but `make trading-bot` command fails with an error:

```
x86_64-linux-gnu-g++: error: build-linux-x86_64/lib/K-linux-x86_64.1.a: No such file or directory
```

How can I build  `K-linux-x86_64.1.a` ?

**Comment by ctubio** [comment]
:koala: did you run `make install` first?

**Comment by v-byte-cpu** [comment]
@ctubio I was researching Makefile and found that precompiled binaries were being downloaded; just wanted to find out if this project is proprietary or open-source. Too bad it is not open source.

**Comment by ctubio** [comment]
you did not discovered nothing, that is public information.

https://github.com/ctubio/Krypto-trading-bot/blob/a9ce28ef802fde1837bbda275823a5a46450c5b6/Makefile#L11-L15

**Comment by v-byte-cpu** [comment]
> licensed by/under the law of my grandma (since last century), feel free to crack all as you need.
To be honest, it sounds more like a joke. 

I was considering contributing to this project, but since it is impossible to build a fully functioning system from open source alone, this project is no better than lame corporate software, it is not open source. without closed-source `K-linux-x86_64.1.a` open source code in this repository is useless. I'm sure many open source developers have the same opinion. Moreover, how can anyone be sure you don't inject droppers into this proprietary lib without reverse engineering ?

**Comment by ctubio** [comment]
sorry let me lol

use --help of read the readme  or makefile file:


             This is free software: the UI and quoting engine are open source,
             feel free to hack both as you need.

             This is non-free software: built-in gateway exchange integrations
             are licensed by/under the law of my grandma (since last century),
             feel free to crack all as you need.

i cannot put it more clear

the gateways are not opensource; if you want the sources of the APIs make it yourself or ask to my grandma (yea is a joke; you should do yourself)

what is opensource here is the UI and the quoting engine

what is private is 4 stupid damn functions that you can see all de details about while reading the documentation of each exchange

all private logic is really public in the documentation of each exchange, you can certainly do yourself

if you bother to read the source, this is the only private source:
https://github.com/ctubio/Krypto-trading-bot/blob/950e52ace728e891e89940252e8b7d963b8df604/src/lib/Krypto.ninja-apis.h#L217-L225

**Comment by ctubio** [comment]
:koala: all this comes from step 0 of installation, so i certainly dont feel like hidding nothing (let me lol again; thank you)
