### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by ipxs123** [ctubio/Krypto-trading-bot#1101]
![Untitled](https://user-images.githubusercontent.com/78660885/116092589-c9edbb80-a65a-11eb-88fb-7510b93b92cb.png)
how to fix it?

**Comment by ipxs123** [comment]
Its not helps 
![Untitled](https://user-images.githubusercontent.com/78660885/116360836-2cf36580-a7b5-11eb-8996-6c474be0199d.png)

**Comment by ctubio** [comment]
:koala: you are using 2 diferent environments

why one prompt has **MSYS** and the others **MINGW64**?

why `make` is installed on **MSYS** but `K` is installed on **MINGW64**?

as soon as you install `make` in the same environments as you install `K` it will work

**Comment by ctubio** [comment]
:bulb: i suggest you to forgot about your **MINGW64** instance (that may be installed by git or github app) and use **MSYS** instead (just because i dont think you can easy install make on **MINGW64** because there is no `pacman` in there)
