### ISSUE TITLE
UI "running" but inaccessible

### ISSUE THREAD

**Issue by lastb0isct** [ctubio/Krypto-trading-bot#1103]
I am running the bot on a server I have.  Have attempted to use docker and manual installation but neither load the WebUI.  I have customized the port and it says that the UI is read at the externalIP:port, but the UI can't be accessed.  Are there any logs that can be looked at?

**Comment by ctubio** [comment]
you can use any internal IP that points to that machine/instance too (not only the external ip)

**Comment by biyian** [comment]
Have been having the same issue, but if you let it go for 30 minutes or so I can get to the UI. Happening on Synology DS918+ via docker, raspberry pi 4 8gb via pi os full. Once it does connect I'm able to make trades just fine but keep getting Curl recv/send fix error: Failed sending data to the peer and couldn't connect to server

05/15 05:55:38.347956 GW COINBASE Warrrrning: CURL recv FIX Error: Failed sending data to the peer.
05/15 05:57:17.836608 GW COINBASE Warrrrning: CURL send FIX Error: Couldn't connect to server.

I'm still running down if its a networking issue on my side. 

ctubio thanks for all the hard work, you're a legend.

**Comment by ctubio** [comment]
maybe that instance doesnt have direct connection to internet?

i would say you can check it manually with:
```
curl -vvv https://api-public.sandbox.pro.coinbase.com/products
```

:koala: note, you dont need to have any open ports to make use of FIX, even if the endpoint is `fix.pro.coinbase.com:4198`
