### ISSUE TITLE
Please place a clearly visible notice that this is NOT an open source on this project.

### ISSUE THREAD

**Issue by eniware-org** [ctubio/Krypto-trading-bot#1104]
> licensed by/under the law of my grandma (since last century), feel free to crack all as you need.

@ctubio To be honest, it sounds more like a joke. 

I was considering contributing to this project, but since it is impossible to build a fully functioning system from open source alone, this project is no much better than lame corporate software, it is not open source. without closed-source `K-linux-x86_64.1.a` open source code in this repository is useless. I'm sure many open source developers have the same opinion. Moreover, how can anyone be sure you don't inject droppers into this proprietary lib without reverse engineering ?

This contradicts your slogan `freedom for the revolutionary`

_Originally posted by @v-byte-cpu in https://github.com/ctubio/Krypto-trading-bot/issues/1100#issuecomment-821980392_

**Comment by ctubio** [comment]
sorry let me lol

use --help of read the readme  or makefile file:


             This is free software: the UI and quoting engine are open source,
             feel free to hack both as you need.

             This is non-free software: built-in gateway exchange integrations
             are licensed by/under the law of my grandma (since last century),
             feel free to crack all as you need.

i cannot put it more clear

the gateways are not opensource; if you want the sources of the APIs make it yourself or ask to my grandma (yea is a joke; you should do yourself)

what is opensource here is the UI and the quoting engine

what is private is 4 stupid damn functions that you can see all de details about while reading the documentation of each exchange

all private logic is really public in the documentation of each exchange, you can certainly do yourself

if you bother to read the source, this is the only private source:
https://github.com/ctubio/Krypto-trading-bot/blob/950e52ace728e891e89940252e8b7d963b8df604/src/lib/Krypto.ninja-apis.h#L217-L225

**Comment by ctubio** [comment]
:koala: all this comes from step 0 of installation, so i certainly dont feel like hidding nothing (let me lol again; thank you)

**Comment by eniware-org** [comment]
What I am asking is a notice on the project page. One has to go much further inside to discover this.
Further, if you are providing something in exchange for payment you have to make sure to the best of your abilities it works. Many of us here are contributing to finding all kings of bugs that are not getting fixed. Some are critical and lead to financial loses!
In addition, you are removing functionality from the gateway for which I have to use. I refer to BITFINEX_MARGIN here. I don't know how to call this!

**Comment by ctubio** [comment]
:koala: lets move it to https://github.com/ctubio/Krypto-trading-bot/issues/1105
