### ISSUE TITLE
stable bot

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#1109]
<kbd>Phase 1</kbd> collect underpants

<kbd>Phase 2</kbd> ???

<kbd>Phase 3</kbd> profit

:koala: stable markets here we go!

**Comment by durrhurr991** [comment]
always a nice idea to keep them underpants sorted :D

**Comment by ctubio** [comment]
:koala: stable bot done

Notorious B.I.G. tested it and says: [is all good baby baby](https://www.youtube.com/watch?v=_JZom_gVfuw&t=19s)
