### ISSUE TITLE
Orders way off balanse never getting traded

### ISSUE THREAD

**Issue by jantb** [ctubio/Krypto-trading-bot#111]
![img_2733](https://user-images.githubusercontent.com/625930/28751345-6087b270-7505-11e7-9603-183179037e05.PNG)

Default settings used and this happens after some hours of trading. Fair price is way off balance.

Trend is downwards and K is only holding btc in the wallet.

What settings do I need to tweak?

**Comment by b-seite** [comment]
maybe it´s  the same issue as mine described here #100 

You can use the cxl option to automatically cancel zombie orders every 5 minutes or delete them manually by using the "cancel orders" button in K.
But my workaround at the moment is to not trade on gdax but to use bitfenix

**Comment by jantb** [comment]
I dont think thats the issue. It's the fair price thats off balance. Restarting the bot fixes the problem.

**Comment by ctubio** [comment]
wtf no logs and screenshots from external websites?

**Comment by jantb** [comment]
Sorry, for not providing logs and a screenshot. Is there a way to get more debug into the logs. Currently it only shows:
```
18:31:26.875 main Event loop delay 300ms
18:31:29.666 tbp recalculated 0.07092132287170076
18:31:56.720 tbp recalculated 0.054436262162670807
18:31:56.841 tbp recalculated 0.07093691193124203
```

For a better screenshot in booming market with trading parameters at the top:
<img width="1407" alt="k" src="https://user-images.githubusercontent.com/625930/28755990-83da66b2-7566-11e7-9c8c-53e054d99451.png">

Now in a market where the price goes up it stacks up on fiat and tries to buy BTC very cheap. And in a downwards market it will fill up on BTC and try to sell for way too much. When I restart the bot it will start putting in buys and sells around the balance price again.

My question is if there is a setting I am missing that will make it rebalance the fair price faster so I don't loose so much when the market goes up or down.

Btw it's a great bot, and I see you put a lot of effort into it.

**Comment by ctubio** [comment]
mm.. i think you are looking for a smaller EWMA value or to directly uncheck it.

in the `Stats` you can see the `ewma quote protection`, i think that is what is selling for way too much or buying very cheap; because ewma is protecting you.

**Comment by jantb** [comment]
Thank you for the quick reply. I'm new to the bot so there is a lot I don't understand yet. I'll tweak the values and hopefully it will go better.
