### ISSUE TITLE
Missing configuration vars in K.sh.dist

### ISSUE THREAD

**Issue by eniware-org** [ctubio/Krypto-trading-bot#1111]
Just noticed that UI_USERNAME, UI_PASSWORD and UI_OPENPORT are missing from the K.sh.dist

**Comment by ctubio** [comment]
:koala: yea not in use anymore cos are not common vars for all bots

the alternative is to put `--user`, `--pass` and  `--port` inside `OPTIONAL_ARGUMENTS`, liiike:
https://github.com/ctubio/Krypto-trading-bot/blob/de1e413c99f9832d6edd71fedd0f2a62fd605437/etc/K.sh.dist#L35
