### ISSUE TITLE
"Internal order execution deadline exceeded" on HitBTC

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#1113]
I keep getting the error "Internal order execution deadline exceeded" on HitBTC since yesterday. What does that mean and what can I do?

**Comment by ctubio** [comment]
just because of the word "Internal" i would say is a hitbtc issue

if the issue persist for you consider going to https://support.hitbtc.com/en/support/tickets/new

here im able to place orders as usual
