### ISSUE TITLE
maRgin trading

### ISSUE THREAD

**Issue by durrhurr991** [ctubio/Krypto-trading-bot#1114]
is it anyhow possible to setup the trading bot to go for margin instead of normal trading? havent found a solution for that just yet

**Comment by ctubio** [comment]
:koala: margin trading for now is just supported only on bitfinex / ethfinex

**Comment by eniware-org** [comment]
@durrhurr991 
In any case, be very careful as TBP is not working on margin. Read again all the warnings before using the bot, repeat 100 times and then carry-on.

**Comment by durrhurr991** [comment]
I see so it would pretty much just make rather random quotes instead of rather calculated ones?

**Comment by ctubio** [comment]
officialy we can say the support of margin is broken, because i do not use it daily and the bot is certainly not build (i mean the math calcs of the [quoting engine](https://github.com/ctubio/Krypto-trading-bot/blob/master/src/bin/trading-bot/trading-bot.data.h)) with margin trading in mind

**Comment by eniware-org** [comment]
@durrhurr991 
The quotes are far for random and very useful (save for the ping-pong logic), but given the lack of position management and the possibility of getting liquidated if you are over-leveraged (as is the case currently 10X for BTC/USD) : USE AT OWN RISK (i.e., don't come back to complain about losses)

**Comment by durrhurr991** [comment]
if one just goes for a 5% margin and plays it safe it would make quite some money in no time though. just tested out the margin a little bit with a coupon and since i lost a few bucks through a pump. i got a good 50% win on a small amount of usdt so if the margiN would go through with safe settings as normal trading does with a 2% a day thats quite a bit if it does not spaz and goes all in

**Comment by durrhurr991** [comment]
@ctubio if i want to edit the settings to go for margin instead which of the api files would i have to edit?

**Comment by ctubio** [comment]
:koala: i put a link to the relevant single file of the [quoting engine](https://github.com/ctubio/Krypto-trading-bot/blob/master/src/bin/trading-bot/trading-bot.data.h)  at https://github.com/ctubio/Krypto-trading-bot/issues/1114#issuecomment-866150860

**Comment by durrhurr991** [comment]
yikes :D
