### ISSUE TITLE
Problems with the latest version

### ISSUE THREAD

**Issue by eniware-org** [ctubio/Krypto-trading-bot#1115]
The new UI is looking awesome!
However, there is problem with the grid. It does not update automatically and when the page is refreshed I get this:
![image](https://user-images.githubusercontent.com/34030382/124203266-3ad6a700-dad4-11eb-841e-17d09c4139ec.png)
Made a clean install on latest Ubuntu 20.04 and deleted the MongoDB before starting with `rm -rf /var/log/K`.

**Comment by ctubio** [comment]
im sorry my bad, cannot have more issues (4) iSee :( thank you for the report; lemme fix on next commit the css and the nan and the refresh and the middle headers

:koala: just saying, is a sqlite database
