### ISSUE TITLE
Binance rounding error - too aggressive (?)

### ISSUE THREAD

**Issue by Corfucinas** [ctubio/Krypto-trading-bot#1118]
Just started the instance with normal settings that you know. I think the rounding update on the last commit triggered this

Bid and Ask size are the same on the settings btw

![image](https://user-images.githubusercontent.com/53630064/126456855-6b4033bd-f58c-4a2d-9eae-65e7dbdfefe0.png)

**Comment by Corfucinas** [comment]
Wallet got eaten again lol 

![image](https://user-images.githubusercontent.com/53630064/126457631-093101b0-9e68-4397-8ba3-ce49851c28ef.png)

**Comment by Corfucinas** [comment]
There's another problem, once the bot hits the above error, it will place arbitrary trades at a losing Pong that will not show up on the UI nor the DB, but will be executed, the market has gone up ~30%, but the bot traded in a way that I lost -10%

**Comment by ctubio** [comment]
thank you for the report'''
my brain hurts reading this error messages, because each line looks like is half of it about the orders and half of it is about the wallet

im sorry for the mess lemme fix it soOn''
