### ISSUE TITLE
BFX Segmentation Fault

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1129]
Happened twice within the past 24-48 hrs. Running K-trading-bot v0.6.5+8 (build on linux-x86_64 at 2021-09-19 23:59:55)..

09/21 00:57:05.306867 Errrror: Segmentation fault (Three-Headed Monkey found):
- exchange: BITFINEX
- currency: ETH/USD
- binbuild: K-trading-bot linux-x86_64
- lastbeat: 54562366
- tracelog:
  2: [0x559938cb94f2]
  1: /lib/x86_64-linux-gnu/libc.so.6(+0x37840) [0x7f3653967840]
  0: K-trading-bot(_ZN3₿6Ending3wtfEi+0x28f) [0x559936f7c0af]

**Comment by ctubio** [comment]
i got some too at ₿::Curl::Web::xfer since a few days ago; so incoming fiiix (hope we are talking about the same)

**Comment by ctubio** [comment]
i was looking for 2 segfaults but only found one so far; excuse me if i closed this issue too quick

**Comment by ctubio** [comment]
:koala: ima leave this here https://github.com/curl/curl/issues/7683
