### ISSUE TITLE
Coinbase market levels are not sync after a while

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#113]
all OK but after a few hours 1 level is wrong, the topBid, that goes beyond the topAsk; some event may be missed (maybe `change` event [nope, is the queue of msgs after snapshot, that are not processed]), will fix soOn

this makes coinbase bot useless since https://github.com/ctubio/Krypto-trading-bot/commit/41ed3f8ba1206cea894aed98953fb7e97b14daaf

**Comment by Zep18** [comment]
Is it fixed ? I experience the same problems with the last commit

**Comment by ctubio** [comment]
the fix was https://github.com/ctubio/Krypto-trading-bot/commit/5e07c62f1d705f058a58a97f7aa51403a4063d22
