### ISSUE TITLE
Catch2 version 3 migration

### ISSUE THREAD

**Issue by nwdset** [ctubio/Krypto-trading-bot#1139]
Catch2 is being upgraded to v3 and one can see that there's some changes needed to be made for [`unit_testing_framework.cxx`](https://github.com/ctubio/Krypto-trading-bot/blob/365044ea4b27571af9fcf9e1a6bd36ce1e8e9d01/test/unit_testing_framework.cxx#L7).
so this line

`#include <catch.h>`

should be 

`#include <catch2/catch_all.hpp>`.

**Comment by ctubio** [comment]
:koala: oh ok, awesome; will do soOn then''

**Comment by nwdset** [comment]
oh actually i just realized your `Makefile` downloads the v2 of `Catch2`, as the migration to V3 haven't happened yet, it's still on develop. my bad, this is an non issue.
