### ISSUE TITLE
Getting wallet data from Websocket + explanation

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#114]
Hey Carles,

I've been thinking and there is a problem with getting wallet data from the REST API.

The issue is that the trade size depends (or can depend) on the amount of free cash you have, but as we're using rest API to calculate this amount but the problem is that we send orders much faster (using WebSocket).

So this can cause a possible discrepancy and harm the trading because either K will try to make a trade but the capital is already taken or in contrary, the capital is free but K sees it as occupied and do not send and order (or a smaller one).

Another solution is to deactivate the protections based on the quantity you have left in the account.

Tell me what you think,

Camille

**Comment by ctubio** [comment]
err.. there is no API with wallet data over websocket; and we already make use of the orders information and the fair value to maintain the wallet values in realtime

market levels works in the same way; there is no websocket with full levels; we just get over REST the full levels on boot and maintain the book based on orders information

**Comment by ctubio** [comment]
if there is a problme, the only solution is to increase the interval
