### ISSUE TITLE
Today, I sing: Dj Jack Tlala - Terminator

### ISSUE THREAD

**Issue by geebsaaaa** [ctubio/Krypto-trading-bot#1140]
https://www.youtube.com/watch?v=nmYOayNiv1A
absolute heat :🔥🔥🔥
very proud of my home..
![1200px-Estelada_blava](https://user-images.githubusercontent.com/35860852/142344506-6a974abb-599c-4b7f-83e6-3558d41333da.png)
.

**Comment by geebsaaaa** [comment]
.

**Comment by ctubio** [comment]
![PUNY](https://user-images.githubusercontent.com/1634027/142347513-b900c43b-573c-4579-a176-aa3b494940cd.jpg)

**Comment by ctubio** [comment]
> :fire: :fire: :fire: 

![itsover1000](https://user-images.githubusercontent.com/1634027/142347457-44b0f1bd-8633-4ab5-a6f2-a0efde5a44d1.jpg)
