### ISSUE TITLE
Gzip Bomb Segmentation Fault

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1152]
Currently using an IP whitelist and have been seeing segfaults happen almost immediately after dropping gzip bombs on unauthorized connections like this:

01/22 07:05:04.019419 UI dropping gzip bomb on 172.104.140.107.
01/22 07:05:14.930584 Errrror: Segmentation fault (deprecated K version found).

01/23 11:27:48.568333 UI dropping gzip bomb on 94.102.49.193.
01/23 11:28:11.164625 UI dropping gzip bomb on 94.102.49.193.
01/23 11:28:34.063473 Errrror: Segmentation fault (deprecated K version found).

Not sure if related, but seeing this happen on multiple fresh Debian 11 installs.

**Comment by ctubio** [comment]
:koala: sorry i been a few years out
thank you alot for the report, i just tested it after updating all libs and is working as expected again
