### ISSUE TITLE
market-filtration.js - Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dddanmar** [ctubio/Krypto-trading-bot#116]
Fantastic package, thank you for working on this, it's greatly appreciated.

I've moved my running instance to another server, updated to the latest commits and am having some problems with OkCoin.

Initial trades and the first few minutes of the bot run well, however it will eventually crash with the following output:

```
01:44:14.226 main Unhandled exception! TypeError: Cannot read property 'length' of undefined
    at MarketFiltration.filterFullMarket (/home/ec2-user/Krypto-trading-bot/app/server/market-filtration.js:12:41)
    at MarketFiltration._evOn.mkt (/home/ec2-user/Krypto-trading-bot/app/server/market-filtration.js:39:52)
01:44:14.229 main Attempting to cancel all open orders, please wait..
1:44:14.230354 GW okcoin Changed quoting state to Disabled.
01:44:16.231 main Exit code 0
```

I've moved the bot back to the original server with the updated code and receive the same error.

**Comment by ctubio** [comment]
umf thanks for the notice, will fix tomorrow
