### ISSUE TITLE
Bot doesnt work

### ISSUE THREAD

**Issue by Noob-A** [ctubio/Krypto-trading-bot#1167]
i have this settings:
![image](https://user-images.githubusercontent.com/59875489/186241915-72eaf182-2b98-483b-a8d6-ca5946a3359e.png)
the problem is that the bot didnt create any orders in 24 hours, why?
only thing changing is balance held and available jumping around
Exchange: binance
Pair: YFI/BUSD

**Comment by ctubio** [comment]
:koala: im sorry i was out a few years
hope you solved it by now, let me close this.
