### ISSUE TITLE
Something is wrong with Bitfi :s

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#117]
Hello Carles and everyone,
Since a few weeks I realized that something is not working well with K on Bitfi I had different theroes but they were wrong.

Now I'm trying with less markets and the result is the same.

It seems that the bot stop trading and "take its time" while there is no reason to do so.
It's confirmed by the amount of trade per day dropping like a rock. :s

Well it's a bit weird and I'll investigate more in depth when I come back from holidays.

So my question is, did some of you noticed something similar ?

Carles do you have an idea where it can come from ?

Obviously we are in the middle of a migration so I understand it's not the time the bot is the most stable haha.

So if you need some tips to investigate tell me! :)

have a good day everyone !
Un saludo desde Croatia :)

**Comment by ctubio** [comment]
it happens also in other markets, this will be addressed during the migration of the quoting engine

**Comment by Camille92** [comment]
Okay i understand would you recommend moving back to v.3 for now ? Or
something in the middle. :)

**Comment by ctubio** [comment]
not sure, for me always the last commit is the best

**Comment by Camille92** [comment]
Moved to last commit so far it works perfect :)
