### ISSUE TITLE
CURL/SSH error

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#1170]
Since some days K doesn't work anymore, I keep getting this error:

11/16 15:16:06.841084 GW Errrror: Unable to fetch data from HITBTC for symbols CHSB/BTC, response was: {"error":"CURL Request Error: SSL peer certificate or SSH remote key was not OK"}.
K exit code 1.
K crashed with exit code 1.. Respawning..

Any ideas?

**Comment by flfsbr** [comment]
Hello, I'm normally using hitbtc. What configuration are you using?

**Comment by Pat71** [comment]
I figured it out - it was a problem with my DNS :-/
