### ISSUE TITLE
GUI is not working (flooded with msgs from server)

### ISSUE THREAD

**Issue by Sladoeg** [ctubio/Krypto-trading-bot#1172]
The GUI doesn't work  for me, dropdown menus are empty.
Version: K-trading-bot v0.6.6+6 (build on linux-x86_64 at 2021-10-12 17:52:29).
@secwang @nonkreon Is this project still supported or dead? And what is the latest stable version that works?

![image](https://user-images.githubusercontent.com/17851813/213865374-8245756a-5b1f-4127-bc56-7390064c78a5.png)

**Comment by nonkreon** [comment]
Let's not call dead but we're doing our best not to get layoffed so is a
little neglected lately. Not much to do anymore anyway, only things I have
in mind is fix Coinbase API sometime soon once I can fix the building issue
and add VWAP.
Did you really compile from source (make build) or just called make install
which downloads and installs prebuilt binaries?
This happened to me back when for two reasons:
1. Some ad/script blocker on chrome
2. If your machine is old/spotty connection and the currency is updating
too often the GUI becomes unstable. Try to increase delay to at least 10
and switch to a more boring market pair just to test if the GUI works with
that and work your way back to the interested quote. To this day when my
connection is spotty on a very active pair like BTCUSD on Coinbase I just
play with the database file to make changes and not use GUI.

**Comment by Sladoeg** [comment]
@nonkreon Thanks a lot , I thought there were no commit and fixed as the latest one was half a year ago. There were two option for me: everything works perfect or left to their own. I suspect it was installed from the precompiled binaries as the version is dated 2021. Get the same idea to configure the paremeters inside the DB when the GUI is out of service. 

Wil try to compile it from source.

Well, as for me, the calculated price models could be added to the project to use it as fair value of price.

**Comment by Sladoeg** [comment]
@nonkreon, have the issue with the json when building, could you please advice how to include it correctly on Ubuntu 22.04?
![image](https://user-images.githubusercontent.com/17851813/213908926-eb02ff32-9747-49d4-8898-e10e90a40b65.png)

**Comment by Sladoeg** [comment]
Is compiled from the latest source, but it took time as there are no fully described manual and some libs cannot be build using automatated script.
The GUI works, but lags to much when using BTC-USDT, other pairs are fine.

@nonkreon The params of the mm strategy are stored inside sqlite db file?
![image](https://user-images.githubusercontent.com/17851813/213945149-15dd5451-d596-4f33-8370-965b72b49645.png)

**Comment by nonkreon** [comment]
Yes, the params you see on the screen are accessible in the db file. 

some libs got old so they are not building as per Carles' original build script anymore, it needs to be updated. If you figured it out please share with the community.

My server at home I was running the bot on and was trying to figure out how to correctly update the libs had a HDD fault, before I got it back up I had a baby then I got laid off from my job... It's been a helluva year and life's still coming at me... I certainly wish I could get it up and running myself and share, but I just don't have the time anymore.

**Comment by ctubio** [comment]
:koala: im sorry i was out a few years
hope this is fixed by now, all libs are again up to date

**Comment by Sladoeg** [comment]
Hello, Carles, I compiled the libs and got  Kbot GUI  lags  when too many
trades records are accumulated.
I re-run the bot by the script regularly to reset the number of trades.

пн, 21 окт. 2024 г. в 03:56, Carles Tubio ***@***.***>:

**Comment by ctubio** [comment]
:koala: many thanks for letting me know, ima rerereview the accumulated trades records

**Comment by ctubio** [comment]
:koala: after the next commit, taker traders will not be send 1 by 1 to the UI in realtime anymore.

instead, taker trades will be accumulated in the server with a maximum limit of 30, and are send to the UI all together only after each 0.3 seconds or the configured delayUI seconds
