### ISSUE TITLE
How to quote both sides each X seconds

### ISSUE THREAD

**Issue by Sladoeg** [ctubio/Krypto-trading-bot#1175]
With the current logic of K-bot the quotes are realeased when there is a difference between the FairValue and the mid price.
On other time the quoting engine is idle.

When the FairValue and mid price are equal that means the bot should quote both side to catch the spread each time.
That is the best time for the market-making as the price is in equilibrium state.

Are there any options to add this?

**Comment by ctubio** [comment]
the quoting parameter tbp and the safeties control  what side is placing orders
