### ISSUE TITLE
Binance Cross Margin connection support

### ISSUE THREAD

**Issue by Sladoeg** [ctubio/Krypto-trading-bot#1176]
Passing the  --leverage=0 argument takes no effect, the K-bot shows token balance of 0 for Binance Cross Margin Account.
The same for Isolated Margin Account if to pas the --leverage=2.

@nonkreon @serzhiio Could you please adivice or this feature is not supported?

![image](https://user-images.githubusercontent.com/17851813/229314354-22c1021c-fe8c-4545-a325-a81d2f002075.png)

Thank you in advance.

**Comment by ctubio** [comment]
im sorry finally only spot trading will be integrated
