### ISSUE TITLE
unable to open database file.

### ISSUE THREAD

**Issue by shaojintian** [ctubio/Krypto-trading-bot#1179]
<img width="588" alt="image" src="https://github.com/ctubio/Krypto-trading-bot/assets/40530183/c0b2e344-2904-42d2-8c59-b86e44381592">

**Comment by shaojintian** [comment]
I have already installed sqlite3

**Comment by ctubio** [comment]
:koala: no need to install sqlite3, it is built-in

note the directory `/var/lib/K/db` should be writable after creating it with `$ make install`
