### ISSUE TITLE
Errrror: Use of missing "BCH" currency on Bitfinex

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#118]
Hi,

since the last Days K throws the Errrrror:Use of missing "BCH" currency when i start with node.

do i have to activate or do something else with BCH on Bitfinex? I found nothing...

output from console is:
`K.linux.57
22:5:58.663617 CF settings loaded from JSON file K OK.
22:5:58.663941 DB /data/db/K.4.6.82.db loaded OK.
22:5:58.664390 UI ready over HTTPS on external port 3000.
22:5:58.897699 GW bitfinex allows client IP.
22:5:58.897877 GW bitfinex:
- autoBot: yes
- pair: ethusd
- minTick: 0.01000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
22:05:59.109 bitfinex Starting nonce: 1501797959109
22:05:59.123 tbp Loaded from DB: 0.1682269851379557
22:5:59.424317 Errrror: Use of missing "BCH" currency.`

**Comment by ctubio** [comment]
thanks for the notice'¡
