### ISSUE TITLE
Binance NOTIONAL error.

### ISSUE THREAD

**Issue by flfsbr** [ctubio/Krypto-trading-bot#1183]
Hello. I've been facing the following error for days.

03/03 20:40:43.884258 GW BINANCE Warrrrning: Error while place order: Filter failure: NOTIONAL.
03/03 20:40:43.995012 GW BINANCE Warrrrning: Error while place order: Filter failure: NOTIONAL.
03/03 20:40:44.032541 GW BINANCE Warrrrning: Error while place order: Filter failure: NOTIONAL.
03/03 20:40:44.122185 GW BINANCE Warrrrning: Error while place order: Filter failure: NOTIONAL.
03/03 20:40:44.484084 GW BINANCE Warrrrning: Error while place order: Filter failure: NOTIONAL.
03/03 20:40:44.802231 GW BINANCE Warrrrning: Error while place order: Filter failure: NOTIONAL.
03/03 20:40:44.829091 GW BINANCE Warrrrning: Error while place order: Filter failure: NOTIONAL.
03/03 20:40:44.924709 GW BINANCE Warrrrning: Error while place order: Filter failure: NOTIONAL.

Is this project still alive?

**Comment by ctubio** [comment]
took some time but finally fixed'¡ thank you for the report and patience
