### ISSUE TITLE
Hi Mate

### ISSUE THREAD

**Issue by saeedaya3** [ctubio/Krypto-trading-bot#1184]
is your service still working? your last update was on 2022 and i'm not sure that the service is alive.

**Comment by irwige** [comment]
its dead

**Comment by ctubio** [comment]
@saeedaya3 coinbase is currently not working, but in little days i will commit the new api for coinbase, and will continue to maintain it cos i wanna make use of it again, thanks for asking'¡

@irwige almost! but not yet xD
