### ISSUE TITLE
Realtime Lock

### ISSUE THREAD

**Issue by flfsbr** [ctubio/Krypto-trading-bot#1187]
Hi Carles. Today my K instances were locked for realtime data. Can you unlock them again?

**Comment by ctubio** [comment]
:koala: hii, i just unlocked them, but if any is missing just run it and i will see and unlock it at the end of the day again
have fun in your side of the planet'¡

**Comment by flfsbr** [comment]
Tell me how can I contact you. Discord, Telegram... etc.

**Comment by ctubio** [comment]
:koala: hiii, feel free to join https://discord.gg/jAX7GEzcWD or DM [ctubio on reddit](https://www.reddit.com/user/ctubio).
