### ISSUE TITLE
Killing the app if too much ram is used

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#121]
Hi Carles and everyone,

I have seen the 500Mb but you were talking about so I was looking for a solution, apparently, there is a node command line argument that kills the process if it eats too much memory.

What do you think about including it in the code when we do a make start or make startall.

The argument is:
--max-old-space-size=100 or --max-old-space-size=200

It seems to be in the V8 argument (for whatever that is). Tell me what you think, it might be a practical solution to the current bug :)

**Comment by Camille92** [comment]
https://stackoverflow.com/questions/30252905/nodejs-decrease-v8-garbage-collector-memory-usage

**Comment by CarlitoGrey** [comment]
I currently have a cron job to restart K every 30 minutes but this looks like a better 'patch' until the leak is fixed, and actually might be a good fail-safe in the long run. 
Testing it now!

**Comment by ctubio** [comment]
yea i preffer to restart than to limit the memory

**Comment by Camille92** [comment]
No probs, I created a cron tab too :)
Is there any way we can help you to find the memory leak?

I have a bit of free time on my hand to help :)

**Comment by ctubio** [comment]
this could be investigated with https://github.com/bnoordhuis/node-heapdump

im 99.999% sure is some src/server/*.ts file, but didnt spend time looking for it cos the plan is to delete all *.ts files; im sorry for the waiting time meanwhile

**Comment by Camille92** [comment]
Hey no worries I understand if it comes from the ts part why it's not ultra necessary.

**Comment by ctubio** [comment]
confirmed is in the node side:
```

<--- Last few GCs --->

[25618:0x2d86990] 16289747 ms: Scavenge 720.4 (800.9) -> 705.1 (801.4) MB, 1.9 / 0.0 ms  allocation failure
[25618:0x2d86990] 16289857 ms: Scavenge 724.6 (805.8) -> 709.6 (805.8) MB, 1.7 / 0.0 ms  allocation failure
[25618:0x2d86990] 16289965 ms: Scavenge 729.4 (810.3) -> 714.1 (810.3) MB, 1.8 / 0.0 ms  allocation failure
[25618:0x2d86990] 16290371 ms: Scavenge 734.3 (815.3) -> 718.6 (815.3) MB, 11.2 / 0.0 ms  allocation failure


<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: MarkingDeque::EnsureCommitted Allocation failed - process out of memory
 1: node::Abort() [node]
 2: 0x13647ec [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::MarkingDeque::StartUsing() [node]
 6: v8::internal::MarkCompactCollector::MarkLiveObjects() [node]
 7: v8::internal::MarkCompactCollector::CollectGarbage() [node]
 8: v8::internal::Heap::MarkCompact() [node]
 9: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
10: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [node]
11: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
12: 0xe92f5c [node]
13: 0xe93965 [node]
14: v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow) [node]
15: v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::Object::StoreFromKeyed) [node]
16: v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::JSObject::AccessorInfoHandling) [node]
17: v8::internal::JSObject::CreateDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::ShouldThrow) [node]
18: v8::internal::JSReceiver::CreateDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::ShouldThrow) [node]
19: v8::internal::Runtime_CreateDataProperty(int, v8::internal::Object**, v8::internal::Isolate*) [node]
20: 0x1066c900437d
Aborted

```

**Comment by johnnyfla123** [comment]
This is the crontab I am using to restart K every 30 minutes. I am running 10 instances and this restarts all of them.

`*/30 * * * * make -C /PATH/TO/K restartall >/dev/null 2>&1`


To make the bots start trading when they start add the word 'auto' to the beginning of BotIdentifier in your K.json/png files. like: `"BotIdentifier": "auto Mybot #1",`

**Comment by ctubio** [comment]
fixed at https://github.com/ctubio/Krypto-trading-bot/commit/e9612e17e949f95c9af631624ee8d31162a5d4f5

**Comment by Ultrahoschie** [comment]
is the problem cleand ... and i can delete the cronjob?

**Comment by ctubio** [comment]
dont you see the issue is closed?

**Comment by Ultrahoschie** [comment]
ok ... thx
