### ISSUE TITLE
nodejs: server not using any ports

### ISSUE THREAD

**Issue by nlegall** [ctubio/Krypto-trading-bot#122]
Web server UI cannot be reached.
netstat -nltp   : port does not show.

Ran simple hello world server on port 3000 it works fine with curl http://127.0.0.1:3000
and port shows in netstat -nltp.

using:
 "WebClientListenPort": "3000",
    "MatryoshkaUrl": "http://",

It does not seem to 'pick-up the port number from the K.json.

KCONFIG=K or KCONFIG=K.json  not working either
I can make start, stop, list no problem.
TIA

**Comment by ctubio** [comment]
your app may not be running; see the output with `node K` instead of run it with make
