### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by shed909** [ctubio/Krypto-trading-bot#126]
Seems to get stuck in a loop on make install on DigitalOcean as well as on a Orange Pi (64bit Ubuntu Server).

Latest version of Node and Make.

Here's the output:

config.status: creating doc/Makefile
config.status: creating doc/html/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
make[4]: Entering directory '/home/orangepi/K/build/quickfix-v.1.14.4'
make  all-recursive
make[5]: Entering directory '/home/orangepi/K/build/quickfix-v.1.14.4'
Making all in UnitTest++
make[6]: Entering directory '/home/orangepi/K/build/quickfix-v.1.14.4/UnitTest++'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/home/orangepi/K/build/quickfix-v.1.14.4/UnitTest++'
Making all in src
make[6]: Entering directory '/home/orangepi/K/build/quickfix-v.1.14.4/src'
Making all in C++
make[7]: Entering directory '/home/orangepi/K/build/quickfix-v.1.14.4/src/C++'
grep "_ALLOCATOR" ../../config.h >Allocator.h
make  all-recursive
make[8]: Entering directory '/home/orangepi/K/build/quickfix-v.1.14.4/src/C++'
Making all in test
make[9]: Entering directory '/home/orangepi/K/build/quickfix-v.1.14.4/src/C++/test'
/bin/bash ../../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../.. -I.. -I../../../UnitTest++/src    -g -O2 -Wall -ansi -Wpointer-arith -Wwrite-strings -Wno-overloaded-virtual          -std=c++0x -O0 -g -MT DictionaryTestCase.lo -MD -MP -MF .deps/DictionaryTestCase.Tpo -c -o DictionaryTestCase.lo DictionaryTestCase.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../.. -I.. -I../../../UnitTest++/src -g -O2 -Wall -ansi -Wpointer-arith -Wwrite-strings -Wno-overloaded-virtual -std=c++0x -O0 -g -MT DictionaryTestCase.lo -MD -MP -MF .deps/DictionaryTestCase.Tpo -c DictionaryTestCase.cpp  -fPIC -DPIC -o .libs/DictionaryTestCase.o
mv -f .deps/DictionaryTestCase.Tpo .deps/DictionaryTestCase.Plo
/bin/bash ../../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../.. -I.. -I../../../UnitTest++/src    -g -O2 -Wall -ansi -Wpointer-arith -Wwrite-strings -Wno-overloaded-virtual          -std=c++0x -O0 -g -MT FieldBaseTestCase.lo -MD -MP -MF .deps/FieldBaseTestCase.Tpo -c -o FieldBaseTestCase.lo FieldBaseTestCase.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../.. -I.. -I../../../UnitTest++/src -g -O2 -Wall -ansi -Wpointer-arith -Wwrite-strings -Wno-overloaded-virtual -std=c++0x -O0 -g -MT FieldBaseTestCase.lo -MD -MP -MF .deps/FieldBaseTestCase.Tpo -c FieldBaseTestCase.cpp  -fPIC -DPIC -o .libs/FieldBaseTestCase.o
mv -f .deps/FieldBaseTestCase.Tpo .deps/FieldBaseTestCase.Plo
/bin/bash ../../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../.. -I.. -I../../../UnitTest++/src    -g -O2 -Wall -ansi -Wpointer-arith -Wwrite-strings -Wno-overloaded-virtual          -std=c++0x -O0 -g -MT FieldConvertorsTestCase.lo -MD -MP -MF .deps/FieldConvertorsTestCase.Tpo -c -o FieldConvertorsTestCase.lo FieldConvertorsTestCase.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../.. -I.. -I../../../UnitTest++/src -g -O2 -Wall -ansi -Wpointer-arith -Wwrite-strings -Wno-overloaded-virtual -std=c++0x -O0 -g -MT FieldConvertorsTestCase.lo -MD -MP -MF .deps/FieldConvertorsTestCase.Tpo -c FieldConvertorsTestCase.cpp  -fPIC -DPIC -o .libs/FieldConvertorsTestCase.o
mv -f .deps/FieldConvertorsTestCase.Tpo .deps/FieldConvertorsTestCase.Plo
/bin/bash ../../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../.. -I.. -I../../../UnitTest++/src    -g -O2 -Wall -ansi -Wpointer-arith -Wwrite-strings -Wno-overloaded-virtual          -std=c++0x -O0 -g -MT FileLogTestCase.lo -MD -MP -MF .deps/FileLogTestCase.Tpo -c -o FileLogTestCase.lo FileLogTestCase.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../.. -I.. -I../../../UnitTest++/src -g -O2 -Wall -ansi -Wpointer-arith -Wwrite-strings -Wno-overloaded-virtual -std=c++0x -O0 -g -MT FileLogTestCase.lo -MD -MP -MF .deps/FileLogTestCase.Tpo -c FileLogTestCase.cpp  -fPIC -DPIC -o .libs/FileLogTestCase.o
In file included from ../DataDictionary.h:31:0,
                 from ../Message.h:33,
                 from ../Log.h:29,
                 from ../FileLog.h:29,
                 from FileLogTestCase.cpp:28:
../DOMDocument.h:43:16: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   typedef std::auto_ptr<DOMAttributes> DOMAttributesPtr;
                ^
In file included from /usr/include/c++/5/memory:81:0,
                 from ../Utility.h:99,
                 from ../FieldTypes.h:29,
                 from ../FieldConvertors.h:25,
                 from ../Field.h:32,
                 from ../FieldMap.h:29,
                 from ../Message.h:29,
                 from ../Log.h:29,
                 from ../FileLog.h:29,
                 from FileLogTestCase.cpp:28:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from ../DataDictionary.h:31:0,
                 from ../Message.h:33,
                 from ../Log.h:29,
                 from ../FileLog.h:29,
                 from FileLogTestCase.cpp:28:
../DOMDocument.h:51:18: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     virtual std::auto_ptr<DOMNode> getFirstChildNode() = 0;

**Comment by ctubio** [comment]
what is your problem? you want it to be installed in less than 10 seconds or what?

there is not a single error in this log..

did you wait until the end or did you opened the issue even before the installation finnishes?

**Comment by shed909** [comment]
The rest of the log is a loop of:

In file included from /usr/include/c++/5/memory:81:0,
                 from ../Utility.h:99,
                 from ../FieldTypes.h:29,
                 from ../FieldConvertors.h:25,
                 from ../Field.h:32,
                 from ../FieldMap.h:29,
                 from ../Message.h:29,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from ../DataDictionary.h:31:0,
                 from ../Message.h:33,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
../DOMDocument.h:51:18: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     virtual std::auto_ptr<DOMNode> getFirstChildNode() = 0;
                  ^
In file included from /usr/include/c++/5/memory:81:0,
                 from ../Utility.h:99,
                 from ../FieldTypes.h:29,
                 from ../FieldConvertors.h:25,
                 from ../Field.h:32,
                 from ../FieldMap.h:29,
                 from ../Message.h:29,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from ../DataDictionary.h:31:0,
                 from ../Message.h:33,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
../DOMDocument.h:52:18: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     virtual std::auto_ptr<DOMNode> getNextSiblingNode() = 0;
                  ^
In file included from /usr/include/c++/5/memory:81:0,
                 from ../Utility.h:99,
                 from ../FieldTypes.h:29,
                 from ../FieldConvertors.h:25,
                 from ../Field.h:32,
                 from ../FieldMap.h:29,
                 from ../Message.h:29,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from ../DataDictionary.h:31:0,
                 from ../Message.h:33,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
../DOMDocument.h:53:18: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     virtual std::auto_ptr<DOMAttributes> getAttributes() = 0;
                  ^
In file included from /usr/include/c++/5/memory:81:0,
                 from ../Utility.h:99,
                 from ../FieldTypes.h:29,
                 from ../FieldConvertors.h:25,
                 from ../Field.h:32,
                 from ../FieldMap.h:29,
                 from ../Message.h:29,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from ../DataDictionary.h:31:0,
                 from ../Message.h:33,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
../DOMDocument.h:57:16: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   typedef std::auto_ptr<DOMNode> DOMNodePtr;
                ^
In file included from /usr/include/c++/5/memory:81:0,
                 from ../Utility.h:99,
                 from ../FieldTypes.h:29,
                 from ../FieldConvertors.h:25,
                 from ../Field.h:32,
                 from ../FieldMap.h:29,
                 from ../Message.h:29,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from ../DataDictionary.h:31:0,
                 from ../Message.h:33,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
../DOMDocument.h:69:18: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     virtual std::auto_ptr<DOMNode> getNode( const std::string& ) = 0;
                  ^
In file included from /usr/include/c++/5/memory:81:0,
                 from ../Utility.h:99,
                 from ../FieldTypes.h:29,
                 from ../FieldConvertors.h:25,
                 from ../Field.h:32,
                 from ../FieldMap.h:29,
                 from ../Message.h:29,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from ../DataDictionary.h:31:0,
                 from ../Message.h:33,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
../DOMDocument.h:71:16: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   typedef std::auto_ptr<DOMDocument> DOMDocumentPtr;
                ^
In file included from /usr/include/c++/5/memory:81:0,
                 from ../Utility.h:99,
                 from ../FieldTypes.h:29,
                 from ../FieldConvertors.h:25,
                 from ../Field.h:32,
                 from ../FieldMap.h:29,
                 from ../Message.h:29,
                 from ../Application.h:25,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from ../Application.h:25:0,
                 from ./TestHelper.h:4,
                 from FileStoreTestCase.cpp:28:
../Message.h:342:15: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   static std::auto_ptr<DataDictionary> s_dataDictionary;

**Comment by ctubio** [comment]
i dont care how slow is you computer; simply wait until the "loop" finnishes.

what you call "loop", is actually the fucking compilation

**Comment by shed909** [comment]
Wow dude, chill the fuck out. I'm not posting here to inconvenience you or put you down, I'm posting here because there may be an issue with your source code you can fix.
The only reason I thought it was a loop was because of multiple users reports in issue #35 and the several times I've tried to install it on different hardware since with the same result.

I let it run for 30 minutes just then..

Anyway, thanks.

**Comment by b-seite** [comment]
perhaps i have a hint: i had some similar problems when compiling on a machine with 512mb ram. what helped me is adding a  1G swap file described in the manual.

**Comment by ctubio** [comment]
still, i dont care

**Comment by ctubio** [comment]
also, when you paste a log, make sure it have an error
