### ISSUE TITLE
Nonce error when connecting to poloniex

### ISSUE THREAD

**Issue by vdaytona** [ctubio/Krypto-trading-bot#13]
app exchange: Poloniex/ETH/BTC
app version: latest

Hi, just find a bug when connecting to poloniex.
There is no information of trade history or my balance.
Seems that when requesting information, time does not fit the server.
Docker log:

04:09:19.588 poloniex Error returnTradeHistory Nonce must be greater than 1498190957748. You provided 1498190954412.
04:09:38.667 poloniex Error returnCompleteBalances Nonce must be greater than 1498190977751. You provided 1498190974287.

Might be a little modification in
line 15:     nonce?: number in /src/server/gateways/poloniex.ts ?

Thanks.

**Comment by CarlitoGrey** [comment]
Is the date and time on your computer correct?

**Comment by vdaytona** [comment]
Thank you for the suggestion. Actually, I run the instance on aws, and have not seen the same issue on other exchanges.

**Comment by ctubio** [comment]
nah is problem of stupid Poloniex api, if you debug the calls, you will see that the nonces are incrementally correct.

Is poloniex in their end messing up the order of the calls.

i research a bit and ppl out there increment the nonce by +1000 instead of by +1, i will try some similar patch

**Comment by ctubio** [comment]
i dont think i should invest time in poloniex
