### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by wulabs** [ctubio/Krypto-trading-bot#134]
A few feature requests.  Please point me in the direction if it is something on the roadmap or can be implemented using something else.

1) External data
Ability to take external signal/data feed to help make decisions. Simple example would be a polling request to a REST API that returns 0 or 1, and trade only when value is 1.

2) Support for OHLC, resampled data.
Resample price feed ask/bids into OHLC using ask/bid midpoint. Then resample into various timeframes (1min, 5min, etc).

3) OKEX Futures
Support for OKCoin OKEX Futures

4) Access to level 2 order book in real time.
Would like to write custom logic around market depth / order book.

**Comment by ctubio** [comment]
point 1 is not planned because is not a feature of general interest (an option is to run `make start` and `make stop` with some shell sccript for example `while.. sleep.. curl.. make`)
point 2 is already done, just click `Watch` link
point 3 can be done, but is not a priority
point 4 is out of my understanding

**Comment by wulabs** [comment]
Thanks for the quick reply.

For #1, the idea is to take external signals. Such as multiple data sources (price, sentiment, events, etc). Is there a way I can hook this? either polling a DB or some zeromq or other messaging service?

For #4, you already grab the bid/ask. Why only grab the top bid/ask? why not grab the entire book? There is significantly more information knowing the structure of the entire book than just the top prices. If it is nonunderstanding of how to use the OB I would be happy to explain that to you offline.

**Comment by ctubio** [comment]
best way may be to simply listen to the websocket, you can test at https://www.websocket.org/echo.html using the same url as your bot but replace `https://` by `wss://`

about the order book, the bot already knows not only the topBid and topAsk, but also all market levels; i some exchanges like in coinbase all market levels means more than 700

**Comment by CarlitoGrey** [comment]
I totally forgot about the 'Watch' link, I've been using cryptowat.ch on a separate tab for each bot!
