### ISSUE TITLE
std::invalid_argument after make start

### ISSUE THREAD

**Issue by rok-povsic** [ctubio/Krypto-trading-bot#135]
I keep getting a bunch of such errors in my forever logs after doing `make start`.

```
K.linux.57
terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected number literal; expected '}'
error: Forever detected script was killed by signal: SIGABRT
error: Script restart attempt #131
```

Ubuntu 16.04.2, node v8.3.0.

Any idea what could be wrong?

**Comment by ctubio** [comment]
no idea because you didnt say what exchange and currency pairs this was.

can you please say what exchange and currency pairs this was?

**Comment by rok-povsic** [comment]
@ctubio I did this for BTC/USD and tried OkCoin and HitBtc -- I got the same result for both.

Thanks for helping.

**Comment by ctubio** [comment]
im not able to reproduce this, for me OkCOin and HitBTC works nice with BTC/USD

seems like the responses are not valid json; maybe you can reproduce the error executing from this machine:
```
curl -vvv https://api.hitbtc.com/api/1/public/symbols
```
 the output should be json

**Comment by rok-povsic** [comment]
@ctubio Thanks for the answer. The response of the curl command seems just fine:

![image](https://user-images.githubusercontent.com/1495233/29261692-2515c448-80d1-11e7-8433-6a1b9c47ff91.png)

Dropping the `-vvv` results in a valid json (with `-vvv` a Connection closed message is inserted in the middle of the json output).

Any other idea what could be wrong? Thanks

**Comment by rok-povsic** [comment]
It seemed like g++-5 was the problem. I now installed g++-6 and updated g++ link to 6. I then had to install some mysql libs (`mysql-common` and `libmysqlclient18_5.6.25-0ubuntu1_amd64.deb`) and now I'm getting this again -- same error as before:

```
...
terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected number literal; expected '}'
error: Forever detected script was killed by signal: SIGABRT
error: Script restart attempt #8
K.linux.57
terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected number literal; expected '}'
error: Forever detected script was killed by signal: SIGABRT
error: Script restart attempt #9
K.linux.57
...
```

**Comment by ctubio** [comment]
im not sure yet what is the difference for you to fail and for me to work; maybe can you see what is the output of `node K`? (lets see if this happens on the very begin or after a while)

also can you confirm if you have more than 0 funds in both sides or if you have only BTC but not USD (or  USD but not BTC?)?

**Comment by rok-povsic** [comment]
@ctubio Ahh, there was a JSON mistake in the config. It'd be good if there was some kind of a check that tells you that since that seems like a common error.

Thanks for all the help!
