### ISSUE TITLE
Bug: When a trade is executed, position is not updated.

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#138]
Hi Carles,

I've noticed a bug on Bitfinex but maybe on the others.

When a trade is executed, the Fiat and asset wallet is not updated accordingly, it's only updated when the bot asks for the exchange the wallet info.

So for instance, if I have 1000USD in my account and 0 BTC, if the bot buys 0.1 BTC at 400 dollars it will show.
1000USD and 0BTC until it's updated with the API.

The problem here is that the bot may buy several times until the value is updated by the API!

**Comment by ctubio** [comment]
will migrate broker position object soon

**Comment by Camille92** [comment]
Okay :)

I'm not sure if it's really an improvement because we had that in past version :p.

But anyway for traders reading that it means, don't put your trade/seg setting under 15 seconds for now!

**Comment by ctubio** [comment]
i think we never had this before, cos wallet is updated only based on open trades, and a completed trade is not an open trade anymore.

immediatelly call the wallet api just because a trade was done doesnt seems like a nice solution

moving the funds to the other side after a trade is done seems like faking the reality; but may be the solution if we found that doesnt generate too much fake wallet data.

**Comment by Camille92** [comment]
Hey Carles I'm quite sure the faking reality option is what we used to use.

Because let's say you have 0 BTC in your account, 10K cash and a TBP of 1 BTC.
If you don't enable trade second, K will buy 1BTC but not update wallet and will try to buy another BTC  (because it thinks you're  still under your TBP).

At the end of the 15 seg maybe you now have 2BTC so K  will try to sell and maybe this time you will end up with 0 BTC again haha.

Do you see the problem :)

**Comment by CarlitoGrey** [comment]
Could you not hold any completed orders in memory until the next 15s refresh? That way it will never be too far out even if something goes wrong. The refresh could even be dropped to 1m if it works reliably and we would have less rate limit issues when trading >5 pairs etc. 

Calling the wallet API isn't great I agree, it will probably trigger some rate limiting too.

**Comment by Camille92** [comment]
Carlito what you propose is like the equivalent of having a minimum of trade/seg = 15seg no ?

What I propose is to "artificially" change the balance when a trade is executed, without calling the API.

So if you had 1BTC and 0 USD, if you sell that BTC you know that logically your USD balance =
**Sell_Size * Sell price - fees**

Then after the 15seg, the API call will update that if something went wrong or the rounding is not perfect. But it's good enough for a 15seg period.

And it allows you to do buy and sell under the 15seg! and that's the most important part!

**Comment by CarlitoGrey** [comment]
Nope, what I'm saying is exactly what you're saying 👍 .

Once an order is completed, K logs it to the DB. K could also log it into memory and apply the deviation, negative or positive, to the balance used to make any decisions. When the next API call is made the memory of completed trades can be dropped and we are 'in-sync' with the true value again.

**Comment by Camille92** [comment]
I've been thinking about that, not even need to mark the orders in a special way.
Just need to say that 2 things change wallet data: orders and api calls.


So one example would be:
API call: updated wallet position
Order 1 : updated
Order 2 : updated
Api call: updated but did not change
Order 3: updated
Order 4: updated
Order 5: updated
Api call: updated and change because of a small rounding error

etc..

What I mean is that api call will just be a confirmation of the wallet position :)

**Comment by CarlitoGrey** [comment]
I think another issue with this is that following a successful buy there is a delay of x seconds before a sell is attempted. Just thought about this today.

**Comment by ctubio** [comment]
closing cos in Bitfinex now we get from websocket data the wallet updates and snapshot in realtime
