### ISSUE TITLE
Minimum wallet amount in exchanges

### ISSUE THREAD

**Issue by fishsticks22** [ctubio/Krypto-trading-bot#139]
Hi, I'd like to test out this project with the smallest amount of bitcoin possible. I see that bitfinex's minimum trading amount is 0.1BTC, but does that apply to all other exchanges? I can't find any information anywhere about this.

**Comment by ctubio** [comment]
here you have hitbtc lots (=min order sizes): https://hitbtc.com/api#cursymbols
