### ISSUE TITLE
libquickfix.so runtime error on Ubuntu

### ISSUE THREAD

**Issue by wulabs** [ctubio/Krypto-trading-bot#140]
So I tried to run this on ubuntu 14.04. Using commit c5dea2e902ec5ae49e0095b5da39fadd6bd0baed.
Tried with gcc-4.9/g++-4.9 as well as gcc-6.3/g++6.3.

System info below.

Runtime Error:
`
$ ./node_modules/.bin/forever K.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
K.linux.57
/home/user/Krypto-trading-bot/app/server/main.js:14
            throw new Error(e);
            ^

Error: Error: /home/user/Krypto-trading-bot/app/server/lib/libquickfix.so.16: symbol _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
    at bindings (/home/user/Krypto-trading-bot/app/server/main.js:14:19)
    at Object.<anonymous> (/home/user/Krypto-trading-bot/app/server/main.js:16:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/Krypto-trading-bot/K.js:2:1)
error: Forever detected script exited with code: 1
`

System Info:
`
$ cat /etc/issue
Ubuntu 14.04.1 LTS \n \l

user@Ethereum:~/Krypto-trading-bot$ node -v
v8.1.3
user@Ethereum:~/Krypto-trading-bot$ g++ --version
g++ (Ubuntu/Linaro 6.3.0-18ubuntu2~14.04) 6.3.0 20170519
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

user@Ethereum:~/Krypto-trading-bot$ uname -a
Linux Ethereum 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by ctubio** [comment]
the fix should be:
```
sudo cp dist/lib/libstdc++.so.6.0.22 /usr/lib/x86_64-linux-gnu/
sudo cp dist/lib/libmysqlclient.* /usr/lib/x86_64-linux-gnu/
```
not sure why it didnt happened automaticaly

**Comment by wulabs** [comment]
Thank you sir!
