### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by loul42** [ctubio/Krypto-trading-bot#142]
Hi,

I installed your trading tool successfully (great job). I would like to test it first obviously, I connected it to hitbtc but their sandbox env is not working anymore ( same for gdax).

It's really hard to understand all those fields and strategies and I would like to test some.
Is there a way to have a fake balance ?
 
Thanks

Ps: Also If someone would be ready to show me how to configure this tool , I would really appreciate.

**Comment by ctubio** [comment]
in the json config file, you can leave "NULL" as the value for EXCHANGE; this will generate fake market data and fake balances/orders

also you can instead set some EXCHANGE but in the OrderDestination set it as NULL; this will only generate fake balances/orders while fetching real market data
