### ISSUE TITLE
running on ARM?

### ISSUE THREAD

**Issue by misaghzayyeni** [ctubio/Krypto-trading-bot#148]
Is it possible to run K on ARM? I'm using a raspberry pi, and I can't get it to run. I always get:

> K.linux.57
/home/pi/K/app/server/main.js:14
            throw new Error(e);
            ^

> Error: Error: /home/pi/K/app/server/lib/K.linux.57.node: wrong ELF class: ELFCLASS64
    at bindings (/home/pi/K/app/server/main.js:14:19)
    at Object.<anonymous> (/home/pi/K/app/server/main.js:16:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/K/K.js:2:1)

**Comment by ctubio** [comment]
not yet, will be once node is removed

**Comment by ctubio** [comment]
feel free to send a link to your RASPBERRY PI model, cos i may be able to test with the very same model mostly possible

**Comment by lejacobroy** [comment]
I also want to run L on the raspberry pi 3, I'll be willing to test a few things for both of you :)

**Comment by ctubio** [comment]
i managed to get a pi 3, will try it soOn''

**Comment by b-seite** [comment]
I have an old and unused pi 2b. 
If its wanted to get K Running on older Pi's i can help you pur with that by either testing on my own, giving you Remote Access or sending it to you

Greetings boris

**Comment by ctubio** [comment]
thanks @b-seite, finally i managed yesterday to get a raspberry; will test soOn''

many thanks again'''''

**Comment by lejacobroy** [comment]
I installed [pi64](https://github.com/bamarni/pi64) to remove this error, it's working so far as I get another, seemingly unrelated error ;)

**Comment by ctubio** [comment]
now it runs, but i think it does runs long enough xD

**Comment by lejacobroy** [comment]
Hi @ctubio .

I'm trying to install from fresh using the latest version on my pi3 running pi64 and `make start` gives me this error when it's still in the building phase : 
`make[6]: Leaving directory '/home/pi/Desktop/K4/build/openssl-1.1.0f'
engines/afalg/e_afalg.c: In function 'eventfd':
engines/afalg/e_afalg.c:110:20: error: '__NR_eventfd' undeclared (first use in this function); did you mean '__NR_eventfd2'?
     return syscall(__NR_eventfd, n);
                    ^~~~~~~~~~~~
                    __NR_eventfd2
engines/afalg/e_afalg.c:110:20: note: each undeclared identifier is reported only once for each function it appears in
engines/afalg/e_afalg.c:111:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:5965: recipe for target 'engines/afalg/e_afalg.o' failed
make[5]: *** [engines/afalg/e_afalg.o] Error 1
`
I don't know if it's related to this commit or not...

**Comment by ctubio** [comment]
maybe there are two versions of openssl sources in the system? try `sudo apt-get remove libssl-dev` cos now openssl source is locally at build/ folder (no need to get from the package manager, moreover may cause problems if versions are diff)

**Comment by ctubio** [comment]
fuck yea https://github.com/ctubio/Krypto-trading-bot/commit/78e6ed0062b625a8489d6568d3cfbf17541da6d4 fixes the missing configs; for me runs 100% now ina official raspbian

**Comment by ctubio** [comment]
well have minor bugs but will fix soOn xD

**Comment by lejacobroy** [comment]
Nice! it compiles but still can't start, as the symlink int K.sh points to `../../dist/lib/K-aarch64` (keep in mind that i'm running pi64) but this file is not in the dist/lib/ folder (only armv71). 

How can I make it create one?

Thanks!

**Comment by ctubio** [comment]
im not sure that pi64 is a good idea, it says "pi64 is an experimental OS"; anyway i will try to cross-compile for aarch64 soOn' (usually executables are created by simply running `make`)

**Comment by lejacobroy** [comment]
Yeah I know it's experimental hehe ;) If it dosen't work, I'll try to move back to raspbian next week.

**Comment by lejacobroy** [comment]
On a side note, how where the files *.a in dist/lib/ created?

I want to try to make one for aarch64..

thanks!
