### ISSUE TITLE
Bug alt markets on Gdax

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#15]
Hi Carles,

I'm struggling to get the Alt markets (LTCBTC LTCEUR ETHBTC ETHEUR) to work on Gdax.

Everything is fine, I get my info and the market info is updated just no order is sent to the market.

Or if it's sent then it's not updated.

Do you manage to reproduce the same?

**Comment by Camille92** [comment]
K thinks orders are sent but trade per second = 0 and nothing shows up on Gdax's website.

![capture d ecran 2017-06-23 a 17 19 35](https://user-images.githubusercontent.com/6861590/27488697-3d02ae3e-5838-11e7-94a7-f9a61b9c751e.png)

**Comment by ctubio** [comment]
ima try to fix first https://github.com/ctubio/Krypto-trading-bot/issues/14 (for me the orders are currently visible and open in the exchange)

**Comment by Camille92** [comment]
Yep no problem I'm going to investigate that, maybe it's just particular settings that creates the issue. (I'm puzzled because it works perfectly for BTCEUR, so I feel like it's something related to minimum tick or decimals somewhere)

**Comment by ctubio** [comment]
you still have issues after https://github.com/ctubio/Krypto-trading-bot/commit/7b4e368664fe3d5190bf4a2d44637bec65834926? for me seems its working nice for liiiiiike 10 continued minutes xD let me know if so please

**Comment by Camille92** [comment]
... Well I had to install form-data and node-uuid manually and now it doesn't work.

I get "CANNOT GET" online and that in the logs:
```

16:16:52.529 broker Exchange details { exchange: 'Coinbase',
  pair: 'BTC/EUR',
  minTick: 0.01,
  minSize: 0.01,
  makeFee: 0,
  takeFee: 0,
  hasSelfTradePrevention: true }
16:16:52.542 coinbase FIX Initiator Start
16:16:52.557 coinbase FIX Logon Connected
16:16:53.210 active Changed quoting mode to true
16:16:53.215 tbp recalculated 0.12118498614103837
16:16:53.217 main Event loop delay 200ms
^C16:17:54.044 main Handling SIGINT
16:17:54.046 main All exiting event handlers have fired, exiting application.
16:17:54.047 main Exiting with code 0
```

**Comment by Camille92** [comment]
New Logs:

```
module.js:472
    throw err;
    ^

Error: Cannot find module './app/server/main.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/K/K.js:2:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by ctubio** [comment]
this means folder `app` doesnt exists, `npm install` is supposed to create that folder xD

**Comment by Camille92** [comment]
Yep I tried but npm install gives me just that:

```
npm WARN lifecycle K.js@3.0.0~preinstall: cannot run in wd %s %s (wd=%s) K.js@3.0.0 sudo rm -rf /usr/local/etc/stunnel && sudo mkdir -p /usr/local/etc/stunnel/ && exec npm run install-packages /K
npm WARN lifecycle K.js@3.0.0~postinstall: cannot run in wd %s %s (wd=%s) K.js@3.0.0 npm run compile-server && npm run compile-client && npm run compile-public && npm run compile-bundle /K
up to date in 3.42s

```

**Comment by ctubio** [comment]
what is your npm version? mine iisss:
```
$ npm -v
5.0.3
```

**Comment by Camille92** [comment]
npm 5.0.3 & node 7.10.0 !

**Comment by ctubio** [comment]
so like https://travis-ci.org/ctubio/Krypto-trading-bot/jobs/246261734, i just restarted that job, it should finnish OK ina bit, see the expecte steps of v7.10.0 there

**Comment by Camille92** [comment]
Yep I see that, but it's still the two lines sudo rm -rf /usr/local/etc/stunnel && sudo mkdir -p /usr/local/etc/stunnel/ && exec npm run install-packages /K
and the second one that doesn't work :/

**Comment by ctubio** [comment]
mm.. make sure you are not already root, npm should not be ran as root

**Comment by Camille92** [comment]
That must be it! By default you're root on Alibaba Cloud.

**Comment by ctubio** [comment]
if you want to keep begin root, add `--unsafe-perm` to npm, like `npm --unsafe-perm install`

**Comment by Camille92** [comment]
Thank you so much, Carles ! It works perfectly I keep that in a corner of my head for next time.

I didn't know for npm as root, maybe it can be good to note is somewhere in the install?

**Comment by ctubio** [comment]
yep will add it somewhere, thanks for the report'¡

**Comment by Camille92** [comment]
Going back to the original problem (markets that don't work).

So good news -> LTC/EUR ETH/EUR work perfeclty now!

But ETH/BTC and LTC/BTC don't:
So it's a bit weird -> market width is negative and K thinks to send many orders (much more than expected I'm using boomerang) and nothing actually sent to the market.

![capture d ecran 2017-06-23 a 19 19 13](https://user-images.githubusercontent.com/6861590/27493253-5db6c244-5849-11e7-86bd-fb4668c67107.png)
![capture d ecran 2017-06-23 a 19 19 41](https://user-images.githubusercontent.com/6861590/27493254-5def4722-5849-11e7-8f17-88d4d701b1cd.png)

**Comment by Camille92** [comment]
Update: It does work when you deactivate % and chose a small number! (0.5LTC / 0.1ETH)

**Comment by ctubio** [comment]
yea i see too gdax has still some issues; is like `match` orders are not deleted from the order book or sumshit

**Comment by ctubio** [comment]
ima not fix more gdax stuff until they dont accept my first PR, hope this is fixed by their side

**Comment by Camille92** [comment]
Yep makes sense!

**Comment by Camille92** [comment]
Okay I think I have a part of the answer!


All the crypto seem "used" very fast that's why only low amounts / and trading with no APR works better.

Maybe it's linked to the time Gdax retains the cash no ?
![capture d ecran 2017-06-23 a 19 46 46](https://user-images.githubusercontent.com/6861590/27494145-e009d706-584c-11e7-8530-1b6e4da9d7d2.png)

**Comment by ctubio** [comment]
im not sure that i follow :S

**Comment by ctubio** [comment]
what im seen is also like #18, it starts ok and after a while it goes out of sync one side

**Comment by Camille92** [comment]
Okay but given what I can read, why not using version 42 instead of 43 if this one is broken ? #newernotalwaysbetter

**Comment by Camille92** [comment]
PS: the module node-uuid is not the install file, you should add it :) 

`src/server/gateways/coinbase.ts(10,23): error TS2307: Cannot find module 'node-uuid'.`

**Comment by ctubio** [comment]
node-uuid is not a dependency of K, but a dependency of a dependency of K. see:
```
$ npm ls node-uuid
```

**Comment by ctubio** [comment]
this will be fixed when https://github.com/coinbase/gdax-node/issues/62 is fixed.

**Comment by ctubio** [comment]
fuck it, lets recover gdax 4.2

**Comment by ctubio** [comment]
4.2 recovered
