### ISSUE TITLE
App terminates with 'std::domain_error' message

### ISSUE THREAD

**Issue by mattygug** [ctubio/Krypto-trading-bot#151]
On Ubuntu machine when running `nodejs K.js`

this happens

```
K.linux.57
21:41:13.512681 CF settings loaded from JSON file K OK.
21:41:13.513145 UI ready over HTTPS on external port 3000.
21:41:14.818108 GW Bitfinex allows client IP.
21:41:14.818260 GW Bitfinex:
- autoBot: no
- pair: btcusd
- minTick: 0.10000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
21:41:14.818733 DB /data/db/K.4.0.82.db loaded OK.
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be number, but is string
Aborted (core dumped)
```

thanks in advance

**Comment by ctubio** [comment]
im not able to reproduce this; are you using the latest commit?

**Comment by dddanmar** [comment]
I'm having the same issue on a fresh reinstall.

Ubuntu 16.04, node v8.4.0

K.linux.57
1:1:50.332680 CF settings loaded from JSON file K OK.
1:1:50.33352 UI ready over HTTPS on external port 3000.
1:1:53.286421 GW coinbase allows client IP.
1:1:53.286484 GW coinbase:
- autoBot: no
- pair: ETH-BTC
- minTick: 0.00001000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
1:1:53.28715 DB /data/db/K.3.6.0.db loaded OK.
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be number, but is string
[1]    11316 abort (core dumped)  node K.js

**Comment by dddanmar** [comment]
More details from strace:

> read(14, "SQLite format 3\0\4\0\1\1\0@  \0\0\0\1\0\0\0\3"..., 100) = 100
> write(1, "1:12:14.78403 ", 141:12:14.78403 )          = 14
> write(1, "DB ", 3DB )                      = 3
> write(1, "/data/db/K.3.6.0.db", 19/data/db/K.3.6.0.db)     = 19
> write(1, " loaded OK.", 11 loaded OK.)             = 11
> write(1, "\n", 1
> )                       = 1
> fcntl(14, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
> fcntl(14, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741826, l_len=510}) = 0
> fcntl(14, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
> stat("/data/db/K.3.6.0.db-journal", 0x7ffdcd086060) = -1 ENOENT (No such file or directory)
> fstat(14, {st_mode=S_IFREG|0644, st_size=3072, ...}) = 0
> stat("/data/db/K.3.6.0.db-wal", 0x7ffdcd086060) = -1 ENOENT (No such file or directory)
> fstat(14, {st_mode=S_IFREG|0644, st_size=3072, ...}) = 0
> lseek(14, 0, SEEK_SET)                  = 0
> read(14, "SQLite format 3\0\4\0\1\1\0@  \0\0\0\1\0\0\0\3"..., 1024) = 1024
> fcntl(14, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
> fcntl(14, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
> fcntl(14, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741826, l_len=510}) = 0
> fcntl(14, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
> stat("/data/db/K.3.6.0.db-journal", 0x7ffdcd086110) = -1 ENOENT (No such file or directory)
> fstat(14, {st_mode=S_IFREG|0644, st_size=3072, ...}) = 0
> lseek(14, 24, SEEK_SET)                 = 24
> read(14, "\0\0\0\1\0\0\0\3\0\0\0\0\0\0\0\0", 16) = 16
> fstat(14, {st_mode=S_IFREG|0644, st_size=3072, ...}) = 0
> stat("/data/db/K.3.6.0.db-wal", 0x7ffdcd086110) = -1 ENOENT (No such file or directory)
> fstat(14, {st_mode=S_IFREG|0644, st_size=3072, ...}) = 0
> lseek(14, 1024, SEEK_SET)               = 1024
> read(14, "\r\0\0\0\0\4\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1024) = 1024
> fcntl(14, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
> futex(0x7f2c9ffa5680, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> write(2, "terminate called after throwing "..., 48terminate called after throwing an instance of ') = 48
> write(2, "std::domain_error", 17std::domain_error)       = 17
> write(2, "'\n", 2'
> )                      = 2
> write(2, "  what():  ", 11  what():  )             = 11
> write(2, "type must be number, but is stri"..., 34type must be number, but is string) = 34
> write(2, "\n", 1
> )                       = 1
> rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
> tgkill(11484, 11484, SIGABRT)           = 0

**Comment by ctubio** [comment]
maybe this happens if the database is empty? will try to reproduce it again tomorrow

**Comment by dddanmar** [comment]
I think you've got it - I replaced the new 'K.3.6.0.db' file with an existing from from another server that had a history of trades in it and K has started fine.

**Comment by mattygug** [comment]
yes I installed it completely fresh same as dddanmar same setup
