### ISSUE TITLE
Bot incompatible nodejs 8.4 ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#152]
I'm trying to run the latest commit and some a bit before but I just run on this error :s.

I guess it comes from my version of node!

`KCONFIG=btcusd nodejs K.js
K.linux.57
13:40:33.21688 CF settings loaded from JSON file btcusd OK.
13:40:33.26187 UI ready over HTTPS on external port 3000.
nodejs: symbol lookup error: /home/camille/K/app/server/lib/K.linux.57.node: undefined symbol: curl_easy_init`

**Comment by ctubio** [comment]
seems curl version is wrong; let me bundle also libcurl at dist/lib/

**Comment by ctubio** [comment]
can you maybe paste your output of `ldd`?
```
ldd dist/lib/K.linux.57.node
```

**Comment by Camille92** [comment]
Okayy: so here is the result:

```
linux-vdso.so.1 =>  (0x00007fffa2796000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f97e2f3e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f97e2d21000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f97e2ab7000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f97e2673000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f97e2459000)
	libpng16.so.16 => not found
	libquickfix.so.16 => /home/camille/K/dist/lib/libquickfix.so.16 (0x00007f97e2157000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f97e1e4e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f97e1a83000)
	/lib64/ld-linux-x86-64.so.2 (0x0000557a20d15000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f97e187f000)
	libmysqlclient.so.18 => /home/camille/K/dist/lib/libmysqlclient.so.18 (0x00007f97e133c000)
	libstdc++.so.6 => /home/camille/K/dist/lib/libstdc++.so.6 (0x00007f97e0fb9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f97e0da3000)

```

**Comment by ctubio** [comment]
umf no libcurl at all; okok will bundle'¡
many thanks for your time'''

**Comment by ctubio** [comment]
im not sure if now you will miss other stuff, hope that was all

**Comment by ctubio** [comment]
looks like finally the fix was as @spudstr found on irc (https://github.com/ctubio/Krypto-trading-bot/commit/7be61690b8afc61f2bdb73f429888c0ef28acc45)
