### ISSUE TITLE
Bitfinex min tick issue (the return)

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#155]
Hi Carles,

I was looking at some markets and the crypto/BTC market for cheap coins is not working anymore.

I guess it's because of the big rise of BTC now it's kind of unseen territories.

See images of the bot trying to sell XRP for 4 btc each haha.
![capture d ecran 2017-08-22 a 12 13 23](https://user-images.githubusercontent.com/6861590/29560794-74c282fc-8733-11e7-9724-45abc97f2f1c.png)
![capture d ecran 2017-08-22 a 12 13 34](https://user-images.githubusercontent.com/6861590/29560802-7b1be670-8733-11e7-9efa-6c7f97294582.png)

Best!

Camille

**Comment by Camille92** [comment]
I'll be on the chat to try to find an answer to that :)

**Comment by ctubio** [comment]
i never used XRP or SAN yet; will try to look at this soOn

**Comment by CarlitoGrey** [comment]
Everytime I see this I also see the negative market width like in your first screenshot. Are we sure it's a min-tick issue and not to do with the market data being wrong?

**Comment by Camille92** [comment]
Yes @ctubio everything with a rather high value works well, the problem is on the little numbers :S 

@CarlitoGrey can be but the formula never has been rock solid so that's my first guess when I see that :)

**Comment by Camille92** [comment]
Could that be because we're using floats and not double? (I know I might sound stupid saying that but well I don't understand everything).

https://stackoverflow.com/questions/4607473/c-significant-figures

> Also storing your figures in floats, doubles or long doubles will allow for more precise operations.
> Floats offer 7 significant digits while doubles offer 16 significant digits.

**Comment by ctubio** [comment]
we dont use float (see https://github.com/ctubio/Krypto-trading-bot/search?l=C%2B%2B&q=float&type=&utf8=%E2%9C%93) but will look for possible similar errors before attempt to redestroy the mintick formula
