### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#16]
High latency on trades, how is this value being calculated as it seems a little high. Just moving over here from tribeca where the (hidden) computationalLatency was around 0-1ms. Hosted near GDAX so I'm sure it's not the connection. 

![image](https://user-images.githubusercontent.com/29517455/27489659-4209f1f8-5833-11e7-8e67-77a7566d98b0.png)

**Comment by ctubio** [comment]
10 or 20ms is not that bad, 100 and 200 starts to be xD, im not sure if your values means 1ms or 10ms or 100ms or more :S

**Comment by CarlitoGrey** [comment]
It seems to spike up to 10-20ms which is when you can't see anymore. I've raised a separate issue to perhaps correct the size. 

In any case I see in other screenshots here of people with 1ms latency - is there any more detailed information in krypto as to whether the latency is due to connectivity?

**Comment by ctubio** [comment]
is very possible that before the latency was wrongly calculated; now using FIX was recoded and may correctly work
