### ISSUE TITLE
Coinbase possible API update?

### ISSUE THREAD

**Issue by heduobacht** [ctubio/Krypto-trading-bot#161]
Hey I am trying to test your bot a bit. I tried to connect it to Coinbase but it answers

![untitled issue](https://user-images.githubusercontent.com/31292870/29639207-40900590-885a-11e7-82cb-8b4811c5999d.jpg)
Checked it with 2 different APIs to avoid misspellings in the API keys.

Is it possible that the API Version of Coinbase changed? I was not able to specify a passphrase on coinbase. In the config file on the Passphrase Line is written "NULL" even with empty passphrase it is not working. Is the not specified passphrase a problem or am I only to stupid to use the config File correctly?

**Comment by ctubio** [comment]
the api key is really invalid

passphrase is a mandatory setting; coinbase give it to you together with your api key

**Comment by b-seite** [comment]
It´s a bit confusing but you need an api from gdax not from coinbase although K only speaks from coinbase. 
The gdax api will provide you the passphrase you are missing.
