### ISSUE TITLE
Fills not correctly showing up on GDAX

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#162]
Hi Charles,

since the last commits i have the following problem on gdax: 
As you can see on the image, not all fills are shown in the List. 

![bildschirmfoto 2017-08-24 um 00 10 12](https://user-images.githubusercontent.com/540850/29640859-2d2570ec-8861-11e7-9159-d58767478a33.png)

I have another instance running bitfinex without that problem.

thanks Boris

**Comment by ctubio** [comment]
i was able to reproduce it, will try to fix soOn

**Comment by ctubio** [comment]
lets fix it at https://github.com/ctubio/Krypto-trading-bot/issues/160
