### ISSUE TITLE
Weird bug: If TBP = 0, Bot is disconnected from Bitfi

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#164]
Hi Carles,

I'm not sure how it's happening but if TBP reaches 0 (or if I manually set it to 0), the bot says it's disconnected from the exchange. And it doesn't look like it.

If I put TBP manually to 1% or more, it works again!

I use the last version with % and on Bitfinex.

**Comment by b-seite** [comment]
Hi,

i see the same behavior on gdax and bitfinex and with % or fixed values.
