### ISSUE TITLE
Unable to run in docker

### ISSUE THREAD

**Issue by Laurensvandendriessche** [ctubio/Krypto-trading-bot#169]
Following error in the log file:

Error: Error: Cannot find module './lib/K.linux.51'
    at bindings (/K/app/server/main.js:14:19)
    at Object.<anonymous> (/K/app/server/main.js:16:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/K/K.js:2:1)

**Comment by ctubio** [comment]
ok thanks' will test Docker installation somewhat soOn

**Comment by Laurensvandendriessche** [comment]
I would be glad to help you out but I'm a complete docker/node.js n00b.

Thanks for the quick response.

**Comment by Laurensvandendriessche** [comment]
I already found out it has something to do with the following lines no longer being present in the makefile:

@NODEv=v7.1.0 $(MAKE) $@

and 

NODEv=v7.1.0 ABIv=51 $(MAKE) node `(uname -s)`

I guess this is the upgrade of node v7 to node v8.

**Comment by Laurensvandendriessche** [comment]
Solved this issue myself by changeing 
FROM node:7 => FROM node:8 in the DOCKERFILE.

Error changed to 

Error: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /K/app/server/lib/libquickfix.so.16)
    at bindings (/K/app/server/main.js:14:19)
    at Object.<anonymous> (/K/app/server/main.js:16:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/K/K.js:2:1)

**Comment by JoKoT3** [comment]
Hi, I can confirm the behavior, I believe this is because node:8 is based on debian jessie (oldstable).
I'm trying to rebuild on node:8-stretch (debian stable)

furthermore, the error message still state you need nodejs >= 7.0.0, where it should state 8.0.0

**Comment by JoKoT3** [comment]
It work on NULL exchange, I'm trying GDAX now

**Comment by Laurensvandendriessche** [comment]
Confirmed working by using FROM node:8-stretch

Following errors in the log now for me (hitbtc):

13:12:42.973009 GW hitbtc WS Error while reading orders, reconnecting..
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be number, but is null
error: Forever detected script was killed by signal: SIGABRT
error: Script restart attempt #4
K.linux.57
13:12:45.788277 UI ready over HTTP on external port 3000.
13:12:45.987193 GW hitbtc allows client IP.
13:12:45.987785 GW hitbtc:
- autoBot: no
- pair: XMRUSD
- minTick: 0.01000000
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000
13:12:45.990240 DB /data/db/K.1.25.82.db loaded OK.
13:12:45.992238 TBP = 0.00000000 XMR loaded from DB.
13:12:46.133820 Unable to calculate stats, missing fair value.
13:12:46.401486 GW hitbtc WS Error while reading orders, reconnecting..
13:12:46.417847 GW hitbtc WS Streaming book levels.
13:12:47.134670 Unable to calculate stats, missing fair value.
13:12:48.134869 Unable to calculate stats, missing fair value.
13:12:49.135034 Unable to calculate stats, missing fair value.
13:12:50.134815 Unable to calculate stats, missing fair value.
13:12:51.494540 GW hitbtc WS Error while reading orders, reconnecting..
13:12:56.611801 GW hitbtc WS Error while reading orders, reconnecting..

Also localhost:3000 not available

**Comment by ctubio** [comment]
thanks for sharing `FROM node:8-stretch`

**Comment by Laurensvandendriessche** [comment]
Please update the documentation of docker run. It should be 

`docker run -p 3000:3000 kjs`. -p exposes the 3000 port of the docker image to the port of localhost.
