### ISSUE TITLE
Negative Market Width on Bitfinex

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#170]
Hi Charles,

since the commits yesterday i get a negative market width on bitfinex with ETH/USD after some hours of running.
![bildschirmfoto 2017-08-25 um 10 15 39](https://user-images.githubusercontent.com/540850/29716028-0d2778a4-89aa-11e7-8a79-a0ec72302179.png)
after a restart the width is computed correctly (or at least not negative) but some hours later it´s negative again

thanks boris

**Comment by ctubio** [comment]
im not able to reproduce this, in case it happens again to you, can you please take a screenshot of the market levels also?
thanks''

**Comment by b-seite** [comment]
Ok i also could never reproduce it again. 
I close this Issue for now.
thank you for the Help

**Comment by CarlitoGrey** [comment]
![image](https://user-images.githubusercontent.com/29517455/29839789-7d8b9300-8cf7-11e7-89e5-e5e10b3a69ea.png)

**Comment by CarlitoGrey** [comment]
Screenshot with the 'live' order book:
![image](https://user-images.githubusercontent.com/29517455/29839895-ea888684-8cf7-11e7-8cef-733a2a7571d9.png)

**Comment by ctubio** [comment]
if still happens please consider to let me know; i was not able to reproduce this since serveral days
