### ISSUE TITLE
Feature request: Using websocket to update wallet / balance with Bitfi (paid $100)

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#171]
Hello everyone,

Looking at the documentation of the Bitfinex API I have seen that we can have wallet/balance info through WebSocket.
https://bitfinex.readme.io/v2/reference#ws-auth-balance
https://bitfinex.readme.io/v2/reference#ws-auth-wallets

That would be very useful for my trading strategy (and probably for other traders around) but I don't know how to do it myself.

The idea is to have info on the balance / held,  amount of both currencies of a pair updated in real time through this channel. Basically, everything that you can see here:

![capture d ecran 2017-08-25 a 17 54 11](https://user-images.githubusercontent.com/6861590/29721698-853c2a56-89be-11e7-9f59-3621cfaaaaf2.png)

As it's not a "real" improvement and maybe not on the development road map, I'm willing to pay one of you guys if you can implement that :). I was thinking about $100 but we can talk about that (I'm not sure how much work is needed for that).

Reply here if you're interested and we can discuss it in the chat :)

PS: @ctubio Sorry to spoil the "issue" page for that but I don't see a better place where I can advertize.

**Comment by ctubio** [comment]
noworry i will implement https://bitfinex.readme.io/v2/reference#ws-auth-wallets this weekend

**Comment by ctubio** [comment]
bye bye rate limits!

**Comment by Camille92** [comment]
Thank you very much !
