### ISSUE TITLE
make install overwrites system libraries

### ISSUE THREAD

**Issue by jangrewe** [ctubio/Krypto-trading-bot#173]
I've been using K.js (or rather: tribeca) for a couple of months, then i stopped, and now i wanted to run it again. I ran `make latest`, and at some point during the process it seems to have messed up my libmysqlclient, or rather libmariadbclient, in the system libraries.
All other services suddenly started throwing errors, or just simply crashed.
After reinstalling libmariadbclient18 (Debian), i was able to restart them.
I am able to replicate this behaviour by running `make latest` again, or even `make install`.

This is pretty bad =(

**Comment by jangrewe** [comment]
I just noticed this in the `Makefile`:
```
dist:
[...]
        sudo cp dist/lib/libstdc++.so.6.0.22 dist/lib/libmysqlclient.* /usr/lib/x86_64-linux-gnu/ || :
```
This is a really, really, really, REALLY BAD IDEA™.
You should at least check if that library is already present, otherwise you'll fsck up anybody's system that isn't 100% compatible with the version you're copying there.

**Comment by ctubio** [comment]
thats why the installation is recommended in a dedicated instance.

the migration from javascript to c++ is focused in the deletion of javascript code, not in the right implementation of c++ code.

once everything is c++ we can start considering your really really really REALY obvious idea

**Comment by ctubio** [comment]
just to clarify, this is done because the way quickfix lib is compiled, the solution here is to to make quickfix compile linking not to /usr/lib but to K/lib
