### ISSUE TITLE
problem with jnode 7.10 / Ubuntu?

### ISSUE THREAD

**Issue by heikog** [ctubio/Krypto-trading-bot#177]
Hi,

I cant get it running under Ubuntu with jnode 7.10
My  output:
` node -v`
`v7.10.1`
` dpkg -l | grep -E 'nodejs|npm'`

`ii  nodejs                             7.10.1-2nodesource1~xenial1                amd64        Node.js event-based server-side javascript engine`

` node K`

`/home/user/K/app/server/main.js:12
                throw new Error('K requires Node.js v7.0.0 or greater.');`

Any Ideas ?
tia

**Comment by ctubio** [comment]
get node v8 at https://nodejs.org/en/download/package-manager/

**Comment by heikog** [comment]
Works. Thx
