### ISSUE TITLE
HitBtc error if zero balances

### ISSUE THREAD

**Issue by Laurensvandendriessche** [ctubio/Krypto-trading-bot#178]
Following error in the logs:

```16:44:16.965108 UI ready over HTTPS on external port 3000.
16:44:17.672562 GW HitBtc allows client IP.
16:44:17.672636 GW HitBtc:
autoBot: no
pair: XMRUSD
minTick: 0.01000000
minSize: 0.00100000
makeFee: 0.00000000
takeFee: 0.00000000
16:44:17.679106 DB /data/db/K.1.25.82.db loaded OK.
16:44:17.702257 TBP = 0.00000000 XMR loaded from DB.
16:44:17.868536 Unable to calculate stats, missing fair value.
16:44:18.089768 GW HitBtc WS Streaming book levels.
16:44:18.157942 GW HitBtc WS Streaming orders.
16:44:18.865524 Unable to calculate stats, missing fair value.
16:44:19.865380 Unable to calculate stats, missing fair value.
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be number, but is null
error: Forever detected script was killed by signal: SIGABRT
error: Script restart attempt #1
K.linux.57
```

Config:
`ENV HitBtcPullUrl http://api.hitbtc.com
ENV HitBtcOrderEntryUrl wss://api.hitbtc.com:8080
ENV HitBtcMarketDataUrl ws://api.hitbtc.com:80`

**Comment by ctubio** [comment]
let me try hitbtc ina fresh install

**Comment by ctubio** [comment]
i just tested hitbtc XMR/USD on a fresh install without issues.

im sorry im not able to reproduce this, are you sure you have balance in that currencies?

**Comment by ctubio** [comment]
i will try to add a better error message for this errors, so will be easy to see where it comes from

**Comment by Laurensvandendriessche** [comment]
I got 0.1 Monero on HitBtc, 0 USD. So might the issue be that I have no usd on my account over there?

If so, maybe a message that the USD balance is empty would be nice.

**Comment by ctubio** [comment]
well next time you see this error we will know from where it comes :dancer:

**Comment by mattygug** [comment]
hey, I found a similar issue on Bitfinex USD/BTC when BTC balance is zero it hangs itself up...

```
08:01:25.733231 GW Bitfinex Changed quoting state to Enabled.
08:01:36.444530 TBP 50% = 0.01539503 BTC
08:03:14.927261 TBP 51% = 0.01597843 BTC
08:04:14.944401 TBP 52% = 0.01615568 BTC
08:05:14.960168 TBP 53% = 0.01634011 BTC
08:06:09.748 main Event loop delay 700ms
08:07:00.760 main Unhandled exception! TypeError: Cannot read property 'price' of null
    at Models.Side.Bid (/home/ubuntu/k/app/server/quote-sender.js:29:30)
    at QuoteSender.checkCrossedQuotes (/home/ubuntu/k/app/server/quote-sender.js:31:23)
    at QuoteSender.sendQuote (/home/ubuntu/k/app/server/quote-sender.js:48:43)
```

I know I should put more playing money in but still it can happen during trading that one side of the trading resources goes to zero temporarily...

**Comment by ctubio** [comment]
i wish it was so easy to have 0 balances... exchanges always keep the cents in all currencies of all users

**Comment by mattygug** [comment]
yep it is not always 000 but it happened once it was completely zero ✌️
