### ISSUE TITLE
Order not found 

### ISSUE THREAD

**Issue by heikog** [ctubio/Krypto-trading-bot#179]
I am running the bot against bitfinex - and I get now and then a pop up (on Bitfinex)
**Order not found**
btw
**Invalid Price**

any idea what that means ?

tia

**Comment by ctubio** [comment]
no idea, im not able to reproduce this in any of my Bitfinex bots, and Bitfinex have too many currencies for me to start testing them all, would you consider to at least say what currency are you using?

**Comment by heikog** [comment]
sure - I am trying it with ETH/BTC
Thanks for the quick response - if I can give any other information let me know

**Comment by ctubio** [comment]
im sorry im not interested into invest my time and funds into test ETH/BTC
