### ISSUE TITLE
Ask orders and order book out of sync

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#18]
I noticed the ask order book and my own order has gone out of sync with GDAX:

![image](https://user-images.githubusercontent.com/29517455/27499966-189249da-585e-11e7-8bb2-f558f08f6268.png)

**Comment by ctubio** [comment]
will fix gdax at https://github.com/ctubio/Krypto-trading-bot/issues/15

**Comment by ctubio** [comment]
ima leave this here https://github.com/coinbase/gdax-node/issues/62

**Comment by ctubio** [comment]
fuck it, lets recover gdax 4.2

**Comment by ctubio** [comment]
4.2 recovered
