### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by Ultrahoschie** [ctubio/Krypto-trading-bot#184]
hi,

today i have updated with "make latest" ... all working good .... but when i jump to the ui of the bot .... every 5 or 10 sec. the ui break (disconnected / connected .... i on bitfinex api ..... before (1 week) all working great ... (debian)

**Comment by ctubio** [comment]
see the output of `node K`

**Comment by Ultrahoschie** [comment]
i cant understand ...

**Comment by Ultrahoschie** [comment]
Errrror: CF package.json not found.

**Comment by ctubio** [comment]
in what folder are you? package.json is in the root folder

**Comment by ctubio** [comment]
instead of `make start` you can run `node K` to see the output

**Comment by Ultrahoschie** [comment]
Use another UI port number, 3010 seems already in use .....

**Comment by ctubio** [comment]
you already have another bot runnning on port 3010, make sure you kill other bots before run another in the same port; only one single application is allowed to listen to a given port

**Comment by Ultrahoschie** [comment]
OK ...
i have 2 Bots

1 works on Port 3000
2 works on Port 3001
when i have started the UI is reconneting every 5-10sec. 

now i have stop the bot and have editing new ports

1 works now with 3005
2 works now with 3020

start the bot again .... all working great now ....

but node K says ..... `Use another UI port number, 3005 seems already in use.`

**Comment by ctubio** [comment]
`Use another UI port number, 3005 seems already in use.`

this means there is another application already fucking listening to the fucking port 3005

do a fucking `netstat` to see what is already listening to your port 3005 instead of ask to me

**Comment by Ultrahoschie** [comment]
ok i see you love fucking .... but before the fucking update no fucking other app use the fucking port

**Comment by Ultrahoschie** [comment]
netstat says ... the ports are not in use .....
