### ISSUE TITLE
[topic] Weird quotes when stdev switched on

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#185]
Hi Charles,

with the latest commits from today i get this weird quotes when stdev is set to any other than off:

![bildschirmfoto 2017-08-28 um 20 52 08](https://user-images.githubusercontent.com/540850/29788542-4ed9237a-8c33-11e7-9d36-6e394a3c3345.png)

This is a Screenshot from BCH/BTC but i get the same issue on ETH/USD

Thanks in advance
Boris

---
```
app exchange: Bitfinex/BCH/BTC
app version: Latest
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
sorry just fixed it a few minute ago at https://github.com/ctubio/Krypto-trading-bot/commit/69f6aede34611ad52dc36b012c3132785b5ff75a
