### ISSUE TITLE
Errors running in Test mode

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#190]
Hi Charles,

atm i get this message when i try to run in test mode with "exchange": "null"
It would be great to get the test mode working again because of the ability to make K better and better.
 
Thanks in advance
Boris

> K.linux.57
08:23:39.190146 CF settings loaded from JSON file K OK.
08:23:39.190586 UI ready over HTTPS on external port 3000.
08:23:39.190717 Errrror: EV signal 11 Segmentation fault (Three-Headed Monkey found):
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2EV3wtfEi+0xc0)[0x7f5f8f17b580]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f5f915334b0]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K6GwNull6configEv+0x0)[0x7f5f8f1b9a20]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2CF8externalEv+0x40)[0x7f5f8f198020]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2UI4mainEN2v85LocalINS1_6ObjectEEE+0x6b0)[0x7f5f8f1637d0]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K4mainEN2v85LocalINS0_6ObjectEEE+0x51)[0x7f5f8f162901]
node[0x1376885]
node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0x193)[0xbc1963]
node[0xc3ac4a]
node(_ZN2v88internal21Builtin_HandleApiCallEiPPNS0_6ObjectEPNS0_7IsolateE+0xb9)[0xc3b9f9]
[0x1b05662840dd]

>Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

>08:23:39.194142 THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END
08:23:39.194371 Errrror: EV signal 11 Segmentation fault (Three-Headed Monkey found):
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2EV3wtfEi+0xc0)[0x7f5f8f17b580]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f5f915334b0]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K6GwNull6configEv+0x0)[0x7f5f8f1b9a20]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2CF8externalEv+0x40)[0x7f5f8f198020]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2UI4mainEN2v85LocalINS1_6ObjectEEE+0x6b0)[0x7f5f8f1637d0]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K4mainEN2v85LocalINS0_6ObjectEEE+0x51)[0x7f5f8f162901]
node[0x1376885]
node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0x193)[0xbc1963]
node[0xc3ac4a]
node(_ZN2v88internal21Builtin_HandleApiCallEiPPNS0_6ObjectEPNS0_7IsolateE+0xb9)[0xc3b9f9]
[0x1b05662840dd]

>Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

>08:23:39.197698 THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END
08:23:39.197913 Errrror: EV signal 11 Segmentation fault (Three-Headed Monkey found):
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2EV3wtfEi+0xc0)[0x7f5f8f17b580]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f5f915334b0]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K6GwNull6configEv+0x0)[0x7f5f8f1b9a20]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2CF8externalEv+0x40)[0x7f5f8f198020]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2UI4mainEN2v85LocalINS1_6ObjectEEE+0x6b0)[0x7f5f8f1637d0]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K4mainEN2v85LocalINS0_6ObjectEEE+0x51)[0x7f5f8f162901]
node[0x1376885]
node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0x193)[0xbc1963]
node[0xc3ac4a]
node(_ZN2v88internal21Builtin_HandleApiCallEiPPNS0_6ObjectEPNS0_7IsolateE+0xb9)[0xc3b9f9]
[0x1b05662840dd]

>Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

>08:23:39.201178 THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END
08:23:39.201400 Errrror: EV signal 11 Segmentation fault (Three-Headed Monkey found):
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2EV3wtfEi+0xc0)[0x7f5f8f17b580]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f5f915334b0]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K6GwNull6configEv+0x0)[0x7f5f8f1b9a20]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2CF8externalEv+0x40)[0x7f5f8f198020]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K2UI4mainEN2v85LocalINS1_6ObjectEEE+0x6b0)[0x7f5f8f1637d0]
/home/ubuntu/Ktest/app/server/lib/K.linux.57.node(_ZN1K4mainEN2v85LocalINS0_6ObjectEEE+0x51)[0x7f5f8f162901]
node[0x1376885]
node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0x193)[0xbc1963]
node[0xc3ac4a]
node(_ZN2v88internal21Builtin_HandleApiCallEiPPNS0_6ObjectEPNS0_7IsolateE+0xb9)[0xc3b9f9]
[0x1b05662840dd]

>Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

>08:23:39.204664 THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END IS NEVER THE END
Segmentation fault (core dumped)

**Comment by ctubio** [comment]
thanks for the report'¡
