### ISSUE TITLE
App crash on manual orders

### ISSUE THREAD

**Issue by ElBibino** [ctubio/Krypto-trading-bot#196]
Hi,

When i set EXCHANGE to poloniex in config file, i have an ERR_CONNECTION_REFUSED on google chrome, but with coinbase and other network all is great.

How i can resolve this ??

**Comment by ElBibino** [comment]
All is great sorry,
But i have a problem to submit order, when i wan't create manuel order, bot disconnect automatically :/

**Comment by ctubio** [comment]
thanks will look at it soOn'

**Comment by ctubio** [comment]
log at https://github.com/ctubio/Krypto-trading-bot/issues/198
