### ISSUE TITLE
Friendly tip to be ready for Poloniex!

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#2]
Hi Carles,

I've seen you're working on Poloniex!

Haha it should be fun and bring a lot of potential profits, but a shitshow to set up! (45 markets !!!!!!)

So I stumbled on that the other day and you might be interested in it (or anyone).

At Alibaba Cloud they now offer a $30 a YEAR quite decent VPS!

So if you or anyone is interested here is my reference link -> https://account-intl.aliyun.com/register/intl_register.htm?biz_params=%7B%22intl%22%3A%22%7B%5C%22referralCode%5C%22%3A%5C%22yy0yuh%5C%22%7D%22%7D 

$20 for me and 300 dollars of credit if you register here (I don't know the details).

Have a good weekend and don't hesitate to close / modify this post if you don't find it relevant,

Best,
Camille

**Comment by ctubio** [comment]
before allow multiple exchanges ina single instance we need to allow multiple currency pairs in the same exchange :dancer: that would be great and i think easier than multiple exchanges to begin with the journey of multiple things

meanwhile, thanks for the tip'¡!

**Comment by Camille92** [comment]
I totally agree with you!

Before that I'm very thankful for the "npm run startall / stopall" functions haha. It saves me a lot of time!
