### ISSUE TITLE
Docker container fails to start (Ubuntu)

### ISSUE THREAD

**Issue by twingotwango** [ctubio/Krypto-trading-bot#204]
Following the guidelines in your documentation, installation/build appears to work correctly, however checking the docker logs reveals the below exception:

/K/K.sh: 3: /K/K.sh: ./app/server/K: not found

Am I doing something silly?

> root@ip-abc:/home/user# docker run -p 3000:3000 --name Ksh -d ksh
> 679eb1a534b6f40a292947bab9374f53af79b7190b8076388978b52526d06d16

> root@ip-abc:/home/user# docker ps
> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
> 679eb1a534b6        ksh                 "node_modules/.bin..."   3 seconds ago       Up 2 seconds        0.0.0.0:3000->3000/tcp, 5000/tcp   Ksh

> root@ip-abc:/home/user# docker logs 679eb1a534b6
> warn:    --minUptime not set. Defaulting to: 1000ms
> warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
> /K/K.sh: 3: /K/K.sh: ./app/server/K: not found
> error: Forever detected script exited with code: 127
>

**Comment by ctubio** [comment]
thanks and sorry, docker may be currently broken, i may fix docker someday :docker:

**Comment by ctubio** [comment]
maybe Docker installation is better now?

**Comment by twingotwango** [comment]
it starts now, thank you :)
