### ISSUE TITLE
libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#206]
Hi Charles,

since the latest few commits i get this Error when i try to start ./K.sh.

> ./app/server/K: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

i thought it was openssl perhaps and i try to reinstall with make openssl but then i get that error:

> make: *** Keine Regel vorhanden, um das Ziel „build-`g++“, 
  benötigt von „openssl“, zu erstellen.  Schluss.

sorry, it´s german  ;) but i think you can understand the error anyway.
when i then hardcode the shell output of g++ -dumpmachine into CROSS in the Makefile, the make openssl script works but still no working K.sh

Thanks for your help

P.S. Ubuntu 16.04 and x86_64-linux-gnu

**Comment by ctubio** [comment]
try `sudo apt-get remove libssl-dev` before compile/execute again; seems there are two openssl versions in the system; this way you will keep only the openssl version provided by K at `build/` folder, that is newer than the openssl version provided by apt

**Comment by ctubio** [comment]
in latest commit, libssl and libcrypto are not dynamic dendencies anymore; hope it helps

**Comment by b-seite** [comment]
Yesss. 
Problem is gone 

Thanks
