### ISSUE TITLE
Server running but doesnt work - bad link to "../../dist/lib/K-x86_64-redhat-linux" binary

### ISSUE THREAD

**Issue by lihaibh** [ctubio/Krypto-trading-bot#207]
I followed the guide installed the bot on my virtual machine (Virtual Box) cloned the repo, installed the dependencies and run  `make start`.
it looks like everything fine, though when i run the command to make a sanity check to the server:
`
curl -Iv https://localhost:3000
`
I get connection refused error.
The configuration file in `etc/K.json` configured with the property value `WebClientListenPort = 3000`

I realised that it might be caused by wrong installation, so i checked out the script K.sh saw it reference to a file in ./app/server/K this file is bad link to: `../../dist/lib/K-x86_64-redhat-linux` and there is no such file.
the command executed in MakeFile: `g++ -dumpmachine` results with the value: `x86_64-redhat-linux`
I tried to raplace the link to this binary file: `../../dist/lib/K-x86_64-linux-gnu`
however when i tried to run K.sh i recieved the error:
`
./app/server/K: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
`

**btw tests are passed:**
```
# make test
./node_modules/.bin/mocha --timeout 42000 --compilers ts:ts-node/register test/*.ts


  Benchmark C shared objects
    ✓ JS round is faster
    ✓ C stdev is faster

  EWMATargetPositionCalculator
    ✓ Should work


  3 passing (9ms)
```

**Environment additional info:**
```
# uname -a
Linux localhost.localdomain 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
# cat /etc/*release
CentOS Linux release 7.2.1511 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.2.1511 (Core)
CentOS Linux release 7.2.1511 (Core)
```

```
# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
node -v
v8.4.0
```

**Comment by ctubio** [comment]
after `cd app/server && ln -f -s ../../dist/lib/K-x86_64-linux-gnu K`, can  you see what is the output of `ldd app/server/K` ?

for me is:
```

 $ ldd app/server/K
        linux-vdso.so.1 (0x00007ffcc69dc000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f67216d0000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f67214b6000)
        libssl.so.1.1 => /usr/local/lib/libssl.so.1.1 (0x00007f6721247000)
        libcrypto.so.1.1 => /usr/local/lib/libcrypto.so.1.1 (0x00007f6720dbe000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6720aba000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f672089b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f67204fc000)
        /lib64/ld-linux-x86-64.so.2 (0x00005610f4601000)
```

if yours is similar, it may be that K needs to be specially compiled for redhat; in that case i will try it soOn; otherwise if you see some not found libs, means the installation steps in redhat need to be fixed

**Comment by lihaibh** [comment]
output of ldd command on K binary:
```
# ldd K
        linux-vdso.so.1 =>  (0x00007ffc799b5000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4d550b5000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f4d54e9e000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libm.so.6 => /lib64/libm.so.6 (0x00007f4d54b9b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4d5497f000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4d545be000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4d5586d000)
```

**Comment by ctubio** [comment]
thanks, in latest commit libssl and libcrypto are not dynamic dependencies anymore; hope it helps
