### ISSUE TITLE
<BotIdentifier> is disconnected

### ISSUE THREAD

**Issue by discosultan** [ctubio/Krypto-trading-bot#212]
Whenever accessing the web UI, the trading view opens, manages to fetch quotes from the exchange and then switches to error view "<BotIdentifier> is disconnected". It will automatically reload the trading view in a while and the same flow repeats.

I'm fairly certain it's due to my misconfiguration and seems that the web server is unable to contact the bot. I'm unsure where to look for errors from, though. The thing is running in docker for Windows.

**Comment by ctubio** [comment]
try running the application in the foreground to see the output

**Comment by discosultan** [comment]
Thanks, @ctubio 

It's unable to open database file, causing the node proc to exit and `forever` to restart it. Seems like an issue with file permissions.

**Comment by ctubio** [comment]
path to database is set at https://github.com/ctubio/Krypto-trading-bot/blob/master/Makefile#L182-L183

**Comment by discosultan** [comment]
I pulled latest and it's now working as expected! Not really sure what the issue was... Anyway, thanks for guidance, @ctubio!
