### ISSUE TITLE
GW coinbase Warning "request timestamp expired" -> Bad Request

### ISSUE THREAD

**Issue by zaubara** [ctubio/Krypto-trading-bot#213]
I'm trying to run the arm-linux-gnueabihf on a raspberry pi 3 (running arch linux), but something's off with the request it seems:

17:34:32.737139 GW coinbase Warning "request timestamp expired"
17:34:33.082158 QE Unable to calculate quote, missing fair value.
17:34:33.659963 GW coinbase FIX Logout.
17:34:33.926762 GW coinbase WS Streaming book levels.
17:34:34.110798 GW coinbase"error""Sorry, you could not be authenticated: Bad Request"

API key and all should be correct, I can only assume it's due to a wrong timestamp being sent. NTP sync is on, same issue after a complete reinstall (had raspbian before). cout'ed timestamps in the log are off by the set time zone, but that shouldn't be the issue

I tried to fix it on my own (compiling and debugging with gdb), but I can't seem to figure out how and where the request actually gets sent (and if that's via curl, fix or ws - i would've assumed curl, but that was a clear no)

Any idea what else I can try?
Quick follow-up: in km.h, virtual void pos() - can you please point me in the direction where those methods are actually implemented?

Thanks you!

**Comment by ctubio** [comment]
on raspberry there are still some bugs, will fix some day; but i neer experiencied this issue of the timestamp, maybe really the time of the machine is wrong?

im sorry pos() source is not at github

**Comment by zaubara** [comment]
Damn, would be great if they were... I could take a closer look what the issue might be. Do you have plans on releasing those? Would be a great thing to have with all those API keys anyway ^^
From what I can tell, ntpd is running and synchronized.
Tried switching to hitbtc and it hit me with a fatal error instead :(
