### ISSUE TITLE
Web UI not starting - Mac OS

### ISSUE THREAD

**Issue by phant13** [ctubio/Krypto-trading-bot#214]
After successful manual installation and processing K.sh file, any of localhost ip addresses with provided port not working.

K.sh file si forever processing, but I can't reach Web UI. I would be grateful for any advices. 

Thanks

**Comment by phant13** [comment]
I don't see even any K.js file to log preview

**Comment by ctubio** [comment]
where did you read is a `K.js`file?

**Comment by phant13** [comment]
https://github.com/ctubio/Krypto-trading-bot/issues/146 
Sorry, for noob question, but I really can't figure out what went wrong in my case.

**Comment by ctubio** [comment]
im sorry for deprecated information; currently `K.sh` doesnt exists, to run the app and see the output is now `./K.sh`; you may be able to see any possible error there

**Comment by phant13** [comment]
but still :/, after running  ./K.sh -
`192:marketMaker phant$ ./K.sh`
`./K.sh: line 3: ./app/server/K: No such file or directory`

K.sh code -
`192:marketMaker phant$ cat K.sh `
`#!/usr/bin/env sh`

`./app/server/K --colors "$@"`

K file exists here
`192:server phant$ ls`
`K`
`192:server phant$ pwd`
`/Users/phant/dev/marketMaker/app/server`

**Comment by ctubio** [comment]
the problem is `./app/server/K: No such file or directory`; it is usualy created on install; maybeh elps if you run `make reinstall`?

**Comment by phant13** [comment]
I tried that as well, no effect. Process seems to be OK, I don't know, but no way I reach WEB UI with any of localhost addresses.
Output:
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
rm -rf app
git checkout .
git fetch
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 15 (delta 12), reused 15 (delta 12), pack-reused 0
Unpacking objects: 100% (15/15), done.
From https://github.com/ctubio/Krypto-trading-bot
   a68341a1..97fe0401  master     -> origin/master
git merge FETCH_HEAD
Updating a68341a1..97fe0401
Fast-forward
 README.md                      |   2 +-
 dist/lib/K-aarch64-linux-gnu   | Bin 30647312 -> 30672424 bytes
 dist/lib/K-aarch64-linux-gnu.a | Bin 1111270 -> 1111270 bytes
 dist/lib/K-x86_64-linux-gnu    | Bin 35064968 -> 35078024 bytes
 dist/lib/K-x86_64-linux-gnu.a  | Bin 12788348 -> 12788532 bytes
 src/server/K.cc                |   2 +-
 src/server/db.h                |  10 +++++-----
 src/server/fn.h                |  57 ++++++++++++++++++++++++++++++++++-----------------------
 src/server/mg.h                |  15 +++++++++------
 9 files changed, 50 insertions(+), 36 deletions(-)
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
test -n "`command -v apt-get`" && sudo apt-get -y install g++ build-essential automake autoconf libtool libxml2 libxml2-dev openssl stunnel python curl gzip imagemagick\
	|| (test -n "`command -v yum`" && sudo yum -y install gcc-c++ automake autoconf libtool libxml2 libxml2-devel openssl stunnel python curl gzip ImageMagick) \
	|| (test -n "`command -v brew`" && (xcode-select --install || :) && (brew install automake autoconf libxml2 sqlite openssl zlib libuv stunnel python curl gzip imagemagick || brew upgrade || :)) \
 	|| (test -n "`command -v pacman`" && sudo pacman --noconfirm -S --needed base-devel libxml2 zlib sqlite curl libcurl-compat openssl stunnel python gzip imagemagick)
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
atk                        cgrep                      folly                      gdk-pixbuf                 glib                       libinfinity                media-info                 vala

Warning: automake 1.15.1 is already installed
Warning: autoconf 2.69 is already installed
Warning: libxml2 2.9.5 is already installed
Warning: sqlite 3.20.1 is already installed
Warning: openssl 1.0.2l is already installed
Warning: zlib 1.2.11 is already installed
Warning: libuv 1.14.1 is already installed
Warning: stunnel 5.42 is already installed
Warning: python 2.7.13_1 is already installed, it's just not linked.
You can use `brew link python` to link this version.
Warning: curl 7.55.1 is already installed
Warning: gzip 1.8 is already installed
Warning: imagemagick 7.0.7-1 is already installed
sudo mkdir -p /data/db/
Password:
sudo chown 501 /data/db
/Applications/Xcode.app/Contents/Developer/usr/bin/make gdax -s
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
depth=2 /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
verify error:num=19:self signed certificate in certificate chain
verify return:0
DONE
mkdir -p app/server
added 1 package in 11.558s
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
mkdir -p app
Building client dynamic files..
./node_modules/.bin/tsc --alwaysStrict --experimentalDecorators -t ES6 -m commonjs --outDir app/pub/js src/client/*.ts
DONE
Building client static files..
cp -R src/pub/* app/pub/
mkdir -p app/pub/js/client
DONE
Building client bundle file..
./node_modules/.bin/browserify -t [ babelify --presets [ babili es2016 ] ] app/pub/js/main.js app/pub/js/lib/*.js | ./node_modules/.bin/uglifyjs | gzip > app/pub/js/client/bundle.min.js
rm app/pub/js/*.js
DONE
cd app/server && ln -f -s ../../dist/lib/K-x86_64-apple-darwin16.6.0 K
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]


  Benchmark C shared objects
    ✓ JS round is faster
    ✓ C stdev is faster

  EWMATargetPositionCalculator
    ✓ Should work


  3 passing (25ms)

./node_modules/.bin/forever restartall
info:    Forever restarted processes:
data:        uid command script forever pid   id logfile   uptime      
data:    [0] K   /bin/sh K.sh   70488   53512    /dev/null 0:0:0:21.15 

..done! Please refresh the GUI if is currently opened in your browser.

**Comment by ctubio** [comment]
macOS is not a supported OS currently
