### ISSUE TITLE
High latency or wrong units?

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#215]
Hi charles,

since some days my bots tell me that the orders all have an at least three digits long latency, see picture below.
Because the bot is still trading as it should, i assume that you switched internally to ns? (if not, my bots all have a problem)

![bildschirmfoto 2017-09-12 um 07 05 13](https://user-images.githubusercontent.com/540850/30309078-76ee36e6-9789-11e7-83e1-959817222114.png)

Thanks a lot and greetings
boris
---
```
app exchange: Bitfinex/BCH/BTC
app version: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
thanks for the notice''
im not sure right now if is a bug or a feature :P will investigate soOn laterz

**Comment by ctubio** [comment]
after investigate it, i think the numbers and the units are now correct.
before the numbers and the units where correct too, but displayed only the time between K calculates a new quote and K send this new quote; now instead what is calculating is the time between K calculates a new quote and K receives a confirmation of the order as received OK and opened in the exchange (so now we have included in the latency the response time, before was only the request time).
