### ISSUE TITLE
UI shows disconnected but console continues

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#217]
I'm not sure if it's actually working though... I'll leave it running and see!

![image](https://user-images.githubusercontent.com/29517455/30343699-5f6c487e-97f6-11e7-8cb2-4bbd0560277a.png)

**Comment by CarlitoGrey** [comment]
Sorry console here is output from forever not direct K output, so it may have restarted I'm not sure.

**Comment by CarlitoGrey** [comment]
Nevermind... this is the forever issue isn't it!

**Comment by ctubio** [comment]
im currently looking at coinbase, seems it got some issues after fix the others :(

**Comment by ctubio** [comment]
i think the reconnection sometimes is not reconnecting; maybe increasing the timeout helps.. now it reconnect after 5 second

**Comment by Ultrahoschie** [comment]
same @bitfinex

**Comment by ctubio** [comment]
im not able to reproduce this since several days ago; let me know incase you still experience this
