### ISSUE TITLE
Docker - failed starting container

### ISSUE THREAD

**Issue by Shoananas** [ctubio/Krypto-trading-bot#218]
Hello,

I am trying to install everything to try your bot that looks very interesting.
I am using a Windows 10 Pro x64 and I'm doing the docker installation.

After executing the following command from your guide:
`docker build --no-cache -t ksh .`
There was a warning (after all steps were done) saying that since I am using Windows and the host OS is non-windows, something had to be done with the permissions (default set to -rwxr-x--x or something like that). Sadly, I forgot to copy the error so I don't remember the exact content :(

After executing the next command:
`docker run -p 3000:3000 --name Ksh -d ksh` 
There was an error that was probably linked to the previous warning.

I forgot to copy it again but I can reproduce the error using "docker start Ksh", see:
`PS C:\Users\Shoananas\Workspace\ctubio_KTB> docker ps -a`
`CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS                              NAMES`
`c430b7072b11        ksh                 "K.sh"                   2 hours ago         Created                    0.0.0.0:3000->3000/tcp, 5000/tcp   Ksh`
`65fbcb582e9c        ec1f1698c86f        "/bin/sh -c 'make ..."   3 hours ago         Exited (255) 2 hours ago                                      elated_leakey`
`PS C:\Users\Shoananas\Workspace\ctubio_KTB> docker start Ksh`
`Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"K.sh\": executable file not found in $PATH"`
`Error: failed to start containers: Ksh`

I don't know how to format it properly so I have attached a screenshot 
![docker-start-error](https://user-images.githubusercontent.com/28597460/30389570-7ea60780-98b3-11e7-8907-cb0cb49b5479.png)

Any idea about what I should do?

Thank you

**Comment by ctubio** [comment]
i think first error is not really an error, and that is normal to be displayed on winy; then in your screenshot your container seems to be created correctly, so im not sure what is the error here.

in the output of the application is where you maybe will find some error; otherwise in the installation (the docker command).

You may also use https://kitematic.com/ to easily manage your containers.

**Comment by Shoananas** [comment]
I can't start the application, the container is not started. I have retried the installation from the start to capture the errors (see screenshot).

![error-docker](https://user-images.githubusercontent.com/28597460/30487123-c8e37672-9a32-11e7-9de5-8cd229eaad44.png)


I am a total newbie with Docker (and Linux, that's why I went for the Windows installation), I'm wondering if it is normal that my working directory is empty outside of the Dockerfile.

Thank you for your link, I'm downloading it to see if it can help me.

**Comment by ctubio** [comment]
`./K.sh executable file not found` suggest the installation steps are wrong; let me know if you still are having the error; i just updated docker installation in the latest commits

**Comment by ctubio** [comment]
hope this was already fixed

**Comment by amexperts** [comment]
I am having the same issue.

**Comment by amexperts** [comment]
Also I just tried in Mac as well. So failed on both windows and mac hosts.

**Comment by ctubio** [comment]
maybe i broke Docker installation, will test soOn' thanks for the report''

**Comment by ctubio** [comment]
hope this is fixed by now
