### ISSUE TITLE
HitBTC LTC zombie orders

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#219]
Hi Carles,

I decided to add LTC to my HitBTC bot, whilst BTC works very well and is stable, the LTC bot seems to post >5 buy orders without cancelling. 

Latest commit.

**Comment by ctubio** [comment]
thanks for the report'' ima look at LTC of hitbtc soOn''

**Comment by ctubio** [comment]
for me works nice LTC/BTC on hitbtc, can you see if the issue still persists and if you can collect some logs?

**Comment by ctubio** [comment]
closing cos im not sure how to reproduce this :S
