### ISSUE TITLE
Buy/Sell Ping not displayed correctly

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#223]
I recognized that the Buy and Sell Pings are not displayed correctly in the gui at the moment.
It seems that it is not updated anymore since some commits ago because the value is fixed even on restart K and/or reload the gui

see Image attached

![bildschirmfoto 2017-09-15 um 16 08 06](https://user-images.githubusercontent.com/540850/30486288-57769f52-9a30-11e7-95fb-1cf8c1e60b13.png)

---
```
app exchange: Coinbase/BTC/EUR & Bitfinex various
app version: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by YokiWorks** [comment]
I am seeing the same thing, @b-seite do you know which commit break it?
