### ISSUE TITLE
"How to" for Quote Parameter Settings

### ISSUE THREAD

**Issue by BigFav** [ctubio/Krypto-trading-bot#229]
Hi all,

I was wondering if there is any form of guide to how to set the quote parameters. I am new to the space, but see the value in a trading bot and this looks like a great repo! However, the long list of quote parameters are a bit overwhelming to take in at once, so I was wondering if there was a guide of sorts to help see what each knob does without having to put money on the line.

Thanks!
Favian

**Comment by ctubio** [comment]
not yet; would you suggest a desired format? or a simply wiki-style pages is enough?

**Comment by BigFav** [comment]
Wiki styling is quite expressive especially if you look into the [advanced markdown](https://help.github.com/articles/working-with-advanced-formatting/), so that would definitely be sufficient.

Was looking for some shortcuts or places to begin, but based on your response it seems like I have to run my own benchmarks from scratch. Thanks for the quick reply.

**Comment by ctubio** [comment]
someday, meanwhile lets keep the list of open issues clean

**Comment by ctubio** [comment]
we can take years until the XMR have some bounty, and some more years until someone wirtes this howto, so ima close this zombie issue
