### ISSUE TITLE
problem with GDAX & new config method

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#230]
Hi charles,

i tried to use the latest Commit with the new config method. Unfortunately i get no connection to GDAX Fix. I think that i cross-double-checked everything. But this is the result:
K build x86_64-linux-gnu 2017-09-19 02:54:52.955033268+00:00.
K version 0day.
10:58:10.187249 UI ready over HTTPS on external port 3000.
10:58:10.480792 GW COINBASE allows client IP.
10:58:10.480916 GW COINBASE:
- autoBot: yes
- pair: BTC-EUR
- minTick: 0.01000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
10:58:10.481289 DB /data/db/K.3.0.2.db loaded OK.
10:58:10.481659 DB loaded Quoting Parameters OK.
10:58:10.483483 DB loaded 203 historical Trades.
10:58:10.483769 DB loaded 0 STDEV Periods.
10:58:10.483855 DB loaded EWMA Long = 0.00000000.
10:58:10.483893 DB loaded EWMA Medium = 0.00000000.
10:58:10.483917 DB loaded EWMA Short = 0.00000000.
10:58:10.483985 DB loaded TBP = 0.06517307 BTC.
10:58:10.484809 QE Warrrrning: Unable to calculate quote, missing fair value.
10:58:10.734574 GW COINBASE WS Streaming book levels.
**10:58:11.508768 GW COINBASE FIX Logout.**
10:58:13.778490 TBP 50% = 0.06473645 BTC

maybe anyone any idea?
thanks boris

**Comment by ctubio** [comment]
let me try Coinbase this afternoon; yesterday night i just tested NULL, Bitfinex and Hitbtc (and NULL was not working as expected), maybe Coinbase was fucked in the last commit too :dancer:
