### ISSUE TITLE
Gdax - here is where it freeze

### ISSUE THREAD

**Issue by Jorman** [ctubio/Krypto-trading-bot#232]
Hi, many tnx for your latest commit, very good!

Finally I've some more data to you to post, with all 2 kind of debug you set-up!

```
19:47:05.551942 DEBUG GW totals toAsk:0.00283026 toBid:0.04125211 min:0.01000000.
19:47:05.552065 DEBUG GW quote¿ {"ask":{"price":3290.99,"size":0.01},"bid":{"price":3283.7,"size":0.01}}.
19:47:05.552194 DEBUG GW quote! {"ask":{"price":3294.87,"size":0.01},"bid":{"price":3283.7,"size":0.01}}.
19:47:05.552295 DEBUG GW  save  ASK id 40000004-afff-4fff-bf00-00000cffffff:: [0]: 0.01000000 BTC at price 3294.87000000 EUR.
19:47:05.552369 DEBUG GW memory 3/1.
19:47:05.552474 DEBUG GW  send  ASK id 40000004-afff-4fff-bf00-00000cffffff: 0.01000000 BTC at price 3294.87000000 EUR.
19:47:47.610874 DEBUG GW reply  ::8537e272-7fb8-46cf-9991-87b11e8bbf8b [3]: 0.00000000/0.00000000 at price 0.00000000.
19:47:47.610985 DEBUG GW remove 40000008-8fff-4fff-bf00-00003200000d::8537e272-7fb8-46cf-9991-87b11e8bbf8b.
19:47:47.611020 DEBUG GW memory 2/0.
```
Let me know if can help in anyway

**Comment by ctubio** [comment]
im sorry this long only shows that and order for 0.00283026 was about to be created but minimum was 0.01000000, so the exchange replied with status 3 (cancelled), and the order was removed from the memory; all coOl

**Comment by Jorman** [comment]
Damm, is the point where stop, sometimes here sometimes in another situation. The conclusion is right, but all the times don't create the order and go ahead to try to sell first, depending on TBP

**Comment by ctubio** [comment]
well im currently investigating coinbase, hope this and other bugs will be fixed soOn''

**Comment by Jorman** [comment]
Many tnx!

**Comment by donaldforest** [comment]
Looks like the same with HitBTC. Bot create 2 orders with first 4-5 min trade and freeze about 3 minutes. Then bot stop create orders, just show some debug info.
