### ISSUE TITLE
Unable to fetch data from POLONIEX symbol "ETH_BTC" with API_CURRENCY=BTC/ETH

### ISSUE THREAD

**Issue by gMare** [ctubio/Krypto-trading-bot#233]
Hi, I'm using commit 694082a.
I have set up everything as described in K.sh and gdax is working fine already. But when I tried to add poloniex, I'm having trouble configuring it. With `API_CURRENCY=BTC/ETH` I get the error in the title, but [it's a valid pair](https://poloniex.com/public?command=returnOrderBook&currencyPair=BTC_ETH). If I flip the pair, it starts to work, but then it complains that I do not have enough ETH (I only have BTC on poloniex atm).

Why is the pair flipped from what I've specified in the config and why does it then want to trade with ETH?

**Comment by ctubio** [comment]
because at https://poloniex.com/exchange#btc_eth says `ETH/BTC`

let me switch it to see if helps, anyway im not using poloniex so i dont care much
