### ISSUE TITLE
Won't install on latest commit

### ISSUE THREAD

**Issue by nate551** [ctubio/Krypto-trading-bot#236]
Docker install

/bin/sh: 2: cannot create dist/sslcert/fix.gdax.com.pem: Directory nonexistent
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "Coinbase, Inc.", CN = *.gdax.com
verify return:1
DONE
make[2]: *** [gdax] Error 2
Makefile:238: recipe for target 'gdax' failed
make[2]: Leaving directory '/K'
make[1]: *** [packages] Error 2
Makefile:165: recipe for target 'packages' failed
make[1]: Leaving directory '/K'
Makefile:182: recipe for target 'docker' failed
make: *** [docker] Error 2
The command '/bin/sh -c make docker' returned a non-zero code: 2
PS G:\GDAX\Docker_LTC>

raspbian install

/bin/sh: 2: cannot create dist/sslcert/fix.gdax.com.pem: Directory nonexistent
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "Coinbase, Inc.", CN = *.gdax.com
verify return:1
DONE
Makefile:238: recipe for target 'gdax' failed
make[2]: *** [gdax] Error 2
make[2]: Leaving directory '/home/nate551/K'
Makefile:165: recipe for target 'packages' failed
make[1]: *** [packages] Error 2
make[1]: Leaving directory '/home/nate551/K'
Makefile:175: recipe for target 'install' failed
make: *** [install] Error 2
nate551@raspberrypi:~/K$

**Comment by nate551** [comment]
updated the make file by replacing dist with etc in the gdax and packages sections
updated the K-stunnel.conf to point at the new location of the .pem file

this got the app to start and connect but now I am getting signal 11 errors

22:58:42.127316 Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x15)[0xa5e7bca245]
./app/server/K(_ZN1K2EV3wtfEi+0x399)[0xa5e7bca709]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f4d74eb3030]
./app/server/K(_ZN1K2UI4uiUpEPNS_5uiTXTEPN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS3_14adl_serializerEEE+0x31)[0xa5e7beb011]
./app/server/K(_ZN1K2UI7appPushEv+0x70)[0xa5e7bee300]
./app/server/K(_ZNSt6thread11_State_implISt12_Bind_simpleIFZN1K2UI5delayEdEUlvE_vEEE6_M_runEv+0xb6)[0xa5e7bef966]
./app/server/K(+0x56094f)[0xa5e7fd094f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7f4d75226494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f4d74f68aff]


I suspect it might be due to my poking around - but I figured I would update the ticket

**Comment by ctubio** [comment]
yea im sorry, im currently killing binary files inside the repo to make it more lightweight (cos git clone currently downloads too much useless megabytes), hope for the installation steps to be fixed soOn'' meanwhile consider to use some old commit/release

**Comment by ctubio** [comment]
hope the installation is fixed after the last commit
