### ISSUE TITLE
K with GDAX crashes when opening UI

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#241]
Hi Charles,

i mentioned it already in issue #234 but because it is still persistent i open a new issue:

with GDAX and latest commit every time i try to open the GUI, K crashes with this Message:

09:03:14.587689 GW COINBASE Quoting state changed to CONNECTED.
09:03:16.435224 UI 1 currently connected, last connection was from ::ffff:212.59.47.85.
09:03:17.434014 Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x28)[0x501db8]
./app/server/K(_ZN1K2EV3wtfEi+0x396)[0x502286]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f68a5f154b0]
./app/server/K(_ZN1K2UI4uiUpEPNS_5uiTXTEPN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS3_14adl_serializerEEE+0x3d)[0x5231bd]
./app/server/K(_ZN1K2UI7appPushEv+0x80)[0x5265c0]
./app/server/K(_ZNSt6thread11_State_implISt12_Bind_simpleIFZN1K2UI5delayEdEUlvE_vEEE6_M_runEv+0xc7)[0x527d17]
./app/server/K[0x8a5a1f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f68a62b16ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f68a5fe73dd]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

09:03:20.441265 GW COINBASE Attempting to cancel all open orders, please wait..

**Comment by ctubio** [comment]
i should look at gdax this weekend

**Comment by b-seite** [comment]
Oh i was a bit too quick: after a make clean && make install i get the same Problem on Bitfinex, so it not seems to be a GDAX problem anymore:

12:23:40.244583 UI 1 currently connected, last connection was from ::ffff:212.59.47.85.
12:23:40.632464 UI authorization attempt from ::ffff:212.59.47.85
12:23:40.755260 UI authorization attempt from ::ffff:212.59.47.85
12:23:40.774939 UI authorization attempt from ::ffff:212.59.47.85
12:23:40.899223 UI authorization attempt from ::ffff:212.59.47.85
12:23:41.023007 UI authorization attempt from ::ffff:212.59.47.85
12:23:41.148651 UI authorization attempt from ::ffff:212.59.47.85
12:23:43.122615 Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x28)[0x501db8]
./app/server/K(_ZN1K2EV3wtfEi+0x396)[0x502286]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7ff1437fa4b0]
./app/server/K(_ZN1K2UI4uiUpEPNS_5uiTXTEPN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS3_14adl_serializerEEE+0x3d)[0x5231bd]
./app/server/K(_ZN1K2UI7appPushEv+0x80)[0x5265c0]
./app/server/K(_ZNSt6thread11_State_implISt12_Bind_simpleIFZN1K2UI5delayEdEUlvE_vEEE6_M_runEv+0xc7)[0x527d17]
./app/server/K[0x8a5a1f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7ff143b966ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7ff1438cc3dd]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

12:23:46.127259 GW BITFINEX Attempting to cancel all open orders, please wait..
 
could that be a compiler issue? Because Ubuntu 16.04 still uses gcc 4.8 by default i tried to install gcc6 according to this https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91

Thanks in advance
boris

**Comment by streetbits** [comment]
any updates with this issue?

**Comment by ctubio** [comment]
the issue is short, feel free to read meanwhile quickly scrolling down to write a comment
