### ISSUE TITLE
make startall not working

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#242]
Hi Charles,

make startall is not working properly atm.
K tries to start the instances without the suffix, i guess:

ubuntu@ip-172-31-29-241:~/K$ make startall
ls -1 *.sh | cut -d / -f2 | cut -d . -f1 | grep -v ^_ | xargs -I % make K=% start -s
**START K-ethusd DONE
START K DONE**
No Sockets found in /var/run/screen/S-ubuntu.

with a make start K works as expected:
ubuntu@ip-172-31-29-241:~/K$ make start
**START K.sh DONE**

**Comment by ctubio** [comment]
im sorry too many changes lately and too little time for tests, this weekend (that start now yayY'¡!) ima review all
