### ISSUE TITLE
Two issues during install

### ISSUE THREAD

**Issue by Grayjack64** [ctubio/Krypto-trading-bot#243]
I'm having two issues that may be related. The first is on the ssh git. It fails each time I try to pull from the repository. See below:

root@user-740U3M:/home/user# git clone ssh://git@github.com/ctubio/Krypto-trading-bot K
Cloning into 'K'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I then switched to pulling  from the normal github url like so: root@user-740U3M:/home/user# git clone https://github.com/ctubio/Krypto-trading-bot.git K. That seemed to work but I then had the following error on 'make install'

Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
Makefile:122: recipe for target 'zlib' failed
make[2]: *** [zlib] Error 1
make[2]: Leaving directory '/home/user/K'
Makefile:98: recipe for target 'dist' failed
make[1]: *** [dist] Error 2
make[1]: Leaving directory '/home/user/K'
Makefile:185: recipe for target 'install' failed
make: *** [install] Error 2

Any suggestions would be greatly appreciated. Thanks

**Comment by b-seite** [comment]
I had the same Problems. For me the Solution was installing GCC 6. On ubuntu 16.04 default is still Version 4.8
Google knows many tips installing it. 
Hope that helps

**Comment by ctubio** [comment]
your problem is `Permission denied (publickey).`; consider to read https://help.github.com/articles/error-permission-denied-publickey/ or use ` git clone https://github.com/ctubio/Krypto-trading-bot K` instead of ssh

**Comment by Grayjack64** [comment]
That did it. I reinstalled g++6 and all seems fine now. Thank you for the help
