### ISSUE TITLE
Errrror: Signal 11 Segmentation fault - running on Bitfinex exchange

### ISSUE THREAD

**Issue by Grayjack64** [ctubio/Krypto-trading-bot#245]
19:16:54.282538 Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x28)[0x501db8]
./app/server/K(_ZN1K2EV3wtfEi+0x396)[0x502286]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f6c6c9d44b0]
./app/server/K(_ZN1K2UI4uiUpEPNS_5uiTXTEPN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS3_14adl_serializerEEE+0x3d)[0x5231bd]
./app/server/K(_ZN1K2UI7appPushEv+0x80)[0x5265c0]
./app/server/K(_ZNSt6thread11_State_implISt12_Bind_simpleIFZN1K2UI5delayEdEUlvE_vEEE6_M_runEv+0xc7)[0x527d17]
./app/server/K[0x8a5a1f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f6c6cd706ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f6c6caa63dd]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by streetbits** [comment]
Getting the same error indicating "deprecated K version found"

**Comment by ctubio** [comment]
thanks for the report'¡ lets fix it at #244
