### ISSUE TITLE
UI is not showing while console is working

### ISSUE THREAD

**Issue by tyfzheng** [ctubio/Krypto-trading-bot#246]
![image](https://user-images.githubusercontent.com/32116214/30770053-433152e6-9fec-11e7-9f1a-f6b57259796e.png)
![image](https://user-images.githubusercontent.com/32116214/30770055-4b5a99dc-9fec-11e7-98de-a576881eb56e.png)

As you can see, the console output indicates the UI is ready. But somehow I can't display from using the browser (firefox or chrome)

In addition, for bitfinex, is the bot using "margin" account or "exchange" account?

Thx

**Comment by ctubio** [comment]
morning'' seems server is running over HTTPS but the client attempts to connect over HTTP

try browsing on port `3000` to the ip of the machine running the server with `https://` protocol

hope it helps''
