### ISSUE TITLE
Still problems with GDAX after a while

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#248]
Hi charles,

i still have problems running K on GDAX. After a while(30-90min) K stops trading without any error. Even with debug activated, there ist just this showing up when it occurs:

14:13:28.612928 DEBUG GW memory 2/1.
14:13:28.613563 DEBUG GW cancel BID id 34000000-feff-4fff-bff0-000000400000::1070456b-dae0-4ea9-9657-8e2d0a263710.
14:13:36.390499 DEBUG GW quote? {"ask":{"price":3240.76,"size":0.0157154933936265},"bid":{"price":3239.9,"size":0.0157154933936265}}.
14:13:36.390646 DEBUG GW quote¿ {"ask":{"price":3240.76,"size":0.0157154933936265},"bid":{"price":3239.9,"size":0.0157154933936265}}.
14:13:36.390732 DEBUG GW quote¿ {"ask":{"price":0.0,"size":0.0157154933936265},"bid":{"price":3239.9,"size":0.031430986787253}}.
14:13:36.390797 DEBUG GW quote¿ {"ask":{"price":0.0,"size":0.0157154933936265},"bid":{"price":3239.9,"size":0.031430986787253}}.
14:13:36.390870 DEBUG GW quote¿ {"ask":{"price":0.0,"size":0.0157154933936265},"bid":{"price":3240.06008239571,"size":0.031430986787253}}.
14:13:36.390933 DEBUG GW quote¿ {"ask":{"price":0.0,"size":0.0157154933936265},"bid":{"price":3240.04,"size":0.031430986787253}}.
14:13:36.390981 DEBUG GW quote¿ {"ask":{"price":0.0,"size":0.0157154933936265},"bid":{"price":3240.04,"size":0.031430986787253}}.
14:13:36.391019 DEBUG GW quote¿ {"ask":{"price":0.0,"size":0.0157154933936265},"bid":{"price":3240.04,"size":0.031430986787253}}.
14:13:36.391051 DEBUG GW totals toAsk:0.01606833 toBid:0.11489411 min:0.01000000.
14:13:36.391086 DEBUG GW quote¿ {"ask":{"price":0.0,"size":0.01571549},"bid":{"price":3240.04,"size":0.03143098}}.
14:13:36.391122 DEBUG GW quote! {"ask":{"price":0.0,"size":0.0},"bid":{"price":3240.04,"size":0.03143098}}.
14:13:36.391177 DEBUG GW  save  BID id 34000000-feff-4fff-bff0-000000400000::1070456b-dae0-4ea9-9657-8e2d0a263710 [1]: 0.01000000 BTC at price 3240.02000000 EUR.
14:13:36.391210 DEBUG GW memory 2/1.
14:13:36.391784 DEBUG GW cancel BID id 34000000-feff-4fff-bff0-000000400000::1070456b-dae0-4ea9-9657-8e2d0a263710.

Hope that you have any idea.
Thanks in advance
Boris

**Comment by ctubio** [comment]
yep confirmed it gets stuck somewhere on coinbase
