### ISSUE TITLE
Boomerang mode enters stalemate when tbp is held and ping set to bidside. 

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#25]
![image](https://user-images.githubusercontent.com/29517455/27561146-e8badc96-5abe-11e7-857e-2e08aac03292.png)

**Comment by CarlitoGrey** [comment]
In this instance a super-op caused me to buy more than my TBP. Due to the order of buys and sells K seems to have lost track of the ping/pong relationships but wouldn't sell my holding to get under the TBP. 

I think in this situation K should sell the holding until under the TBP and able to perform a ping. This also occurs on start up with more BTC than your TBP.

**Comment by ctubio** [comment]
that is normal, you may want to tweak tbp or stop blocking a side waiting for pings
