### ISSUE TITLE
Getting make errors when try to do a manual make install

### ISSUE THREAD

**Issue by s3479** [ctubio/Krypto-trading-bot#250]
running this:  git clone https://github.com/ctubio/Krypto-trading-bot.git K ends with errors.

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  593k  100  593k    0     0   853k      0 --:--:-- --:--:-- --:--:--  852k
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
Makefile:121: recipe for target 'zlib' failed
make[2]: *** [zlib] Error 1
make[2]: Leaving directory '/home/test/K'
Makefile:97: recipe for target 'dist' failed
make[1]: *** [dist] Error 2
make[1]: Leaving directory '/home/test/K'
Makefile:184: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by ctubio** [comment]
maybe the gcc in your target machine is not version 6?
travis was throwing this same error on gcc-4.9 (https://travis-ci.org/ctubio/Krypto-trading-bot/jobs/279078737), and after update to 6 this was fixed but now is throwing another error; please let me know if you have also this second error cos currently fixing travis is not a priority (but could be if it affects you too)

**Comment by ctubio** [comment]
ok thanks, i will try a machine with http://releases.ubuntu.com/16.04/ubuntu-16.04.3-desktop-amd64.iso

**Comment by s3479** [comment]
I just manually did this: Fixed g++ version for travis to the system and it's been compiling for a good 25 min so far.

**Comment by s3479** [comment]
Opened another session, not sure of the version now. got this: 
login as: sam
sam@172.16.0.31's password:
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-96-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

8 packages can be updated.
0 updates are security updates.


Last login: Sun Sep 24 09:27:27 2017 from 172.16.0.99
sam@krobot:~$ sudo apt update
[sudo] password for sam:
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Hit:3 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial InRelease
Hit:4 https://deb.nodesource.com/node_8.x xenial InRelease
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Fetched 306 kB in 0s (384 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
8 packages can be upgraded. Run 'apt list --upgradable' to see them.
sam@krobot:~$ sudo apt list --upgradable
Listing... Done
cpp-5/xenial 5.4.1-2ubuntu1~16.04 amd64 [upgradable from: 5.4.0-6ubuntu1~16.04.4]
g++-5/xenial 5.4.1-2ubuntu1~16.04 amd64 [upgradable from: 5.4.0-6ubuntu1~16.04.4]
gcc-5/xenial 5.4.1-2ubuntu1~16.04 amd64 [upgradable from: 5.4.0-6ubuntu1~16.04.4]
gcc-5-base/xenial 5.4.1-2ubuntu1~16.04 amd64 [upgradable from: 5.4.0-6ubuntu1~16.04.4]
libasan2/xenial 5.4.1-2ubuntu1~16.04 amd64 [upgradable from: 5.4.0-6ubuntu1~16.04.4]
libgcc-5-dev/xenial 5.4.1-2ubuntu1~16.04 amd64 [upgradable from: 5.4.0-6ubuntu1~16.04.4]
libmpx0/xenial 5.4.1-2ubuntu1~16.04 amd64 [upgradable from: 5.4.0-6ubuntu1~16.04.4]
libstdc++-5-dev/xenial 5.4.1-2ubuntu1~16.04 amd64 [upgradable from: 5.4.0-6ubuntu1~16.04.4]

**Comment by ctubio** [comment]
closing cos on http://releases.ubuntu.com/16.04/ubuntu-16.04.3-server-amd64.iso i did `make travis install start screen` and got a running bot OK
