### ISSUE TITLE
Errrror: Signal 6 Aborted on Coinbase

### ISSUE THREAD

**Issue by Grayjack64** [ctubio/Krypto-trading-bot#252]
I get the error  pasted below while running on Coinbase. Generally it takes about 5 - 10 minutes before it appears but will sometimes take a good bit longer. I have also run an instance connected to Bitfinex and the error never appeared. I included the Backtrace shown in the console as well as the Signal 6 error. Thank you for your help

*** Error in `./app/server/K': double free or corruption (fasttop): 0x00007f590c026690 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f5929d707e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f5929d7937a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f5929d7d53c]
./app/server/K(_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N8nlohmann10basic_jsonISt3mapSt6vectorS5_blmdSaNS8_14adl_serializerEEEESt10_Select1stISE_ESt4lessIS5_ESaISE_EE8_M_eraseEPSt13_Rb_tree_nodeISE_E+0x40f)[0x5090af]
./app/server/K(_ZN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEED1Ev+0x3d)[0x50964d]
./app/server/K(_ZN1K2UI6uiHoldENS_5uiTXTEN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS2_14adl_serializerEEE+0x2f4)[0x522654]
./app/server/K(_ZN1K2UI6uiSendENS_5uiTXTEN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS2_14adl_serializerEEEb+0xaf)[0x5229ff]
./app/server/K(_ZN1K2PG10calcWalletENS_7mWalletE+0x5b7)[0x527797]
./app/server/K(_ZZN1K2PG4mainEvENKUlNS_6mOrderEE0_clES1_+0x152)[0x527dd2]
./app/server/K(_ZN1K2OG16updateOrderStateENS_6mOrderE+0x2d0)[0x52a1e0]
./app/server/K(_ZZN1K2OG4mainEvENKUlNS_6mOrderEE_clES1_+0x20c)[0x52e29c]
./app/server/K(_ZN1K2GW9gwOrderUpENS_6mOrderE+0xcd)[0x55445d]
./app/server/K(_ZN1K10GwCoinbase7fromAppERKN3FIX7MessageERKNS1_9SessionIDE+0x4e7)[0x55aec7]
./app/server/K(_ZN3FIX7Session6verifyERKNS_7MessageEbb+0x452)[0x58aa92]
./app/server/K(_ZN3FIX7Session4nextERKNS_7MessageERKNS_12UtcTimeStampEb+0x9f5)[0x58d285]
./app/server/K(_ZN3FIX7Session4nextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_12UtcTimeStampEb+0x1db)[0x58e78b]
./app/server/K(_ZN3FIX16SocketConnection12readMessagesERNS_13SocketMonitorE+0x66)[0x5a6136]
./app/server/K(_ZN3FIX16SocketConnection4readERNS_15SocketConnectorE+0x3a)[0x5a621a]
./app/server/K(_ZN3FIX16ConnectorWrapper7onEventERNS_13SocketMonitorEi+0x19)[0x5fb489]
./app/server/K(_ZN3FIX13SocketMonitor14processReadSetERNS0_8StrategyER6fd_set+0xde)[0x5a481e]
./app/server/K(_ZN3FIX13SocketMonitor5blockERNS0_8StrategyEbd+0x2c8)[0x5a4bc8]
./app/server/K(_ZN3FIX15SocketConnector5blockERNS0_8StrategyEbd+0x31)[0x5fb3a1]
./app/server/K(_ZN3FIX15SocketInitiator7onStartEv+0x55)[0x59fcc5]
./app/server/K(_ZN3FIX9Initiator11startThreadEPv+0xa)[0x59c1ca]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f592a0ca6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f5929e003dd]
======= Memory map: ========
00400000-00a6a000 r-xp 00000000 08:02 17714575                           /home/danny/K/build-x86_64-linux-gnu/local/bin/K-x86_64-linux-gnu
00c6a000-00c92000 r--p 0066a000 08:02 17714575                           /home/danny/K/build-x86_64-linux-gnu/local/bin/K-x86_64-linux-gnu
00c92000-00ca3000 rw-p 00692000 08:02 17714575                           /home/danny/K/build-x86_64-linux-gnu/local/bin/K-x86_64-linux-gnu
00ca3000-00cac000 rw-p 00000000 00:00 0 
014e6000-016c6000 rw-p 00000000 00:00 0                                  [heap]
7f5904000000-7f5904021000 rw-p 00000000 00:00 0 
7f5904021000-7f5908000000 ---p 00000000 00:00 0 
7f590c000000-7f590c9ad000 rw-p 00000000 00:00 0 
7f590c9ad000-7f5910000000 ---p 00000000 00:00 0 
7f5910000000-7f5910021000 rw-p 00000000 00:00 0 
7f5910021000-7f5914000000 ---p 00000000 00:00 0 
7f5914000000-7f591411a000 rw-p 00000000 00:00 0 
7f591411a000-7f5918000000 ---p 00000000 00:00 0 
7f591affe000-7f591afff000 ---p 00000000 00:00 0 
7f591afff000-7f591b7ff000 rw-p 00000000 00:00 0 
7f591c000000-7f591c021000 rw-p 00000000 00:00 0 
7f591c021000-7f5920000000 ---p 00000000 00:00 0 
7f5921ffc000-7f5921ffd000 ---p 00000000 00:00 0 
7f5921ffd000-7f59227fd000 rw-p 00000000 00:00 0 
7f59227fd000-7f59227fe000 ---p 00000000 00:00 0 
7f59227fe000-7f5922ffe000 rw-p 00000000 00:00 0 
7f5922ffe000-7f5922fff000 ---p 00000000 00:00 0 
7f5922fff000-7f59237ff000 rw-p 00000000 00:00 0 
7f59237ff000-7f5923800000 ---p 00000000 00:00 0 
7f5923800000-7f5924000000 rw-p 00000000 00:00 0 
7f5924000000-7f5924021000 rw-p 00000000 00:00 0 
7f5924021000-7f5928000000 ---p 00000000 00:00 0 
7f59282a9000-7f59282bf000 r-xp 00000000 08:02 15996279                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f59282bf000-7f59284be000 ---p 00016000 08:02 15996279                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f59284be000-7f59284bf000 r--p 00015000 08:02 15996279                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f59284bf000-7f59284c0000 rw-p 00016000 08:02 15996279                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f59284c0000-7f59284c1000 ---p 00000000 00:00 0 
7f59284c1000-7f5928cc1000 rw-p 00000000 00:00 0 
7f5928cc1000-7f5928cd8000 r-xp 00000000 08:02 15995466                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f5928cd8000-7f5928ed8000 ---p 00017000 08:02 15995466                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f5928ed8000-7f5928ed9000 r--p 00017000 08:02 15995466                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f5928ed9000-7f5928eda000 rw-p 00018000 08:02 15995466                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f5928eda000-7f5928edc000 rw-p 00000000 00:00 0 
7f5928edc000-7f5928ee1000 r-xp 00000000 08:02 15995411                   /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f5928ee1000-7f59290e1000 ---p 00005000 08:02 15995411                   /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f59290e1000-7f59290e2000 r--p 00005000 08:02 15995411                   /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f59290e2000-7f59290e3000 rw-p 00006000 08:02 15995411                   /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f59290e3000-7f59290e5000 r-xp 00000000 08:02 15995419                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f59290e5000-7f59292e4000 ---p 00002000 08:02 15995419                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f59292e4000-7f59292e5000 r--p 00001000 08:02 15995419                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f59292e5000-7f59292e6000 rw-p 00002000 08:02 15995419                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f59292e6000-7f59292f1000 r-xp 00000000 08:02 15995413                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f59292f1000-7f59294f0000 ---p 0000b000 08:02 15995413                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f59294f0000-7f59294f1000 r--p 0000a000 08:02 15995413                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f59294f1000-7f59294f2000 rw-p 0000b000 08:02 15995413                   /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f59294f2000-7f59294f8000 rw-p 00000000 00:00 0 
7f59294f8000-7f59294f9000 ---p 00000000 00:00 0 
7f59294f9000-7f5929cf9000 rw-p 00000000 00:00 0 
7f5929cf9000-7f5929eb9000 r-xp 00000000 08:02 15995314                   /lib/x86_64-linux-gnu/libc-2.23.so
7f5929eb9000-7f592a0b9000 ---p 001c0000 08:02 15995314                   /lib/x86_64-linux-gnu/libc-2.23.so
7f592a0b9000-7f592a0bd000 r--p 001c0000 08:02 15995314                   /lib/x86_64-linux-gnu/libc-2.23.so
7f592a0bd000-7f592a0bf000 rw-p 001c4000 08:02 15995314                   /lib/x86_64-linux-gnu/libc-2.23.so
7f592a0bf000-7f592a0c3000 rw-p 00000000 00:00 0 
7f592a0c3000-7f592a0db000 r-xp 00000000 08:02 15995460                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f592a0db000-7f592a2da000 ---p 00018000 08:02 15995460                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f592a2da000-7f592a2db000 r--p 00017000 08:02 15995460                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f592a2db000-7f592a2dc000 rw-p 00018000 08:02 15995460                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f592a2dc000-7f592a2e0000 rw-p 00000000 00:00 0 
7f592a2e0000-7f592a3e8000 r-xp 00000000 08:02 15995384                   /lib/x86_64-linux-gnu/libm-2.23.so
7f592a3e8000-7f592a5e7000 ---p 00108000 08:02 15995384                   /lib/x86_64-linux-gnu/libm-2.23.so
7f592a5e7000-7f592a5e8000 r--p 00107000 08:02 15995384                   /lib/x86_64-linux-gnu/libm-2.23.so
7f592a5e8000-7f592a5e9000 rw-p 00108000 08:02 15995384                   /lib/x86_64-linux-gnu/libm-2.23.so
7f592a5e9000-7f592a5ec000 r-xp 00000000 08:02 15995338                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f592a5ec000-7f592a7eb000 ---p 00003000 08:02 15995338                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f592a7eb000-7f592a7ec000 r--p 00002000 08:02 15995338                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f592a7ec000-7f592a7ed000 rw-p 00003000 08:02 15995338                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f592a7ed000-7f592a813000 r-xp 00000000 08:02 15995286                   /lib/x86_64-linux-gnu/ld-2.23.so
7f592a82c000-7f592a9f8000 rw-p 00000000 00:00 0 
7f592aa0f000-7f592aa12000 rw-p 00000000 00:00 0 
7f592aa12000-7f592aa13000 r--p 00025000 08:02 15995286                   /lib/x86_64-linux-gnu/ld-2.23.so
7f592aa13000-7f592aa14000 rw-p 00026000 08:02 15995286                   /lib/x86_64-linux-gnu/ld-2.23.so
7f592aa14000-7f592aa15000 rw-p 00000000 00:00 0 
7fff4c0e7000-7fff4c108000 rw-p 00000000 00:00 0                          [stack]
7fff4c11b000-7fff4c11d000 r--p 00000000 00:00 0                          [vvar]
7fff4c11d000-7fff4c11f000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
12:40:05.244361 Errrror: Signal 6 Aborted (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x28)[0x500d08]
./app/server/K(_ZN1K2EV3wtfEi+0x396)[0x5011d6]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f5929d2e4b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f5929d2e428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f5929d3002a]
/lib/x86_64-linux-gnu/libc.so.6(+0x777ea)[0x7f5929d707ea]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f5929d7937a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f5929d7d53c]
./app/server/K(_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N8nlohmann10basic_jsonISt3mapSt6vectorS5_blmdSaNS8_14adl_serializerEEEESt10_Select1stISE_ESt4lessIS5_ESaISE_EE8_M_eraseEPSt13_Rb_tree_nodeISE_E+0x40f)[0x5090af]
./app/server/K(_ZN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEED1Ev+0x3d)[0x50964d]
./app/server/K(_ZN1K2UI6uiHoldENS_5uiTXTEN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS2_14adl_serializerEEE+0x2f4)[0x522654]
./app/server/K(_ZN1K2UI6uiSendENS_5uiTXTEN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS2_14adl_serializerEEEb+0xaf)[0x5229ff]
./app/server/K(_ZN1K2PG10calcWalletENS_7mWalletE+0x5b7)[0x527797]
./app/server/K(_ZZN1K2PG4mainEvENKUlNS_6mOrderEE0_clES1_+0x152)[0x527dd2]
./app/server/K(_ZN1K2OG16updateOrderStateENS_6mOrderE+0x2d0)[0x52a1e0]
./app/server/K(_ZZN1K2OG4mainEvENKUlNS_6mOrderEE_clES1_+0x20c)[0x52e29c]
./app/server/K(_ZN1K2GW9gwOrderUpENS_6mOrderE+0xcd)[0x55445d]
./app/server/K(_ZN1K10GwCoinbase7fromAppERKN3FIX7MessageERKNS1_9SessionIDE+0x4e7)[0x55aec7]
./app/server/K(_ZN3FIX7Session6verifyERKNS_7MessageEbb+0x452)[0x58aa92]
./app/server/K(_ZN3FIX7Session4nextERKNS_7MessageERKNS_12UtcTimeStampEb+0x9f5)[0x58d285]
./app/server/K(_ZN3FIX7Session4nextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_12UtcTimeStampEb+0x1db)[0x58e78b]
./app/server/K(_ZN3FIX16SocketConnection12readMessagesERNS_13SocketMonitorE+0x66)[0x5a6136]
./app/server/K(_ZN3FIX16SocketConnection4readERNS_15SocketConnectorE+0x3a)[0x5a621a]
./app/server/K(_ZN3FIX16ConnectorWrapper7onEventERNS_13SocketMonitorEi+0x19)[0x5fb489]
./app/server/K(_ZN3FIX13SocketMonitor14processReadSetERNS0_8StrategyER6fd_set+0xde)[0x5a481e]
./app/server/K(_ZN3FIX13SocketMonitor5blockERNS0_8StrategyEbd+0x2c8)[0x5a4bc8]
./app/server/K(_ZN3FIX15SocketConnector5blockERNS0_8StrategyEbd+0x31)[0x5fb3a1]
./app/server/K(_ZN3FIX15SocketInitiator7onStartEv+0x55)[0x59fcc5]
./app/server/K(_ZN3FIX9Initiator11startThreadEPv+0xa)[0x59c1ca]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f592a0ca6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f5929e003dd]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by ctubio** [comment]
thanks'' im currently looking at coinbase; i feel like the solution is to get rid of quickfix and use simply websockets like other exchanges.. anyway ima try to fix quickfix integration a bit moar

**Comment by charbarb** [comment]
@ctubio Does the the codebase have support for Websockets with Coinbase/GDAX now?

**Comment by ctubio** [comment]
Coinbase still have some errors that im still fighting with.. for example the UI sometimes accumulates closed trades as still opened trades.. but these are other issues
