### ISSUE TITLE
Errrror: Signal 6 Aborted (Three-Headed Monkey found) - Gdax

### ISSUE THREAD

**Issue by aborgx** [ctubio/Krypto-trading-bot#253]
Error after last update on Gdax:

./K.sh
K build x86_64-linux-gnu 2017-09-25 20:38:58.628274707+00:00.
K version 0day.
21:45:18.227618 UI ready over HTTPS on external port 3000.
21:45:19.420983 GW COINBASE allows client IP.
21:45:19.421103 GW COINBASE:

21:45:19.421430 DB /data/db/K.3.0.2.db loaded OK.
21:45:19.421809 DB loaded Quoting Parameters OK.
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be number, but is null
21:45:19.423849 Errrror: Signal 6 Aborted (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x28)[0x500d08]
./app/server/K(_ZN1K2EV3wtfEi+0x396)[0x5011d6]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7fc22bcb84b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7fc22bcb8428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fc22bcba02a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x16d)[0x92158d]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6)[0x891166]
./app/server/K[0x8911b1]
./app/server/K[0x8928d9]
./app/server/K(_ZN8nlohmann6detail20get_arithmetic_valueINS_10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEEEdLi0EEEvRKT_RT0_+0xa0)[0x511b90]
./app/server/K(_ZN1K2OG4loadEv+0x177)[0x518c97]
./app/server/K(_ZN1K2OG4mainEv+0x9)[0x4f5119]
./app/server/K(main+0x87)[0x4f5047]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fc22bca3830]
./app/server/K(_start+0x29)[0x4f9369]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by ctubio** [comment]
thanks, lets fix it at https://github.com/ctubio/Krypto-trading-bot/issues/252
