### ISSUE TITLE
Allow dynamic currencies

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#254]
Hi Charles, can you please add this 2 new currencies as they are now traded on Bitfinex.

Thank you!

PS: would that be possible to not have to add them but just make every combination of 3 or for letters working ?

And resulting with an error if you're trying to put in pair that doesn't exist :)

**Comment by ctubio** [comment]
we need a numberic ID for each currency, thats why need to be know by the source in advance; i will try to extract a unique numeric value based on the asciii characters of each currency.

**Comment by ctubio** [comment]
added NEO and ETP at https://github.com/ctubio/Krypto-trading-bot/commit/b54e433878a108b16007d42ec3a9c258de9775f6, still hardcoded

**Comment by ctubio** [comment]
take care after upgrade database is lost cos filename changed
