### ISSUE TITLE
Bug: Pdiv is not working with PingPong mode

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#255]
Hello Carles,

A bug I've noticed, pdiv is absolutely not respected when using PingPong mode, basically meaning that this mode is broken at the moment.

It will just sell and buy at the same time all the time!

**Comment by Camille92** [comment]
Well after more investigation, instead of respecting pdiv it changes pdiv to 50%.

**Comment by ctubio** [comment]
but pDiv is not related with the quoting mode in any way :S i dont see what you see

**Comment by Camille92** [comment]
Hey Charles, thank you for your answer.

I don't think it's something linked with pdiv but it acts like if pdiv was
put to 50%.

I'll send you a video tomorrow morning but if you can do it if you want
tonight.

Basically "held" status is not called before 50% of your stack is sold
(given that TBP = 100%).

So pdiv doesn't play it's role of limiting the divergence !

**Comment by Camille92** [comment]
Hi Carles,

Here is a video of the bug so you can try to redo it.

https://s.nimbus.everhelper.me/share/1143643/z1v1qdthck3s53hllr6n

As you can see, the bot TBP is around 16 ZEC (maximum value) but with a pdiv of 10%, so in theory if I have less than 14.4 ZEC in the account the bot should only try to buy.

However here it's still selling.

After I do a test by changing pdiv % to normal pdiv with this time a pdiv of 0 but you can see that there is not a change in the behavior of the bot.

Ps: At the moment I'm using the last version with .json config but I think it's ok as nothing has been changed in the ping-pong quoting engine since then.

**Comment by ctubio** [comment]
i think a thread has uninitialized global variables :dancer: will test'¡
