### ISSUE TITLE
Unable to cal quote, missing fair value on HitBTC XMR/BTC

### ISSUE THREAD

**Issue by s3479** [ctubio/Krypto-trading-bot#256]
What OS is best for running the bot?
I'm running Ubuntu 16.04 server. May be the problem?
I get the following error and bot will not do a buy. How do I fix this error?

K build x86_64-linux-gnu 2017-09-26 12:21:57.346076952-05:00.
K version -2commits..
* 49858db Fixed first make install.
* d5370f5 Updated release asset with included K binary.
17:37:24.925002 UI ready over HTTPS on external port 7993.
17:37:26.096672 GW HITBTC allows client IP.
17:37:26.096697 GW HITBTC:
- autoBot: no
- pair: XMRBTC
- minTick: 0.00000100
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
17:37:26.103823 DB /data/db/K.1.25.0.db loaded OK.
17:37:26.143800 DB loaded Quoting Parameters OR reading defaults instead.
17:37:26.183816 DB loaded 0 historical Trades.
17:37:26.224066 DB loaded 0 STDEV Periods.
17:37:26.260336 DB loaded EWMA Long = 0.00000000.
17:37:26.260362 DB loaded EWMA Medium = 0.00000000.
17:37:26.260374 DB loaded EWMA Short = 0.00000000.
17:37:26.297365 DB loaded TBP = 0.00000000 XMR.
17:37:26.297434 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:26.645033 GW HITBTC WS Streaming book levels.
17:37:26.928306 GW HITBTC WS Streaming orders.
17:37:27.297642 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:28.297765 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:29.297880 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:30.297997 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:31.298115 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:32.298230 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:33.298345 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:34.298483 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:35.298600 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:36.298718 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:37.298829 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:38.298943 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:39.299057 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:40.299173 QE Warrrrning: Unable to calculate quote, missing fair value.
17:37:42.143005 TBP 50% = 0.45268363 XMR
17:37:51.226176 TBP 50% = 0.45284579 XMR
17:37:51.647866 TBP 50% = 0.45266889 XMR
17:37:55.927079 TBP 50% = 0.45283104 XMR
17:37:57.070433 TBP 50% = 0.45265416 XMR
17:38:03.034193 TBP 50% = 0.45283104 XMR
17:38:05.089856 TBP 50% = 0.45263943 XMR
17:38:11.647198 TBP 50% = 0.45283104 XMR
17:38:20.224492 TBP 50% = 0.45268363 XMR
17:38:33.444365 TBP 50% = 0.45280155 XMR
17:38:33.833037 TBP 50% = 0.45262470 XMR
17:38:48.429640 TBP 50% = 0.45280155 XMR
17:38:49.096448 TBP 50% = 0.45259524 XMR

running with tdp 50 pDiv 50
K build x86_64-linux-gnu 2017-09-26 12:21:57.346076952-05:00.
K version -4commits..
* b54e433 Added NEO and ETP hardcoded curriencies.
* 48de2b2 Updated macOS out of travis.
* 49858db Fixed first make install.
* d5370f5 Updated release asset with included K binary.
18:43:41.014726 UI ready over HTTPS on external port 7993.
18:43:41.928984 GW HITBTC allows client IP.
18:43:41.929021 GW HITBTC:
- autoBot: no
- pair: XMRBTC
- minTick: 0.00000100
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
18:43:41.929276 DB /data/db/K.1.25.0.db loaded OK.
18:43:41.929701 DB loaded Quoting Parameters OK.
18:43:41.929796 DB loaded 1 historical Trades.
18:43:41.933622 DB loaded 536 STDEV Periods.
18:43:41.934006 DB loaded EWMA Long = 0.02423173.
18:43:41.934029 DB loaded EWMA Medium = 0.02422372.
18:43:41.934040 DB loaded EWMA Short = 0.02421577.
18:43:41.934156 DB loaded TBP = 50.00000000 XMR.
18:43:41.934226 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:41.939289 UI 1 currently connected, last connection was from ::ffff:172.16.0.99.
18:43:42.276587 GW HITBTC WS Streaming book levels.
18:43:42.696842 GW HITBTC WS Streaming orders.
18:43:42.934298 GW HITBTC Error Wrong request params.
18:43:42.934334 GW HITBTC WS Error while reading orders, reconnecting..
18:43:42.934434 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:43.934559 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:44.934657 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:45.934793 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:46.934888 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:47.934981 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:48.807035 GW HITBTC WS Streaming orders.
18:43:48.935088 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:49.935188 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:50.935284 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:51.935380 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:52.935480 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:53.935640 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:54.935756 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:55.935874 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:56.935989 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:57.936083 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:58.936201 QE Warrrrning: Unable to calculate quote, missing fair value.
18:43:59.936297 QE Warrrrning: Unable to calculate quote, missing fair value.
18:44:00.838893 GW HITBTC Quoting state changed to CONNECTED.
18:44:02.271981 TBP 5519% = 50.00000000 XMR

**Comment by ctubio** [comment]
if there is a problem with the OS, the bot refuses to be executed, so seems your OS is compatible; your issue may be bad codes; i will review soOn XMR on hitbtc (hope for it after fixing quickfix of coinbase )

**Comment by ctubio** [comment]
errr.. looking at your logs, thats normal, that is K trying to connect, and the messages stops as soon as it connects, and instead it start calculating TBP; i dont see any problem in your logs
