### ISSUE TITLE
some additional things I had to do to install

### ISSUE THREAD

**Issue by charbarb** [ctubio/Krypto-trading-bot#257]
You may want to note in the install section the following things:

On Ubuntu I had to:

1. install node
2. install npm
3. `sudo ln -s /usr/bin/nodejs /usr/bin/node`
4. Install gcc-6 and then reboot the entire linux box.

**Comment by ctubio** [comment]
yep but last 4th step is not needed anymore. first 3 for now are needed, but soOn will get rid of node/npm dependency
