### ISSUE TITLE
Poloniex Order Book "Disconnected"

### ISSUE THREAD

**Issue by perelin** [ctubio/Krypto-trading-bot#258]
Hi,

the order book pane is showing "Disconnected" on both sides and the bot isn´t trading at all. GUI+Console Output sems to suggest that the bot has connected correctly to th exchange (polo)

![bildschirmfoto 2017-09-27 um 08 54 36](https://user-images.githubusercontent.com/517976/30899803-b7eafe3e-a361-11e7-98e4-e1d6b8f8a431.png)

![bildschirmfoto 2017-09-27 um 08 59 41](https://user-images.githubusercontent.com/517976/30899919-4236238e-a362-11e7-9fbc-d14375d01024.png)

K build x86_64-linux-gnu 2017-09-26 22:16:50.469609608+00:00.
K version 0day.
06:50:30.952672 UI ready over HTTPS on external port 6969.
06:50:31.605081 GW POLONIEX allows client IP.
06:50:31.605162 GW POLONIEX:
- autoBot: no
- pair: BTC_XMR
- minTick: 0.00001000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
06:50:31.606952 DB /data/db/K.6.0.25.db loaded OK.
06:50:31.608037 DB loaded Quoting Parameters OK.
06:50:31.608138 DB loaded 0 historical Trades.
06:50:31.609875 DB loaded 585 STDEV Periods.
06:50:31.610040 DB loaded EWMA Long = 0.02434516.
06:50:31.610089 DB loaded EWMA Medium = 0.02434061.
06:50:31.610122 DB loaded EWMA Short = 0.02433236.
06:50:31.610222 DB loaded TBP = 3.62561664 BTC.
06:50:31.611262 QE Warrrrning: Unable to calculate quote, missing fair value.
06:50:34.094218 UI 1 currently connected, last connection was from ::ffff:2.246.73.54.
06:51:31.744075 TBP 43% = 3.51677725 BTC
06:51:33.665519 TBP 43% = 3.50809582 BTC
06:52:30.268832 TBP 43% = 3.51677725 BTC
06:52:31.877125 TBP 41% = 3.39780040 BTC
06:52:44.698044 GW POLONIEX Quoting state changed to CONNECTED.
06:52:56.849520 TBP 41% = 3.39920240 BTC
06:53:12.189867 TBP 41% = 3.40060556 BTC
06:53:32.005774 TBP 40% = 3.26798935 BTC
06:53:41.981446 TBP 40% = 3.26394737 BTC

Just update to the last version.

Any idea where to start digging?

**Comment by ctubio** [comment]
long time since i dont test poloniex, will do maybe if somebody votes for it once the payments are activated (there is a random activation timer that i hope it will trigger soOn)

**Comment by ctubio** [comment]
closing cos nobody cares since +1 month ago
