### ISSUE TITLE
Can't do a buy or a manual buy in bot, only does sells

### ISSUE THREAD

**Issue by s3479** [ctubio/Krypto-trading-bot#260]
What do I need to do to have the bot buy? If I try to do a manual buy in the bot, it just cancels. Have done 100s of buys and sells on the exchange before and during the bot run. I Have not been able to do a buy with the bot. Please help. Has always shown the unknownheld, and has never had a buyping on the bot. Have changed settings to all that's possible with no luck in buying. Tried with dif pairs and dif exchanges, same problem. Screen shot while on HitBTC. min is 0.01 on buy or sell.
[thanks for the screenshot!]

**Comment by ctubio** [comment]
is long time i dont see `UnknownHeld`, let me see if i can reproduce this on XMR/BTC of HitBTC

**Comment by s3479** [comment]
No, set to Manual 50 each, no help

**Comment by s3479** [comment]
![image](https://user-images.githubusercontent.com/24231198/30941594-de31a904-a3ab-11e7-9fcf-27fa206c7008.png)

**Comment by ctubio** [comment]
now is missing the `%` to be checked (so tbp and pDib are 50 % not 50 BTC)

if you say that enabling `%` doesnt work then i will get hands dirty, thanks'¡

**Comment by s3479** [comment]
ok, let me try %.

**Comment by s3479** [comment]
Looks like it's not working
![image](https://user-images.githubusercontent.com/24231198/30944720-6f699036-a3bf-11e7-831b-c3beb75ea43b.png)

**Comment by ctubio** [comment]
allright will investigate XMR/BTC this weekend together with LTC of https://github.com/ctubio/Krypto-trading-bot/issues/219

**Comment by s3479** [comment]
Not going to pay you to fix your broken version!!!!

**Comment by ctubio** [comment]
i didnt asked you to pay me, not to use my broken version!!!!!

**Comment by s3479** [comment]
your payment timer for $800+ to unlock features is active.

**Comment by ctubio** [comment]
really?

then was yourself asking to yourself

https://en.wikipedia.org/wiki/Consumer_behaviour#The_consumer.27s_purchase_decision_process:_an_overview

yourself alone is engaged in a series of mental evaluations of alternatives, searching for the best value; im not asking to you nothing; you can pay or not whatever you want to who you want, im not and i will not ask you nothing cos you dont have nothing that i need.

btw i dont think you have read the README, the payment is optional only for lazy users like you that only open issues. normal users that collaborate doing pull request enjoy the bot for free.

go read the readme, or go do whatever you want, but do not bother me with your stupid screams.

**Comment by s3479** [comment]
I'm not looking to use it for free, don't expect to. I have not been able to get it to work correctly for me and your attitude is what makes me look elsewhere.

**Comment by ctubio** [comment]
im not a happy human, good look out there
