### ISSUE TITLE
Bitfinex send seg fault 

### ISSUE THREAD

**Issue by tyfzheng** [ctubio/Krypto-trading-bot#263]
02:59:34.529141 Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x15)[0x55f2a6eb15e5]                                                                                                                                                                                             
./app/server/K(_ZN1K2EV3wtfEi+0x399)[0x55f2a6eb1aa9]                                                                                                                                                                                               
/lib/x86_64-linux-gnu/libc.so.6(+0x357f0)[0x7f34146287f0]                                                                                                                                                                                          
./app/server/K(do_ssl3_write+0x303)[0x55f2a709b493]                                                                                                                                                                                                
./app/server/K(ssl3_write_bytes+0x2a8)[0x55f2a709be28]                                                                                                                                                                                             
./app/server/K(SSL_write+0x30)[0x55f2a70ab260]                                                                                                                                                                                                     
./app/server/K(_ZN3uWS9WebSocketILb0EE4sendEPKcmNS_6OpCodeEPFvPS1_PvbS6_ES6_+0x579)[0x55f2a6ef7869]                                                                                                                                                
./app/server/K(_ZN1K10GwBitfinex4sendENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_5mSideEddNS_10mOrderTypeENS_12mTimeInForceEbm+0x352)[0x55f2a6f00792]                                                                                  
./app/server/K(_ZN1K2OG9sendOrderENS_5mSideEddNS_10mOrderTypeENS_12mTimeInForceEbb+0x521)[0x55f2a6edc751]                                                                                                                                          
./app/server/K(_ZN1K2QE5startENS_5mSideENS_6mLevelEb+0x447)[0x55f2a6edcd27]                                                                                                                                                                        
./app/server/K(_ZN1K2QE11updateQuoteENS_6mLevelENS_5mSideEb+0x177)[0x55f2a6edd957]
./app/server/K(_ZN1K2QE14sendQuoteToAPIEv+0xf6)[0x55f2a6edda96]
./app/server/K(_ZN1K2QE9calcQuoteEv+0x2e2)[0x55f2a6eddd82]
./app/server/K(_ZZN1K2QE4mainEvENUlvE5_4_FUNEv+0xce)[0x55f2a6ede61e]
./app/server/K(_ZZN1K2MG4mainEvENKUlNS_7mLevelsEE0_clES1_+0x186d)[0x55f2a6ed72bd]
./app/server/K(_ZN1K2GW9gwLevelUpENS_7mLevelsE+0x34)[0x55f2a6f08144]
./app/server/K(_ZZN1K10GwBitfinex4bookEvENKUlPN3uWS9WebSocketILb0EEEPcmNS1_6OpCodeEE2_clES4_S5_mS6_+0x12ea)[0x55f2a6f3253a]
./app/server/K(_ZN3uWS9WebSocketILb0EE14handleFragmentEPcmjibPNS_14WebSocketStateILb0EEE+0x270)[0x55f2a6efc230]
./app/server/K(_ZN3uWS9WebSocketILb0EE6onDataEPN2uS6SocketEPcm+0x1d2)[0x55f2a6efcb22]
./app/server/K(_ZN2uS6Socket12sslIoHandlerIN3uWS9WebSocketILb0EEEEEvP4Pollii+0x187)[0x55f2a6eeb927]
./app/server/K(_ZN4Loop3runEv+0x111)[0x55f2a6ee3981]
./app/server/K(_ZN1K10GwBitfinex4bookEv+0x1b3)[0x55f2a6f0da23]
./app/server/K(+0x56194f)[0x55f2a72ba94f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76da)[0x7f34149c16da]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x5f)[0x7f34146fbd7f]

**Comment by ctubio** [comment]
this must be fixed in latest commit; now websockets are thread safe
