### ISSUE TITLE
Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).

### ISSUE THREAD

**Issue by pbrdebruijn** [ctubio/Krypto-trading-bot#264]
Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x15)[0x555c26c08025]
./app/server/K(_ZN1K2EV3wtfEi+0x399)[0x555c26c084e9]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7facbbdc0030]
/lib/x86_64-linux-gnu/libc.so.6(+0x8405f)[0x7facbbe1105f]
./app/server/K(_ZN1K2PG10calcWalletENS_7mWalletE+0x6b8)[0x555c26c37c18]
./app/server/K(_ZZN1K2PG4mainEvENKUlNS_6mOrderEE0_clES1_+0x2ac)[0x555c26c3856c]
./app/server/K(_ZN1K2OG16updateOrderStateENS_6mOrderE+0x32d)[0x555c26c31c7d]
./app/server/K(_ZZN1K2OG4mainEvENKUlNS_6mOrderEE_clES1_+0x21b)[0x555c26c34dab]
./app/server/K(_ZN1K2GW9gwOrderUpENS_6mOrderE+0x130)[0x555c26c5c190]
./app/server/K(_ZN1K10GwCoinbase7fromAppERKN3FIX7MessageERKNS1_9SessionIDE+0x4e7)[0x555c26c62877]
./app/server/K(_ZN3FIX7Session6verifyERKNS_7MessageEbb+0x2fb)[0x555c26c922fb]
./app/server/K(_ZN3FIX7Session4nextERKNS_7MessageERKNS_12UtcTimeStampEb+0x9b1)[0x555c26c94c71]
./app/server/K(_ZN3FIX7Session4nextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_12UtcTimeStampEb+0x1a3)[0x555c26c96093]
./app/server/K(_ZN3FIX16SocketConnection12readMessagesERNS_13SocketMonitorE+0x70)[0x555c26cad3e0]
./app/server/K(_ZN3FIX16SocketConnection4readERNS_15SocketConnectorE+0x28)[0x555c26cad4a8]
./app/server/K(_ZN3FIX16ConnectorWrapper7onEventERNS_13SocketMonitorEi+0x19)[0x555c26d017b9]
./app/server/K(_ZN3FIX13SocketMonitor14processReadSetERNS0_8StrategyER6fd_set+0xe6)[0x555c26cabb76]
./app/server/K(_ZN3FIX13SocketMonitor5blockERNS0_8StrategyEbd+0x298)[0x555c26cabed8]
./app/server/K(_ZN3FIX15SocketConnector5blockERNS0_8StrategyEbd+0x24)[0x555c26d016e4]
./app/server/K(_ZN3FIX15SocketInitiator7onStartEv+0x45)[0x555c26ca7145]
./app/server/K(_ZN3FIX9Initiator11startThreadEPv+0xa)[0x555c26ca362a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7facbc133494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7facbbe75aff]

**Comment by ctubio** [comment]
many thanks for your report, i will try to fix it this weekend at https://github.com/ctubio/Krypto-trading-bot/issues/262
