### ISSUE TITLE
Strange Prices on POLONIEX

### ISSUE THREAD

**Issue by usovichivan** [ctubio/Krypto-trading-bot#265]
Hi.
looks like prices on POLONIEX sometimes right but more often wrong.

12:21:57.103557 GW POLONIEX TRADE SELL 0.01000000 BTC at price 0.07053000 ETH (value 0.00070530 ETH)
12:21:57.392875 GW POLONIEX TRADE SELL 0.01000000 BTC at price 0.57054000 ETH (value 0.00570540 ETH)
12:22:40.559533 TBP 82% = 0.00829521 BTC
12:23:11.662606 GW POLONIEX TRADE SELL 0.01000000 BTC at price 0.57057000 ETH (value 0.00570570 ETH)
12:24:23.920339 GW POLONIEX TRADE SELL 0.01000000 BTC at price 0.57057000 ETH (value 0.00570570 ETH)
12:25:35.209210 GW POLONIEX TRADE SELL 0.01000000 BTC at price 0.07071000 ETH (value 0.00070710 ETH)
12:26:51.494377 GW POLONIEX TRADE SELL 0.01000000 BTC at price 0.57076000 ETH (value 0.00570760 ETH)

**Comment by ctubio** [comment]
thanks for the report, i may look at poloniex in case somebody votes for it
