### ISSUE TITLE
Bitfinex Zombie orders when switched to EWMA_LS

### ISSUE THREAD

**Issue by lunnh** [ctubio/Krypto-trading-bot#267]
I am testing ETH/USD on Bitfinex. It's running smoothly on manual tbp mode.
However when I switched to EWMA_LS lots of zombie orders appeared, which can be found on Bitfinex's web UI. CXL is enabled already. Things resumed normal when I switched back to manual mode.
![bitfinex1](https://user-images.githubusercontent.com/32397882/31028683-6d7149b8-a581-11e7-8189-5192d05e1a04.png)
![bitfinex2](https://user-images.githubusercontent.com/32397882/31028686-71e50f84-a581-11e7-9fbf-8d41315e0e81.png)

**Comment by ctubio** [comment]
many thanks for the report, can i ask what quoting mode are you using? (was AK-47?)

**Comment by lunnh** [comment]
I am using Boomerang. Thanks

**Comment by ctubio** [comment]
hope this is fixed after https://github.com/ctubio/Krypto-trading-bot/commit/1ec4d544063259534b9fb687300431e95b7a8526
