### ISSUE TITLE
GDAX Crash with: double free or corruption (out): 0x00007f758c10e3f0

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#268]
Hi Charles,

K crashed with that message this evening:

19:33:12.216218 TBP 60% = 0.06909415 BTC
*** Error in `./app/server/K': double free or corruption (out): 0x00007f758c10e3f0 ***
*** Error in `./app/server/K': malloc(): memory corruption (fast): 0x00007f758c0e42b0 ***

never seen this before, any ideas?

Thanks Boris
---
```
app exchange: GDAX/BTC/EUR
app version: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
it doesnt says anything else? i cant see from where it comes from with this log, but i will try to reproduce too

**Comment by b-seite** [comment]
Unfortunately no. Just the two Lines and after that nothing else. 
I‘ll try to reproduce it with Debug on. Maybe then we‘ll See some more

**Comment by ctubio** [comment]
ok thanks'' noworry to much, more detailed logs may be impossible for this bug, thanks again'¡

**Comment by ctubio** [comment]
is long time since i dont see this error, may be fixed; anyway i keep running gdax so if happens again i will notice
