### ISSUE TITLE
Bug with GDAX, the bot keeps reseting

### ISSUE THREAD

**Issue by frod123** [ctubio/Krypto-trading-bot#269]
Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x15)[0x5588cced6025]
./app/server/K(_ZN1K2EV3wtfEi+0x399)[0x5588cced64e9]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f374fce6030]
./app/server/K(_ZNSt6thread11_State_implISt12_Bind_simpleIFZN1K2QE5startENS2_5mSideENS2_6mLevelEbEUlvE_vEEE6_M_runEv+0x24)[0x5588ccf011c4]
./app/server/K(+0x4c2aaf)[0x5588cd242aaf]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7f375005a494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f374fd9baff]

**Comment by ctubio** [comment]
thanks for the report'' will fix gdax segfauls at https://github.com/ctubio/Krypto-trading-bot/issues/268
