### ISSUE TITLE
GDAX does not Reconnect

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#270]
Hi Charles,

i have the following problem with K: 
the bot is not automatically reconnecting to GDAX after a disconnect. Happened last night. Bot is still alive but never again tries to reconnect...
This is a bad behavior of the bot, maybe we can get a try-to-reconnect-loop every several minutes? 
 
see here:
23:56:34.392361 TBP 60% = 0.07264909 BTC
23:56:34.399732 TBP 60% = 0.06604426 BTC
23:56:52.431178 GW COINBASE TRADE SELL 0.01100733 BTC at price 3675.28000000 EUR (value 40.45501980 EUR)
23:57:04.552182 TBP 60% = 0.07264889 BTC
23:57:04.559932 TBP 60% = 0.06604450 BTC
23:59:59.076866 GW COINBASE Quoting state changed to DISCONNECTED.
23:59:59.077015 GW COINBASE FIX Logout.
00:00:17.272097 GW COINBASE Quoting state changed to CONNECTED.
00:00:17.274098 GW COINBASE FIX success Logon.
00:13:45.083575 GW COINBASE TRADE SELL 0.01099434 BTC at price 3682.08000000 EUR (value 40.48203943 EUR)
00:13:57.942301 TBP 60% = 0.07254072 BTC
00:13:57.952300 TBP 60% = 0.06594412 BTC
00:17:22.035221 TBP 60% = 0.06584161 BTC
00:22:42.676624 GW COINBASE Quoting state changed to DISCONNECTED.
00:22:42.676711 GW COINBASE WS Disconnected, reconnecting..
12:37:14.045803 UI authorization attempt from ::ffff:212.59.47.85

---
```
app exchange: Coinbase/BTC/EUR
app version: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by scatterp** [comment]
if i had access to the src for the quickfix part of the code i may be able to do something towards getting libquickfix working a little better as i have the exchange side as well...

**Comment by WilliamJamesDalrympleWest** [comment]
GW COINBASE FIX Logout

Was this fixed?

**Comment by ctubio** [comment]
closing because seems fixed
```
15:06:29.869986 GW COINBASE Quoting state changed to DISCONNECTED.
15:06:29.870066 GW COINBASE FIX Logout.
15:06:31.210722 GW COINBASE FIX Logout.
15:06:37.751935 GW COINBASE FIX Logout.
15:06:38.657700 GW COINBASE FIX Logout.
15:06:52.283859 GW COINBASE Quoting state changed to CONNECTED.
15:06:52.287677 GW COINBASE FIX success Logon.
```

that was while:
```
killall stunnel && read && stunnel etc/K-stunnel.conf
```
