### ISSUE TITLE
Error opening terminal: xterm-256color

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#271]
Hey Charles,

with theactual commit i get this Error when trying to start the Bot:

K build x86_64-linux-gnu 2017-10-01 05:37:32.975130843+00:00.
**Error opening terminal: xterm-256color.**
K crashed with exit code 1.. Respawning..

happens on a Ubuntu 16.04

Hmmmm... any ideas?
---
```
app exchange: //
app version: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by b-seite** [comment]
Hm, as i understand the code right, K tries to open a new window with a terminal inside? But that fails when i am already connected to my remote server via terminal-session, right? 
I went back to 1ddab102a0274fde065e5ad4529029bd5af8306d for the moment

**Comment by ctubio** [comment]
sorry can i ask what terminal client are you using?

i tested putty for now

**Comment by b-seite** [comment]
I am connecting to the bot via ssh within  the OS X Terminal.

**Comment by ctubio** [comment]
should be fixed at https://github.com/ctubio/Krypto-trading-bot/commit/99ea1b30dd3e596771649799eef18a6d473d6cd1 but im not sure if looks good in that terminal; if is very horrible please let me know :P thanks'¡

**Comment by b-seite** [comment]
It´s fixed, thanks. 
the output is not so horrible... but there is a refresh error after scrolling.
see below:
![bildschirmfoto 2017-10-02 um 13 57 49](https://user-images.githubusercontent.com/540850/31076472-866b4b4e-a77a-11e7-9e3f-a4d34979d629.png)

and should pressing q quitting the screen or the bot? atm it quits the bot, a bit dangerous i think
