### ISSUE TITLE
Can't open terminal after last 2 commit update.

### ISSUE THREAD

**Issue by s3479** [ctubio/Krypto-trading-bot#272]
getting a running loop:
K build x86_64-linux-gnu 2017-10-01 18:23:11.
Error opening terminal: screen.
K crashed with exit code 1.. Respawning..
K build x86_64-linux-gnu 2017-10-01 18:23:11.
Error opening terminal: screen.
K crashed with exit code 1.. Respawning..
K build x86_64-linux-gnu 2017-10-01 18:23:11.
Error opening terminal: screen.
K crashed with exit code 1.. Respawning..
K build x86_64-linux-gnu 2017-10-01 18:23:11.
Error opening terminal: screen.
K crashed with exit code 1.. Respawning..
K build x86_64-linux-gnu 2017-10-01 18:23:11.
Error opening terminal: screen.
K crashed with exit code 1.. Respawning..
K build x86_64-linux-gnu 2017-10-01 18:23:11.
Error opening terminal: screen.
K crashed with exit code 1.. Respawning..
K build x86_64-linux-gnu 2017-10-01 18:23:11.

**Comment by ctubio** [comment]
thanks for the report'¡ hope for it to be fixed together with https://github.com/ctubio/Krypto-trading-bot/issues/271

**Comment by ctubio** [comment]
should be fixed at https://github.com/ctubio/Krypto-trading-bot/commit/99ea1b30dd3e596771649799eef18a6d473d6cd1 but im not sure if looks good in that terminal; if is very horrible please let me know :P thanks'¡
