### ISSUE TITLE
Not doing anything

### ISSUE THREAD

**Issue by WilliamJamesDalrympleWest** [ctubio/Krypto-trading-bot#273]
![screen shot 2017-10-02 at 10 01 49](https://user-images.githubusercontent.com/7057144/31062941-c716a822-a758-11e7-9c88-b97add3d884f.png)
Money in the account, coinbase API set up, yet not doing anything

**Comment by ctubio** [comment]
without see the logs i can't say whats wrong, it must be some error printed in the logs; anyway you should double check your api/secret.
