### ISSUE TITLE
non-option ARGV-elements: NULL

### ISSUE THREAD

**Issue by frod123** [ctubio/Krypto-trading-bot#276]
I keep getting this error "non-option ARGV-elements: NULL" and #!/usr/bin/env: not found. I did change my exchange and api information. The only other thing I did was install the latest commit

**Comment by ctubio** [comment]
what is the command you are using to execute the bot? and what is your OS? im not sure why you dont have `/usr/bin/env`; why you dont have it?

**Comment by frod123** [comment]
I use ubuntu 64 bit. I use `sudo ./K.sh` I'm not sure why it wouldn't be there. It was working fine yesterday.

**Comment by ctubio** [comment]
i never used it with sudo, maybe without helps?

**Comment by frod123** [comment]
nah not working IDK, i'll do a fresh install and try again

**Comment by ctubio** [comment]
thanks cos i have no idea what may be wrong (never experiencied it before)

**Comment by ctubio** [comment]
it must be an space somewhere in the config file, mostly possible near an equal symbol [=]; or sumshit, this error happens when NULL is passed as a value of an unexistent argument, like in:
```
./hitbtc.sh NULL
K build x86_64-linux-gnu 2017-10-03 11:53:30.
ARG Errrror: non-option ARGV-elements: NULL
```

**Comment by Zep18** [comment]
Got this error, making a fresh install and a clean K.sh config fixed it !
