### ISSUE TITLE
Missing file on install because makefile hardcodes OS names (instead of only ARCH type)

### ISSUE THREAD

**Issue by rkhoury82** [ctubio/Krypto-trading-bot#277]
Environment: Centos 7 / Node 8/ NPM 5.3

Appears the installer is looking for a file that doesn't exist ? 
Is this fixable?

mkdir -p build-x86_64-redhat-linux/local
curl -L https://github.com/ctubio/Krypto-trading-bot/releases/download/3.0/768cf2c575cd33fd811bf1dc19ecef3ab34644da-x86_64-redhat-linux.tar.gz \
| tar xz -C build-x86_64-redhat-linux/local && chmod +x build-x86_64-redhat-linux/local/lib/K-x86_64-redhat-linux.a build-x86_64-redhat-linux/local/bin/K-x86_64-redhat-linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0      8      0 --:--:--  0:00:01 --:--:--     8

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make[1]: *** [build] Error 2
make[1]: Leaving directory `/home/kbot'
make: *** [install] Error 2

**Comment by andrewcz** [comment]
This probably because of your gzip version incompatibility.

Check these points first:

which gzip
/usr/bin/gzip or /bin/gzip

It should be either /bin/gzip or /usr/bin/gzip. If your gzip points to some other gzip application please try by removing that path from your PATH env variable.

Next is

gzip -V
gzip 1.3.5 (2002-09-30)

Your problem can be resolve with these check points.

**Comment by andrewcz** [comment]
give the above a try and see if that resolves it

**Comment by andrewcz** [comment]
andrewcz@andrewcz-PORTEGE-Z30t-B ~ $ which gzip
/bin/gzip
andrewcz@andrewcz-PORTEGE-Z30t-B ~ $ gzip -v
gzip: compressed data not written to a terminal. Use -f to force compression.
For help, type: gzip -h
andrewcz@andrewcz-PORTEGE-Z30t-B ~ $ gzip -V
gzip 1.6
Copyright (C) 2007, 2010, 2011 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

Written by Jean-loup Gailly.
andrewcz@andrewcz-PORTEGE-Z30t-B ~ $

**Comment by rkhoury82** [comment]
Hi there, 

which gzip /usr/bin/gzip
gzip 1.5

but I can access gzip by /usr/bin/gzip & /bin/gzip

this gives me a 404 error https://github.com/ctubio/Krypto-trading-bot/releases/download/3.0/768cf2c575cd33fd811bf1dc19ecef3ab34644da-x86_64-redhat-linux.tar.gz

**Comment by gamedevST** [comment]
Encountered the same problem myself. It is error in makefile script logic for matching OS type to correct download. Quick fix is to open makefile in text editor, change line 3 to "CROSS   ?= x86_64-linux-gnu" (without quotes)

**Comment by gamedevST** [comment]
Problem has nothing to do with gzip, problem is that no file is downloaded due to incorrect url target, causing gzip to error out. G++ returns "redhat-linux" as os type whereas url needs it to return "linux-gnu" in order to reach correct target file at github.com/ctubio/Krypto-trading-bot/releases/3.0/...

**Comment by rkhoury82** [comment]
Thanks - that sorted it !

**Comment by gamedevST** [comment]
No problem, glad I could help!

**Comment by ctubio** [comment]
many thanks for the comments, i will try to use only the first part of the dumpmachine value (x86_64 for example) and get rid of the OS name/platform, hope this way redhat and others will be fixed
