### ISSUE TITLE
Without --naked Bot is using 100% CPU

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#279]
Hi Charles,

since yesterdays commits my Bots eating up all my cpu performance.
they are using 100% CPU, see below:

![bildschirmfoto 2017-10-05 um 02 18 11](https://user-images.githubusercontent.com/540850/31205781-ddeb81e0-a973-11e7-9cf9-40f1cac9c2d6.png)

the CPU usage the last weeks was under 1% per bot, quet good :) but now they use all the can get...

Any ideas?

---
```
app exchange: Any
app version: latest
Op system: Ubuntu 16.04
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
thanks for the screenshot'¡
when this hapens do you notice anything else i can use to reproduce the issue? (does the bot still works like normal or you need to restart cos is stuck?)

meanwhile ima fire up my htop and look for this, cos i didnt noticed my bots doing this yes

**Comment by b-seite** [comment]
Unfortunately not at the moment. The bots are working as expected until the CPU credits are all eaten up.
i´ll try to figure out wich commit is starting with this behaviour and hopefully come back with more news

**Comment by b-seite** [comment]
don't know if i am right but the problem begins at c6fc0cc73b9d43ef00001e2f417f0977f184c5ee

Maybe it helps you finding the error

**Comment by ctubio** [comment]
thankls for your research, let me come back during this weekend (finally its friday! :dancer:)

**Comment by ctubio** [comment]
ima make ncurses optional meanwhile this is fixed, the problem seems in the ncurses cli as you said, many thanks'¡
