### ISSUE TITLE
Bitfinex Missing market data

### ISSUE THREAD

**Issue by decazuk** [ctubio/Krypto-trading-bot#281]
Bitfinex ETH/USD 
Warrrrning: Unable to calculate TBP, missing market data.
It seems that the bot can not load my wallet data.
I can place order and cancel order by bot ui interface. So I think my api key is ok.

**Comment by ctubio** [comment]
i didnt experienced any issue with Bitfinex wallet today nor since several days ago, consider to get more logs with `--debug`; are you using the latest commit?

**Comment by decazuk** [comment]
OK, I finally fix this, I only have ETH on my wallet first, after I sell some ETH the bot works.

**Comment by les888** [comment]
is there a minimum ETH amount required to get market data on Bitfinex?
