### ISSUE TITLE
Bot usage and unlocking

### ISSUE THREAD

**Issue by LeoMessi99** [ctubio/Krypto-trading-bot#282]
Hello All,
I'm quite new to this and trying to setup the bot, but so far i'm not successfully in making profitable trades yet :(

Going through the documentations I can see that this software needs to be unlocked first in order for it to work?

Do I have to donate the BTC to get a full version of the bot with new features? or I will be getting some settings to use in the current version?

Thank you in advance.

**Comment by ctubio** [comment]
morning''
this is how looks a locked bot: https://imgur.com/a/d3ULy
and in the README is a screenshoot with the bot unlocked (were all market levels are displayed)

"full version" means "all market levels are visible"; you dont need to pay if you still are under the trial period (you can create a new api key to refresh the trail period); or also you can make usefull PR and i will credit the amount for you; ultimately if you want to unlock the bot by yourself alone you will need to pay once the trial period is expired.

**Comment by ctubio** [comment]
![fc-barcelona-catalan-independence](https://user-images.githubusercontent.com/1634027/31308307-11389044-ab75-11e7-9397-1361e7751a7b.jpg)
