### ISSUE TITLE
Poloniex USDT/ZEC Wrong prices calculation

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#284]
Hi, look at the screenshot. Something is definitely wrong.
Poloniex, USDT-ZEC, i'm sure i have less than 30,557 in ZEC.
![zec-usdt-prices](https://user-images.githubusercontent.com/10449591/31315895-74e9e696-ac2a-11e7-97e3-64a9bb93111c.png)

**Comment by ctubio** [comment]
thanks for the report'' sorry I never used Poloniex ZEC market because nobody never voted for it and im not intereset by myself in altcoins so is not a priority for me currently (right now im looking at issues into gdax/hitbtc/bitfinex/okcoin meanwhile votes for Poloniex don't arrive)

**Comment by serzhiio** [comment]
That means that I cant trade any alts?

**Comment by ctubio** [comment]
that means that i didnt tested the bot on Poloniex altcoins since the creation of it (many months ago)

so yea, to run the bot as of today on Poloniex the user needs to be a bit adventurous and willing to face/fix more bugs than in other markets

**Comment by ctubio** [comment]
will add a link from the README to here, to prevent more confusion, hope somebody will care and fix/support this

**Comment by serzhiio** [comment]
This bug cause Poloniex error: "Not enough ZEC"

**Comment by ctubio** [comment]
closing cos nobody cares since +1 month ago

**Comment by ainesh01** [comment]
Is Poloniex ok or not?
