### ISSUE TITLE
Instruction bad info about cloning repo

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#286]
In readme.md we have: "git clone ssh://git@github.com/ctubio/Krypto-trading-bot K"
But this doesn't work and nothing installed.
Need use "git clone http://github.com/ctubio/Krypto-trading-bot K" instead.

**Comment by ctubio** [comment]
is not my problem if you use alternative protocols to access the repo

officialy SSH is supported only.

why HTTPS better than FILE? as in  `git clone file:///opt/git/project.git`` ?

**Comment by serzhiio** [comment]
It's not better, but such way has less problems especially with 'Permission denied'.
