### ISSUE TITLE
Bitifinex disconnects

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#287]
There is strange situation with bitfinix, after 2-3 hours of work disconnect appears, pressing button doesn't help. Bot can reconnect to Bitfinex only after manual restart (make restart).
P.S.: No logs, no messages.

**Comment by serzhiio** [comment]
Catched this error: "QE Warrrrning: Unable to calculate quote, missing fair value"

**Comment by ctubio** [comment]
this msgs mostly possible means market data was not available; may be a temporal issue or.. im not sure how to reproduce this, i will try to reproduce by simply running bitfinex (but im not a bitfinex lover)

**Comment by ctubio** [comment]
i donno whats wrong, im not able to reproduce this, consider to paste some logs
