### ISSUE TITLE
Strange orders with real API

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#288]
Hi,
i've setup some tests (API_ORDERS_DESTINATION=NULL) with boomerang strategy and noticed strange orders. See screenshot. Can't understand where does it comes from.
![btcusd_strange_orders_k sh](https://user-images.githubusercontent.com/10449591/31344895-baae69c0-ad1c-11e7-9cc8-13816ce0e2e2.png)

**Comment by ctubio** [comment]
once multiple orders with the _same_ price are historicaly archived, they get acumulated under the  same price; this means the historical grid of trades never shows 2 rows with the same price, instead it accumulates quantities; this may be what you are highlighting (thanks for the screenshot btw'¡)
