### ISSUE TITLE
DisabledQuotes ? Bitfinex

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#29]
Hi Carles,

After sometime trading on Bitfinex I get that:

![capture d ecran 2017-06-28 a 17 46 31](https://user-images.githubusercontent.com/6861590/27646820-f9b77844-5c29-11e7-9045-4e38087b4b99.png)

And it stops trading. Any idea why?

Am I hitting the limit on Bitfinex? (I trade on al markets)

And can K do something about ? Like trying to reconnect :)

Best Camille

**Comment by Camille92** [comment]
Ok apparently K does reconnect automatically after some time.

I guess I get "punished" by Bitfinex :/

**Comment by Camille92** [comment]
Ok I come back, no finally I think it stays disconnected :s

**Comment by CarlitoGrey** [comment]
Camille, 

Have you tried putting "auto" before the  bot identifier in the config file? This should tell K to auto connect when starting?

"BotIdentifier": "autobot",

**Comment by Camille92** [comment]
Hi @CarlitoGrey thank you for your help but the problem is not that K is off, the problem is that K doesn't trade after some time.

**Comment by ctubio** [comment]
DisabledQuotes is supposed to mean that big green button is red, or that the broker class is disconnected from the exchange; also in the log is supposed that some lines similar to the following are printed when the Quoting state change:
```
Changed quoting mode to true
...
Changed quoting mode to false
```

was the button green or red? :P

**Comment by ctubio** [comment]
since looks like there was no market data, the issue may be that broker class was disconnected from the exchange

**Comment by Camille92** [comment]
I don't remember the color, but I would say yes disconnected from the exchange (probably because I'm hitting the API limit I guess).

But then it doesn't reconnect itself. It's fixed by a simple npm run restartall.

It happens on all markets more or less at the same time!

Next time I'll look at the color to tell you.

**Comment by ctubio** [comment]
if is because a limit is reached, im not sure how to fix this yet meanwhile we have multiple independent instances running against the same resources.

the fix i believe is to unify them all, but this is not like a quick fix :dancer: let me close this meanwhile we dont get to the point that is feasible.

**Comment by Camille92** [comment]
Hey Carles,

Thanks for the answer!
When you say resources, do you speak about 1) CPU/ram of the server, 2) quantity of cash/ crypto or 3) number of requests that can be sent to the exchange?
I can try to adjust my settings accordingly.

And is it possible to, not fix the issue, but exit the app if it's in DisabledMode for more than a few minutes, so it doesn't affect the trading for too long if that happens :)

**Comment by ctubio** [comment]
sorry i mean the problem currently is because saturated external resources, like API endpoints (im not sure how to fix this with the current app; all running gateways need to be unified but currently are not)

**Comment by Camille92** [comment]
I got it again so I hope it gives you more info with this screenshot!

![capture d ecran 2017-06-30 a 19 06 17](https://user-images.githubusercontent.com/6861590/27746517-cc220c60-5dc7-11e7-8fe6-a0de42b94c45.png)

Ps: It is possible to have a way to restart K automatically if that happens?

**Comment by ctubio** [comment]
umf it hae a bunch of open New orders; i think this is becuase the connection failed and they are accumulating (so thats another issue xD)

about the connectivity, if is lost; currently the app tries to reconnect, so you should see some msg in the log like: `bifinex Heartbeat lost, reconnecting..`

thats why the application doesn't restarts, because it is supposed that it tries to reconnect

**Comment by Camille92** [comment]
Well thing is that I start it with npm (no logs) and then some hours later I find out that happens.

If I find a more efficient way of doing it, I'll take a loook at the logs

**Comment by blackivory** [comment]
hi Camille92 , would you be able to solve the issues at the end , with Bitfinex ? pretty annoying that I have to manually click the button n reconnect .
