### ISSUE TITLE
MacOS Installation Error

### ISSUE THREAD

**Issue by onlyyouandty** [ctubio/Krypto-trading-bot#290]
<img width="1280" alt="screen shot 2017-10-09 at 7 52 25 pm" src="https://user-images.githubusercontent.com/7871367/31353696-731855b2-ad2b-11e7-8721-d253ff5432cc.png">

**Comment by ctubio** [comment]
thanks for the screenshot, sorry macOS doesn't work, but soOn maybe will do (follow up at https://github.com/ctubio/Krypto-trading-bot/issues/136)
