### ISSUE TITLE
Add Support for Bittrex

### ISSUE THREAD

**Issue by rconnelly** [ctubio/Krypto-trading-bot#291]
Bittrex volume has surpassed Poloniex. I recommend we add support to bittrex. 

Has anyone started work on this yet?

**Comment by serzhiio** [comment]
Support this feature

**Comment by ctubio** [comment]
on next holidays maybe :dancer: (hope for december 2017)

**Comment by MiningInMySleep** [comment]
Would love this along with Kraken support.

**Comment by ctubio** [comment]
closing cos nobody cares to support the development of this and i have other stuff to play with
