### ISSUE TITLE
Performance problems on GDAX

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#292]
Hi Charles,

i still have performance problems with K & GDAX. 
At the moment i have two instances running on AWS. The one has no performance problems, there are two K instances connected to bitfinex.
Credits last week are looking good:
![bildschirmfoto 2017-10-10 um 23 29 52](https://user-images.githubusercontent.com/540850/31413463-a2771534-ae19-11e7-93b9-de05b140648c.png)

the other instance connects to GDAX and looks like this:
![bildschirmfoto 2017-10-11 um 00 13 43](https://user-images.githubusercontent.com/540850/31413502-da33b5fe-ae19-11e7-9bf3-56bc081c37eb.png)

it seems that K on GDAX/Coinbase still has a performance Problem

Thanks for any solution

**Comment by ctubio** [comment]
true, im still fixing minor libquickfix issues, thanks for the screenshots'' (yours seems not a minor issue :P but im currently monitorig gdax and hope to reproduce your case soOn'')

**Comment by ctubio** [comment]
but are you using the cli? or are you using `--naked`? thanks'¡

**Comment by b-seite** [comment]
Ah sorry i forgot to mention: These schreenshhots were both made wihh —naked Option on. 
Without —naked the bots still using ALL cpu performance

**Comment by ctubio** [comment]
my gdax started to go up to 40% now :( will investigate'¡

**Comment by ctubio** [comment]
seems cpu goes high when TBP starts to be reclaculated nonstop; in other exhanges TBP is never recalculated nonstop but periodically with a friendly delay in between each calculation

**Comment by ctubio** [comment]
hope this is already fixed, i was running gdax between 3% and 10% all day

**Comment by b-seite** [comment]
Hi it´s me again and again with the same issue.
even with --naked on, the bot consumes all processor power sometimes. 
After some time it comes back to normal state for some minutes and again goes up to 25-100% cpu power. 

See Image below:
![bildschirmfoto 2017-10-20 um 09 13 58](https://user-images.githubusercontent.com/540850/31809818-a9538c68-b579-11e7-8354-0a594f529910.png)

running GDAX on Ubuntu 16.04 on AWS
