### ISSUE TITLE
ERROR: Signal 6 aborted Three-headed monkey

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#293]
*** Error in `./app/server/K': double free or corruption (fasttop): 0x00007fe520011cf0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bcb)[0x7fe52fd30bcb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76f96)[0x7fe52fd36f96]
/lib/x86_64-linux-gnu/libc.so.6(+0x777de)[0x7fe52fd377de]
./app/server/K(_ZNSt6vectorIN8nlohmann10basic_jsonISt3mapS_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS0_14adl_serializerEEESaISA_EED1Ev+0x24)[0x7fe530b17894]
./app/server/K(_ZN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEED1Ev+0x89)[0x7fe530b17829]
./app/server/K(_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N8nlohmann10basic_jsonISt3mapSt6vectorS5_blmdSaNS8_14adl_serializerEEEESt10_Select1stISE_ESt4lessIS5_ESaISE_EE8_M_eraseEPSt13_Rb_tree_nodeISE_E+0x489)[0x7fe530b172a9]
./app/server/K(_ZN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEED1Ev+0x3d)[0x7fe530b177dd]
./app/server/K(_ZN1K2UI7appPushEv+0x13c)[0x7fe530b3034c]
./app/server/K(_ZNSt6thread11_State_implISt12_Bind_simpleIFZN1K2UI5delayEdEUlvE_vEEE6_M_runEv+0xdc)[0x7fe530b31d2c]
./app/server/K(+0x4f217f)[0x7fe530e9c17f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7fe530066494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fe52fda8aff]
======= Memory map: ========
7fe518000000-7fe518021000 rw-p 00000000 00:00 0
7fe518021000-7fe51c000000 ---p 00000000 00:00 0
7fe51c000000-7fe51c021000 rw-p 00000000 00:00 0
7fe51c021000-7fe520000000 ---p 00000000 00:00 0
7fe520000000-7fe520021000 rw-p 00000000 00:00 0
7fe520021000-7fe524000000 ---p 00000000 00:00 0
7fe524000000-7fe524021000 rw-p 00000000 00:00 0
7fe524021000-7fe528000000 ---p 00000000 00:00 0
7fe528000000-7fe528021000 rw-p 00000000 00:00 0
7fe528021000-7fe52c000000 ---p 00000000 00:00 0
7fe52cc76000-7fe52cc8c000 r-xp 00000000 b6:87c41 131830                  /lib/x86_64-linux-gnu/libgcc_s.so.1
7fe52cc8c000-7fe52ce8b000 ---p 00016000 b6:87c41 131830                  /lib/x86_64-linux-gnu/libgcc_s.so.1
7fe52ce8b000-7fe52ce8c000 r--p 00015000 b6:87c41 131830                  /lib/x86_64-linux-gnu/libgcc_s.so.1
7fe52ce8c000-7fe52ce8d000 rw-p 00016000 b6:87c41 131830                  /lib/x86_64-linux-gnu/libgcc_s.so.1
7fe52ce8d000-7fe52ce8e000 ---p 00000000 00:00 0
7fe52ce8e000-7fe52d88e000 rw-p 00000000 00:00 0
7fe52d88e000-7fe52d88f000 ---p 00000000 00:00 0
7fe52d88f000-7fe52e28f000 rw-p 00000000 00:00 0
7fe52e28f000-7fe52e290000 ---p 00000000 00:00 0
7fe52e290000-7fe52ec90000 rw-p 00000000 00:00 0
7fe52ec90000-7fe52eca4000 r-xp 00000000 b6:87c41 131770                  /lib/x86_64-linux-gnu/libresolv-2.24.so
7fe52eca4000-7fe52eea3000 ---p 00014000 b6:87c41 131770                  /lib/x86_64-linux-gnu/libresolv-2.24.so
7fe52eea3000-7fe52eea4000 r--p 00013000 b6:87c41 131770                  /lib/x86_64-linux-gnu/libresolv-2.24.so
7fe52eea4000-7fe52eea5000 rw-p 00014000 b6:87c41 131770                  /lib/x86_64-linux-gnu/libresolv-2.24.so
7fe52eea5000-7fe52eea7000 rw-p 00000000 00:00 0
7fe52eea7000-7fe52eeac000 r-xp 00000000 b6:87c41 131747                  /lib/x86_64-linux-gnu/libnss_dns-2.24.so
7fe52eeac000-7fe52f0ab000 ---p 00005000 b6:87c41 131747                  /lib/x86_64-linux-gnu/libnss_dns-2.24.so
7fe52f0ab000-7fe52f0ac000 r--p 00004000 b6:87c41 131747                  /lib/x86_64-linux-gnu/libnss_dns-2.24.so
7fe52f0ac000-7fe52f0ad000 rw-p 00005000 b6:87c41 131747                  /lib/x86_64-linux-gnu/libnss_dns-2.24.so
7fe52f0ad000-7fe52f0b7000 r-xp 00000000 b6:87c41 131749                  /lib/x86_64-linux-gnu/libnss_files-2.24.so
7fe52f0b7000-7fe52f2b7000 ---p 0000a000 b6:87c41 131749                  /lib/x86_64-linux-gnu/libnss_files-2.24.so
7fe52f2b7000-7fe52f2b8000 r--p 0000a000 b6:87c41 131749                  /lib/x86_64-linux-gnu/libnss_files-2.24.so
7fe52f2b8000-7fe52f2b9000 rw-p 0000b000 b6:87c41 131749                  /lib/x86_64-linux-gnu/libnss_files-2.24.so
7fe52f2b9000-7fe52f2bf000 rw-p 00000000 00:00 0
7fe52f2bf000-7fe52f2c0000 ---p 00000000 00:00 0
7fe52f2c0000-7fe52fcc0000 rw-p 00000000 00:00 0
7fe52fcc0000-7fe52fe55000 r-xp 00000000 b6:87c41 131711                  /lib/x86_64-linux-gnu/libc-2.24.so
7fe52fe55000-7fe530055000 ---p 00195000 b6:87c41 131711                  /lib/x86_64-linux-gnu/libc-2.24.so
7fe530055000-7fe530059000 r--p 00195000 b6:87c41 131711                  /lib/x86_64-linux-gnu/libc-2.24.so
7fe530059000-7fe53005b000 rw-p 00199000 b6:87c41 131711                  /lib/x86_64-linux-gnu/libc-2.24.so
7fe53005b000-7fe53005f000 rw-p 00000000 00:00 0
7fe53005f000-7fe530077000 r-xp 00000000 b6:87c41 131768                  /lib/x86_64-linux-gnu/libpthread-2.24.so
7fe530077000-7fe530276000 ---p 00018000 b6:87c41 131768                  /lib/x86_64-linux-gnu/libpthread-2.24.so
7fe530276000-7fe530277000 r--p 00017000 b6:87c41 131768                  /lib/x86_64-linux-gnu/libpthread-2.24.so
7fe530277000-7fe530278000 rw-p 00018000 b6:87c41 131768                  /lib/x86_64-linux-gnu/libpthread-2.24.so
7fe530278000-7fe53027c000 rw-p 00000000 00:00 0
7fe53027c000-7fe53037f000 r-xp 00000000 b6:87c41 131720                  /lib/x86_64-linux-gnu/libm-2.24.so
7fe53037f000-7fe53057e000 ---p 00103000 b6:87c41 131720                  /lib/x86_64-linux-gnu/libm-2.24.so
7fe53057e000-7fe53057f000 r--p 00102000 b6:87c41 131720                  /lib/x86_64-linux-gnu/libm-2.24.so
7fe53057f000-7fe530580000 rw-p 00103000 b6:87c41 131720                  /lib/x86_64-linux-gnu/libm-2.24.so
7fe530580000-7fe530583000 r-xp 00000000 b6:87c41 131717                  /lib/x86_64-linux-gnu/libdl-2.24.so
7fe530583000-7fe530782000 ---p 00003000 b6:87c41 131717                  /lib/x86_64-linux-gnu/libdl-2.24.so
7fe530782000-7fe530783000 r--p 00002000 b6:87c41 131717                  /lib/x86_64-linux-gnu/libdl-2.24.so
7fe530783000-7fe530784000 rw-p 00003000 b6:87c41 131717                  /lib/x86_64-linux-gnu/libdl-2.24.so
7fe530784000-7fe5307a7000 r-xp 00000000 b6:87c41 131581                  /lib/x86_64-linux-gnu/ld-2.24.so
7fe5309a7000-7fe5309a8000 r--p 00023000 b6:87c41 131581                  /lib/x86_64-linux-gnu/ld-2.24.so
7fe5309a8000-7fe5309a9000 rw-p 00024000 b6:87c41 131581                  /lib/x86_64-linux-gnu/ld-2.24.so
7fe5309a9000-7fe5309aa000 rw-p 00000000 00:00 0
7fe5309aa000-7fe530ff9000 r-xp 00000000 b6:87c41 394363                  /var/www/vhosts/K/build-x86_64-linux-gnu/local/bin/K-x86_64-linux-gnu
7fe531022000-7fe5311ec000 rw-p 00000000 00:00 0
7fe5311f4000-7fe5311f8000 rw-p 00000000 00:00 0 08:05:13.894816 Errrror: Signal 6 Aborted (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x1a)[0x7fe530b092aa]
./app/server/K(_ZN1K2EV3wtfEi+0x426)[0x7fe530b0c696]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7fe52fcf3030]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf)[0x7fe52fcf2fcf]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fe52fcf43fa]
/lib/x86_64-linux-gnu/libc.so.6(+0x70bd0)[0x7fe52fd30bd0]
/lib/x86_64-linux-gnu/libc.so.6(+0x76f96)[0x7fe52fd36f96]
/lib/x86_64-linux-gnu/libc.so.6(+0x777de)[0x7fe52fd377de]
./app/server/K(_ZNSt6vectorIN8nlohmann10basic_jsonISt3mapS_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS0_14adl_serializerEEESaISA_EED1Ev+0x24)[0x7fe530b17894]
./app/server/K(_ZN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEED1Ev+0x89)[0x7fe530b17829]
./app/server/K(_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N8nlohmann10basic_jsonISt3mapSt6vectorS5_blmdSaNS8_14adl_serializerEEEESt10_Select1stISE_ESt4lessIS5_ESaISE_EE8_M_eraseEPSt13_Rb_tree_nodeISE_E+0x489)[0x7fe530b172a9]
./app/server/K(_ZN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEED1Ev+0x3d)[0x7fe530b177dd]
./app/server/K(_ZN1K2UI7appPushEv+0x13c)[0x7fe530b3034c]
./app/server/K(_ZNSt6thread11_State_implISt12_Bind_simpleIFZN1K2UI5delayEdEUlvE_vEEE6_M_runEv+0xdc)[0x7fe530b31d2c]
./app/server/K(+0x4f217f)[0x7fe530e9c17f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7fe530066494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fe52fda8aff]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by ctubio** [comment]
what exchange is this?

**Comment by serzhiio** [comment]
Bitfinex
