### ISSUE TITLE
Another Errrror: Signal 6 Aborted (Three-Headed Monkey found).

### ISSUE THREAD

**Issue by simonlucalandi** [ctubio/Krypto-trading-bot#296]
09:36:03.712013 K exit code 1.
K crashed with exit code 1.. Respawning..
K build x86_64-linux-gnu 2017-10-08 13:18:22.
12:02:04.306475 Errrror: Signal 6 Aborted (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x1a)[0x7f57936ea2aa]
./app/server/K(_ZN1K2EV3wtfEi+0x426)[0x7f57936ed696]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f57928d4030]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf)[0x7f57928d3fcf]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f57928d53fa]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d)[0x7f5793a8261d]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6)[0x7f57939fa8a6]
./app/server/K(+0x46f8f1)[0x7f57939fa8f1]
./app/server/K(+0x4f21ae)[0x7f5793a7d1ae]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7f5792c47494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f5792989aff]

**Comment by ctubio** [comment]
what exchange was this?

**Comment by simonlucalandi** [comment]
Coinbase (GDAX)

**Comment by ctubio** [comment]
thanks'' will fix gdax in other already opened threads, closing this cos this stack trace is not very usefull :(
