### ISSUE TITLE
HamelinRat mode: ask quote is always the 13th

### ISSUE THREAD

**Issue by simonlucalandi** [ctubio/Krypto-trading-bot#297]
When using the HamelinRat mode, the quote provided for the ask side is always the 13th in the book.
I guess there is a bug in server/qe.h in the calcColossusOfMarket method.

I guess that
```
        for (vector<mLevel>::iterator it = mgLevelsFilter.asks.begin(); it != mgLevelsFilter.asks.end(); ++it) {
          if (askSz < it->size) {
            askSz = it->size;
            askPx = it->price;
          }
          if (!--maxLvl) break;
        }
```

should instead iterato over the asks in reverse order, like this:

```
        for (vector<mLevel>::reverse_iterator it = mgLevelsFilter.asks.rbegin(); it != mgLevelsFilter.asks.rend(); ++it) {
          if (askSz < it->size) {
            askSz = it->size;
            askPx = it->price;
          }
          if (!--maxLvl) break;
        }
 
```
 I can open PR this patch

**Comment by ctubio** [comment]
thanks for the report, this may happen under certain situations (i didnt experiencied it yet); will keep improving HamelinRat on following days; for now have super simple logic
