### ISSUE TITLE
Problems getting it going.

### ISSUE THREAD

**Issue by WilliamJamesDalrympleWest** [ctubio/Krypto-trading-bot#300]
Funds transferred from Coinbase to GDax,

API exchange set as coinbase

All API Key, Pass, Phraise are gdax, all end points are gdax

![screen shot 2017-10-13 at 18 03 41](https://user-images.githubusercontent.com/7057144/31543582-f4769638-b040-11e7-83d4-46bd0cac2af5.png)

Yet nothing is happening...

**Comment by ctubio** [comment]
consider to get some logs to know what is going on (maybe with `./K.sh --naked`)

**Comment by WilliamJamesDalrympleWest** [comment]
![screen shot 2017-10-13 at 18 51 08](https://user-images.githubusercontent.com/7057144/31544963-82b4ff1a-b047-11e7-8315-768c74edcc66.png)

Placed a manual order in GDAX just fine, nothing seems to be happening in the bot, also pulled it, but dont seem to have the upgrade turned off.

**Comment by WilliamJamesDalrympleWest** [comment]
Not sure where to run or how to run ./K.sh --naked

**Comment by WilliamJamesDalrympleWest** [comment]
@ctubio would appreciate...

**Comment by ctubio** [comment]
in your last screenshot seems all nice, just need to click the red button to turn it green no? or what happens when you click the red button?

**Comment by NA-Proiv** [comment]
Haha, was on a 3 day session and turned out firewall issue on the server that I did not consider at the time,
