### ISSUE TITLE
GDAX/Coinbase connected but orders notplacing

### ISSUE THREAD

**Issue by WilliamJamesDalrympleWest** [ctubio/Krypto-trading-bot#301]
Placed a manual order in GDAX just fine, nothing seems to be happening in the bot, also pulled it, but dont seem to have the upgrade turned off.

Not sure where to run or how to run ./K.sh --naked
![screen shot 2017-10-13 at 18 51 08](https://user-images.githubusercontent.com/7057144/31546426-743fc518-b04d-11e7-8615-b8db50aed68c.png)

@ctubio would appreciate... some advice

**Comment by WilliamJamesDalrympleWest** [comment]
![screen shot 2017-10-13 at 19 37 31](https://user-images.githubusercontent.com/7057144/31546560-05e7a17a-b04e-11e7-90e5-4d33c153d488.png)
Is this due to only having like 6GBP In the account? (testing)

**Comment by WilliamJamesDalrympleWest** [comment]
Does 'work' when set to null real orders, but nothing on the real front
![screen shot 2017-10-13 at 20 03 49](https://user-images.githubusercontent.com/7057144/31547847-10eeb7f2-b053-11e7-82cd-b480ce8df741.png)

**Comment by WilliamJamesDalrympleWest** [comment]
![screen shot 2017-10-13 at 20 16 23](https://user-images.githubusercontent.com/7057144/31547962-6ece4022-b053-11e7-981b-3d254e5460f8.png)
Manual orders not passing through either.

Cant see any errors

**Comment by WilliamJamesDalrympleWest** [comment]
👎  Amazing piece but not sure where it's going wrong, it's fully hooked up just not placing orders when live, whether this is an issue with the fund volume i don't know, i've strenuously gone through the open and closed issues, and can not find anything similar.

On NULL (Real trades) it is mimicking 100% and i believe data flowing, but when it comes to physical it's just a head banging situation
![screen shot 2017-10-13 at 21 23 22](https://user-images.githubusercontent.com/7057144/31550839-e2849620-b05c-11e7-8875-25e27e06dae5.png)
 as to what the issue could be.

**Comment by WilliamJamesDalrympleWest** [comment]
root@tweetfeels-ubuntu-python3:~/Krypto-trading-bot# make screen
Detach screen hotkey: holding CTRL hit A then D

14:42:57.658700 UI ready over HTTP on external port 3000.
14:42:58.465101 GW COINBASE allows client IP.
14:42:58.465187 GW COINBASE:
- autoBot: no
- pair: BTC-GBP
- minTick: 0.01000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
14:42:58.465999 DB /data/db/K.3.BTC.GBP.db loaded OK.
14:42:58.466527 DB loaded Quoting Parameters OK.
14:42:58.466603 DB loaded 0 historical Trades.
14:42:58.470542 DB loaded 1087 STDEV Periods.
14:42:58.475990 DB loaded EWMA Long = 4277.46024114.
14:42:58.476031 DB loaded EWMA Medium = 4292.26061819.
14:42:58.476051 DB loaded EWMA Short = 4316.88319872.
14:42:58.476185 DB loaded TBP = 0.00138783 BTC.
14:42:58.809291 GW COINBASE FIX success Logon.
14:42:59.026638 GW COINBASE WS Streaming book levels.
14:42:59.762835 UI authorization success from ::ffff:184.22.191.145
14:43:03.315091 UI 1 currently connected, last connection was from ::ffff:184.22.191.145.
14:43:10.596445 GW COINBASE Quoting state changed to CONNECTED.
14:43:59.876705 TBP 100% = 0.00140167 BTC

**Comment by WilliamJamesDalrympleWest** [comment]
Nightmare, uploaded latest now getting


15:17:15.844105 GW COINBASE FIX Logout.
15:17:17.380235 UI authorization failed from ::ffff:1.186.125.98
15:17:36.865773 GW COINBASE FIX Logout.
15:17:57.888270 GW COINBASE FIX Logout.
15:18:18.911116 GW COINBASE FIX Logout.
15:18:39.933540 GW COINBASE FIX Logout.
15:18:54.366684 UI 0 currently connected, last disconnection was from ::ffff:184.22.191.145.
15:19:00.945122 GW COINBASE FIX Logout.
15:19:21.967499 GW COINBASE FIX Logout.
15:19:42.990046 GW COINBASE FIX Logout.
15:19:55.932434 UI authorization success from ::ffff:184.22.191.145
15:20:00.559406 UI 1 currently connected, last connection was from ::ffff:184.22.191.145.
15:20:03.011732 GW COINBASE FIX Logout.
15:20:24.034253 GW COINBASE FIX Logout.
15:20:45.045728 GW COINBASE FIX Logout.
15:21:06.068256 GW COINBASE FIX Logout.
15:21:27.091115 GW COINBASE FIX Logout.
15:21:48.113878 GW COINBASE FIX Logout.
15:22:09.136568 GW COINBASE FIX Logout.
15:22:30.159302 GW COINBASE FIX Logout.
15:22:51.181860 GW COINBASE FIX Logout.
15:23:12.204476 GW COINBASE FIX Logout.
m15:23:33.227140 GW COINBASE FIX Logout.

**Comment by WilliamJamesDalrympleWest** [comment]
Turned to Bitrex


p.
* 3612352 Added user agreement before install.
* 59dd157 Added collaborators and contributors notes.
* 46bc917 Added anonymous users notes.
* 4985173 Added moar term fallbacks.
* 99ea1b3 Added term fallbacks.
* 8674cbd Added bold even if no colors.
* e1d8562 Added quit hotkey q and dummy scroll.
* c36b3e4 Updated build stamp format.
* 5c288b7 Added ncurses window.
* 1ddab10 Added ncurses to make dist.
* d6b9b02 Updated HitBTC api numbers to strings.
* d1306a0 Fixed cross compilation for Raspbian.
* d765f3d Added npm install to travis.
* 8c785ee Fixed typo.
* e134634 Updated make test out of make reinstall.
* 4e4d8d3 Updated make bundle against all builds.
* 9add8f9 Fixed typo.
* 48836d7 Updated installation without useless npm dependency.
* 7ac62df Updated installation without useless node dependency.
16:11:04.252958 UI ready over HTTP on external port 3000.
16:11:05.227754 CF Errrror: Unable to fetch data from BITFINEX symbol "btcgbp".
K crashed with exit code 1.. Respawning..

**Comment by WilliamJamesDalrympleWest** [comment]
It's doing the same with Bitfinex

**Comment by ctubio** [comment]
i donno whats wrong, consider to review the output of the application instead of the user interface.

logs usually have interesting warnings/errors

you can use --debug argumnet to get detailed logs
