### ISSUE TITLE
Three-Headed Monkey found on Coinbase

### ISSUE THREAD

**Issue by simonlucalandi** [ctubio/Krypto-trading-bot#302]
(Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x1a)[0x558302f5976a]
./app/server/K(_ZN1K2EV3wtfEi+0x426)[0x558302f5cb56]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f08158dd030]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf)[0x7f08158dcfcf]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f08158de3fa]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0xed)[0x558303309a2d]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6)[0x558303281d26]
./app/server/K(+0x488d71)[0x558303281d71]
./app/server/K(_ZN10__cxxabiv112__unexpectedEPFvvE+0x6)[0x558303281d86]
./app/server/K(__cxa_call_unexpected+0x32)[0x5583032827f2]
./app/server/K(_ZN1K10GwCoinbase7fromAppERKN3FIX7MessageERKNS1_9SessionIDE+0xb96)[0x558302fd1596]
./app/server/K(_ZN3FIX7Session6verifyERKNS_7MessageEbb+0x2fb)[0x55830300387b]
./app/server/K(_ZN3FIX7Session4nextERKNS_7MessageERKNS_12UtcTimeStampEb+0x9b1)[0x5583030061f1]
./app/server/K(_ZN3FIX7Session4nextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_12UtcTimeStampEb+0x1a3)[0x558303007613]
./app/server/K(_ZN3FIX16SocketConnection12readMessagesERNS_13SocketMonitorE+0x70)[0x55830301e8b0]
./app/server/K(_ZN3FIX16SocketConnection4readERNS_15SocketConnectorE+0x28)[0x55830301e978]
./app/server/K(_ZN3FIX16ConnectorWrapper7onEventERNS_13SocketMonitorEi+0x19)[0x558303072c89]
./app/server/K(_ZN3FIX13SocketMonitor14processReadSetERNS0_8StrategyER6fd_set+0xe6)[0x55830301d046]
./app/server/K(_ZN3FIX13SocketMonitor5blockERNS0_8StrategyEbd+0x298)[0x55830301d3a8]
./app/server/K(_ZN3FIX15SocketConnector5blockERNS0_8StrategyEbd+0x24)[0x558303072bb4]
./app/server/K(_ZN3FIX15SocketInitiator7onStartEv+0x45)[0x558303018615]
./app/server/K(_ZN3FIX9Initiator11startThreadEPv+0xa)[0x558303014afa]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7f0815c50494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f0815992aff]

**Comment by ctubio** [comment]
thanks for the report, will fix gdax in other already opened gdax threads
