### ISSUE TITLE
[topic] short and sweet description

### ISSUE THREAD

**Issue by WilliamJamesDalrympleWest** [ctubio/Krypto-trading-bot#305]
Still not able to connect to exchange
---
```
app exchange: Coinbase/BTC/USD
app version: Latest
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
still not able to see any logs (does the output say anything interesting?)
