### ISSUE TITLE
Strange order placement in UI

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#306]
Hi please look at position of Ask order. I think it is in wrong position.
![order-place-bug](https://user-images.githubusercontent.com/10449591/31586906-96748c38-b1e0-11e7-8e14-32557606d187.jpg)

**Comment by ctubio** [comment]
sorry i dont understand your description

**Comment by serzhiio** [comment]
in the orders stack **0.059848** is between 0.59827 and 0.59833.

**Comment by ctubio** [comment]
im not able to reproduce this, consider to provide more information

does this happens always at all times in all markets no matter what quoting parameters are used? or is only related to one of them? or a few of them?
