### ISSUE TITLE
Bitfinex Last commit brings back UI ghost orders :/

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#308]
Since: https://github.com/ctubio/Krypto-trading-bot/commit/b78182c1289bd562d671ce2ddc3df8916f4bccc4

What happens:
After a few minute, It seems that ALL orders sent to the exchange appear on the bot UI.

I'm trading on Bitfi :)

![capture d ecran 2017-10-17 a 11 53 18](https://user-images.githubusercontent.com/6861590/31658833-7ae6341e-b332-11e7-8d97-da618cb8f62c.png)

**Comment by ctubio** [comment]
morniiing''
thanks for the report, will rewrite soOn the uiHold function and friends, hope will be fixed then

**Comment by ctubio** [comment]
i was able to reproduce it, some mutex (wsMutex) are dancing together
