### ISSUE TITLE
Starting next week -> Bitfinex order size Adjustments 

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#309]
"On Tuesday, October 24th, Bitfinex will be making adjustments to the minimum order size for several trading pairs.

Beginning on the 24th, the minimum order size for each trading pair will be automatically adjusted on a weekly basis to maintain minimum order sizes that are reasonably proportioned to their values. The goal is to keep the minimum order size between $10 and $25 USD equivalent value while limiting the changes to the minimum order sizes to useful incremental values.

At this initial adjustment, some pairs will have their minimum order size adjusted downward (for example, BTC/USD will likely be adjusted from 0.005 to ~0.004) - while others will see a significant increase in minimum order size (for example, IOTA/USD will be adjusted from 0.1 to ~10.0). This will ensure that all trading pairs maintain minimum order sizes that are closer in relative value.

Minimum order sizes can be checked at any time using the REST v1 API endpoint, /v1/symbols_details (API documentation). (https://api.bitfinex.com/v1/symbols_details) / (https://docs.bitfinex.com/v1/reference#rest-public-symbol-details) "

https://www.bitfinex.com/posts/226

I'm quite sure that the bot in its current form can't deal with that, is a fix easy or possible? 

Thanks!

Camille

**Comment by ctubio** [comment]
![mr-homn-thank-you-for-the-links](https://user-images.githubusercontent.com/1634027/31717643-16d3276c-b40d-11e7-8c6e-e9448a5fca10.png)

**Comment by Camille92** [comment]
This is a good decision by bitfinex because it will stop people from "spoofing" the market with 0.001 USD orders!
