### ISSUE TITLE
HitBTC always disconnected

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#310]
Faced with HitBTC connection problems. Nothing helps, always disconnected.
11:31:07.186469 GW HITBTC Error 2 {"error":"Unauthorized"}.

**Comment by serzhiio** [comment]
I've refreshed API keys, and now still have DISCONNECTED with no log messages.
![hitbtc-just-disconnect](https://user-images.githubusercontent.com/10449591/31670906-60e7a8c0-b361-11e7-983e-9999025f1626.jpg)

**Comment by ctubio** [comment]
are you sure your api keys are correct? my hitbtc bots works fine, feel free to include more logs if you consider; in the screenshot the bot shows green background, that is connected

**Comment by serzhiio** [comment]
Really, after bot deleted and then reinstalled, it worked.
Sorry for false issue.
