### ISSUE TITLE
HitBTC ETH-BTC hollow orders

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#311]
Right after i created and ran second bot on BCC/USD, ETH-BTC bot stopped sending orders to HitBTC, but at HitBTC i see bulk of strange orders. Hope i did screenshot at the right moment. Everything were great before second bot ran.

![hollow-orders](https://user-images.githubusercontent.com/10449591/31731279-2f73ac62-b43d-11e7-8806-3e36b5e63cf9.jpg)

**Comment by ctubio** [comment]
try different api keys for each market

**Comment by serzhiio** [comment]
Every time i created a new instance, i'm generating new API keys.

**Comment by ctubio** [comment]
then try to get some logs, im not able to reproduce the issue :(
