### ISSUE TITLE
Question: hundred or thousand of openOrders/60sec

### ISSUE THREAD

**Issue by simonlucalandi** [ctubio/Krypto-trading-bot#314]
On the web UI I see values of openOrders/60sec: up to thousands (> 1200) and Quote like Quotes: 500/2/0 . 
Is it "normal"? 
This happens in modes AK47 and HamelinRat, exchange is Coinbase (GDAX)

**Comment by ctubio** [comment]
the value comes from https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/og.h#L44, it just count calls to `send` function, efectively counting orders send to the exchange api

**Comment by simonlucalandi** [comment]
Thank you for the very quick answer 🥇 I'll try to investigate why sometime I see hundred of Quotes
