### ISSUE TITLE
updateQuote bug

### ISSUE THREAD

**Issue by benfavre** [ctubio/Krypto-trading-bot#315]
./app/server/K(_ZN1K2QE5startENS_5mSideENS_6mLevelEb+0x2ab)[0x5629ce2f2efb]
./app/server/K(_ZN1K2QE6modifyENS_5mSideENS_6mLevelEb+0x81)[0x5629ce2f3b61]
./app/server/K(_ZN1K2QE11updateQuoteENS_6mLevelENS_5mSideEb+0x148)[0x5629ce2f3d88]
./app/server/K(_ZN1K2QE9calcQuoteEv+0x2ec)[0x5629ce2fdd1c]
./app/server/K(_ZZN1K2QE4mainEvENKUlvE_clEv+0x2ad)[0x5629ce2fe11d]
./app/server/K(+0x19810d)[0x5629ce2ff10d]
./app/server/K(+0x50b54f)[0x5629ce67254f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f2206aaa6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f22067e03dd]

---
```
app exchange: HitBtc/BTC/USD
app version: latest
OS distro: linux mint
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by benfavre** [comment]
cd6a2d4000-7fcd6a2d5000 rw-p 00018000 08:01 661830                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7fcd6a2d5000-7fcd6a2d9000 rw-p 00000000 00:00 0 
7fcd6a2d9000-7fcd6a3e1000 r-xp 00000000 08:01 661905                     /lib/x86_64-linux-gnu/libm-2.23.so
7fcd6a3e1000-7fcd6a5e0000 ---p 00108000 08:01 661905                     /lib/x86_64-linux-gnu/libm-2.23.so
7fcd6a5e0000-7fcd6a5e1000 r--p 00107000 08:01 661905                     /lib/x86_64-linux-gnu/libm-2.23.so
7fcd6a5e1000-7fcd6a5e2000 rw-p 00108000 08:01 661905                     /lib/x86_64-linux-gnu/libm-2.23.so
7fcd6a5e2000-7fcd6a5e5000 r-xp 00000000 08:01 661857                     /lib/x86_64-linux-gnu/libdl-2.23.so
7fcd6a5e5000-7fcd6a7e4000 ---p 00003000 08:01 661857                     /lib/x86_64-linux-gnu/libdl-2.23.so
7fcd6a7e4000-7fcd6a7e5000 r--p 00002000 08:01 661857                     /lib/x86_64-linux-gnu/libdl-2.23.so
7fcd6a7e5000-7fcd6a7e6000 rw-p 00003000 08:01 661857                     /lib/x86_64-linux-gnu/libdl-2.23.so
7fcd6a7e6000-7fcd6a80c000 r-xp 00000000 08:01 659893                     /lib/x86_64-linux-gnu/ld-2.23.so
7fcd6a80f000-7fcd6a9db000 rw-p 00000000 00:00 0 
7fcd6aa08000-7fcd6aa0b000 rw-p 00000000 00:00 0 
7fcd6aa0b000-7fcd6aa0c000 r--p 00025000 08:01 659893                     /lib/x86_64-linux-gnu/ld-2.23.so
7fcd6aa0c000-7fcd6aa0d000 rw-p 00026000 08:01 659893                     /lib/x86_64-linux-gnu/ld-2.23.so
7fcd6aa0d000-7fcd6aa0e000 rw-p 00000000 00:00 0 
7ffd5389f000-7ffd538c0000 rw-p 00000000 00:00 0                          [stack]
7ffd5390c000-7ffd5390e000 r--p 00000000 00:00 0                          [vvar]
7ffd5390e000-7ffd53910000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
10:02:06.645974 Errrror: Signal 6 Aborted (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x1a)[0x5617a677276a]
./app/server/K(_ZN1K2EV3wtfEi+0x41e)[0x5617a6775fce]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7fcd69d274b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7fcd69d27428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fcd69d2902a]
/lib/x86_64-linux-gnu/libc.so.6(+0x777ea)[0x7fcd69d697ea]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fcd69d7237a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fcd69d7653c]
./app/server/K(_ZNSt8_Rb_treeIN1K5mSideESt4pairIKS1_NS0_6mLevelEESt10_Select1stIS5_ESt4lessIS1_ESaIS5_EE8_M_eraseEPSt13_Rb_tree_nodeIS5_E+0x19a)[0x5617a677fb3a]
./app/server/K(_ZN1K2QE5startENS_5mSideENS_6mLevelEb+0x2ab)[0x5617a679defb]
./app/server/K(_ZNSt6thread11_State_implISt12_Bind_simpleIFZN1K2QE5startENS2_5mSideENS2_6mLevelEbEUlvE_vEEE6_M_runEv+0x1a4)[0x5617a679ea64]
./app/server/K(+0x50b54f)[0x5617a6b1d54f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7fcd6a0c36ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fcd69df93dd]

**Comment by ctubio** [comment]
many thanks for the report'¡ will fix threads soOn

**Comment by ctubio** [comment]
hope libuv fixed this after latest commits
