### ISSUE TITLE
Bitfinex not connecting

### ISSUE THREAD

**Issue by lompok10** [ctubio/Krypto-trading-bot#316]
Someone has had this issue:

12:16:38.127287 DB loaded Quoting Parameters OR reading defaults instead.
12:16:38.127361 DB loaded 0 historical Trades.
12:16:38.127425 DB loaded 0 STDEV Periods.
12:16:38.127484 DB loaded EWMA Long = 0.000000.
12:16:38.127516 DB loaded EWMA Medium = 0.000000.
12:16:38.127539 DB loaded EWMA Short = 0.000000.
12:16:38.127592 DB loaded TBP = 0.00000000 BTC.
12:16:38.757413 GW BITFINEX WS Info {"event":"info","version":2}.
12:16:38.909913 GW BITFINEX WS Streaming channel 85:trades.
12:16:38.910432 GW BITFINEX WS Disconnected, reconnecting..
12:16:39.127953 QE Warrrrning: Unable to calculate quote, missing fair value.
12:16:40.128265 QE Warrrrning: Unable to calculate quote, missing fair value.
12:16:41.128541 QE Warrrrning: Unable to calculate quote, missing fair value.
12:16:42.128817 QE Warrrrning: Unable to calculate quote, missing fair value.
12:16:43.129091 QE Warrrrning: Unable to calculate quote, missing fair value.
12:16:44.129365 QE Warrrrning: Unable to calculate quote, missing fair value.

**Comment by ctubio** [comment]
notpe, but let me see this afternoon if i can reproduce it

**Comment by ctubio** [comment]
well now we have:
```
17:37:43.975448 Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x1a)[0x5616db9ae5ca]
./app/server/K(_ZN1K2EV3wtfEi+0x41e)[0x5616db9b127e]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f31f5fc3030]
./app/server/K(uv_timer_start+0x2b)[0x5616dbcd87db]
./app/server/K(_ZN1K10GwBitfinex6levelsEv+0x135)[0x5616dba12895]
./app/server/K(_ZN1K2GW4mainEv+0xf1)[0x5616db9a1e51]
./app/server/K(main+0x156)[0x5616db9a4716]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f31f5fb02b1]
./app/server/K(_start+0x2a)[0x5616db9a7eaa]

```

**Comment by ctubio** [comment]
for me connects fine to bitfinex now
