### ISSUE TITLE
IMPROVEMENT Reforming the market making strategy of the bot

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#317]
Hi all,

After some reflections, I think it would be a great plus to reform the way the bot is divided.
We've seen/made tremendous improvements in the abilities of the bot however we need to rethink how those improvements work together.

This will also help for further improvements and how to implement them nicely in the code.

I think the concept of "mode" is misused.
A mode should be a way to get a quote ONLY using the market data, everything that uses past trades or memory should be called and labeled as a safety. By doing so we are able to mix different safeties in the same way you can use ewma and stdev together today.
This will create new options like for instance the bullets of Ak47 as well as the Hamelin Rat mode. (So much power!!).

### 1) Correctly relabelling the modes [FIXED]
Top, mid, join, inverses, Hamelin rat, Depth should keep their status of "mode" as they don't require any memory.

Ak-47, PingPong, Boomerang should become safeties.

By becoming safeties, they should all have their own settings (so one separate pong width for ping-pong and one for boomerang).

### 2) Defining those safeties by their key characteristics
**a) Pingpong** [FIXED]
The key characteristic of ping-pong is to use the last buy or the last sell as the base for the new quote. It's quite easy, you just need to remember last buy / last sell and apply to it "PingPong width pong" to get the quote.
If the FV is above the last sold price by a margin superior to the "PingPong width pong", Pingpong safety BUY is off (until the price comes back down).
If the FV is below the last bought price by a margin superior to the PingPong width pong, Pingpong safety SELL is off. (until the price comes up).
(Ps: PingPongwidth range should be in % if %w? is checked).

**b) Ak47** [FIXED]
Ak47 is an insurance to profit from big orders in the book by placing secondary orders quite far in the book. It places an order at a "range" above and below the quote.  (or many orders).
(Ps: Ak47 range should work in % if %w? is checked) 

**c) Boomerang** [TODO]
Boomerang idea is to be the same as ping-pong but with any past order. 
I REALLY don't like Boomerang in its current form. The problem is that matching an order with any past order is way too easy. You will always find a 'Ping' to match your pong, so the width pong when using boomerang is only cosmetic. It will NOT push the bid /ask quote higher or lower.
But if you like it, well let's keep it like that.  I assure you, and you can check that width pong is really useless, unless you're using "fair" ping in which case ping width becomes useless.

A possible fix to boomerang is to use the weighted average of the trades registered (and not closed), so, for instance, you calculate the weighted average of your open ping buys, and that becomes the safety level for boomerang. 
Once you have the average buy and average sell, you report to this average buy / sell the width pong and you get your quote.
If the FV is above the sold average price by a margin superior to the Boomerang width pong, Boomerang safety BUY is off.
If the FV is below the average buy price by a margin superior to the Boomerang width pong, Boomerang safety SELL is off. (until the price comes back up).

For each new trade, you update the average by either adding one trade in the average (not matching) or suppressing one (matching).

For instance, if you have 3 buys in your history at 90, 95 and 100 and 2 sell at 87 and 89.
Your average sell is 88 and average buy is 95.
So you try to buy at 88 - width pong and sell at 95 + width pong.

If you make a buy below "88 - pong width" it's a match. If you make a sell above "95 + pong width".
So let's say you make a new buy at 90, it's not a match and your average buy price is now: 93.75.

Now imagine you make a new buy at 85, it's a match so you don't add it to the average but you "close it" with the 87 or the 89 sell order (depending if you're using Short or Long in PongAt).
Let's say you use long, you match with the 89 and your new average sell is 87 :).

We can talk about it if you like it but I think it's more urgent to fix the current issue before that.

### 3) Reforming PongAt: [WONTFIX]

I think fair Pongat is useless as it totally covers ping Width when used. I can't see a situation where it's useful but maybe I'm wrong!

Well tell me what you think about those changes and if you see think that it's useful. We have seen a lot of reforms on the code and I think it's important to focus now a bit more on the strategies!

Best,

Camille

**Comment by b-seite** [comment]
Hi Camille,

tried to resolve point 1 here #346 
I go on and try to work on point 2 (if my coding skills are good enough for that)

**Comment by Camille92** [comment]
Thank you for your time and work @b-seite  :D

**Comment by ctubio** [comment]
will update docs later to reflect b-seite mods

**Comment by ctubio** [comment]
i think all here was implemented by b-seite; only missing the Boomerang "weighted average of the trades registered (and not closed)" but i think you explained a new quoting mode, not a improvement for Boomerang; will consider'¡

about fair pongAt, is usefull as long as there is the need to have a way to unselect agressive pongAt while still choosing long or short
