### ISSUE TITLE
Noob Question

### ISSUE THREAD

**Issue by lompok10** [ctubio/Krypto-trading-bot#318]
Firstable sorry whether this is a dumb question but i would like to know what  would be a minimun amount of capital for this kind strategy in trading since i come from forex and that is a little different.

Also, i am currentley using HITBTC as exchange and recieving  Disconected in UI´s Market and Data Quotes:

![image](https://user-images.githubusercontent.com/4948739/31837342-12006f78-b59e-11e7-8985-357618ec5f33.png)

**Comment by ctubio** [comment]
if you plan to place orders of a quantity of 0.01, you could want to be able to do 10 trades on each side, so 0.1 will be the minimum balance you may want.

^here all numbers are variables, you can play with yout own :dancer:

hope this is what you mean''
