### ISSUE TITLE
Bitfinex not getting wallet info

### ISSUE THREAD

**Issue by lompok10** [ctubio/Krypto-trading-bot#320]
I have tested updated and reinstalling from scratch but the program is not getting wallet info from Bitfinex, so is not calculating TBP and so the system is not working completely

![bit](https://user-images.githubusercontent.com/4948739/31857201-c5f9978e-b69d-11e7-86cb-56d1641c9bb6.png)

**Comment by lompok10** [comment]
After reinstalled, tried with HITBTC and working properly

**Comment by ctubio** [comment]
check you api keys or user agreements of bitfinex website; here is working fine bitfinex
