### ISSUE TITLE
Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found)

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#322]
I've find out that this problem appears when using '--free-version' flag!

<serzhiio> 17:43:01.517234 UI authorization success from ::ffff:87.255.31.112.
<serzhiio> 17:43:01.575284 Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
<serzhiio> ./app/server/K(_ZN1K2EV6reportEv+0x1a)[0x555fc0c160aa]
<serzhiio> ./app/server/K(_ZN1K2EV3wtfEi+0x41e)[0x555fc0c18d4e]
<serzhiio> ./app/server/K(uv_async_send+0x0)[0x555fc0f33dc0]
<serzhiio> ./app/server/K(_ZN2uS6Socket10changePollEPS0_+0x7b)[0x555fc0c20f9b]
<serzhiio> ./app/server/K(_ZN2uS6Socket5writeEPNS0_5Queue7MessageERb+0x101)[0x555fc0c21101]
<serzhiio> ./app/server/K(_ZN2uS6Socket15sendTransformedIZN3uWS12HttpResponse5writeEPKcmPFvPvS6_bS6_ES6_E15NoopTransformeriEEvS5_mS8_S6_T0_+0x1de)[0x555fc0c212fe]
<serzhiio> ./app/server/K(_ZZN1K2UI4mainEvENKUlPN3uWS12HttpResponseENS1_11HttpRequestEPcmmE1_clES3_S4_S5_mm+0x75c)[0x555fc0c21aac]
<serzhiio> ./app/server/K(_ZN3uWS10HttpSocketILb1EE6onDataEPN2uS6SocketEPcm+0x470)[0x555fc0c53480]
<serzhiio> ./app/server/K(_ZN2uS6Socket12sslIoHandlerIN3uWS10HttpSocketILb1EEEEEvP4Pollii+0x177)[0x555fc0c56b87]
<serzhiio> ./app/server/K(uv__io_poll+0x318)[0x555fc0f3e2b8]
<serzhiio> ./app/server/K(uv_run+0x114)[0x555fc0f343a4]
<serzhiio> ./app/server/K(+0x1bbe39)[0x555fc0c71e39]
<serzhiio> ./app/server/K(+0x512d2f)[0x555fc0fc8d2f]
<serzhiio> Yikes!
<serzhiio> please copy and paste the error above into a new github issue (noworry for duplicates).
<serzhiio> If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by ctubio** [comment]
only when using it concurrently in multiple instances!
