### ISSUE TITLE
UI bug, current trades window empty

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#323]
After click button 'click to view data' nothing happens, current trades window always empty.
In browser console an error appears:
"bundle.min.js:1 WebSocket connection to 'wss://165.227.XXX.XXX:3000/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
KSocket @ bundle.min.js:1"

**Comment by ctubio** [comment]
what exchange you mean? hitbtc doesnt have market trades data
