### ISSUE TITLE
Can't connect to EDO/USD instance ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#326]
Hi Carles,

There's something a bit weird,

I can't connect to my EDO/USD instance, I don't know why it's the only one not working.
Also this is the only pair "locked" for me, even if I used a already unlocked api key from another market, it wouldn't want to be unlocked.

Any info on that?

Best,
Camille

**Comment by ctubio** [comment]
locks are based on apikey+currency pair; feel free to let me know the locked btc adddess

**Comment by Camille92** [comment]
No probs!

Once I manage to get my hand back on this instance :p

**Comment by ctubio** [comment]
well, feeling happy i had unlocked all EDOs addresses (3), i beleive yours was included too :dancer:

please feel free to open a new issue about the "unable to connect" when you consider

**Comment by Camille92** [comment]
It's working again!

Thank you :)
