### ISSUE TITLE
Can't put width below 1$

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#327]
I've noticed new rules that block you from putting width below 1, it's not a good rule.

I want to put the width on 0.05 USD for some markets trading the asset around 5USD and I can't :S.

Not talking about the people trading in BTC denominated markets!

**Comment by b-seite** [comment]
Hi Camille 

i hope i found the error and resolved it here: cbad38363b0c580aa9fd8343733d74f4244e63e0
It is because the server imports the floating values from the GUI as integer and cuts the decimals

**Comment by ctubio** [comment]
umf iSee.. i copy pasted from 600 commits ago and didnt fixed the datatypes :( but super @b-seite  fixed it at https://github.com/ctubio/Krypto-trading-bot/pull/331/files; will merge soOn

**Comment by b-seite** [comment]
Hey Charles,
i know its a bit off topic but i think that's a good idea to display the minTicks and minSize in the GUI. 
It was no Problem to get the minTicks value (of course not) to the GUI but i cannot figure out how to advertise minSize. I ended on models.productAdversiesment but got no further...

**Comment by ctubio** [comment]
minSize is displayed in the logs onboot, do you mean that this is not enough and should be also displayed in the UI? im not sure :S

**Comment by Camille92** [comment]
Can you please reopen tar because it still not fix ?

OR should I need to do a make dep ?
