### ISSUE TITLE
New safety: Average width over period

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#328]
Hi Carles,

I had an idea of an easy to implement and efficient safety to add to the bot.

This would be to calculate the ewma of the width over a period (in seconds) and report it from FV. (with a factor option like for stdev).

It's quite easy to implement and that should help to put the optimum width setting!

Tell me what you think,

Best,
Camille

**Comment by ctubio** [comment]
by "ewma of the width" you mean the ewma of the diff betwen topBid and topAsk?

**Comment by Camille92** [comment]
Yes!

Then you get 
bid quote = FV - (Ewma Width / 2)
Ask quote = FV + (Ewma width /2)

**Comment by Camille92** [comment]
The goal is to answer the question:
How to benefit most from the market? Without putting too little or too wide width.

I tried to fix that with stdev but with mixed results, I hope a simple average could better pinpoint the width to use.

PS: stdev tops and on top seems to be broken as they have both the exact same results!

**Comment by serzhiio** [comment]
Whole week the thought about abg width didn't get out of my head.
That would be a perfect solution for Join-like modes.
I think that we need to create **autoWidth** checkbox input for Join-like modes except Inversed modes.

**Comment by serzhiio** [comment]
Camille, why you propose ewma of width? Why not use simple Average?

**Comment by Camille92** [comment]
Because Ewma is easier to calculate!

**Comment by b-seite** [comment]
Hi all,

i see that @serzhiio implemented the average width in his pull request. Very cool!

It is calculated with an average formula. I think that EWMA might be better to weight the closer past higher. 
And i am thinking about the question: Is it better do put all that in a separate quoting mode or as a safety for all modes?

**Comment by serzhiio** [comment]
imho ping average is a kind of protection not a mode or safety. Because it can be usefull with both modes and safeties.

**Comment by b-seite** [comment]
I am still thinking about the average width and have some ideas about it. 

1. maybe we can do a compromise between the ammount of params and size of code. If we Compute just one width and reuse the ewma Protection size for the with over Time then we have only two new params: the activation and the Percentage. But i think that we May be not  even Need a percentage. Then there is one on/off Switch left. And one new ewma Vector Störes in the db.  

2. The market width is changing very often. If we take only one Value Every Second then that Will Never be a realistc average. My idea is to accumlate the Values of the width every second or even every new calculated one. Then we calculate an average every Minute over These values and then an ewma with the result of the First average calculation. 
So and then the big question: Is it worth all that? I am thankfull for any comments

**Comment by donaldforest** [comment]
@Camille92 In which case it can be helpful?
