### ISSUE TITLE
(Small improvement) wBBO + depth 

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#33]
Hi Carles,

Just for a small improvement this time, we talked about a way of calculating FV including the weight of not only the first orders but a few.

Here is the simple formula:
We first calculate the total size of the orders in the book (maybe all the orders, maybe something preset by the user):
VolBidSize = VolumeOrder1 + VolumeOrder2 + VolumeOrder3 ...
VolAskSize = VolumeOrder1 + VolumeOrder2 + VolumeOrder3 ...
TotalVolume = VolBidSize + VolAskSize

Then we do a simple weighted average:
wBB0 = (BestBidPrice * VolBidSize + BestAskPrice* VolAskSize) / TotalVolume

This should give a result always between the 2 BestPrice.

Another solution is to go simply for:
Weighted AskPrice =VolumeOrderAsk1  * PriceOrderAsk1 + VolumeOrderAsk2  * PriceOrderAsk2 + VolumeOrderAsk3  * PriceOrderAsk3 ...

WeightedBidPrice = VolumeOrderBid1  * PriceOrderBid1 + VolumeOrderBid2  * PriceOrderBid2 + VolumeOrderBid3  * PriceOrderBid3 ...

wBBO = WeightedBidPrice + WeightedAskPrice / TotalVolume

But this can get results out of the two best offered prices and I don't know if it's something we want.

**Comment by ctubio** [comment]
so the plan is to keep BBO as-is, and to modify the calculation of wBBO, no?
thanks for confirm'0¡

**Comment by Camille92** [comment]
Yes I would say so, but imho it's really far from being the most relevant improvement.
I would actually put it bottom of my list haha!

**Comment by ctubio** [comment]
this is not possible, because if the bot calculates a fair value that is over the sell price or under the buy price it will place taker orders nonstop; just because a big order is at depth +1 in some side.
