### ISSUE TITLE
After update to commit 11c8a15 K hangs after loading data from DB

### ISSUE THREAD

**Issue by Mir4ik** [ctubio/Krypto-trading-bot#330]
Output in console:
K build x86_64-linux-gnu 2017-10-24 00:27:16.
K version 0day.
09:17:56.957679 UI ready over HTTPS on external port 3000.
09:17:57.097191 GW HITBTC allows client IP.
09:17:57.097293 GW HITBTC:
- autoBot: no
- pair: ETHUSD
- minTick: 0.01000000
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000.
09:17:57.097647 DB /data/db/K.1.ETH.USD.db loaded OK.
09:17:57.205602 DB loaded Quoting Parameters OR reading defaults instead.
09:17:57.290739 DB loaded 0 historical Trades.
09:17:57.393472 DB loaded 0 STDEV Periods.
09:17:57.493600 DB loaded EWMA Long = 0.000000.
09:17:57.493704 DB loaded EWMA Medium = 0.000000.
09:17:57.493733 DB loaded EWMA Short = 0.000000.
09:17:57.587362 DB loaded TBP = 0.00000000 ETH.

No way I can connect using UI; can telnet onto it but seems something wrong with http server. 
Tried new keys from HITBTC, clean install, even clean install on new server (Ubuntu VM in Azure). Everything was working find till update. 
Any way I can check logs to see what's wrong? was not able to find them on server

**Comment by ctubio** [comment]
umm.. i never experienced this i think; to see more logs only is possible with argument `--debug`; also can you try to delete the database file and start it again to see if it helps? (you can temporarily `mv` files in `/data/db/*` or run `make cleandb`)

feel free to paste any interesting log, apikeys are never printed in logs

**Comment by Camille92** [comment]
I think it's what I had with Edo.
I couldn't connect to the web ui and once you unlocked my key, it worked again.

Are you using the free version?

**Comment by Mir4ik** [comment]
Tried with --debug - no changes to output. Cleaned db - also no luck. UI still not working, browser errors out with "ook too long to respond", telnet to port 3000 works fine from same PC. 

Let me try to check out to previous commit that was working and try it out.  

```
mir4ik@k-bot:~/K$ ./K.sh --debug
K build x86_64-linux-gnu 2017-10-24 00:27:16.
K version 0day.
12:01:40.656863 UI ready over HTTPS on external port 3000.
12:01:40.749862 GW HITBTC allows client IP.
12:01:40.749982 GW HITBTC:
- autoBot: yes
- pair: ETHUSD
- minTick: 0.01000000
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000.
12:01:40.750278 DB /data/db/K.1.ETH.USD.db loaded OK.
12:01:40.750484 DB loaded Quoting Parameters OR reading defaults instead.
12:01:40.750555 DB loaded 0 historical Trades.
12:01:40.750621 DB loaded 0 STDEV Periods.
12:01:40.750682 DB loaded EWMA Long = 0.000000.
12:01:40.751040 DB loaded EWMA Medium = 0.000000.
12:01:40.751072 DB loaded EWMA Short = 0.000000.
12:01:40.751135 DB loaded TBP = 0.00000000 ETH.
♥
12:02:18.661775 GW HITBTC Attempting to cancel all open orders, please wait..
12:02:18.710816 GW HITBTC cancell all open orders OK.
12:02:18.710970 K exit code 0.

mir4ik@k-bot:~/K$ make cleandb
rm -rf /data/db/K*.db
mir4ik@k-bot:~/K$ ./K.sh --debug
K build x86_64-linux-gnu 2017-10-24 00:27:16.
K version 0day.
12:02:52.761184 UI ready over HTTPS on external port 3000.
12:02:52.837432 GW HITBTC allows client IP.
12:02:52.837538 GW HITBTC:
- autoBot: yes
- pair: ETHUSD
- minTick: 0.01000000
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000.
12:02:52.837859 DB /data/db/K.1.ETH.USD.db loaded OK.
12:02:52.960951 DB loaded Quoting Parameters OR reading defaults instead.
12:02:53.103136 DB loaded 0 historical Trades.
12:02:53.181135 DB loaded 0 STDEV Periods.
12:02:53.274599 DB loaded EWMA Long = 0.000000.
12:02:53.274708 DB loaded EWMA Medium = 0.000000.
12:02:53.274737 DB loaded EWMA Short = 0.000000.
12:02:53.367765 DB loaded TBP = 0.00000000 ETH.
```

**Comment by Mir4ik** [comment]
Ok, thanks to @Camille92 - added --free-version and was able to proceed, now I can log in to web ui and see detailed output so this seems to be an issue non using --free-version attribute. 

But now I am getting other issue:

**Comment by ctubio** [comment]
closing cos currently public ws of hitbtc is up and down non-stop since a few days ago; feel free to email hitbtc asking when the ws of market  data will be stable again :S im lazy to do fallbackt o http but will consider if this last forever
