### ISSUE TITLE
Send zip-bomb if UI IP is not in whitelist

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#332]
add some argument to whitelist a csv of IPs, then if an alien IP attempts to access the UI serve https://en.wikipedia.org/wiki/Zip_bomb like  http://www.unforgettable.dk/42.zip instead of the usual login prompt

Edited: ah yea btw, download is OK but do not try to uncompress ^this zip :dancer: for serving proposes the password in the zip needs to be removed

**Comment by benfavre** [comment]
:grin: :skull:
