### ISSUE TITLE
Can't connect to container

### ISSUE THREAD

**Issue by mvarle** [ctubio/Krypto-trading-bot#333]
Let me first say I am new to docker. I managed to set up the installation following the docker installation guide using a Dockerfile. I can see the container is running but I can't access it through my browser. I am running this on windows 7 machine. I can ping the default machine but when I try to ping the container I get timeout. 

I can see the container is running at 0.0.0.0:3000->3000. I'm not sure if this is the issue.

Is anyone able to tell me what I am doing wrong or guide me in a direction?

**Comment by ctubio** [comment]
let me recommend in you case https://kitematic.com/; is a very nice user interface to manage your containers, and easily access ui by clicking a web preview near the console output (http://agup.tech/content/images/2015/08/Kitematic.PNG), later without hurry you can go back to docker commands if you really want to keep using docker

hope it helps'¡
