### ISSUE TITLE
[Bug] Chuck norris should not need to type his name before a command

### ISSUE THREAD

**Issue by benfavre** [ctubio/Krypto-trading-bot#334]
Found a bug : 
"Excellent decision! Chuck Norris doesn't need sudo, he just types "Chuck Norris" before his commands."

I don't think he should need to type his name.
Thanks.

**Comment by ctubio** [comment]
![giphy 1](https://user-images.githubusercontent.com/1634027/32020239-dcf799b0-b9cf-11e7-9a9b-9a6df2409248.gif)

**Comment by ctubio** [comment]
closing cos seems Chuck Norris doesn't need an OS.
