### ISSUE TITLE
Profits that survive a restart?

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#335]
Hej Charles,

at the moment i restart my bots hourly (hope to reduce the CPU performance issues i have)
I recognize that the Profit values begin at 0% every restart no matter what setting i use for profit.

I think it could  be helpful if the profit % resists a restart.

Is that easy to realize? If i understand it right, profits are calculated over the trades stored im memory.

thanks in advance 
Boris
---
```
app exchange: Coinbase/BTC/EUR
app version: latest
OS distro: Ubuntu 16.04
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
thanks for the idea, will consider soOn''

**Comment by b-seite** [comment]
Yes, see image below. this is the last day with a hourly restart. 
Stange thing is that its so different every hour. Sometimes CPU usage is more or less ok but sometimes horrible until next restart. (and i know K can do that better, i´ve seen it in the past)
![bildschirmfoto 2017-10-26 um 10 05 17](https://user-images.githubusercontent.com/540850/32041941-4bdf1aea-ba36-11e7-9969-bb09c031804b.png)

**Comment by Camille92** [comment]
(I "restartall" every hour too because of zombie orders / fake orders in the book too)

**Comment by ctubio** [comment]
thanks for the comments'¡ just moved gdax thread outta here :dancer: hope you agree

**Comment by ctubio** [comment]
@b-seite just saying, profits come directly from wallet values, not from historical trades
