### ISSUE TITLE
AK47 bug at ETH/BTC

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#336]
Second bullet range doesn't respect defined one. Look at the distance between 2 buy orders on the screenshot. Seems this problem occurs at other pairs not denominated in BTC.
![bot-ak47bug](https://user-images.githubusercontent.com/10449591/32018670-4b57fde8-b9d3-11e7-9fd9-85ac66494529.jpg)

**Comment by donaldforest** [comment]
Same on BTC/USD on HitBTC. Range value has no effect to second and another orders. I was trying test values above 10-40$..
