### ISSUE TITLE
Can't access Web UI using Dreamhost

### ISSUE THREAD

**Issue by mvarle** [ctubio/Krypto-trading-bot#337]
Hi guys

First of all sorry if this is noob question. I am more of a finance guy and still have a lot to learn in the CS field. 

I have been following the guide and I have successfully setup the application on Dreamhost Debian Instance. I went through the guide and everything went fine. K version is running. But when I try to access UI through my browser I get connection timed out. I use MyServerIp:3000 or https://MyServerIp:3000. But none of them is working. I suspect it might have to do with my server settings at Dreamhost and I was hoping one of you would be able to direct me in the right direction. I am currently using default settings at Dreamhost. 

This is the output I get from PuTTy when I run K.sh:

13:45:46.805402 UI ready over HTTPS on external port 3000.
13:45:46.805492 GW NULL allows client IP.
13:45:46.805536 GW NULL:
- autoBot: no
- pair: BTC_USD
- minTick: 0.01000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000.
13:45:46.805772 DB /data/db/K.0.BTC.USD.db loaded OK.
13:45:46.806239 DB loaded Quoting Parameters OR reading defaults instead.
13:45:46.806281 DB loaded 0 historical Trades.
13:45:46.806521 DB loaded 9 STDEV Periods.
13:45:46.806608 DB loaded EWMA Long = 935.742563.
13:45:46.806617 DB loaded EWMA Medium = 999.138889.
13:45:46.806621 DB loaded EWMA Short = 0.000000.
13:45:46.806677 DB loaded TBP = 5.06528654 BTC.

**Comment by normanu** [comment]
For some reason with the latest update, it also doesn't seem to work for me anymore.
It seems to not connect to the exchanges.

**Comment by ctubio** [comment]
you need to open the port 3000 in the Network Group associated with your Debian instance

the rule you need is TCP Ingress port 3000, see https://help.dreamhost.com/hc/en-us/articles/215912838-How-to-configure-access-and-security-for-DreamCompute-instances

hope it helps''

**Comment by normanu** [comment]
Im not using a VPS, its my local Linux server.
It worked before doing a make reinstall

**Comment by ctubio** [comment]
wtf is a Dreamhost Debian? a local linux? why is called Dreamhost then? are you Dreamhost?

i dont understand you

**Comment by normanu** [comment]
Two different replies in this thread.
I'm not the topic starter.
