### ISSUE TITLE
GDAX high cpu

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#339]
moar info at https://github.com/ctubio/Krypto-trading-bot/issues/335#issuecomment-339587899

**Comment by b-seite** [comment]
Hi Carles,

i think we can close this issue for now. My GDAX runs like a charm since several days. See image attached.

Thanks a lot

![bildschirmfoto 2017-11-01 um 20 15 50](https://user-images.githubusercontent.com/540850/32292889-c898724c-bf41-11e7-855f-9524eab524a5.png)

**Comment by ctubio** [comment]
it hink was the FileLogFactory of quickfix
