### ISSUE TITLE
Bitfinex Bug zombie orders in the order book

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#340]
![capture d ecran 2017-10-27 a 13 48 09](https://user-images.githubusercontent.com/6861590/32102661-a3d0e4bc-bb1d-11e7-9abf-ff735088889e.png)

In this picture, all the orders at 255 are past orders not updated.

Potential issues: in the quote creation that might consider those orders as real and in the calculation of the ewma.

Seriously, guys, we need to focus on the bugs for a while before doing improvements because at the moment nothing works correctly. 😞

**Comment by b-seite** [comment]
I am with you and i also think that we have to focus on the bugs. 
i will spend my time and coding skills to find and delete bugs in the code.

Let's  find the 🐞 🐞🐞

**Comment by Camille92** [comment]
A simple solution: why not restarting the bot or at least throwing away all the market book when Market width < 0?
![capture d ecran 2017-10-31 a 12 43 41](https://user-images.githubusercontent.com/6861590/32222354-3d0da066-be39-11e7-8c6e-a2090712e9c0.png)

**Comment by serzhiio** [comment]
Definitely agree! We need some kind of bad data protection.

**Comment by b-seite** [comment]
seen it on bitfinex today:
![bildschirmfoto 2017-11-03 um 12 56 08](https://user-images.githubusercontent.com/540850/32372799-b09d2fce-c096-11e7-880a-4d382068f2ed.png)
Negative market width and zombie quotes.

**Comment by Camille92** [comment]
yes it happens to me all the time !

So do you think a "if market width < 0" -> restart bot is a solution?

**Comment by ctubio** [comment]
if after the next commit the order book shows zombie orders, that is not zombie orders, thats zombie levels in the UI only (not in the server)
