### ISSUE TITLE
Can't access Web UI on DigitalOcean

### ISSUE THREAD

**Issue by zilions** [ctubio/Krypto-trading-bot#342]
Have spun up a new Debian instance and installed the K package perfectly. Although can't seem to view the Web UI with myIP:3000. Just times out every time.

I tested with http://ping.eu/port-chk/ and it states that port 3000 of my IP is definitely open. So it's just not publicly accessible for some reason.

**Comment by b-seite** [comment]
maybe a silly question but have you tried it with https://myIP:3000?

**Comment by serzhiio** [comment]
What pair do you trying to trade?

**Comment by zilions** [comment]
Yes I tried with both http and https.
Trying HitBTC with BCH/BTC. The console states that trading is working and the pair is found, although just can’t access the IP/port from outside the instance.

**Comment by serzhiio** [comment]
I have quite the same problem and i'm on DigitalOcean too.
Look at issue #325

**Comment by ctubio** [comment]
i think this happened because https://github.com/ctubio/Krypto-trading-bot/issues/345, closing this cos was just fixed
