### ISSUE TITLE
./K.sh: Permission denied

### ISSUE THREAD

**Issue by DerekPadula** [ctubio/Krypto-trading-bot#343]
I've been trying to run this software via Linux Ubuntu 16.04 on Windows 10 for the last two nights, without success. I've installed it by following the installation guide with SSH. I've also done a full delete and fresh install with https. Both with Linux run as administrator. I have the dependent packages and have configured my generated K.sh file in my editor to connect to GDAX, with the appropriate keys. However, each time I try to execute ./K.sh via the terminal I receive the following message:

```
derek@LAPTOP-H628005C:~/K$ ./K.sh
-bash: ./K.sh: Permission denied
```

When I double click the K.sh file it opens a window and then loops the following:

```
./app/server/K: line 1: ../../build-x86_64-linux-gnu/local/bin/K-x86_64-linux-gnu: No such file or directory
K crashed with exit code 127.. Respawning..
```
I searched for the log files, but could not find them. 

I'm at a loss for what to do. Any ideas?

**Comment by serzhiio** [comment]
Try to chmod *.sh file to local user and give to file X perms.

**Comment by ctubio** [comment]
thank you @serzhiio ''''
