### ISSUE TITLE
New HITBTC APIv2

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#344]
Should be integrated!
DOC is here:
https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv2.md#subscribe-to-orderbook
REST https://api.hitbtc.com/api/2
SOCKET wss://api.hitbtc.com/api/2/ws

**Comment by serzhiio** [comment]
FIX protocol using:
https://github.com/hitbtc-com/hitbtc-api/blob/master/fix.md

**Comment by ctubio** [comment]
about fix, it doesnt says the endpoint, so there is no way to connect.

**Comment by serzhiio** [comment]
FIX is accessible via OpenVPN connection for BIG MM, thats why they didn't publish IP.
