### ISSUE TITLE
Locked bot without the --free-version doesn't work 

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#345]
According to what I read and my experience (everything works but I can't start using the bot with BTG for which I'm not unlocked), it seems that when the bot is not unlocked you can't use it.

The fix is to use the` --free-version` argument. :)

**Comment by serzhiio** [comment]
Actually, bot doesn't lock it hangs up for 2-3 hours.
See #325.

**Comment by ctubio** [comment]
many thanks for the report'''
