### ISSUE TITLE
git fatal: ambiguous argument '@..@{u}': unknown revision or path not in working tree.

### ISSUE THREAD

**Issue by dullfig** [ctubio/Krypto-trading-bot#348]
after installing, I configured K.sh for Coinbase. When I execute make start, and make screen, I get over and over the following:

K version -3commits..
fatal: ambiguous argument '@..@{u}': unknown revision or path not in working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

what could be the problem? what other information do you guys need me to post?

Dan

**Comment by ctubio** [comment]
it seems that the running folder is not the top level clonned path of the git repository OR your current git version does not support the argument `@..@{u}` (strange)

can you please confirm you are running ./K.sh in the top level folder cloned from git?
also can you see what is the version/name of your git client?
also can  you see what are your remotes?

something similar to the following is expected:
```
[10:30:41] tradingBox 100 days 6:52 /home/admin/K (master)
 $ ls -la && git --version && git remote -v
total 424K
drwxrwxr-x  8 admin admin 4.0K Oct  8 15:33 ./
drwxr-xr-x 10 admin admin 4.0K Oct 30 09:17 ../
drwxrwxr-x  3 admin admin 4.0K Oct  8 15:33 app/
drwxrwxr-x  3 admin admin 4.0K Sep 28 14:43 build-x86_64-linux-gnu/
-rw-rw-r--  1 admin admin 1.1K Sep 23 20:38 COPYING
drwxrwxr-x  4 admin admin 4.0K Oct  7 17:42 etc/
drwxrwxr-x  8 admin admin 4.0K Oct  8 15:33 .git/
-rw-rw-r--  1 admin admin   82 Sep 23 20:38 .gitignore
-rwxrwxr-x  1 admin admin 4.5K Sep 23 21:15 K.sh*
-rw-rw-r--  1 admin admin  823 Sep 23 20:38 LICENSE
-rw-rw-r--  1 admin admin  16K Oct  8 15:33 Makefile
-rw-rw-r--  1 admin admin  23K Oct  7 22:26 MANUAL.md
-rw-rw-r--  1 admin admin 1.8K Sep 23 20:38 package.json
-rw-rw-r--  1 admin admin 287K Sep 28 04:08 package-lock.json
-rw-rw-r--  1 admin admin  20K Oct  8 15:33 README.md
drwxrwxr-x  5 admin admin 4.0K Sep 28 03:09 src/
drwxrwxr-x  2 admin admin 4.0K Sep 23 20:38 test/
-rw-rw-r--  1 admin admin  528 Sep 23 20:38 THANKS
-rw-rw-r--  1 admin admin  225 Sep 23 20:38 TODO
-rw-rw-r--  1 admin admin  534 Oct  7 17:42 .travis.yml

git version 2.11.0

origin  ssh://git@github.com/ctubio/Krypto-trading-bot (fetch)
origin  ssh://git@github.com/ctubio/Krypto-trading-bot (push)
```
having this, it should be possible to run (that is what the app is running):
```
[10:40:32] tradingBox 100 days 7:02 /home/admin/K (master)
 $ git rev-parse @
811f532068b4565a4c956c52b4241a75525f21ce

[10:43:19] tradingBox 100 days 7:05 /home/admin/K (master)
 $ git rev-parse @{u}
811f532068b4565a4c956c52b4241a75525f21ce
```
hope you can see whats your difference'' im not sure why for you fails this last 2 commands (that the app tries to runs on boot)

**Comment by ctubio** [comment]
this is the failing point for you https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/ev.h#L80 you may want to comment this line and recompile if git still gives you problems (im sorry i never found this problems with git and i can't imagine why)

**Comment by ctubio** [comment]
feel free to use https://github.com/ctubio/Krypto-trading-bot#manual-zip-installation in case git still gives your problems

hope it helps''
