### ISSUE TITLE
Strange code in Quoting Modes Top&InverseTop

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#350]
Hey All,

i,ve found these Lines in quotingModes Top & InverseTop but i do not understand the part with the k.bid.size > 0.2
https://github.com/ctubio/Krypto-trading-bot/blob/552f7f56a51e0c132fdcea2bcce655e2c8dcf096/src/server/qe.h#L421-L424
what function does it have? Is that a fixed value from a time where BTC was way below 1000$

besides that, im quiet sure that qp.mode != mQuotingMode::Join should be qp.mode != mQuotingMode::Top (as it is/was in Tribeca)

**Comment by ctubio** [comment]
this is logic coming from upstream project, unmodified yet in K:
https://github.com/michaelgrosner/tribeca/blob/06ff36cdbecccd602bb0fac88804dff415a2d2be/src/service/quoting-styles/top-join.ts#L58-L79

**Comment by b-seite** [comment]
Hey Charles,

yes i found the lines in the upstream project and i still think that is an error. 
The extra minTick is the only difference between Join and Top mode. 
For me, the code means that only quotes with a size > 0.2 get the extra minTick, and all the other quotes are same as Join or inverseJoin. 
Let's think about deleting the k.bid.size > 0.2 condition completely or put in a variable factor like minsize * 2 or so.
But in my opinion every quote should use the extra minTick... 
may i do a pull request with what i mean?

**Comment by ctubio** [comment]
i think this logic comes from a time where minTick didnt exists, so yea, must be updated accordingly

**Comment by ctubio** [comment]
sorry i didnt read the last sentence :dancer: sure feel free to PR your suggestion'''

**Comment by ctubio** [comment]
many thanks for the fixes'¡
