### ISSUE TITLE
Idea of "flat line" orders protection

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#357]
I've noticed that sometimes when strong flat occurs bot is trying to put orders within pingWidth almost on flat line. If you understood my description, i propose to make a protection that prevents such situations.

Bot should make a check using previous orders data from DB. When bot is considering to put buy/sell orders it should check if there is same type of previous order which price is not more or less current pingWidth.

Please give me a sign that you understand my idea
![flatline-orders](https://user-images.githubusercontent.com/10449591/32351329-05c9e352-c02e-11e7-8422-be84090a7d12.jpg)
 :)

**Comment by ctubio** [comment]
pingWidth checks against fairValue, not against price of previous orders;

to check price against previous orders use pongWidth (but if pongWidth matches with order X, it doesnt means it will be near and looking flat to order Y or order Z)
