### ISSUE TITLE
Can we remove the "depleted funds" thing ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#358]
Hi all,

I understand the idea of depleted funds, but it's usually more blocking for me than anything else.
Like I want to buy as much as possible in BTC, I put tbp manual 100% and pdiv = 0 but at some point, I run into depleted funds (especially annoying when you use %).

You have similar issues when using the new ewma trend protection!

At the end of the day, I'm not sure how helpful it is but maybe having it as an option can help!

Best,

Camille

**Comment by Camille92** [comment]
Not a real problem, don't worry

**Comment by juanzolo** [comment]
I second this, this is a bug. It keeps the bot from working at all. I did get TPBHeld at one point, then I restarted and got depleted funds on both ends.


IT doesnt work!
