### ISSUE TITLE
Errrror: Signal 6 Aborted (Three-Headed Monkey found).

### ISSUE THREAD

**Issue by DarkSunRise** [ctubio/Krypto-trading-bot#359]
device rpi 3, guessing thats it may happen due to prebuilt binaries. may be there is way to compile them locally?
it persist during startup. exchange BITFINEX
OPTIONAL_ARGUMENTS="--colors --naked --debug"
API_HTTP_ENDPOINT=https://api.bitfinex.com/v1
API_WSS_ENDPOINT=wss://api.bitfinex.com/ws/20

> pi@raspberrypi $ uname -a
> Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
> pi@raspberrypi $ cat /etc/os-release 
> PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="8"
> VERSION="8 (jessie)"
> ID=raspbian
> ID_LIKE=debian
> HOME_URL="http://www.raspbian.org/"
> SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
> BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
> pi@raspberrypi $ ./K.sh
> K build arm-linux-gnueabihf 2017-11-02 20:14:13.
> K version 0day.
> 19:35:57.891424 DB /data/db/K.4.BTC.USD.db loaded OK.
> 19:35:57.892788 UI ready over HTTPS on external port 3000.
> 19:35:57.893743 QP Warrrrning: using default values for Quoting Parameters.
> 19:35:57.893903 DB loaded 0 historical Trades.
> 19:35:57.894509 DB loaded 4 STDEV Periods.
> 19:35:57.894697 DB loaded EWMA Long = 0.000000.
> 19:35:57.894742 DB loaded EWMA Medium = 0.000000.
> 19:35:57.894777 DB loaded EWMA Short = 0.000000.
> 19:35:57.894934 DB loaded TBP = 0.00000000 BTC.
> 19:35:59.641573 GW BITFINEX allows client IP.
> 19:35:59.641969 GW BITFINEX: 
> - autoBot: no
> - pair: btcusd
> - minTick: 0.10000000
> - minSize: 0.00400000
> - makeFee: 0.00000000
> - takeFee: 0.00000000.
> 19:36:00.215359 DEBUG EV GW tDelay timer.
> 19:36:00.215897 DEBUG EV GW tWallet timer.
> 19:36:00.215980 DEBUG EV GW tCancel timer.
> 19:36:00.221300 DEBUG EV GW tCalcs timer.
> 19:36:00.221387 QE Warrrrning: Unable to calculate quote, missing fair value.
> 19:36:00.509467 DEBUG EV QE v_gwConnectButton.
> 19:36:00.509563 DEBUG EV QE ev_gwConnectExchange.
> 19:36:00.556769 GW BITFINEX WS Info {"event":"info","version":1.1}.
> 19:36:00.610113 GW BITFINEX WS Streaming channel 82:trades.
> 19:36:00.610788 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.611025 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.611255 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.611488 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.611759 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.611992 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.612219 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.612444 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.612670 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.612901 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.613127 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.613354 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.613577 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.613803 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.614025 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.614250 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.614475 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.614707 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.614931 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.615156 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.615380 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.615604 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.615830 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.616055 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.616279 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.616502 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.616727 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.616951 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.617176 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.617401 DEBUG EV MG ev_gwDataTrade.
> 19:36:00.617704 DEBUG EV QE v_gwConnectButton.
> 19:36:00.617782 DEBUG EV QE ev_gwConnectExchange.
> 19:36:00.617867 GW BITFINEX WS Streaming wallet and orders OK 0:"auth".
> 19:36:00.618291 DEBUG EV PG ev_gwDataWallet mWallet {"amount":0.0,"currency":"ETH","held":0.0}.
> 19:36:00.618486 DEBUG EV PG ev_gwDataWallet mWallet {"amount":0.00316708,"currency":"DSH","held":0.0}.
> 19:36:00.899797 GW BITFINEX WS Streaming channel 5949:book.
> 19:36:00.901636 DEBUG EV MG ev_gwDataLevels.
> 19:36:00.901792 DEBUG EV PG ev_gwDataWallet mWallet {"amount":0.0,"currency":"","held":0.0}.
> 19:36:00.901836 DEBUG EV QE ev_mgLevels.
> 19:36:01.215355 DEBUG EV GW tCalcs timer.
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  unresolved reference token '0'
> 19:36:02.041106 Errrror: Signal 6 Aborted (Three-Headed Monkey found).
> ./app/server/K(_ZN1K2EV3wtfEi+0x265)[0x54bf1e82]
> /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer_v2+0x0)[0x76d59180]
> /lib/arm-linux-gnueabihf/libc.so.6(gsignal+0x38)[0x76d57f70]
> 
> Yikes!
> please copy and paste the error above into a new github issue (noworry for duplicates).
> If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new
> 
> 19:36:05.060351 DEBUG EV QE v_gwConnectButton.
> 19:36:05.060432 DEBUG EV QE ev_gwConnectExchange.
> 19:36:05.060506 DEBUG EV QE v_gwConnectButton.
> 19:36:05.060555 DEBUG EV QE ev_gwConnectExchange.
> 19:36:05.060610 DEBUG EV MG ev_gwDataLevels.
> 19:36:05.060742 GW BITFINEX Attempting to cancel all open orders, please wait..
> 19:36:05.393224 GW BITFINEX cancell all open orders OK.
> 19:36:05.393750 K exit code 1.
> K crashed with exit code 1.. Respawning..

**Comment by DarkSunRise** [comment]
seems missed with API_WSS_ENDPOINT=wss://api.bitfinex.com/ws/20 should be .../ws/2
but still can't connect to bitfinex 
23:38:00.690914 GW BITFINEX WS Info {"event":"info","version":2}.
23:38:00.743440 GW BITFINEX WS Streaming channel 1:trades.
23:38:00.743839 DEBUG EV MG ev_gwDataTrade.
...
23:38:00.752145 DEBUG EV MG ev_gwDataTrade.
23:38:00.752470 DEBUG EV QE v_gwConnectButton.
23:38:00.752510 DEBUG EV QE ev_gwConnectExchange.
23:38:00.752590 DEBUG EV MG ev_gwDataLevels.
23:38:00.752788 GW BITFINEX WS Disconnect, reconnecting in 10s..
23:38:01.132741 DEBUG EV GW tCalcs timer.
23:38:01.132857 QE Warrrrning: Unable to calculate quote, missing fair value.
....
23:38:10.143817 QE Warrrrning: Unable to calculate quote, missing fair value.
23:38:11.125369 DEBUG EV GW tDelay timer.
23:38:11.144303 DEBUG EV GW tCalcs timer.
23:38:11.144640 QE Warrrrning: Unable to calculate quote, missing fair value.
23:38:11.158020 DEBUG EV QE v_gwConnectButton.
23:38:11.158287 DEBUG EV QE ev_gwConnectExchange.
23:38:11.162369 GW BITFINEX WS Info {"event":"info","version":2}.
23:38:11.286407 GW BITFINEX WS Streaming channel 79:trades.

**Comment by ctubio** [comment]
sorry im able to connect to bitfinex; consider to check your apikeys/user agreements
