### ISSUE TITLE
Latest commit orders placement bug

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#363]
I've noticed strange order placement behavior using HamelinRat (maybe other modes also in touch).
Look at the screenshot.
![order-placement-bug](https://user-images.githubusercontent.com/10449591/32413296-c7f6c204-c21f-11e7-975e-22ee2bc5b96c.jpg)

**Comment by ctubio** [comment]
fixed at https://github.com/ctubio/Krypto-trading-bot/pull/366
