### ISSUE TITLE
Hello HitBTC api v2

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#368]
**Where?**
HITBTC config file needs new api endpoints.

(example file [etc/K.sh.dist](https://github.com/ctubio/Krypto-trading-bot/blob/master/etc/K.sh.dist) was already updated)

**What?**
new correct HITBTC endpoints (like https://github.com/ctubio/Krypto-trading-bot/issues/372):
```
API_HTTP_ENDPOINT=https://api.hitbtc.com/api/2

API_WSS_ENDPOINT=wss://api.hitbtc.com/api/2/ws
```

and `API_WS_ENDPOINT`  can be removed.

**When?**
since https://github.com/ctubio/Krypto-trading-bot/commit/2a6dc757e925e3824910e2044d441b7be33daaa7

**Why?**
cos HITBTC API v1 is not working as expected since a few month ago

**Comment by serzhiio** [comment]
Wow... outstanding news! Thanks!
Will test now.
