### ISSUE TITLE
Strange orders size in HitBTC order book

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#369]
Please look at orders sizes in order book. They are extreamly low considering miSize of 0.01.
![strange-small-orders](https://user-images.githubusercontent.com/10449591/32437888-c6dac0ac-c2f9-11e7-8d24-e07434038ce6.jpg)

**Comment by ctubio** [comment]
sorry the app is still * by minSize the market prices, will fix soOn''
