### ISSUE TITLE
GUI blank screen on Safari

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#37]
I can not use the GUI on iOS. The only thing after login is a blank screen with a ? In the title. 
It worked several days ago like a charm on iPhone an iPad but after a npm run latest I see nothing like a white page. 

The bot is working normally with auto start and trades like before. 

I reinstalled the cert but nothing changed. 
Even without a cert-folder there is no difference, still a white screen

I am running the latest commit on Ubuntu 16.4 

Tested with Safari and Firefox on iOS 9 & 10

Any ideas?

**Comment by ctubio** [comment]
if the GUI works for you in one machine but fails in another, can you please go to http://supportdetails.com/ from the machine that the GUI is failing and copy here your specs? (you can export to csv format)

thanks'¡

**Comment by CarlitoGrey** [comment]
I get this also, only on iOS, using safari or chrome (thought hey both use the same rendering engine). Looks like it doesn't like something in the JS and stops rendering completely.

**Comment by ctubio** [comment]
GUI in iOS and server in linux? or server also ina macOS?

**Comment by CarlitoGrey** [comment]
Server on Ubuntu 16.04. Works fine from chrome on pc.

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by CarlitoGrey** [comment]
I may be able to debug this my end, if not at home then definitely at work (don't have a mac at home). Will take a look later tonight.

**Comment by ctubio** [comment]
to debug in safari is just open the javascript console, as any other browser errors are printed there

**Comment by ctubio** [comment]
consider to use chrome, im not sure what is the benefit of safarin? (to me seems like none)

**Comment by CarlitoGrey** [comment]
I don't believe there is a js console on the phone version of safari. You don't get a choice to use anything other than safari on an iPhone. Even chrome uses Safari's rendering engine on an iPhone. 

I'll have to hook my phone up to the mac at work this week and debug.

**Comment by b-seite** [comment]
Thanks a lot 
It is Wirkung Again on iOS. 

The only thing is this:  
![img_2500](https://user-images.githubusercontent.com/540850/27821018-0bd9c31c-60a1-11e7-95c0-336ba3cea178.PNG)
 Not Sure if it is a new issue 

But this is just Minor

**Comment by ctubio** [comment]
i broke again iOS because otherwise all other devices were broken; will try  to find a real fix soOn
