### ISSUE TITLE
Bitfinex/HitBTC no orders bug

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#370]
Cant understand why there is empty label at bid side and no BIDs at all.
pDiv is set to 15% to be sure that bid absense is not because of TBP.
![bitfinex-no-orders](https://user-images.githubusercontent.com/10449591/32438397-6254e5e8-c2fb-11e7-9f88-6b3da5613c30.jpg)

**Comment by serzhiio** [comment]
I've made some investigations.
Look, at this screenshot. Bot has calculated QuoteWidth and even blocked some amount, but there are no orders at all.
![bitfinex-no-orders-2](https://user-images.githubusercontent.com/10449591/32439122-5a195776-c2fe-11e7-9c54-e862a769aefd.jpg)

**Comment by serzhiio** [comment]
I'm using latest commit from 06-Nov.

**Comment by serzhiio** [comment]
And in logs there is always one order remains in memory.
Like that:
**DEBUG OG memory 1/0.**

**Comment by ctubio** [comment]
thanks, will fix at https://github.com/ctubio/Krypto-trading-bot/issues/367
