### ISSUE TITLE
Connecting error on latest commit / changes in K.sh 

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#372]
Hi Carles,

i tried to update from 488f80ad1e2d11f66299dc5ef101d9299806a766 to latest commit but my bots won't connect (GDAX & Bitfinex)
They both try to connect every 10sec. but without success. GUI Background is red.
When i go back to 488f80ad1e2d11f66299dc5ef101d9299806a766 the connection error is gone and they are working as expected

**Comment by serzhiio** [comment]
This problem occurs because you didn't change *.sh file.
Try to remove all lines with HitBTC WS strings. 
It helped me.

**Comment by b-seite** [comment]
Yeah thanks a lot that was it. 
Maybe we change this issue to a sticky note or something to remind others: 

For the latest commits you have to remove these Lines from your K.sh files :

> ## API_WS_ENDPOINT
> ### - Allows one of the following urls (see the website of the exchange).
> ### - Only HITBTC exchange must have API_WS_ENDPOINT, other exchanges can be NULL.
> #API_WS_ENDPOINT=ws://api.hitbtc.com:80
> API_WS_ENDPOINT=NULL

**Comment by Camille92** [comment]
Did you solve the problem ?

I got rid of those lines but I can't connect to the exchange :s

**Comment by Camille92** [comment]
Ok thanks, I will keep on trying!

**Comment by Camille92** [comment]
OK found the problem,

you need to ALSO delete the line

`--ws         $API_WS_ENDPOINT                       \`

best!

**Comment by ctubio** [comment]
err.. 4 issues ago there is already https://github.com/ctubio/Krypto-trading-bot/issues/368 :P

**Comment by ctubio** [comment]
reopening to attempt to avoid moar duplicates

**Comment by Optictrollz** [comment]
Is this still a problem? When I set up K.sh with all of GDAXs stuff without entering information it doesnt load any of the data into the WEB UI

**Comment by ctubio** [comment]
the app doesnt work without api keys

it was never expected that a trader will trade without api keys

the app is not a testing platform, is a trading platform
