### ISSUE TITLE
Bitfinex dat/usd issues 

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#373]
Hi Carles,

I have a problem with the DAT USD market on Bitfinex, it's always crashing! (since i updated from a older version today).

It's the only market with issues so I don't know what is happening!

K build x86_64-linux-gnu 2017-11-07 01:17:02.
02:04:11.159905 Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x1a)[0x561cd864a76a]
./app/server/K(_ZN1K2EV3wtfEi+0x41e)[0x561cd864ff3e]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7fc201fa74b0]
./app/server/K(_ZN3uWS5GroupILb0EE9broadcastEPKcmNS_6OpCodeE+0x50)[0x561cd868b3a0]
./app/server/K(_ZN1K3kxxEPN3uWS5GroupILb0EEE+0x2a0)[0x561cd86af490]
./app/server/K(+0x1c1544)[0x561cd86af544]
./app/server/K(+0x50904f)[0x561cd89f704f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7fc2023436ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fc2020793dd]

**Comment by ctubio** [comment]
can you run with --naked and paste the line before the Errrror? thanks''

**Comment by ctubio** [comment]
ah no that was https://github.com/ctubio/Krypto-trading-bot/issues/375 sorry just fixed it
