### ISSUE TITLE
[Bitfinex] Too much pending IDs to cancel

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#374]
I've noticed a lot of such lines in debug even when bot is disconnected:
```14:15:52.666093 QE Warrrrning: SELL quote ignored: depleted EOS balance.
14:15:52.666236 DEBUG OG cancel pending id 47928053.
14:15:52.666327 DEBUG OG cancel pending id 80476436.
14:15:52.666503 DEBUG OG cancel pending id 11777942.
14:15:52.666613 DEBUG OG cancel pending id 15235934.
14:15:52.666668 DEBUG OG cancel pending id 12081847.
14:15:52.666705 DEBUG OG cancel pending id 17157729.
14:15:52.666736 DEBUG OG cancel pending id 28066222.
14:15:52.666769 DEBUG OG cancel pending id 99546452.
14:15:52.666936 QE Warrrrning: SELL quote ignored: depleted EOS balance.
14:15:52.666982 DEBUG OG cancel pending id 47928053.
14:15:52.667023 DEBUG OG cancel pending id 80476436.
14:15:52.667056 DEBUG OG cancel pending id 11777942.
14:15:52.667085 DEBUG OG cancel pending id 15235934.
14:15:52.667116 DEBUG OG cancel pending id 12081847.
14:15:52.667148 DEBUG OG cancel pending id 17157729.
14:15:52.667182 DEBUG OG cancel pending id 28066222.
14:15:52.667209 DEBUG OG cancel pending id 99546452.```

**Comment by serzhiio** [comment]
If my understanding of this is correct, pending to cancel orders are still holding amount of deposit therefore they doesn't let bot send new order.
This problem also looks like connection latency problem, but my orders latency is 0.2-0.7ms.

**Comment by ctubio** [comment]
i dont see any problem in bitfinex here, cancel pending id is a normal debug message of canceled orders not yet working

**Comment by b-seite** [comment]
Hi Carles, 

i agree with serzhiio that there is still a Problem with Bitfinex. 
I also have lots of unconcancelled orders after a couple of Minutes, see Image below. `Cxl` is not activated but i don't want to wait every 5 minutes to trade again.
![bildschirmfoto 2017-11-07 um 21 57 34](https://user-images.githubusercontent.com/540850/32517578-228efa7c-c407-11e7-9d6d-023fd578e0ab.png)

and with `--debug-orders` on there are some lines looking weird to me. 
![bildschirmfoto 2017-11-07 um 21 35 33](https://user-images.githubusercontent.com/540850/32517648-59c2ede6-c407-11e7-8b2a-b7ea94b1fdb4.png)

what i see are saves, sends and replies with missing exchangeID and lots of cancel pending...

Do you have any ideas?

**Comment by serzhiio** [comment]
b-siete, try this part of code for OG.h
```
      static void cancelOrder(string k) {
        ogMutex.lock();
        if (allOrders.find(k) == allOrders.end()) {
          ogMutex.unlock();
          //updateOrderState(mOrder(k, mORS::Cancelled));
          allOrdersDelete(k,"");
          if (argDebugOrders) FN::log("DEBUG", string("OG cancel unknown id ") + k);
          return;
        }
        if (!gW->cancelByLocalIds and allOrders[k].exchangeId == "") {
          toCancel.push_back(k);
          ogMutex.unlock();
          if (argDebugOrders) FN::log("DEBUG", string("OG cancel pending id ") + k);
          return;
        }
        mOrder o = allOrders[k];
        ogMutex.unlock();
        if (argDebugOrders) FN::log("DEBUG", string("OG cancel ") + (o.side == mSide::Bid ? "BID id " : "ASK id ") + o.orderId + "::" + o.exchangeId);
        gW->cancel(o.orderId, o.exchangeId, o.side, o.time);
      };
```

**Comment by b-seite** [comment]
Cool thank you.

That helps a lot :)

**Comment by ctubio** [comment]
im not able to reproduce this yet, but donno will keep retrying stuff

**Comment by ctubio** [comment]
the cancel function is fine, orders are accumulated without id because other functions (see net commit while crossing fingers)

**Comment by ctubio** [comment]
see now the openOrders/60sec :rocket:
