### ISSUE TITLE
Signal 11 Segmentation fault (Three-Headed Monkey found).

### ISSUE THREAD

**Issue by cymru2000** [ctubio/Krypto-trading-bot#375]
Evening, 

After update, getting another three-headed monkey, same system which reported #371

22:19:15.579172 Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x1a)[0x55fad6aa176a]
./app/server/K(_ZN1K2EV3wtfEi+0x41e)[0x55fad6aa6f3e]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030)[0x7f0cb06d3030]
./app/server/K(_ZN3uWS5GroupILb0EE9broadcastEPKcmNS_6OpCodeE+0x50)[0x55fad6ae23a0]
./app/server/K(_ZN1K3kxxEPN3uWS5GroupILb0EEE+0x2a0)[0x55fad6b06490]
./app/server/K(+0x1c1544)[0x55fad6b06544]
./app/server/K(+0x50904f)[0x55fad6e4e04f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7f0cb0a46494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f0cb0788aff]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by ctubio** [comment]
sorry missed to mutex a broadcast function :( wil fix soOn''
