### ISSUE TITLE
WS error connecting to GDAX

### ISSUE THREAD

**Issue by Grayjack64** [ctubio/Krypto-trading-bot#377]
Everything had been running fairly stable for the last week or so but after I updated to the latest build using 'make latest' I continually get "GW COINBASE WS Error, reconnecting in 10s'. It shows a successful logon to the exchange but this error seems to be blocking it. I have tried a new API Key as well but that did nothing. Any ideas? thanks

**Comment by ctubio** [comment]
that seems because https://github.com/ctubio/Krypto-trading-bot/issues/372  see also https://github.com/ctubio/Krypto-trading-bot/issues/368, you will need to remove `API_WS_ENDPOINT`  and `--ws` from your config file

**Comment by ctubio** [comment]
that seems because https://github.com/ctubio/Krypto-trading-bot/issues/372  see also https://github.com/ctubio/Krypto-trading-bot/issues/368, you will need to remove `API_WS_ENDPOINT`  and `--ws` from your config file
