### ISSUE TITLE
(Little improvement) Saving ewma trend on reboot

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#378]
Hi Carles,

It seems that ewma trend is not saved on reboot like stdev or the other ewma!

Maybe I'm wrong but it seems that it needs a few minutes before appearing :)

I think it would be easy to save them as well in the db.

Have a nice evening,
Camille

**Comment by donaldforest** [comment]
Good idea! I was also surprised with that.

**Comment by ctubio** [comment]
thanks for notice this''
