### ISSUE TITLE
Trading problems with % switched on

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#379]
Hi All,

i notice strange behaviour from my GDAX BTC/EUR bot. In brief, it did not trade, only very few trades a day. And it burns my funds slowly...

![bildschirmfoto 2017-11-08 um 22 07 33](https://user-images.githubusercontent.com/540850/32574588-f354289c-c4d1-11e7-9e2f-3962bed62424.png)

The strange thing its, that with `--debug-orders` you see lots of orders. On the screenshot you see that there are many orders per minute but no one shows up on GDAX and in the order book.
The bot is connected, no errors, no active protection, pingWidth on minimum but no quotes in the book. 
I am running with latest commit on aws with a latency of 10-20ms (if there are quotes)

I know, perhaps its not an error or a technical issue, perhaps the problem i inbetween my ears but 
has anybody an idea before my funds went zero?

**Comment by b-seite** [comment]
ok i was too quick with that Issue. i found the error: when i switch off %  the bot trades like hell...

so there must be something with the % calculation. In the past i had no Problems with that...

**Comment by ctubio** [comment]
i always have % enabled but didn't experiencied this yet, your problem may be caused by something else (not sure what yet)

**Comment by ctubio** [comment]
can you please see if https://github.com/ctubio/Krypto-trading-bot/commit/b8605bb214929e0c253007cc2cda058863f23a34 helps?
thanks''

**Comment by b-seite** [comment]
hi Carles,

many thanks for the update on the QE. But it did help me that much i hoped. But i have new information: When i switch on `Boomerang `or `AK47`, in the UI `SellPing` goes to zero or freezes to an old value. And when i then activate `Short/LongPingAggressive` then the bot stops selling.
I looked inside the code but i did not find any error

**Comment by ctubio** [comment]
aaand to keep discarting.. non-placing-orders bug ony happens to you on gdax? or also in others?

**Comment by b-seite** [comment]
It seems to me that it´s a global problem. 
But on my bitfinex bots it´s hard to see because of some other strange things: 

![bildschirmfoto 2017-11-09 um 15 40 27](https://user-images.githubusercontent.com/540850/32610897-6b0791de-c564-11e7-9d9d-64fac6447248.png)

![bildschirmfoto 2017-11-09 um 15 40 51](https://user-images.githubusercontent.com/540850/32610898-6c4c1088-c564-11e7-809e-75fe88f2329b.png)
but that will be part of another topic

**Comment by b-seite** [comment]
Hej Carles,

I‘ll close this topic. Think that the error is gone. Perhaps i will reopen it in the Future if the error comes back. 

Again, many thanks for all the lines of code.
