### ISSUE TITLE
Cost basis based logging

### ISSUE THREAD

**Issue by AZm1n** [ctubio/Krypto-trading-bot#38]
Hi all,
is there any logging available or any useful query against the DB that can show the cost basis based on FIFO?
the reason is obviously for tax reporting purposes, I understand GDAX which i trade will provide something but I'd like to be ready from my side just in case.

**Comment by ctubio** [comment]
nobody cares about taxes here. if you want to read the database you can use tools similar to http://sqlitebrowser.org/
