### ISSUE TITLE
HitBTC. Fresh installation. BQX/ETH. Unable to calculate quote, missing fair value.

### ISSUE THREAD

**Issue by zzayale** [ctubio/Krypto-trading-bot#380]
$ ./K.sh 
K build x86_64-linux-gnu 2017-11-09 04:22:59.
K version 0day.
08:59:44.491593 DB /data/db/K.1.BQX.ETH.db loaded OK.
08:59:44.491984 UI ready over HTTPS on external port 3000.
08:59:44.492230 DB loaded Quoting Parameters OK.
08:59:44.492290 DB loaded 0 historical Trades.
08:59:44.493794 DB loaded 0 STDEV Periods.
08:59:44.493921 DB loaded EWMA Long = 0.000000.
08:59:44.493926 DB loaded EWMA Medium = 0.000000.
08:59:44.493929 DB loaded EWMA Short = 0.000000.
08:59:44.494016 DB loaded TBP = 0.09394279 BQX.
08:59:44.730378 GW HITBTC allows client IP.
08:59:44.730418 GW HITBTC: 
- autoBot: no
- symbols: BQXETH
- minTick: 0.00000100
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000.
08:59:47.083152 GW HITBTC WS Error, reconnecting in 10s..
08:59:47.083168 QE Warrrrning: Unable to calculate quote, missing fair value.
08:59:47.099394 UI 1 currently connected, last connection was from ::1.
08:59:47.318336 QE Warrrrning: Unable to calculate quote, missing fair value.
08:59:48.318960 QE Warrrrning: Unable to calculate quote, missing fair value.
08:59:49.319058 QE Warrrrning: Unable to calculate quote, missing fair value.
08:59:50.320128 QE Warrrrning: Unable to calculate quote, missing fair value.
08:59:51.321183 QE Warrrrning: Unable to calculate quote, missing fair value.
08:59:52.322102 QE Warrrrning: Unable to calculate quote, missing fair value.
08:59:53.322217 QE Warrrrning: Unable to calculate quote, missing fair value.
08:59:54.323255 QE Warrrrning: Unable to calculate quote, missing fair value.
08:59:55.323861 QE Warrrrning: Unable to calculate quote, missing fair value.
08:59:56.318939 GW HITBTC WS Error, reconnecting in 10s..
08:59:56.324025 QE Warrrrning: Unable to calculate quote, missing fair value.
^C
08:59:57.167236 Excellent decision! No one has ever pair-programmed with Chuck Norris and lived to tell about it.
08:59:57.167265 GW HITBTC Attempting to cancel all open orders, please wait..
08:59:57.376853 GW HITBTC cancell all open orders OK.
08:59:57.376877 UI 0 currently connected, last connection was from ::1.
08:59:57.376931 K exit code 0.

Help me please. Thank you.

**Comment by ctubio** [comment]
sorry you may have an old config file even if installation is fresh?

please see if https://github.com/ctubio/Krypto-trading-bot/issues/377 helps

**Comment by zzayale** [comment]
Does not work. :(

grep -v "#" K.sh 
OPTIONAL_ARGUMENTS="--colors --naked"
UI_USERNAME=NULL
UI_PASSWORD=NULL
UI_OPENPORT=3000
API_EXCHANGE=HITBTC
API_CURRENCY=BQX/ETH
API_ORDERS_DESTINATION=REAL
API_KEY=<my_key>
API_SECRET=<my_secret>
API_PASSPHRASE=NULL
API_USERNAME=NULL
API_HTTP_ENDPOINT=https://api.hitbtc.com/api/2
**API_WSS_ENDPOINT=NULL**
until ./app/server/K                                    \
    --port       $UI_OPENPORT                           \
    --user       $UI_USERNAME                           \
    --pass       $UI_PASSWORD                           \
    --exchange   $API_EXCHANGE                          \
    --currency   $API_CURRENCY                          \
    --target     $API_ORDERS_DESTINATION                \
    --apikey     $API_KEY                               \
    --secret     $API_SECRET                            \
    --passphrase $API_PASSPHRASE                        \
    --username   $API_USERNAME                          \
    --http       $API_HTTP_ENDPOINT                     \
    --wss        $API_WSS_ENDPOINT                      \

**Comment by ctubio** [comment]
because hitbtc requires API_WSS_ENDPOINT as not NULL:
```
#  █ API_WSS_ENDPOINT                                   .
#  ██ - Allows one of the following urls (see the website of the exchange).
#  ██ - Almost all exchanges must have API_WSS_ENDPOINT, only KORBIT exchange can be NULL.
```
