### ISSUE TITLE
Sell orders accumulating Bitfinex

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#381]
Hi Carles,

I found a problem, sell orders tend to accumulate on the exchange and are not reported on the web UI.

I don't use AK47 and here is what I have.
It results that all of my assets can be sold when I wanted to sell only a fraction.
Also, some orders (buy or sell) do not appear on the web ui, I checked on the exchange and I've made trades that are not reported by the bot.

I guess it's the same issue but as the capital to buy is usually limited, I don't see 5 buy orders. :)

![capture d ecran 2017-11-09 a 19 01 22](https://user-images.githubusercontent.com/6861590/32621731-06c386a2-c581-11e7-8b0e-2d86cbe7e678.png)

You can see that it all happened after a restartall (that happened at 19h precise) so I imagine it only happens when the bot starts.

**Comment by Camille92** [comment]
Update: It's not only on reboot :s

**Comment by Camille92** [comment]
Update 2: And it's also for buy orders!

For information, I'm using pdiv = 0 and APR size if it changes something :/

**Comment by serzhiio** [comment]
Same situation for me. Tons of orders with no fetch in UI.

**Comment by b-seite** [comment]
hey Camille,

think that's the same problem we discussed here: #374 
maybe the proposed fix helps you too. (but i think that's just a rough workaround)

**Comment by ctubio** [comment]
bitfinex changed api notifications (`ou` is now `on`); will be fixed on next commit

**Comment by ctubio** [comment]
![giphy 2](https://user-images.githubusercontent.com/1634027/32641898-dac2a70e-c5d0-11e7-8f49-9b254063b35f.gif)
