### ISSUE TITLE
Negative width -> what are the consequences ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#383]
Hi Carles,

Just a question, I'm afraid of the consequences of the negative width that we see often occurring on trading.

Does it have an impact on the ewma / ewma trend / stdev / quoting?

Because it seems so (but I can't say for sure).

Please tell me more about it!

And if it has consequences, then it's necessary to find a fix :)
![capture d ecran 2017-11-10 a 13 29 13](https://user-images.githubusercontent.com/6861590/32658642-43113024-c61b-11e7-8851-2a1982110362.png)

**Comment by ctubio** [comment]
in what exchange you see overlapping market sides?

if is a UI glitch is harmless, but if is a api bug then all fail

**Comment by b-seite** [comment]
Hi Carles,
i´ve seen it on Bitfinex with ETH/USD and BCH/BTC when the bots run more than an Hour. 
(atm. i do a hourly restart because of that but i have seen it yesterday on both bots)
On GDAX i did not notice that problem.

**Comment by Camille92** [comment]
Hey to answer your questions,

It's on Bitfinex and on any market as soon you have big volatility.

I think it's not a web UI glitch because I was comparing the ewma in Tradingview and the bot and it differed when the glitch happened. :/

I think you could see the bug by opening an instance in bitfi where when you have big volatility in a few minutes / 1h you should see some!

**Comment by ctubio** [comment]
ima leave this here for laterz
```
bitfinex algorithm to create and keep a book instance updated:
1 subscribe to channel
2 receive the book snapshot and create your in-memory book structure
3 when count > 0 then you have to add or update the price level
3.1 if amount > 0 then add/update bids
3.2 if amount < 0 then add/update asks
4 when count = 0 then you have to delete the price level.
4.1 if amount = 1 then remove from bids
4.2 if amount = -1 then remove from asks
```

**Comment by Camille92** [comment]
Works well!
Thank you for the time carles!

**Comment by Camille92** [comment]
Hi Carles,

Sadly the problem has not been fixed with the latest update. After letting it run for the night, I've found it.

Do you think we could include a protection to drop the book or restart the bot if a negative width happens?

Best,
Camille

**Comment by ctubio** [comment]
note that negative width means zombie market levels, that become negative when the market price moves above/below (that means we should try to avoid them from the root, not just when are clearly visible cos sides overlap).

**Comment by Camille92** [comment]
That seems to be a good option to ask for the book again.

As it seems to be a problem happening with high volatility it could be that it's just too much information coming at the same time or created and canceled before the bot has the time to manage the information.

Why not request a snapshot each time width is negative + after a certain amount of time?

Is there is a way to ask for a certain order?

I find the options offered by Bitfinex a bit slim!

**Comment by ctubio** [comment]
request a snapshot when the width is negative is bad because the solves the problem too late. the problem (zombie market levels) exists since long time before the sides clearly overlap.

**Comment by Camille92** [comment]
Yep, but I have no idea on how to see if an order is true or fake if it doesn't cross.

And it doesn't have a very negative consequence that there is a fake order somewhere in the book.

I agree it's not perfect, but I feel that it's better than the current state and If you have an idea for a better solution I'm obviously in for that :)

**Comment by ctubio** [comment]
ok soo.. xD:
plan a rerereview
~~plan b snap every now and then~~
plan b snap on negative width

thanks for the opinionated replies'¡!

**Comment by Camille92** [comment]
![image](https://user-images.githubusercontent.com/6861590/32726814-9dbe0748-c87a-11e7-9455-37f46b4f66a8.png)

**Comment by ctubio** [comment]
![bnq1gi7iyaa9nzn](https://user-images.githubusercontent.com/1634027/32727147-c39cca52-c87b-11e7-8a93-6c09fbbef575.jpg)

**Comment by Camille92** [comment]
Fixed with some of the latest updates!

Well done :)
