### ISSUE TITLE
Pings stay for way too long...

### ISSUE THREAD

**Issue by kjullien** [ctubio/Krypto-trading-bot#384]
Hello,
First let me say that I am a complete noob in finance and trading, but have some understanding of algebra and programming, so please forgive my misuse of different terms and try to indulge my ignorance...

Here is what I would like to understand :
I mainly use boomerang safety, which places multiple pings and tries to match a pong close to the millisecond. So far so good.
My problem is that over time, the bot will accumulate some pings that wont get ponged because it might buy at 6.5K and then the price might drop to 6.4-6.3K for more than a day. So how do I tell the bot that it is okay to "let go" of a ping after a while if no matching pong can be found ?

At first I thought the "cxl" option would do that, clean my unresolved pings every 5 minutes, but that clearly does something else that I do not understand...

Then I tried to entirely disable EMWA (as recommended in #111) and that seems to solve the problem of the bot waiting for all the pings to be resolved. Now it continues to invest even with the hanging pings, so I continue to generate profit, but the pings still wont go away. Also I'm not sure I feel comfortable having no protection, but an other problem I had with EMWA was that after a while it would almost never diverge from 0.01 width... (I used 50 as period value for emwa)

Here is a screenshot of my current settings for reference :
![Settings Screenshot](https://i.imgur.com/tcQut3S.png)

I'm trying to make it work with as many trades for a given time period as possible. (I want to hear a never ending chaching you know)

Any help would be greatly appreciated.

PS: using GDAX

**Comment by ctubio** [comment]
morning''
see `Kmemory`option, you may want to use some negative value
