### ISSUE TITLE
crash bitfinex eth/usd

### ISSUE THREAD

**Issue by decazuk** [ctubio/Krypto-trading-bot#385]
Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x1a)[0x5576886470aa]
./app/server/K(_ZN1K2EV3wtfEi+0x41e)[0x55768864c6de]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7fb66043d4b0]

**Comment by ctubio** [comment]
sorry closing cos to little info to debug nothing
