### ISSUE TITLE
Docker container crashing

### ISSUE THREAD

**Issue by Ganayan** [ctubio/Krypto-trading-bot#389]
When first starting up the Docker container, it crashes with the log saying:

./K.sh: 3: ./K.sh: --exchange: not found
./K.sh: 12: ./K.sh: Syntax error: "do" unexpected

I'm using Docker 17.09.0-ce, build afdb6d4 on MacOS 10.13.1 (17B48)

**Comment by ctubio** [comment]
sorry yesterday broke it, will fix laterz ina bit
