### ISSUE TITLE
MANUAL Update

### ISSUE THREAD

**Issue by kjullien** [ctubio/Krypto-trading-bot#391]
Hello,

I was wondering if it could be possible to make the MANUAL.md a wiki page so as that it can be community edited ?
Not to be mean but the current documentation is quite unclear to cryptotrading noobs like me and it would be great if we could make it more understandable, personally I could edit stuff as I get more understanding about the bot.

For instance the concept of EMWA is not at all explained and it took me quite some time to understand even the most basic concept such as this one...

Here is an example of a schema that I did real fast to explain the main concept of the bot in 10 seconds :
![screen](https://i.imgur.com/3dpYWsJ.png)

Stuff like that would've been so useful to me when I found out about the project..

So can we have a wiki please ?

**Comment by ctubio** [comment]
thanks for your ideas'¡ the MANUAL.md already allows community edition, just edit the file (see https://help.github.com/articles/editing-files-in-another-user-s-repository/)

**Comment by ctubio** [comment]
is not a wiki but a markdown file since is not a wiki since https://github.com/ctubio/Krypto-trading-bot/commit/6c3b50ebe4aa0fa825bf690e2cd42a35039fe57c
