### ISSUE TITLE
HitBTC  ossie

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#392]
This morning i've noticed a lot of buy orders on HitBTC and no active orders visible in UI, connection persists. Looks like btc connection bug, a've manually deleted hitbtc orders, but now bot just dont send any. What's a problem?

**Comment by CarlitoGrey** [comment]
Looks like HitBTC might be having some issues at their end this morning.  I'm seeing lots of 503's in the log.

**Comment by ctubio** [comment]
maybe hitbtc messing with the new server
