### ISSUE TITLE
Do I need click XMR miner: [ START ] button for --free-version?

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#393]
Hello!
Just want try --free-version with XMR miner. In manual: "market levels will be all visible and usable but slowdown a few milliseconds with a XMR mining calculation of 1 hash". But in my case I can click [ START ] and make 20-40 hashes per second. In this case bot still continue work with delay? Is no sense click  [ START ] to speed up process of XMR mining?
PS I am not greedy, just want to get to the truth.

**Comment by ctubio** [comment]
there are 2 miners, one in the UI and one in the server.

--free-version runs the miner at the server side and slowsdown market levels

click on the [START] runs the miner at UI side and does not slow nothing but your own web browser tabs.

one miner have nothing to do with the other miner.

you cannot click on the server miner.

you cannot run the UI miner with --free-version.

**Comment by donaldforest** [comment]
UI miner with [START] button - is just like donation? It dosent unlock all / any features?

**Comment by ctubio** [comment]
yes exactly, [START] buttons has no benefit for the user, it only has benefits for the dev of the bot

--free-version has benefits for both i hope, dev and users

**Comment by donaldforest** [comment]
Nevertheless, I would like to make it work for you.
