### ISSUE TITLE
GW POLONIEX Error {"error":"Not enough BCH."}.

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#394]
Hello!
Is bot cacl funds amount on own side to make orders or try brute-force exchange API? I mean, this error in ./K,sh run logs:
`GW POLONIEX Error {"error":"Not enough BCH."}.`
This error - normal for trade process (for example, maybe i set incorrect trade settings and bot try buy to much..) or bot have troubles with some trade wallet logic?

**Comment by ctubio** [comment]
wallet logic is fine but bot has troubles with poloniex api because i hate poloniex and nobody wanted to support the development on poloniex integration yet, so im not loosing my time in a exchange that nobody cares yet

**Comment by donaldforest** [comment]
In any case poloniex have smaller fees for trade \ wallet than bitfinex.
Maybe I can fix and test it for community and Pull Request with fix??!

**Comment by ctubio** [comment]
the exchange integrations is the only code not available in github, so pull request are not possible

only the quoting engine and the ui allows pull request
