### ISSUE TITLE
Buying unlock questions

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#395]
Hello!
1) Can I buy unlock and get some good strategy settings or recommendations?
2) If I buy unlock and want to change server, I lost this unlock? I mean, how to transfer licence from different installs?
3) Do you sell strategies/settings?
4) Updates included to unlocked bot with pay to unlock?

Thanks!

**Comment by ctubio** [comment]
for strategy hints consider to join the IRC channel

license is based on the API KEY of your exchange, as long as you have the same api key you can reinstall in all computers you need. also upgrade all times you need cos your api key does not change after an upgrade.

i do not sell strategies but maybe somebody on IRC does

**Comment by ctubio** [comment]
thanks for your questions, will try to add the answers somehow to the README soOn'' :dancer:

**Comment by donaldforest** [comment]
1) Can I change API after buying licence?
Some troubles can be with exchanges and some exchanges resets APIs with some period..
2) Can I get a discount?

**Comment by ctubio** [comment]
if you collaborate to the project you can get unlimited free licenses for life, just collaborate and let me know the bots you wanna unlock on irc anytime
