### ISSUE TITLE
Bitfinex: QE Warrrrning: Unable to calculate TBP, missing market data..

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#396]
Bitfinex logs:
14:26:42.338065 QE Warrrrning: Unable to calculate TBP, missing market data..
14:27:12.681546 QE Warrrrning: Unable to calculate TBP, missing market data..
14:28:12.690655 QE Warrrrning: Unable to calculate TBP, missing market data..
14:29:12.701864 QE Warrrrning: Unable to calculate TBP, missing market data..

**Comment by Camille92** [comment]
Which version are you running on?

When I have some issues I update my system + fresh install everything and some cases it works again.

Was it working before?

Please give us some more info, I can't really help with your description.

**Comment by donaldforest** [comment]
K build x86_64-linux-gnu 2017-11-16 02:52:58.

Same for HITBTC

```
16:45:10.444698 QE Warrrrning: Unable to calculate quote, missing fair value.
16:45:10.444805 QE Warrrrning: Unable to calculate quote, missing fair value.
16:45:11.104562 GW HITBTC WS Streaming book levels and orders.
16:45:11.444382 QE Warrrrning: Unable to calculate quote, missing fair value.
16:45:40.326804 UI authorization success from 78.140.174.254.
16:45:41.015850 UI authorization success from 78.140.174.254.
16:45:46.078056 UI 1 currently connected, last connection was from 78.140.174.254.
16:46:02.325955 GW HITBTC Quoting state changed to CONNECTED.
16:46:13.423515 QE Warrrrning: Unable to calculate TBP, missing market data..
^C
16:46:51.901062 Excellent decision! The class object inherits from Chuck Norris
16:46:51.901103 GW HITBTC Quoting state changed to DISCONNECTED.
16:46:51.901168 GW HITBTC Attempting to cancel all open orders, please wait..
16:46:52.631983 GW HITBTC cancell all open orders OK.
16:46:52.632022 UI 0 currently connected, last connection was from 78.140.174.254.
16:46:52.632080 K exit code 0.
```

domainse@s2104:~/K$ ./K.sh --version
K build x86_64-linux-gnu 2017-11-16 02:52:58.
domainse@s2104:~/K$

**Comment by donaldforest** [comment]
What command reinstall K-bot?

**Comment by Camille92** [comment]
"make reinstall" :)

**Comment by ctubio** [comment]
there is no problem, the message is ONLY displayed BEFORE the bot is connected to the exchange

**Comment by donaldforest** [comment]
Thanks. Fixed with funding this trade pair.
