### ISSUE TITLE
Bitfinex - Error: Unable to fetch data from BITFINEX symbol "btcusd".

### ISSUE THREAD

**Issue by blast1987** [ctubio/Krypto-trading-bot#397]
Hello,
i am getting this error with a working API from bitfinex and default parameters

> 16:19:41.146110 UI ready over HTTPS on external port 3000.
16:19:41.147247 QP Warrrrning: using default values for Quoting Parameters.
16:19:41.147556 DB loaded 0 historical Trades.
16:19:41.147933 DB loaded 0 STDEV Periods.
16:19:41.148152 DB loaded EWMA Long = 0.000000.
16:19:41.148222 DB loaded EWMA Medium = 0.000000.
16:19:41.148262 DB loaded EWMA Short = 0.000000.
16:19:41.148461 DB loaded TBP = 0.00000000 BTC.
16:19:43.848762 CF Errrror: Unable to fetch data from BITFINEX symbol "btcusd".

My config:

> OPTIONAL_ARGUMENTS="--naked --autobot --free-version"
API_EXCHANGE=BITFINEX
API_CURRENCY=BTC/USD
API_HTTP_ENDPOINT=https://api.bitfinex.com/api/2
API_WSS_ENDPOINT=wss://api.bitfinex.com/ws/2

Thanks

**Comment by ctubio** [comment]
this means your computer had no access to https://api.bitfinex.com/v1/symbols_details or https://api.bitfinex.com/v1/symbols_details was not online at that time

after verify that `curl https://api.bitfinex.com/v1/symbols_details` works from this computer, simply try again, cos there is nothing to be fixed, looks like a connectivity problem while initialy fetching https://api.bitfinex.com/v1/symbols_details
