### ISSUE TITLE
Can owner of bot recommend exchange service which uses by yourself?!

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#398]
Hello!
I mean, can You please recommend exchange service which work without freeze and wallet errors?
I try Poloniex (wallet errors,), Bitfinex (Not best at all), HitBTC (Freeze after 4-5 min of trade)
Maybe this troubles is connected with --free-version param?!
Thanks.

**Comment by ctubio** [comment]
paste some logs if you want to report bugs, it runs for months without crash if you dont have a segfault commit xD

if you want to get general information consider to use the irc channel, im used to only keep open issues related about documented bugs or explained improvements only

**Comment by donaldforest** [comment]
I mark freeze place. You can see about 3 min of nothing, then another fast activity:

`18:38:53.320229 DEBUG QE quoteA 4 4 {"ask":{"price":0.13197311,"size":0.0350308715930844},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:38:53.320243 DEBUG QE quoteB 4 4 {"ask":{"price":0.13197311,"size":0.0350308715930844},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:38:53.320256 DEBUG QE quoteC 4 4 {"ask":{"price":0.13197311,"size":0.0350308715930844},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:38:53.320270 DEBUG QE quoteD 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:38:53.320284 DEBUG QE quoteE 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:38:53.320297 DEBUG QE quoteF 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:38:53.320309 DEBUG QE quoteG 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:38:53.320321 DEBUG QE quoteH 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:38:53.320335 DEBUG QE quoteI 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:38:53.320349 DEBUG QE quoteJ 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:38:53.320361 DEBUG QE quoteK 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:38:53.320374 DEBUG QE quoteL 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.03503087}}.
18:38:53.320387 DEBUG QE quote! 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.03503087}}.
18:38:53.320407 DEBUG QE totals toAsk:0.388500 toBid:0.111941 min:0.001000.
18:38:53.320417 DEBUG OG cancel BID id NLl1u91vAMxdD04A::6528217801.
18:38:53.320455 DEBUG OG  save  BID id 7LyXcxPDk3Q6pthL:: [0]: 0.035031 BCH at price 0.131315 BTC.
18:38:53.320463 DEBUG OG memory 2/1.
18:38:53.320496 DEBUG EV PG ogOrder mOrder {"computationalLatency":0,"exchange":1,"exchangeId":"","isPong":true,"lastQuantity":0.0,"orderId":"7LyXcxPDk3Q6pthL","orderStatus":0,"pair":{"base":"BCH","quote":"BTC"},"preferPostOnly":true,"price":0.131315,"quantity":0.03503087,"side":0,"time":1510857533320,"timeInForce":2,"type":0}.
18:38:53.320519 DEBUG OG  send  BID id 7LyXcxPDk3Q6pthL: 0.035031 BCH at price 0.131315 BTC.
-----------------------
18:41:26.487098 DEBUG EV GW tCalcs timer.
18:41:26.489609 DEBUG QE quote? 4 4 {"ask":{"price":0.13197311,"size":0.0350308715930844},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:26.489632 DEBUG QE quoteA 4 4 {"ask":{"price":0.13197311,"size":0.0350308715930844},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:26.489646 DEBUG QE quoteB 4 4 {"ask":{"price":0.13197311,"size":0.0350308715930844},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:26.489662 DEBUG QE quoteC 4 4 {"ask":{"price":0.13197311,"size":0.0350308715930844},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:26.489676 DEBUG QE quoteD 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:26.489689 DEBUG QE quoteE 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:26.489702 DEBUG QE quoteF 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:26.489716 DEBUG QE quoteG 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:26.489730 DEBUG QE quoteH 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:41:26.489744 DEBUG QE quoteI 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:41:26.489758 DEBUG QE quoteJ 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:41:26.489784 DEBUG QE quoteK 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:41:26.489803 DEBUG QE quoteL 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.03503087}}.
18:41:26.489818 DEBUG QE quote! 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.03503087}}.
18:41:26.489838 DEBUG QE totals toAsk:0.388500 toBid:0.111941 min:0.001000.
18:41:26.489851 DEBUG EV GW tWallet timer.
18:41:27.315281 DEBUG EV PG evDataWallet mWallet {"amount":0.3885,"currency":"BCH","held":0.0}.
18:41:27.319734 DEBUG EV PG evDataWallet mWallet {"amount":0.010135719,"currency":"BTC","held":0.004600645}.
18:41:27.319834 DEBUG EV GW tDelay timer.
18:41:27.320006 DEBUG EV GW tCancel timer.
18:41:27.320196 DEBUG EV MG evDataLevels.
18:41:27.320216 DEBUG EV QE mgLevels.
18:41:27.320239 DEBUG QE quote? 4 4 {"ask":{"price":0.13197311,"size":0.0350308715930844},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:27.320267 DEBUG QE quoteA 4 4 {"ask":{"price":0.13197311,"size":0.0350308715930844},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:27.320283 DEBUG QE quoteB 4 4 {"ask":{"price":0.13197311,"size":0.0350308715930844},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:27.320298 DEBUG QE quoteC 4 4 {"ask":{"price":0.13197311,"size":0.0350308715930844},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:27.320312 DEBUG QE quoteD 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:27.320338 DEBUG QE quoteE 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:27.320352 DEBUG QE quoteF 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:27.320366 DEBUG QE quoteG 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.13131489,"size":0.0350308715930844}}.
18:41:27.320382 DEBUG QE quoteH 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:41:27.320396 DEBUG QE quoteI 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:41:27.320421 DEBUG QE quoteJ 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:41:27.320435 DEBUG QE quoteK 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.0350308715930844}}.
18:41:27.320448 DEBUG QE quoteL 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.03503087}}.
18:41:27.320461 DEBUG QE quote! 4 5 {"ask":{"price":0.0,"size":0.0},"bid":{"price":0.131315,"size":0.03503087}}.
18:41:27.320481 DEBUG QE totals toAsk:0.388500 toBid:0.111941 min:0.001000.`

**Comment by donaldforest** [comment]
Finally work with delayApi = 30 ! I scared to stop to change mode to free-version!
In any case your bot is the best from those which I seen before! I see a lot!.. :+1: 
Thanks!

**Comment by donaldforest** [comment]
Another log to freeze with HitBTC (last line is a last line of live):

`20:50:42.023057 DEBUG EV GW tCalcs timer.
20:50:42.023109 DEBUG EV QE mgEwmaQuoteProtection.
20:50:42.023116 DEBUG EV QE mgEwmaSMUProtection.
20:50:42.023122 DEBUG EV PG mgTargetPosition.
20:50:42.023127 DEBUG EV QE pgTargetBasePosition.
20:50:42.026810 TBP 48% = 0.24067549 BCH.
20:50:42.311049 DEBUG EV MG evDataLevels.
20:50:42.311106 DEBUG EV PG evDataWallet mWallet {"amount":0.0,"currency":"","held":0.0}.
20:50:42.311166 DEBUG EV QE mgLevels.
20:50:42.311260 DEBUG EV MG evDataLevels.
20:50:42.311282 DEBUG EV QE mgLevels.
20:50:42.318638 DEBUG EV MG evDataLevels.
20:50:42.318652 DEBUG EV QE mgLevels.
20:50:42.364740 DEBUG EV MG evDataLevels.
20:50:42.364771 DEBUG EV QE mgLevels.
20:50:42.387978 DEBUG EV MG evDataLevels.
20:50:42.387992 DEBUG EV QE mgLevels.
20:50:42.388027 DEBUG EV MG evDataTrade.
20:50:42.388307 DEBUG EV MG evDataLevels.
20:50:42.388319 DEBUG EV QE mgLevels.
20:50:42.388364 DEBUG EV MG evDataLevels.
20:50:42.388370 DEBUG EV QE mgLevels.
20:50:42.388474 DEBUG EV MG evDataLevels.
20:50:42.388482 DEBUG EV QE mgLevels.
20:50:42.388588 DEBUG EV MG evDataLevels.
20:50:42.388595 DEBUG EV QE mgLevels.
20:50:42.408669 DEBUG EV MG evDataLevels.
20:50:42.408701 DEBUG EV PG evDataWallet mWallet {"amount":0.0,"currency":"","held":0.0}.
20:50:42.408736 DEBUG EV QE mgLevels.
20:50:42.423063 DEBUG EV MG evDataLevels.
20:50:42.423084 DEBUG EV PG evDataWallet mWallet {"amount":0.0,"currency":"","held":0.0}.
20:50:42.423130 DEBUG EV QE mgLevels.
20:50:42.427534 DEBUG EV MG evDataLevels.
20:50:42.427547 DEBUG EV QE mgLevels.
20:50:42.443806 DEBUG EV MG evDataLevels.
20:50:42.443824 DEBUG EV QE mgLevels.
20:50:42.461742 DEBUG EV MG evDataLevels.
20:50:42.461758 DEBUG EV QE mgLevels.
20:50:42.473068 DEBUG EV MG evDataLevels.
20:50:42.473094 DEBUG EV QE mgLevels.
20:50:42.490741 DEBUG EV MG evDataLevels.
20:50:42.490754 DEBUG EV QE mgLevels.
20:50:42.513184 DEBUG EV MG evDataLevels.
20:50:42.513199 DEBUG EV QE mgLevels.
20:50:42.513305 DEBUG EV MG evDataLevels.
20:50:42.513312 DEBUG EV QE mgLevels.
20:50:42.525179 DEBUG EV MG evDataLevels.
20:50:42.525193 DEBUG EV QE mgLevels.
20:50:42.526929 DEBUG EV MG evDataLevels.
20:50:42.526943 DEBUG EV QE mgLevels.
20:50:42.622320 DEBUG EV MG evDataLevels.
20:50:42.622349 DEBUG EV QE mgLevels.
20:50:42.718653 DEBUG EV MG evDataLevels.
20:50:42.718687 DEBUG EV QE mgLevels.
20:50:42.815173 DEBUG EV MG evDataLevels.
20:50:42.815202 DEBUG EV QE mgLevels.
20:50:42.923573 DEBUG EV MG evDataLevels.
20:50:42.923613 DEBUG EV QE mgLevels.
20:50:43.023742 DEBUG EV GW tCalcs timer.
20:50:43.037012 DEBUG EV MG evDataLevels.
20:50:43.037027 DEBUG EV QE mgLevels.
20:50:43.120547 DEBUG EV MG evDataLevels.
20:50:43.120588 DEBUG EV QE mgLevels.
`

**Comment by donaldforest** [comment]
Maybe you have a params to run bot in one processor stream\thread mode?

**Comment by donaldforest** [comment]
On local virtual Ubuntu 16 with restricted hardware, bot works with same API correct.
On 2 x Intel(R) Xeon(R) CPU E5-2660 32GB dedicated server with Ububntu 16.04.1 try reinstall bot twice and it always freeze when work 2-5 minutes.
HM...

**Comment by ctubio** [comment]
i never experiencied freezes; not sure howto reproduce this; check your quoting paramteres
