### ISSUE TITLE
Kraken support

### ISSUE THREAD

**Issue by scarecr0w12** [ctubio/Krypto-trading-bot#399]
Any chance of having kraken added as a supported exchange. It allows for smaller trade sizes, and would be nice to be able to use for those of us who play around with less then 100$ worth of crypto

**Comment by ctubio** [comment]
maaaybe, lets link thiz with https://github.com/ctubio/Krypto-trading-bot/issues/291

thanks for the suggestion (may need to add some votes system for decide it xD if you ask me, currently i dont care much to add new exchanges, im still optimizing the base)

**Comment by davidalbertonogueira** [comment]
I support Kraken support.

**Comment by ctubio** [comment]
so as low priority, but already started.

thanks for your support to support Kraken support.

**Comment by josipbrcina** [comment]
Go Kraken!! That would be great!

**Comment by Basti922** [comment]
Yes

**Comment by MiningInMySleep** [comment]
Have BTC to put into this as soon as it's ready. Admittedly it's probably not going to happen until Kraken fixes their servers, but I can wait. If you need help testing anything, just let me know.

**Comment by Bomper** [comment]
Kraken is a joke these daus. I've written a robust Kraken library with timeouts, retries and fixes for many of their small issues, but their servers are so congested any connection times out 10+ times in a rows, which makes it Kraken unusable.

**Comment by Neo478** [comment]
@scarecr0w12 If you want to play with 100$ of cryptos, you can trade on crypto to crypto currencies on HitBtc

**Comment by MiningInMySleep** [comment]
They actually finished a really big upgrade to their trading engine. Maybe it's better now?

**Comment by ctubio** [comment]
seems coOl here now; lets try to continue'
