### ISSUE TITLE
Minimum hardware requirements?

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#400]
Hello!
Can You recommend please some minimal  hardware requirements for bot fast working?
Same question for using bot with free-mode?

**Comment by ctubio** [comment]
use the irc channel or the trollbox for questions

github issues are for bug or improments

**Comment by donaldforest** [comment]
But how about mining for free version?

**Comment by ctubio** [comment]
as bigger the cpu, faster it will mine; it doesnt have any minimum, it only uses 1 thread
