### ISSUE TITLE
Is some simulation mode for bot?

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#401]
I seen before 2 types of simulation trade bot modes:
1) Fast simulation with backfilled data from some exchange with needed trade pair. In this case bot download couple days of trade data to local DB and can test for some minutes trade strategy on this data with virtual depo. Then we count % of profit.
2) We can simulate trade with virtual depo in live exchange data mode.. This is more accuracy, but to slow process.

In first case we have 2 advantages:
a) We have a tool fast customize and compare strategy params with highest profit.
b) If strategy params make possible change in cli mode and get in cli result, we can run gradient (slow and big for float values) or genetic algorithm (good for this case) presets to search most accurate and best profit settings which can be various and unforeseen for some trade pairs and exchanges features.

Then when by case 1 with thousands simulations we found optimal settings we can test it for live test case 2 and then switch to real live mode.

Maybe this tools already exist? In case no, you can think about create something like this.. I can help with some genetic solutions. Whell that its already tons of realised on github!

**Comment by ctubio** [comment]
we have just NULL gateway currently
