### ISSUE TITLE
HitBTC - Completed trades aren't always recorded in Ping/Pong table

### ISSUE THREAD

**Issue by Zachar543** [ctubio/Krypto-trading-bot#405]
I'm seeing the occasional HitBTC trade being completed (according to HitBTC's trades page), but the Ping/Pong table does not display the trade. With the "audio?" option enabled, I do hear the sound for a new Ping or Pong, but the trade isn't always recorded.

This just started in the 2 days, and it appears that HitBTC may be having API issues (spikes of extremely high latency, gateway timeouts, etc.), so that may be a factor.

I updated to [the current newest commit](https://github.com/ctubio/Krypto-trading-bot/commit/52538b9178bf9b4cf9c00dc6ea7ead7ecd342281), but it didn't help.

Mode: Join/Top
Safety: Boomerang
Kmemory: 1
Pings in Memory: > 390

**Comment by ctubio** [comment]
history of trades accumulate orders of the same price.

that is, you will not see 2 rows in the table of trades with the same price.

that may be where you are missing your trades, because they are accumulated together based on same price.

look for the quantities, you will notice accumulated orders.

**Comment by Zachar543** [comment]
Thanks for responding. This appears to be better now (possibly due to a reinstall).

When this was happening, I checked for corresponding Pings/Pongs soon after I heard the sound, but I couldn't find any orders in the table that matched based on timePing/timePong (all were several minutes older), pxPing/pxPong prices, or any qtyPing/qtyPong that was anything other than my set bidSize/askSize, which is the min size on the exchange. It was almost as though they weren't recorded.

Since a reinstall seems to have fixed this along with several other things, feel free to leave this closed.
