### ISSUE TITLE
How to reset profits?

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#406]
Hello!
How to reset profits values to 0.0%?
I load my exchange manually this distort profits stats in UI.

**Comment by ctubio** [comment]
rm /data/db/*

**Comment by ctubio** [comment]
issues are to report bugs or to explain improvements, do your share your quesitons use the IRC channel

**Comment by donaldforest** [comment]
Oh, sorry!
What is nick in IRC channel have relation to K?
