### ISSUE TITLE
Zombie order

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#410]
After 20-30 hours of work one order appears and then always persists even when disconnected.
![zombie-order](https://user-images.githubusercontent.com/10449591/33013126-f72391a8-cdf3-11e7-9579-6e8c9ba477a0.jpg)

**Comment by ctubio** [comment]
noway with the latest mod, we do not accumulate orders. that was really an open order in the server and in the UI (you can see the server count in your screenshot as 0/1/0, so clearly it was not a zombie order but a working order in the UI and in the server..

what you mean by zombie?

**Comment by serzhiio** [comment]
I called it zombie because i've been seeing this order during all trade period and even after manual cancel it resurrected. And how can it be that when bot is disconnected order is in work furthermore there was no orders on exchange at that time?

**Comment by serzhiio** [comment]
Think we shpuld open this issue again so i have new proofs!
Look i have 2 orders at HitBTC and 3 active orders in the UI. When bot calculate wallet held values i see that this zombie order size counted in held amount.
![zombie-order-2](https://user-images.githubusercontent.com/10449591/33186763-3bc9ce84-d09d-11e7-872e-ecd4ef6ef32a.jpg)

**Comment by serzhiio** [comment]
And one more screenshot
![zombie-order-3](https://user-images.githubusercontent.com/10449591/33186882-5877ac3a-d09e-11e7-84d9-bd2debdd6c0c.jpg)
