### ISSUE TITLE
make client error

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#411]
Hello!
When I try recompile client side of K UI with **sudo make client**, I see error:

> make: *** No rule to make target 'node_modules/.bin/tsc', needed by 'client'.  Stop.

How to make client scripts?

**Comment by ctubio** [comment]
make sure `node_modules/.bin/tsc` exists, should be installed by `npm install`; your `npm install` if ever executed may had failed to fetch the dependency because of reasons

**Comment by ctubio** [comment]
usually is just `make bundle`
