### ISSUE TITLE
strange hang ups

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#412]
I dont know is it a UI only bug or it reflects on orders sending, but there is kind of hang ups during orders placement. No Ask/Bid status messages visible in this particular time, order list just blank. Look at the screenshot.
![orders-ui-bug](https://user-images.githubusercontent.com/10449591/33035892-c7b963bc-ce3d-11e7-9352-4dc3cb5a49c9.jpg)

**Comment by ctubio** [comment]
consider to show some logsi have no idea what is going on there

**Comment by serzhiio** [comment]
This i saw in HitBTC.
![bug-hitbtc-orders](https://user-images.githubusercontent.com/10449591/33036558-d4a71b44-ce3f-11e7-89d6-6e8effb3163b.jpg)
