### ISSUE TITLE
New UI tools

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#413]
Hello!
 I fork K https://github.com/donaldforest/Krypto-trading-bot and add some interface new tools.

1) For example, I always interested see in UI total amount of pair base currency and quote (Available + Held). Compiled example:
![info](https://user-images.githubusercontent.com/33358791/33059746-b2603914-cea6-11e7-8e9b-b1d27c84a13b.PNG)
https://image.prntscr.com/image/SX7UB6wORq6M9M9FBNQR6w.png

2) "Submit Order" fast features:
![submit_order_1](https://user-images.githubusercontent.com/33358791/33059774-cbc476c2-cea6-11e7-83ac-8a09e95a8d3b.png)
https://image.prntscr.com/image/HPie6UQIRluVlU-2pTodTw.png
I wanted to implement it, when I tried to copy and paste data manually!

3) Resizable columns in trades table. (Some browsers cut values)

If someone interested, you can request K owner add this to release.
If interested, I plan improve Manual with new images.

**Comment by ctubio** [comment]
feel free to make a pull request, i cannot merge from here
