### ISSUE TITLE
Question: K freezes?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#414]
Hi Carles,

I see some instances of the bot "freezing" after running for some time.

I can't connect to the bot and in the terminal, I get something like

> │ 09:56:01.217093 TBP 0% = 0.00000000 QTM.
> │ 09:56:44.709026 TBP 0% = 0.00000000 QTM.
> │ 09:56:46.817929 TBP 0% = 0.00000000 QTM.
> │ 09:56:46.847290 TBP 0% = 0.00000000 QTM.
> │ 09:56:51.023141 TBP 0% = 0.00000000 QTM.
> │ 09:56:52.001195 TBP 0% = 0.00000000 QTM.
> │ 09:57:01.468300 TBP 0% = 0.00000000 QTM.
> │ 09:58:09.641266 TBP 0% = 0.00000000 QTM.
> │ 09:59:17.371121 TBP 0% = 0.00000000 QTM.
> │ 10:00:25.425377 TBP 0% = 0.00000000 QTM.
> │ 10:01:14.872246 TBP 0% = 0.00000000 QTM.
> │ 10:01:36.006886 TBP 0% = 0.00000000 QTM.
> │ 10:01:47.751678 TBP 0% = 0.00000000 QTM.
> │ 10:01:47.800793 TBP 0% = 0.00000000 QTM.
> │ 10:01:50.958359 TBP 0% = 0.00000000 QTM.
> │ 10:02:45.876234 TBP 0% = 0.00000000 QTM.
> │ 10:02:49.592248 TBP 0% = 0.00000000 QTM.
> │ 10:02:50.378877 TBP 0% = 0.00000000 QTM.
> 

Note: It was 13 when I did the test and nothing is updated. It stays like that.

So one question is this because of my server being too loaded or just that the bot can freeze? Both options seem to be possible.
Also to note, I run free-version on many of them because I didn't want to bother you to unlock them 1 by 1 (when you have 5 minutes let's unlock them). Maybe that plays a role too?

> 
%Cpu(s): 99.0 us,  0.3 sy,  0.0 ni,  0.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st

(CPU use is between 93 and 99)

Thank you for taking a bit of time to answer me and very well done for the 6 digits bug, it works like a charm now!

**Comment by ctubio** [comment]
100% of cpu for sure is not nice, that may be the problem, feel free to let me know your addresses and i will credit

**Comment by ctubio** [comment]
just the BTC payment addresses is fine, no need a single char about api keys

**Comment by ctubio** [comment]
morning''
soo all unlocked'¡

**Comment by Camille92** [comment]
Thank you :))
