### ISSUE TITLE
UnknownHeld on GDAX 

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#415]
Hi Carles,

My GDAX Bot makes me problems from time to time. As you can see on the screenshot, it tells me that on ask side there is "unknown held". I don't know how to get rid of that message/error. 
Restart did not help, manual trade did not help. No open orders seen on GDAX website.
After several minutes in that state the message disappears. its seen on GDAX, other bots are fine.
Think, that the message comes from the closed source part, right?

any ideas?

thanks Boris

![bildschirmfoto 2017-11-21 um 18 42 43](https://user-images.githubusercontent.com/540850/33087987-8e633f0c-ceec-11e7-8c63-7ef19f01fe67.png)

---
```
app exchange: Coinbase/BTC/EUR
app version: latest / ownmod
OS distro: Ubuntu 16.04
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
the closed source only have api calls, the logic for statuses is in src/server/qe.h

**Comment by ctubio** [comment]
there is another issue about wrong status too i think, will review statuses soOn'' (in your case the status seems true, i mean, there are no quotes in big side, so the status of UnkownHeld may be "unknown" but at least is affecting correctly the quoting engine. oor.. did you have big quotes at that time? if not, i think we just need to replace "unknown" by the actual reason of the "held")

**Comment by b-seite** [comment]
The thing is, that when the Quoting engine applies the "UnknownHeld" it did it for both sides. as far as i understand the code right. But it appears only on one side. At least i´ve seen it on just one side.
So that maybe seems to be just a missing update to status "empty"?
But yes, i think K should trade at that time but instead it says "UnknownHeld".
Its a bit confusing.
