### ISSUE TITLE
Waiting Ping (Ping already done)

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#416]
HitBTC:
Why script waiting ping when ping already done? Its a bug?

![waitingping](https://user-images.githubusercontent.com/33358791/33120829-4c42a62e-cf84-11e7-9262-2529775f0a4a.PNG)

**Comment by serzhiio** [comment]
Everything is good.
You made buy (Ping) at $8 256.04 and choose pingAt BidSide it means that bot will seek for oportunity to sell (Pong) amount you already bought at higher price, but unfortunately fairPrice went lower to $8 244. Therefore there is no opportunity to make sell at defined level ($8254.04+pongWidth). Thats why bot is WaitingPing.

**Comment by donaldforest** [comment]
Ah, sorry! But I think bot must make another ping.. Or bot wait some conditions to made another ping?
I ask because in final all my depo was moved to BTC currency  (with multiply pings bidSize=0.02) and I again have uncompleted pong and WitingPing!

**Comment by serzhiio** [comment]
Why it should if you have TBPHeld?

**Comment by donaldforest** [comment]
I need to check again, but looks in my case TBPHeld sometimes have a black hole! In another case how to explain that bot buy BTC for ALL USD with static tbp and pDiv.

**Comment by serzhiio** [comment]
No blackholes at all. Look, you set tbp to 0.01 and pDiv to 0.01, so bot cant buy more btc than tbp+pDiv(0.01+0.01=0.02). On the screenshot you have 0.026 (its more than 0.02) so you overbought by btc and have insufficient USD funds. Thats it!

**Comment by donaldforest** [comment]
Was old screen. Now it
![s1](https://user-images.githubusercontent.com/33358791/33149270-361d0b1c-cfe0-11e7-99d4-1149968ea131.PNG)

**Comment by serzhiio** [comment]
It cant be seen on the screenshot but feels like you set too big bidSize/askSize. Think its a reason why you've been ran out of USD very quick. Objectively 0.02btc bid is too high for 0.067btc deposit. Try to lower bids or increase your deposit.

**Comment by donaldforest** [comment]
0.067btc deposit - is zero deposit for hitBTC. Is no way trade on this exchange lower than 0.01 Btc.
I try save all my depo is about 500$ in USD. But bot as always buy BTC on top of price and hold it now. I try setup strategy without holding anything except pings in BTC depo. Trade only in one direction ping for buying some BTC and fast pong with selling this BTC with USD. But about a 5 days cant setup this!

**Comment by donaldforest** [comment]
Again! Can You explain, looks like bug..
I move all possible BTC to USD depo (sold it). Setup TBP = 0.01, pDiv = 0.01. sop = off, arp = off.
Bot again move all depo to BTC:
Its legal for this settings?
![222](https://user-images.githubusercontent.com/33358791/33154355-e58101cc-cff8-11e7-9963-169487a2c1f9.PNG)

**Comment by Camille92** [comment]
Yes the second buy order could be a bug, but I can't say for sure.
