### ISSUE TITLE
Kmemory for values < 1

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#418]
Hello!
Strange work of **Kmemory = -0.1**
As I understood Kmemory = 0.1 (in absolute value) is a 24 (day) * 0.1 = 2.4 (hours). I wait cleaning ifo about pings and pongs (-0.1) which older than 2hours:24min. In my case history with older trades already exist and bot don't start new pings (existing incomplete ping prevents him to create another from a clean slate)..

![kmemory](https://user-images.githubusercontent.com/33358791/33142355-3b24fb06-cfc7-11e7-9992-ee0bc86df894.png)

**Comment by ctubio** [comment]
trades are NOT nonstop auto cleaned

trades are cleaned only after a trade is done

wait for a new trade, and  you will see all old ones gone

**Comment by donaldforest** [comment]
Hm, will be more helpful reset by time, like in my case. I mean some trades cant be done ever or long month!

**Comment by ctubio** [comment]
well, the bot is expected to trade frequently, that is why a timer seems redundant

the bot is never expected to be 1 month without trading

trades should be more frequent than any desired interval for auto clean trades; simply because is not logical that trades are cleaned faster than what are created.

**Comment by donaldforest** [comment]
But as you see on picture bot make pings by higher price and already 4+ hours wait trend up to make pongs. Yep its possible, that BTC price go up today and bot continue trade. But it is undeniable that there will be a moment when the price won't be coming back.
Yep, reset trades history - is mean record a loss. But sometimes it's the only one solution, because we cannot be confident that the price will not go down.
I have no this situation when setup K make pings in both sides, but this case have no place to make profit. We lose on both directions of the trend.

**Comment by ctubio** [comment]
yea, not all trading paths goes to profits
