### ISSUE TITLE
Trade solution request (merge long time waiting pings)

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#419]
Hello!
It possible to add solution merge some pings by average price.
Example: We buy 1 BTC by price 8300$, then one more 1BTC by 8200$ (price go down), and now we can merge this pings to one -> 2BTC with buy price 8250$. Then we can pong it with sell 2BTC starting from 8250$ except waiting 8200$ for first ping...

**Comment by ctubio** [comment]
is enough confusing the trades history to make it even more (see https://github.com/ctubio/Krypto-trading-bot/issues/405) and i dont see the logic in mergin ping trades of different prices; in your example makes sense, but the market not always goes where your math needs

**Comment by ctubio** [comment]
what is pending TODO is ignore ping trades that are smaller of X quantity
