### ISSUE TITLE
Switch from https or using additional http UI connection

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#421]
Possible to add option for using http connection to UI on default or some configured ports?
All my tries to connect UI from Apple iOS browsers was failed. Is no way to connect with sockets with seflsigned certificates on last versions of iOS. Looks like http can solve this.

**Comment by ctubio** [comment]
to use http see the last sentence at https://github.com/ctubio/Krypto-trading-bot#web-ui
