### ISSUE TITLE
HITBTC - Floating point exception

### ISSUE THREAD

**Issue by malt001** [ctubio/Krypto-trading-bot#422]
Hi,
today I tried to setup the bot on a Raspberry PI and on an Debian pc. 
On both I get an error after the first parts seem to work as designed.
Example from the Debian client:

K build x86_64-linux-gnu 2017-11-23 00:33:46.
K version 0day.
15:23:33.370241 DB /data/db/K.1.XDN.USD.db loaded OK.
15:23:33.370826 UI ready over HTTPS on external port 3000.
15:23:33.371097 QP Warrrrning: using default values for Quoting Parameters.
15:23:33.371162 DB loaded 0 historical Trades.
15:23:33.371236 DB loaded 7 STDEV Periods.
15:23:33.371331 DB loaded EWMA Long = 0.000000.
15:23:33.371361 DB loaded EWMA Medium = 0.000000.
15:23:33.371372 DB loaded EWMA Short = 0.000000.
15:23:33.371416 DB loaded TBP = 0.00000000 XDN.
15:23:33.371481 DB loaded 3 historical Profits.
15:23:33.621621 GW HITBTC allows client IP.
15:23:33.621668 GW HITBTC:
- autoBot: no
- symbols: XDNUSD
- minTick: 0.00000100
- minSize: 10.00000000
- makeFee: 0.00000000
- takeFee: 0.00000000.
15:23:34.393927 QE Warrrrning: Unable to calculate quote, missing fair value.
15:23:34.681633 GW HITBTC WS Streaming book levels and orders.
**Floating point exception
K crashed with exit code 136.. Respawning..**

After this the error loops...

Any ideas?

**Comment by ctubio** [comment]
for now nope, i never experienced this error

does this happen in other markets or only happens to you at hitbtc xdn/usd?

**Comment by malt001** [comment]
For now I only checked with HitBTC - but with different pairs. Sometimes the process is alive for 30 - 40 seconds. but in the end it is always this error 136,

**Comment by malt001** [comment]
Maybe some requirements missing on a fresh installed debian / raspian minimal installation?

**Comment by ctubio** [comment]
maybe if you uncomment valgrind at https://github.com/ctubio/Krypto-trading-bot/blob/master/etc/K.sh.dist#L109 you can get more detailed logs?

**Comment by malt001** [comment]
No luck. Today i tried to with an ubuntu and a docker client and it started to work out. But in the end both version stoped working with a freeze after a few minutes. Same problem as i saw in other issues here.

**Comment by ctubio** [comment]
:( ok thanks, well someday we will find out

**Comment by SpencerMKSmith** [comment]
I've tried it on three different machines and have received the same issue.

**Comment by ctubio** [comment]
after the latests commits does this still happen?
