### ISSUE TITLE
foxfire: https://127.0.0.1:3000/    certificate issue    

### ISSUE THREAD

**Issue by 174high** [ctubio/Krypto-trading-bot#426]
hi  when i type https://127.0.0.1:3000/  
it shows  as below :  can you help me with it ?  

Your connection is not secure

The owner of 127.0.0.1 has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

127.0.0.1:3000 uses an invalid security certificate. The certificate is not trusted because it is self-signed. The certificate is not valid for any server names. (Error code: sec_error_unknown_issuer)

**Comment by donaldforest** [comment]
This is self-signed certificate. To continue you must agree that connection will be insecure and add this certificate as Exception. For example, for Firefox, click **Advanced** -> **Add Exception**. With google chrome something like **Processing Anyway**.
Another case: You can add your own "appropriate" certificates if you dont like this message! Or connect without ssl with simple http protocol (In case you don't need to encrypt trade information).
How to switch to http and more info about certificates here https://github.com/ctubio/Krypto-trading-bot#application-usage
