### ISSUE TITLE
Orders go off in UI - not reflected in GDAX

### ISSUE THREAD

**Issue by nate551** [ctubio/Krypto-trading-bot#43]
I am running the bot on Windows via docker - I am able to connect and everything appears to working correctly.  Some buys and asks cycled through and showed up in the order log.  However, my gdax doesn't reflect any such order, nor does it show any open orders.

**Comment by ctubio** [comment]
you mean that the app seems correctly working but is really not sending orders?

i never saw that, maybe can you go to https://www.gdax.com/orders/ and see if there are really any others or not?

In case that really is not sending orders, can you maybe execute the app with `nodejs K.js` and see if the error log prints something interesting?
thanks'¡

**Comment by nate551** [comment]
I verified that it is not sending the orders - I am going to try attaching mode-inspector to my container.  Hopefully I can figure that out.

Wouldn't be a config issue would it?
# General config properties. Replace with your own exchange account information:
ENV BotIdentifier autodev_bot
ENV EXCHANGE coinbase
ENV TradedPair ETH/USD
ENV WebClientUsername **redacted**
ENV WebClientPassword **redacted**
ENV WebClientListenPort 3000
ENV MatryoshkaUrl https:localhost

# Set options only for your desired EXCHANGE:

## Coinbase GDAX
ENV CoinbaseRestUrl https://api.gdax.com
ENV CoinbaseWebsocketUrl wss://ws-feed.gdax.com
ENV CoinbasePassphrase **redacted**
ENV CoinbaseApiKey **redacted**
ENV CoinbaseSecret **redacted**
ENV CoinbaseOrderDestination coinbase

I run the container using the -p 3001:3000 and -p 5001:5000 (otherwise it never connects to anything) and I can't connect to the URL

**Comment by ctubio** [comment]
err...
i hope this is not, but try changing the last line to:
```
ENV CoinbaseOrderDestination Coinbase
```

note the uppercase first C, let me know if this fixes your issue, and i will fix the app to avoid this
thanks'¡

**Comment by ctubio** [comment]
to check if your container can connect with gdax i think you can test a simple ping like:
```
ping api.gdax.com
```
you should see > 0  packets transmitted

**Comment by nate551** [comment]
Those don't need to be in quotes do they?

I changed the CoinbaseOrderDestination and rebuilt - it doesn't appear to have fixed anything.  It still shows that it did something, but GDAX has no knowledge of it

Still working on getting some logs out of the container - I'm new to docker so things are moving slowly.

**Comment by Camille92** [comment]
Hi all,

I had some problems with Gdax, for me it was the ETH/BTC and LTC/BTC markets. Can you try to see if it works on other markets than ETH/USD?

Best

**Comment by nate551** [comment]
LTC/USD doesn't seem to work either 

The API should only need view and trade permissions correct?

**Comment by nate551** [comment]
Now it doesn't seem to want to connect - tho the log does show something different (progress I guess)

13:25:15.088 main Event loop delay 12400ms
13:25:15.089 stdev Unable to compute value
13:25:27.115 main Event loop delay 11500ms
13:25:27.116 stdev Unable to compute value
13:25:27.589 coinbase FIX Logon Disconnected
13:25:38.720 tbp recalculated 1.7780919008318663
13:25:38.920 tbp recalculated 1.7782325046079246
13:25:39.259 tbp recalculated 1.7783362350370804
13:25:39.282 tbp recalculated 1.7782325046079246
13:25:39.440 tbp recalculated 1.7783362350370804
13:25:44.236 coinbase FIX Logon Disconnected
13:25:54.419 tbp recalculated 1.7785365931198625
13:25:56.434 tbp recalculated 1.7786406417701142
13:26:05.258 coinbase FIX Logon Disconnected
13:26:26.281 coinbase FIX Logon Disconnected

**Comment by nate551** [comment]
So I was poking thru the coinbase.ts file and saw on line 499 SocketConnectPort=4199

In GDAX API doc is see:
FIX API ENDPOINT URL

tcp+ssl://fix.gdax.com:4198

related?

**Comment by nate551** [comment]
I figured it out - I needed to log into the container and run stunnel witht he K-stunnel.conf

Even if your suggestions didn't fix it... it got me looking deeper and was able to figure it out!

**Comment by ctubio** [comment]
make sure `stunnel` is running with `ps axu | grep stunnel`, if is not, you can run it with `npm run test-stunel`, then see again if is running please
thanks'¡
