### ISSUE TITLE
changing cryptocurrencies

### ISSUE THREAD

**Issue by lonnieOST** [ctubio/Krypto-trading-bot#432]
I am testing out Krypto-trading-bot and would like to test it with XRP-USDT or BTC-XRP but did not see any information on how to chance it from BTC-USDT

Thanks,
Lonnie

**Comment by ctubio** [comment]
im not sure that i understand the question, just copy the config file to a new file and rename it as you desire, then inside the new config file set the desired new currency pairs; ooor what do you mean?

**Comment by lonnieOST** [comment]
Hello,

Sorry for the late response on this. 

Yes, I think that changing the config is what I am looking for but am running the docker instance and will have to get into the image to change the config.

I was looking for how to change the config for the docker instance.

Thanks,
Lonnie

**Comment by lonnieOST** [comment]
I have been able to get into the docker container 

$ docker run -it  ksh /bin/bash

and am looking for the file to change.

The github for this shows "K.sh.dist" but I am not sure if that is the correct config file.

Thanks,
Lonnie

**Comment by ctubio** [comment]
oh i see, in Docker the configs are not in any config file, but in the Environment variables of the docker container, to change docker's env vars simply edit the Dockerfile (ENV statements); more info at https://docs.docker.com/engine/reference/builder/#environment-replacement; if you use kitematic is simply in the General tab:  https://docs.docker.com/opensource/kitematic/images/kitematic_gui_container_id.png

**Comment by lonnieOST** [comment]
Thanks for getting back to me.

Is there any way to pass these variables on the docker command line?

now:

docker run -p 3000:3000 -v /home/lonnie/krypto-bot/data:/data --name Ksh -t
ksh

possibly:

docker run *--currency XRP-USD*   -p 3000:3000 -v
/home/lonnie/krypto-bot/data:/data --name Ksh -t ksh

maybe some of the other K.sh variables as well.

Thanks,
Lonnie

**Comment by ctubio** [comment]
to define env vars is the `-e` argument, see https://stackoverflow.com/questions/30494050/how-do-i-pass-environment-variables-to-docker-containers
