### ISSUE TITLE
remove delayAPI

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#433]
`delayAPI` ~and `cxl`~ quoting parameter~s~ will be removed if nobody cares soOn''

**Comment by Camille92** [comment]
I'm in for delay API but against cxl because if it's useless now, it *can* be very useful in the future in case something is wrong.

Well at least that's my view :p

**Comment by b-seite** [comment]
I am with Camille92 
Cxl could be helpfull in the Future. (Hopefully not but Nobody knows)
And because i like gui options, maybe we add the Option to set the cancel loop Time in the gui.
