### ISSUE TITLE
DEVELOPER WANTED

### ISSUE THREAD

**Issue by coinexchhange** [ctubio/Krypto-trading-bot#44]
Hi
was wondering if anyone provides paid services for installing krypto-trading-bot and creating trading bots?

Looking forward hearing from you all.

warm regards
vasilis

**Comment by ctubio** [comment]
feel free to join the IRC channel at https://kiwiirc.com/client/irc.domirc.net:6697/##tradingBot, we can easy talk in private there and solve your needs, im analpaper but maybe others are willing to help too.
