### ISSUE TITLE
not respecting pDiv

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#440]
Hi, Carles!
Please look at the screenshot. I've faced with total pDiv ignoring situations.
Fortunately, bot make big btc sale at good high margin right before falling by $50.
Despite this fact its a wrong bahavior.

![pdiv-respecting](https://user-images.githubusercontent.com/10449591/33342248-88a0b12a-d492-11e7-8a90-47a02f63b4ea.jpg)

**Comment by ctubio** [comment]
im sorry im not able to see whats wrong; missing too many information to reproduce the issue
