### ISSUE TITLE
BUY SELL TS 

### ISSUE THREAD

**Issue by 174high** [ctubio/Krypto-trading-bot#442]
from the manual guidance 
i can't understand how to calculate the buyTS . 

Time | Side | Price | Size | BuyTS | SellTS | Notes
-- | -- | -- | -- | -- | -- | --
12:00:01 | Buy | 10 | 1 | 1 | 0 |  
12:00:02 | Buy | 10 | 0.5 | 1.5 | 0 | Partial fills of size get counted fractionally
12:00:03 | Sell | 11 | 0.75 | 0.75 | 0 | Sell for more decrements the imbalance
12:00:05 | Sell | 5 | 0.75 | 0.75 | 0 | Sell for less than the other buys doesn't help
12:00:06 | Buy | 10 | 0.5 | 1.75 | 0 |  
12:00:07 | Buy | 10 | 0.5 | 2.75 | 0 | Stop sending buy orders until 12:30:07

**Comment by ctubio** [comment]
if a trade have X value, a buyTS or sellTS will be 1 when the 100% of X is traded.

having a buy/sellTS of 3, means that you bought or sold 300% what you expect in that period of time
