### ISSUE TITLE
detachable windows - feature request

### ISSUE THREAD

**Issue by spudstr** [ctubio/Krypto-trading-bot#443]
Would be a neat feature to make the stats window detachable and in its own window?  Could make life a little easier.

**Comment by donaldforest** [comment]
You mean slide it to footer under trade data?

**Comment by spudstr** [comment]
That.. or make it a popout window that can be moved around.

**Comment by donaldforest** [comment]
I can try add button to Stats which control it jump bottom or back again. Just need test it on different browsers resolutions and get community agree. Adding charts to movable overlay window not optimal - Web UI is already to hard (more than 3.5 Mb).

**Comment by ctubio** [comment]
the layout is focused for multiple stacked matryoshka UIs; but if you just have one UI visible, maybe makes sense to separate the stats; will consider someday while migrating the UI to a more lightweight layout

**Comment by Jeetlions** [comment]
Whats the performance of the BOT this year on BTC USD ?

**Comment by ctubio** [comment]
that question is too generic; and is hijackin an unrelated thread
