### ISSUE TITLE
Conditional (delayed) TBP change

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#446]
The main idea is to have a settings to change tbp on a conditional predefined basis.
Lets imagine we have a strong uptrend and we have a vision that we should exit this trend on specific price.
For instance i want to have TBP 50% when price will reach $15000 and now i have $12000. So when price come to $15000 TBP whatever it was will be defined constantly at 50% and it can be changed manually by turning off "Delayed TBP" or automatically when original TBP will come to 50%.
How is it?

**Comment by donaldforest** [comment]
How to detect, we need stop on $15000?
In case fixed price value like $15000 or $15632 we have new layer of settings which do not consider automation principles. I mean we will be moved to manual trade mode.
Why to stop on $15000 if TBP try automatically respect trade changing and we can continue have a profit?

**Comment by ctubio** [comment]
im sorry im not sure what to do here :S
