### ISSUE TITLE
App Crashing after latest update

### ISSUE THREAD

**Issue by Grayjack64** [ctubio/Krypto-trading-bot#447]
I did a 'make latest' request and am now getting the following:

K crashed with exit code 127.. Respawning..
K build x86_64-linux-gnu 2017-11-29 02:30:05.
./app/server/K: unrecognized option '--target'
 Thanks for the help

**Comment by ctubio** [comment]
sorry i had updated the sh config file, make sure you remove --target argument at the very botom in your file, also please make sure --ws is also removed

**Comment by ctubio** [comment]
you can compare/see the latest at https://github.com/ctubio/Krypto-trading-bot/blob/master/etc/K.sh.dist

**Comment by Grayjack64** [comment]
Thank you. I have it up and running again.
