### ISSUE TITLE
Pong with qtyPing=0.0000, valPing=$0.00, valPong=$0.00, qtyPong=0.0000 and Kdiff=$0.00

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#448]
Not sure, bug or not.
Exchange: HitBTC
![kdiff_0](https://user-images.githubusercontent.com/33358791/33474812-1fcc1980-d68d-11e7-82bd-f02fee147bf3.PNG)

**Comment by ctubio** [comment]
decimals are too small
