### ISSUE TITLE
Problems with makefile

### ISSUE THREAD

**Issue by b-seite** [ctubio/Krypto-trading-bot#449]
Hey Carles,

i have two issues with the actual makefile.

1. when i have made local changes and then i do a make reinstall or latest, the process runs thru the end without any errors instead of stopping because git says that it has unmerged files and did not load the latest from upstream. I like to have it as it was in the past when make stopped on unmarked files. 

2. make bundle runs me crazy because it builds all three CARCH folders. And when i try to do a new make K i get this (sorry for the german language) 
`make: aarch64-linux-gnu-g++-6: Befehl nicht gefunden
Makefile:87: die Regel für Ziel „K“ scheiterte
make: *** [K] Fehler 127`
i first have to remove the unwanted build-arm-linux-gnueabihf build-aarch64-linux-gnu folder to make K again.
its this line what makes me the trouble : https://github.com/ctubio/Krypto-trading-bot/blob/73ddaa03ad22eb312786ef6f9db372e4d446e464/Makefile#L280

**Comment by ctubio** [comment]
thanks, will fix point 1

about point 2, it just really compiles 1 arch, and the other two are `cp` with the line you pasted, i will try a fix or otherwise simply split the `cp` action into a new separated make target.

thanks again''

**Comment by ctubio** [comment]
at point 1, it runs without erros but it looses  your local changes, right? :(

**Comment by b-seite** [comment]
Its the other way round. 
if there are any local changes (even its a package-lock.json or something) then the makefile did not update to head but throws no error

**Comment by ctubio** [comment]
is now any better?

im now sure i was able to reproduce your situation, for me local changes are always lost after reinstall, the files that seems changed after make reinstall are because the latest tar build does not include the latest commits sometimes; i try to do tar builds as frequent as commits to fix this confusion :dancer:

**Comment by ctubio** [comment]
about your point 2, i dont get why your `make bundle` and your `make` uses different arch; did you installed with git or with zip?
