### ISSUE TITLE
pingWidth affect price pongs in PingPong and Boomerang safety

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#450]
In case safety  PingPong or Boomerang (AK-47 not checked) if you try increase pingWidth to 99 (pongWidth about 1-5), then price of pongs increased to $50+ (Simple to check all pongs - is Ask side).
Checked on pingAt = BidSize with pongAt = ShortPingFair.

**Comment by ctubio** [comment]
may be increased because of safeties, widthPong is not based in widthPing
