### ISSUE TITLE
(Just for convenience) : Can we put all the conf files in a folder?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#452]
So the multy-instance guys like me can just copy and paste the entire folder when I do a clean install.

Plus it will look less messy in the main directory!

**Comment by Camille92** [comment]
> app                     dshbtc.sh  etcusd.sh   Makefile           paping_1.5.5_x86-64_linux.tar.gz  sanusd.sh     yywbtc.sh
> btcusd                  dshusd.sh  _ethbtc.sh  MANUAL.md          qshbtc.sh                         src           yywusd.sh
> btcusd.sh               edobtc.sh  ethbtc.sh   node_modules       qshusd.sh                         test
> build-x86_64-linux-gnu  edousd.sh  ethusd.sh   package.json       README.md                         THANKS
> COPYING                 etc        _K.sh       package-lock.json  sanbtc.sh                         TODO
> _dshbtc.sh              etcbtc.sh  LICENSE     paping             sanusd                            WHITE_R🐰BBIT

**Comment by ctubio** [comment]
i do believe is more convenient in the root folder :S

**Comment by ctubio** [comment]
:bulb: hey, by now this is possible, you can call the sh files from any folder, cos they all call the global `/usr/local/bin/K-trading-bot` file, and we dont read from the filesystem any relative path anymore
