### ISSUE TITLE
Matryoshka: nested client won't connect if server has password with special characters

### ISSUE THREAD

**Issue by gladstonedigital** [ctubio/Krypto-trading-bot#453]
In K2.sh:

`UI_PASSWORD="somepassword!with)and("`

I'm able to access the second instance in the browser at its own URL just fine, but when I try to add it as a nested matryoshka instance in the first instance, "localhost refused to connect"

However, when I change the password to use a normal password with only letters, it connects just fine.

**Comment by ctubio** [comment]
are you adding to the url the username and the password instead of just the ip letting the browser prompt the credentials?

**Comment by gladstonedigital** [comment]
No I didn't try that, I was just using url like https://localhost:3001, and letting the browser prompt for password. It might work the way you mentioned

**Comment by ctubio** [comment]
letting the browser prompt for the password is what i usualy do, and i could not reproduce the issue you describe; for me the passwords works nice as long as the browser prompts for it and i dont put it wrong :S

**Comment by gladstonedigital** [comment]
Hm that's strange, I tried it multiple times and it kept failing, but worked if I went to the second instance's page directly. I'll play with it more later

**Comment by ctubio** [comment]
im sorry i not able to reproduce this
