### ISSUE TITLE
Add timer before each respawn 

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#455]
Hey Carles,

So according to what we talked about yesterday, making a "make restartall" is becoming very difficult as we hit the bitfinex limit very quickly.

So is it possible to make a delay between each respawn, or maybe that the bot doesn't crash if it doesn't get market data on boot with REST API and just tries again 1mn after?

Thanks for the development,

Camille

(It's fine once it's launched but it takes a lot of time before getting there)

**Comment by ctubio** [comment]
will add this mod to the next tar build

thanks'¡
