### ISSUE TITLE
EWMA_* stop counting data after some minutes of work

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#458]
K reinstalled 12-15 hours ago.

![tbp_ewma](https://user-images.githubusercontent.com/33358791/33551416-5ed78c50-d902-11e7-9d2d-74efa2355b16.PNG)

Some minutes after switching to Manual:

![tbp_manual](https://user-images.githubusercontent.com/33358791/33551514-a6560bc4-d902-11e7-8e71-6d6378906d32.PNG)

**Comment by ctubio** [comment]
TBP is not displayed in the charts when it is equal to 0% or 100%
