### ISSUE TITLE
Okex -> -0.1 maker fees. Is the bot working with it ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#459]
Hi Carles and all,

I just looked at Okex which is the alt trading platform of OkCoin.

It seems to be a good exchange to trade in as the maker fees is negative (and -0.1% is a LOT).
If you just trade 10x your stack, you made already 1%. 

Doing market making, I achieve to exchange my stack around 1000 times per month, so I think it's really worth it.

Plus, as it's derivated from OkCoin, I imagine that the API might be pretty similar or exactly the same.

They offer a lot of pairs to trade in, so it seems to be one good trading platform for the bot. (Above 40).

Tell me what you think,

Camille

**Comment by Camille92** [comment]
https://www.okex.com/

**Comment by ctubio** [comment]
just change the WSS HTTP endpoints and there you go, like okcoin.cn i hope

**Comment by Camille92** [comment]
That would be amazing it is just that, I will try when I have time :)

**Comment by serzhiio** [comment]
Are they working outside US territory?

**Comment by Camille92** [comment]
They are Chinese, I think they don't care when you come from as you don't put fiat there.

They have crypto / BTC, crypto /ETH and crypto /USDT pairs.

**Comment by serzhiio** [comment]
Unfortunately BTC maker fee is positive.

**Comment by Camille92** [comment]
No look go on "token trading" side and everything is minus -0.1.

![capture d ecran 2017-12-04 a 14 06 01](https://user-images.githubusercontent.com/6861590/33554288-610a8a28-d8fc-11e7-9d92-12cab2a17241.png)

**Comment by serzhiio** [comment]
Hm interesting!
I've glanced here.
![fee the leading global bitcoin cryptocurrency exchange okex com](https://user-images.githubusercontent.com/10449591/33554864-64d7ce50-d90f-11e7-9b41-6876ccf2b472.png)
P.S.: Camille how can I contact you, i have some questions about bitfinex.

**Comment by Camille92** [comment]
It's for the futures :).

You'll tell me when I'm on the IRC or here :)

**Comment by Camille92** [comment]
I need to add that volume is probably going to be an issue here (see: https://coinmarketcap.com/exchanges/okex/), but that would be a good starting exchange for people with a small budget!

**Comment by CarlitoGrey** [comment]
Just updating the API addresses doesn't work:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  unresolved reference token '4'
```
I'm guessing there's some small changes to the API. I'd be interested in getting on this exchange so another vote from me!

**Comment by CarlitoGrey** [comment]
Ok, managed to get it to connect but there's no order book :D.

**Comment by Camille92** [comment]
Oh sad!

I was thinking about it, it's crazy you trade 1M, and you get 1000USD! And that's just if you sell at the price of buying.

**Comment by CarlitoGrey** [comment]
Yup! Sounds good to me.

**Comment by b-seite** [comment]
Hey @CarlitoGrey do you like to explain hot you fixed the unresolved reference token error?

**Comment by ctubio** [comment]
reopening cos some buggy bugs were reported about this integration
