### ISSUE TITLE
Coinbase : FIX Logon Disconnected

### ISSUE THREAD

**Issue by daaaaan** [ctubio/Krypto-trading-bot#46]
At some point in the last few hours the bot is unable to connect to trade on the coinbase exchange. In the GUI I get the "Connecting to Exchange..." 

When I fire it up in the foreground on my server I get

`08:34:11.164 coinbase FIX Logon Disconnected`

And that repeats every 20 seconds or so. I've changed the API keys, interestingly if I give it an incorrect key it errors on wrong key so the auth is working. Not sure if the issue is only related to me or others are experiencing it. 

Just done a npm run latest and no difference.

**Comment by ctubio** [comment]
see if https://github.com/ctubio/Krypto-trading-bot/issues/43 resolved your issue, basically you need to make sure that `stunnel` is running; usualy simply by running `npm run stunnel`

**Comment by daaaaan** [comment]
Stunnel Madness. Fixed.
