### ISSUE TITLE
ping orders smaller than bidSize on available balance

### ISSUE THREAD

**Issue by spudstr** [ctubio/Krypto-trading-bot#460]
i.e .  i have a .05 bid on BTC.  and it places a bid for .0001 valued at 1.64..   can we put a option or a check in place not to place a bid if balance < bidSize ?

**Comment by ctubio** [comment]
check if  balance < bidSize is at:
https://github.com/ctubio/Krypto-trading-bot/blob/cd38e64837c6a269689becc8995dff80012fb7d1/src/server/qe.h#L230-L241

**Comment by ctubio** [comment]
im not sure that i understood your question

**Comment by spudstr** [comment]
balance less than BidSize.  i have a bidsize of .05 but it put a bid in for .0001.  I assume its because the total base position + pdiv was triggering it.

**Comment by ctubio** [comment]
it places smaller orders if there isnt enough balance; do you have more than .1 on bid side to possible allow more than 1 concurrent order of .05 in bid side?

**Comment by spudstr** [comment]
probably did.  I just figured it would only ever stick to bid/ask size and not deviate.

**Comment by ctubio** [comment]
i had reviewed nextQuote friend functions and cannot find offensive lines; let me close this and forget about unless you feel that something must be still fixed
