### ISSUE TITLE
How to compile some local experimental changes in src/server?

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#464]
Before pushing to global, I want to check some changes in sources make\compile\run local K build. For client I do "make bundle"; for server I was try "make dist" (correct me if I'm wrong) .. With client all ok, but server side compiled with error in case adding just one simple space to code with errors like:

> 
> Makefile:144: recipe for target 'ncurses' failed
> make[1]: *** [ncurses] Error 77
> make[1]: Leaving directory '/home/bottt/K'
> Makefile:97: recipe for target 'dist' failed
> make: *** [dist] Error 2

Can You help me?

**Comment by ctubio** [comment]
first need to `make dist` to compile all dependencies; only once is done, then anytime you want to recompile src/server you can use `make`
