### ISSUE TITLE
Used the - - free-version

### ISSUE THREAD

**Issue by Ultrahoschie** [ctubio/Krypto-trading-bot#465]
Hey,

How i used the - - free-version Statement in the background? I can Start it with. /K.sh - - free-version but how i Start it with make Start Statement for background using?

And how it works the paying way when i only send you btc to your adress or is the the adress for all different?

Thx

**Comment by ctubio** [comment]
just add it to the K.sh file, inside the line OPTIONAL_ARGUMENTS
