### ISSUE TITLE
Blank screen https://127.0.0.1:3000/

### ISSUE THREAD

**Issue by TonyStark** [ctubio/Krypto-trading-bot#469]
Getting blank UI while opening 127.0......
here is my browser detail:: https://www.whatismybrowser.com/w/GHEAM58
tried chrome and firefox but same result

**Comment by ctubio** [comment]
i dont understand what means blank screen, try `curl -vvv https://127.0.0.1:3000/` to see what is going on

**Comment by TonyStark** [comment]
@ctubio 
this is screenshot of blank white screen
https://i.imgur.com/3KWjGBa.png
and output of your command
```➜  Krypto-trading-bot curl -vvv https://127.0.0.1:3000/
* About to connect() to 127.0.0.1 port 3000 (#0)
*   Trying 127.0.0.1...
* Adding handle: conn: 0x1def9b0
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x1def9b0) send_pipe: 1, recv_pipe: 0
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS alert, Server hello (2):
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by ctubio** [comment]
well, it is `curl -vvvk https://127.0.0.1:3000/` to avoid the `curl: (60) SSL certificate problem: self signed certificate`

**Comment by TonyStark** [comment]
@ctubio 
i dont understand. i mean what to do to remove that blank screen on browser?

**Comment by ctubio** [comment]
if you have credentials, to get rid of the blank screen you must insert the correct password when prompted, usualy

if that was not the case, close and open again the browser to be prompted again

`curl -vvv https://127.0.0.1:3000/` fails because is missing `-k` to avoid the self signed certifiacte problem.. use `curl -vvvk https://127.0.0.1:3000/`  to see if your server is alive; a blank screen, as you can imagine does not give any information, thats why i ask for a curl output..

instead of a useless blank screen you could open the network tab in the inspector and show the number of the return html code, or anything you see in the response; that would be uselfull then

**Comment by TonyStark** [comment]
no password prompted when i open 127.0.0.1:3000 only blank screen appear
i open and closed browser, tried in slimjet browser. but no access
again ```-vvvk``` gives below output
```
* About to connect() to 127.0.0.1 port 3000 (#0)
*   Trying 127.0.0.1...
* Adding handle: conn: 0x7f69b0
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7f69b0) send_pipe: 1, recv_pipe: 0
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-SHA
* Server certificate:
* 	 subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
* 	 start date: 2016-12-22 21:03:25 GMT
* 	 expire date: 2017-12-22 21:03:25 GMT
* 	 issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
* 	 SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET / HTTP/1.1
> User-Agent: curl/7.32.0
> Host: 127.0.0.1:3000
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: keep-alive
< Accept-Ranges: bytes
< Vary: Accept-Encoding
< Cache-Control: public, max-age=0
< Content-Type: text/html; charset=UTF-8
< Content-Length: 760
< 
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/ag-grid.min.css">
    <link id="daynight" rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>[?]</title>
    <link rel="icon" href="favicon.png">
    <style>
      .buy { color: blue }
      .sell { color: red }
      .kira { color: green }
      .unknown { color: black }
      .row { margin-left: 0; margin-right: 0; }
    </style>
  </head>
  <body>
    <ui></ui>
  </body>
  <script src="/js/client/bundle.min.js"></script>
</html>
* Connection #0 to host 127.0.0.1 left intact
```
also network inspector and view html shown same above html code.
but still blank screen

**Comment by ctubio** [comment]
i never experiencied a blank screen after having correct html in the response; can you see if in the network tab of the browser there is any failing request? like the bundle.js failing to be loaded? or in the console tab is there any js error?

if this is the case i would suggest to use a popular (tested) browser, that even if is not so fast it will at least work

**Comment by TonyStark** [comment]
No error in network tab
https://i.imgur.com/MPDPzha.png
i guess now i should try latest browser...

**Comment by ctubio** [comment]
yea there is some syntax error, im sorry i only tested the web ui with firefox and chrome

**Comment by TonyStark** [comment]
switch to Firefox 57 and no more blank screen :v:

**Comment by ctubio** [comment]
thanks for the report''' on my next holidays i promise to investigate a bit whats wrong with slimjet or other webkit browsers (as a non-priority funny task); thanks'¡.

**Comment by cheddarwhizzy** [comment]
same blank screen on osx in chrome, FF, and safari using Docker image `docker run --rm -ti -p 3000:3000 -p 5000:5000 -v `pwd`/K.sh:/K/K.sh cryptobot`.. and Virtualbox broken on 10.13.2.. aye aye aye let's ressurect Steve Jobs thru crypto. Apple really taking a shit lately :(

**Comment by schovi** [comment]
Same here. I tried to enable/disable auth and ssl. And still blank response. Using Docker version from master branch.

This runs inside Docker, so no problem with port visibility or something:

```
root@71b3d0884dbd:/K# curl -vvvk http://localhost:3000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Connection: keep-alive
< Accept-Ranges: bytes
< Vary: Accept-Encoding
< Cache-Control: public, max-age=0
< Content-Type: text/html; charset=UTF-8
< Content-Length: 0
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Comment by jpelini** [comment]
Mate, it does not look working..."Content-length: 0".

I have the exact same problem, and I cannot deal with that...using docker, authentication looks ok over SSL (I tried TLS1.0 TLS1.1 TLS1.2 SSLv3 - some are supported, some are not).

< HTTP/1.1 200 OK
< Connection: keep-alive
< Accept-Ranges: bytes
< Vary: Accept-Encoding
< Cache-Control: public, max-age=0
< Content-Type: text/html; charset=UTF-8
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact


Any ideas guys?

Tried : firefox 58, chrome 63, safari 11, opera 12.11...I got a 200 OK, but nothing is sent from the server. Is there a specific URI or something?

OSX highsierra

Thank you

**Comment by ctubio** [comment]
i have no idea, for me all works as expected while using the Dockerfile

what says `netstat -anp | grep 3000`?

and `ls app build*/*/*/*`?

**Comment by ctubio** [comment]
maybe helps thiz? https://github.com/ctubio/Krypto-trading-bot/issues/540

**Comment by jpelini** [comment]
Thank you ctubio
https://github.com/ctubio/Krypto-trading-bot/issues/540

Helps me a lot.

Thanks guys
