### ISSUE TITLE
Question: Multiple instances running on multiple networked machines

### ISSUE THREAD

**Issue by supersurfer92** [ctubio/Krypto-trading-bot#471]
Can multiple instances be running on multiple networked machines?

**Comment by ctubio** [comment]
it will work but will requiere mostly possible to setup different api keys for each bot, to avoid rate limits or to simply connect (hitbtc is all OK i think, but bitfinex will ban for 1 hour or so and coinbase doesnt allow multiple concurrent connections having the same api key)

**Comment by supersurfer92** [comment]
Cool, is it possible for the multiple *.sh' to be run on multiple machines and have everything fed to one main machine that would do the actual trading? I have multiple low power machines that I figure I could put to use

**Comment by ctubio** [comment]
im not sure what you mean, but feel free to reverse proxy anything in your network

**Comment by supersurfer92** [comment]
Basically can you distribute configs to be run on multiple machines but only have one machine do all the trading (the one with most available resources/RAM/processing speed)

**Comment by ctubio** [comment]
feel free to distribute any file inside your network; i dont get why is usefull to remotely maintain config files, but feel free
