### ISSUE TITLE
What happened to EWMA_Trend ? (+0.01BTC BOUNTY)

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#472]
Hi guys,

I find that very confusing, I ran an update and I can't find ewma trend anywhere ?!?

What is removed?

It's a great feature I don't get why!

**Comment by ctubio** [comment]
the idea was great but the implementation need less complexity (less customizable quoting parameters and less duplicate code)

**Comment by Camille92** [comment]
Well, why not keep it the way it is and update it when someone has time to write a better code?

On the other side, I feel all the customizable part was just the right amount to make it versatile and powerful.

#imissewmatrend :p

**Comment by ctubio** [comment]
i was updating it, made many fixed commits, and end up removing it cos really needs a rewrite from scratch ; see https://github.com/ctubio/Krypto-trading-bot/pull/456

**Comment by ctubio** [comment]
@serzhiio will be happy to know that you miss it

will try to rewrite it from scrach someday; resuing the lovely codes from serzhiio

**Comment by Camille92** [comment]
Thanks :)

**Comment by Camille92** [comment]
and thank you for the explanation :)

**Comment by prodigymike** [comment]
I was curious about this as well. Was trying to piece together things from the commit history. I figured that much code was removed for a reason ;-). Glad to see this thread about it. Rock on you all, glad to have donated.

**Comment by donaldforest** [comment]
@Camille92 is EWMA_* values works correct in last releases for you?

**Comment by Camille92** [comment]
Yes it does (not latest latest but from 2 days ago)

**Comment by donaldforest** [comment]
Try observe and compare EWMA_* charts with another sources. And check  https://github.com/ctubio/Krypto-trading-bot/issues/523

**Comment by Camille92** [comment]
Hey you're right there is a difference from other sources. I've noticed
that since a long time.

I have a few explanations for it:

1) K takes FV instead of close to calculate the Ewma you see on other
websites.
2) K doesn't consider the minutes according to the "time" it is (like 8:30
and 8:31) but every 60 seconds after it boots so it can be 8:30 and 17
seconds and then 8:31 and 17 seconds.


So I justify the difference with that. Meaning that usually it differs a
bit from what we see with different sources.

However if you notice a difference bigger than that it means that there's a
real issue we need to investigate.

I'll head to a party now so I can't look at the issue tonight.


Happy New year to you and the K traders !!!

**Comment by donaldforest** [comment]
I think troubles can be in some logging ewma to DB..

Happy New Year!!!

**Comment by Camille92** [comment]
I'm adding a 0.01BTC bounty for whoever can add ewma_trend again!

**Comment by mmourani** [comment]
hi camille, 

Thank you for all the good feedback on the bot. I have read all your post and it seem you got the experience and understand market making. Can you please help me in getting the proper configuration for the bot ? I tried a lot of different config and playing with each parameter and can't seem to be able to get it right.

**Comment by Camille92** [comment]
Hi @mmourani sorry for the long period without replying to you.

In those markets conditions it's really hard to do good market making. I invite you to join the IRC chat where there is always long-time users that can give you tips :)
