### ISSUE TITLE
Error in the calculation of ewma after a "save"

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#474]
Hello everyone,

I realized that when you save new values in your settings, the ewma are not calculated properly during 1mn.

I guess there's something to do with new ewma recalculation here, but I can't say for sure.

Here is one example of what you get in stats.

The problem is that it changes your TBP to 0 during 1mn.

I'm using EWMA_4 and the problem is only with medium and short.

![capture d ecran 2017-12-13 a 22 22 40](https://user-images.githubusercontent.com/6861590/33963237-8f0b793c-e054-11e7-9ce3-188e2c0ac3e4.png)

**Comment by serzhiio** [comment]
Support this issue. Seen such behavior some days ago.

**Comment by b-seite** [comment]
Yes that‘s a bug in the calcEwmaHistory function in mg.sh
We have to Start with the oldest record and Not with a 0 to recalc the ewma. 
Maybe there is another bug But...

**Comment by b-seite** [comment]
And then n has to be Periods - 1 because the 1. Value is already used to calculate the 2. Value 

Sorry for my wired Writings. Sitting in a Train and touching on an iPhone with german Autokorrektur

**Comment by Camille92** [comment]
No problem!

Happy to see that you know where the problem is :)

Tschuss!

**Comment by Camille92** [comment]
thank you for the quick fix guys!
