### ISSUE TITLE
OKEX partially filled orders bug

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#478]
I've noticed that sometimes partially filled orders just disappears in K and still persists at Okex. so Okex 
Look at the screenshot.
![okex-partially-filled-bug](https://user-images.githubusercontent.com/10449591/34009631-b052db82-e11a-11e7-9738-2f73ab35cd5d.jpg)

**Comment by serzhiio** [comment]
Carles, did you pay attention to price of partially filled order?

**Comment by ctubio** [comment]
now partial orders are not showing up in trades history until that partial trade is finaly completed or canceled; this way it avoid the silly okex api not telling the traded amount of each partial trade and we just use the total traded amount
