### ISSUE TITLE
Bug: pdiv and pdiv min can't be lower than 1%

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#483]
Hi everyone,

I just noticed that pdiv and pdiv min can't be lower than 1% (I use % mode I don't know about the rest).

So just a little bug!

Have a good weekend,
Camille

**Comment by ctubio** [comment]
so lets allow 0.1? or even lower you need?

**Comment by Camille92** [comment]
No let's allow 0, if at some point you want to do b&h or manual trading while keeping the bot on.

Or if you use for instance Switch you might want pdiv = 0 if a coin if going up a lot :)

**Comment by ctubio** [comment]
ok nice, cos decimals are anyway not allowed as percentages xD, lets allow 0

**Comment by ctubio** [comment]
will be available on next tar build, thanks for notice this'''
