### ISSUE TITLE
GOT IT TO WORK

### ISSUE THREAD

**Issue by dullfig1** [ctubio/Krypto-trading-bot#485]
Ok, please excuse my excitement, I got the software to work. Ok, for any other users out there as dense as me having problems, here are the things I had to figure out, which were not immediately obvious to me.

If you are on coinbase, you need to upgrade to the gdax website. (or am I wrong?)

then you need to create an API key. It's one of the menu options. Save the API key, the API secret and the API passphrase somewhere ( i made a text file) because it won't be shown again, and you need it. 

the API_PASSPHRASE in the configuration file (K.sh) is NOT your password that you use to log into gdax, it's the passphrase you put in when creating the API key.

the API secret has a "==" at the end. This is part of the secret, you need to put it in.

Anyhow, I can now log into the program from a browser and can see the screens.

BY the way, is .0121 still the required donation to unlock?

Dan

PS.: program keeps saying "missing market data". Is this due to the program being locked? or is there something else going on? I'm not running live yet.

**Comment by ctubio** [comment]
missing market data means the api key does not have permissions to read market data; or the market setup does not exists; it is not related to the unlock.
