### ISSUE TITLE
 Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found) on Poloniex

### ISSUE THREAD

**Issue by jbarket** [ctubio/Krypto-trading-bot#486]
uname -a: Linux CPZL0G2 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

Everything seems to work fine until after it places its first order. Then the world ends. Here's the full stdout:

K build x86_64-linux-gnu 2017-12-16 20:42:01.
K version 0day.
06:01:13.426907 DB /data/db/K.8.BTC.XMR.db loaded OK.
06:01:13.428754 UI ready over HTTPS on external port 3002.
06:01:13.430406 DB loaded Quoting Parameters OK.
06:01:13.430830 DB loaded 0 historical Trades.
06:01:13.434054 DB loaded 740 STDEV Periods.
06:01:13.434571 DB loaded 0.017920 EWMA VeryLong.
06:01:13.434778 DB loaded 0.018061 EWMA Long.
06:01:13.435204 DB loaded 0.018217 EWMA Medium.
06:01:13.435638 DB loaded 0.018320 EWMA Short.
06:01:13.437526 DB loaded 250 historical FairValues (save time avg: 73573ms).
06:01:13.437959 DB loaded TBP = 0.62285234 BTC.
06:01:13.440985 DB loaded 37 historical Profits.
06:01:13.740137 GW POLONIEX allows client IP.
06:01:13.740754 GW POLONIEX:
- autoBot: no
- symbols: BTC_XMR
- minTick: 0.00001000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000.
06:01:14.708819 QE Warrrrning: Unable to calculate quote, missing fair value.
06:01:15.710031 QE Warrrrning: Unable to calculate quote, missing fair value.
06:01:16.711209 QE Warrrrning: Unable to calculate quote, missing fair value.
06:01:17.712057 QE Warrrrning: Unable to calculate quote, missing fair value.
06:01:18.713279 QE Warrrrning: Unable to calculate quote, missing fair value.
06:01:20.721987 PG TBP: 100% = 0.62250958 BTC, pDiv: 144% = 0.90000000 BTC.
06:01:25.128463 UI authorization success from ::1.
06:01:26.417208 UI 1 currently connected, last connection was from ::1.
06:01:33.762037 GW POLONIEX Quoting state changed to CONNECTED.
06:01:34.762209 PG TBP: 100% = 0.62216720 BTC, pDiv: 144% = 0.90000000 BTC.
06:01:38.383312 Errrror: Signal 11 Segmentation fault (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x1a)[0x7fba6076d3aa]
./app/server/K(_ZN1K2EV3wtfEi+0x128)[0x7fba6077a058]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7fba5f7254b0]
./app/server/K(_ZSt18_Rb_tree_incrementPKSt18_Rb_tree_node_base+0x22)[0x7fba60a9e042]
./app/server/K(_ZN1K2QE13stopAllQuotesENS_5mSideE+0xa9)[0x7fba60787fb9]
./app/server/K(_ZN1K2QE11updateQuoteENS_6mLevelENS_5mSideEb+0x4f9)[0x7fba607a4d59]
./app/server/K(_ZN1K2QE9calcQuoteEv+0x315)[0x7fba607a5385]
./app/server/K(_ZZN1K2QE8waitTimeEvENKUlP5TimerE_clES2_+0x11a)[0x7fba607a579a]
./app/server/K(_ZN4Loop3runEv+0x17a)[0x7fba607acfea]
./app/server/K(main+0x1436)[0x7fba6075eb06]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fba5f710830]
./app/server/K(_start+0x2a)[0x7fba6075f79a]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by ctubio** [comment]
thanks for the report'' im sorry doesn't seems to be very popular this exchange so im not investing time on it currently

**Comment by ctubio** [comment]
closing this because https://github.com/ctubio/Krypto-trading-bot/issues/577 have more info
