### ISSUE TITLE
unable to calculate TBP, missing market data...

### ISSUE THREAD

**Issue by dullfig1** [ctubio/Krypto-trading-bot#488]
Hello:

On the tty console where I start K.sh, there are messages popping up that say

"QE Warrrning: Unable to calculate TBP, missing market data...."

I checked the API key I generated, and it has all permissions enabled (view, trade, manage, transfer, bypass-2fa); 

So what could be going on? where do I look next?

Dan

**Comment by ctubio** [comment]
do a manual order in the exchange to verify that your api key have permission to trade on that market; if so make sure is correct the configs in your config file

**Comment by dullfig1** [comment]
Hmmmm. scratching my head. The messages say i logged in successfully, but I am unable to place orders...

**Comment by dullfig1** [comment]
Maybe create new API key? by the way, are keys immediately active? they seem to have a waiting period on the coinbase.com site.

**Comment by dullfig1** [comment]
solved it. You have to actually have funds in GDAX... duh.

**Comment by ctubio** [comment]
thanks for the infos''
