### ISSUE TITLE
Segmentation fault after control -c

### ISSUE THREAD

**Issue by Optictrollz** [ctubio/Krypto-trading-bot#489]
https://gyazo.com/a842330a50c660f182187a2fb8a3ec0c

**Comment by ctubio** [comment]
thanks for the report'' can i ask if was with --naked or without? and how you exit the app with ctrl+c or with [q] hotkey?

**Comment by Optictrollz** [comment]
I exited the app with ctrl+c, I just ran it with gdax settings, I didnt explicitly write out --naked, or --free-version. it uses the default optional_arguments of "--colors --naked"

**Comment by ctubio** [comment]
thanks for the info; if was without --free-version i have no idea; will investigate

**Comment by ctubio** [comment]
last question'¡ the ctrl+c was a few seconds only after start the app or was several minutes after the app was running? (i believe was at the very begin)

**Comment by Optictrollz** [comment]
It was like 15 seconds, I was just seeing, if it said GW Coinbase Fix Logout, reconnecting in 21s...
