### ISSUE TITLE
Can't boot -> undefined symbol: sqlite3_open

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#49]
Hi Carles,

I just ran an update and I can't boot, I get that:

```
K.linux.51
nodejs: symbol lookup error: /root/K/app/server/lib/K.linux.51.node: undefined symbol: sqlite3_open
```

Have a good night,

Camille

**Comment by ctubio** [comment]
is a heavy update, can you make sure all modules are reintalled? (`rm -rf build node_modules`)

i checked and `-lsqlite3` is in the first line at https://github.com/ctubio/Krypto-trading-bot/blob/master/Makefile#L1, so you may need to recompile

**Comment by Camille92** [comment]
Will do I late you know :)

**Comment by Camille92** [comment]
Still running in the same issue but I did not put too much time to see what's happening. I'll do that when I have more time!

**Comment by b-seite** [comment]
Same here,

deleted the node_modules, app and build folders. 
But still the same Error when starting K

**Comment by ctubio** [comment]
feel free to paste the installation log; the execution log is useless as you can see

**Comment by b-seite** [comment]
My OS Version is Ubuntu Linux 16.04 with Node Version 8.1.2 and npm 5.1.0
Attached is a debug-log from npm install

[npm-debug.log.txt](https://github.com/ctubio/Krypto-trading-bot/files/1135668/npm-debug.log.txt)

**Comment by ctubio** [comment]
thanks for the log just downloaded it

**Comment by ctubio** [comment]
i never used `--unsafe-perm`, let me test the install with it and see if this is the reason

**Comment by Camille92** [comment]
Clean install on Ubuntu 16.04, node 7.1, npm 5.1.0 and as a non-root and I still have the same result:
:S 
https://pastebin.com/NmGS0hq0

**Comment by b-seite** [comment]
i also ran as non-root

**Comment by Camille92** [comment]
The internet took me there looking for a solution https://stackoverflow.com/questions/9389344/error-undefined-reference-to-sqlite3-open

**Comment by Camille92** [comment]
Problem solved !! I send you a PR :D

**Comment by ctubio** [comment]
many thanks Camille, laterz i will try to remove the unused lib in the first line, hope it doesn't crash again xD

**Comment by ctubio** [comment]
hope https://github.com/ctubio/Krypto-trading-bot/commit/926da26d610aaa918450454698ff5dad9b83d96f is still OK for you

**Comment by Camille92** [comment]
Yep all good!

**Comment by Jorman** [comment]
Hi, I just installed the program on a vps server but when I ran it won't start, so I tried with node K.js and here the same error
```
lello@9f60:~/K$ node K.js
K.linux.57
20:46:59.867355 CF settings loaded from K.json OK.
node: symbol lookup error: /home/lello/K/app/server/lib/K.linux.57.node: undefined symbol: sqlite3_open
```

I also tried to reinstall with `rm -rf build node_modules && npm install` but no luck

I always run as non root user, and here some info
```
lello@9f60:~/K$ node -v
v8.2.1
lello@9f60:~/K$ npm -v
5.3.0
lello@9f60:~/K$ uname -a
Linux 9f60.k.time4vps.cloud 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Any idea?

**Comment by ctubio** [comment]
@Jorman can you see if is OK after 5ee69106dc073dd5e3342100b8fd3ff3b9f47e04? thanks'¡

**Comment by Jorman** [comment]
tnx @ctubio 
Now the sql error was gonne, I tried to start after a recompile, I got this error

```
lello@9f60:~/K$ node K.js
K.linux.57
7:55:42.339108 CF settings loaded from K.json OK.
7:55:42.387500 DB /data/db/K.0.0.82.db loaded OK.
7:55:42.432402 UI ready over HTTPS on external port 3000.
7:55:43.296356 GW null details:
- autoBot: no
- pair: BTC_USD
- minTick: 0.01
- minSize: 0.01
- makeFee: 0
- takeFee: 0
07:55:44.756 stdev Unable to compute value
07:55:45.758 stdev Unable to compute value
07:55:46.178 main Unhandled exception! TypeError: gwSymbol.split is not a function
    at Timeout.NullPositionGateway.setInterval [as _onTimeout] (/home/lello/K/app/server/gateways/nullgw.js:61:103)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
07:55:46.182 main Attempting to cancel all open orders, please wait..
07:55:46.184 main Unhandled exception! TypeError: gwSymbol.split is not a function
    at Timeout.NullPositionGateway.setInterval [as _onTimeout] (/home/lello/K/app/server/gateways/nullgw.js:62:103)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
    at listOnTimeoutNT (timers.js:340:26)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at Immediate._tickCallback [as _onImmediate] (internal/process/next_tick.js:180:9)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
07:55:46.185 main Attempting to cancel all open orders, please wait..
07:55:46.759 stdev Unable to compute value
07:55:47.759 stdev Unable to compute value
07:55:48.182 main Exit code 0
```
I've not yet edited the file with the market data, so is set to null, maybe this?
Anyway I've a question, which exchange is better to use? I see there'are many exchange but I don't have the experience to start with one or other, any suggestion?

**Comment by Camille92** [comment]
https://github.com/ctubio/Krypto-trading-bot/issues/72 ...

**Comment by ctubio** [comment]
yea `TradedPair` currently throws an error if doesnt containts the symbol `/`

**Comment by Jorman** [comment]
To try, mi config is
```
    "BotIdentifier": "bot",
    "EXCHANGE": "null",
    "TradedPair": "BTC/ETH",
    "WebClientUsername": "NULL",
    "WebClientPassword": "NULL",
    "WebClientListenPort": "3000",
    "MatryoshkaUrl": "https://",
```
So pair was set, when I lauch with npm start I got this, but I can't reach the ip:3000 page and I don't know what is wrong without a log
```
lello@9f60:~/K$ npm start

> K.js@3.0.0 start /home/lello/K
> npm run test-compile && KCONFIG=$npm_package_config_config forever start --uid $npm_package_config_config -a -l /dev/null K.js && exec npm run test-stunnel


> K.js@3.0.0 test-compile /home/lello/K
> test -d app || npm $(test -d node_modules && echo run post)install

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: K.js

> K.js@3.0.0 test-stunnel /home/lello/K
> test -z "$SKIP_STUNNEL$(ps axu | grep stunnel | grep -v grep)" && exec stunnel dist/K-stunnel.conf || :
```

Any Idea?

**Comment by ctubio** [comment]
with "EXCHANGE": "null", nothing is expected to happen, im not sure what do you expect?

**Comment by ctubio** [comment]
i just fixed the split error, but still nothing will happen with null exchange

**Comment by Jorman** [comment]
Ok, I think that start anyway, my fault.
So I just put the poloniex data, api and secrets then started with npm start
```
lello@9f60:~/K$ npm start

> K.js@3.0.0 start /home/lello/K
> npm run test-compile && KCONFIG=$npm_package_config_config forever start --uid $npm_package_config_config -a -l /dev/null K.js && exec npm run test-stunnel


> K.js@3.0.0 test-compile /home/lello/K
> test -d app || npm $(test -d node_modules && echo run post)install

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: K.js

> K.js@3.0.0 test-stunnel /home/lello/K
> test -z "$SKIP_STUNNEL$(ps axu | grep stunnel | grep -v grep)" && exec stunnel dist/K-stunnel.conf || :
```
The ip:3000 is not reachable. How can I see a kind of log to post here?

**Comment by ctubio** [comment]
running `node K` or `nodejs K.js` should display the log in the foreground
