### ISSUE TITLE
Where to go from here?

### ISSUE THREAD

**Issue by dullfig1** [ctubio/Krypto-trading-bot#492]
Hi:

This is probably not the best place to ask, as this is an "issues" message board, but I managed to work out all the kinks of my installation, and last night I was able to connect to my GDAX account, and trade.

I am a complete newbie to this game, and so now I would like to get pointed in the right direction. I need to learn all this new terminology and how to tweek it. Market Making is new to me, but I learn fast.

Any help will be appreciated.

Dan

**Comment by ctubio** [comment]
the irc is a nice place, you can find the link in the donations section of the readme
