### ISSUE TITLE
cross exchange marketmaker + arbitrage opportunities

### ISSUE THREAD

**Issue by markchristoph** [ctubio/Krypto-trading-bot#494]
hey Carles,
thanks for sharing your nice Project here on github.
I am not a  coder, but MS Systems engineer out of proffession.

I am doing fx trading since many years and have experience in live Sports betting Arbitrage, in both sectors I have experience in developing trading strategies for automated trading Systems. 

So i am not sure if my issue is suiting to the System from technical side, but I would like to share one issue with you

By the way, I am so bad in technical side that i did not get your bot running yet on my Windows 10 maschine. So excuse please when any of my proposals are already included the bot, i did not test it yet.

...so during my Problems to install I read many issues about div. problems, also about connecting to exchanges. 
So I was wondering if the bot only works with 1 Exchange for market making? As I understood yes. I was asking me why didn´t you include "cross-exchange" comparison. Would that too much blow up the kryprotradingbot?
adding more exchanges to the bot in a kind of universal api (there is one code from Patricky Grady https://github.com/patrickgrad/crypto-universal-api - ) would open a wider range, and we could go deeper in strategy oportunities. like crossExchange<->crossmarket - single/cross-marketmaking and Arbitrage oportunities.

If you like my strategy Input, I would be glad to help from that side.
looking forward to your feedback
merry christmas
Mark

**Comment by ctubio** [comment]
thanks for the suggestion'' addition of concurrent exchanges is in the TODO list

btw the bot is a unix-like application; it will not run natively on winy

**Comment by ctubio** [comment]
that link is a bit out of dated :( seems not updated since 1 year ago, also it just works for 2 exchanges, the only universal thing it have is the name :( the abstract class to extend the exchanges is too much simple, ours is far better and enough for what we need:
https://github.com/ctubio/Krypto-trading-bot/blob/1aee0b323769379c72351e33ad14465dce913e68/src/server/km.h#L538-L566

**Comment by markchristoph** [comment]
Hello Carles, thank you for your feedback. am sry not able to check the code of this universal api before bothering you. When you say you have something better, ok. Just wanted to suggest that the crypto market still have great price differences from exchange to exchange and market/Fiat to crossmarket/Fiat.
Just checked the actual BCH and btc prices from today, picture attached, differing prices, wondering how it can still happen. It seems that there are not so much bots yet which are caring about these differences. Out of my view it is the greatest chance to improve the bot and it should get higher prio. Please tell me freely your opinion, may i am missing the total coding view and i am wrong? I am sure you have had these opotunities in your mind for longer time, and your reasons why not to Set Up yet?

Von meinem Huawei-Mobiltelefon gesendet

-------- Originalnachricht --------
Betreff: Re: [ctubio/Krypto-trading-bot] cross exchange marketmaker + arbitrage opportunities (#494)
Von: Carles Tubio
An: ctubio/Krypto-trading-bot
Cc: markchristoph ,Author


that link is a bit out of dated :( seems not updated since 1 year ago, also it just works for 2 exchanges, the only universal thing it have is the name :( the abstract class to extend the exchanges is too much simple, ours is far better and enough for what we need:
https://github.com/ctubio/Krypto-trading-bot/blob/1aee0b323769379c72351e33ad14465dce913e68/src/server/km.h#L538-L566

**Comment by ctubio** [comment]
another link coming from IRC https://github.com/donaldng/bitfinex-arbitrage
