### ISSUE TITLE
IOTA @Bitfinex not working ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#5]
Hi Carles,

I did not have time to try those markets before but apparently, they don't work.

Do you experience the same issue?

Best,

Camille

**Comment by ctubio** [comment]
Hello Camille,
the symbol is `IOT`, see https://api.bitfinex.com/v1/symbols_details, are you using this one?

**Comment by Camille92** [comment]
Yep, I get the market info but no trades and not my balance :/ ![capture d ecran 2017-06-19 a 00 03 44](https://user-images.githubusercontent.com/6861590/27264627-f2603242-5482-11e7-8e89-5eb182c448ae.png)

**Comment by ctubio** [comment]
i thikn you need to agree with IOTA disclaimer, see https://www.bitfinex.com/deposits/new/iota

**Comment by Camille92** [comment]
Thank you that was the error!

And before it works you need to manually buy some IOT!

Weird but now it works :)
