### ISSUE TITLE
Bid size not calculating correctly?

### ISSUE THREAD

**Issue by pha3z** [ctubio/Krypto-trading-bot#502]
![cryptobot-bid-not-working](https://user-images.githubusercontent.com/2966966/34274869-3f83ec5c-e660-11e7-830e-1bed1340d256.jpg)

I inserted a screenshot to this post.  Should be visible above:

The documentation says Mid mode should be setting FV - width / 2 for bid.  But if you look at my settings, it's not working.  The bot keeps entering a significantly lower bid.

Am I doing something wrong?
I clicked the SAVE button after I made parameter changes and canceled any existing bids so it would enter new ones.  The new ones always come up way lowe than they should be.

**Comment by ctubio** [comment]
cos you have safeties enabled; consider to use the irc channel for this, i hate this shit of issues
