### ISSUE TITLE
Ask/Bid size calculation

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#505]
Maybe i'm wrong, but is it correct to use rawBidSz inside Ask size calculation?
```
          if (rawQuote->ask.size > totalBasePosition)
            rawQuote->ask.size = (!rawBidSz or rawBidSz > totalBasePosition)
              ? totalBasePosition : rawBidSz;
```

**Comment by ctubio** [comment]
is a fallback when ask.size > totalBasePosition

otherwise will not place any order

**Comment by serzhiio** [comment]
The question was not about what is it, but about why we are using rawBidSz
in AskSize calculation? Maybe change it to rawAskSize?

24 дек. 2017 г. 2:08 пользователь "Carles Tubio" <notifications@github.com>
написал:

**Comment by donaldforest** [comment]
Agree. Size in last version some random value.. For example for bidSize, askSize = 0.05, bot frequently setup 0.01, 0.02 qty, independently of TBP and pDiv.. and switched off all sop, apr, safety..
