### ISSUE TITLE
Negative Price Detected / UnknownHeld

### ISSUE THREAD

**Issue by werkkrew** [ctubio/Krypto-trading-bot#507]
HitBTC - ZEC/ETH Market

No matter what settings I try the console is filled with:
Negative price detected, widthPing or/and widthPong must be smaller.

The top of the order book for both quotes says: "UnknownHeld" and no quote data seems to get filled in.

Latest version pulled today, clean build.

**Comment by ctubio** [comment]
yea well, consider to run --debug-quotes or something

**Comment by werkkrew** [comment]
I did, would you mind taking a look at the logs or perhaps helping me out?  I'd like to confirm if its actually some sort of bug or if its user error.

**Comment by ctubio** [comment]
sure feel free anytime on IRC, we can freely talk there
