### ISSUE TITLE
teh codez

### ISSUE THREAD

**Issue by see2bio** [ctubio/Krypto-trading-bot#508]
it is beautiful. but why, why teh sh1t comez precompiled wit teh damn fre3-v3r$ion slowdown?

**Comment by ctubio** [comment]
precompiled is just because it save me time when upgrading multiple machines; and therefore to the end user too

the free version shit is because nobody donates otherwise; just the same 3 users all the time; i was starting to feel bad for them

**Comment by see2bio** [comment]
hmm to be honest one of the biggest downsides is fact that users don't get the full experience unless they pay. for instance I would be happy to turn on the miner so you get your kick but the fact that it degrades performance is a bummer. what about a different approach? like setting a temporary session with some reasonable hash countdown that the user has to mine, not necessarily even on the same machine? (even connecting that to mining via the UI could solve the problem). what do you think?

**Comment by ctubio** [comment]
there are 3 modes:
run in realtime but 3 levels only (without --free-version and without a donation)
run delayed with all levels  (with --free-version and without a donation)
run in realtime with all levels  (without --free-version and with a donation)

i cannot imagine more convinations, because with --free-version and with a donation seems a stupid convination

if you dont donate, and if you want all levels; i want you to mine nonstop all day, not just a temporary period xD wtf

**Comment by ctubio** [comment]
note that a donation can be a payment to the BTC addr or can be also a nice PR; again, i cannot think about more convinations to make life easier and happier for everybody

**Comment by see2bio** [comment]
^ that claim is ridiculous. there are no feature request issues, also the source code is intentionally obfuscated making it non approachable for most people. 

some gratitude to the folks that did most of the heavy lifting and less bullying could have made things different. saying thanks on a damn MD is not enough, what if they forced you to donate? I think I'm gonna fork tribeca, rewrite the core in go so you don't have a claim for being negligibly superior on speed, add support for the major exchanges with recent api updates and gtfo with the "donations". kthxbai fuck you asshole

**Comment by ctubio** [comment]
the code is not obfuscated in any way; i had stop reading you because i totally disagree; did you ever saw obfuscated code?
