### ISSUE TITLE
Using API from diff accounts whithin same pair

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#510]
Faced with trouble.
I'm trying to run several bots on same pair from diffirent accounts (and API).
But after install i see that all bots using same DB file (one trades history for all).
Can i define different db files for this or i need to setup new K instance on current/other machine?

**Comment by serzhiio** [comment]
So i treat this problem as serious bug because i've prepared new config file and moved it to other current configs. Due to DB sharing problem after "make restartall" new btc/usd bot changed config of first btc/usd.

**Comment by ctubio** [comment]
use --database=/whatever/other/path.db or --database=:memory:
