### ISSUE TITLE
Coinbase Errrror: Signal 6 Aborted (Three-Headed Monkey found)

### ISSUE THREAD

**Issue by rettori** [ctubio/Krypto-trading-bot#511]
00:43:21.462766 Errrror: Signal 6 Aborted (Three-Headed Monkey found):
./app/server/K(_ZN1K2EV6reportEv+0x1a)[0x55bb8d1f96ca]
./app/server/K(_ZN1K2EV3wtfEi+0x128)[0x55bb8d204e28]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f52128f04b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f52128f0428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f52128f202a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d)[0x55bb8d5b7bfd]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6)[0x55bb8d52fab6]
./app/server/K(+0x4abb01)[0x55bb8d52fb01]
./app/server/K(+0x4aba49)[0x55bb8d52fa49]
./app/server/K(_ZNK3FIX8FieldMap11getFieldRefEi+0x21c)[0x55bb8d27797c]
./app/server/K(_ZZN1K10GwCoinbase6levelsEvENKUlP5AsyncE1_clES2_+0x867)[0x55bb8d27f707]
./app/server/K(_ZZN5Async5startEPFvPS_EENUlP4PolliiE_4_FUNES4_ii+0x36)[0x55bb8d1f6306]
./app/server/K(_ZN4Loop3runEv+0x111)[0x55bb8d23c221]
./app/server/K(main+0x14af)[0x55bb8d1e8f6f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f52128db830]
./app/server/K(_start+0x2a)[0x55bb8d1e9c5a]

**Comment by ctubio** [comment]
thanks for the report'' can i ask what currency pair are you using in coinbase?

**Comment by ctubio** [comment]
hope next commit fixes it; i didn't reproduced this recently

**Comment by rettori** [comment]
@ctubio, trading pair was LTC/USD

**Comment by kelsonic** [comment]
I just got this issue as well.

```
20:47:13.819465 Errrror: Signal 6 Abort trap: 6 (Three-Headed Monkey found):
- upstream: COINBASE
- currency: BTC/USD
- lastbeat: 1516135633819
- tracelog:
0   K                                   0x00000001099466b5 _ZN1K2EV3wtfEi + 645
1   ???                                 0x0000000000000010 0x0 + 16
```

I did see when creating the API key for Coinbase (not gdax) that it says that the API keys are invalid for 48 hours as a safety measure. However, when creating the API key on gdax I did not receive this warning, but I suppose they could be invalidating new API keys for 48 hours, too.

**Comment by ctubio** [comment]
that is because of mac OSX, see https://github.com/ctubio/Krypto-trading-bot/issues/136
