### ISSUE TITLE
minTick Decimal Precision on HitBTC

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#513]
Some trading pairs have the issue where the bot doesn't properly process minTick precision greater than 8 decimal places. I imagine that based off this issue here: https://github.com/ctubio/Krypto-trading-bot/issues/403
That the bot currently only accepts minTick decimal precision up to 8 which, as shown in that thread, causes many issues when placing orders.

- symbols: BCNBTC
- minTick: 0.00000000
Should be: 0.0000000001
{"id":"BCNBTC","baseCurrency":"BCN","quoteCurrency":"BTC","quantityIncrement":"100","tickSize":"0.0000000001","takeLiquidityRate":"0.001","provideLiquidityRate":"-0.0001","feeCurrency":"BTC"},

- symbols: DOGEBTC
- minTick: 0.00000000
Should be: 0.000000001
{"id":"DOGEBTC","baseCurrency":"DOGE","quoteCurrency":"BTC","quantityIncrement":"1000","tickSize":"0.000000001","takeLiquidityRate":"0.001","provideLiquidityRate":"-0.0001","feeCurrency":"BTC"},

- symbols: XDNBTC
- minTick: 0.00000000
Should be: 0.0000000001
{"id":"XDNBTC","baseCurrency":"XDN","quoteCurrency":"BTC","quantityIncrement":"100","tickSize":"0.0000000001","takeLiquidityRate":"0.001","provideLiquidityRate":"-0.0001","feeCurrency":"BTC"},

There are currently 5 pairs with 9 decimal precision minTicks and 3 with 10.
Can the bot please be modified to allow decimal precision up to 10 decimal places at least if the exchange API is set to HitBTC?

Thank you!

**Comment by ctubio** [comment]
thanks for the report, let me review thiz currency pairs on hitbtc

(note the limit of 8 decimals is just a **visual** limit for the numbers printed to the terminal; in other places may be displayed with other decimals, even if it have more than 8 decimals really)

**Comment by MiningInMySleep** [comment]
Thanks for the quick fix, but I think there might be some issue with how orders are rounded still because, while the interface on K is showing full 10 decimal precision (e.g.: 0.0000004244), the order that it is placing is still being rounded to 8 (e.g.: 0.00000042). I have confirmed both under "My Trades" and within the order book that this is happening.
