### ISSUE TITLE
IPC between instances 

### ISSUE THREAD

**Issue by 0xicl33n** [ctubio/Krypto-trading-bot#514]
Let's say I'm running two instances on the same exchange 

BTC/USD
LTC/BTC

My theory was originally that this would be a self propagating system where ltc is traded to BTC and back and forth between to usd, hopefully increasing everything overtime. 

Long story short, it didn't work. There were very very few trades. 

I'm no c++ programmer but I do know python, so the idea I have is to implement ipc between multiple instances of K, only if they're on the same exchange. 

Eg: 

If trade placed on exchange > blocking call to other instance > wait for trade to be canceled or go through before other instance attempts to make a trade. 

This should only be done on the same exchange and if one of the two currency pairs matches, like with ltc/btc and btc/usd the matching currency would of course be btc.

**Comment by ctubio** [comment]
instances are independent for each other as of today
