### ISSUE TITLE
UI Improvement Ideas

### ISSUE THREAD

**Issue by werkkrew** [ctubio/Krypto-trading-bot#516]
After using this tool for a week or so, I have a few UI improvement ideas:

1. Make stats graphs viewable all the time along side the main data panes without being on top of them.  For example, when "stats" is clicked have the graph/stats show up in a region below the rest of the existing panes.  Right now you can only view them instead of the orders or have it in an overlay above the orders which is not really readable.
2. In the current orders pane, if an order is a pong attempt, denote that it is a pong and for which ping the attempted pong is for.
3. In the current orders pane (or anywhere really) make it more obvious when the bot is attempting to actually do an aggressive buy/sell order.  Most of the time the orders are jumping around very rapidly and not near the top of the order book - but when certain conditions are met, the orders become more aggressive to the point of placing successful trades.  I would like to be able to know more readily what indicators are currently affecting the quotes and when the conditions are being met for it to place orders that it actually wants to happen.  For example, in EWMA_LS mode the manual says: 

> will use a long minute and short minute exponential weighted moving average calculation to buy up BTC when the short minute line crosses over the long minute line, and sell BTC when the reverse happens. The EWMA values are currently exposed in the stats.

It would be nice to know when these conditions are met and therefore what the bot is currently trying to do.

**Comment by ctubio** [comment]
for 2 and 3 the info is in the top text bars and in the stats; for example if buyPing or sellPing is > 0 then the the value of them are the matching pings for the current pongs; same for all other text/stats

about 1 im sorry but im not interested currently into expand the layout verticaly; maybe on the next redesign
