### ISSUE TITLE
Improvement: Define Web UI Path

### ISSUE THREAD

**Issue by werkkrew** [ctubio/Krypto-trading-bot#517]
When running multiple instances it would be nice for those of us who use a reverse proxy to be able to define a path the UI is running on.

For example, if I have https://kryptobot.mydomain.com  as my main domain for reverse proxy, I would like to be able to have instances laid out like:

https://kryptobot.mydomain.com/BTCUSD
https://kryptobot.mydomain.com/ETHUSD

etc.

Right now. even when I start two instances on different ports and attempt to do this, it does not work as expected.  I believe the app server needs to be able to have a path defined that it should listen on.

**Comment by ctubio** [comment]
make your reverse proxy in a subpath instead of in the root of the domain, like in:
```
location /nagios/ {
    proxy_pass  http://10.0.21.8:80/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect    off;
}
```

otherwise is also possible:
```
https://kryptobot-BTCUSD.mydomain.com/
https://kryptobot-ETHUSD.mydomain.com/
```

**Comment by werkkrew** [comment]
I am aware I could have multiple subdomains but using a path in the location directive didn't work, it caused some strange issues with the UI connecting to the wrong instance.  I'll see if I can get it to work on my end though.

**Comment by ctubio** [comment]
thanks for the idea'' will consider to add an optional document root path for each bot someday (anyway when implementing concurrent exchanges it will be mandatory i think)
