### ISSUE TITLE
Order History Precision Gets Lost

### ISSUE THREAD

**Issue by werkkrew** [ctubio/Krypto-trading-bot#518]
At some point in time (I am not sure what causes it) the precision of the values in the order history gets lost.  Based on a conversation in IRC I was told this is tied to the minTick value from the API.

In this example, the HitBTC minTick comes back as:
- symbols: ZECBTC
- minTick: 0.00000100
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000.

Looking at the order history in my UI:

![pings](https://user-images.githubusercontent.com/838837/34395770-23ce3bea-eb31-11e7-8b66-4750dfca3d4d.png)

After some time the pings lose their precision.  This makes it difficult to track profits/losses.

**Comment by Camille92** [comment]
Yes agreed there is a bug/choice made here that's not convenient with low-value assets.

Same for ewma that will all appear with only a precision of 2 zeros after the decimal point.

From my experience, this is NOT affecting the trading of the bot, just what's displayed.

**Comment by ctubio** [comment]
minTick is set on boot and is not modified during execution; this display truncates numbers because it wants when it wants xD if cannot contorl it better will simply not truncate numbers.

**Comment by werkkrew** [comment]
I agree it is not affecting the trading, just the display.  There is another display issue with the orders table where sometimes it doesn't show the pong columns:

![pong](https://user-images.githubusercontent.com/838837/34415700-1b22b56a-ebbe-11e7-964c-ab2f33a52f24.png)

**Comment by ctubio** [comment]
that is because quoting parameters defined; different modes have different columns; is not a issue
