### ISSUE TITLE
TBP pegged to zero using EWMA_4

### ISSUE THREAD

**Issue by SlackerATX** [ctubio/Krypto-trading-bot#522]
for 40 min TBP was set to 0% using EWMA_4 default period linear 5pDiv 10PDivMin%.  I restarting virtual box and it increased almost immediatly to 44%
:32.950889 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521020 BTC.
11:43:32.977706 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521141 BTC.
11:43:33.020282 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521020 BTC.
11:43:33.068061 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521141 BTC.
11:43:33.072358 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521020 BTC.
11:43:33.109389 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521142 BTC.
11:43:33.114290 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521020 BTC.
11:43:33.166695 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521144 BTC.
11:43:33.176569 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04522262 BTC.
11:43:33.254351 PG TBP: 44% = 0.19918285 BTC, pDiv: 5% = 0.02530433 BTC.
11:43:40.615592 GW COINBASE Quoting state changed to CONNECTED.
11:43:45.603364 PG TBP: 44% = 0.19911050 BTC, pDiv: 5% = 0.02529514 BTC.
11:43:45.747738 PG TBP: 44% = 0.19900074 BTC, pDiv: 5% = 0.02528120 BTC.
11:43:50.574415 PG TBP: 44% = 0.20289444 BTC, pDiv: 5% = 0.02577586 BTC.
11:43:50.574539 PG TBP: 44% = 0.19891785 BTC, pDiv: 5% = 0.02527067 BTC.
11:43:50.574785 GW COINBASE TRADE BUY 0.00903241 BTC at price 13905.2 USD (value 125.598 USD).
11:44:12.951585 PG TBP: 44% = 0.20286377 BTC, pDiv: 5% = 0.02577196 BTC.
11:44:12.951655 PG TBP: 44% = 0.19888809 BTC, pDiv: 5% = 0.02526689 BTC.
11:44:12.951903 GW COINBASE TRADE BUY 0.00903016 BTC at price 13908 USD (value 125.591 USD).
11:44:19.763712 PG TBP: 44% = 0.20286629 BTC, pDiv: 5% = 0.02577228 BTC.
11:44:19.763765 PG TBP: 44% = 0.19889095 BTC, pDiv: 5% = 0.02526725 BTC.
11:44:19.763876 GW COINBASE TRADE BUY 0.00903115 BTC at price 13905.2 USD (v

---
```
app exchange: Coinbase/BTC/USD
app version: latest
OS distro: I banged 1, ubuntu
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by SlackerATX** [comment]
BTW I stopped and restarting K.sh several times.

**Comment by SlackerATX** [comment]
then back to 0

11:49:41.149373 PG TBP: 48% = 0.21855771 BTC, pDiv: 5% = 0.02336923 BTC.
11:50:24.713916 MG reloaded 13891.420546 EWMA Long.
11:50:24.713948 MG reloaded 13856.597642 EWMA Medium.
11:50:24.713955 MG reloaded 13854.554569 EWMA Short.
11:50:35.384560 PG TBP: 48% = 0.22944274 BTC, pDiv: 5% = 0.02453311 BTC.
11:50:35.384691 PG TBP: 48% = 0.21852578 BTC, pDiv: 5% = 0.02336581 BTC.
11:50:35.384967 GW COINBASE TRADE BUY 0.0226083 BTC at price 13881 USD (value 313.826 USD).
11:50:42.507065 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521398 BTC.
11:50:43.039677 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04522363 BTC.
11:50:44.146351 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521397 BTC.
11:50:44.330122 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04522921 BTC.
11:50:52.041898 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521722 BTC.
11:50:52.942077 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04521395 BTC.

**Comment by Camille92** [comment]
Is very long ewma below long ewma in your stats?

**Comment by SlackerATX** [comment]
Are you asking for the config params or the output in the log for the values recorded?

**Comment by Camille92** [comment]
Just the logs or the info you get in "stats" of the bot.

**Comment by SlackerATX** [comment]
No, VeryLong is not below long.

12:41:02.684451 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04621279 BTC.
12:41:02.684520 MG reloaded 13848.166661 EWMA VeryLong.
12:41:02.684536 MG reloaded 13803.690491 EWMA Long.
12:41:02.684542 MG reloaded 13741.187218 EWMA Medium.
12:41:02.684547 MG reloaded 13702.206922 EWMA Short.
12:41:21.807793 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04621279 BTC.
12:42:28.711345 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04667492 BTC.
12:42:28.711397 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04621279 BTC.

**Comment by SlackerATX** [comment]
12:55:36.011301 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.016639 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04635811 BTC.
12:55:36.038069 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.043680 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04635812 BTC.
12:55:36.048162 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.066666 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04635814 BTC.
12:55:36.075592 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.249619 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633471 BTC.
12:55:36.252743 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.264891 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633470 BTC.
12:55:36.268459 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.290777 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633468 BTC.
12:55:36.294738 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.304581 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633467 BTC.
12:55:36.308479 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.320291 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633465 BTC.
12:55:36.323883 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.333229 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633464 BTC.
12:55:36.337201 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.350655 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633462 BTC.
12:55:36.354522 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.364086 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633462 BTC.
12:55:36.367880 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.381162 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633462 BTC.
12:55:36.388040 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633494 BTC.
12:55:36.610989 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633515 BTC.
12:55:36.626029 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.637199 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633517 BTC.
12:55:36.651902 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.656804 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633518 BTC.
12:55:36.670660 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.678251 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633520 BTC.
12:55:36.708451 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.716490 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633521 BTC.
12:55:36.730627 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.738686 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633523 BTC.
12:55:36.758969 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.764564 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633524 BTC.
12:55:36.780738 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.780953 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633526 BTC.
12:55:36.811788 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.817096 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633527 BTC.
12:55:36.907163 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.921136 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633529 BTC.
12:55:36.954857 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.967570 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633529 BTC.
12:55:36.972544 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.982221 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633529 BTC.
12:55:36.987104 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633492 BTC.
12:55:36.997460 PG TBP: 0% = 0.00000000 BTC, pDiv: 10% = 0.04633530 BTC.

**Comment by Camille92** [comment]
Well then it's a totally normal reaction of the bot under EWMA_4.
