### ISSUE TITLE
 CURL Warrrrning: wPost failed Peer certificate cannot be authenticated with given CA certificates.

### ISSUE THREAD

**Issue by zusanisha** [ctubio/Krypto-trading-bot#525]
Hi Dev!

1. I have been struggling with this error for the last 48 hours:
 CURL Warrrrning: wPost failed Peer certificate cannot be authenticated with given CA certificates.
I am not able to get the bot work at all.

2. I followed the instruction to manually make a trade in the exchange, however, the bot still cannot get the wallet info.

Please check the log info:

K build x86_64-linux-gnu 2017-12-29 04:08:06.
K version -3commits..
fatal: ambiguous argument '@..@{u}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
04:06:57.559222 DB /data/db/K.OKEX.ETH.BTC.db loaded OK.
04:06:57.560045 UI ready over HTTPS on external port 3000.
04:06:57.560865 DB loaded Quoting Parameters OK.
04:06:57.560969 DB loaded 0 historical Trades.
04:06:57.564893 DB loaded 549 STDEV Periods.
04:06:57.565017 DB loaded 0.053502 EWMA VeryLong.
04:06:57.565032 DB loaded 0.053507 EWMA Long.
04:06:57.565046 DB loaded 0.053518 EWMA Medium.
04:06:57.565055 DB loaded 0.053537 EWMA Short.
04:06:57.567705 DB loaded 668 historical FairValues.
04:06:57.567827 DB loaded 0 historical Profits.
04:06:57.567915 DB loaded TBP = 0.00000000 ETH.
04:06:57.567953 GW OKEX allows client IP.
04:06:57.567975 GW OKEX:
- autoBot: no
- symbols: eth_btc
- minTick: 0.00010000
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000.
04:06:58.612147 CURL Warrrrning: wPost failed Peer certificate cannot be authenticated with given CA certificates.
04:06:58.612315 GW OKEX Unable to read wallet data positions.
04:06:58.612337 QE Warrrrning: Unable to calculate quote, missing market data.
04:06:58.922813 GW OKEX WS Streaming channel ok_sub_spot_eth_btc_depth_20 true.
04:06:58.923359 GW OKEX WS Streaming channel ok_sub_spot_eth_btc_deals true.
04:06:58.959686 GW OKEX WS Streaming channel login true.
04:06:59.682748 PG Warrrrning: Unable to calculate TBP, missing wallet data.
04:07:02.258403 UI 1 currently connected, last connection was from 1.203.100.219.
04:07:13.689819 CURL Warrrrning: wPost failed Peer certificate cannot be authenticated with given CA certificates.
04:07:13.689937 GW OKEX Unable to read wallet data positions.

Please help! Many thanks!

**Comment by zusanisha** [comment]
The following is the debug log just in case you need it:

K build x86_64-linux-gnu 2017-12-29 04:08:06.
K version -3commits..
fatal: ambiguous argument '@..@{u}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
04:16:59.194438 DB /data/db/K.OKEX.ETH.BTC.db loaded OK.
04:16:59.195409 UI ready over HTTPS on external port 3000.
04:16:59.196350 DB loaded Quoting Parameters OK.
04:16:59.196470 DB loaded 0 historical Trades.
04:16:59.203345 DB loaded 830 STDEV Periods.
04:16:59.203508 DB loaded 0.053509 EWMA VeryLong.
04:16:59.203525 DB loaded 0.053521 EWMA Long.
04:16:59.203534 DB loaded 0.053544 EWMA Medium.
04:16:59.203542 DB loaded 0.053583 EWMA Short.
04:16:59.206933 DB loaded 674 historical FairValues.
04:16:59.207096 DB loaded 0 historical Profits.
04:16:59.207230 DB loaded TBP = 0.00000000 ETH.
04:16:59.207272 GW OKEX allows client IP.
04:16:59.207291 GW OKEX:
- autoBot: no
- symbols: eth_btc
- minTick: 0.00010000
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000.
04:17:00.079325 DEBUG EV void K::UI::timer_60s_or_Xs().
04:17:00.079553 DEBUG EV void K::GW::timer_15s().
04:17:00.094338 CURL Warrrrning: wPost failed Peer certificate cannot be authenticated with given CA certificates.
04:17:00.094441 GW OKEX Unable to read wallet data positions.
04:17:00.263030 DEBUG EV void K::QE::timer_1s().
04:17:00.263098 QE Warrrrning: Unable to calculate quote, missing market data.
04:17:00.368408 GW OKEX WS Streaming channel ok_sub_spot_eth_btc_depth_20 true.
04:17:00.368632 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:00.368653 DEBUG EV K::PG::waitData()::<lambda(K::mWallet)>.
04:17:00.368691 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:00.368770 GW OKEX WS Streaming channel ok_sub_spot_eth_btc_deals true.
04:17:00.369014 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369036 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369046 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369055 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369063 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369074 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369082 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369091 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369099 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369110 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369127 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369136 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369144 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369152 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369160 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369181 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369190 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369202 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369212 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369226 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369248 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369264 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369273 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369281 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369290 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369298 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369306 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369314 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369328 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369336 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369344 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369353 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369361 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369374 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369387 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369395 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369403 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369412 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369420 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369428 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369436 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369444 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369455 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369463 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369474 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369501 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369516 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369526 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369534 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369542 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369556 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369565 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369573 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369581 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369589 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369597 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369605 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369613 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369622 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.369630 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
04:17:00.395783 GW OKEX WS Streaming channel login true.
04:17:00.421654 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:00.421693 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:00.494244 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:00.494275 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:00.608263 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:00.608307 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:00.691341 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:00.691406 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:00.760383 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:00.760427 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:00.825208 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:00.825262 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:00.904582 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:00.904624 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:01.201413 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:01.201458 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:01.319051 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:01.319100 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:01.319138 DEBUG EV void K::QE::timer_1s().
04:17:01.319151 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:01.319194 DEBUG EV K::PG::waitData()::<lambda()>.
04:17:01.319204 PG Warrrrning: Unable to calculate TBP, missing wallet data.
04:17:01.399659 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:01.399705 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:01.505768 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:01.505825 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:01.597971 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:01.598024 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:01.735481 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:01.735633 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:01.856693 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:01.856743 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:01.930978 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:01.931028 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:02.051653 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:02.051702 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:02.135025 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:02.135073 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:02.236274 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:02.236321 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:02.337936 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:02.337987 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:02.338011 DEBUG EV void K::QE::timer_1s().
04:17:02.458689 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:02.458735 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:02.555024 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:02.555062 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:02.707103 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:02.707159 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:02.808020 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:02.808057 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:02.902192 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:02.902231 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:03.322542 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:03.322580 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:03.415908 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:03.415969 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:03.416008 DEBUG EV void K::QE::timer_1s().
04:17:03.704373 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:03.704407 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:03.888796 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:03.888843 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:04.010466 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:04.010595 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:04.112704 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:04.112735 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:04.152964 UI 1 currently connected, last connection was from 1.203.100.219.
04:17:04.220445 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:04.220476 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:04.335034 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:04.335075 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:04.467859 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:04.467905 DEBUG EV K::QE::waitData()::<lambda()>.
04:17:04.467928 DEBUG EV void K::QE::timer_1s().
04:17:04.599459 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:04.599558 DEBUG EV K::QE::waitData()::<lambda()>.
^C
04:17:04.814424 Excellent decision! let's plant a tree instead..
04:17:04.814473 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
04:17:04.814595 GW OKEX Attempting to cancel all open orders, please wait..
04:17:04.829896 CURL Warrrrning: wPost failed Peer certificate cannot be authenticated with given CA certificates.
04:17:04.829966 GW OKEX Unable to read order data.
04:17:04.829978 GW OKEX cancell all open orders OK.
04:17:04.830057 UI 0 currently connected, last connection was from 1.203.100.219.
04:17:04.830148 K exit code 0.

And this is the screenshot of GUI:
![image](https://user-images.githubusercontent.com/34975686/34459223-d4681700-ee24-11e7-93b4-91d30e620a23.png)

**Comment by ctubio** [comment]
thanks for the report'' may i ask what is your operating system?

maybe https://github.com/ctubio/Krypto-trading-bot/issues/503 helps?

**Comment by zusanisha** [comment]
You are welcome!

I am using centos with Docker application. However, I am not using docker for K. It was manually installed.

**Comment by ctubio** [comment]
i was never able to reproduce this issue; if you give me a link or steps to build your very same operating system i promise to investigate it

**Comment by zusanisha** [comment]
So do you think this issue is caused by centos?

What Linux OS do recommend then?

**Comment by ctubio** [comment]
im used to Debian and some users i know have Ubuntu, in CentOS should work but i never tried CentOS under Docker, i had always dedicated machines

**Comment by zusanisha** [comment]
Thanks! 

I switched to a dedicated server with Debian 8. However, I am not able to make install. I have tried with both Debian 8 and 9.

root@botvs:~/kbot# make install
make[1]: Entering directory '/root/kbot'
test -n "`command -v apt-get`" && sudo apt-get -y install g++ build-essential automake autoconf libtool libxml2 libxml2-dev zlib1g-dev openssl stunnel python curl gzip imagemagick screen \
|| (test -n "`command -v yum`" && sudo yum -y install gcc-c++ automake autoconf libtool libxml2 libxml2-devel openssl stunnel python curl gzip ImageMagick screen) \
|| (test -n "`command -v brew`" && (xcode-select --install || :) && (brew install automake autoconf libxml2 sqlite openssl zlib stunnel python curl gzip imagemagick || brew upgrade || :)) \
        || (test -n "`command -v pacman`" && sudo pacman --noconfirm -S --needed base-devel libxml2 zlib sqlite curl libcurl-compat openssl stunnel python gzip imagemagick screen)
/bin/sh: 1: sudo: not found
Makefile:194: recipe for target 'packages' failed
make[1]: *** [packages] Error 1
make[1]: Leaving directory '/root/kbot'
Makefile:202: recipe for target 'install' failed
make: *** [install] Error 2

Please advise! Thanks.

**Comment by zusanisha** [comment]
I think I got it work by switching to ubuntu. thanks!

**Comment by ctubio** [comment]
ima try to fix it with https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html

**Comment by ctubio** [comment]
let me say this was the first good idea of the year; thanks for the report'¡ :dancer:
