### ISSUE TITLE
Limit on depth of pricebook?

### ISSUE THREAD

**Issue by SlackerATX** [ctubio/Krypto-trading-bot#528]
My unlocked version doesn't seem to consider price levels below 20 or so.  I set the width on depth to like 100 just to check but it still on about 20 price  levels.

**Comment by ctubio** [comment]
in what exchange you mean? some do not allow more than 21 levels

**Comment by SlackerATX** [comment]
GDAX

**Comment by ctubio** [comment]
ok thanks, will take care of it first

**Comment by SlackerATX** [comment]
actually just confirmed it's limited to 15 price levels, same as the gui

**Comment by ctubio** [comment]
you are right, internally as well as in the UI, will update the internal levels to unlimited in the next commit; the UI may take some more commits

thanks for the report''

**Comment by ctubio** [comment]
will try to display them all in the UI somehow someday; for now are just couned in the footer
