### ISSUE TITLE
Memory leak/High RAM Consumption

### ISSUE THREAD

**Issue by JReming85** [ctubio/Krypto-trading-bot#529]
For some reason whenever I run this it always starts out using around 44-54mb of ram, then after an hour it is sitting around 500mb and climbing to 1gb, after several hours is maxes out my vps and using 2gb of ram and eating away at my vram.

Is there a way to cut its memory usage?

---
```
app exchange: Coinbase/BTC/USD
app version: undisclosed
OS distro: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
are you sure using the latest commit? if so can you please let me know if you are using `--headless` or `--naked` arguments? or is wthout them?

**Comment by ctubio** [comment]
after 6h my bots keeps under 20Mb; please feel free to add more info here in case you still want me to investigate your issue

**Comment by JReming85** [comment]
Forgot to mention I also use the --free-version on gdax.

The restricted version works fine and stays under 50mb of ram

**Comment by ctubio** [comment]
many thanks for the info will review soOn'' i was trying without

**Comment by JReming85** [comment]
Appreciate it,

Also using Ubuntu 16.04 LTS Server, 2 core, Intel(R) Xeon(R) CPU E5620 @ 2.40GHz.
2GB Ram with 2GB VRAM.
OpenVZ, Fresh install with only Krypton installed from git.

**Comment by ctubio** [comment]
now it should be around 21Mb while forever :dancer:

**Comment by JReming85** [comment]
Thanks, works perfectly now
