### ISSUE TITLE
Gemini Support

### ISSUE THREAD

**Issue by renkcub** [ctubio/Krypto-trading-bot#53]
Is this on the timeline? Would be willing to tip to prioritize.

**Comment by ctubio** [comment]
feel free to paste some link

**Comment by renkcub** [comment]
https://docs.gemini.com/rest-api/

Thanks, please feel free to provide a tip rate to prioritize by target x date.

**Comment by renkcub** [comment]
Same for Kraken - 
https://www.kraken.com/help/api

These are probably the two most "Legit" USA friendly exchanges, besides GDAX.

**Comment by ctubio** [comment]
it takes like 40 hours of development each gateway; the sum is bigger than what i feel happy to ask for as a tip

**Comment by bigdatabreen** [comment]
Would also tip for additional exchange supports. Can also contribute.
