### ISSUE TITLE
Order Price Rounding

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#530]
Thanks for the quick fix on the minTick decimal precision in issue #513  but I think that there might be some issue with how orders are rounded still because, while the interface on K is showing full 10 decimal precision (e.g.: 0.0000004244), the order that it is placing is still being rounded to 8 (e.g.: 0.00000042). I have confirmed both under "My Trades" and within the order book that this is happening.
Upon a quick glance at my trade history, it's pretty obvious that the rounding is causing the bot to buy and sell from itself based on the time stamps of subsequent trades for the same value and price.

**Comment by ctubio** [comment]
xD buying and selling from itself doesnt sounds nice

can you please confirm what are the affected currency pairs of hitbtc?

**Comment by MiningInMySleep** [comment]
I have bw enabled, but wouldn't that properly reflect on the K interface if it was affecting the price?
The pairs that I saw it most pronounced on are DOGE/BTC, BCN/BTC, BCN/ETH.
I imagine that any currency pair with higher than 8 decimal place precision will have this issue.
10: BCNBTC, XDNBTC, XDNCOBTC (Not sure what this last one is. Maybe old ICO?)
9: DOGEBTC, DSHBTC, SCBTC, ARDRBTC, POEBTC

**Comment by ctubio** [comment]
many thanks for the info''

(with `bw` disabled orders tends to have smaller spread; possibly overlapping, but i never saw it; i may need to start trading on this small currencies)

**Comment by ctubio** [comment]
the cause must be https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/km.h#L511 :(
will fix soOn after super testing that the possible solution does not affect other currencies (cos price is the most sensible value we have).

many thanks for insist on this''''

**Comment by ctubio** [comment]
still this issue exists but now is possible to use varaible precision for decimals everywhere, just need to implement it everywhere cos is still 8 everywhere even if is variable

**Comment by ctubio** [comment]
lets fix this at https://github.com/ctubio/Krypto-trading-bot/issues/862 since this one is a bit ou of date
