### ISSUE TITLE
Trading Strategy

### ISSUE THREAD

**Issue by IgorPcelnikov** [ctubio/Krypto-trading-bot#532]
Hello,
I'm thinking of this strategy that using quite often.
1) System scans last X last hours average
2) If Current Position is downtrend for M minutes defined  and X - marginParam  > CurrentPosition - try to buy
3) Budget (Defined) spreaded using either array of percentages or values for bidding steps
4) Max. buy bid level can be defined as parameter

This is buy strategy. Sell strategy can be either straight margin from buy bid or using existing functionality with buy bid + margin as a minimum

There should be timeframe defined in system to scan for the new bid to buy, for example every 30 minutes run through 1-3 steps again.

Thanks!

**Comment by ctubio** [comment]
Hello'''
i believe this buy strategy can be done using ewma/tbp/pdiv values

the sell strategy can be done using pingAt values

do you think really that we are talking about different things? (if so place can you explain better for my little brain?)
thanks for the info''

**Comment by IgorPcelnikov** [comment]
Let me play 1-2 days with params to check, just got it yesterday and unlocked and playing with params. Great work my friend!

**Comment by ctubio** [comment]
(otherwise i will close this in 24h just because im addicted to close isuess, but feel free to open as many issues as you consider anytime)

**Comment by Camille92** [comment]
@IgorPcelnikov It seems to be a good idea to me, don't hesitate to use tradingview and write on a chart to show us exactly how you want to proceed :)
