### ISSUE TITLE
Expose Stats Externally / Record Stats

### ISSUE THREAD

**Issue by werkkrew** [ctubio/Krypto-trading-bot#533]
Based on the README:

> The metrics are not saved anywhere, is just UI data collected with a visibility retention of n hours (where n is the value of profit quoting parameter), to display over time

Would be nice to have the stats stored somewhere or exposed via an api for display in other charting software.  This would not only allow for more advanced charting and easier visualization but it would also allow us to store more history so we could see profit over longer periods of time.

For example, I have currently modeled all of the EWMA modes and TBP/pDiv modes on tradingview so that I can see how changing different variables affects the bot:

![download](https://user-images.githubusercontent.com/838837/34546832-b9a3c110-f0c4-11e7-898d-144a70876f1d.png)

**Comment by ctubio** [comment]
im sorry that is reusing an existent application to do a secondary task; the main task of this application is to trade not to save data somewhere; and is important enought to not be delayed a single nanosecond

**Comment by ctubio** [comment]
the websocket data is quite simple with meanfull object members and in plain text; a simple application could connect to it like the UI does and listen to it like another client
