### ISSUE TITLE
GW OKEX Unable to read wallet data positions.

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#536]
I'm constantly seeing this warning in debug output:
"10:32:00.924336 GW OKEX Unable to read wallet data positions."

Trades are going on but what if this cause delays, wrong size calculations or whatever?

**Comment by ctubio** [comment]
mm... let me investigate this a bit, i saw it sometimes but not constantly

thanks for insist'¡

**Comment by ctubio** [comment]
next commit improves the wallet data, it was a bit dummy

**Comment by serzhiio** [comment]
Please look at logs.
Now when there is problem with wallet data instance hungs and WebUI just not answering to requests.
16:27:11.727854 DEBUG EV void K::UI::timer_60s_or_Xs().
16:27:11.733970 DEBUG EV void K::GW::timer_15s().
16:27:25.799428 GW OKEX Unable to read wallet data positions.
16:27:39.869039 GW OKEX Unable to read order data.

**Comment by ctubio** [comment]
for me the wallet data is nice; you still have issues?

**Comment by serzhiio** [comment]
At this moment i have no problem with wallet data.
But i have problems with bot stop showing orders and stop trading.

**Comment by r8m** [comment]
Getting same problem with wallet data:
```
10/09 14:59:40.658945 DEBUG OKEX <<< {"error_code":10007,"result":false}.
10/09 14:59:40.659501 GW OKEX Unable to read wallet data positions.
```
