### ISSUE TITLE
Okex new orders in memory while disconnected

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#543]
Hi, opened web UI of 2days turned off (disconnected) instance, noticed 2 orders in memory.
Looks like a bug, no?
![okex-turned-off](https://user-images.githubusercontent.com/10449591/34626242-f59e64d2-f26c-11e7-820f-5c2b859271b9.jpg)

**Comment by donaldforest** [comment]
Looks like something similar here but with HitBTC: https://github.com/ctubio/Krypto-trading-bot/issues/546#issuecomment-355835019

**Comment by ctubio** [comment]
the counter for sure doesn't have any bug; this orders must be really existing in the memory of the bot

without a full --debug-orders is impossible to know why
