### ISSUE TITLE
Kucoin Exchange Support

### ISSUE THREAD

**Issue by SpiryMedia** [ctubio/Krypto-trading-bot#545]
Any plan for Kucoin.com integration plan? 
It has a low-fee market program which is very appealing for the usage of the bot. Please take it in consideration.
Their API documentation:
https://kucoinapidocs.docs.apiary.io/

For those who aren't aware of the exchange: https://www.kucoin.com/
You are free to use invite code: 1K5v2

**Comment by ctubio** [comment]
SPAAAAAAM

**Comment by SpiryMedia** [comment]
Clearly is not a spam as I could have simply put a refferal link as it is possible. :) I've just been of good common sense :) . 

Anyway. Kucoin is gaining a lot of volume and interest similar to Binance :) But its up to you to be ignorant.

**Comment by ctubio** [comment]
im not going to waste time on a exchange nobody does business on it

do you think i eat smiles?

is up to you to be cheap

**Comment by SpiryMedia** [comment]
Hypocrisy is what I hate the most at people :) 

Meanwhile you have support for Korbit a shitty exchange huh? Or support the Russian mobsters from HitBTC 👍 . 

I think people should ask more question about the objective on the front page of this project also :)

**Comment by blast1987** [comment]
I care about it.
