### ISSUE TITLE
How does unlocking work?

### ISSUE THREAD

**Issue by 0xicl33n** [ctubio/Krypto-trading-bot#547]
I have sent BTC to the payment address in my client, however when i built K i did not git clone over SSH, i do not have any ssh keys setup on my github account - what happens if i want to move installations to a different server? How do  your api key unlock codes work? If i unlock while using coinbase does it still unlock for another exchange? 

Should i  add ssh keys, rebuild and send you the transaction id?

**Comment by bhallier** [comment]
As I understand it, the unlock is for one API key. So using a different exchange that uses a different API key will require an additional unlock. Once you send the deposit to the given address and it is confirmed, the active API key is unlocked and can be used on any server.

**Comment by ctubio** [comment]
unlocks are granted even with 0 confirmations and are related to the current API_KEY set in the current config file.

multiple api keys require multiple unlocks, no matter if the same exchange of different one.

i dont know what you maen by ssh keys; the only related key is your current API_KEY

it is also not related to git, and is not related to the protocol used in git

it is not related to the installed machine or the operating system

**Comment by ctubio** [comment]
basically api_keys are translated into bitcoin addresses. each one generates a new one, and the same api key generates the same address.

the bot just checks in the bitcoin network if the address representing the given api key was credited; otherwise bot gets locked. no matter any other condition.
