### ISSUE TITLE
Npm Start script stops after running test command

### ISSUE THREAD

**Issue by mattygug** [ctubio/Krypto-trading-bot#55]
Hey ! Nice work upgrading and maintaining the old bot !!

I have setup an EC2 instance and running the bot in a Node environment. The setup went fine but when I start running the bot it crashes after the test script

```test -z "$SKIP_STUNNEL$(ps axu | grep stunnel | grep -v grep)" && exec stunnel dist/K-stunnel.conf || :```

-> Moreover I cannot get into log files you save them under `dev/null`tried to change the folder but it wont let me
-> Hint: can it be that the EC2 instance is too small and I need to make a swap file as explained ? Sometimes it even kicks me out of the instance

Many thanks in advance

here are more logs from the terminal
```
info:    Forever processing file: K.js

> K.js@3.0.0 test-stunnel /home/ec2-user/bot
> test -z "$SKIP_STUNNEL$(ps axu | grep stunnel | grep -v grep)" && exec stunnel dist/K-stunnel.conf || :

[ec2-user@xxx bot]$ npm run list

> K.js@3.0.0 list /home/ec2-user/bot
> forever list

info:    Forever processes running
data:        uid    command             script      forever pid   id logfile   uptime  
data:    [0] K.json /usr/local/bin/node K.js K.json 21324   21461    /dev/null STOPPED 
data:    [1] K.json /usr/local/bin/node K.js K.json 21630   21645    /dev/null STOPPED 
data:    [2] K.json /usr/local/bin/node K.js K.json 21748   21763    /dev/null STOPPED 
````

**Comment by ctubio** [comment]
you are running multiple concurent failing bots; first kill all the STOPPED bots and later try to run `node K.js` or `nodejs K.js` to see the log

**Comment by mattygug** [comment]
Hey thx

Ok there was another bug when running `node` with the `dlconfig` but that one is solved see first commands...

So here are the logs with `node K.js` apparently it gets running although I cannot open the UI
at `https`+ `Server IP`+`port`

log when running node:
```
[ec2-user@ip-xxx bot]$ LD_LIBRARY_PATH=/usr/local/lib
[ec2-user@ip-xxx bot]$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
[ec2-user@ip-xxx bot]$ node K.js
K.linux.51
DB /data/db/K.0.0.82.db loaded OK
UI ready over HTTPS on external port 3000
04:57:54.884 broker Exchange details { exchange: 'Null',
  pair: 'BTC/USD',
  minTick: 0.01,
  minSize: 0.01,
  makeFee: 0,
  takeFee: 0,
  hasSelfTradePrevention: false }
04:57:54.892 tbp Loaded from DB: { data: 284.7193718969704, time: 2017-07-13T04:55:57.331Z }
04:57:55.893 stdev Unable to compute value
04:57:56.893 stdev Unable to compute value
04:57:57.893 stdev Unable to compute value
04:57:58.894 stdev Unable to compute value
04:57:59.897 tbp recalculated 275.27358556264113
04:58:04.908 tbp recalculated 275.2726497590767
```

still running it with npm leads to a shutdown on the mentioned test command before

**Comment by ctubio** [comment]
so all OK now, cool
