### ISSUE TITLE
HitBTC Filter cxl function by instance

### ISSUE THREAD

**Issue by adirta** [ctubio/Krypto-trading-bot#551]
Hello
It would be possible that the cxl function (for my necessary by zombie orders), only cancel orders in the instances that is activated? In this way, you can continue creating orders manually in other pairs without being canceled.

Thank you

**Comment by ctubio** [comment]
cxl function cancels all orders; because it attempts to kill zombies

if you dont want your manual orders to be canceled, do not enable cxl

there is no way the bot can know if a manual order is really manual or zombie, since both were created without the bot consentiment.

**Comment by adirta** [comment]
Simply that when CXL is active, the process of canceling open orders is only for the instance pair. In hitbtc, for example, you can send as a parameter the symbol to cancel https://api.hitbtc.com/#cancel-orders

Sometimes, I need to have an open order outside the bot and activated cxl is necessary.

Thank you very much for your response

**Comment by ctubio** [comment]
ah sorry i understand your requirement now; need to add filter by currency pair to cancelAll in HitBTC; okok will do soOn

many thanks for insist on this''''

**Comment by serzhiio** [comment]
That's a must for HitBTC!
Really often i need to put some manual orders but they are cancelling by the bot.
