### ISSUE TITLE
HitBTC - Quotes: 2/0/0 + No orders in order table ann web UI of exchange

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#555]
Hello!
Sorry if again.. K updated 30 min ago (after "Updated HitBTC random order ids with moar distribution to avoid dupes.")
Screens in same time:
![333](https://user-images.githubusercontent.com/33358791/34764302-1bc32158-f5ff-11e7-8d2e-bc8c3a857937.PNG)
![1111](https://user-images.githubusercontent.com/33358791/34764308-20f64e2a-f5ff-11e7-9229-b9e1c8350862.PNG)
![222](https://user-images.githubusercontent.com/33358791/34764336-33d97440-f5ff-11e7-972b-0eb000e639aa.PNG)

**Comment by donaldforest** [comment]
UPD: Not sure this is critical! I see that K start working today more better with HitBTC than last 2 days.. But I hope we need fix this strange zombie or phantom orders (if we can do that and this is not exchange trouble).

**Comment by ctubio** [comment]
this was related to https://github.com/ctubio/Krypto-trading-bot/issues/550 right?

**Comment by donaldforest** [comment]
Yes. But except data about:

> GW HITBTC Warrrrning: Ignored response: {"error":{"code":2010,"d escription ........

I have no so deep data this time. Just external factors.

**Comment by ctubio** [comment]
ok so zombies in hitbtc but without error messages. understood'¡

**Comment by donaldforest** [comment]
And still delay new orders.

**Comment by donaldforest** [comment]
Again:

> 19:16:35.728488 GW HITBTC Warrrrning: Ignored response: {"error":{"code":504,"description":"","message":"Gateway Timeout"},"id":161,"jsonrpc":"2.0"}.

**Comment by captainreptile** [comment]
I'm not sure if this is related, but on K UI i see one open order while on HitBTC i have around 10+ open orders.

I have the feeling that its updating the price of order but if K decided to cancel it its not really canceled on HItBTC side.

**Comment by captainreptile** [comment]
Other thing i noticed:
When order does trigger and goes to order history then it does multiple orders of the same - so though i had one open order, it closes in few.

Is it becouse trading account is more than bid/sell amount and it try to fill up to totall amounts?
It also could be the uncanceled orders?

**Comment by donaldforest** [comment]
@captainreptile have you some anomaly logs in this moment?

**Comment by captainreptile** [comment]
@donaldforest i have the shell screen open, is it logging in any file?

I can confirm that first time i see same error as in this thread:

 ```
21:49:43.482854 GW HITBTC Warrrrning: Ignored response: {"error":{"code":504,"description":"","message":"Gateway Timeout"},"id":16480,"jsonrpc":"2.0"}.
21:49:54.307051 GW HITBTC Warrrrning: Ignored response: {"error":{"code":504,"description":"","message":"Gateway Timeout"},"id":16481,"jsonrpc":"2.0"}
```

**Comment by captainreptile** [comment]
"cxl?"  - seems to fix the issue with zombi orders on HBTC
i also changed safety and now i also have pings and pongs, before i had only pongs (under pingpong).

**Comment by donaldforest** [comment]
Maybe you a right about "cxl?". But in my case "cxl?" delay work not always in strategy direction. ("cxl?" have some fixed delay period which reset all orders)

**Comment by captainreptile** [comment]
you are right i ticked it only to avoid having irrelevant quotes/orders on HItBTC side that K "4got" about.
it does seem to affect on strategy under certain settings.
