### ISSUE TITLE
Improvement: Updating orders whenever possible

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#558]
Hi Carles and everyone,

I was thinking, why not instead of canceling + creating a new order the bot would not rather update existing orders.

I think this would improve the speed of trading and wouldn't let the market with a few ms without an order.

When we cancel an order we have to wait for the response "order cancelled" to come to K + wait for the fund to be liberated on our account and then send a new order.

I was looking at the API and correct me if I'm wrong but I think that you can update orders in:
Bitfinex, Korbit and HitBTC.

What do you think?

Would that help to trade?

Best,

Camille

**Comment by serzhiio** [comment]
Thats a great idea, but doesnt we already use orders updating?
And also we can use FOK (Fill or kill) orders type, cant we?

**Comment by serzhiio** [comment]
May be we can get rid of #557 if implement order updating?

**Comment by Camille92** [comment]
Well I don't think Okex allows for updating orders, but I'm not a pro in API, feel free to check :)

Yes, I was thinking "why would we need FOK? :p"

**Comment by ctubio** [comment]
yea that is only allowed in some exchanges; and because is not allowed in all exchanges we are not using this functionality.

will attempt to make use of it soOn were possible cos will save one api call

thanks for insist on this'''

**Comment by Camille92** [comment]
Thanks! :D

**Comment by ctubio** [comment]
for exchanges that do not support it we can do like Bitfinex and put both msgs into a single websocket msg, but separated by a new line each msg :dancer: (multiline msgs should be supported by default because of the websocket protocol without extra application logic/endpoints; will try'¡1)

**Comment by ctubio** [comment]
for now Bitfinex is nicely done; for the rest of exchanges i will test to join the websocket messages someday :dancer:
