### ISSUE TITLE
New GDAX FIX API available 1/16/2018

### ISSUE THREAD

**Issue by SlackerATX** [ctubio/Krypto-trading-bot#559]
Valued GDAX Customer,We have made a number of reliability enhancements to our FIX API which you may now begin testing in sandbox:

- **Enforceheartbeats:** A TestRequest (35=1) message is sent if a message hasn't been sent within 45 seconds (assuming 108=30 for Logon message)

- **Gracefully logout during deploys:** A Logout (35=5) message with the text "server terminated" is sent prior to shutting down. This will address the race condition causing some orders to not be canceled on deployments if cancel on disconnect is enabled.

- **Modifiederror handling behavior:** An ExecutionReport (35=8) message is sent for errors where there is no possibility that the order was sent to the matching engine. Previous behavior was to send a Reject (35=3) message.

We intend to deploy the latest code changes next Tuesday, January 16th at 10am PT. At that time you will receive a sudden disconnect and any open orders may not be canceled.For more information on these changes, please see docs.gdax.com

**Comment by ctubio** [comment]
thanks for the info''

**Comment by ctubio** [comment]
after review seems all coOl, no need to modify existent code

thanks again'¡
