### ISSUE TITLE
UI price calculation issue

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#562]
Look at the screenshot:
![wrong-calcs](https://user-images.githubusercontent.com/10449591/34821252-2cdcb62c-f6d4-11e7-81a7-4f6d89990f1b.jpg)

**Comment by ctubio** [comment]
dont fuck me, `price * quantity` cannot be wrong

if you think a bit, you will see where is the mismatch of decimals; and if you consider it a bit, you will see how much useless is that mismatch

**Comment by ctubio** [comment]
hint: feel free to truncate decimals based on minTick to get rid of the mismatch

**Comment by ctubio** [comment]
btw, i also not like the ethernal decimals; will keep on next commits ethernal decimals only in Kdff, not in val or valPong

**Comment by serzhiio** [comment]
I've just cought this thing in Chrome. Thought that it might be some bug, who knows.
I agree with big decimals it looks ugly.
