### ISSUE TITLE
use database for settings even when --database=:memory:

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#564]
this way --database=:memory: bots don't need to restore params from backup on boot and can keep updating params as usual while still not writing to the disk in between trading cycles unless params are updated

**Comment by CarlitoGrey** [comment]
Great idea :D

**Comment by donaldforest** [comment]
Wow! Amazing!

**Comment by SlackerATX** [comment]
I started loading from memory, but I didn't see EWMA load from disk

04:51:06.469884 DB /data/db/K.COINBASE.BTC.USD.db loaded OK.
04:51:06.470320 UI ready over HTTPS on external port 3000.
04:51:06.470756 DB loaded Quoting Parameters OK.
04:51:06.470918 DB loaded 0 historical Trades.
04:51:06.476365 DB loaded 628 STDEV Periods.
04:51:06.476686 DB loaded 11271.286860 EWMA VeryLong.
04:51:06.476708 DB loaded 11433.831369 EWMA Long.
04:51:06.476716 DB loaded 11442.103409 EWMA Medium.
04:51:06.476783 DB loaded 11371.104073 EWMA Short.
04:51:06.498653 DB loaded 2800 historical FairValues.
04:51:06.530084 DB loaded 3963 historical Profits.
04:51:06.530354 DB loaded TBP = 0.00000000 BTC.
04:51:07.077121 GW COINBASE allows client IP.
04:51:07.077176 GW COINBASE: 

4:51:12.578778 DB :memory: loaded OK.
04:51:12.579160 DB /data/db/K.COINBASE.BTC.USD.db loaded OK.
04:51:12.579611 UI ready over HTTPS on external port 3000.
04:51:12.579781 DB loaded Quoting Parameters OK.
04:51:12.579982 DB loaded 0 historical Trades.
04:51:12.580089 DB loaded 0 STDEV Periods.
04:51:12.580275 DB loaded 0 historical FairValues.
04:51:12.580380 DB loaded 0 historical Profits.
04:51:12.580527 DB loaded TBP = 0.00000000 BTC.
04:51:13.030226 GW COINBASE allows client IP.
04:51:13.030278 GW COINBASE:
 
 Am I misunderstanding the intent of this feature?  I'd like to load EWMA params from disk even if using memory.

**Comment by ctubio** [comment]
when using :memory: only the Quoting parameters are persistent.

the ewma values require a warm up
