### ISSUE TITLE
HitBTC not cancelling orders

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#567]
Hey Carles,

Further to our discussion yesterday I have completely rebuilt (make clean) and upgraded to latest commit. I still see zombies on HitBTC. Here's some log:
```
09:41:36.807049 DEBUG OG  saved BID id c1429ecc5ef845a6800000f50c89f367:: [0]: 0.03000000 BTC at price 14131.01000000 USD.
09:41:36.807062 DEBUG OG  send  61744fbdbf51454480000041a69e2e4c> BID id c1429ecc5ef845a6800000f50c89f367: 0.03000000 BTC at price 14131.01000000 USD.
09:41:46.850315 DEBUG OG remove c1429ecc5ef845a6800000f50c89f367.
09:41:58.475507 DEBUG OG reply  c1429ecc5ef845a6800000f50c89f367::13144231116 [1]: 0.03000000/0.00000000 at price 0.00000000.
09:41:58.475585 DEBUG OG reply  c1429ecc5ef845a6800000f50c89f367::13144231116 [1]: 0.03000000/0.00000000 at price 0.00000000.
09:42:20.877694 DEBUG OG reply  c1429ecc5ef845a6800000f50c89f367::13144231116 [3]: 0.03000000/0.00000000 at price 0.00000000.
```
It looks like K never cancels 13144231116 . The last cancel is when I closed the bot (look at the times).

**Comment by CarlitoGrey** [comment]
(It also gets double replies still)

**Comment by ctubio** [comment]
many thanks for the logs; ima focus on this until next commit if i can reproduce it before patience goes away; but when so will just play again https://www.youtube.com/watch?v=Oc5QaJCCXeA and continue the fight

![pinya](https://user-images.githubusercontent.com/1634027/34908134-3c1f0d02-f88b-11e7-9f91-6150b73ca656.jpg)

![31733764-e79df244-b43c-11e7-9186-92b6744db290](https://user-images.githubusercontent.com/1634027/34908135-474a7806-f88b-11e7-97e4-ccb8e29bf88d.png)
