### ISSUE TITLE
Crash with Coinbase/Gdax

### ISSUE THREAD

**Issue by stephenc01** [ctubio/Krypto-trading-bot#569]
20:05:55.312708 Errrror: Signal 6 Abort trap: 6 (Three-Headed Monkey found):
- upstream: COINBASE
- currency: BTC/USD
- lastbeat: 1515873955312
- tracelog: 
0   K                                   0x000000010ef3c495 _ZN1K2EV3wtfEi + 645
1   ???                                 0x00007fb8a8c60d88 0x0 + 140431082261896

Yikes!

**Comment by ctubio** [comment]
let me guess, i feel lucky today :dancer:

this was a mac, see https://github.com/ctubio/Krypto-trading-bot/issues/136
