### ISSUE TITLE
Support for Binance, Cryptopia or Kucoin

### ISSUE THREAD

**Issue by ph3l1x** [ctubio/Krypto-trading-bot#571]
Any chance of getting support for Binance, Cryptopia or Kucoin? Those are the only exchanges I am currently on.

**Comment by ctubio** [comment]
someday maybe if more users are interested; for now you are the second; will keep this open in case

**Comment by ph3l1x** [comment]
Why nobody cares tag? lol. Binance is about to become the worlds biggest exchange. Its already the second. I dont have access to any of the supported exchanges. Bitfiniex doesn't even allow US residents.

**Comment by MiningInMySleep** [comment]
I'd be interested in Binance and Cryptopia support. Not on Kucoin yet though...

**Comment by serzhiio** [comment]
I think Binance is most interesting, others too risky.

**Comment by ctubio** [comment]
as far as i know nobody wanna make business with this exchange, seems just for fun; the tag is to note it

**Comment by cmartin81** [comment]
+1 for binance! They have a nice API and also websockets

**Comment by MiningInMySleep** [comment]
Cryptopia has a lot of new coins - some of which no other exchanges have so I'd argue on that alone that it would be a worthwhile effort to include support for them should they prove reliable.
I haven't heard a single bad thing about Binance and from what I've seen the platform and UI seems very streamlined, smooth, and responsive.
If I had to pick between the two, I'd say Cryptopia just because of the vast market coverage they have.

**Comment by flfsbr** [comment]
I agree. Cryptopia has a vast market coverage.
It is interesting support cryptopia.

**Comment by ctubio** [comment]
thanks for the fun'' will close this soOn if nobody cares to support the development

(if nobody cares to support the whole initial integration, i believe less support will have in the future the maintenance; so better to not start losing time)

**Comment by ctubio** [comment]
someday maybe

**Comment by aviggiano** [comment]
Hello,

I am thinking about adding support for Kucoin, would you be interested in a pull request?

**Comment by ctubio** [comment]
@aviggiano im sorry PR are not possible cos the apis are still private, someday will be public, but im not ready yet :(
