### ISSUE TITLE
Okex 2-4+ similar orders at the same time

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#572]
Latest commit 9d6be4e  13 hours ago
Like AK-46, but as you can see by buttons amount safety is off:

![okex](https://user-images.githubusercontent.com/33358791/34916291-ebf2d73e-f946-11e7-9ed0-2280686b4652.PNG)

**Comment by ctubio** [comment]
last commit should have fixed okex too as well as hitbtc
