### ISSUE TITLE
Need help with bug smashing

### ISSUE THREAD

**Issue by woshikie** [ctubio/Krypto-trading-bot#574]
Since @ctubio has closed #560 but I am still facing the bug, I attempted to try to find a fix but I couldn't find any usage of argFree in any of the server files nor could i find any declaration for Gw::config 😕

**Comment by ctubio** [comment]
i think you are looking for the private codes im sorry, the only public part of Gw (and related XMR miner code in the server) is declared at https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/km.h#L570 but is defined in the private lib build-*/local/lib/K*.a

**Comment by ctubio** [comment]
if you give me a link or the exact steps to build your vm where is failing i can try to reproduce it

**Comment by ctubio** [comment]
lets reopen the other issue then
