### ISSUE TITLE
Raspberry Pi Zero W Illegal instruction 

### ISSUE THREAD

**Issue by evilsperm** [ctubio/Krypto-trading-bot#575]
After make install it build with no errors, running ./K.sh 
immediately returns: 
Illegal instruction K crashed with exit code 132.. Respawning..

**Comment by ctubio** [comment]
thanks for the report'' sorry long time i dont test a raspberry, will do soOn''

**Comment by evilsperm** [comment]
exchange = gdax 
uname -a = Linux raspberrypi 4.9.59+ #1047 Sun Oct 29 11:47:10 GMT 2017 armv6l GNU/Linux

**Comment by ctubio** [comment]
the arm-linux-gnueabihf compilation is for armv7l machines; and i do not own any Pi Zero to test this

consider to use some armv7l OS to fix this
