### ISSUE TITLE
Raspberry Pi 3 / Bitfinex M - Wrong exchangeId + Not funded orders

### ISSUE THREAD

**Issue by 5ymph0en1x** [ctubio/Krypto-trading-bot#576]
Hi everyone !

I'm trying to make Krypto Bot work on **Raspbian Stretch** with "Bitfinex Margin" but I'm facing an issue concerning the **exchangeId** number which comes out **negative** in the debug report. The consequence is that Bitfinex doesn't retrieve the order for cancelling (Order not found) and Krypto keeps piling stop orders but doesn't keep track of them in the web interface. It even tries to open orders with insufficient funds...

I've compiled everything (make packages + make dist + make) but it doesn't change anything.

The Id tracking works on a fresh Debian 9 install even if the insufficient funds problem persists...

No problem with HitBTC and Raspbian.

Kind regards

PS : Thanks for this amazing piece of software !

**Comment by ctubio** [comment]
thanks for the info'' lets solve this at https://github.com/ctubio/Krypto-trading-bot/issues/527 im currently looking to fix this
