### ISSUE TITLE
Poloniex error message

### ISSUE THREAD

**Issue by lee101** [ctubio/Krypto-trading-bot#577]
Not sure why the bot couldnt connect to poloniex i got this error
08:16:47.324180 DB /data/db/K.POLONIEX.BTC.USD.db loaded OK.
08:16:47.324691 UI ready over HTTPS on external port 3000.
08:16:47.325107 QP Warrrrning: using default values for Quoting Parameters.
08:16:47.325200 DB loaded 0 historical Trades.
08:16:47.325300 DB loaded 0 STDEV Periods.
08:16:47.325449 DB loaded 0 historical FairValues.
08:16:47.325527 DB loaded 0 historical Profits.
08:16:47.325628 DB loaded TBP = 0.00000000 BTC.
08:16:47.624053 CF Errrror: Unable to fetch data from POLONIEX for symbol "BTC_USD", possible error message: {"BTC_AMP":{"baseVolume":"42.87686362","high24hr":"0.00006799","highestBid":"0.00005426","id":160,"isFrozen":"0","last":"0.00005457","low24hr":"0.00005400","lowestAsk":"0.00005454","percentChange":"-0.19537009","quoteVolume":"699263.87156631"},"BTC_ARDR":{"baseVolume":"57.97711822","high24hr":"0.00011489","highestBid":"0.00010801","id":177,"isFrozen":"0","last":"0.00010801","low24hr":"0.00010200","lowestAsk":"0.00010824","percentChange":"-0.00944607","quoteVolume":"536241.23625330"},"BTC_BCH":{"baseVolume":"1882.50160920","high24hr":"0.18350000","highestBid":"0.16600008","id":189,"isFrozen":"0","last":"0.16664989","low24hr":"0.16600000","lowestAsk":"0.16649799","percentChange":"-0.09182576","quoteVolume":"10776.33319437"},"BTC_BCN":{"baseVolume":"238.54823996","high24hr":"0.00000076","highestBid":"0.00000062","id":7,"isFrozen":"0","last":"0.00000062","low24hr":"0.00000062","lowestAsk":"0.00000063","percentChange":"-0.18421052","quoteVolume":"344901801.33326256"},"BTC_BCY":{"baseVolume":"67.25248367","high24hr":"0.00012450","highestBid":"0.00009500","id":151,"isFrozen":"0","last":"0.00009568","low24hr":"0.00009356","lowestAsk":"0.00009568","percentChange":"-0.14265232","quoteVolume":"611166.91954202"},"BTC_BELA":{"baseVolume":"25.73457684","high24hr":"0.00003422","highestBid":"0.00002857","id":8,"isFrozen":"0","last":"0.00002861","low24hr":"0.00002824","lowestAsk":"0.00002861","percentChange":"-0.14341317","quoteVolume":"816574.05826560"},"BTC_BLK":{"baseVolume":"27.65789815","high24hr":"0.00006452","highestBid":"0.00005609","id":10,"isFrozen":"0","last":"0.00005689","low24hr":"0.00005510","lowestAsk":"0.00005687","percentChange":"-0.11413889","quoteVolume":"461984.42918487"},"BTC_BTCD":{"baseVolume":"14.89584042","high24hr":"0.01834999","highestBid":"0.01621633","id":12,"isFrozen":"0","last":"0.01621633","low24hr":"0.01610000","lowestAsk":"0.01630963","percentChange":"-0.09475312","quoteVolume":"881.21950820"},"BTC_BTM":{"baseVolume":"2.88735257","high24hr":"0.00021902","highestBid":"0.00018522","id":13,"isFrozen":"0","last":"0.00018581","low24hr":"0.00018600","lowestAsk":"0.00018581","percentChange":"-0.13464046","quoteVolume":"14541.17668775"},"BTC_BTS":{"baseVolume":"647.96197289","high24hr":"0.00003934","highestBid":"0.00003194","id":14,"isFrozen":"0","last":"0.00003194","low24hr":"0.00003181","lowestAsk":"0.00003195","percentChange":"-0.15143464","quoteVolume":"17892951.88126828"},"BTC_BURST":{"baseVolume":"115.04506514","high24hr":"0.00000580","highestBid":"0.00000461","id":15,"isFrozen":"0","last":"0.00000462","low24hr":"0.00000460","lowestAsk":"0.00000462","percentChange":"-0.15693430","quoteVolume":"21940884.86935200"},"BTC_CLAM":{"baseVolume":"28.50314847","high24hr":"0.00083856","highestBid":"0.00074620","id":20,"isFrozen":"0","last":"0.00074687","low24hr":"0.00074687","lowestAsk":"0.00074687","percentChange":"-0.08779236","quoteVolume":"36047.60626920"},"BTC_CVC":{"baseVolume":"80.86130760","high24hr":"0.00007950","highestBid":"0.00006454","id":194,"isFrozen":"0","last":"0.00006528","low24hr":"0.00006447","lowestAsk":"0.00006528","percentChange":"-0.14431773","quoteVolume":"1122862.10707986"},"BTC_DASH":{"baseVolume":"852.08564643","high24hr":"0.07479500","highestBid":"0.06770000","id":24,"isFrozen":"0","last":"0.06793503","low24hr":"0.06586792","lowestAsk":"0.06793498","percentChange":"-0.08653735","quoteVolume":"12315.71951995"},"BTC_DCR":{"baseVolume":"124.37643855","high24hr":"0.00811706","highestBid":"0.00730089","id":162,"isFrozen":"0","last":"0.00730088","low24hr":"0.00730000","lowestAsk":"0.00739658","percentChange":"-0.07342653","quoteVolume":"16099.41703728"},"BTC_DGB":{"baseVolume":"814.24872514","high24hr":"0.00000681","highestBid":"0.00000533","id":25,"isFrozen":"0","last":"0.00000532","low24hr":"0.00000533","lowestAsk":"0.00000542","percentChange":"-0.21764705","quoteVolume":"133107399.53392546"},"BTC_DOGE":{"baseVolume":"1532.33328303","high24hr":"0.00000083","highestBid":"0.00000066","id":27,"isFrozen":"0","last":"0.00000067","low24hr":"0.00000065","lowestAsk":"0.00000067","percentChange":"-0.18292682","quoteVolume":"2101231014.35486650"},"BTC_EMC2":{"baseVolume":"74.98495606","high24hr":"0.00005865","highestBid":"0.00005080","id":28,"isFrozen":"0","last":"0.00005078","low24hr":"0.00005075","lowestAsk":"0.00005145","percentChange":"-0.13181740","quoteVolume":"1366301.29706836"},"BTC_ETC":{"baseVolume":"1732.27895322","high24hr":"0.00318300","highestBid":"0.00281261","id":171,"isFrozen":"0","last":"0.00281261","low24hr":"0.00279000","lowestAsk":"0.00281994","percentChange":"-0.08999110","quoteVolume":"587841.31098114"},"BTC_ETH":{"baseVolume":"9206.46522508","high24hr":"0.09760000","highestBid":"0.09215381","id":148,"isFrozen":"0","last":"0.09235700","low24hr":"0.09104631","lowestAsk":"0.09235696","percentChange":"-0.04915687","quoteVolume":"98045.09055256"},"BTC_EXP":{"baseVolume":"57.27882577","high24hr":"0.00059999","highestBid":"0.00047500","id":153,"isFrozen":"0","last":"0.00047564","low24hr":"0.00047500","lowestAsk":"0.00047564","percentChange":"-0.12633628","quoteVolume":"104900.49818190"},"BTC_FCT":{"baseVolume":"558.06040738","high24hr":"0.00474298","highestBid":"0.00392802","id":155,"isFrozen":"0","last":"0.00392803","low24hr":"0.00390101","lowestAsk":"0.00392803","percentChange":"-0.16603397","quoteVolume":"131254.82279734"},"BTC_FLDC":{"baseVolume":"31.42052218","high24hr":"0.00000464","highestBid":"0.00000361","id":31,"isFrozen":"0","last":"0.00000362","low24hr":"0.00000360","lowestAsk":"0.00000363","percentChange":"-0.20614035","quoteVolume":"7806915.58589085"},"BTC_FLO":{"baseVolume":"20.16910188","high24hr":"0.00002155","highestBid":"0.00001823","id":32,"isFrozen":"0","last":"0.00001840","low24hr":"0.00001832","lowestAsk":"0.00001839","percentChange":"-0.06026557","quoteVolume":"1023256.15508593"},"BTC_GAME":{"baseVolume":"219.24148766","high24hr":"0.00048120","highestBid":"0.00040355","id":38,"isFrozen":"0","last":"0.00040987","low24hr":"0.00038432","lowestAsk":"0.00040987","percentChange":"-0.04959884","quoteVolume":"501210.83422621"},"BTC_GAS":{"baseVolume":"800.77679902","high24hr":"0.00700000","highestBid":"0.00658500","id":198,"isFrozen":"0","last":"0.00658413","low24hr":"0.00475470","lowestAsk":"0.00659362","percentChange":"0.26727308","quoteVolume":"132362.25131788"},"BTC_GNO":{"baseVolume":"92.06382317","high24hr":"0.02497187","highestBid":"0.01930126","id":187,"isFrozen":"0","last":"0.01934231","low24hr":"0.01917341","lowestAsk":"0.01934231","percentChange":"-0.20753116","quoteVolume":"4095.51499676"},"BTC_GNT":{"baseVolume":"255.56959741","high24hr":"0.00007333","highestBid":"0.00006126","id":185,"isFrozen":"0","last":"0.00006124","low24hr":"0.00006126","lowestAsk":"0.00006170","percentChange":"-0.14588563","quoteVolume":"3716451.12153012"},"BTC_GRC":{"baseVolume":"26.00722249","high24hr":"0.00001179","highestBid":"0.00000953","id":40,"isFrozen":"0","last":"0.00000953","low24hr":"0.00000949","lowestAsk":"0.00000959","percentChange":"-0.18962585","quoteVolume":"2445831.40481124"},"BTC_HUC":{"baseVolume":"9.38919944","high24hr":"0.00003349","highestBid":"0.00002587","id":43,"isFrozen":"0","last":"0.00002600","low24hr":"0.00002580","lowestAsk":"0.00002600","percentChange":"-0.18084436","quoteVolume":"311899.72637182"},"BTC_LBC":{"baseVolume":"116.51832311","high24hr":"0.00008122","highestBid":"0.00007220","id":167,"isFrozen":"0","last":"0.00007219","low24hr":"0.00007218","lowestAsk":"0.00007280","percentChange":"-0.10622755","quoteVolume":"1503480.59388188"},"BTC_LSK":{"baseVolume":"601.33348756","high24hr":"0.00213381","highestBid":"0.00184094","id":163,"isFrozen":"0","last":"0.00185335","low24hr":"0.00181000","lowestAsk":"0.00185335","percentChange":"-0.11065097","quoteVolume":"304859.62870800"},"BTC_LTC":{"baseVolume":"1190.70656241","high24hr":"0.01741000","highestBid":"0.01683000","id":50,"isFrozen":"0","last":"0.01685010","low24hr":"0.01684200","lowestAsk":"0.01687197","percentChange":"-0.02856016","quoteVolume":"69626.93613311"},"BTC_MAID":{"baseVolume":"228.03248985","high24hr":"0.00007950","highestBid":"0.00007390","id":51,"isFrozen":"0","last":"0.00007388","low24hr":"0.00007060","lowestAsk":"0.00007400","percentChange":"0.00040622","quoteVolume":"3044200.52681228"},"BTC_NAV":{"baseVolume":"74.14459477","high24hr":"0.00032418","highestBid":"0.00029035","id":61,"isFrozen":"0","last":"0.00029569","low24hr":"0.00027489","lowestAsk":"0.00029561","percentChange":"-0.05828211","quoteVolume":"250570.14215898"},"BTC_NEOS":{"baseVolume":"36.58546590","high24hr":"0.00100533","highestBid":"0.00086085","id":63,"isFrozen":"0","last":"0.00086080","low24hr":"0.00086007","lowestAsk":"0.00087915","percentChange":"-0.14272340","quoteVolume":"39592.71036940"},"BTC_NMC":{"baseVolume":"25.11575248","high24hr":"0.00049452","highestBid":"0.00039458","id":64,"isFrozen":"0","last":"0.00040632","low24hr":"0.00037501","lowestAsk":"0.00040584","percentChange":"-0.16300339","quoteVolume":"59121.76688521"},"BTC_NXC":{"baseVolume":"37.76404851","high24hr":"0.00005100","highestBid":"0.00004600","id":183,"isFrozen":"0","last":"0.00004603","low24hr":"0.00004226","lowestAsk":"0.00004604","percentChange":"-0.03642453","quoteVolume":"788938.45875903"},"BTC_NXT":{"baseVolume":"189.07879041","high24hr":"0.00003184","highestBid":"0.00002912","id":69,"isFrozen":"0","last":"0.00002912","low24hr":"0.00002908","lowestAsk":"0.00002918","percentChange":"-0.06064516","quoteVolume":"6232296.16160374"},"BTC_OMG":{"baseVolume":"300.45800014","high24hr":"0.00175100","highestBid":"0.00154201","id":196,"isFrozen":"0","last":"0.00154201","low24hr":"0.00154725","lowestAsk":"0.00154587","percentChange":"-0.11847363","quoteVolume":"183507.86365545"},"BTC_OMNI":{"baseVolume":"28.69057334","high24hr":"0.00630001","highestBid":"0.00504033","id":58,"isFrozen":"0","last":"0.00504015","low24hr":"0.00490000","lowestAsk":"0.00511042","percentChange":"-0.18646242","quoteVolume":"5194.93171504"},"BTC_PASC":{"baseVolume":"79.59565124","high24hr":"0.00033056","highestBid":"0.00027650","id":184,"isFrozen":"0","last":"0.00027626","low24hr":"0.00027623","lowestAsk":"0.00027681","percentChange":"-0.09452638","quoteVolume":"270613.94818215"},"BTC_PINK":{"baseVolume":"22.89350445","high24hr":"0.00000531","highestBid":"0.00000400","id":73,"isFrozen":"0","last":"0.00000400","low24hr":"0.00000400","lowestAsk":"0.00000407","percentChange":"-0.20318725","quoteVolume":"5100456.05728991"},"BTC_POT":{"baseVolume":"23.81529421","high24hr":"0.00002381","highestBid":"0.00002070","id":74,"isFrozen":"0","last":"0.00002073","low24hr":"0.00002073","lowestAsk":"0.00002073","percentChange":"-0.11862244","quoteVolume":"1080965.43416210"},"BTC_PPC":{"baseVolume":"26.64074659","high24hr":"0.00060113","highestBid":"0.00050054","id":75,"isFrozen":"0","last":"0.00050053","low24hr":"0.00049740","lowestAsk":"0.00051426","percentChange":"-0.16735148","quoteVolume":"49248.07689794"},"BTC_RADS":{"baseVolume":"33.38041761","high24hr":"0.00103955","highestBid":"0.00089130","id":158,"isFrozen":"0","last":"0.00089130","low24hr":"0.00088568","lowestAsk":"0.00089353","percentChange":"-0.13289230","quoteVolume":"35303.21855219"},"BTC_REP":{"baseVolume":"207.73417448","high24hr":"0.00707002","highestBid":"0.00614660","id":174,"isFrozen":"0","last":"0.00614660","low24hr":"0.00612966","lowestAsk":"0.00621274","percentChange":"-0.12496067","quoteVolume":"31833.20805443"},"BTC_RIC":{"baseVolume":"51.24268023","high24hr":"0.00003778","highestBid":"0.00002756","id":83,"isFrozen":"0","last":"0.00002793","low24hr":"0.00002750","lowestAsk":"0.00002793","percentChange":"-0.12582159","quoteVolume":"1594866.71333522"},"BTC_SBD":{"baseVolume":"20.78071724","high24hr":"0.00045968","highestBid":"0.00039000","id":170,"isFrozen":"0","last":"0.00039001","low24hr":"0.00039000","lowestAsk":"0.00039001","percentChange":"-0.12260691","quoteVolume":"47902.25111703"},"BTC_SC":{"baseVolume":"888.37087652","high24hr":"0.00000428","highestBid":"0.00000332","id":150,"isFrozen":"0","last":"0.00000338","low24hr":"0.00000326","lowestAsk":"0.00000339","percentChange":"-0.20470588","quoteVolume":"238004055.38386413"},"BTC_STEEM":{"baseVolume":"253.85774082","high24hr":"0.00042681","highestBid":"0.00034682","id":168,"isFrozen":"0","last":"0.00035009","low24hr":"0.00034385","lowestAsk":"0.00035009","percentChange":"-0.16797775","quoteVolume":"659230.87818375"},"BTC_STORJ":{"baseVolume":"67.13109819","high24hr":"0.00014749","highestBid":"0.00012001","id":200,"isFrozen":"0","last":"0.00012092","low24hr":"0.00012000","lowestAsk":"0.00012092","percentChange":"-0.16283577","quoteVolume":"492706.20948020"},"BTC_STR":{"baseVolume":"2159.25790246","high24hr":"0.00004726","highestBid":"0.00004026","id":89,"isFrozen":"0","last":"0.00004028","low24hr":"0.00004000","lowestAsk":"0.00004027","percentChange":"-0.13432194","quoteVolume":"49249594.58531650"},"BTC_STRAT":{"baseVolume":"837.37955448","high24hr":"0.00160797","highestBid":"0.00136025","id":182,"isFrozen":"0","last":"0.00136025","low24hr":"0.00135301","lowestAsk":"0.00136528","percentChange":"-0.11585960","quoteVolume":"559670.63398731"},"BTC_SYS":{"baseVolume":"101.23674042","high24hr":"0.00006561","highestBid":"0.00005681","id":92,"isFrozen":"0","last":"0.00005683","low24hr":"0.00005684","lowestAsk":"0.00005684","percentChange":"-0.10994518","quoteVolume":"1665847.93736714"},"BTC_VIA":{"baseVolume":"59.69286280","high24hr":"0.00047692","highestBid":"0.00040589","id":97,"isFrozen":"0","last":"0.00041000","low24hr":"0.00040583","lowestAsk":"0.00041000","percentChange":"-0.13212819","quoteVolume":"138951.86347728"},"BTC_VRC":{"baseVolume":"44.25016692","high24hr":"0.00014231","highestBid":"0.00011603","id":99,"isFrozen":"0","last":"0.00011602","low24hr":"0.00011636","lowestAsk":"0.00011672","percentChange":"-0.15270576","quoteVolume":"339489.54418747"},"BTC_VTC":{"baseVolume":"146.56923309","high24hr":"0.00043558","highestBid":"0.00038733","id":100,"isFrozen":"0","last":"0.00038876","low24hr":"0.00038001","lowestAsk":"0.00038860","percentChange":"-0.09244560","quoteVolume":"362032.32950872"},"BTC_XBC":{"baseVolume":"22.22554684","high24hr":"0.01153999","highestBid":"0.00908271","id":104,"isFrozen":"0","last":"0.00909906","low24hr":"0.00909906","lowestAsk":"0.00909868","percentChange":"-0.18008463","quoteVolume":"2156.01500799"},"BTC_XCP":{"baseVolume":"146.49750817","high24hr":"0.00475143","highestBid":"0.00406000","id":108,"isFrozen":"0","last":"0.00401325","low24hr":"0.00370000","lowestAsk":"0.00406999","percentChange":"-0.07623732","quoteVolume":"36161.09425717"},"BTC_XEM":{"baseVolume":"1247.00774020","high24hr":"0.00010477","highestBid":"0.00008208","id":112,"isFrozen":"0","last":"0.00008208","low24hr":"0.00007628","lowestAsk":"0.00008230","percentChange":"-0.19529411","quoteVolume":"13280372.72527828"},"BTC_XMR":{"baseVolume":"3201.48389972","high24hr":"0.03189009","highestBid":"0.02980025","id":114,"isFrozen":"0","last":"0.02980080","low24hr":"0.02880001","lowestAsk":"0.02980080","percentChange":"0.00859994","quoteVolume":"105145.40794639"},"BTC_XPM":{"baseVolume":"15.34909394","high24hr":"0.00008303","highestBid":"0.00007140","id":116,"isFrozen":"0","last":"0.00007140","low24hr":"0.00007009","lowestAsk":"0.00007199","percentChange":"-0.11742892","quoteVolume":"197929.62733694"},"BTC_XRP":{"baseVolume":"8273.04314963","high24hr":"0.00013451","highestBid":"0.00011383","id":117,"isFrozen":"0","last":"0.00011490","low24hr":"0.00011206","lowestAsk":"0.00011490","percentChange":"-0.14508928","quoteVolume":"67567660.17581888"},"BTC_XVC":{"baseVolume":"39.05783654","high24hr":"0.00008801","highestBid":"0.00006804","id":98,"isFrozen":"0","last":"0.00006803","low24hr":"0.00006700","lowestAsk":"0.00006887","percentChange":"-0.19936448","quoteVolume":"503203.44677696"},"BTC_ZEC":{"baseVolume":"872.83461085","high24hr":"0.05259580","highestBid":"0.04660500","id":178,"isFrozen":"0","last":"0.04660500","low24hr":"0.04461620","lowestAsk":"0.04660502","percentChange":"-0.02667054","quoteVolume":"18266.71954241"},"BTC_ZRX":{"baseVolume":"586.22419378","high24hr":"0.00015252","highestBid":"0.00011132","id":192,"isFrozen":"0","last":"0.00011131","low24hr":"0.00011110","lowestAsk":"0.00011269","percentChange":"-0.26528052","quoteVolume":"4654698.28788504"},"ETH_BCH":{"baseVolume":"2318.70497108","high24hr":"1.90950165","highestBid":"1.80000000","id":190,"isFrozen":"0","last":"1.80000000","low24hr":"1.79018004","lowestAsk":"1.80500000","percentChange":"-0.04178348","quoteVolume":"1236.68058997"},"ETH_CVC":{"baseVolume":"153.82919770","high24hr":"0.00082536","highestBid":"0.00070404","id":195,"isFrozen":"0","last":"0.00070467","low24hr":"0.00070404","lowestAsk":"0.00071246","percentChange":"-0.09441745","quoteVolume":"191528.22146916"},"ETH_ETC":{"baseVolume":"423.42840590","high24hr":"0.03310698","highestBid":"0.03043094","id":172,"isFrozen":"0","last":"0.03071147","low24hr":"0.02977837","lowestAsk":"0.03083067","percentChange":"-0.03609707","quoteVolume":"13498.71032935"},"ETH_GAS":{"baseVolume":"811.25095598","high24hr":"0.07400000","highestBid":"0.06946187","id":199,"isFrozen":"0","last":"0.06920502","low24hr":"0.05132091","lowestAsk":"0.07118084","percentChange":"0.28157444","quoteVolume":"12506.78912117"},"ETH_GNO":{"baseVolume":"224.21799050","high24hr":"0.26214329","highestBid":"0.20775382","id":188,"isFrozen":"0","last":"0.20775382","low24hr":"0.20775382","lowestAsk":"0.21674421","percentChange":"-0.18164899","quoteVolume":"935.22303294"},"ETH_GNT":{"baseVolume":"383.71594297","high24hr":"0.00078014","highestBid":"0.00067426","id":186,"isFrozen":"0","last":"0.00067426","low24hr":"0.00067000","lowestAsk":"0.00068060","percentChange":"-0.08899787","quoteVolume":"516918.56476293"},"ETH_LSK":{"baseVolume":"134.62302061","high24hr":"0.02256378","highestBid":"0.02007102","id":166,"isFrozen":"0","last":"0.02004181","low24hr":"0.01980000","lowestAsk":"0.02027172","percentChange":"-0.06782279","quoteVolume":"6316.89539317"},"ETH_OMG":{"baseVolume":"246.94241371","high24hr":"0.01806925","highestBid":"0.01685707","id":197,"isFrozen":"0","last":"0.01689167","low24hr":"0.01675000","lowestAsk":"0.01710408","percentChange":"-0.05537769","quoteVolume":"14126.49305427"},"ETH_REP":{"baseVolume":"160.35759196","high24hr":"0.07312014","highestBid":"0.06700000","id":176,"isFrozen":"0","last":"0.06700000","low24hr":"0.06533000","lowestAsk":"0.06818187","percentChange":"-0.07317965","quoteVolume":"2312.09011172"},"ETH_STEEM":{"baseVolume":"107.42418883","high24hr":"0.00449019","highestBid":"0.00377577","id":169,"isFrozen":"0","last":"0.00379768","low24hr":"0.00378491","lowestAsk":"0.00379805","percentChange":"-0.12092165","quoteVolume":"25442.48553492"},"ETH_ZEC":{"baseVolume":"367.98667773","high24hr":"0.56135192","highestBid":"0.50251048","id":179,"isFrozen":"0","last":"0.50682910","low24hr":"0.47121668","lowestAsk":"0.50682910","percentChange":"0.02369925","quoteVolume":"706.49606475"},"ETH_ZRX":{"baseVolume":"1513.98991871","high24hr":"0.00157758","highestBid":"0.00120641","id":193,"isFrozen":"0","last":"0.00120846","low24hr":"0.00120212","lowestAsk":"0.00123398","percentChange":"-0.23397862","quoteVolume":"1134280.28368230"},"USDT_BCH":{"baseVolume":"14013700.27697326","high24hr":"2509.62244465","highestBid":"2003.17585712","id":191,"isFrozen":"0","last":"2032.59999988","low24hr":"2000.41900780","lowestAsk":"2032.59999984","percentChange":"-0.19007737","quoteVolume":"6148.56429564"},"USDT_BTC":{"baseVolume":"88144692.89519081","high24hr":"14300.00000000","highestBid":"12101.39999952","id":121,"isFrozen":"0","last":"12149.99999933","low24hr":"11980.00000000","lowestAsk":"12149.99999933","percentChange":"-0.10952050","quoteVolume":"6620.21673893"},"USDT_DASH":{"baseVolume":"3227324.89416591","high24hr":"1030.00000001","highestBid":"816.37075600","id":122,"isFrozen":"0","last":"819.00000000","low24hr":"816.54735793","lowestAsk":"819.00000000","percentChange":"-0.19230689","quoteVolume":"3523.49933168"},"USDT_ETC":{"baseVolume":"9189358.71881872","high24hr":"43.89999998","highestBid":"34.13559200","id":173,"isFrozen":"0","last":"33.75000043","low24hr":"33.24238155","lowestAsk":"34.14880800","percentChange":"-0.19912788","quoteVolume":"236075.92728736"},"USDT_ETH":{"baseVolume":"25527131.91800166","high24hr":"1332.00000000","highestBid":"1120.92512665","id":149,"isFrozen":"0","last":"1126.55791607","low24hr":"1105.61038527","lowestAsk":"1126.55791606","percentChange":"-0.14848755","quoteVolume":"20554.97367787"},"USDT_LTC":{"baseVolume":"4847325.08994183","high24hr":"244.50000000","highestBid":"203.09036817","id":123,"isFrozen":"0","last":"203.09036813","low24hr":"201.72368330","lowestAsk":"204.61762738","percentChange":"-0.14214357","quoteVolume":"21533.72003080"},"USDT_NXT":{"baseVolume":"1694373.07115733","high24hr":"0.44261520","highestBid":"0.34862272","id":124,"isFrozen":"0","last":"0.35599999","low24hr":"0.33527200","lowestAsk":"0.35599989","percentChange":"-0.15385970","quoteVolume":"4217514.55380240"},"USDT_REP":{"baseVolume":"1116431.53301679","high24hr":"97.65736083","highestBid":"75.00000000","id":175,"isFrozen":"0","last":"75.00000000","low24hr":"75.00000000","lowestAsk":"75.00030088","percentChange":"-0.21515279","quoteVolume":"12977.04632080"},"USDT_STR":{"baseVolume":"8591932.47740388","high24hr":"0.67400000","highestBid":"0.47991859","id":125,"isFrozen":"0","last":"0.47991858","low24hr":"0.47600001","lowestAsk":"0.49124003","percentChange":"-0.24387087","quoteVolume":"14897021.74728889"},"USDT_XMR":{"baseVolume":"5143894.55481719","high24hr":"436.75408661","highestBid":"357.96962614","id":126,"isFrozen":"0","last":"357.96962614","low24hr":"357.53693715","lowestAsk":"361.99999970","percentChange":"-0.11363368","quoteVolume":"12654.65022902"},"USDT_XRP":{"baseVolume":"23884534.35891994","high24hr":"1.84315047","highestBid":"1.39192501","id":127,"isFrozen":"0","last":"1.39703780","low24hr":"1.35787979","lowestAsk":"1.39969723","percentChange":"-0.24021462","quoteVolume":"14960153.17033516"},"USDT_ZEC":{"baseVolume":"5189819.46487413","high24hr":"685.01000000","highestBid":"562.00000001","id":180,"isFrozen":"0","last":"562.00000000","low24hr":"559.00000000","lowestAsk":"565.00000000","percentChange":"-0.13912742","quoteVolume":"8460.18231615"},"XMR_BCN":{"baseVolume":"25.61491835","high24hr":"0.00002592","highestBid":"0.00002078","id":129,"isFrozen":"0","last":"0.00002083","low24hr":"0.00002077","lowestAsk":"0.00002131","percentChange":"-0.20038387","quoteVolume":"1134897.75995394"},"XMR_BLK":{"baseVolume":"30.48642985","high24hr":"0.00224959","highestBid":"0.00183859","id":130,"isFrozen":"0","last":"0.00183829","low24hr":"0.00157224","lowestAsk":"0.00191279","percentChange":"-0.15336505","quoteVolume":"15531.78759606"},"XMR_BTCD":{"baseVolume":"53.55026027","high24hr":"0.63347835","highestBid":"0.53471232","id":131,"isFrozen":"0","last":"0.53103595","low24hr":"0.51854358","lowestAsk":"0.55108840","percentChange":"-0.14264745","quoteVolume":"98.57847758"},"XMR_DASH":{"baseVolume":"477.88091983","high24hr":"2.52665117","highestBid":"2.21948295","id":132,"isFrozen":"0","last":"2.26737414","low24hr":"2.17248000","lowestAsk":"2.28025184","percentChange":"-0.10223803","quoteVolume":"207.78279430"},"XMR_LTC":{"baseVolume":"1009.66425388","high24hr":"0.60217271","highestBid":"0.55801550","id":137,"isFrozen":"0","last":"0.56344168","low24hr":"0.53884208","lowestAsk":"0.56591540","percentChange":"-0.03802887","quoteVolume":"1793.99348085"},"XMR_MAID":{"baseVolume":"38.60265449","high24hr":"0.00258281","highestBid":"0.00241903","id":138,"isFrozen":"0","last":"0.00246177","low24hr":"0.00232327","lowestAsk":"0.00246893","percentChange":"-0.02953455","quoteVolume":"16170.98946335"},"XMR_NXT":{"baseVolume":"74.76514177","high24hr":"0.00106794","highestBid":"0.00095235","id":140,"isFrozen":"0","last":"0.00095227","low24hr":"0.00092920","lowestAsk":"0.00097958","percentChange":"-0.08818713","quoteVolume":"75339.28132285"},"XMR_ZEC":{"baseVolume":"1044.51675650","high24hr":"1.74306146","highestBid":"1.54104790","id":181,"isFrozen":"0","last":"1.57082986","low24hr":"1.47080899","lowestAsk":"1.57544532","percentChange":"-0.03392997","quoteVolume":"666.72730661"}}.
K crashed with exit code 1.. Respawning..

**Comment by ctubio** [comment]
thanks for the report'' im sorry i have more fun priorities than to maintain Poloniex

**Comment by ctubio** [comment]
btw USD does not exists on poloniex, is USDT

**Comment by ctubio** [comment]
lets close this since #486 is more accurate
