### ISSUE TITLE
Improvement: choosing number of decimals?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#580]
Hi Carles and everyone,

Now that everything is truncated with 2 decimals, I have many markets where I can't really look at the data to know what the bot has done because of price = 0.00 ...

Also, I understand that for people trading in BTC/USD or ETH/USD having many decimals is annoying.
![capture d ecran 2018-01-17 a 10 22 43](https://user-images.githubusercontent.com/6861590/35035119-9e5303a6-fb70-11e7-9410-df65a587dd3f.png)

So here are my 2 propositions to fix that problem and make everyone happy:

1) Converting all prices to a "123.45" scheme. So artificially multiplying or dividing price in the web UI so they are easily comparable. And obviously, add the info on how much prices are multiplicated or divided using the scientific writing.
Ie: 10^-2: Prices are divided by 100
10^5 Prices are multiplicated by 100000

2) The second idea, keeping it "as if" but adding an option to chose the number of decimals somewhere next to K memory and profit. Where the number you put is the number of decimals after 0.
So if you put 3 prices are going to be displayed with a price precision of 1/1000 or 0.001.
If you put 6 prices are going to be displayed with a price precision of 1/1000000 or 0.000001

Tell me what you think about that!

And good luck in this time of complicated trading :)

**Comment by ctubio** [comment]
thanks for the suggestions''' will decide for one soOn''

**Comment by ctubio** [comment]
what about using the same amount of decimals as in the price of the market levels?

**Comment by Camille92** [comment]
Sounds good and easy to me!
Actually it sound more logical than what I proposed haha !

#veryfastreply

**Comment by ctubio** [comment]
sorry in what exchange/pairs you saw 0.00 prices?
thanks for the info''

**Comment by Camille92** [comment]
So in Bitfinex,

USD pairs: FUN and TNB with only 1 digit (0.01)
BTC pairs: 0.00 for ETC, XRP, IOTA,  EOS, SAN, OMG, ETP, QTM, AVT, EDO, DAT, QSH, YYW, GNT, SNT, BAT, MNA, FUN, ZRX, TNB, SPK.

**Comment by Camille92** [comment]
Hey Carles,

Actually I was wrong, because the latest coins I added have all the decimals I need.
Maybe it's due to an issue in older database ?

**Comment by ctubio** [comment]
maybe cos im looking at the codes of the trades table and is not fixed to 2 decimals, is variable based on minTick like the market levels

feel free to close the issue or let me know in case you still think some decimal is wrong; im a bit confused now cos to me seems correct; it is correct for you too now?

**Comment by ctubio** [comment]
in latest commit i had cleanup a bit the ui functions; hope you dont miss any decimal after the last commit; please let me know if you feel the `val` values in the trades history are missing decimals otherwise i will close this soOn'' :dancer:

many thanks for you time''

**Comment by Camille92** [comment]
Thank you for working on it!

I'll update soon and tell you :)
