### ISSUE TITLE
Suggestion: Unlocked if running only one instance

### ISSUE THREAD

**Issue by woshikie** [ctubio/Krypto-trading-bot#581]
After trading using Krypto using --free-version for a few days, i'm really curious how much money the unlocked version can get me because currently, the issue with my version of K is that the price gets updated too slowly (about once every 4s) and couldn't stay on top of the order book for long enough for any of my orders to be filled, and it almost always get filled when there is a steep change for the worst

**Comment by ctubio** [comment]
im sorry --free-version effectively slows down fun and profit for you and me. Please don't open issues asking how much % less the bot generates with --free-version; it is relative to your trading strategy, the market conditions, and the bot's performance. It is almost impossible to know.
