### ISSUE TITLE
Improvement: stop spamming console with TBP-messages

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#583]
The console log is being spammed with TBP-messages like this:
10:48:39.003064 PG TBP: 0% = 0.00000000 BCC, pDiv: 10% = 3.53052098 BCC.

It would be great if one could suppress these...

**Comment by ctubio** [comment]
you mean in gdax? or in what exchange?

**Comment by Pat71** [comment]
No, HITBTC

**Comment by ctubio** [comment]
hitbtc is not very spammy, gdax does it nonstop, but thanks for the suggestion will allow it somehows soOn''

**Comment by ctubio** [comment]
will remove it by default and add it only if `--debug-wallet` is used, but will include `--debug-wallet` to the default OPTIONAL_ARGUMENTS
