### ISSUE TITLE
Is GDAX Sandbox supported?

### ISSUE THREAD

**Issue by serial77** [ctubio/Krypto-trading-bot#584]
Hi! Thanks for this awesome bot @ctubio 

I would (obviously) like to test it on the GDAX sandbox befor taking it to my live account.
When connecting to the live account all seems fine but when changing the config to point to the sandbox api (and using the sandbox api key) I get the following error:

> K build x86_64-linux-gnu 2018-01-19 03:20:03.
> K version 0day.
> 15:31:06.325560 DB /data/db/K.COINBASE.BTC.USD.db loaded OK.
> 15:31:06.325949 UI ready over HTTPS on external port 3000.
> 15:31:06.326238 QP Warrrrning: using default values for Quoting Parameters.
> 15:31:06.326356 DB loaded 0 historical Trades.
> 15:31:06.328960 DB loaded 565 STDEV Periods.
> 15:31:06.329048 DB loaded 11370.053667 EWMA VeryLong.
> 15:31:06.329080 DB loaded 11372.507212 EWMA Long.
> 15:31:06.329100 DB loaded 11377.267423 EWMA Medium.
> 15:31:06.329109 DB loaded 11386.223692 EWMA Short.
> 15:31:06.329214 DB loaded 20 historical FairValues.
> 15:31:06.329395 DB loaded 26 historical Profits.
> 15:31:06.329476 DB loaded TBP = 0.01379719 BTC.
> 15:31:06.563221 GW COINBASE allows client IP.
> 15:31:06.563275 GW COINBASE: 
> - autoBot: no
> - symbols: BTC-USD
> - minTick: 0.01000000
> - minSize: 0.01000000
> - makeFee: 0.00000000
> - takeFee: 0.00000000.
> 15:31:09.016008 GW COINBASE FIX Logout, reconnecting in 21s..
> 15:31:09.300460 PG TBP: 50% = 0.01379719 BTC, pDiv: 3261% = 0.90000000 BTC.
> 15:31:09.312044 PG TBP: 61% = 0.01695974 BTC, pDiv: 3261% = 0.90000000 BTC.
> 15:31:09.326201 UI 1 currently connected, last connection was from 127.0.0.1.
> 15:31:09.847787 GW COINBASE WS Streaming book levels.
> **15:31:28.517521 GW COINBASE FIX Logout, reconnecting in 21s..
> 15:31:49.548369 GW COINBASE FIX Logout, reconnecting in 21s..**

API values:

> 
> API_HTTP_ENDPOINT=https://api-public.sandbox.gdax.com
> API_WSS_ENDPOINT=wss://ws-feed-public.sandbox.gdax.com

Is this not supported or am I doing something wrong?

Thank you!

**Comment by ctubio** [comment]
is not supported the gdax sandbox because is very boring, it does not have almost market movements, so it really doesn't allow to test nothing.

**Comment by ctubio** [comment]
note we connect to gdax using FIX protocol, im not sure the gdax sandbox have FIX endpoing

**Comment by serial77** [comment]
Moltes gracies @ctubio I'll check it out!

**Comment by ctubio** [comment]
![captura-de-pantalla-2017-10-16-a-les-22 37 15-16223853-604x270](https://user-images.githubusercontent.com/1634027/35177965-c90466f6-fd84-11e7-86d6-619604943fde.jpg)
