### ISSUE TITLE
Unlocking the program

### ISSUE THREAD

**Issue by 1svich2008** [ctubio/Krypto-trading-bot#586]
What do I need to specify in PR when unlocking the program?
description
please, consider to add all possible details (if any) about your new feature request or bug report

---
```
app exchange: HitBtc/BTC/USD
app version: undisclosed
OS distro: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
see the README, section Unlock, first paragraph; if is a lion will eat you

**Comment by 1svich2008** [comment]
"and let me know the BTC Payment Address for the bot that you wish to unlock in the description of the PR", where this BTC Payment Address for the bot ? I read all the instructions, but did not find where to get it. If not difficult, explain.

**Comment by ctubio** [comment]
the BTC Payment Address is displayed when --free-version is not used

**Comment by 1svich2008** [comment]
I have a weak computer for a free version with a delay, I need an unlocked version of the program with a different currency, can you help me in this?

**Comment by ctubio** [comment]
i dont understand what is the bug here

**Comment by 1svich2008** [comment]
How do you know what I paid for my program, if in the modification program in the Makefile - KZIP?

**Comment by 1svich2008** [comment]
What do I need to do to get the full version of the program?

**Comment by ctubio** [comment]
the payment will be in the blockchain forever; an update or reinstall of the application do not have any effect; the api key will remain unlocked forever
