### ISSUE TITLE
Bot is not buying or selling

### ISSUE THREAD

**Issue by DasBasti** [ctubio/Krypto-trading-bot#588]
why does the bot not buy or sell anything when the market does this?
![image](https://user-images.githubusercontent.com/1713093/35199846-5d8af6a2-ff04-11e7-8425-4af9baeabe62.png)

It does have sufficient funds, width is at a very low setting (2%)

I only see it putting wild changes to the bids and asks but never letting a order fill. It is always off by a little

**Comment by ctubio** [comment]
because of reasons sure; it does not do magic

consider the IRC channel for questions
