### ISSUE TITLE
Improvement / Feature request: Anti Slippage Protection -> Make Pdiv great again!

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#59]
Hi Carles and everyone,

This idea was briefly evoked here https://github.com/ctubio/Krypto-trading-bot/issues/6 1) Option Pdiv = 0 if TargetPosition > Sensibility [PENDING]

But I'm realizing it's much more needed that I first thought, and I'm going to explain why:

When you trade on multiple pairs in one exchange, your PDIV is **multiplicated** by the number of pair you have for each currency, because each pair will try to respect Pdiv.
This leads to enormous slippage and nothing you can do about it (for now).

Let me give you an example with USD at Bitfinex. There are 11 pairs trading with USD:
BTC/USD, ETH/USD, ETC/USD, LTC/USD, XMR/USD, XRP/USD, EOS/USD, IOTA/USD, SAN/USD, ZEC/USD, DASH/USD ...

Now imagine all the markets are down and you have a pdiv of 5% and a trade size of 2.5%.
In theory you wish to have most of your value in USD and wait for the storm to be over.

But you're going to have a minimum of 55% (5*11) of your money NOT in USD and that could go as high as 82.5% (7.5 * 11) because each pair is going to keep 5% of your USD balance in the currency.

Same thing if BTC (11 pairs) or ETH (5 pairs) is going up!

Let's just say that under those circonstances, **TBP is nearly useless!**

### How to solve the problem:

I have been thinking about a solution easy to implement with what we have already while not harming market making strategy. 
This solution is to have a ASP (Anti Slippage Protection) option that changes Pdiv to 0 if a factor (multiplier) of sensibility is met!

### How to do it?

I propose to use the value of TargetPosition that we have here https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/statistics.ts#L53 **BEFORE** it's capped to -1 and 1. (We still need to cap it after for TBP calculation).

Then we just need to input a new variable "ASP factor" to be a positive number:
So we get something like:

```
if (newTargetPosition > ASPFactor) || (newTargetPosition < -ASPFactor) 
  pdiv = 0
```

So now a concrete example:

Your sensibility = 0.4 and your ASPFactor = 1.5
So the ASP will be activated if TargetPosition is superior to 1.5, so in other word if the difference between your 2 ewma = 0.4 * 1.5 = 0.6

I hope you understand the issue and the proposed solution!

I think it's a great tool for everyone trading on multiple pairs in big markets like Bitfinex, polo and HitBT.

I know you're in a reforming period Carles, but if you can have a look at that that would really help me 🥇 . If you need some tips for developing that, your price is mine!

Best and happy trading for all,

Camille

**Comment by ctubio** [comment]
understood the problem but as always not the solution xD let me see this laterz againz onze brain iz awake :P

**Comment by Camille92** [comment]
Hello Carles,

No worries,  I come back for a quick explanation of the solution. (and I can say we are each other's Pinky and the Brain because I don't understand about most of how you make K work haha).

K always respects pdiv, which is good and necessary for market making, but when the market goes clearly in one direction it can be interesting not to respect Pdiv and just try to keep as much as you can of this asset, or if it goes down, not to have any.

Let's say BTC/USD is going seriously down like -5% in the last hour. Your tbp will probably be at 0.
But K will still try to buy some btc (respecting pdiv) in hope that you can make a good trade by selling them higher.

However given how the market is moving, you're going to find very easily someone to sell you BTC but hardly someone to buy the BTC you have and by the time you're doing that, market is probably going to be lower than the price you bought your btc resulting in a loss.

This problem exists for everyone but is amplified when you trade with the same asset in different markets (as explained above).

One solution would be simply to have pdiv = 0 all the time but then you would never do market making, and that's not what we want!

So the solution I propose is to reuse the formula to define TP in statistics:


```
if (this._qpRepo.latest.autoPositionMode === Models.AutoPositionMode.EWMA_LMS) {
--
  | const newTrend = ((SMA3 * 100 / newLong) - 100);
  | const newEwmacrossing = ((newShort * 100 / newMedium) - 100);
  | newTargetPosition = ((newTrend + newEwmacrossing) / 2) * (1 / this._qpRepo.latest.ewmaSensiblityPercentage);
  | } else if (this._qpRepo.latest.autoPositionMode === Models.AutoPositionMode.EWMA_LS) {
  | newTargetPosition = ((newShort * 100/ newLong) - 100) * (1 / this._qpRepo.latest.ewmaSensiblityPercentage);
```

But instead of calculating TBP we calculate a "Anti Slippage Protection" that acts like a lock on pdiv.
Meaning that let's say you put 0.5% as your ASP sensibility (same way you do for TBP) if 

((newShort * 100/newLong) - 100  > 0.5 OR
((newShort * 100/newLong) - 100 < -0.5

Then you activate the ASP that just changes PDIV to 0.
By doing so, you're sure you're not going to buy this asset on a descending market or sell it in an upward market. 
Until -0.5 < ((newShort * 100/newLong) - 100  < 0.5 is respected again.


Is it more clear now? 😺

**Comment by Camille92** [comment]
a little temporary solution to put in quoting-engine.ts for people interested.

It's definitely not perfect (can't access to the UI, can't configure the sensibility) but it links pDiv to TBP. So if your TBP is 100% or 0% then if will stop buying or selling in the wrong side ;)

```
        if (targetBasePosition >= totalBasePosition || targetBasePosition <= 0) {
          pDiv = 0;
        }

```

**Comment by Camille92** [comment]
Hi Carles,

I don't have time to try it this weekend but here it's what I came up to make ASP happening. Please tell me if I'm missing something.

In statistics.ts:
```
    let newTargetPosition: number = 0;
    **let ASP: number = 0;**
    const params = this._qpRepo();
    if (params.autoPositionMode === Models.AutoPositionMode.EWMA_LMS) {
      const newTrend = ((SMA3 * 100 / newLong) - 100);
      const newEwmacrossing = ((newShort * 100 / newMedium) - 100);
      newTargetPosition = ((newTrend + newEwmacrossing) / 2) * (1 / params.ewmaSensiblityPercentage);
      **ASP = newTargetPosition;**
    } else if (params.autoPositionMode === Models.AutoPositionMode.EWMA_LS) {
      newTargetPosition = ((newShort * 100/ newLong) - 100) * (1 / params.ewmaSensiblityPercentage);
     **ASP = newTargetPosition;**
    }
    if (newTargetPosition > 1) newTargetPosition = 1;
    else if (newTargetPosition < -1) newTargetPosition = -1;

    return newTargetPosition
    **return ASP**
```


in quoting-engine.ts:
```
        let pDiv: number  = (params.percentageValues)
          ? params.positionDivergencePercentage * latestPosition.value / 100
          : params.positionDivergence;

        **if (ASP >= 5 || ASP <= -5) pDiv = 0;**       
```

What do I expect that to do:
If the width between the ewma (TP) is 5 times "sensibility", then block pdiv to 0.

Do I need to write something in particular to use ASP created in statistics in quoting-engine?

If this code works then just need to add it to the web UI to change the "5" to whatever we want and it's done :)

**Comment by Camille92** [comment]
Ok I tried it and I could not get it to work because I don't know how to get ASP in quoting-engine :S ...

**Comment by Camille92** [comment]
See for v2 here 
https://github.com/ctubio/Krypto-trading-bot/issues/205
