### ISSUE TITLE
HitBTC Error

### ISSUE THREAD

**Issue by FWCJohn** [ctubio/Krypto-trading-bot#590]
Keep getting two errors, one just hitting over and over, and the other when I try to manually trade:

Manual trade error:

GW HITBTC Warrrrning: Ignored response: {"error":{"code":500,"description":"","message":"Internal Server Error"},"id":283,"jsonrpc":"2.0"

Error with missing wallet data (wallet is funded)

00:15:22.923819 PG Warrrrning: Unable to calculate TBP, missing wallet data.

I checked API settings it has everything selected in hitbtc, not sure what is going on.

**Comment by ctubio** [comment]
the message about missing wallet data when happens?

do you see in the UI the wallet values or the wallet is not displayed?

**Comment by ctubio** [comment]
if is not just on bot but nonstop over and over i may say that the api key doesnt have permission to read wallet data

**Comment by ctubio** [comment]
you can try '--debug-secret` argument  to see some more hitbtc messages, maybe there is something interesting; as far as i can tell i had never received a 500 error response from hitbtc so im not sure why it does it

just make sure you dont paste the log of --debug-secret anywhere cos it contains secrets

**Comment by ctubio** [comment]
maybe the IRC channel is a better place to solve this situation, cos im not sure that any commit will come out of here
