### ISSUE TITLE
HitBTC - not reading account balance when quote currency is USDT

### ISSUE THREAD

**Issue by KelvinJones** [ctubio/Krypto-trading-bot#593]
I could be wrong, this may have been reported alread, I'm new to the bot. There, disclaimers posted first!

I'm running the K bot successfully on HitBTC, works great actually, on BTC/USD and ETH/USD.  Then I tried XRP/USD and the ticker for that is actually XRPUSDT or from the bot's perspective, XRP/USDT.  I had to manually place a trade, full cycle (buy then sell) then it picked up the quotes.  The problem is it couldn't read the account balance. Perhaps "T" in USDT is throwing it off?

![image](https://user-images.githubusercontent.com/29181172/35277784-8550ac7a-0050-11e8-9fe9-b575252f7dd6.png)

**Comment by adirta** [comment]
The pair to operate is "USD" whiout "T"
What do you have all the pairs: https://api.hitbtc.com/api/2/public/symbol
you have to add "/" between the abbreviations of the coins
Example: XRP/USD

**Comment by KelvinJones** [comment]
@adirta , 100% with you. Looked for that before posting.  XRPUSD or XRP/USD does not exist on HitBTC and I think it may be useful to implement the ability for the K bot to the account currency when the ticker like USDT doesn't match the account which is USD.  In the meantime I will avoid trading XRP on HitBTC and look for other pairs with a quote currency of USD only.

**Comment by adirta** [comment]
Exists. https://hitbtc.com/exchange/XRP-to-USDT
Add in the conf file:
API_CURRENCY = XRP/USD

**Comment by KelvinJones** [comment]
Add it to the K bot conf file?

**Comment by adirta** [comment]
Yes, in the configuration file of your bot (example "k.sh" or any other "xrp.sh") you have the API_CURRENCY line. For the bot to operate with XRP and USDT, it has to be exactly like this:

API_CURRENCY = XRP / USD

Save file configuration and restart the bot process.

**Comment by KelvinJones** [comment]
Ah, yes I did that before I posted the first post. When I do that the bot doesn't connect. It doesn't connect because HitBTC does not support that ticker (XRP/USD).  It only supports XRP/USDT.  If I set API_CURRENCY = XRP/USDT the bot connects, but then, back to my first post and picture above, it can't read the USD value in the account. It thinks there's no cash because to connect to the account the USD symbol is needed. So, to connect to XRP in HitBTC we need the bot to allow XRP/"USDT" to connect to the ticker properly for trading but at the same time use only "USD" to connect to the account.

**Comment by ctubio** [comment]
many thanks for your help @adirta '''

@KelvinJones hope you agree toconsider the IRC channel to resolve this situation if you are still in trouble

**Comment by KelvinJones** [comment]
Hi all, actually I'm wondering if anyone is reading what I've written?  

I've tested this several times now and when I follow the above suggestion, which I appreciate and have done prior to my very first post, the bot literally does not restart, does not connect and the terminal cannot be connected to via a browser, I get "page not found".  

BUT, when I use the ticker symbol for XRP on HitBTC, which HitBTC and @adirta above, says is XRPUSDT (or XRP/USDT in the K.sh file), then the bot runs and I can connect. BUT, then the bot cannot read the balance in the account because the api appears to want us to use USDT to connect to the account but it looks like the api requires us to connect to the account using USD instead.  

If above is not clear perhaps it's my English, please let me know and I'll try to articulate this differently for clarity.

Either way I guess it doesn't matter as there are plenty of pairs to trade besides XRP.  Still a good bot even without support for USDT quoted pairs.

**Comment by akileos** [comment]
Everyone has read you, but it's unusual to have "USDT" on HitBTC pair names, most of pairs omit the "T". 

But I double checked on you're right on the pair 👍 

`{"id":"XRPUSDT","baseCurrency":"XRP","quoteCurrency":"USD","quantityIncrement":"1","tickSize":"0.0001","takeLiquidityRate":"0.001","provideLiquidityRate":"-0.0001","feeCurrency":"USD"},`

Not sure if it's a corner case, can't help much here, may be an issue on hitbtc side !

**Comment by MiningInMySleep** [comment]
Can we have this looked into as it wasn't an issue on the older version of K. After updating to the most recent build from one back in December (maybe older actually) a bunch of USDT pairs stopped working including XRP/USDT.

**Comment by ctubio** [comment]
to speed it up, can you please confirm what are the exact values you are using in the config file for:
API_EXCHANGE
API_CURRENCY
?

i will test with the very same then

**Comment by MiningInMySleep** [comment]
Thanks for re-opening this!
I have been using:
API_EXCHANGE=HITBTC
API_CURRENCY=XRP/USDT

After updating to the latest commit on Monday, it started giving me the "PG Warrrrning: Unable to calculate TBP, missing wallet data." error that other people are having. Before that it was trading just fine on the pair for over 3 months.

**Comment by ctubio** [comment]
seems this is because even if the market is named USDT, the quote currency is still USD (as seen as https://api.hitbtc.com/api/2/public/symbol)
