### ISSUE TITLE
On the necessity of re-implementing "ewma trend"

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#594]
Hi Carles and all,

I know it's duplicating this post (https://github.com/ctubio/Krypto-trading-bot/issues/472) but I want to emphasize here how ewma trend is beneficial for every trader especially is the current downtrend situation. (don't hesitate to close the old post if you feel like it).

So here is my argumentation to push the rehabilitation of ewma_trend as a top priority for K:

In the next weeks, we might experience some "hardcore" downtrend and no one wants to be tricked buying in a falling knife.

We already experienced that in the past few days, here is an example that particularly touched me:

![telechargement 6](https://user-images.githubusercontent.com/6861590/35280303-0d3987ca-0050-11e8-8517-be4f4bdfedbf.png)

EOS lost **-12% loss in 2h30**, even with the best market making strategy it's impossible to make a profit out of that. But with a simple 20/30 ewma trend K would not buy this fall of 13.1 to 11.6 on 

EOS and instead would buy back around 12, and then restart the MM making strategy after as the two ewma are close from each other.
Examples of that kind of fall that would be saved by having ewma trend are numerous!

Same thing when the market is going up. Look at XRP is always recovering crazy fast and it's so annoying to sell a rocket!
![telechargement 7](https://user-images.githubusercontent.com/6861590/35280314-176b3fa4-0050-11e8-87ac-e385bc0ec24f.png)

Market making is doing the best when the market is relatively stable but when the market is strongly going in one direction there's no best strategy than B&H or staying out!
Ewma_trend is allowing you to have best of both worlds!

Lastly, if I'm not mistaking, it seems to me that we have everything to reimplement ewma_trend  easily and I find it damageable not to enjoy its benefits when it's so reachable!

Happy trading and I hope you understand and support my point!

Camille

**Comment by SlackerATX** [comment]
Can't you accomplish something similar with ewma_4?

**Comment by Camille92** [comment]
Hi @SlackerATX, not really each setting of K answer to a different aspect to make a trade or not.

Ap_mode question is: Should I buy? 

Mode / width / ewma? / stdev etc ... : question is: at what price ?
Ewma_trend question is: When?

Ewma_trend is helping to find tops and bottoms!

I take again the example of EOS:

Here in general EOS is rising, but if you don't answer the question "when to buy" using ewma_trend you will buy when it's going down. 
Using it you can make sure to buy only when it reached the bottom around 12 and sell only after it came back to 13.4

![telechargement 8](https://user-images.githubusercontent.com/6861590/35327949-3334b3ae-00fb-11e8-9785-73933c8176ae.png)

Here is a picture of the expected behavior of ewma_trend.
