### ISSUE TITLE
theme suggestion

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#596]
Two suggestions regarding theme (light/dark):
1. add a command line switch for starting in dark theme (or remember last theme when starting)
2. please fix that every morning at 9 the theme gets switched back to light

**Comment by b-seite** [comment]
The scheduled theme switch is a funny Feature at the Moment But i also suggest that we better get a Switch Option to permanentes decide what theme to use. 
And btw. maybe we think about removing the old Green tribeca theme completely? I personally prefer the dark theme... what do ohters think about that?

**Comment by ctubio** [comment]
a pair of arguments --light-side and --dark-side may do the work without adding a ui button just for a one-click-time

**Comment by MiningInMySleep** [comment]
Yeah, I'm not gonna lie. I never want my UI to be on the light theme. It's always too bright even during the day and it makes it hard to read.

**Comment by ctubio** [comment]
im so happy my eyes will not bleed anymore with the light theme
