### ISSUE TITLE
bitmex.com - exchange with wsAPI,  Maker fee -0.0250%, -0.0500%

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#599]
https://www.bitmex.com/app/wsAPI
https://www.bitmex.com/app/fees

What you think?

**Comment by ctubio** [comment]
like kucoin and else, someday

**Comment by donaldforest** [comment]
kucoin Trading Fees:
0.1%

**Comment by serzhiio** [comment]
Voting for BitMEX!

**Comment by donaldforest** [comment]
> Remember... all I'm offering to **have a choice**. Nothing more.

![morpheus-armchair](https://user-images.githubusercontent.com/33358791/35413484-a3e580f2-0230-11e8-988b-5469ba76fe65.jpg)

**Comment by donaldforest** [comment]
![rabbit](https://user-images.githubusercontent.com/33358791/35938984-d7d98612-0c5b-11e8-89a9-c5caa3235177.png)
