### ISSUE TITLE
2 small improvements

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#6]
Camille said: Hello Carles,

If you don't find that annoying that I'm always posting new stuff, I'm coming this week with a little list of small improvements that, IMHO can make life easier using Tribeca and raise some profits.

(If you don't mind I kind of find it funny to try to come each week with one big or a few small ideas to make Tribeca better)

### Confort improvement:
**1) Ak-47 bullets in % if width % is activated** **[WONT FIX]**
I think this one is just following the logic of "all % option" and bullets of Ak-47 is the last one not % compatible.

**2) "Auto-cleaning of K orders":** **[FIXED]**
I don't know if you have the same issue but if I don't check Tribeca for some time then it takes a while to load (if it loads) because there are too many orders waiting there.
I guess a tick box that would get rid of the closed orders can be a good idea (maybe keeping the last 100 and getting rid of the oldest), well tell me what you think about that

**3) Labeling each line of Tribeca for its function:** **[FIXED]**
Tribeca has different strategies in it, I think it might be a bit more explicit for everyone to clearly divide the rows in the UI, so you understand what you're doing when you're touching to a row.
First one: "Market Making"
Second one: " Technical Analysis"
Third one: "Protections"
Fourth one (I hope :p): "Safeties" 

### Performance improvement:
**1) Option Pdiv = 0 if TargetPosition > Sensibility** **[DONE SIMILAR]**

The goal is twofold, first to stop the "leaking" of profit when Tribeca is in the good direction with the market but will anyway sell or buy just because is going to try to do some market making.
Sometimes it's just good to buy and hold or just stay away from the market.

Second, is to allow a bigger Pdiv for "normal market", because I'm afraid of that "leak", over time I reduced the size of Pdiv to about 5%. However, in normal market condition (when TBP is central) it is more interesting to have a bigger Pdiv. With this option, one can easily have a big Pdiv and still be sure that if the market goes strongly in one direction there will be no "leak".

I'm not sure if it should be linked to the sensibility we have already or to a separate one but I really think it's a good idea in general. If we have a separate sensibility we can choose to put that higher that TPB sensibility to only in BIG market movement you're locking Pdiv.
Ie: TBP sensibility 0.5 but Pdiv lock sensitibility = 1.

**2) Ewma width:** **[PENDING]**

We all the recent improvements (Stdev and EWMA_LMS) I think this one should be quite easy to implement.
I think it should take the general design of Stdev with periods in seconds and a factor. However here what we calculate is the ewma of the width.

The concept is just not to post an order with a small width if the width has been bigger before.

minAsk = FV + (ewma_width(periods)*ewma_width_factor) / 2 
minBid = FV - (ewma_width(periods)*ewma_width_factor) / 2 

I think this should work well with a small value and in complement with Stdev Fair or Top ideally because they don't take into account the width but just the evolution of the price :).

Tell me what you think about all of that!

I know it might be the most important things but I think it cool to always come with new ideas :)

**Comment by Camille92** [comment]
New small improvement:

Changing (or offering the possibility) to calculate EWMA protection at the second instead of a minute.

I never use EWMA protection because it's way too slow at 20mn and putting it at 2-3 lacks of data point to be relevant.

But I think something of a few minutes calculated every second can give you a good line without lagging too much if the price moves in one direction :)

**Comment by b-seite** [comment]
I think we can close this one because of #482 there is nothing  left open

**Comment by ctubio** [comment]
@b-seite you are on fire xD
