### ISSUE TITLE
Manually add different exchange.

### ISSUE THREAD

**Issue by istrau2** [ctubio/Krypto-trading-bot#60]
I am looking to become a market maker on an exchange not supported here. I am wondering if there is any straightforward way to:
1) Add a PriceDeterminationStrategy (from an unsupported exchange for an unsupported asset pair)
2) Add a QuoteExecutionStrategy (using an unsupported exchange for an unsupported asset pair)
assuming that I am a capable javascript dev and willing to get my hands dirty.

Thanks in advance.

**Comment by ctubio** [comment]
yea you can use your keyboard to add manually any unsupported exchange/strategy; then recompile and run

**Comment by istrau2** [comment]
@ctubio Aw come on. I just wanted a little help getting pointed in the right direction (i.e. which parts of the code, generally speaking would I need to add to).

**Comment by ctubio** [comment]
duplicate src/gateway/korbit.ts that is the most simple exchange
then simply in src/server/maint.ts add the new exchange near the others at the top "exchange" switcher

not sure what else you need?

**Comment by ctubio** [comment]
https://github.com/ctubio/Krypto-trading-bot/commit/ced0c2ef5332ff856d1c0d2b82b941131346db63 here is an example of an exchange addition

**Comment by istrau2** [comment]
Ok, thanks. That is a good start. Greatly, appreciated.
