### ISSUE TITLE
all bots unlocked by default

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#600]
meanwhile internal functions of the payment system are updated :dancer: enjoy!

(the update will not change the functionality just optimize it)

**Comment by ctubio** [comment]
btw this will last just a few hours and the unlock is not permanent, is only during for this timeframe

**Comment by f4bsch** [comment]
Can we pay to unlock meanwhile? The bot does not show the BTC address anymore. I saw it on the weekend, then switched to free version. Now back and can't find it anymore. Also market levels are now empty 🤔

**Comment by ctubio** [comment]
if you mean market levels of hitbtc see https://github.com/ctubio/Krypto-trading-bot/issues/597

about the btc address will be displayed soon again once payment system is active again, meanwhile running the bot without --free-version is like an unlocked bot, and on next restart (hopefully cos i need yet a few more hours) the payment address will be displayed

**Comment by f4bsch** [comment]
Oh, seems to be the hitbtc issue. Ok thanks!
