### ISSUE TITLE
Unable to calculate quote, missing market data.

### ISSUE THREAD

**Issue by KelvinJones** [ctubio/Krypto-trading-bot#602]
Is this a problem with HitBTC or the bot?  No offense intended. Still learning the b. I suspect it's HitBTC and I've logged a ticket but I was hoping to get an answer before I grow old and die so I'm posting here.  This is what the bot reports:

x 17:48:32.584089 QE Warrrrning: Unable to calculate quote, missing market data.
x 17:48:33.402666 GW HITBTC WS Streaming book levels and orders.
x 17:48:33.606960 QE Warrrrning: Unable to calculate quote, missing market data.
x 17:48:34.643103 QE Warrrrning: Unable to calculate quote, missing market data.
x 17:48:35.672321 PG Warrrrning: Unable to calculate TBP, missing wallet data.

**Comment by ctubio** [comment]
yep see https://github.com/ctubio/Krypto-trading-bot/issues/597 and https://github.com/hitbtc-com/hitbtc-api/issues/113

**Comment by KelvinJones** [comment]
Thanks!
Odd that it’s that old.  The bot made money for me up until a couple hrs ago. Anyway, thanks for the prompt feedback.
Kel

--
c: +27 83 682 2660
e: kelvinjones@outlook.com
in: https://za.linkedin.com/in/kelvin-jones-01a3a56
