### ISSUE TITLE
need to Lock Hitbtc  Market again 

### ISSUE THREAD

**Issue by hamadaDev** [ctubio/Krypto-trading-bot#603]
Hi
Please can you re-lock HitBTC because  Locked Coin like Doge work fine .  and any unlock coin have issue and trade with it may be dangerous now . 
![image](https://user-images.githubusercontent.com/11373077/35398497-1623f956-0203-11e8-841e-e8f5ae2b2a74.png)

![image](https://user-images.githubusercontent.com/11373077/35398578-4ee1e9a6-0203-11e8-9f83-417d09b1757a.png)
all  snapshot taken  now  7.10 pm (+3)  25/01/2018

**Comment by ctubio** [comment]
the problem of hitbtc is not because a locked bot, see https://github.com/ctubio/Krypto-trading-bot/issues/597

**Comment by ctubio** [comment]
also the unlocks of yesterday are not permanent

**Comment by hamadaDev** [comment]
![image](https://user-images.githubusercontent.com/11373077/35401868-cea31b80-020b-11e8-919f-08a005db4e5a.png)

when you re-Lock  I think bot's work fine now I started trade in some Coin and no problem
