### ISSUE TITLE
Bug: DepletedFunds on AskSide though there are funds

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#605]
As can be seen in the screenshot, I keep getting the message "DepletedFunds" on the AskSide from time to time though I have funds to be sold...
Is this a K bug or again the fault of the buggy HITBTC API?

![depletedfunds](https://user-images.githubusercontent.com/35595325/35429095-cd5e2fd2-0272-11e8-88e2-fa5854944cde.jpg)

**Comment by ctubio** [comment]
because size is bigged than available amount

**Comment by ctubio** [comment]
do you mean that you feel that the bot should sell this 2 coins even if the setting of size have a higher value?

**Comment by serzhiio** [comment]
IMHO, there is a little problem.
I think that we should compare totalBasePosition with gw->minSize for Depleted status.
