### ISSUE TITLE
Suggestion for stats charts

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#607]
**1)** We have on this time Legend:
- Fair Value
- Width
- Sell
- Buy
- EWMA Quote
- EWMA Very Long
- EWMA Long
- EWMA Medium
- EWMA Short
- STDEV Fair
- STDEV Tops
- STDEV TopAsk
- STDEV TopBid
- STDEV BBFair
- STDEV BBTops
- STDEV BBTop
- Market Buy Size
- Market Sell Size

**2)** But by default settings (first run) bot used data for:
- Fair Value
- Width
- Sell
- Buy
- EWMA Quote      _- checked by default_
- EWMA Long        _- apMode EWMA_LS_
- EWMA Short        _- apMode EWMA_LS_

**3)** But in most cases we need just:
- Fair Value
- Sell
- Buy
and always click by click remove all unused legends from chart after each UI refresh or bot run/restart!

I suggest make some default minimal set of default showed charts\lines in stats. If someone need more it can enable \ show needed. But I sure is no one don't use all in same time! Like for me is the best most minimal set - **3)**. But I understand new users + K presentability for first run when K need show to show its power and possibilities in charts... And we can use by default in this case for example set **2)** + Market Buy Size + Market Sell Size (for beauty).

PS Hard way - use cookie to save charts legend. But not sure we need it now.

**Comment by ctubio** [comment]
stats since a month ago allow show/hide depending on quoting parameters, but no conditions were implemented yet, will do soOn''
