### ISSUE TITLE
Poloniex Value Errors

### ISSUE THREAD

**Issue by alexpalmer** [ctubio/Krypto-trading-bot#608]
I understand that there are errors with the Poloniex exchange (mostly around the overal value, causing no bids to be made).

I'm interested in fixing this - but can't find where in the source the poloniex GW code is? Any someone point me in the right direction? If I can fix I'll post a pull request

#284

**Comment by ctubio** [comment]
the code about exchange integrations is not public

**Comment by alexpalmer** [comment]
So if I want to contribute and help... how can I help?

**Comment by ctubio** [comment]
there is no way to contribute in the private sources
