### ISSUE TITLE
Docker Builds but cannot seem to connect via localhost

### ISSUE THREAD

**Issue by zbanga** [ctubio/Krypto-trading-bot#61]
Did several clean installs of Docker. Docker ps brings up Kjs and the ports, but cannot seem to connect via localhost?

**Comment by lejacobroy** [comment]
Hi!
You need to find the real IP to which docker binds. I find that using Kitematic makes it much simpler as it will bind to the localhost when you start the Docker image from the app.

Hope it helps!

**Comment by ctubio** [comment]
yea i use https://kitematic.com/ too and it really helps to avoid all the docker pains

once you have Kitematic opened, you can click ina web page preview to open the web page of the container, no need to fetch ips

**Comment by DeanJason** [comment]
after opening kitematic how can i point it towards the files on my drive?  i can't find the repo in the search function.  haven't used kitematic before

**Comment by ctubio** [comment]
there are no shared files between the container and the host machine; what you mean by "my drive"?
