### ISSUE TITLE
Suggestion: "dont buy/dont sell"-options

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#612]
It happens quite often that the bot buys some coins and shortly afterwards, the price drops and the bot sells the coins for a much lower price.

It would be nice to have an option like "dont sell" that one could activate manually so the bots continues to buy (at low price) but doesn't sell. When the price has risen, the user could deactive this option so the bot continues to sell.

Vice Versa, when the price is very high, it would be nice to activate an option "dont buy" to tell the bot to sell the coins in stock but not to buy new ones (ok, this can be achieved by setting tbp/div to 0, at least in pingpong)

**Comment by ctubio** [comment]
use ewma?

**Comment by Pat71** [comment]
Hm, in my opinion, EWMA does not run very well if you're running multiple bots (on the same base currency)

**Comment by ctubio** [comment]
im not sure that i understand it cos ewma is related to the fair value and is not affected by TBP (instead, os the opposite since it affects TBP)
