### ISSUE TITLE
Bitfinex limitation of orders per 10 minutes

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#613]
Hi Carles and everyone,

@serzhiio and I noticed that there is a limit on the number of orders that can be sent to Bitfinex every 10 minutes. This is not stipulated in the API doc and we both sent tickets to have more answers but we didn't have a reply yet.

Does someone here have more info on that?
Is there is something we can do about that on the bot?

Best,

Camille

**Comment by ctubio** [comment]
i didnt noticed any limit at 10 minutes but will keep an eye :S

**Comment by Camille92** [comment]
The limit is rather high but if you trade in different markets, you can reach it easily! :S

**Comment by Camille92** [comment]
For the curious here is a video of what's happening:
https://youtu.be/rHz4pOWgKqc

**Comment by ctubio** [comment]
lets fix this at #614

thanks again'''

**Comment by serzhiio** [comment]
By exprimental way i found that more than 150-200 orders at 1min generates such error.
