### ISSUE TITLE
idea: min time before cancelling order

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#614]
Hi all,

I'm thinking about this function to help against the bitfinex limit and also to help trade on complicated markets with no post only orders where you can become a taker easily like Okex.

The solution I propose is to incorporate a timer defining the minimum time for an order before being cancelled (or updated).

So let's say you put 5 for in the timer when K sends an order the order will be on for at least 5 seconds before being canceled, and so even if width or size or whatever is not respected.
**During this 5 seconds, only this order will be sent.**

After the 5 seconds, the order may be canceled and updated according to your settings.
If you don't want to use that, just put the timer to 0.

That should help in some markets to get your orders filled, as well as reducing the time you're "off" the market (the time between you cancel an order and send a new one).

I think it's particularly useful for people with not that great latency (over 200ms).

At the end, our orders will be in the market longer and so have more chances to get filled. And also it should protect against the terrible invisible limit of orders per 10 mn in bitfinex.

Tell me what you think and good trading,
Camille

https://github.com/ctubio/Krypto-trading-bot/issues/613

**Comment by ctubio** [comment]
great idea''' should be doable; lets try it'¡

**Comment by donaldforest** [comment]
@Camille92  Can You recommend value for this parameter?
