### ISSUE TITLE
K cant decrease askSize to sell smaller wallet value

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#616]
GDAX
For example we have: askSize = 0.02, TBP = 0.
Wallet BTC side = 0.01 BTC and Bot dont add ask order = 0.01 BTC. (ask side - Depleted Funds)
How to Fix: decrease askSize = 0.01.

Not sure its correct bot behaviour. Looks like before K decrease ask/bidSize to completely same orders.

**Comment by Pat71** [comment]
I think that's exactly what I pointed out in issue #605

**Comment by Camille92** [comment]
I fix that by using APR.
If you use APR and factor 1 you can do that :)

**Comment by donaldforest** [comment]
Looks like APR not fix it on my side.

**Comment by donaldforest** [comment]
Just checked **apr** block order too in some cases.

**Comment by donaldforest** [comment]
![gdax](https://user-images.githubusercontent.com/33358791/35775616-2dcdb49c-099d-11e8-9001-9262d0284405.PNG)
