### ISSUE TITLE
GDAX / Macos High Sierra - Errrror: Signal 6 Abort trap: 6 (Three-Headed Monkey found):

### ISSUE THREAD

**Issue by dragonbiter** [ctubio/Krypto-trading-bot#623]
Hi - I got this error within the first couple seconds the first time I ran K.sh on my Mac running Macos High Sierra (kernel 17.4.0)  against GDAX / BTC / USD.  The minTick, minSize, makeFee and TakeFee data appeared to be returned successfully:

Errrror: Signal 6 Abort trap: 6 (Three-Headed Monkey found):
- upstream: COINBASE
- currency: BTC/USD
- lastbeat: 1517802339879
- os-uname: Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
- tracelog: 
0   K                                   0x00000001016f8561 _ZN1K2EV3wtfEi + 769
1   ???                                 0x0000000000000010 0x0 + 16

**Comment by dragonbiter** [comment]
appears to be a duplicate of #136

**Comment by ctubio** [comment]
thanks for the report, yesterday found is because libquickfix, but not solution yet

**Comment by ctubio** [comment]
should be fixed on next commit :dancer:
