### ISSUE TITLE
Okex FOK orders feature

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#624]
Hi Carles,
can we integrate FOK orders for Okex into K?
As they said its specially for MMs and should help to avoid bad trades.
https://support.okex.com/hc/en-us/articles/360000270492-New-Fill-or-Kill-Feature-in-Spot-Token-Trading

**Comment by ctubio** [comment]
feel free to edit https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/qe.h#L501 and recompile
