### ISSUE TITLE
Bitfinex not enough exchange balance problem solution

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#629]
Hi, Carles!
Lets try this line for BFX gw:
`type + (oLM == mOrderType::Market ? "MARKET" : (oTIF == mTimeInForce::FOK ?"FOK":"EXCHANGE LIMIT")) ?`
People say that it helps to avoid exchange balance problem.

**Comment by ctubio** [comment]
i dont care what people says, this line is wrong because it will generate `EXCHANGE EXCHANE LIMIT` since `type` is already a string that contains `EXCHANGE `

**Comment by serzhiio** [comment]
sorry for being stupid
this problem just makes me crazy

**Comment by ctubio** [comment]
this will be easier if the lib was public, never worry'¡ im the stupid one to not give it for free, but i hate stupid business men stealing projects

**Comment by serzhiio** [comment]
oh man... thx anyway... your project makes my happy everyday
