### ISSUE TITLE
poloniex BTC/SC

### ISSUE THREAD

**Issue by Emma-Walker** [ctubio/Krypto-trading-bot#63]
K shows disconnected. BTC/USDT works fine.

**Comment by bunde83** [comment]
I get the same message but even for BTC/USDT. Do you also get "tbp Unable to compute tbp" when running via "node K.js" ?

**Comment by ctubio** [comment]
to see the logs and be able to report mayeb some error you can run the app in the foreground with `nodejs K.js`

**Comment by Emma-Walker** [comment]
Where are the logs?

Running nodejs K.js results in: "<rejected> 'Unable to get Poloniex Ticker for symbol SC_BTC' }"
