### ISSUE TITLE
Wallet Value decreasing Email Alarm

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#634]
Point: send email when depo decreased to X% per Y min.

1) Web UI Sketches:
![walarm1](https://user-images.githubusercontent.com/33358791/36078782-2784afa6-0f8c-11e8-9041-deb1af2960fb.PNG)
![alarm2](https://user-images.githubusercontent.com/33358791/36078783-2b3f1078-0f8c-11e8-8c04-90c7606a7faf.PNG)

2) Config example:
![aemail2](https://user-images.githubusercontent.com/33358791/36078930-2fca0042-0f8e-11e8-808e-5ba43adf6ade.PNG)
PS This email can be used for some another **critical** script messages. I recommend use in email description focus on this (critical). For example your phone have 2 emails: work, personal (many messages including spam received on).. You can add 3rd special email for K and add for it personal alarm ringtone.. Do not use this email for anything else and you will always sure and ready to alarm.

3) In case bot for some reason start loosing depo, it can send via sendmail message with some contents. No need to describe to many factors, just server name\IP, bot instance name = db filename (K.COINBSE.BTC.EUR...) and and some values, like "wAlarm: -22% 30min" in body.
**PS No need to describe to many values with security reason.**

4) I recommend using sendmail.. Just check\install it with make install. Email code with sendmail is simple:
```
int sendmail(const char *to, const char *from, const char *subject, const char *message)
{
    int retval = -1;
    FILE *mailpipe = popen("/usr/lib/sendmail -t", "w");
    if (mailpipe != NULL) {
        fprintf(mailpipe, "To: %s\n", to);
        fprintf(mailpipe, "From: %s\n", from);
        fprintf(mailpipe, "Subject: %s\n\n", subject);
        fwrite(message, 1, strlen(message), mailpipe);
        fwrite(".\n", 1, 2, mailpipe);
        pclose(mailpipe);
        retval = 0;
    }
    else {
        perror("Failed to invoke sendmail");
    }
    return retval;
}
```
 
Just need to add timer and check wallet. Possible add another K state alarms.

**Comment by ctubio** [comment]
nice idea but what means "depo"? :dancer:

**Comment by donaldforest** [comment]
UPD, we can using "profit" value as time-frame frequency. -1 settings.
