### ISSUE TITLE
coinut.com - 0 Maker fees, Websocket and REST API supported

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#637]
FEES: https://help.coinut.com/hc/en-us/articles/115000267887-What-are-the-fees
API: https://github.com/coinut/api/wiki

Looks like another good exchange for MM. What You think about adding it to K?

**Comment by ctubio** [comment]
someday maybe :dancer: i have more fun priorities to do unless nobody cares to prioritize thiz
