### ISSUE TITLE
Minimum bid/ask is 0.01. Why?

### ISSUE THREAD

**Issue by Emma-Walker** [ctubio/Krypto-trading-bot#64]
Why is the minimum bid/ask 0.01? Why can't it be less? Is it dependent upon the Exchange?

**Comment by lejacobroy** [comment]
It must be dependent upon the Exchange : I'm on Bitfinex and the minimum is 0.01 of ETH or EOS.

**Comment by ctubio** [comment]
if you find that some exchange has really some other minimum order amount, we can try to fix it
