### ISSUE TITLE
More beginner friendly tutorials and help.

### ISSUE THREAD

**Issue by luqa151** [ctubio/Krypto-trading-bot#645]
More information that is beginner friendly is needed as of right now it is quite hard to understand. Some tips like what coins to choose, when to change and some basic setups in different situations, that you may encounter.

**Comment by ctubio** [comment]
im sorry this is a trading bot, not a trading school; not even a source of suggestions

**Comment by ctubio** [comment]
the irc channel may be the best place while this docs do not exists
