### ISSUE TITLE
BitFINEX limit API rate limit reached per 10 minutes 

### ISSUE THREAD

**Issue by shahidjalally** [ctubio/Krypto-trading-bot#646]
Hello,
While I logged in at BitFinex own platform, I see that at certain times a pop up appears "maximum limit reached per 10 minutes" and activities are stopped for some time.

Additionally where I can see the logs of activities.

I want to investigate because bot continually making loss since I have started it.

**Comment by ctubio** [comment]
use --lifetime argument (see https://github.com/ctubio/Krypto-trading-bot/issues/614)

**Comment by shahidjalally** [comment]
@ctubio 
I'm still failed to understand how may implement this solution as I have most recent reinstall K bot. and still facing the same issue
