### ISSUE TITLE
IMPROVEMENT with the new UI: K "A la carte"

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#649]
Dear Carles and K community,

Here is an idea I think can satisfy many traders here.
I don't know how you imagine the new UI, but something that would be awesome is to be able to add the safety already existing in the bot with a kind of "drag and drop" feature and being able to add as much as we want.

So for instance, if I want to have 3 ewma_price and 2 stdev I could.

I would just click on "add a safety" chose among what we have and add it. :)
A bit in the same way you can add an indicator in tradingview.

What do you think about that?

Best,

Camille

**Comment by ctubio** [comment]
that goes in the direction of the new UI, thanks for your pro suggestions'¡

**Comment by ctubio** [comment]
lemme close this as we have the same abstract idea and still will take a few to be realizable

**Comment by Camille92** [comment]
No probs! Very glad that we have the same idea :)
