### ISSUE TITLE
A little help?

### ISSUE THREAD

**Issue by cjh156** [ctubio/Krypto-trading-bot#65]
I will admit that I dont know much about coding but that doesnt mean I cant learn and contribute. I have developed my own strategy that I believe can be profitable. But I am having a hard time even finding where I can alter a current strategy. Can anyone give me any pointers on how I can begin to code my strategy? Im sorry for posting such a basic question.

**Comment by ctubio** [comment]
https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/quoting-engine.ts is a nice place to start, here the Quotes are calculated, and from here on all methods are called using this calculated Quotes; i believe you want to customize the values of the calculated Quotes.

hope it helps''
