### ISSUE TITLE
Heroku DepFailed

### ISSUE THREAD

**Issue by prohealthbox** [ctubio/Krypto-trading-bot#654]
i am trying to deploy at heroku, but fails..
please find below build log, any help will be appriciated.

-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 8.x...
       Downloading and installing node 8.9.4...
       Using default npm version: 5.6.0
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Installing node modules (package.json + package-lock)
       up to date in 5.478s
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
 !     This app may not specify any way to start a node process
       https://devcenter.heroku.com/articles/nodejs-support#default-web-process-type
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...
       Done: 70.1M
-----> Launching...
       Released v4
       https://kryptotradingbot.herokuapp.com/ deployed to Heroku

**Comment by ctubio** [comment]
can you paste in one line the error message? i dont see any error there :S
thanks''

(you may have more luck asking ina heroku forum :dancer:)
