### ISSUE TITLE
Compile in centos6 can not find build-x86_64-pc-linux-gnu/local/lib/K-x86_64-pc-linux-gnu.a

### ISSUE THREAD

**Issue by edigar007** [ctubio/Krypto-trading-bot#655]
I want to compile K in Centos6. I do these below:
1. Install a gcc g++ 6.4.0
2. Make soft link 
 x86_64-pc-linux-gnu-cc -> /usr/local/bin/gcc
 x86_64-pc-linux-gnu-ar -> /usr/bin/ar
(I think this is not a good solution, but with out this , it will compile error)
3. I get K from git clone
4. make dist with no errors
5. make clients www css bundle docroot
6. make K but it link error 
x86_64-pc-linux-gnu-g++: error：build-x86_64-pc-linux-gnu/local/lib/K-x86_64-pc-linux-gnu.a：no such file or directory
Problem is : how can i get static library build-x86_64-pc-linux-gnu/local/lib/K-x86_64-pc-linux-gnu.a

thanks for your help, best wishes

**Comment by donaldforest** [comment]
make build

**Comment by edigar007** [comment]
@donaldforest thanks for your help
I download v0.4.3.2 and mv K-x86_64-linux-gnu.a to K-x86_64-pc-linux-gnu.a then make, i got this:

/usr/bin/ld: BFD version 2.20.51.0.2-5.47.el6_9.1 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

how i slove this?

how i get the  K-x86_64-linux-gnu.a from compile myself? or it is not open sources?

**Comment by donaldforest** [comment]
make clean
make dist
make build

**Comment by ctubio** [comment]
try with
```
CHOST=`g++ -dumpmachine` make whatever
```
