### ISSUE TITLE
Bug: sqlite errors in recent version

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#658]
Hi,
since todays update I am getting the following error:

"09:25:27.994574 DB Warrrrning: Sqlite error: attempt to write a readonly database at DELETE FROM main.e WHERE time < 1519722327994;INSERT INTO main.e (id,json) VALUES(NULL,'{"ask":0.09625,"bid":0.09622,"fv":0.096235,"time":1519723527994}');."

Since I didn't change anything in my local config (file permissions in /data and such) and /data is writable I presume it's a bug?!

**Comment by ctubio** [comment]
are you sure you are not running two same bots again the same db file?

**Comment by Pat71** [comment]
Yes, I'm running only one bot at the moment...

**Comment by Pat71** [comment]
strange...the error occurs only only on BARUSD on hitbtc...other coins seem to work...
The DB-files are all the same...

**Comment by ctubio** [comment]
i had never experiencied a "read-only"  error in the database, i would suggest to `rm` the file for BARUSD at `/data/db/` and restart to let the bot initialize a new db file

**Comment by ctubio** [comment]
closing cos i cannot imagine any modification that could be done to resolve your issue (the database integration was not updated since many months ago), just `rm` the offensive file
