### ISSUE TITLE
Bring back old UI (or at least allow the new one to be disabled)

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#659]
While the new UI is surely fancy, I find it useless and superfluous.
And it is not really working/looking good on mobile devices.

So please bring either the old UI back or make it switchable via commandline (like "--disable-new-ui").

Thanks and keep up the good work!

**Comment by ctubio** [comment]
i dont care about mobiles because this is not a mobile app (yet)

what buttons/links you click so much that needs to be always visible?

**Comment by Pat71** [comment]
The buttons aren't the problem, the animation is. If you could just remove the animation, everything would be ok.

And I'm using the bot on the phone, i.e. on the bus. It would be sad if I couldn't use it anymore...

**Comment by ctubio** [comment]
ok will do a `--fixed-ui` argument to display both panels without useless animations; hope it will work for you then

**Comment by ctubio** [comment]
when you use the phone, is the little little layout where all panels are stacked vertically? or you have normal desktop layout with panels stacked horizontal?

because instead of an argument, the trigger could be the vertical layout if is the one that you have on the phone

**Comment by ctubio** [comment]
after next commit is still horrible positioned but at least should be usable without rotations/hidden panels.

will take care of the positions soOn''

thanks for your time reporting thiz''

**Comment by Pat71** [comment]
I'm reopening this issue because the "new" GUI is really annoying, even on PCs (and everyone I spoke with is agreeing on that).
So I'begging you to disable the new GUI or make it optional via a commandline-switch - what about the "--fixed-ui argument" you mentioned earlier??

**Comment by zmbbmz** [comment]
i support Pat71^^ please make --oldUI or --fixedUI. thanks!

**Comment by ctubio** [comment]
hope is better now
