### ISSUE TITLE
Availability of older releases

### ISSUE THREAD

**Issue by keeroo1337** [ctubio/Krypto-trading-bot#661]
In the last weeks, there have been lots of improvements of the K bot. I am very happy about the large number of new commits and releases. Nevertheless, I would like to use a bot version that was working for me under certain conditions which was right before and after the ewmaTrend release. The list of releases under https://github.com/ctubio/Krypto-trading-bot/releases/ goes back until release 4.3.0. The very earliest release of version 4 that is available for download still has the ewmaTrend. So the release that I am looking for is not available there.

Is there any chance to get access to releases of version 4 prior to the release 4.3.0?

**Comment by ctubio** [comment]
only way is by recompiling an older commit or by having saved the zip localy in advance, because on github there is a limit of 1Gb and try to keep below always by removing old zips
