### ISSUE TITLE
Some cli improvements

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#662]
Hello!
1) **[DONE]** If it possible add second space after word "BUY" in cli output to vertical price and val alignment:
![k_cli](https://user-images.githubusercontent.com/33358791/36843026-a7882d06-1d5e-11e8-9a89-2011dacee787.PNG)

2) **[DONE]**  Will be good to reserve at least 2 lines bottom for opened orders to prevent jumping all data in non naked mode. (This is not for all occasions but in most 90% cases we have max 1-2 opened orders in same time).

**Comment by donaldforest** [comment]
3. Can You please add wallet data to cli header?
Example:
![walet](https://user-images.githubusercontent.com/33358791/36849211-72d19ff0-1d74-11e8-86e5-97c8608c5b60.PNG)
like:
![wallet](https://user-images.githubusercontent.com/33358791/36849227-811a9fbc-1d74-11e8-963e-da811af75248.png)

**Comment by donaldforest** [comment]
4. Modify open orders:

> BID > 15f8ec58-10c8384b36e8: 0.02395203 BTC at price 8830.98000000 EUR

to

> BID > 15f8ec58-10c8384b36e8: 0.02395203 BTC at price 8830.98000000 EUR (total 211,519 EUR)

Like in Web UI and similar to cli orders history.

**Comment by ctubio** [comment]
many thanks for your suggestions''''

**Comment by donaldforest** [comment]
5. Transfer order ID in open orders to the end of order:

> ├ASK > 39a3c-48b2-8980a4ed: 0.05103874 BTC at price 9052.13000000 EUR (value 462.00930952 EUR).

change to

> ├ASK > 0.05103874 BTC at price 9052.13000000 EUR (value 462.00930952 EUR): 39a3c-48b2-8980a4ed.

Like for me this is more human friendly.

**Comment by donaldforest** [comment]
6) cli UI is more geek, then I think we must have a latency info in cli also.

7) Like for me more clear (like on candles charts)! Example:
![1](https://user-images.githubusercontent.com/33358791/37792788-d0ffc296-2e1d-11e8-9290-e13ecee0bfaa.png)

**Comment by ctubio** [comment]
just added `--latency` argument, soOn i will add to the cli screen; thanks for the suggestions''''
