### ISSUE TITLE
[FEATURE] Trades history stats inside mg.h

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#665]
I have an idea to use realtime trades history data inside my strategy.
And, i believe, it can be useful for all of us because we can make start/stop triggers based on last 1-3-5minutes quantity of trades.

**Comment by ctubio** [comment]
that is already a public OG var (https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/og.h#L8) already accessible from MG (https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/km.h#L756)

**Comment by ctubio** [comment]
MG is not using vars of OG since https://github.com/ctubio/Krypto-trading-bot/commit/757f01226d68a5493403504b49e63e9be10a6b6e#diff-802ed2dbe6b56e94a3e7b75bb3746213 but in that commit you have an example of how to use it (`simply ((OG*)broker)->tradesHistory`)

**Comment by serzhiio** [comment]
Oh.. great!
I thought this var is for current bot trades history only.

**Comment by ctubio** [comment]
yes that is, is not accumulating nothing in any periods; just a list of all previous trades

feel free to walk over it and extract any accumulated values

**Comment by serzhiio** [comment]
But i need all market trades history. Like in the UI at the right side.

5 марта 2018 г. 16:39 пользователь "Carles Tubio" <notifications@github.com>
написал:

**Comment by serzhiio** [comment]
So is it possible to get total number of all market buy/sell trades for the last 1-3-5 minutes?

**Comment by ctubio** [comment]
yup, tradesHistory have quantities and timestamps
