### ISSUE TITLE
kraken never ping

### ISSUE THREAD

**Issue by wiwi0123** [ctubio/Krypto-trading-bot#670]
the transaction passes but never goes to ping
![image](https://user-images.githubusercontent.com/6229771/37203941-a9ffaa28-238f-11e8-95d8-9e956e072b1b.png)

**Comment by donaldforest** [comment]
Features of the market!
You have a ping width about 50 ZEU.. Looks like is no those who buy your order by this price when stable spread = just 0.1!

**Comment by ctubio** [comment]
mm.. strange, lemme review XBT/EUR Kraken pings

**Comment by wiwi0123** [comment]
no she never passes I had 10 transaction waiting + - 30 min or the bot was spinning

**Comment by ctubio** [comment]
thanks for confirm the issue will review Kraken pings asap

**Comment by ctubio** [comment]
seems Kraken sends an object even if the docs says that [is an array of closed orders](https://www.kraken.com/help/api#get-closed-orders); will be fixed on next commit
