### ISSUE TITLE
Kraken first run error

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#671]
Today release, 4010 commit..
Not sure it help, cos second run goes normal, but in any case:

> Yikes!
> please copy and paste the error above into a new github issue (noworry for duplicates).
> If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new
> 
> - lastbeat: 1520792019262
> - os-uname: Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64
> - tracelog:
> ./app/server/K(_ZN1K2EV3wtfEi+0x920) [0x55630b30d8c0]
> /lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7f5c436ac060]
> /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7f5c436abfff]
> /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f5c436ad42a]
> ./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0xed) [0x55630b6dab9d]
> ./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x55630b651fe6]
> ./app/server/K(+0x4c80f9) [0x55630b6530f9]
> ./app/server/K(__gxx_personality_v0+0x2cd) [0x55630b652a1d]
> ./app/server/K(+0x565563) [0x55630b6f0563]
> ./app/server/K(+0x565d87) [0x55630b6f0d87]
> ./app/server/K(_ZN1K2EV3wtfEi+0xca1) [0x55630b30dc41]
> /lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7f5c436ac060]
> /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7f5c436abfff]
> /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f5c436ad42a]
> ./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d) [0x55630b6dac0d]
> ./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x55630b651fe6]
> ./app/server/K(+0x4c7031) [0x55630b652031]
> ./app/server/K(+0x4c732a) [0x55630b65232a]
> ./app/server/K(_ZN1K2Gw11waitForDataEv+0x983) [0x55630b31ffc3]
> ./app/server/K(_ZN1K2EV9asyncLoopMUlP5AsyncE_4_FUNES2_+0x86) [0x55630b3276f6]
> ./app/server/K(_ZZN5Async5startEPFvPS_EENUlP4PolliiE_4_FUNES4_ii+0x36) [0x55630b307876]
> ./app/server/K(_ZN4Loop3runEv+0x111) [0x55630b353921]
> ./app/server/K(_ZN1K2GW3runEv+0x15b) [0x55630b30bb1b]
> ./app/server/K(main+0x16cb) [0x55630b2fa06b]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f5c436992e1]
> ./app/server/K(_start+0x2a) [0x55630b2fad5a]
> 
> Yikes!
> please copy and paste the error above into a new github issue (noworry for duplicates).
> If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by ctubio** [comment]
what currency pairs was this?

**Comment by donaldforest** [comment]
API_CURRENCY=XBT/USD

**Comment by donaldforest** [comment]
+ UPD in same time bot can show 3 similar orders, for example ask, but in the same time is just one or no orders in kraken web interface!

**Comment by donaldforest** [comment]
I try after this troubles use **cxl?** and --lifetime=10000
If I right understood, --lifetime=10000 - this is 10 sec for order lifetime. But K cant cancel orders. No reaction.

**Comment by donaldforest** [comment]
This interface show orders faster https://trade.kraken.com/kraken/
but dont show order ID
Is always see this error when I try cancel any existing order:

> 901: Order id is invalid
> 
> What it means: The exchange’s API rejected your request because it was dealing with an order that, according to them, doesn’t exist.
> 
> What you can do: If you were trying to cancel an order, it’s possible it has already been filled or canceled. If you can’t figure out why you got this error, please contact support.

**Comment by ctubio** [comment]
thanks for the link to the new coinwatch interface; is horrible the legacy site of kraken xD

**Comment by ctubio** [comment]
lets fix Kraken at https://github.com/ctubio/Krypto-trading-bot/issues/741
