### ISSUE TITLE
Build error with docker 

### ISSUE THREAD

**Issue by scottiesan** [ctubio/Krypto-trading-bot#673]
sudo mkdir -p /data/db/
sudo chown 0 /data/db
make[1]: Leaving directory '/K'
mkdir -p app/server
make[1]: Entering directory '/K'
curl -L https://github.com/ctubio/Krypto-trading-bot/releases/download/0.4.x/v0.4.5.9-make[1]: Entering directory '/K' x86_64-linux-gnumake[1]: Leaving directory '/K'.tar.gz \
| tar xz && chmod +x build-*/local/bin/K-make[1]: Entering directory '/K' x86_64-linux-gnumake[1]: Leaving directory '/K'
curl: (3) [globbing] bad range in column 84
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 80: Connection refused
curl: (6) Could not resolve host: directory
curl: (3) <url> malformed
curl: (3) [globbing] bad range in column 22
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 80: Connection refused
curl: (6) Could not resolve host: directory
curl: (3) <url> malformed

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make[1]: *** [build] Error 2
Makefile:218: recipe for target 'build' failed
make[1]: Leaving directory '/K'
make: *** [docker] Error 2
Makefile:248: recipe for target 'docker' failed
The command '/bin/sh -c make docker' returned a non-zero code: 2
Scotts-MacBook:bot scottho$ 

Any suggestions will be greatly appreciated.  Thanks!!

**Comment by ctubio** [comment]
seems the environment variable `CHOST` have a wrong value

if the output of your `g++ -dumpmachine` is not supported, force a supported one with `CHOST=x86_64-linux-gnu`

or simply download the zip from https://github.com/ctubio/Krypto-trading-bot/releases

**Comment by ctubio** [comment]
finally this will be fixed at #682, i was wrong about the CHOST var :dancer:
