### ISSUE TITLE
cxl? and Kraken

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#676]
cxl? isnt work with Kraken at all.  Phantom orders accumulated more and more.
On Kraken side is no more than 1-2 orders, when K show 6+.. When I click delete orders red buttons orders returns back.

**Comment by ctubio** [comment]
maybe is another array turned into an object :S will review soOn

thanks for the report''

**Comment by donaldforest** [comment]
23 opened orders! But no orders on Kraken web UI side..
![kraken_cli](https://user-images.githubusercontent.com/33358791/37568828-9808ba22-2aeb-11e8-9a22-b179d2c30433.PNG)
