### ISSUE TITLE
error code 2

### ISSUE THREAD

**Issue by valourus** [ctubio/Krypto-trading-bot#677]
When I start the bot I get error code 2.. what does this mean?
`/home/pi/Desktop/l/Krypto-trading-bot-master/K.sh: 117: /home/pi/Desktop/l/Krypto-trading-bot-master/K.sh: ./app/server/K: Exec format error
K crashed with exit code 2.. Respawning..
`

thanks in advance :)

**Comment by ctubio** [comment]
about 32bits architectures, only armv7 is supported, can you see what is the output of your `uname -a`?

if says arm6, here is your problem

**Comment by valourus** [comment]
I ran uname -a but it says armv7l
`Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux`

**Comment by ctubio** [comment]
thanks for the info''' ok now im not sure if armv71 is supported like armv7 is; lemme test it

**Comment by ctubio** [comment]
can you paste the output of your `g++ -dumpmachine` too please?  i will try the very same if possible

**Comment by valourus** [comment]
output: 
`arm-linux-gnueabihf`

**Comment by valourus** [comment]
I did a clean install and it gave and error.. I ran it again and it worked.. so weird..

If you get this error just do a clean install of this project.(maybe run make reinstall twice)

**Comment by ctubio** [comment]
coOl; thanks again'' anyway i will test a bit to see if i can reproduce it and avoid it :S
