### ISSUE TITLE
Dark theme charts is really dark!

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#678]
Hello!
Need something to do with charts background or legend font colors in dark theme. Is same and dark and merges:
![darkisdark](https://user-images.githubusercontent.com/33358791/37373296-0f069cb6-2727-11e8-8c81-775502987133.PNG)

**Comment by ctubio** [comment]
yea and on light theme is the opposite xD will fix soOn

thanks for the report''
