### ISSUE TITLE
Error when connecting to a Api fine when Null

### ISSUE THREAD

**Issue by ndgm2016** [ctubio/Krypto-trading-bot#681]
When i run on test account as Null all works fine.

Ass soon as i pick a api i am getting error 
 Errrror: Unable to fetch data from POLONIEX for symbol "LTC_BTC", possible error message: {"error":"CURL Error: Couldn't resolve host name"}.

Also seems like its trying to go out of port 0
17:04:34.463047 UI ready over HTTP on external port 0.
Full error log

K build x86_64-linux-gnu 2018-03-13 19:02:34.
v0.4.5+12 (zip install).
17:04:34.462778 DB /data/db/K.POLONIEX.BTC.LTC.db loaded OK.
17:04:34.463047 UI ready over HTTP on external port 0.
17:04:34.463279 QP Warrrrning: using default values for Quoting Parameters.
17:04:34.463381 DB loaded 0 historical Trades.
17:04:34.463456 DB loaded 0 STDEV Periods.
17:04:34.463540 DB loaded 0 historical FairValues.
17:04:34.463601 DB loaded 0 historical Profits.
17:04:34.463665 DB loaded TBP = 0.00000000 BTC.
17:04:35.976748 CF Errrror: Unable to fetch data from POLONIEX for symbol "LTC_BTC", possible error message: {"error":"CURL Error: Couldn't resolve host name"}.
K crashed with exit code 1.. Respawning..

Also the First part of the config K file

#  ▌ II ▐_______________________________________________.
#  ▌¯¯¯¯                                                .
#  █ UI_USERNAME                                        .
#  ██ - Allows any username, to authenticate UI connections.
#UI_USERNAME=1234abcd
UI_USERNAME=NULL
#  ▌____________________________________________________.
#  █ UI_PASSWORD                                        .
#  ██ - Allows any password, to authenticate UI connections.
#UI_PASSWORD=efgh5678
UI_PASSWORD=NULL
#  ▌____________________________________________________.
#  █ UI_OPENPORT                                        .
#  ██ - Allows any port number, to listen to UI connections.
#UI_OPENPORT=6969
UI_OPENPORT=3009

**Comment by ctubio** [comment]
can you share what is the value of you `API_HTTP_ENDPOINT` var?

i donno what host name curl is trying to resolve without it

**Comment by ctubio** [comment]
` UI ready over HTTP on external port 0.` means is not reading correctly the value of `UI_OPENPORT`; mostly possible is not reading the whole config file, or the config file is corrupt; consider to recreate your config file from a fresh copy of the distributed file
