### ISSUE TITLE
Docker install error

### ISSUE THREAD

**Issue by lesiromanu** [ctubio/Krypto-trading-bot#682]
Hello.
I'm getting the following error while installing with docker.

`mkdir -p app/server
make[1]: Entering directory '/K'
curl -L https://github.com/ctubio/Krypto-trading-bot/releases/download/0.4.x/v0.4.5.12-make[1]: Entering directory '/K' x86_64-linux-gnumake[1]: Leaving directory '/K'.tar.gz \
| tar xz && chmod +x build-*/local/bin/K-make[1]: Entering directory '/K' x86_64-linux-gnumake[1]: Leaving directory '/K'
curl: (3) [globbing] bad range in column 85
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: Entering
curl: (6) Could not resolve host: directory
curl: (3) <url> malformed
curl: (3) [globbing] bad range in column 22
curl: (6) Could not resolve host: Leaving
curl: (6) Could not resolve host: directory
curl: (3) <url> malformed

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Makefile:218: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/K'
Makefile:248: recipe for target 'docker' failed
make: *** [docker] Error 2
The command '/bin/sh -c make docker' returned a non-zero code: 2`

The error lies in the makefile i believe:

`build:
	curl -L https://github.com/ctubio/Krypto-trading-bot/releases/download/$(MAJOR).$(MINOR).x/v$(MAJOR).$(MINOR).$(PATCH).$(BUILD)-$(CHOST).tar.gz \
	| tar xz && chmod +x build-*/local/bin/K-$(CHOST)`

**Comment by ctubio** [comment]
seems the same as https://github.com/ctubio/Krypto-trading-bot/issues/673

ook i finally understood, some make output is in the middle of the url to be downloaded, andcurl thinks is a directory cos the new lines and garbage text looks like

thanks for insist on this will fix soOn

**Comment by ctubio** [comment]
does it helps the last commit? or make still breaks the url to download?

(im not sure why i was not able to reproduce this yet)

**Comment by lesiromanu** [comment]
Now it downloads correctly. But i'm still having problems to make it run on a Windows Docker. Still working on it

**Comment by ctubio** [comment]
coOl; feel free to paste any log even if the issue is closed

thanks for confirm'''
