### ISSUE TITLE
Issue loading gdax certificates with Raspberry PI 3

### ISSUE THREAD

**Issue by rrodrigonuez** [ctubio/Krypto-trading-bot#683]
unable to load certificate
1995847072:error:0906D06C:PEM routines:PEM_read_bio:no start ine:../crypto/pem/pem_lib.c:691:Expecting: TRUSTED CERTIFICATE
Makefile:307: recipe for target 'gdax' failed
make[3]: *** [gdax] Error 1
make[3]: Leaving directory '/home/pi/K'
Makefile:254: recipe for target 'link' failed
make[2]: *** [link] Error 2
make[2]: Leaving directory '/home/pi/K'
Makefile:240: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/pi/K'
Makefile:259: recipe for target 'reinstall' failed
make: *** [reinstall] Error 2

**Comment by ctubio** [comment]
can you simply run the bare command without make hidding the outputs with:
```
openssl s_client -showcerts -connect fix.gdax.com:4198 -CApath /etc/ssl/certs < /dev/null 2> /dev/null | openssl x509 -outform PEM > etc/sslcert/fix.gdax.com.pem
```
from the K folder so it can find the sslcert files at etc folder; maybe prints some more interesting output?

**Comment by ctubio** [comment]
if your local openssl binary give you errors you can compile the latest version of openssl with `make openssl` and then use it like in:
```
build-arm-linux-gnueabihf/local/bin/openssl s_client -showcerts -connect fix.gdax.com:4198 -CApath /etc/ssl/certs < /dev/null 2> /dev/null | build-arm-linux-gnueabihf/local/bin/openssl x509 -outform PEM > etc/sslcert/fix.gdax.com.pem
```

**Comment by rrodrigonuez** [comment]
Problem was that internal time was not correct, so could not donwload certificates.
Thank you for your help dude!

**Comment by ctubio** [comment]
if you agree can you share how you fixed the time?

maybe can be included into the makefile :dancer:

**Comment by rrodrigonuez** [comment]
Sure, I had a very restrictive set of rules on my firewall and was blocking ntp connections to go through, I just enable this rule in my firewall, and resync my date/time in my Raspberry PI and bualá! I could load gdax certificates and compile K!

**Comment by ctubio** [comment]
xD ok thanks well noway to do it from the makefile :dancer:
