### ISSUE TITLE
Kraken Unable to calculate quote, missing market data.

### ISSUE THREAD

**Issue by valourus** [ctubio/Krypto-trading-bot#684]
I got 
`Unable to calculate quote, missing market data.`

I looked at earlier issues like this but i coudnot find a clear solution.

thanks in advance :)

Market: kraken
pair: ETH/EUR
life trading

**Comment by ctubio** [comment]
can you please share what is the exact value youhave at API_CURRENCY? is `ETH/EUR` exactly?

**Comment by valourus** [comment]
mhh yea, this is my config maybe I missed something?
https://pastebin.com/KCmT8RtL

**Comment by ctubio** [comment]
seems super correct; lemme test it anyway :S

**Comment by valourus** [comment]
thanks if you need any extra info let me know :)

**Comment by ctubio** [comment]
lets fix Kraken at https://github.com/ctubio/Krypto-trading-bot/issues/741
