### ISSUE TITLE
Unable to connect to GDAX

### ISSUE THREAD

**Issue by tkupka** [ctubio/Krypto-trading-bot#686]
I'm unable to connect to GDAX.  Only such message appears: Connecting to exchange..

I tried several API keys with the same result. 

I'm able to see my wallet data and also bid and ask prices/volume.

Probably only trades are now working.

API_EXCHANGE=COINBASE
API_HTTP_ENDPOINT=https://api.gdax.com
API_WSS_ENDPOINT=wss://ws-feed.gdax.com

**Comment by ctubio** [comment]
consider to show some logs..

the expected is:
```
19:30:45.999293 GW COINBASE FIX success Logon.
19:30:46.070903 GW COINBASE WS Streaming book levels.
```

**Comment by tkupka** [comment]
str_stats: 2 block(s), 10 data byte(s), 116 control byte(s)
16:11:04.963297 GW COINBASE allows client IP.
16:11:04.963377 GW COINBASE:
- autoBot: no
- symbols: BTC-EUR
- minTick: 0.01000000
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000.
16:11:06.412152 GW COINBASE FIX Logout, reconnecting in 21s..
16:11:06.880477 GW COINBASE WS Streaming book levels.

**Comment by ctubio** [comment]
can you validate the connectivity? (check if stunnel is having some error by uncommenting the log configs are `etc/stunnel.conf`)
