### ISSUE TITLE
Bot is trading with losses at KRAKEN

### ISSUE THREAD

**Issue by zac87** [ctubio/Krypto-trading-bot#687]
Hey,

I have a unlocked version of the Bot, but unluckily the bot is trading with big losses...
I have setup everything like described in the MANUAL, still no profits.

Whats the issue ? Am I using the wrong trading strategy (JOIN) ?
---
```
app exchange: //Kraken
app version: undisclosed
OS distro: Ubuntu 16
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
the issue is not a bug; consider the irc channel
