### ISSUE TITLE
Question / help: running clean pings automatically

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#69]
Hi Carles,

I look for adding a line that would trigger the "clean pings" button automatically every few hours or so.

I guess it should use "moment" but I don't know what is the way to call this function and where to put it.

Can you please tell me what's the name of this function and where I can find it?

I understand quite well the "server" part of the program but not as well the web UI one :)

Thank you very much :)

**Comment by ctubio** [comment]
inside the constructor of src/server/broket.ts, maybe near the other timer to cancel orders:
```
_timeProvider.setInterval(() => { this.cleanOrders(); }, moment.duration(5, 'minutes'));
```
or sumshit similar (didnt tested thiz line)

hope it helps'

**Comment by Camille92** [comment]
I'll look at that thank you :)
