### ISSUE TITLE
Signal 6 Aborted(Three-Headed Monkey found)

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#692]
16:47:38.228541 UI 1 currently connected, last connection was from 87.255.2.181.
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be string, but is object

16:48:55.033672 Errrror: Signal 6 Aborted(Three-Headed Monkey found):
- upstream: HITBTC
- currency: ETH/USD
- roll-out: 1522169258088
- lastbeat: 1522169335031
- os-uname: Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64
- tracelog:
./app/server/K(_ZN1K2EV3wtfEi+0x8eb) [0x55c082fec2cb]
/lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7fced7a6a060]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7fced7a69fff]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fced7a6b42a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d) [0x55c0833bd8ed]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x55c083331306]
./app/server/K(+0x4c9351) [0x55c083331351]
./app/server/K(+0x4cb40a) [0x55c08333340a]
./app/server/K(_ZN1K2Gw7waitForINS_6mOrderEEEjRSt6futureISt6vectorIT_SaIS5_EEERSt8functionIFvS5_EE+0x3ab) [0x55c082ffdc5b]
./app/server/K(_ZN1K2EV9asyncLoopMUlP5AsyncE_4_FUNES2_+0x945) [0x55c083006765]
./app/server/K(_ZZN5Async5startEPFvPS_EENUlP4PolliiE_4_FUNES4_ii+0x36) [0x55c082fe5bd6]
./app/server/K(_ZN4Loop3runEv+0x111) [0x55c083033621]
./app/server/K(_ZN1K2GW3runEv+0x15b) [0x55c082fea55b]
./app/server/K(main+0x178c) [0x55c082fd7e3c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7fced7a572e1]
./app/server/K(_start+0x2a) [0x55c082fd8b1a]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

16:48:55.033928 GW HITBTC Quoting state changed to DISCONNECTED.
16:48:55.034085 GW HITBTC Attempting to cancel all open orders, please wait..
16:48:55.063654 GW HITBTC cancel all open orders OK.
terminate called recursively

16:48:55.072317 Errrror: Signal 6 Aborted(Three-Headed Monkey found):
Errrror: Signal 6 Aborted(Three-Headed Monkey found):
- upstream: HITBTC
- currency: ETH/USD
- roll-out: 1522169258088
- lastbeat: 1522169335031
- os-uname: Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64
- tracelog:
./app/server/K(_ZN1K2EV3wtfEi+0x8eb) [0x55c082fec2cb]
/lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7fced7a6a060]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7fced7a69fff]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fced7a6b42a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d) [0x55c0833bd8ed]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x55c083331306]
./app/server/K(+0x4c9351) [0x55c083331351]
./app/server/K(+0x4cb40a) [0x55c08333340a]
./app/server/K(_ZN1K2Gw7waitForINS_6mOrderEEEjRSt6futureISt6vectorIT_SaIS5_EEERSt8functionIFvS5_EE+0x3ab) [0x55c082ffdc5b]
./app/server/K(_ZN1K2EV9asyncLoopMUlP5AsyncE_4_FUNES2_+0x945) [0x55c083006765]
./app/server/K(_ZZN5Async5startEPFvPS_EENUlP4PolliiE_4_FUNES4_ii+0x36) [0x55c082fe5bd6]
./app/server/K(_ZN4Loop3runEv+0x111) [0x55c083033621]
./app/server/K(_ZN1K2GW3runEv+0x15b) [0x55c082fea55b]
./app/server/K(main+0x178c) [0x55c082fd7e3c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7fced7a572e1]
./app/server/K(_start+0x2a) [0x55c082fd8b1a]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

- lastbeat: 1522169335069
- os-uname: Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64
- tracelog:
./app/server/K(_ZN1K2EV3wtfEi+0x8eb) [0x55c082fec2cb]
/lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7fced7a6a060]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7fced7a69fff]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fced7a6b42a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0xed) [0x55c0833bd87d]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x55c083331306]
./app/server/K(+0x555969) [0x55c0833bd969]
./app/server/K(__gxx_personality_v0+0x2cd) [0x55c08333211d]
./app/server/K(+0x5685a3) [0x55c0833d05a3]
./app/server/K(+0x568dc7) [0x55c0833d0dc7]
./app/server/K(_ZN1K2EV3wtfEi+0xc69) [0x55c082fec649]
/lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7fced7a6a060]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7fced7a69fff]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fced7a6b42a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d) [0x55c0833bd8ed]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x55c083331306]
./app/server/K(+0x4c9351) [0x55c083331351]
./app/server/K(+0x4cb40a) [0x55c08333340a]
./app/server/K(_ZN1K2Gw7waitForINS_6mOrderEEEjRSt6futureISt6vectorIT_SaIS5_EEERSt8functionIFvS5_EE+0x3ab) [0x55c082ffdc5b]
./app/server/K(_ZN1K2EV9asyncLoopMUlP5AsyncE_4_FUNES2_+0x945) [0x55c083006765]
./app/server/K(_ZZN5Async5startEPFvPS_EENUlP4PolliiE_4_FUNES4_ii+0x36) [0x55c082fe5bd6]
./app/server/K(_ZN4Loop3runEv+0x111) [0x55c083033621]
./app/server/K(_ZN1K2GW3runEv+0x15b) [0x55c082fea55b]
./app/server/K(main+0x178c) [0x55c082fd7e3c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7fced7a572e1]
./app/server/K(_start+0x2a) [0x55c082fd8b1a]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by ctubio** [comment]
```c++
inline void timer_1s() {                                      _debugEvent_
  if (gwT_countdown and gwT_countdown-- == 1)
    gw->hub->connect(gw->ws, nullptr, {}, 5000, gw->gwGroup);
  else ((QE*)engine)->timer_1s();
  if (sync_orders and !(gwT_5m % 2))  ((EV*)events)->async(gw->orders);
  if (sync_levels /*and !(gwT_5m % 3)*/)  ((EV*)events)->async(gw->levels);
  if (FN::trueOnce(&gw->forceUpdate)
    or !(gwT_5m % 10))                ((EV*)events)->async(gw->wallet);
  if (sync_trades and !(gwT_5m % 30)) ((EV*)events)->async(gw->trades);
  if (++gwT_5m == 5) {
    gwT_5m = 0;
    if (qp->cancelOrdersAuto)         ((EV*)events)->async(gw->cancelAll);
  }
};
void waitTime() {                                             _debugEvent_
  sync_levels = !gw->async_levels();
  sync_trades = !gw->async_trades();
  sync_orders = !gw->async_orders();
  if (!sync_levels) gwConnect();
  ((EV*)events)->tServer->setData(this);
  ((EV*)events)->tServer->start([](Timer *tServer) {
    ((GW*)tServer->getData())->timer_1s();
  }, 0, 330);
};
```

**Comment by ctubio** [comment]
lets discuss this on irc cos im not able to reproduce it

**Comment by serzhiio** [comment]
any news?
