### ISSUE TITLE
Pongs become pings option

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#696]
Hi Carles and everyone,

After our talk of tonight, I've been thinking a bit about how to improve Boomerang and harmonize it with ping-pong.

The solution I came up with is to make pongs becoming pings!

Now when you make a trade using Boomerang, once a trade is closed, you might run out of pings to match to and end up selling only at ping width price.

So let's say you're using ANY boomerang with "aggressive" setting with a ping width of 5 and a pong width of 20. You make your first buy at 7000 and sell later at 7020.

But now that you're out of Pings trade to match so you will buy back likely at 7015! (following your ping width setting) and then try to sell at 7035. (and keep going like that).

But now if instead of considering the pong trade as the end, you change it into a valid Ping, you will now try to buy back at 7000!

So more profits for you :)

I think it's a quite easy option to implement and will be very interesting to have in order to make boomerang definitely the best option!

Tell me what you think about it and if you have any question!

Happy Easter to all!

Camille

**Comment by ctubio** [comment]
this can be easily done by simply recording the last trade on each side, and apply that price to the safety of the opposite side; we currently do this for SIZE, lets do it also for PRICE and lets stop waking the whole history of trades for pingpong; with the last trade in history in each side is enough

will be done this way soOn if no further comments on this issue'¡
thanks'''

**Comment by Camille92** [comment]
Yep totally what we need, but keep reading up to the most recent posts haha!


Ps: I don't think that checking size if useful. :P

Le jeu. 5 juil. 2018 19:48, Carles Tubio <notifications@github.com> a
écrit :

**Comment by ctubio** [comment]
this means then that `pongAt` option should be hidden when `safety` is `PingPong`, do you agree?

ima read #694 (and maybe do together) before do this

**Comment by ctubio** [comment]
yea im considering the removal of the size check, it can go in spiral down until 0.0000001 xD

**Comment by Camille92** [comment]
Haha not sure what you mean by going in spiral!

Have a look of the latest post, it's the clearer about what pinpong can
become !

Le jeu. 5 juil. 2018 19:52, Carles Tubio <notifications@github.com> a
écrit :

**Comment by ctubio** [comment]
Ok lers close this and fux ut at #754 since borh talk about using price instead of size/volume for pingpong safety

Many thanks for the explanations!
