### ISSUE TITLE
HitBTC Latest Commit Crashing

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#697]
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be string, but is object

11:50:23.262969 Errrror: Signal 6 Aborted(Three-Headed Monkey found):
Errrror: Signal 6 Aborted(Three-Headed Monkey found):
- upstream: HITBTC
- currency: COSS/BTC
- roll-out: 1522583095770
- lastbeat: 1522583423236
- os-uname: Linux 4.14.0-0.bpo.3-amd64 #1 SMP Debian 4.14.13-1~bpo9+1 (2018-01-14) x86_64
- tracelog:
./app/server/K(_ZN1K2EV3wtfEi+0x8eb) [0x55dfd9974dfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030) [0x7f862efe9030]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7f862efe8fcf]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f862efea3fa]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d) [0x55dfd9d428ad]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x55dfd9cb9c86]
./app/server/K(+0x4c6cd1) [0x55dfd9cb9cd1]
./app/server/K(+0x4c6fca) [0x55dfd9cb9fca]
./app/server/K(_ZN1K2Gw7waitForINS_6mOrderEEEjRSt6futureISt6vectorIT_SaIS5_EEERSt8functionIFvS5_EE+0x3ab) [0x55dfd998661b]
./app/server/K(_ZN1K2EV9asyncLoopMUlP5AsyncE_4_FUNES2_+0x945) [0x55dfd998f0a5]
./app/server/K(_ZZN5Async5startEPFvPS_EENUlP4PolliiE_4_FUNES4_ii+0x36) [0x55dfd996f0a6]
./app/server/K(_ZN4Loop3runEv+0x111) [0x55dfd99bb5e1]
./app/server/K(_ZN1K2GW3runEv+0x15b) [0x55dfd997314b]
./app/server/K(main+0x173a) [0x55dfd9962a5a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f862efd62b1]
./app/server/K(_start+0x2a) [0x55dfd996373a]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

- lastbeat: 1522583423260
- os-uname: Linux 4.14.0-0.bpo.3-amd64 #1 SMP Debian 4.14.13-1~bpo9+1 (2018-01-14) x86_64
- tracelog:
./app/server/K(_ZN1K2EV3wtfEi+0x8eb) [0x55dfd9974dfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030) [0x7f862efe9030]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7f862efe8fcf]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f862efea3fa]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0xed) [0x55dfd9d4283d]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x55dfd9cb9c86]
./app/server/K(+0x4c7d99) [0x55dfd9cbad99]
./app/server/K(__gxx_personality_v0+0x2cd) [0x55dfd9cba6bd]
./app/server/K(+0x565203) [0x55dfd9d58203]
./app/server/K(+0x565a27) [0x55dfd9d58a27]
./app/server/K(_ZN1K2EV3wtfEi+0xc69) [0x55dfd9975179]
/lib/x86_64-linux-gnu/libc.so.6(+0x33030) [0x7f862efe9030]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7f862efe8fcf]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f862efea3fa]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d) [0x55dfd9d428ad]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x55dfd9cb9c86]
./app/server/K(+0x4c6cd1) [0x55dfd9cb9cd1]
./app/server/K(+0x4c6fca) [0x55dfd9cb9fca]
./app/server/K(_ZN1K2Gw7waitForINS_6mOrderEEEjRSt6futureISt6vectorIT_SaIS5_EEERSt8functionIFvS5_EE+0x3ab) [0x55dfd998661b]
./app/server/K(_ZN1K2EV9asyncLoopMUlP5AsyncE_4_FUNES2_+0x945) [0x55dfd998f0a5]
./app/server/K(_ZZN5Async5startEPFvPS_EENUlP4PolliiE_4_FUNES4_ii+0x36) [0x55dfd996f0a6]
./app/server/K(_ZN4Loop3runEv+0x111) [0x55dfd99bb5e1]
./app/server/K(_ZN1K2GW3runEv+0x15b) [0x55dfd997314b]
./app/server/K(main+0x173a) [0x55dfd9962a5a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f862efd62b1]
./app/server/K(_start+0x2a) [0x55dfd996373a]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by serzhiio** [comment]
So, i'm not the only one.
#692

**Comment by serzhiio** [comment]
@MiningInMySleep have you customized your code?

**Comment by MiningInMySleep** [comment]
@serzhiio No. Everything is vanilla.

**Comment by ctubio** [comment]
many thanks for the info'' im not reproducing this but will rethink the parser of hitbtc soOn''

**Comment by serzhiio** [comment]
This problem seems solved...
Observing no reconnects. Working quite stable.

**Comment by ctubio** [comment]
hope this doesn't happen anymore after latest commits
