### ISSUE TITLE
Submit Order button inop

### ISSUE THREAD

**Issue by lodcomm** [ctubio/Krypto-trading-bot#698]
Hey Folks,
I upgraded to the latest commit.. The "Submit Order" button/Function is still inoperative.  Any idea on a fix for this issue?

---
```
app exchange: Coinbase/BTC/USD
app version: undisclosed
OS distro: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by lodcomm** [comment]
any update on this?

**Comment by ctubio** [comment]
yep, incoming'''
