### ISSUE TITLE
Ghost orders

### ISSUE THREAD

**Issue by piotrekkaminski** [ctubio/Krypto-trading-bot#699]
If something crashes (power outage etc) later orders get removed from exchange but they stay visible in bot. If you remove them by clicking X, they come back in a few seconds. Checking directly open orders on exchange, they are not open. 

![image](https://user-images.githubusercontent.com/1714545/38457789-a20af93a-3a5a-11e8-9be5-ffb179c10ca9.png)

**Comment by nspassov** [comment]
Which exchange are you using? I am having the opposite issue with Bitfinex: apparently sometimes orders cannot be cancelled successfully, so on BFX I see way more orders than the bot lists (either in console or in web interface). Has anyone else experienced that?

**Comment by piotrekkaminski** [comment]
It is on HitBTC. Yeah, restarting fixes that.

**Comment by ctubio** [comment]
im sorry here works nice hitbtc since months ago, im not sure how to reproduce this
(about bitfinex, it was recently updated at https://github.com/ctubio/Krypto-trading-bot/commit/b32e7a7905d5ee88d4794862fb221f904b8142d1 and now it doesnt creates/cancels orders, instead it updates orders)
