### ISSUE TITLE
EWMA not saved on restart

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#70]
Hi Carles,

I'm sorry I come again to have an issue about this topic but TBP is not saved on start.

So is it just me or everyone?

Also the name of the files in data/db are not in the format exchange.base_currency.quote_currency but more like  K.4.84.0.db maybe the numbers are code for exchange/currency and etc but I wanted to check with you.

I did not really understand what is sent to the database but one explanation can be (maybe I'm totally wrong) that only tbp is sent to the database.

I think we just need to send the values of ewma to the database every minute when they are updated, and from those saved values calculate TBP. (Bonus it is less data sent because TBP can be updated many many times in a mn but not the ewma).

Please tell me if you have the same issue :) and if TBP and the ewma are sent there or only TBP!

Best,

Camille

(One day it will work for me lol!)

**Comment by Camille92** [comment]
Hey so I've been looking at the code and I think I understand where the problem is.

I don't see anywhere the ewma values to be sent to SQLite that's the reason why tbp is not saved (well it is saved but it's useless as K will update the tbp just after starting).

So correct me if I'm wrong but:

if in position-management we put:

```
this._sqlite.insert(Models.Topics.newShort, newShort);
this._sqlite.insert(Models.Topics.newMedium, newMedium);
this._sqlite.insert(Models.Topics.newLong, newLong);
```
and in main.ts:
```

const initShort = sqlite.load(Models.Topics.newShort).map(x => Object.assign(x, {time: new Date(x.time)}))[0];
const initMedium = sqlite.load(Models.Topics.newMedium).map(x => Object.assign(x, {time: new Date(x.time)}))[0];
const initLong = sqlite.load(Models.Topics.newLong).map(x => Object.assign(x, {time: new Date(x.time)}))[0];
```

Would that work?

The logic being, saving the last ewma value is something that lasts as we can build TBP from it while saving TBP is not efficient as K will change it with the new ewma values it creates on start.

Please tell me if I'm right :)

Best,
Camille

**Comment by ctubio** [comment]
ewmas are loaded from database at https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/statistics.ts#L23 therefore they are saved into the database; at https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/position-management.ts#L110

**Comment by Camille92** [comment]
Okay thank you, I'm going to investigate more in that direction then.

But Carles do you retrieve a correct ewma value and TBP after a crash/install/restart ?

**Comment by Camille92** [comment]
I have to say I really don't understand this line, why is there stdev at the end haha ?

**Comment by ctubio** [comment]
no, TBP is fucked for me too after restart, i will investigate the values after restart at https://github.com/ctubio/Krypto-trading-bot/issues/51 (not only TBP but all initial values, so if you allow me ima close this)

**Comment by Camille92** [comment]
Okay sure no probs, I thought I had part of the solution ! Sorry for duplicate

**Comment by ctubio** [comment]
note that currently what we save in the database is not ewmas, but FairValues; and ewmas are build up from the stored fairvalues (in case is usefull for your investigation)

**Comment by Camille92** [comment]
Huuumm yes it's quite important:

I'm not sure what do you mean by FairValues, it is the fair value of X periods registered ?
Because if yes we don't need that.

If we still use this formula for the ewma:

```
Multiplier = (2 / (Time periods + 1) ) = (2 / (10 + 1) )

EWMA ={Close - EWMA(previous period)} x multiplier + EWMA(previous period). 
```

We only need to save in the database the latest value of ewma.

So after a restart we assume that current price = close.
Then calculate a new ewma value, using the one registered as EWMA(previous period) 
Then drop the ewma saved and replace it by the newly calculated one. :)

Easy and only need 3 data saved and replaced every mn. :)

**Comment by Camille92** [comment]
OKKKK I found the issue!

So I was looking at the db files and yes the problem is that we save FV BUT looking here:
https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/statistics.ts#L11

We don't use Fv to calculate ewma but "previous" so when K restarts, it looks for previous, don't find one and so start a new ewma period!


AM I RIGHT ???? (I feel like I am but maybe I did not see a part of the code here!)

**Comment by Camille92** [comment]
Also, there seems to be something blocking to have more than 60 FV registered because I looked in all the files I have and none of them save more than 60FV (But it should not be an issue if we have the latest ewma instead:) )

**Comment by ctubio** [comment]
yea your right i believe, about the 60 fv the only limit is the `periods` value; otherwise if is always 60 no matter what periods are defiened, is a error

**Comment by Camille92** [comment]
Oh yes, I did not think about that so any problem for the FV.

So yes it makes total sense that it doesn't work I did not see that it's at the second level.

So we have a few FV at the second for keeping stdev, but nothing that keeps the ewma or something to calculate them (ewma are calculated at the minute level)

When I look in the database there are 6 tables:
'a' that seems to be a price but alone.
'e' the FV values for stdev 
'f' empty (maybe the settings ?)
's' the past trades
'sqlite_sequence' which seems to be some technical info
'v' which is the last saved TBP


I'm glad it makes sense now :)

**Comment by Camille92** [comment]
Is the solution described earlier (comment 2) a way to fix the problem, or at least going in the good direction?

**Comment by ctubio** [comment]
yea i think so, will get hands dirty soOn :dancer:

**Comment by Camille92** [comment]
You're the best !!
