### ISSUE TITLE
Full timestamp in output

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#701]
Hi,
I'm running stats on the output (Log) and it would be very nice if you could supply the full timestamp (incl. date), not just the time.
atm it's
12:13:23.538262 GW HITBTC TRADE BUY  
I'd like to have
2018-04-19T12:13:23.538262 GW HITBTC TRADE BUY

**Comment by ctubio** [comment]
thanks for the suggestion, i will try to add month and day (if is not too long); and leave without include the year; hope is enough this way (the year is too much redundant for me)
thanks''
