### ISSUE TITLE
Bitfinex atomic order update

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#702]
Hi Carles!
Some news about BFX:
https://medium.com/bitfinex/bitfinex-api-dev-update-april-ee10d59f75c2
They have implemented order update instead cancel+submit.
Could we implement this mechnism?

**Comment by ctubio** [comment]
https://docs.bitfinex.com/v2/reference#update-order
```js
ws.send(JSON.stringify([
  0, 'ou', null, {
    id: 1149698545,
    amount: '0.1',
    price: '500'
  }
])) 
```

**Comment by serzhiio** [comment]
I'll leave it here if need:
https://medium.com/bitfinex/node-js-client-2-0-0-beta-1-release-f8a5a41c53ed
