### ISSUE TITLE
Joining efforts with the Dexbot team ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#707]
Hi Carles and all,

I've been looking at the development from the DexBot team, they look motivated and work for a great cause. :)

I think both bots could benefit to be working closer together.

They have great GUI and and are growing, we have one of the best API implementations and some good strategies already incorporated.

What do you think about that?

dexbot.info
https://docs.google.com/document/d/1z2rMlMiMufHdZEirc8x9lKuqSHvLAsVDOYK3xr4AfYE/edit?ts=5addf8a2#
https://github.com/Codaone/DEXBot/wiki

@Codaone

**Comment by ctubio** [comment]
sorry im not magician of python but thanks for the references about UX ideas; agree mine are horrible xD :dancer:

(i dont see yet any other possible collaboration but UX ideas is big collaboration if you ask me!)

((if both apps had same language maybe then it could be more collaborative :S))

allow me to keep this genius post closed in the tasklist for ethernal reference; many thanks for the suggestions'''' will install DEXBot soOn (and commit some bugfix in exchange if i can! :D)

**Comment by ctubio** [comment]
btw did you integrated somehow magento with all this? xDD (i daily work with magento too :D)

**Comment by MarkoPaasila** [comment]
No, it's totally unrelated - although a magento plugin for cryptocurrency payments would be nice
