### ISSUE TITLE
Feature request: auto-switch between longpingfair and shortpingfair based on trend

### ISSUE THREAD

**Issue by bdbabiak** [ctubio/Krypto-trading-bot#709]
I think it would be good to have an option to automatically switch from longpingfair to shortpingfair based on the trend detector. We could even keep the same threshold and trend ultra and micro. Also would switch between the pair longpingaggressive and shortpingaggressive on the same. So, in summary, the ability to autoswitch from long to short pings in the ping pong safety based on the trend. The setting could be called 'switchpingfair' and 'switchpingaggressive'

**Comment by Camille92** [comment]
Why not but short ping aggressive or long ping aggressive nearly never have an effect on the price you sell and buy when using Boomerang. Let alone PingPong which is broken.
