### ISSUE TITLE
sqlite error: database is locked

### ISSUE THREAD

**Issue by lejacobroy** [ctubio/Krypto-trading-bot#71]
I just upgraded to the latest commit and I get this error after the webserver is up ( I receive a blank page).

tried to clear the node_modules and resinstall but still the same error.

**Comment by ctubio** [comment]
not sure if you agree but `rm /data/db/K*.db` may fix it

i never experiencied a locked database yet, so can't imagine whats wrong

**Comment by lejacobroy** [comment]
a reboot fixed it... no idea why but thank anyway!
