### ISSUE TITLE
Bitfinex

### ISSUE THREAD

**Issue by astronights** [ctubio/Krypto-trading-bot#710]
I tried changing the API_EXCHANGE, API_HTTP_ENDPOINT and the API_WSS-ENDPOINT to the Bitfinex values as provided in the source code.

But when I run it, it says no market data available, even with the API key and secret.

Please help.

**Comment by Camille92** [comment]
U need to make 1 manual trade

**Comment by astronights** [comment]
Thank you for the advice, but without market data how do I make a manual trade, since the web UI of the Bot is empty.

**Comment by Camille92** [comment]
go to bitfinex.com genius

**Comment by astronights** [comment]
Oh, right. Well, the API key and secret is from an already active Bitfinex account that has been trading actively in the past.

**Comment by Camille92** [comment]
Do you have funds in the target currency in that account?

**Comment by astronights** [comment]
Yes, those are there.

**Comment by Camille92** [comment]
what is the console saying?

**Comment by ctubio** [comment]
your config file is not configuring properly the credentials and/or the endpoint, this way the connection is expected to attempt to reconnect ethernaly; try to resetup your config file using the distributed config file as a carefully edited base and at the end the connection should connect at the first attempt

anyway consider the irc channel to resolve non-bugs
