### ISSUE TITLE
GUI not usable on mobile anymore

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#712]
Since one of the last updates, the GUI isn't usable on mobile phone anymore since it isn't resizable or scrollable anymore, so you can't see/reach the GUI elements on the far right. 
You can't see/reach the "save"-button, for example.

**Comment by donaldforest** [comment]
I was trying implement separate mobile version: https://github.com/ctubio/Krypto-trading-bot/pull/587
Looks, like need try do it again. Need suggestions.

**Comment by ctubio** [comment]
im sorry im so bad at gui devs, will try a second attempt soOn, not sure if forward or backward to the old ui, will see..

**Comment by ctubio** [comment]
:bulb: nice suggestion at https://github.com/ctubio/Krypto-trading-bot/issues/659#issuecomment-385726502

**Comment by ctubio** [comment]
hope is better now
