### ISSUE TITLE
ak-47 bullets

### ISSUE THREAD

**Issue by lukepg** [ctubio/Krypto-trading-bot#715]
Hello, I am running this with AK-47 and have problems with bullets and range%. I have % settings checked. My problems are:

1) Description of bullets is: "maximum amount of trades placed in each side" but event setting to 1 doesn't do anything to prevent trades, they keep going and

2) range% doesn't do anything to ofset order prices from each other. If it only works in cents then it doesn't seem to be using cents either

Is anyone else having these same issues?

---
```
app exchange: HitBtc/BTC/USD
app version: v0.4 (latest?)
OS distro: Ubuntu 
```

**Comment by ctubio** [comment]
Hello'' ak47 is suposed to have a value greater than 1 on bullets, try with 3
