### ISSUE TITLE
Qryptos exchange -0.075% maker fees !!!

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#716]
Carles, hi!
Lets have a look, -0.075% maker fees, good japan rooted exchange.
https://www.qryptos.com/

**Comment by serzhiio** [comment]
API docs link: https://developers.quoine.com
Cant find WS endpoints.

**Comment by serzhiio** [comment]
The say QRYPTOS sucks because of manual money withdrawal that takes a lot of time.

**Comment by ctubio** [comment]
ñets fuck Qryptos, seems as good as Kraken and Poloniex (an http [piece of shit](https://www.urbandictionary.com/define.php?term=piece%20of%20shit))
