### ISSUE TITLE
KRAKEN

### ISSUE THREAD

**Issue by scatterp** [ctubio/Krypto-trading-bot#717]
04/29 21:59:44.065215 Errrror: Signal 6 Aborted(Three-Headed Monkey found):
Errrror: Signal 6 Aborted(Three-Headed Monkey found):
- upstream: KRAKEN
- currency: BTC/EUR
- roll-out: 1525028362785
- lastbeat: 1525028383105
- os-uname: Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64
- tracelog: 
./app/server/K(_ZN1K2EV3wtfEi+0x896) [0x524836]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fdcf96cf4b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7fdcf96cf428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fdcf96d102a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x16d) [0x9100bd]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x878fc6]
./app/server/K() [0x879011]
./app/server/K() [0x87932a]
./app/server/K(_ZN1K2EV9asyncLoopMUlPN2uS5AsyncEE_4_FUNES3_+0xbd4) [0x53fcf4]
./app/server/K(_ZZN2uS5Async5startEPFvPS0_EENUlPNS_4PollEiiE_4_FUNES5_ii+0x56) [0x51e936]
./app/server/K() [0x56b4d3]
./app/server/K(_ZN2uS4Loop3runEv+0x8b) [0x56b8ab]
./app/server/K(_ZN1K2GW3runEv+0x15e) [0x522bde]
./app/server/K(main+0x15d5) [0x510105]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fdcf96ba830]
./app/server/K(_start+0x29) [0x510da9]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

- lastbeat: 1525028384062
- os-uname: Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64
- tracelog: 
./app/server/K(_ZN1K2EV3wtfEi+0x896) [0x524836]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fdcf96cf4b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7fdcf96cf428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fdcf96d102a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0xfd) [0x91004d]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x878fc6]
./app/server/K() [0x908389]
./app/server/K(__gxx_personality_v0+0x2ed) [0x878bbd]
./app/server/K() [0x91c193]
./app/server/K() [0x91c9b7]
./app/server/K(_ZN1K2EV3wtfEi+0xc02) [0x524ba2]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fdcf96cf4b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7fdcf96cf428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fdcf96d102a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x16d) [0x9100bd]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x878fc6]
./app/server/K() [0x879011]
./app/server/K() [0x87932a]
./app/server/K(_ZN1K2EV9asyncLoopMUlPN2uS5AsyncEE_4_FUNES3_+0xbd4) [0x53fcf4]
./app/server/K(_ZZN2uS5Async5startEPFvPS0_EENUlPNS_4PollEiiE_4_FUNES5_ii+0x56) [0x51e936]
./app/server/K() [0x56b4d3]
./app/server/K(_ZN2uS4Loop3runEv+0x8b) [0x56b8ab]
./app/server/K(_ZN1K2GW3runEv+0x15e) [0x522bde]
./app/server/K(main+0x15d5) [0x510105]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fdcf96ba830]
./app/server/K(_start+0x29) [0x510da9]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by ctubio** [comment]
many thanks, lets fix this at https://github.com/ctubio/Krypto-trading-bot/issues/741 since there is a newer tracelog
