### ISSUE TITLE
HitBTC Rate Limit Issue

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#719]
Seems to be new?

https://github.com/hitbtc-com/hitbtc-api/issues/156

Any way we can have some overall check if running multiple?

05/02 12:48:13.263460 GW HITBTC Warrrrning: Error or ignored response: {"error":{"code":429,"description":"","message":"Too many requests"},"id":1868,"jsonrpc":"2.0"}.

**Comment by ctubio** [comment]
currently each instance is independent from the others so it could be possible that 1 instance send a call to hitbtc while another still is waiting for a response (reproducing then hitbtc-com/hitbtc-api#156).

im not sure there is a solution currently since all instance are independent :(
