### ISSUE TITLE
Would you be able to post a readme on how to add another exchange?

### ISSUE THREAD

**Issue by keithmgould** [ctubio/Krypto-trading-bot#720]
Hello! Thank you for making this great bot :)

Regarding adding another exchange, I took a look and found a few places where I'd have to touch the codebase by searching the name of an existing exchange.

But I probably did not find all the places.

I think if there was a readme on how to do this, on where to touch the code, it would lead to a lot more contributors (like myself!).

Again, thank you for the great bot.

**Comment by ctubio** [comment]
sorry only the UI and the quoting engine are public (available in this repo)
the exchange integrations are not open source
