### ISSUE TITLE
allowing ping-/pongwidth under 0.1%

### ISSUE THREAD

**Issue by zmbbmz** [ctubio/Krypto-trading-bot#721]
Hi, it seems that the bot doesn't go below under 0.1% in ping-/pongwidth. In manual apmode an safety/pingpong 
In the acutal market situation, there aren't many coins with a big markt width. It would be nice, if the bot can go below the 0.1% restriction. (0.01-0.001%)

keep up the good work! greets chris

**Comment by ak9250** [comment]
I was digging around in the code and found a file called qe.h and changed two lines 131 and 226 by making it /1000 instead of dividing by a /100 for pong and pingwidth im not sure if that works though because in the UI i still cant lower it below .1%

**Comment by ctubio** [comment]
sorry this fix is not yet included in the tar builds (but will release next version ina few hours)

**Comment by ak9250** [comment]
just following up on this i still cant go below .1% on the web ui for ping or pongwidth.

**Comment by ctubio** [comment]
since e4f10ab `pingWidth` when `w%` is enabled have a limit precision of 3 decimals; the ui input allows a value like 0,001; are you sure you are using the latest version?

**Comment by ctubio** [comment]
git pull does not update nothing, the html is compiled into the binary, updating the sources does nothing; make sure you download and execute or compile yourself the latest binary

**Comment by ctubio** [comment]
see https://github.com/ctubio/Krypto-trading-bot#upgrade-to-the-latest-commit

**Comment by ak9250** [comment]
@ctubio apologies, yes that was the problem. It works now thanks

**Comment by ak9250** [comment]
@ctubio is it possible to allow ping and pongwidth to be any value >0%, the closer to 0% the better. I tried manually changing ds.h but that didnt work

**Comment by ctubio** [comment]
see https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/qe.h (search for where is used the function `quoteAtTopOfMarket`, there you will see that `minTick` is added as well as other vars; you may want to not make any additions)
