### ISSUE TITLE
Paying some one to  Setup on my windows $100

### ISSUE THREAD

**Issue by Willstar44** [ctubio/Krypto-trading-bot#726]
Im a noob and couldn't work out how to get this running with Docker on windows 10 pro ..

anyone want to try an help me out, I'm willing to pay for an hour of your time . 

Telegram the same name

**Comment by ctubio** [comment]
go to earn.com/analpaper or the irc channel, do not open bug issues for already solved situations

**Comment by ctubio** [comment]
irc://irc.freenode.net:6697/#tradingBot
https://kiwiirc.com/client/irc.freenode.net:6697/?theme=cli#tradingBot
