### ISSUE TITLE
K buying high and selling low.

### ISSUE THREAD

**Issue by ZeroCool940711** [ctubio/Krypto-trading-bot#727]
Hi there, I recently started using K and after a lot of testing haven't found a way to make K work correctly on Gdax with ETH-USD pair, right now its buying high and selling low, so far ive lost more than 200 USD and no profit at all, I know its because the market is on a down trend but I think K should have some way to protect my assets and not sell unless its making profit from the sell but havent found anything yet, does any of you have a good setup for ETH-USD you could share?

**Comment by ctubio** [comment]
this is a bug tracker, consider the irc channel for questions
