### ISSUE TITLE
K cant sell more than 0.02 BTC (askSize) wheni need sell all Available BTC

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#728]
Strange trouble. Looks like just in one pair on HitBTC.
TBP = 0. bidSz = 0.05, ... bot buy 0.05 BTC and stop trade (dont add ask askSize = 0.05). I set askSz = 0.02 or 0.01 ... bot start adding asks, but just in case smaller askSize than amount BTC Available on wallet.

Maybe it connected with unrealized part of BTC balance (coz another pairs trade ok with any sizes):
![btc_usd](https://user-images.githubusercontent.com/33358791/39965985-a8f38b18-56ac-11e8-94c8-a7bacaab7219.PNG)
![btc_hitbtc](https://user-images.githubusercontent.com/33358791/39965986-abe86302-56ac-11e8-8c63-4248e8f48bbd.PNG)

**Comment by ctubio** [comment]
sorry im not sure that i understand the issue, consider to share some logs on irc (will be easier)
