### ISSUE TITLE
UI ready over HTTPS on external port 0

### ISSUE THREAD

**Issue by brucetus** [ctubio/Krypto-trading-bot#731]
Another issue from me, sorry. Started a new VM, followed the installation instructions, and started up the bot without even editing the K.sh file. 

<img width="667" alt="screen shot 2018-05-13 at 10 58 47 pm" src="https://user-images.githubusercontent.com/31704711/39980672-e3b5617c-5701-11e8-8f73-91dcea599863.png">

Whatever I do I can't seem to get the UI_OPENPORT option to actually work and for me to be able to access the web UI.

**Comment by ctubio** [comment]
seems a issue of `--naked` argument, lemme review it; meanwhile you can remove `--naked`

**Comment by ctubio** [comment]
thanks for the screenshot''
