### ISSUE TITLE
Let's fix a meeting to fix strategy stuff!

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#732]
Hi Carles,

I think we really need to work on the strategy and fix some stuff (like ping pong for instance).

Do you have a time when you will be free so we could have a look at that together ?

PS: other dev welcome, the more the merrier!

Best,

Camille

**Comment by ctubio** [comment]
thiz weekend? (at any hour).

**Comment by Camille92** [comment]
Good! So let's say at 5pm on Saturday?

If it's good I put in on my agenda :)

**Comment by ctubio** [comment]
purrrfect'' see you on irc?

**Comment by Camille92** [comment]
Yep!
