### ISSUE TITLE
Bitfinex FIX protocol

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#739]
Okay! New info from BFX:
https://github.com/bitfinexcom/bfxfixgw

**Comment by serzhiio** [comment]
It looks like just wrapper around WebSocket! But i may be wrong...

**Comment by ctubio** [comment]
:( that is a fix wrapper of a websocket wrapper of a socket wrapper; i preffer more DIY :P thanks anyway for  the suggestion'¡
