### ISSUE TITLE
Adding new exchange 

### ISSUE THREAD

**Issue by bernardoteixeirabtc** [ctubio/Krypto-trading-bot#745]
Hey ctubio, I've integrated Michael's Tribeca with an exchange I use in Brazil called BitcoinTrade (bitcointrade.com.br) and it has been working decently well as the spreads are pretty decent over there. It seems to me however, that the code you have built has some significant improvements I was wondering if you do make the gateway code available for the Krypto-trading-bot? I'm happy to make (monetary or coding) contributions if needed.

**Comment by bernardoteixeirabtc** [comment]
ctubio, thanks for the information. If at some point you are interested in developing the bot for this exchange, where spreads are on average 1% let me know I can get you touch with them. I think there is a pretty good amount of money to be made there as there are not a lot of bots

**Comment by flfsbr** [comment]
Im intersted. Estou interessado.

**Comment by bernardoteixeirabtc** [comment]
ahah I can guarantee you that one is the best one in Brazil. All the other ones are really week, plus the other fees are insane. The API documentation is here: https://apidocs.bitcointrade.com.br/ but it is in Portuguese.

Also attached is the gateway I built for that exchange for the original Tribeca. 

[bitcointrade.zip](https://github.com/ctubio/Krypto-trading-bot/files/2099223/bitcointrade.zip)

**Comment by bernardoteixeirabtc** [comment]
If you are interested in the other exchanges in Brazil take a look at this link https://bitvalor.com/. But basically: 1. Negocie coins volume is absolutely fake, its well known that they dont have 10% of that volume 2. Foxbit servers are always down, there was a point they were 2 weeks out. 3, Mercado Bitcoin doesnt even have a websocket and charges the craziest fees. All the other ones don't have enough liquidity or technology. The only one that gives you decent fees, better infrastructure/security, and liquidity is BitcoinTrade

**Comment by ctubio** [comment]
awesome zip attached thanks''' ok will consider the addition of bitcointrade soOn'

**Comment by ctubio** [comment]
umf but bitcointrade doesnt have websocket api :( i think i dont want to integtrate more REST-only exchanges :S

**Comment by bernardoteixeirabtc** [comment]
yeah absolutely, maybe one day they will change that I will let you know. The market in Brasil is so slow and the volume is relatively low that I don't think it makes too much of a difference for them to implement websocket on the API.  Sometimes it takes 1-2 minutes to reflect the price change internationally.
