### ISSUE TITLE
Pair profit % values are not being updated

### ISSUE THREAD

**Issue by eugenelab** [ctubio/Krypto-trading-bot#746]
Value:
X.XXXXXXXX
X.XXXXX

+0.00%, +0.00% <- these are always 0%

**Comment by ctubio** [comment]
in all market levels and in all currencies?
i dont think so

**Comment by eugenelab** [comment]
@ctubio  trading on hitbtc, was working fine there. probably was broken with recent updates. do you need the settings JSON?

**Comment by ctubio** [comment]
just the value of `profit`; what value do you have?
thanks''

**Comment by donaldforest** [comment]
yep +0.00%, +0.00% stop working in last commits

**Comment by ctubio** [comment]
i see the issue, will fix on next commit; thanks''
