### ISSUE TITLE
STDEV BBTops ignored (4167 commit)

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#747]
1) Ignored BBTops, BBFair and looks like BBTop too.
![bbtops](https://user-images.githubusercontent.com/33358791/41510397-9e85bfb2-726c-11e8-9e9d-3db31993ed06.PNG)

2) In stats charts when I try enable STDEV BBFair - no chart.
![bbfair](https://user-images.githubusercontent.com/33358791/41510433-2d0105da-726d-11e8-95e2-0c448ee64680.PNG)

**Comment by ctubio** [comment]
for me only fails `STDEV BBFair` and `STDEV Fair`; thanks for the report''

**Comment by donaldforest** [comment]
If You about charts display, yes, sorry, I lost STDEV Fair.
But pay attention to the serviceability of all functions from stdev option (not charts). Looks like K ignore stdev values when add orders.

**Comment by ctubio** [comment]
cos stdev thinks fairVaule is always = 0 currently
