### ISSUE TITLE
Adding all the arguments in the manual

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#749]
So that's clear for everyone to know which ones exist and what they do. :)

**Comment by donaldforest** [comment]
Camille92, strange to hear it from You! What arguments you mean?

**Comment by Camille92** [comment]
--naked --color --autobot etc...
All those arguments :)


Le mer. 20 juin 2018 16:29, donaldforest <notifications@github.com> a
écrit :

**Comment by ctubio** [comment]
im sorry that is suposed to be already documented:
https://github.com/ctubio/Krypto-trading-bot/blob/master/etc/K.sh.dist#L4
https://github.com/ctubio/Krypto-trading-bot/blob/master/README.md#after-manual-installation

anyway i will add documentation (for sure!) about arguments when arguments become somewhat immutable; i hate to reedit prose versicles (that im currently reediting at https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/cf.h#L85
