### ISSUE TITLE
GDAX December 31, 2018

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#751]
GDAX API Update:

There will be no disruption to the gdax.com API during this time. GDAX APIs will continue to function until December 31, 2018.

We encourage Coinbase Pro users to begin migrating their API usage away from `api.gdax.com` to `api.pro.coinbase.com`.

Type | New Endpoint
-- | --
Rest API | https://api.pro.coinbase.com
Fix API | tcp+ssl://fix.pro.coinbase.com
Sandbox Web | https://public.sandbox.pro.coinbase.com
Sandbox Rest API | https://api-public.sandbox.pro.coinbase.com
Websocket Feed | wss://ws-feed.pro.coinbase.com

**Comment by KaseMaster** [comment]
OK. Thanks :)
