### ISSUE TITLE
Headless mode broken

### ISSUE THREAD

**Issue by grhangelone** [ctubio/Krypto-trading-bot#752]
Hi there,
I just updated the bot and now headless mode seems to be broken.
The regular mode with Web-UI works.

angelone@server2:~/ramdisk/K$ ./angelone.sh --currency latx/btc --autobot --headless --naked
K build x86_64-linux-gnu 2018-06-25 02:43:43.
v0.4.7+79 (zip install).
06/25 14:58:20.856791 DB loaded OK from data/angelone.db.
06/25 14:58:20.857779 DB loaded last Quoting Parameters OK.
06/25 14:58:20.858487 DB Warrrrning: consider to warm up some EWMA Values.
06/25 14:58:21.085236 GW HITBTC allows client IP.
06/25 14:58:21.085352 GW HITBTC:
- autoBot: yes
- symbols: LATXBTC
- minTick: 0.00000001
- minSize: 100.00000000
- makeFee: 0.00000000
- takeFee: 0.00000000.
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call

06/25 14:58:22.072116 Errrror: Signal 6 Aborted (Three-Headed Monkey found):
- exchange: HITBTC
- currency: LATX/BTC
- roll-out: 1529931500332
- lastbeat: 1529931502068
- binbuild: x86_64-linux-gnu
- os-uname: Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64
- tracelog:
./app/server/K(_ZN1K6Ending3wtfEi+0xad5) [0x557f924e7c05]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fabb1ffe4b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7fabb1ffe428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fabb200002a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d) [0x557f928c8bdd]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x557f9283c5f6]
./app/server/K(+0x4ec641) [0x557f9283c641]
./app/server/K(+0x4ed899) [0x557f9283d899]
./app/server/K(+0x4f9c52) [0x557f92849c52]
./app/server/K(_ZN1K2EV8timer_1sEv+0x417) [0x557f924ec807]
./app/server/K(+0x1cf5aa) [0x557f9251f5aa]
./app/server/K(_ZN2uS4Loop3runEv+0x8b) [0x557f9251f8fb]
./app/server/K(_ZN1K5Klass4waitEv+0x235) [0x557f92501c55]
./app/server/K(main+0xc47) [0x557f924cc667]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fabb1fe9830]
./app/server/K(_start+0x2a) [0x557f924cdf7a]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

06/25 14:58:22.072246 GW HITBTC Attempting to cancel all open orders, please wait..
06/25 14:58:22.267883 GW HITBTC cancel all open orders OK.
^CK exit code 0.

**Comment by ctubio** [comment]
many thanks for the report'''
lemme see what i did yesterday :(
