### ISSUE TITLE
K helper -> Side kick program ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#753]
Hi Carles and everyone,

I think we need to have something helping you to pick the best markets, coz you don't get profit on BTC/USD or ETH/BTC market anymore the spread is usually too thin.

However, you have many markets with big spread (over 2%) and a decent volume, and those are the ones you can make a profit from.

What do you think about making a sidekick program that helps find the best markets?

I know @CarlitoGrey and @bdbabiak have been thinking about that but I think something public (with different calculation method) can very much help.

As a rule of thumb, I think we can rank markets like that:

Average spread * volume = potential profit

(I know taking volatility into account would be best but I need to think about a formula).

So a sidekick program would compare all markets over a 24h period of one exchange by:
_ Taking the tick of every market and measuring the spread (and make a simple average of the spread).
_ Update volume every minute and take out of calculation over than 24h old volume (optionally converting this volume on a base currency for easy comparison).
_ Multiplying the 2 results

Then you have a great ranking of the best coins where to do market making, and an idea of the width setting you should use.

Let's see how it would work by comparing 3 coins:
BTC/USD average spread 0,02% volume 3000BTC : Score : 60
LTC/USD average spread 0,2% volume 500BTC :  Score : 100
MTC/USD average spread 2% Volume 150BTC : Score : 300

So you know that in this example is better to do market making on MTC/USD because even though the volume is way lower, the spread is much more interesting.

Tell me what you think!

Best,

Camille

**Comment by ctubio** [comment]
niiice

**Comment by mistacoda** [comment]
we could merge it into the same tool, it will just parse supported exchanges / all markets and generate top N pairs sorted by profit  https://github.com/ctubio/Krypto-trading-bot/issues/796

with python it's very easy to parse with help of https://github.com/ccxt/ccxt

**Comment by georgk10** [comment]
Is anyone working on the program suggestest by Camille92? If not I would like to do my best and write a program like this (I'm very familiar with python & could do pretty fast I guess)...
In case the task isn't already solved yet, sShould it be a console application/ Web app/ or just pure functions to integrate it to the trading bot itself ?

**Comment by nonkreon** [comment]
encouraging the enthusiasm @georgk10 , we have our console and webapp here in krypto trading bot which works with certain number of exchanges,, and the ccxt api @mistacoda mentioned can be used to improve it greatly. once you can create an interface between krypto trading bot and ccxt we would first be able to use krypto trading bot with virtually all meaningful exchanges in the world which is a huge leap, and the rest is just searching and sorting through it

**Comment by durrhurr991** [comment]
while we`re at it, since this would turn into a currency ranking ( possibly add that to a database) or even better have it search for best currency pair ( since we`re running on c this is rather fast) and then use that currency pair with given settings ( likely add that maybe to the autobot function?) and while we`re at it if this ever gets a multi instance feature maybe get the bot to search for like best 3 currency pairs or best 10 pairs ( would be somewhat of a code marathon to get that working properly since we would need advanced api features like withdraw and trade between currency pairs which would be turn into some kind of clusterfuck since we have several exchanges and all would need to have some kind of base currency like idk btc for example)

**Comment by ctubio** [comment]
i think we can call this `K-balance-bot`; let me start working on it'¡'

**Comment by durrhurr991** [comment]
maybe then have like a --basecurrency option  with that then  search for best trading pair ( OR pairs like out of 10, have it scored and then either use best score or choose manually)

**Comment by durrhurr991** [comment]
and maybe even optional have it put the best 10 or best 100 in the webui then have the currency pair (as in start button) like a dropdown menu to choose from best rated

**Comment by ctubio** [comment]
:koala: mm finally done at [/src/bin/+portfolios](https://github.com/ctubio/Krypto-trading-bot/tree/master/src/bin/%2Bportfolios), thank you for all the suggestions'¡!
