### ISSUE TITLE
 New Safety -> Only Profit Unless

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#754]
Hi all,

After a lot of thinking, this is, in my opinion, the best way to replace PingPong safety in a clear, useful and easy to understand way for everyone.

When this Only Profit safety is activated:
**You only sell above your last buy by a fixed (or %) value.
You only buy below your last sell by a fixed (or %) value.**

**The volume of last buy/sell is NOT taken into account.**

Of course, it would be a bit stupid because you can get stuck if you use this safety like that that's why I propose for this mode to have a **unless option** that would invalidate the above conditions.

The unless options can be:
**"nothing":** Never invalidate the sell above/ buy below condition.
** APR is on**
**If FV is below 'last buy'/ 'above' sell by:** user value or X%
**if best bid is below 'last buy'/ best ask is above 'last sell' by:** user value /X%
**If only profit target was not reached in:** XX minutes

When the "unless option" is reached, Only Profit unless acts like "top" until a new trade is made.

I hope you like the concept, I tried to make it as self-explanatory as possible!

If you're a programmer I would really appreciate if you can make it happen, everyone would benefit from it :)

Have a great day!

Camille

**Comment by ctubio** [comment]
:bulb: linked to #694 and #696

**Comment by ctubio** [comment]
7ec0f00 fixes pingpong safety based on last price in opposite side but still doesnt add any new *unless* option; hope for them soOn

**Comment by Camille92** [comment]
Hey Carles, so i've been experimenting it with that, it works well but sure enough you need manual restart every few hours otherwise it get stuck without the "unless" option.

**Comment by Camille92** [comment]
Hey any planning on making unless condition? :)

**Comment by ctubio** [comment]
:boom: selfreminder: see https://github.com/ctubio/Krypto-trading-bot/issues/820

**Comment by ctubio** [comment]
after af04981 your `unless` checkbox has become a new safety option in the dropdown named `PingPoing`; the new intro in the manual is at https://github.com/ctubio/Krypto-trading-bot/commit/af04981e192fb33ad5dbcf40d22c708575b5fda8#diff-39e155c0f8736983ac1c9a108839d13bR92

hope is as you expect'' otherwise feel free to open a new issue so we dont miss it as closed

:koala: many thanks for your time explaining'¡
