### ISSUE TITLE
Always Showing Missing Market Data & Missing Wallet Data with Hitbtc

### ISSUE THREAD

**Issue by simonwongmw** [ctubio/Krypto-trading-bot#755]
The terminal always display when working on Hitbtc:

**- Unable to calculate TBP, missing market data** and

**- Unable to calculate TBP, missing wallet data** 

New to coding, could anyone please let me know why? Thanks in advance.

**Comment by ctubio** [comment]
is impossible to provide support if you dont paste the full log

did you notice it is impossible to know what currency pairs are you using by reading your report?

consider using the IRC channel if you need help to succeed with the inital configs

**Comment by simonwongmw** [comment]
Hi, thanks for your help.

May I know where I could access the IRV channel?

Thanks.

「Carles Tubio <notifications@github.com>」在 2018年7月6日 週五，下午5:08 寫道：

**Comment by ctubio** [comment]
thanks, IRC is sure faster for quick questions:
https://kiwiirc.com/client/irc.freenode.net:6697/?theme=cli#tradingBot
^from https://github.com/ctubio/Krypto-trading-bot#general-discussion

**Comment by ctubio** [comment]
ima leave you here a copy of a working example for hitbtc, hope is easy to paste or compare with yours:
```
#!/usr/bin/env sh

# configurable! executable! k.sh initialization file

# Usage (replace k.sh by the current filename of THIS file):
## $ ./k.sh --help


# Feel free to copy/edit/rename THIS file.
# Is possible also to uncomment examples (but do not define multiple times the same variable).
# THIS file does, in order:
## I. Define hardcoded optional K arguments.
## II. Define initial mandatory UI arguments.
## III. Define initial mandatory API arguments.
## IV. Execute K in a loop until CTRL+C.

# I

OPTIONAL_ARGUMENTS="--colors --naked"

# II

UI_USERNAME=1234abcd
UI_PASSWORD=efgh5678
UI_OPENPORT=3000

# III

API_EXCHANGE=HITBTC
API_CURRENCY=XRP/BTC

API_KEY=WRITE_YOUR_API_KEY_HERE
API_SECRET=WRITE_YOUR_API_SECRET_HERE

API_PASSPHRASE=NULL
API_USERNAME=NULL
API_HTTP_ENDPOINT=api.hitbtc.com/api/2
API_WSS_ENDPOINT=wss//api.hitbtc.com/api/2/ws

# IV

./app/server/K                      \
    --title ${0##*/}                 \
    --port $UI_OPENPORT              \
    --user $UI_USERNAME              \
    --pass $UI_PASSWORD              \
    --exchange $API_EXCHANGE         \
    --currency $API_CURRENCY         \
    --apikey $API_KEY                \
    --secret $API_SECRET             \
    --passphrase $API_PASSPHRASE     \
    --username $API_USERNAME         \
    --http $API_HTTP_ENDPOINT        \
    --wss $API_WSS_ENDPOINT          \
    $OPTIONAL_ARGUMENTS "$@"         ;
```
