### ISSUE TITLE
Imposible conectar a bitfinex

### ISSUE THREAD

**Issue by KaseMaster** [ctubio/Krypto-trading-bot#757]
salida de time out continua. Cambios en la api? Algna idea?

---
```
app exchange: Bitfinex
app version: undisclosed
OS distro: ubuntu 14.01
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
Hello, maybe you have some extra spaces in the config file? consider to recreate your config file double checking to not leave empty spaces before/after the variable values

**Comment by KaseMaster** [comment]
https://discord.gg/ZUe8dyn

No spaces in code. exit time out

**Comment by ctubio** [comment]
try `$ curl -vvv https://api.bitfinex.com/v2/book/tBTCEUR/P0` if fails, means your computer have some firewall rules or something blocking connectivity to bitfinex servers; meanwhile curl fails K will fail to connect too :S

**Comment by KaseMaster** [comment]
whenever I run on hitbtc :(
only on debian, in ubuntu work ok
