### ISSUE TITLE
Error conect HitBTC Debian

### ISSUE THREAD

**Issue by KaseMaster** [ctubio/Krypto-trading-bot#758]
Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

07/12 23:14:59.355997 GW HITBTC Attempting to cancel all open orders, please wait..
07/12 23:14:59.411129 GW HITBTC cancel all open orders OK.
K exit code 1.
K crashed with exit code 1.. Respawning..
K build x86_64-linux-gnu 2018-07-12 23:04:18.
^Cv0.4.8+36 (0day).
07/12 23:15:06.160670 DB loaded OK from /data/db/K.HITBTC.BTC.USD.db.
07/12 23:15:06.161287 UI ready at https://2001:1608:10:25::1c15:a38c:7007.
07/12 23:15:06.162168 DB Warrrrning: using default values for Quoting Parameters.
07/12 23:15:06.162638 DB Warrrrning: consider to warm up some EWMA Values.
07/12 23:15:06.215400 GW HITBTC allows client IP.
07/12 23:15:06.215447 GW HITBTC:
- autoBot: no
- symbols: BTCUSD
- minTick: 0.01000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000.
07/12 23:15:06.877722 GW HITBTC WS Streaming book levels and orders.
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be boolean, but is null

07/12 23:15:06.937029 Errrror: Signal 6 Aborted (Three-Headed Monkey found):
- exchange: HITBTC
- currency: BTC/USD
- roll-out: 1531451705416
- lastbeat: 1531451706934
- binbuild: x86_64-linux-gnu
- os-uname: Linux 2.6.32-042stab120.16 #1 SMP Tue Dec 13 20:58:28 MSK 2016 x86_64
- tracelog:
./app/server/K(_ZN1K6Ending3wtfEi+0xae7) [0x7fdbc87f42f7]
/lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7fdbc79a5060]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf) [0x7fdbc79a4fff]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fdbc79a642a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d) [0x7fdbc8be1a4d]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x7fdbc8b55466]
./app/server/K(+0x4f94b1) [0x7fdbc8b554b1]
./app/server/K(+0x4fa709) [0x7fdbc8b56709]
./app/server/K(_ZN8nlohmann6detail9from_jsonINS_10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEEEEEvRKT_RNSD_9boolean_tE+0xcd) [0x7fdbc881479d]
./app/server/K(_ZNK8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEE5valueIbLi0EEET_RKS8_RKSC_+0xc3) [0x7fdbc8814913]
./app/server/K(_ZZN1K8GwHitBtc5readyEvENKUlPN3uWS9WebSocketILb0EEEPcmNS1_6OpCodeEE2_clES4_S5_mS6_+0x105f) [0x7fdbc88a6aaf]
./app/server/K(_ZN3uWS9WebSocketILb0EE14handleFragmentEPcmjibPNS_14WebSocketStateILb0EEE+0x270) [0x7fdbc8846d00]
./app/server/K(_ZN3uWS9WebSocketILb0EE6onDataEPN2uS6SocketEPcm+0x1d2) [0x7fdbc8847602]
./app/server/K(_ZN2uS6Socket12sslIoHandlerIN3uWS9WebSocketILb0EEEEEvPNS_4PollEii+0x187) [0x7fdbc88352b7]
./app/server/K(+0x1d1af8) [0x7fdbc882daf8]
./app/server/K(_ZN2uS4Loop3runEv+0x8b) [0x7fdbc882decb]
./app/server/K(_ZN1K5Klass4waitEv+0x25a) [0x7fdbc880c85a]
./app/server/K(main+0x90b) [0x7fdbc87d73fb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7fdbc79922e1]
./app/server/K(_start+0x2a) [0x7fdbc87d8b5a]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

07/12 23:15:06.937134 GW HITBTC Attempting to cancel all open orders, please wait..
07/12 23:15:06.993763 GW HITBTC cancel all open orders OK.
K exit code 1.

**Comment by ctubio** [comment]
im not sure how to reproduce this yet; will try a bit more :S

**Comment by ctubio** [comment]
Ks said:
```
whenever I run on hitbtc :(
only on debian, in ubuntu work ok
```

**Comment by ctubio** [comment]
im sorry im still not able to reproduce this; here hitbtc connects and works nicely no matter what configs i try.

consider to paste the full log (this error you pasted looks like the last error but more may exists prior to this; please paste the first not the last if you still wanna fix this)
