### ISSUE TITLE
DB Errrror: unable to open database file.

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#759]
Hello!
Clean install on Debian 9
First run with error (in console):
DB Errrror: unable to open database file.

**Comment by donaldforest** [comment]
was install with sudo
Fixed: chmod -R 777 /data

**Comment by ctubio** [comment]
is suposed that `make install` runs witth the same user as `./K.sh` because https://github.com/ctubio/Krypto-trading-bot/blob/master/Makefile#L248

no need to run all `make install` with `sudo`, since `make` uses sudo wherever needed, not everywhere
