### ISSUE TITLE
ETH/BTC orders way overpriced

### ISSUE THREAD

**Issue by phlongere** [ctubio/Krypto-trading-bot#76]
Hi,
Facing a problem with the bot on ETH/BTC (on Poloniex, not sure it's related) : order are placed at value 1.0 over "normal" market value (e.g. trying to sell ETH at 1.0845 BTC value instead of 0.0845, which would be a great deal, but doesn't quite meet demand).
It is quite constant in our tests with a +1.0 difference.
Code is up-to-date as of yesterday, and works all right with e.g. ETH/USDT on Poloniex.
Thx
![capture d ecran 2017-07-18 a 11 28 52](https://user-images.githubusercontent.com/839980/28310472-e0074996-6bac-11e7-8b5b-67007574751f.png)

**Comment by ctubio** [comment]
i think nobody cares about Poloniex because nobody donated for it
