### ISSUE TITLE
Only one idea

### ISSUE THREAD

**Issue by KaseMaster** [ctubio/Krypto-trading-bot#760]
Hello friends!
First of all, thanks for an excellent job!

Only one way, who may be interested:
It would be nice to be able to do:
- change torque from the web interface
- send operations / actions to Tw, mail, Discord, ...
- imbue the graph of tradingview.com
- triangular arbitrage in the same exchange
- demon in listening of all or some selected pairs tracking technical analysis signals
- save the strategies as a file and be able to select it in a selector of the web interface

I said friends, I hope it helps.

**Comment by ctubio** [comment]
- dont know what means "torque".
- not planning to send data to nowhere but to the logs, feel free to parse the logs and send the data where you want
- will consider to aadd tradingview.com soOn
- still not possible to connect to multiple excange/pairs; someday
- there is already another issue about it
- not going to save settings nowhere cos you already can export/import backups

will close this issue cos contains too many different issues, but thanks for the multiple ideas''

**Comment by KaseMaster** [comment]
torque lo traduce desde "PAR" 
Cambiar el par a tradear desde la interfaz web

**Comment by ctubio** [comment]
oh iSee, thanks for the explanation; switch of pairs from the UI is planned too but not possible yet :(
