### ISSUE TITLE
BUG: BW? Option not updating

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#761]
Hi Carles,

I'm now using the ping pong mode haha (working well thanks for the effort), and I noticed that the price is not always updated to match the best width.

You can have a look at the screenshot  below: on BCH USD, the bid price should be:
719.84944, just above the order below :)
![capture d ecran 2018-07-15 a 14 44 00](https://user-images.githubusercontent.com/6861590/42734064-c929fcb0-883d-11e8-90a6-5ce08f292bb1.png)

PS: ALLEZ LES BLEUS

**Comment by ctubio** [comment]
what value do you have for `delayUI`?

**Comment by ctubio** [comment]
you mean that the current order in the bid side was 719.84944 but in the market levels the selected level was another (720.21412)?

**Comment by Camille92** [comment]
Hi I use 5 for delayUI, but even after 5 seconds (or 10 or 20), it's not updating.

I meant that 720.21412 is respecting ping and pong width, but it's not the best width according to bw? rules.

In that case, the best width would be to put an order at  719.84944.

I think this happens because of the order not updating if orders below it disappear!

**Comment by ctubio** [comment]
ok iSee, you mean that looks like `bw` have no effect; ok many thanks for the reexplaination'''

**Comment by ctubio** [comment]
it looks to me that works correctly, let me write a test case for `QE::applyBestWidth()` before close this issue (i need to migrate QE logic to data objects before test cases can be done)

**Comment by ctubio** [comment]
im sorry finally found the issue
