### ISSUE TITLE
One commit made K super heavy!

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#762]
Hi Carles,

I've been running the updates of the 14 and 15 and I noticed that is greatly increased the use of my CPU, to the point that my VSP was not able to run all the K instances it was running the day before.

It went from a "wa" or 10% and "id" of 60-80% to "id" of 0% and "wa" of 80!

It made the instances useless :(.

I went back to this commit: https://github.com/ctubio/Krypto-trading-bot/commit/0d09cdafbb2c2792a11e60fad6fc905077c7f640 and everything is fine again.

So I guess the problem is a bit after! I noticed the problem on the 15 morning, so I guess the 3 last ones of yesterday night are clean too!

**Comment by ctubio** [comment]
errr thanks for the notice, lemme review cpu usage after the new ratelimits (now ratelimits only affect UI messages not server calcs; that may be the reason, but i didnt noticed, lemme look at it :S)

thanks again'''

**Comment by ctubio** [comment]
can you share the command you use to monitor usage? so i can see the same as you expect me to see?

**Comment by Camille92** [comment]
A simple top on Ubuntu 16.04!

Le lun. 16 juil. 2018 13:46, Carles Tubio <notifications@github.com> a
écrit :

**Comment by ctubio** [comment]
ok thanks i will use`top` too.
just saying: meanwhile `--database=:memory:` should make the app stop writing to disk nonstop

**Comment by ctubio** [comment]
so for you the nice latest version was `v0.4.8+40`? can you see what says `--versions` argument? i will compare with the same you have if you can share it

**Comment by Camille92** [comment]
I have to admit I'm not sure where to put the version argument, but I did a 
```
git checkout 0d09cdafbb2c2792a11e60fad6fc905077c7f640
make install
make restartall
```

**Comment by Camille92** [comment]
I'm still running the old version, but using --database=:memory: reduced my wa to 0 =)

**Comment by ctubio** [comment]
make install install the latest version, try `./K.sh --version`  to see the K version currently running

**Comment by ctubio** [comment]
:koala: still need to reatelimit better the `fairvalue` and the quote `status`

**Comment by ctubio** [comment]
looks OK to me by now, let me close this issue
