### ISSUE TITLE
UI stuck on Disconnected when trying to reconnect after awhile

### ISSUE THREAD

**Issue by rezart** [ctubio/Krypto-trading-bot#763]
First of all great work on this project! I am just getting acquainted with the project and looking forward to contributing.

Running into a weird issue after running the server for a few hours using the in memory storage; if I leave a tab open with the UI client it's fine & stays connected, but if I try to reconnect in a new tab or from another location to it I get a 'disconnected' screen while the server is still running and continues to place new orders. 

Looked into the server logs and nothing unusual, also nothing in the browser console (no client errors). I am only keeping an hour worth of data so don't think it's an issue with trying to load a massive amount of data at once onto the client...

**Comment by ctubio** [comment]
thanks for the report''
you mean with 2 client opened int 2 tabs or from 2 locations? or just 1 client all the time?

**Comment by rezart** [comment]
@ctubio all of the above. Basically you end up getting a 'Disconnected.' page after the server has been running and gathering data for 1+ hours. But if you already have a client that is connected that connection still continues...so seems to be related to new connections only.

**Comment by ctubio** [comment]
im not sure how to reproduce this, let me just run 1 server and multiple clients for a few days and see whats going on.

i usaly run only 1 client against my servers, but multiple clients are supposed to be supported while running all  synchronized as if one (update settings in one must update also settings in the others in realtime)

i will use chrome and mozilla concurrently while testing this :S

**Comment by rezart** [comment]
@ctubio 1 client, 1 server, 2 hours later I cannot connect :(

![image](https://user-images.githubusercontent.com/1059379/43032285-10febe9e-8c68-11e8-88c1-96bb8ad793f0.png)

**Comment by ctubio** [comment]
what value do you have in `delayUI`? im still not able to reproduce this :(

**Comment by ctubio** [comment]
i donno whats going on here, may be some firewall or router dis/re/connecting or some service not properly serving something :S it doesn't looks like i can reproduce this :(

**Comment by zilions** [comment]
Also getting this issue after running K for around an hour or so. Becomes disconnected and I have to log onto my cloud server to start K again.

**Comment by ctubio** [comment]
can you share what exchange are you using? thanks''
