### ISSUE TITLE
PingPong mode plays the same sound for pings and pongs.

### ISSUE THREAD

**Issue by ZeroCool940711** [ctubio/Krypto-trading-bot#765]
Hi there, I noticed that K is playing now the same sound for me when it buys and sells, only the sound for buying is been played no matter if its buying or selling making it hard to know whats the bot doing.

**Comment by ctubio** [comment]
sounds had never changed.

sounds are for ping trades or pong trades (not for bids or asks.).

**Comment by ctubio** [comment]
doyou mean you have same sound ever for pings and pongs?

**Comment by ZeroCool940711** [comment]
I technically have the same configuration as before and some time ago it was working correctly, the only difference is that now im using pingpong instead of boomerang, everything else is the same in my setup. Also I see that K do not update any option if I change it, have to restart the bot for changes to take effect and if restart K then it will forget about any open order and it wont sell.

**Comment by ctubio** [comment]
ah you are right, pingpong mode have since a few commits ago no more pong trades (marked as a green K in the UI)

let me reopen the issue because you are truth that it was nicer before

**Comment by ctubio** [comment]
thanks'' the safety will be added at #754 (just fix the sounds here)

**Comment by ZeroCool940711** [comment]
That safety sound awesome, would save a lot of troubles and will probably give more freedom with the rest of the settings, in my case I have almost every option trying to do what that safety propose, one last question as im not sure about this, if I have K to sell only above the last buy and it bought two times lets say it bough BTC at $7450 and then again at $7510 but then the price went down to $7480 again, will K sell there what it bought at $7450 or it will wait until the price goes above $7510 and sell there both trades at once? in other words, does K consider every trade individually when selling or it looks at all the previous trades and sells above the one that has the highest price?

**Comment by ctubio** [comment]
currently..
when using PingPong it looks individually and exclusively to the latest trade in the opposite side, without matter how many trades already hapened on any side, and each "last trade" can be used multiple times as a safety for next trades in the opposite side.

when using Boomerang or AK47 all previous can be used, and once a trade is used it is marked as "closed" and then it can't be used anymore.

hope this is what you were lookin for
