### ISSUE TITLE
Add FCoin API

### ISSUE THREAD

**Issue by zilions** [ctubio/Krypto-trading-bot#767]
Add FCoin to the list of exchanges.

Documented API - https://developer.fcoin.com/

FCoin is currently 1st in the world as per trade volume listed at CoinMarketCap.
https://coinmarketcap.com/exchanges/volume/24-hour/all/

**Comment by ctubio** [comment]
im not sure that i can read that "english" documentation at https://developer.fcoin.com/en.html

**Comment by zilions** [comment]
Yeah, I noticed that too. Silly error on their behalf. Just use Chrome to translate.

You may have added the `nobody cares` label, but the exchange is massive with billions of dollars worth in volume. It's lead by the ex-CTO of Huobi.

I'm willing to pay for this API integration.

**Comment by ctubio** [comment]
if you say that the google translation is OK, i will try with the translator then.

the label is there to provoke cares from somebody so this issue becomes more urgent; (cares = *small donations to my GitTip address so i can deposit and run tests freely on the new exchange [i dont use sandboxes and is not nice to worry for the funds while developing an exchange that i will not make use later on])

* see previous transactions in the GitTip address to see what other users consider as "small" in the past

thanks for insist on new exchanges''
(im too lazy if nobody cares because im too happy already with coinbase/hitbtc/bitfinex)

**Comment by zilions** [comment]
I'm struggling to find your GitTip address. Could you please link me?

**Comment by ctubio** [comment]
sorry i didnt to dont provoke compulsive donations xD (but is on every commit, like at https://github.com/ctubio/Krypto-trading-bot/commit/6361f1dd042e33423195a7b2ec75dfbc91d55fff)

**Comment by zilions** [comment]
Great, sounds good :) Let me know how you go.

**Comment by ctubio** [comment]
:koala: ima leave this here https://github.com/superhuai/fcoin-api/blob/master/index.js

**Comment by ctubio** [comment]
:koala: official docs page has deprecated info; better see https://github.com/nogo6260/Fcoin

**Comment by ctubio** [comment]
:bulb: maket data (public websocket) done

**Comment by zilions** [comment]
Let me know when you require the donation for testing 👍

**Comment by ctubio** [comment]
if you agree i would need a small donation to correctly develop the place/cancel orders functions (also to verify that the wallet data correctly give values > 0 xD) if nothing goes wrong can be done in next 48h

**Comment by zilions** [comment]
Done :)
Sent a little more than 0.03 BTC directly to your FCoin address.

**Comment by ctubio** [comment]
many thanks''' let me come back again once is done'

**Comment by zilions** [comment]
Cool. Let's hope they add it soon then. 
Looking forward to testing it out when it's ready 👍

**Comment by ctubio** [comment]
:bulb: all data is suposed to be integrated correctly after v0.4.9+15 (fef6f966ad59138dced672f356baf75d916315d2)

feel free to test it if you agree (and to let me know the payment address of the bot that you wish to unlock to test FCoin integration; i will unlock it asap)

**Comment by zilions** [comment]
Nice work :)

Unfortunately, I won’t get time to test this until I’m back in the office on Monday.

We haven’t purchased the bot yet. Please let me know what address and how much we need to send for purchase.

**Comment by ctubio** [comment]
the address is different for each bot, you will see it as soon as you open the UI of your bot

**Comment by zilions** [comment]
Here's the address - 3PGB5pkn3xoQUpjfPbCXi1aGJ5DCMrkEFt

**Comment by ctubio** [comment]
thanks, i just unlocked it

**Comment by zilions** [comment]
Thank you. I have reached out to you on Earn.com with another small inquiry.

**Comment by myrsnipa** [comment]
#767

Hanne brænna

----- Opprinnelig melding -----
Fra: "Carles Tubio" <notifications@github.com>
Sendt: ‎02.‎08.‎2018 14:19
Til: "ctubio/Krypto-trading-bot" <Krypto-trading-bot@noreply.github.com>
Kopi: "Subscribed" <subscribed@noreply.github.com>
Emne: Re: [ctubio/Krypto-trading-bot] Add FCoin API (#767)

many thanks''' let me come back again once is done'
