### ISSUE TITLE
AK-47 not selling properly.

### ISSUE THREAD

**Issue by ZeroCool940711** [ctubio/Krypto-trading-bot#769]
Hi there, I noticed that K is not working properly when AK-47 is used, I set to use two bullets and with a range of 1% between bullet, also pingAt is set to BidSide and pongAt is LongPingFair, it bought correctly, in my case it bought BTC/USDT twice, the first time at $8326.88 USDT and the second time at $8343.00 USDT, then it sold everything at $8337.99 USDT, that price is ok for the first trade but not for the second one, I lost there a lot of money and cant understand why, the bot should had sold there only what it bought on the first trade and not everything at once, I dont know what other setting to change in order to make the bot sell without loosing money, Ive tried every possible combination of setting and still cant make the bot sell only on profit.

**Comment by JamesBura** [comment]
Ive noticed the same using boomerang, not not sure if  it just averages the values you bought at or if its a weighted average but I would assume it should have been the lowest value for the max margin. 
LongPingFair - Place new Pongs based on the highest margin Ping in history respecting the widthPong from the fair value.

**Comment by ctubio** [comment]
consider to use and paste the output of `--debug-quotes` at least when reporting issues with quotes so we all can investigate the issue in a sane manner

**Comment by ZeroCool940711** [comment]
Ok, I understand, @ctubio can you add an option to save the console output to a log file of choice something like `--log-file=K_log.txt`, so when reporting things we have a place where to look for logs? in my case the console has a limit of just a few characters and K print too much stuff there and its hard to find something there, with K saving everything to a file it will be easier to get the info needed to debug K better, and before you mention it I tried redirecting the output of K to a log file with something like `./K.sh > log.txt` and in my case it doesnt save anything, K for me when using it on Hitbtc it creates something like a GUI on the console and I think that's why I get an empty file with no console output.

**Comment by ctubio** [comment]
feel free to run `./K.sh --naked > /path/to/K_log.txt`

**Comment by ctubio** [comment]
i think i found the issue, let me try a fix tomorrow
