### ISSUE TITLE
Autobot Switch Broken?

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#771]
Just did a reinstall and it seems that --autobot no longer applies correctly.

**Comment by ctubio** [comment]
can you confirm you are running v0.4.9+0?
aand are you using x86_64-linux-gnu?

**Comment by MiningInMySleep** [comment]
Yeah, I should be running the latest. Last time I did a re-install before today was maybe ~3 weeks ago.

K build x86_64-linux-gnu 2018-07-28 19:57:24.
v0.4.9+0 (zip install).

**Comment by ctubio** [comment]
ok thanks''
for me is working but is true that i had updated it recently, lemme review it
