### ISSUE TITLE
[info] Bitfinex API changes from 1st of September

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#773]
Dear Bitfinex user,

Starting from September 1st, 2018, 00:00 UTC, Bitfinex will be implementing a series of changes to the way we manage WebSocket connections to our APIs.

As of September 1st, every WebSocket connection will have a limit of 50 subscriptions to market data feed channels (tickers, book, candles, trades, ...). We kindly ask all users to adapt their application setup accordingly to split subscriptions to channels using multiple WebSocket connections.

As an example, if you subscribe to all tickers, books, candles, trades channels on a single WebSocket connection, you'll receive error:10305 (docs.bitfinex.com/v2/docs/ws-general#section-error-codes) to notify the quota if the current WebSocket connection is full.

For users, this means handling multiple streams, or running multiple instances and spreading them over different pairs. Implementing this API change results in quicker connections for all our API users, meaning quicker data feeds and optimised trading strategies.

For a full overview of the Bitfinex API documentation, refer to the following page: docs.bitfinex.com/docs. For issues or concerns, please contact support@bitfinex.com with [API Update September 2018] as the email subject.

Kind regards,
The Bitfinex team

**Comment by myrsnipa** [comment]
ok

**Comment by ctubio** [comment]
just saying, each K bot against bitfinex opens 3 channels; so we can open like 16 K bots against bitfinex using a single apikey

**Comment by MiningInMySleep** [comment]
So just to confirm, individual bots for different pairs are not actually separate websocket connections?

**Comment by ctubio** [comment]
now im confused :D

i was meaning IF 1 apikey = 1 websocket connection
(cos usualy limits are for a single apikey not for single socket opened)

if they mean 1 websocket connection = 1 websocket connection then is as you said; each bot is 1 different connection even if the apikey is the same.

**Comment by ctubio** [comment]
(im confused cos i dont see how their performance will improve by forcing people to open multiple sockets instead of a single one; and if sockets connections are allowed to be multiple and unlimited even for a single apikey, then there is no limit really xD even if each one can only subscribe to 50; you can always open unlimited :?)

ofcourse i may be missing something (or they are)

**Comment by MiningInMySleep** [comment]
Well, from what I understand, every time you connect to WS via the bot, you get assigned to a specific server:
GW BITFINEX WS Info {"event":"info","platform":{"status":1},"serverId":"5a441759-5beb-4824-91af-6dd6fbb83d16"

But putting a lot of subscriptions (50+) on a single connection would cause a much heavier load than those using 50 or less. So this might be their attempt at load balancing and (hopefully) not we'll stop seeing "GW BITFINEX WS Info {"code":20051,"event":"info","msg":"Stopping. Please try to reconnect"}." every single day.

**Comment by ctubio** [comment]
oh iSee thanks'' lets hope this servers have autoscaling based on some max users limit
