### ISSUE TITLE
2 question

### ISSUE THREAD

**Issue by sgs1** [ctubio/Krypto-trading-bot#777]
Hi guys!

I'm testing Krypto trading bot, and I've two question:
1) Can I test this software in demo, without using "real" crypto? If yes, what are the exchanges that I could use?
2) In this moment, I'm using Bitfinex with 0.00044046 BTC, and I have no order.
I'm attaching here a screenshot of what I see.
Is this normal?
Thank you!
<img width="1420" alt="schermata 2018-08-07 alle 22 08 39" src="https://user-images.githubusercontent.com/6910643/43799672-7a3c9384-9a8e-11e8-8b0a-ea9519f218b1.png">

**Comment by ctubio** [comment]
gdax have a sandbox, but there is no much movements (is a bit boring)

aboutt the orders, seems normal cos the big red button is not green

**Comment by sgs1** [comment]
At the moment, the button is red but no orders.
Maybe I have not enough bitcoin?
<img width="1415" alt="schermata 2018-08-08 alle 10 44 18" src="https://user-images.githubusercontent.com/6910643/43826646-19cb7b86-9af8-11e8-9bea-95ef1d46dc88.png">

**Comment by ctubio** [comment]
why you don't click the green/red button?

see the logs with `./K.sh --naked` and read the manual; you didnt read the manual for sure because it says how to read the logs

**Comment by sgs1** [comment]
Hello!
Now the button is green, as reported in the manual. 
"When the button is green, the bot is actively placing orders."

But, at the moment, I have no order. May I'm wrong with something? 
At the moment Bitfinex don't verify my account. Maybe is this a problem?

**Comment by ctubio** [comment]
you cannot trade with so low funds

**Comment by ctubio** [comment]
check the minimum size amount in the documentation of your exchange
