### ISSUE TITLE
share of best performing parameters?

### ISSUE THREAD

**Issue by chivalry123** [ctubio/Krypto-trading-bot#778]
Is there a place where we could share (buy/sell) the best parameters?

**Comment by ctubio** [comment]
nope cos ppl will end up buyin whatever other ppl says that is good; there is no way to securely proof the performance of "the best parameters", and i dont want to run a darknet market for scammers

**Comment by ctubio** [comment]
share for free without buy/sell could be an option, but nobody share their own "best parameters" for free
