### ISSUE TITLE
Question: Performance improvement and Kmemory !

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#78]
Hi Carles,

First of all thanks for the big update, super nice, saving the ewma is really something that missed so it's very cool!

Also it seems that the bot is using fewer resources, so that's great! I don't know what caused that but I definitely feel an improvement!

I have a question for Kmemory if I put a small value like 0.04 are the orders going to be cleaned every hour or so?

Thanks for telling methat :)

Ps: That's for this type of questions that we need a forum haha. I think a subreddit it definitely the best option!

**Comment by ctubio** [comment]
yea, the value is "days", but really are milliseconds (at https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/broker.ts#L339) so a fraction could result in "hours"

**Comment by Camille92** [comment]
Thankss ! I'll we seen in an hour if it works haha :)
