### ISSUE TITLE
[Bitfinex] no wallet data message after every reload!

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#781]
Hi since today after every reload i'm getting: "NO WALLET DATA Do a manual order first using the website of this Market!". After reload i make manual buy operation, then K shows me actual balance, then it sells coin and balance remain not updated. After reload NO WALLET msg appears. What can it be?

**Comment by ctubio** [comment]
what currency pairs are you using? im using bitfinex btcusd and seems ok

**Comment by serzhiio** [comment]
Btc/usd, ltc/usd

пн, 13 авг. 2018 г., 3:09 Carles Tubio <notifications@github.com>:

**Comment by ctubio** [comment]
im not able to reproduce this, can you share your config file (without api/secrets) so i can test with the very same as you?

tnanks''

**Comment by ctubio** [comment]
i donno but this september they have many plans, they may be already started messing arround with the hardware xD

**Comment by ctubio** [comment]
lets link with #773
