### ISSUE TITLE
Coinbase issues after last commit

### ISSUE THREAD

**Issue by JamesBura** [ctubio/Krypto-trading-bot#782]
After the latest update, K has gone nuts! Quotes are all over place and my account balance fluctuates coins are double or triple what I have.  

---
```
app exchange: COINBASE/LTC/USD
app version: v0.4.9+22
OS distro: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
thanks for the report'' lemme review coinbase :(

**Comment by ctubio** [comment]
ima try to fix coinbase prices instead of rollback https://github.com/ctubio/Krypto-trading-bot/commit/c9efed86e9a38a0555f8fdcef541787ed3807132#diff-6a30526e529c54caf3ce6a92e5b2d914R647

**Comment by ctubio** [comment]
well i end up rolling back, feel free to add some --debug-orders or --debug-quotes logs if you still have issues

thanks againz'
