### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by sgs1** [ctubio/Krypto-trading-bot#783]
Hi!
A question:  Is there the possibility to close an open order after X points? Like a take profit. 

I've read the manual, but honestly... I don't understand if there is this option or not.

**Comment by ctubio** [comment]
Hello,
im sorry im not sure what means "X points", but mostly possible the answer is "currently no but may be doable".

can you please explain with another words what moment in time is defined by the expression "after X points" that you want to wait for it to cancel open orders?
thanks''

**Comment by sgs1** [comment]
Hello!
I'll make an example (important: I'm using bitfinex with BTC/USD).

At 19.50 of today, BTC/USD is exchanged at 6000 USD. So, the bot opens a limit buy at 6002 USD.
After 2 minutes, the price is 6050 USD, but I'd like that this position is closed at 6025 USD.

A question: i'm using the "Top" mode, but I don't understand how the profits are generated.
Ps: ping and pong are terms too much confusing.

**Comment by ctubio** [comment]
i think you want to have selected `pongAt ` = `ShortPingAggresive` or `ShortPingAggresive`

this way, and if the bot has widthPong = 23, if you buy at 6002, it will sell for sure at 6025

otheriwse when pongAt is not Aggressive, it will always respect the widthPing from the current fair value, and it can go up to any price up to 6050 if the market spread is always lower than half of your widthPing

hope this helps; but saddly pongAt is only used by Boomerang/AK47; there is no other way currently to force a "close position at X" than using aggressive pongAt

note that is still possible that i understand you wrong and that my explanations are useless :sa: 

feel free to join the IRC channel better for questions (this is a bug tracker)

**Comment by ctubio** [comment]
also a very log widthPing and a higher widthPong will do the trick too for what you want i believe

**Comment by ctubio** [comment]
mm no way cos only 1 can be applied to a quote; a quote cannot have both applied, since they define a "price", and a quote only have 1 price

Long = price of the next quote taken from the opposite side having the biggest margin
Short = price of the next quote taken from the opposite side having the lowest margin

im not sure how to apply both to a single next quote price, doing a 50% mean between both?
