### ISSUE TITLE
[suggestion] commands with wildcard

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#788]
I want to suggest small improvement for some of make commands that works with several instances.
There is a need of restart/start/stop instances using wildcard. If i have a group of instances with file name prefix like 'bitfinex00' lets restart this group by typing command: '**make restartall bitfinex00***' and so on...

**Comment by ctubio** [comment]
cannot not pass parameters to make targets, need to do environment vars instead

i suggest a sh file with all the individual K=* make restart; that will do the job quicker
