### ISSUE TITLE
Support Bitibu

### ISSUE THREAD

**Issue by pelitlik** [ctubio/Krypto-trading-bot#790]
Hello,

Can you support Bitibu Exchange?

Document: https://bitibu.com/documents/api_v2

**Comment by ctubio** [comment]
can Bitibu Exchange support me?

looks like the api is only REST and ratelimited; i bet 1 coin Bitibu will ban me in the first 24h instead of support me

**Comment by pelitlik** [comment]
How can i contact with you? @ctubio

**Comment by ctubio** [comment]
im always on IRC (https://kiwiirc.com/client/irc.freenode.net:6697/?theme=cli#tradingBot)
