### ISSUE TITLE
Adding BitMEX exchange

### ISSUE THREAD

**Issue by sectrgt** [ctubio/Krypto-trading-bot#791]
Are there any plans to implement BitMEX into the bot in the near future? I feel this is a great exchange to trade on especially as a market maker and it wide leverage options.
Thank you.

**Comment by ctubio** [comment]
nobody yet suggested to initiate the development of this integration with a small donation.

if nobody donates for it, i understand that the interest into this integration is not big enough to compensate the future never-ending maintenance of it.

also first, need to check if BitMEX have acceptable websocket/ratelimits.

**Comment by ctubio** [comment]
let me close this issue as the answer was answered.

thanks'''
