### ISSUE TITLE
Wrong Watch link for some currencies

### ISSUE THREAD

**Issue by mistacoda** [ctubio/Krypto-trading-bot#794]
Hello,

I just found that for this market/currency

![image](https://user-images.githubusercontent.com/42780364/44820577-1e1a1680-abfa-11e8-9547-cea9dcb5fc29.png)

Wrong watch url generated: https://embed.cryptowat.ch/markets/hitbtc/btc/usd/1d
![image](https://user-images.githubusercontent.com/42780364/44820593-3db13f00-abfa-11e8-881a-3b97ce1b4c59.png)

The correct one is: https://embed.cryptowat.ch/markets/hitbtc/btc/usdt/1d 

so USD should be converted to USDT

PS: tried to fix it myself, but just not sure how compile *.ts, I tried "make clients && make bundle" but seems it doesn't update bundle.js what is the best workflow for dev / debug / no min  ?

**Comment by ctubio** [comment]
thanks for the report''

P.S. the readme suggest `make bundle K`

**Comment by ctubio** [comment]
:koala: soOn will replace cryptowatch by tradingview i think
