### ISSUE TITLE
ubuntus Makefile wrong g++ path detection

### ISSUE THREAD

**Issue by mistacoda** [ctubio/Krypto-trading-bot#795]
I'am running Ubuntu 16.04 with g++5 (default) and g++6 installed

```
make dist bundle K
```

gives me this error

```
Makefile:110: *** K require g++ v6, but g++ v6 was not found at /usr/bin/x86_64-linux-gnu-g++
Makefile:110: *** consider to create a symlink at /usr/bin/x86_64-linux-gnu-g++ pointing to your g++-6 executable.  Stop.
```

but actually this link exist (I just created it)
```
/usr/bin/x86_64-linux-gnu-g++ --version
x86_64-linux-gnu-g++ (Ubuntu 6.4.0-17ubuntu1~16.04) 6.4.0 20180424
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
```

The problem seems is in Makefile in this line, as g++ by default in system V5:
```
@$(if $(shell sh -c 'test "`g++ -dumpversion | cut -d . -f1`" != $(V_CXX) || echo 1'),,$(warning $(ERR));$(error $(HINT)))
```
if I replace it with this line, everything is fine:
```
@$(if $(shell sh -c 'test "`$(shell which "$(CXX)" 2> /dev/null) -dumpversion | cut -d . -f1`" != $(V_CXX) || echo 1'),,$(warning $(ERR));$(error $(HINT)))
```

I didn't create PR as seems my method wrong too, as by default /usr/bin/x86_64-linux-gnu-g++ linked to g++ V5 if both versions (5&6) in system installed.

Maybe we have to "which g++-6" first, if no found then set default "which g++" variable and use it everywhere?

**Comment by ctubio** [comment]
on ubuntus (as seen in travis file) i do:
```
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 50
```

but will consider your suggestion as seems it will not break my builds on debian

thanks for your time''

**Comment by ctubio** [comment]
finally fixed it at https://github.com/ctubio/Krypto-trading-bot/commit/3a256c4ba9e3ae62b51d0ca4bff6262c5d7d7078
