### ISSUE TITLE
Backtesting & Auto-tune idea

### ISSUE THREAD

**Issue by mistacoda** [ctubio/Krypto-trading-bot#796]
Hi everyone,

I'am mostly python guy, and most my last works were related to backtesting strategies and writing bots. After looking into your bot it's clearly see that it's great peace of software, but without right numbers/settings it will not make me rich very fast, and I'am pretty sure no one of you want to share these info with me or anyone else for nothing.

On other side, while trying to find right numbers/settings we can easily burn our deposits as with any other strategy in this world. So here is when usually backtesting helps, but as MM is not TA based by nature, but just simply math & luck - it may work much better here.

So here is my plan: we can store live data for OHLC / Order Book / Trade History and analyze it with python to find most profitable params / setting for last N period of time, and update them in K with websockets directly from python daemon running nearside. So actually depends on the market movements, we can brute-force the best combination for settings for each moment and update accordingly.

**What are benefits:**
1. From the start we have pretty good settings as we can backtest & brute force most params.
2. We have best settings per market/exchange per each moment.
3. If i'am not wrong, overfitting here doesn't matter so much as in case of TA strategies.

**What are disadvantages:**
1. As we are makers, we can't backtest everything, but we have lot of historical information including spread size, trades prices e.t.c. what should be enough for most settings.

Of course without community, it will be long trip for me, but if you'll share your experience to move me in right direction (how to test, what to test at first e.t.c.) we could have K backtest framework and tune tool in weeks or months. 

What you guys think, is it good idea?

**Comment by ctubio** [comment]
this is a trading bot not a trading simulator
