### ISSUE TITLE
Ethfinex: Unable to calculate quote, missing market data.

### ISSUE THREAD

**Issue by atsuki-iwamoto** [ctubio/Krypto-trading-bot#797]
I got an error below:

> 09/01 12:32:55.449483 DB loaded OK from /data/db/K.ETHFINEX.ETH.USD.db.
09/01 12:32:55.450236 UI ready at https://[*masked]:3000.
09/01 12:32:55.450915 DB loaded last Quoting Parameters OK.
09/01 12:32:55.451425 DB loaded 109 historical Fair Values.
09/01 12:32:55.451558 DB loaded last EWMA Values OK.
09/01 12:32:55.454441 DB loaded 940 STDEV Periods.
09/01 12:32:57.522667 GW ETHFINEX allows client IP.
09/01 12:32:57.522712 GW ETHFINEX: 
> - autoBot: no
> - symbols: ethusd
> - minTick: 0.01000000
> - minSize: 0.04000000
> - makeFee: 0.00000000
> - takeFee: 0.00000000.

> 09/01 12:32:59.179231 UI 1 currently connected, last connection was from [*masked].
09/01 12:32:59.569674 QE Warrrrning: Unable to calculate quote, missing market data.
09/01 12:32:59.607763 GW ETHFINEX WS Info {"event":"info","platform":{"status":1},"serverId":"f3ae92c4-c2ee-41c9-9daa-9fd1882d2f2d","version":2}.
09/01 12:32:59.865672 GW ETHFINEX WS Streaming channel 3029:trades.
09/01 12:32:59.866286 GW ETHFINEX WS Streaming wallet and orders OK 0:"auth".
09/01 12:33:00.569720 QE Warrrrning: Unable to calculate quote, missing market data.
09/01 12:33:01.570998 QE Warrrrning: Unable to calculate quote, missing market data.
09/01 12:33:02.571542 QE Warrrrning: Unable to calculate quote, missing market data.
09/01 12:33:02.759585 GW ETHFINEX WS Streaming channel 32775:book.

The config file is this:
https://pastebin.com/wVKZ4JfF

I think the config is ok.
All the api key permissions are allowed except withdraw. 
I would appreciate any help.

**Comment by ctubio** [comment]
yep your config is all OK cos minTick/minSize have correct values coming from the exchange

also your execution is all OK cos at the end it says:
```
09/01 12:33:02.759585 GW ETHFINEX WS Streaming channel 32775:book.
```

after ^this line sure it doesnt prints any more Warrrrning msgs

that is because every second tries to place an order, and for the first 4 seconds bitfinex didnt send you market data, and the app warn about until market data arrived.

**Comment by ctubio** [comment]
thanks for the logs'¡

**Comment by atsuki-iwamoto** [comment]
so, is it just waiting the connection stabilized?
It seems any other causes prevent it from placing an order.
I'll try to find the cause around the quoting parameters.
Thank you very much anyway.
