### ISSUE TITLE
trades /sec - looks bug

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#799]
Hello!
K installed 2 days ago.
![min](https://user-images.githubusercontent.com/33358791/44993567-b837e100-afa3-11e8-9904-64d7c58f2eac.PNG)

sop and apr is OFF
Can You check it please.

**Comment by ctubio** [comment]
trades/sec is part of test/units.h and seems OK but lemme recheck it

thanks for the screenshot'''

**Comment by donaldforest** [comment]
Maybe --database=:memory: ?

**Comment by ctubio** [comment]
yep no difference

didnt had time to look at it yet sorry; hope for it soOn'
