### ISSUE TITLE
Warning! OkCoin updated their fees -> No 0% market maker fee anymore.

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#8]
I was very surprised to realize that so don't get fooled as well!

https://www.okcoin.com/fees.html

**Comment by ctubio** [comment]
thanks'¡

**Comment by ngxiaoyi** [comment]
So this trading-bot is not suitable for OKCoin any more. Am I right?

**Comment by Camille92** [comment]
Hello @ngxiaoyi,

It's a complicated question,
In theory, no the bot still works with OkCoin, however, verify your settings so that you overcome the fees while doing market making.

But in practice and in my opinion, OkCoin is not interesting enough anymore, I prefer Gdax or Bitfinex where you have more markets, lower fees, and better volume.

**Comment by ctubio** [comment]
i use OkCoin for testing, API is nice and works perfectly, not like stupid Poloniex xD
but Coinbase is where profits come from (in my home)

**Comment by ngxiaoyi** [comment]
@Camille92 haha  
yeah~ I know it's not a good question. but as a Chinese OKCoin is almost the only option of my exchange. One more info in case: ETH market fee downgraded to 0.05% on OKcoin.cn till July.8, not sure about okcoin.com
