### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#800]
Sometimes (once in 24 hours) I see this messages on Coinbase config:
![missing_data](https://user-images.githubusercontent.com/33358791/45002057-86427100-afdb-11e8-8110-4f5e9aa545c4.PNG)
Just manual stop and start fix it immediately. (**clx?** isnt help, is always checked on for my configs)

**Comment by donaldforest** [comment]
ok. I'm going to try **--debug-wallet**. Mayby in this case need some more debug options?
Previously I tried setup "make restartall" in cron, but in this case trades | /sec resets every K restart.

**Comment by MiningInMySleep** [comment]
Been getting this on Bitfi/FCoin but have ignored it. Orders seem to go through, but can't tell if it's causing problems overall. If I refresh the interface sometimes it goes away by itself.

**Comment by r8m** [comment]
Same problem on Okex

**Comment by OverlordQ** [comment]
Seeing this with BCHUSD on Coinbase.
