### ISSUE TITLE
[Bitfinex] wallet issue question

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#801]
Hi Carles! I'm discussing some wallet issues with Bitfinex team and they asked me:
"when sending the filter configuration to the server are you sending ["wallet", "wallet-exchange-BTC", "wallet-exchange-USD"] or just ["wallet-exchange-BTC", "wallet-exchange-USD"]"? (The second is correct)
Need an answer...

**Comment by ctubio** [comment]
we send filter as`["trading-tBTCUSD","wallet"]`

we send calc as `["wallet-exchange-BTC", "wallet-exchange-USD"]`
