### ISSUE TITLE
npm warn

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#802]
```
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
```

**Comment by ctubio** [comment]
alone? or you executed a command?

**Comment by Pat71** [comment]
Sorry: when I "make"

**Comment by ctubio** [comment]
thanks''
im sorry i had never seen this error, i donno what means `Error: Method Not Allowed` but i see many cache shits in your output; maybe reinstall npm helps? (or just flush npm caches)

here running "make" having npm v6.4.1 im not able to reproduce this misterious error you have :S

**Comment by ctubio** [comment]
(closing also cos the new babel extension is a mess and will not be implemented yet)
