### ISSUE TITLE
HamelinRat

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#803]
Hello!
a)
![hr3](https://user-images.githubusercontent.com/33358791/45149435-35e13400-b1d2-11e8-84eb-b7680ebadde0.PNG)
We have 2 cases:
1) All ok:
![hr2](https://user-images.githubusercontent.com/33358791/45149458-442f5000-b1d2-11e8-8cd2-b6616fede19a.PNG)
2) Not quite logical:
![hr1](https://user-images.githubusercontent.com/33358791/45149475-4f827b80-b1d2-11e8-9291-12b9cee80327.PNG)
* In second case we lost our position on market.. No way in current example to finish ask order.. -- your competitors set very big volume before my order.

In case:
b)
![hr11](https://user-images.githubusercontent.com/33358791/45149707-e3544780-b1d2-11e8-9bb9-549140636c9b.PNG)
1) same like for a) case - all ok.
2) Order disappears from all lists. Order disabled. It looks like order deletion is related to small spread (No place set limit order with 0.01 spread and with conditions HamelinRat, we have a risk set market order). Maybe we can in this case merge our order with big volume orders set?!

**Comment by serzhiio** [comment]
Consider that UI orderbook refresh speed is not realtime.

**Comment by donaldforest** [comment]
Hm. Maybe.

**Comment by ctubio** [comment]
yea when the biggest order is the first, there is no way to put an order infront, so maybe makes sense to skip trading;

Note that even if HamelinRat is used; the widthPing must be always respected

not sure if helps :S
