### ISSUE TITLE
Add a new exchange OceanONE

### ISSUE THREAD

**Issue by kyokokiss** [ctubio/Krypto-trading-bot#804]
Hi, do you have interest in adding OceanONE —— A decentralized Exchange based on Mixin Network, guaranteed ‘0’ transfer fee & immediate transfer speed, it has the following characters:

High Security
Exchange code is open-sourced; User assets are stored in their own wallets
High Transparency
All transaction records are publicly available on the Mixin Network;
Transparent and checkable
Trading Experience - High-speed & Low-cost
Immediate order placement; No charges on Buying, Selling and Cancelling
Full set of crypto-currencies
Supports more than 11 main chains with more than 41,000 crypto-currencies
including XIN, BTC, Omni USDT, etc.
OceanONE  API Open-sourced 
Developers friendly, meeting different trading needs 
https://github.com/MixinNetwork/ocean.one

**Comment by ctubio** [comment]
im sorry it doesn't looks very popular, only their own developers are opening issues in that project :S (maybe cos that project only is 4month old)

**Comment by kyokokiss** [comment]
The project is not old enough, we're trying to connect more people to know it, maybe you could keep an eye on it? ^_^
