### ISSUE TITLE
make: *** No rule to make target 'src//.cxx', needed by 'src'.  Stop.

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#805]
Hello.
Today K release. When I try update it with **make reinstall** I receive:
`make: *** No rule to make target 'src//.cxx', needed by 'src'.  Stop.`

**Comment by ctubio** [comment]
yea i fucked it yesterday; will fix thiz afternoOn

**Comment by ctubio** [comment]
many thanks for the report'''
(incoming fix even if still midday!)
