### ISSUE TITLE
Max trades / sec is including pongs

### ISSUE THREAD

**Issue by boogey100** [ctubio/Krypto-trading-bot#806]
I've just seen a situation where max trades is stopping both buy and sell.

This is what happened.

Safety is on Boomerang. Ping buy with sop active  with sopSize 3. Pong sell 2 trades sop not active. The sells are ponging, but it can't sell any more because of max trades. I don't think pongs should (ever) count towards the max trades per sec.

What do you think? Maybe have separate settings for  maxTrades, maxPings, maxPongs?

**Comment by ctubio** [comment]
currently `trades/sec` safety is intentionally limiting both pings and pongs

this could be implemented maybe not with separated settings but with unified settings, allowing to choose if those single settings (`trades/sec`) affects both or only Pings or only Pongs

**Comment by asfbhero** [comment]
Is there a setting that currently does what Boogey described? I'm using a combination of max trades/s along with ewmatrend to prevent getting smacked when the price jumps fast. I think it would be great  to allow a quick blip in the price to pong out of as many trades as possible.

**Comment by ctubio** [comment]
not possible yet, but it makes alot of sense yea, hope for it soOn; lets Pin it to not forget it asap

**Comment by ctubio** [comment]
i will go for the unified settings explained in the previous comment, if you dont disagree

**Comment by asfbhero** [comment]
That would probably work just fine.  Being able to tune the individual settings might be nice, but would probably just be curve fitting and end up not helping with future results.

**Comment by ctubio** [comment]
mmm.. instead ima not modify the settings, and just ignore protection of trades/sec for pongs; cos i think it makes sense always
