### ISSUE TITLE
Weird sellSize when APR active

### ISSUE THREAD

**Issue by boogey100** [ctubio/Krypto-trading-bot#809]
https://github.com/ctubio/Krypto-trading-bot/blob/afa23af58dce0f0716c889bed167316d273bd572/src/include/Krypto.ninja-data.h#L2535

I noticed that with APR active, quotes were posting with sellSize ever decreasing in size.  I changed this line to:
if (!qp.sellSizeMax) quotes.ask.size = fmin(qp.aprMultiplier * quotes.ask.size, wallet.base.total - wallet.target.targetBasePosition);

and this seems to be behaving better.

I haven't done any c++  before, or pull requests for that matter, so I thought I'd start just posting as an issue. I hope that's ok :P

**Comment by ctubio** [comment]
sure many thanks for the suggestion'''
will review thiz weekend :D

**Comment by ctubio** [comment]
thanks for the suggestion'' next commit includes it, also i applied it to `buySizeMax` as well as `sellSizeMax`
