### ISSUE TITLE
Start/Stop Trading activity via an HTTP endpoint for K?

### ISSUE THREAD

**Issue by beegmon** [ctubio/Krypto-trading-bot#81]
It's been a while but I am finally getting back around to playing in this space again.

I would like to use K for something that I am testing with, because it is really really good at managing limit orders and placing them on the book.

I need to be able to trigger K to start buying or start selling only when told to do so.

My idea is that I would have two instances of K running, one setup to buy with a specific set of parameters, and one setup to sell with another set of parameters. I would like to enable the buy side instance with a HTTP call, and disable it with an HTTP call. Same thing for the sell side instance.

Otherwise I don't want either instance to take any positions until told to do so. 

Is there an endpoint I can curl on the bot's web service that I can use to start/stop it's activity?

**Comment by ctubio** [comment]
yea, set the bot in auto mode, and then from any other computer, (not using HTTP calls cos are insecure):
```
ssh user@host -C killall -9 node
```
and to start it:
```
ssh user@host -C node K.js
```
