### ISSUE TITLE
[COINBASE PRO] Three head monkey

### ISSUE THREAD

**Issue by JamesBura** [ctubio/Krypto-trading-bot#817]
K-trading-bot x86_64-linux-gnu 2018-09-28 00:08:35.
v0.4.10+50 (0day).
09/27 23:00:21.204589 DB loaded OK from /data/db/K.COINBASE.BTC.USD.db.
09/27 23:00:21.205235 UI Warrrrning: Connected web clients will enjoy unsecure SSL encryption..
(because the private key is visible in the source!), consider --ssl-crt and --ssl-key arguments.
09/27 23:00:21.206408 UI ready at https://75.110.138.75:3000.
09/27 23:00:21.226234 DB Warrrrning: using default values for Quoting Parameters.
09/27 23:00:21.275142 DB Warrrrning: consider to warm up some EWMA Values.
09/27 23:00:21.418154 GW COINBASE allows client IP.
09/27 23:00:21.418634 GW COINBASE:
- autoBot: no
- symbols: BTC-USD
- minTick: 0.01000000
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000.
09/27 23:00:22.226219 GW COINBASE WS Streaming book levels.
09/27 23:00:22.300582 Errrror: Segmentation fault (Three-Headed Monkey found):
- exchange: COINBASE
- currency: BTC/USD
- lastbeat: 1906
- binbuild: trading-bot x86_64-linux-gnu
- tracelog:
./app/server/K(_ZN1K6Ending3wtfEi+0x6b0) [0x7f7f341f70b0]
/lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7f7f33153060]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by ctubio** [comment]
im sorry this tracelog is too little :S im not able to understand what is going on here

**Comment by ctubio** [comment]
if this issue is permanent for you feel free to comment; im not able to reproduce it just by starting the bot
