### ISSUE TITLE
Turning off Monero Miner

### ISSUE THREAD

**Issue by Gondee** [ctubio/Krypto-trading-bot#818]
@ctubio I noticed that when I have the panel open (I have purchased Krypto-Trading-Bot), the CPU utilization still is very high, is this due to the monero miner still running? Is there a setting to turn it off, or will I need to compile the code without it. Killing my battery life on my laptop

**Comment by ctubio** [comment]
there is no setting to turn it off because is off by default

the setting to enable it the argument `--free-version`

try `ps axu | grep K` to see if you are running still some K in the backgroud

otherwise try `ps aux | sort -nrk 3,3 | head -n 10` to check what are the top 10 apps eating cpu

**Comment by ctubio** [comment]
if you still have issues consider to show the output of your ps or top commands, !taking care that api keys/secrets/sensitive infos are removed!

usualy each bot should take 1% of cpu with ocasional spikes of 4%
