### ISSUE TITLE
stdev Unable to compute value

### ISSUE THREAD

**Issue by yepla** [ctubio/Krypto-trading-bot#82]
Hello,
I try to start the bot on hitbtc to trading PAY/ETH but an error happen:
stdev Unable to compute value
I can access to the webui but there are no connection made to the exchange it say to me disconnect and on the left there are write connecting to the exchange.
Thanks for your help.

**Comment by ctubio** [comment]
hopefully fixed at https://github.com/ctubio/Krypto-trading-bot/issues/83
