### ISSUE TITLE
PG Warrrrning: Unable to calculate TBP, missing wallet data.

### ISSUE THREAD

**Issue by luispinonferrer** [ctubio/Krypto-trading-bot#822]
./K.sh 
K-trading-bot x86_64-linux-gnu 2018-10-01 03:29:25.
v0.4.10+54 (0day).
10/05 02:56:12.778364 DB loaded OK from /data/db/K.HITBTC.ETH.USD.db.
10/05 02:56:12.778688 UI Warrrrning: Connected web clients will enjoy unsecure SSL encryption..
(because the private key is visible in the source!), consider --ssl-crt and --ssl-key arguments.
10/05 02:56:12.779064 UI ready at https://212.237.24.145:3000.
10/05 02:56:12.779867 DB Warrrrning: using default values for Quoting Parameters.
10/05 02:56:12.780468 DB loaded 12 historical Fair Values.
10/05 02:56:12.780807 DB loaded last EWMA Values OK.
10/05 02:56:12.902264 GW HITBTC allows client IP.
10/05 02:56:12.902445 GW HITBTC: 
- autoBot: no
- symbols: ETHUSD
- minTick: 0.01000000
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000.
10/05 02:56:13.498160 GW HITBTC WS Streaming book levels and orders.
10/05 02:56:13.659002 PG Warrrrning: Unable to calculate TBP, missing wallet data.
10/05 02:56:13.927438 PG Warrrrning: Unable to calculate TBP, missing wallet data.
10/05 02:56:14.691377 PG Warrrrning: Unable to calculate TBP, missing wallet data.
10/05 02:56:15.021923 PG Warrrrning: Unable to calculate TBP, missing wallet data.
....

**Comment by ctubio** [comment]
this is suposed to happen always that wallet values are equal to `0`

to fix it make sure you have some positive quantity as funds in both sides (eth and usd); maybe doing a manual order using the website of the exchange helps'
