### ISSUE TITLE
Bitfinex Partial Order Updating

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#826]
Bitfinex recently modified the UI to display order errors.
One thing that appears to be happening is if an order is partially executed to the point where the remainder is under the minimum order size threshold, that order will return an error when updating it.
Edit: this basically freezes price for the pair on that side until either the order is cancelled or executed.

**Comment by ctubio** [comment]
many thanks for the report''

**Comment by MiningInMySleep** [comment]
Would it be possible to check if the remaining order quantity is less than the minSize for the pair and cancel if so?

**Comment by ctubio** [comment]
sure, thanks for the hint; will do it soOn

**Comment by ctubio** [comment]
hope your UI is not spammed with all this red msgs after eff888f'¡
