### ISSUE TITLE
HitBTC connecting to exchange...

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#83]
K is loading without issue now, market orders and my btc/usd balance is all working, however it seems to be stuck at connecting:
![image](https://user-images.githubusercontent.com/29517455/28341527-1134e3ac-6c0c-11e7-9a91-e7778c383a56.png)

**Comment by CarlitoGrey** [comment]
There are no additional logs in the console output.

**Comment by ctubio** [comment]
![data_rolling_the_dice](https://user-images.githubusercontent.com/1634027/28344494-0482a9a6-6c24-11e7-8771-502100ece453.gif)
