### ISSUE TITLE
Bitfinex missing market data

### ISSUE THREAD

**Issue by sgs1** [ctubio/Krypto-trading-bot#830]
Hi guys!
I've downloaded your bot in my ubuntu pc; I've configured the API for Bitfinex for BTC/USD  but I see this error (only this): Warrrrning: unable to calculate quote, missing market data.

In my webclient, I see two columns with name "MissingData". 
What I'm wrong?

**Comment by ctubio** [comment]
does refreshing the webclient (F5 on winy) helps?

**Comment by sgs1** [comment]
No, it doesn't help.

Here I post the logs that I see when I run ./K.sh. I'm using Mojave in this moment, but the same problem is under Ubuntu.

`K build x86_64-apple-darwin17 2018-08-05 01:48:12.
v0.4.9+17 (zip install).
10/14 12:45:23.660720 DB loaded OK from /data/db/K.BITFINEX.BTC.USD.db.
10/14 12:45:23.662161 UI ready at https://2001:b07:2ee:92c8:497a:5f8:7c40:c086:3000.
10/14 12:45:23.664339 DB loaded last Quoting Parameters OK.
10/14 12:45:23.664722 DB loaded TBP = 0.002800 BTC.
10/14 12:45:23.673355 DB loaded 1518 historical Fair Values.
10/14 12:45:23.675224 DB Warrrrning: consider to warm up some EWMA Values.
10/14 12:45:23.685591 DB loaded 118 historical Trades.
10/14 12:45:26.184502 GW BITFINEX allows client IP.
10/14 12:45:26.184539 GW BITFINEX: 
- autoBot: no
- symbols: btcusd
- minTick: 0.10000000
- minSize: 0.00200000
- makeFee: 0.00000000
- takeFee: 0.00000000.
10/14 12:45:27.829510 GW BITFINEX WS Info {"event":"info","platform":{"status":1},"serverId":"b670120a-3eae-4d0f-9903-3d92aba626b2","version":2}.
10/14 12:45:28.000653 GW BITFINEX WS Streaming channel 7:trades.
10/14 12:45:28.000873 GW BITFINEX WS Streaming wallet and orders OK 0:"auth".
10/14 12:45:28.294595 QE Warrrrning: Unable to calculate quote, missing market data.
10/14 12:45:29.298252 QE Warrrrning: Unable to calculate quote, missing market data.
10/14 12:45:30.299785 QE Warrrrning: Unable to calculate quote, missing market data.
10/14 12:45:31.153318 GW BITFINEX WS Streaming channel 515826:book.
10/14 12:45:39.479928 UI authorization success from 127.0.0.1.
10/14 12:45:40.515308 UI 1 currently connected, last connection was from 127.0.0.1.
10/14 12:45:49.570127 UI authorization success from 127.0.0.1.
10/14 12:45:49.577194 UI 0 currently connected, last connection was from 127.0.0.1.
10/14 12:45:50.375082 UI 1 currently connected, last connection was from 127.0.0.1.`

**Comment by sgs1** [comment]
Hello, thanks for the reply!

I've runned the bot, and after 10 seconds, I've refreshed the page. But, I still see "missingData" in the columns. 
<img width="553" alt="schermata 2018-10-14 alle 17 59 47" src="https://user-images.githubusercontent.com/6910643/46919135-2a580880-cfdb-11e8-90df-97b26909391b.png">

**Comment by ctubio** [comment]
your next issue is with wallet data, this MissingData statuses are related to the wallet.

wallet values are displayed under Market, Orders link, and over Submit Order button.
if you dont see them must be because the value are 0 or very close to 0.

can you please make sure about having positive balance on BTC and/or USD? i belive this will fix your issue.

alternatively you can use `--debug-secret` argument to display messages coming from bitfienx, were your wallet values must be displayed

**Comment by sgs1** [comment]
then I've to run ".K.sh --debug-secret", right?

**Comment by ctubio** [comment]
yes, in case you want to display debug messages

you need to look for message like:
```
<<< [0,"ws",[["exchange","USD",XXX,0,null]]]
```
or
```
<<< [0,"ws",[["exchange","BTC",XXX,0,null]]]
```

where XXX must be your current available wallet funds

**Comment by sgs1** [comment]
Hello!
Yes, I look both of the two messages. And the value of them is: 0.007 for USD and 0.004 for BTC.
At the moment, the view is this.
<img width="422" alt="schermata 2018-10-21 alle 19 06 30" src="https://user-images.githubusercontent.com/6910643/47269924-859e7380-d564-11e8-8a68-7cabaaf0abe5.png">
