### ISSUE TITLE
Report segmentation fault: 11

### ISSUE THREAD

**Issue by iamGeoWat** [ctubio/Krypto-trading-bot#831]
10/21 16:53:45.866920 GW FCOIN Notice: 0.0003 is less than the min limit order amount 0.001.
10/21 16:53:52.329108 GW FCOIN Notice: 0.0003 is less than the min limit order amount 0.001.
10/21 16:54:05.777339 GW FCOIN Notice: 0.0003 is less than the min limit order amount 0.001.
10/21 16:54:10.191026 GW FCOIN Notice: 0.0003 is less than the min limit order amount 0.001.
10/21 16:54:18.393416 Errrror: Segmentation fault: 11 (Three-Headed Monkey found):
- exchange: FCOIN
- currency: BTC/USDT
- lastbeat: 791831
- binbuild: K-trading-bot x86_64-apple-darwin17
- tracelog: 
0   K-trading-bot                       0x000000010ffe0fea _ZN1K6Ending3wtfEi + 1786

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).

**Comment by ctubio** [comment]
consider to increase your balance/order size
