### ISSUE TITLE
[Bitfinex] Postonly issue

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#832]
I've noticed an issue which leads to takerfees instead of makers.
So far i cant say was it a bug or new behaviour but we need to check that we are **sending postonly flag every time when updating an order**.

**Comment by serzhiio** [comment]
Info from BFX stuff:
> because the post-only is a one time thing: you send an order, either the order gets canceled if it on taker side (or executed if there is a maker hidden order) or it gets added to the book and since then it becomes a normal limit order

**Comment by ctubio** [comment]
nope :D but on next commit yes (replaced by flags:4096)
