### ISSUE TITLE
your bot wont trade

### ISSUE THREAD

**Issue by cyberneticdinner** [ctubio/Krypto-trading-bot#833]
10/25 14:46:54.455127 QE Warrrrning: Unable to calculate quote, missing market data.
10/25 14:46:55.127093 UI 1 currently connected, last connection was from 212.115.246.172.
10/25 14:50:11.311366 Errrror: Segmentation fault (Three-Headed Monkey found):
- exchange: KRAKEN
- currency: BTC/EUR
- lastbeat: 238027
- binbuild: K-trading-bot x86_64-linux-gnu
- tracelog: 
K-trading-bot(_ZN1K6Ending3wtfEi+0x6d9) [0x55cc95184609]
/lib/x86_64-linux-gnu/libc.so.6(+0x35fc0) [0x7eff3809ffc0]

Yikes!

10/25 14:44:39.983264 GW KRAKEN Quoting state changed to CONNECTED.
10/25 14:46:10.080075 Errrror: Segmentation fault (Three-Headed Monkey found):
- exchange: KRAKEN
- currency: BTC/EUR
- lastbeat: 132205
- binbuild: K-trading-bot x86_64-linux-gnu
- tracelog: 
K-trading-bot(_ZN1K6Ending3wtfEi+0x6d9) [0x559283693609]
/lib/x86_64-linux-gnu/libc.so.6(+0x35fc0) [0x7f4214813fc0]
K-trading-bot(AES_encrypt+0xfe) [0x55928397b351]
K-trading-bot(+0x480cd5) [0x559283914cd5]
K-trading-bot(EVP_EncryptUpdate+0x10c) [0x55928391e3cc]
K-trading-bot(EVP_CipherUpdate+0xf) [0x55928391e99f]
K-trading-bot(+0x5218fa) [0x5592839b58fa]
K-trading-bot(+0x521e29) [0x5592839b5e29]
K-trading-bot(RAND_DRBG_generate+0xad) [0x55928393f0a0]
K-trading-bot(RAND_DRBG_bytes+0x5d) [0x55928393f2c9]
K-trading-bot(RAND_priv_bytes+0x47) [0x5592839405d9]
K-trading-bot(SSL_CTX_new+0x27c) [0x5592838abf67]
K-trading-bot(+0x3fe9b4) [0x5592838929b4]
K-trading-bot(+0x402007) [0x559283896007]
K-trading-bot(+0x3dfda7) [0x559283873da7]
K-trading-bot(+0x3e55e2) [0x5592838795e2]
K-trading-bot(+0x3e6e7b) [0x55928387ae7b]
K-trading-bot(+0x3ed5ef) [0x5592838815ef]
K-trading-bot(+0x3ce456) [0x559283862456]
K-trading-bot(+0x3cf761) [0x559283863761]
K-trading-bot(+0x3c9c13) [0x55928385dc13]
K-trading-bot(_ZN1K5mREST12curl_performERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt8functionIFvPvEEb+0xde) [0x5592836d7dbe]
K-trading-bot(_ZN1K8GwKraken4xferERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_S8_S8_+0x89) [0x5592836eb809]
K-trading-bot(_ZN1K12GwKrakenData11sync_walletEv+0x4a2) [0x5592836ecac2]
K-trading-bot(_ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultISt6vectorIN1K8mWalletsESaISA_EEEES3_ENSt6thread8_InvokerISt5tupleIJZNS9_14GwExchangeData20askForNeverAsyncDataERKjEUlvE_EEEESC_EEE9_M_invokeERKSt9_Any_data+0x28) [0x5592836b3d38]
K-trading-bot(_ZNSt13__future_base13_State_baseV29_M_do_setEPSt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEEPb+0x1b) [0x55928364b4ab]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf827) [0x7f42149aa827]
K-trading-bot(_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZNSt13__future_base17_Async_state_implINS1_IS2_IJZN1K14GwExchangeData20askForNeverAsyncDataERKjEUlvE_EEEESt6vectorINS5_8mWalletsESaISD_EEEC4EOSB_EUlvE_EEEEE6_M_runEv+0x109) [0x5592836bee89]
K-trading-bot(+0x5e5f0f) [0x559283a79f0f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7f2a) [0x7f42149a2f2a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f42148d5edf]

Yikes!

**Comment by cyberneticdinner** [comment]
server: debian at AWS

**Comment by ctubio** [comment]
Kraken may be fixed someday at #741

im not using Kraken and nobody that uses supports the development, so i have no interest into fix it for now
