### ISSUE TITLE
Poloniex first run issue

### ISSUE THREAD

**Issue by cyberneticdinner** [ctubio/Krypto-trading-bot#834]
10/26 05:13:34.050346 QE Warrrrning: Unable to calculate quote, missing market data.
10/26 05:13:34.505846 PG TBP: 0% = 0.00000000 BTC, pDiv: 300% = 0.90000000 BTC.
10/26 05:13:42.058222 UI 1 currently connected, last connection was from 212.115.246.44.
10/26 05:13:53.787256 Errrror: Segmentation fault (Three-Headed Monkey found):
- exchange: POLONIEX
- currency: BTC/USDT
- lastbeat: 20442
- binbuild: K-trading-bot x86_64-linux-gnu
- tracelog: 
K-trading-bot(_ZN1K6Ending3wtfEi+0x6d9) [0x55fc29144609]
/lib/x86_64-linux-gnu/libc.so.6(+0x35fc0) [0x7f379b4cffc0]
K-trading-bot(+0x480ccf) [0x55fc293c5ccf]
K-trading-bot(EVP_EncryptUpdate+0x10c) [0x55fc293cf3cc]
K-trading-bot(EVP_CipherUpdate+0xf) [0x55fc293cf99f]
K-trading-bot(+0x521bd6) [0x55fc29466bd6]
K-trading-bot(+0x521e29) [0x55fc29466e29]
K-trading-bot(RAND_DRBG_generate+0xad) [0x55fc293f00a0]
K-trading-bot(RAND_DRBG_bytes+0x5d) [0x55fc293f02c9]
K-trading-bot(+0x4aba9b) [0x55fc293f0a9b]
K-trading-bot(RAND_bytes+0x20) [0x55fc293f1563]
K-trading-bot(SSL_CTX_new+0x259) [0x55fc2935cf44]
K-trading-bot(+0x3fe9b4) [0x55fc293439b4]
K-trading-bot(+0x402007) [0x55fc29347007]
K-trading-bot(+0x3dfda7) [0x55fc29324da7]
K-trading-bot(+0x3e55e2) [0x55fc2932a5e2]
K-trading-bot(+0x3e6e7b) [0x55fc2932be7b]
K-trading-bot(+0x3ed5ef) [0x55fc293325ef]
K-trading-bot(+0x3ce456) [0x55fc29313456]
K-trading-bot(+0x3cf761) [0x55fc29314761]
K-trading-bot(+0x3c9c13) [0x55fc2930ec13]
K-trading-bot(_ZN1K5mREST12curl_performERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt8functionIFvPvEEb+0xde) [0x55fc29188dbe]
K-trading-bot(_ZN1K14GwPoloniexData11sync_ordersEv+0x399) [0x55fc291a5549]
K-trading-bot(_ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultISt6vectorIN1K6mOrderESaISA_EEEES3_ENSt6thread8_InvokerISt5tupleIJZNS9_14GwExchangeData14askForSyncDataERKjEUlvE_EEEESC_EEE9_M_invokeERKSt9_Any_data+0x28) [0x55fc29167d38]
K-trading-bot(_ZNSt13__future_base13_State_baseV29_M_do_setEPSt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEEPb+0x1b) [0x55fc290fc4ab]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf827) [0x7f379b666827]
K-trading-bot(_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZNSt13__future_base17_Async_state_implINS1_IS2_IJZN1K14GwExchangeData14askForSyncDataERKjEUlvE_EEEESt6vectorINS5_6mOrderESaISD_EEEC4EOSB_EUlvE_EEEEE6_M_runEv+0x109) [0x55fc29170089]
K-trading-bot(+0x5e5f0f) [0x55fc2952af0f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7f2a) [0x7f379b65ef2a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f379b591edf]

Yikes!

**Comment by ctubio** [comment]
sorry im not using Poloniex and nobody that uses Poloniex want to supports the development, so i have no interest into fix it for now

**Comment by cyberneticdinner** [comment]
can you tell me what exchange i should use?

**Comment by ctubio** [comment]
coinbase / hitbtc and bitfinex are 100% currently maintained

im sorry i think i will remove soOn Poloniex/okcoin/kraken soon, cos as of today is not true that is supported
