### ISSUE TITLE
BitFinex Order Update With Insufficient Balance

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#837]
If the bot tries to update an order and you don't have enough balance for it, the update will error out continuously. 

Example of an error:
Invalid order: not enough exchange balance for -0.05 ETH/BTC at 0.033661.

In this case the market was moving up so the attempt to increase the bid at the same size fails constantly.
It should probably reduce the order size to compensate for the remaining available balance.

**Comment by serzhiio** [comment]
Its a common error if you are trading with many bots which sometimes make bids more than actual amount.
Maybe you should use percents instead of absolute numbers?

**Comment by ctubio** [comment]
sizes are minimized to the `total` amount available but also are maximized to match `minSize` setting from the exchange, see https://github.com/ctubio/Krypto-trading-bot/blob/3ba4434472555dc6bb2fcfd2dad3e05c81979266/src/include/Krypto.ninja-data.h#L2474-L2491

not sure how to fix this situation unless using `%` quoting parameter (it doesnt fix it completely but helps a bit)
