### ISSUE TITLE
Interface IPV4 Bug

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#838]
When attempting to set --interface=ip I'm getting:
11/07 11:33:34.679762 UI Errrror: Unable to listen to UI port number 3001, may be already in use by another program.

This is off a fresh reboot + K install on debian buster.
Removing --interface=ip seems to remedy this. Most of the time it will default to ipv6 but sometimes it will work on ipv4. Regardless, accessing ipv4:port still works for the web interface after removing it so it's no problem for me. Might be an issue for others.

**Comment by ctubio** [comment]
im sorry many thanks for the report'''
