### ISSUE TITLE
Coinbase macOS malloc: Incorrect checksum for freed object

### ISSUE THREAD

**Issue by nazariyv** [ctubio/Krypto-trading-bot#846]
Hi,

I keep getting this error a couple of times per day. Once it happens you cannot CTRL+C from within the Terminal. Need to go to Activity Monitor to force quit, then it respawns by itself. I have to sit and oversee the bot at all times, otherwise it just leaves open orders in the market when this happens. Not sure what else I can add here. Is there a debug mode that I can run the bot in to give you a bit more info. 

My system info:
`macOS Mojave Version 10.14.1
MacBook Pro
Processor: 2.3 GHz Intel Core i5
Memory: 8 GB 2133 MHz LPDDR3
Graphics Intel Iris Plus Graphics 640 1536 MB`

I am running the bot in iTerm 2.

The error is:
`K-trading-bot(1334, 0x70000db8b000) malloc: Incorrect checksum for freed object 0x7fa4d2828588: probably modified after being freed.
Corrupt value: 0x283d07fa4d05443d
K-trading-bot(1334, 0x70000db8b000) malloc: ** set a breakpoint in malloc_error_ break to debug`

**Comment by ctubio** [comment]
thanks for the report'' after next commit i will review macOS

**Comment by ctubio** [comment]
:koala: that was with coinbase exchange?

**Comment by nazariyv** [comment]
correct

**Comment by sitatmike** [comment]
Kindly update on the price

**Comment by ctubio** [comment]
i ran finally Coinbase for a week on macOS and found no issues so allow me to close this; sorry for abandon it
