### ISSUE TITLE
Coinbase cxl Segmentation fault (deprecated K version found)

### ISSUE THREAD

**Issue by nonkreon** [ctubio/Krypto-trading-bot#847]
Hi everyone,
I've finally got out of using 0.4.10.52 and got my hands on the latest version, However, the latest version is throwing a segfault at me after running for some time hinting me that the version I'm using is deprecated:

```
│ 14:47:12.146469 GW COINBASE WS Streaming book levels.                      │
│ 14:47:12.346475 GW COINBASE Quoting state changed to CONNECTED.
│ 14:47:12.346796 GW COINBASE FIX success Logon.
│ 14:47:13.156602 QE Warrrrning: Unable to calculate quote, missing market
│  data.
│                                                                          └──┘
├───┤< (5) Open Orders while 1 BCH = 0.04787000 BTC:
├ASK > 0.03069039 BCH at price 0.23999000 BTC (value 0.00736539 BTC)
├ASK > 0.03064436 BCH at price 0.06479000 BTC (value 0.00198545 BTC)
16:23:16.747400 Errrror: Segmentation fault (deprecated K version found).

Hint!
please upgrade to the latest commit; the encountered error may be already fixed at:
2018-11-12 13:05:44 (7c52934) Added permanent shame on spain.
2018-11-12 20:18:42 (183fc3f) Added permanent shame on spain.
2018-11-18 13:31:57 (cf26de0) Updated Manual
2018-11-18 13:33:16 (ea2c2b2) Merge pull request #1 from nazariyv/nazariyv-patch-1
2018-11-18 20:55:33 (427d8df) Merge pull request #845 from nazariyv/master

If you agree, consider to run "make latest" prior further executions.


16:23:17.747717 GW COINBASE Quoting state changed to DISCONNECTED.
16:23:17.747997 GW COINBASE Attempting to cancel all open orders, please wait..
16:23:18.944764 GW COINBASE cancel all open orders OK.
K exit code 1.

```
However when I try to upgrade I get nothing
```
$ make latest
Fetching origin
Local running version: 427d8df7d365c00f7d0394dc6d551fffaf0e6d78
Latest remote version: 427d8df7d365c00f7d0394dc6d551fffaf0e6d78

No need to upgrade, both versions are equal.
```
Anyone run into something like this?

**Comment by boogey100** [comment]
If you have auto cancel on (cxl?) it is probably that. See #824

**Comment by nonkreon** [comment]
the new title looks great, hope it will bring luck to all of us along with the new namespace. the issue is indeed cxl, after I turned it off none of the bots have died. any debugging you propose on my side?

**Comment by ctubio** [comment]
i was told this happens with default settings (making sure `cxl` is enabled), so im testing with default settings

but still after many days i was not able to reproduce it, and just by looking the codes i dont see nothing wrong :D i need to reproduce it somehow :S is not my desire to run coinbase with default settings but i will keep trying waiting for it

anything you consider helpfull to reproduce it, just lemme know here'¡ (many thanks for your support'¡)

**Comment by nonkreon** [comment]
I'm repulsed by the fact that the FIX api only allows 50 requests/user/second. If you are pinging both sides with 10 bullets each side, each market bot has 20 orders. In about 3 or more bots it's very easy to go beyond this stupid limits, even if you increase the lifetime ridiculuously.

**Comment by ctubio** [comment]
just saying, `cxl` uses REST api, so even less request/user/seconds :(
```
REST PRIVATE ENDPOINTS
5 requests per second, up to 10 requests per second in bursts.

FINANCIAL INFORMATION EXCHANGE API
50 commands per second.
```

will try to stop using REST api for `cxl` and use instead FIX msgs

**Comment by ctubio** [comment]
thanks for the patience'' (and for the suggestion'¡)

:koala: now we use instead a super short FIX message to cancel all: `H,37=*` :dancer: and only the wallet of coinbase uses REST api
