### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by jordap123** [ctubio/Krypto-trading-bot#849]
- exchange: COINBASE
- currency: ETH-USD
- lastbeat: 1507141
- binbuild: K-trading-bot x86_64-apple-darwin17
- tracelog: 
0   K-trading-bot                       0x000000010f66f929 _ZN5u0E3F6Ending3wtfEi + 1353
1   ???                                 0x0000000000000051 0x0 + 81

**Comment by ctubio** [comment]
thank you for the report''
lets fix Coinbase on macOS at https://github.com/ctubio/Krypto-trading-bot/issues/846
