### ISSUE TITLE
HitBTC

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#85]
Carles,

Many thanks for getting HitBTC to run, tip sent.

Unfortunately I've been testing today and K seems to lose track of buy/sell orders every few minutes. Occasionally it will freeze up entirely and need to be restarted. Is there any chance you could take a look at this?

**Comment by ctubio** [comment]
lety me use your donation to test HitBTC, before i didnt had any funds in HitBTC so i coulnd test orders really

**Comment by ctubio** [comment]
so to test this is just to let the app run and watch for missing/zombie orders or a freeze (donno what is a freeze :P), okok on my way'¡

**Comment by ctubio** [comment]
websocket is not login correctly; only the public websocket works; aaand seems hitbtc has FIX protocol so ima try to migrate to FIX instead of websocket for new/cancel orders

**Comment by ctubio** [comment]
well the FIX protocol is not public :S
