### ISSUE TITLE
Locked bot after API change

### ISSUE THREAD

**Issue by Cointechltd** [ctubio/Krypto-trading-bot#850]
description
please, consider to add all possible details (if any) about your new feature request or bug report

---
```
app exchange: //
app version: undisclosed
OS distro: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by Cointechltd** [comment]
Hi,

12:55:10 PMGuest68777I have paid yesterday for the Krypto bot but I had to change my API 
12:55:16 PMGuest68777now it is locked again 
12:55:43 PMGuest68777please advice how to fix this 
1:00:44 PMGuest68777https://thepasteb.in/p/Y6hk72mpBAxi7 
1:00:44 PMGuest68777Complete BTC 0.01280000 
1:00:44 PMGuest687772018-11-28 15:56:29 
1:00:44 PMGuest68777Address: 3DRYzMPDFYAtVodo9Yj6trvHVguXgtXyB3 
1:00:44 PMGuest68777Txid: 4568e13e8c39a7359d8026c2eea9b09e6774177dafb305d615c547faa47fe408 
1:00:44 PMGuest68777 Complete BTC 0.01280000 
1:00:44 PMGuest687772018-11-28 15:56:29 
1:00:44 PMGuest68777Address: 3DRYzMPDFYAtVodo9Yj6trvHVguXgtXyB3 
1:00:44 PMGuest68777Txid: 4568e13e8c39a7359d8026c2eea9b09e6774177dafb305d615c547faa47fe408 
1:01:14 PMGuest68777this is the new one 
1:01:21 PMGuest68777https://thepasteb.in/p/AnhrQABnJkKIv 
1:01:27 PMGuest68777or send 0.01210000 BTC or more to: 
1:01:27 PMGuest687773DwN29QLGmuanXGweb6yeYsLCzKCttstQ5 


Thanks that from IRC copied

**Comment by ctubio** [comment]
morning'''
i just unlocked 3DwN29QLGmuanXGweb6yeYsLCzKCttstQ5, hope this is what you were looking for

**Comment by Cointechltd** [comment]
Thanks! I am enjoying the bot a lot :)

**Comment by Cointechltd** [comment]
I have an error, do you know how to solve it?

11/29 13:06:33.201600 Errrror: Segmentation fault (Three-Headed Monkey found):
- exchange: POLONIEX
- currency: USDT_BTC
- lastbeat: 21006
- binbuild: K-trading-bot x86_64-linux-gnu
- tracelog: 
K-trading-bot(_ZN3฿6Ending3wtfEi+0x549) [0x55f481f04409]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7efec5cd4f20]
K-trading-bot(AES_encrypt+0x1c4) [0x55f4821dff37]
K-trading-bot(+0x4707f5) [0x55f4821797f5]
K-trading-bot(EVP_EncryptUpdate+0x10c) [0x55f482182eec]
K-trading-bot(EVP_CipherUpdate+0xf) [0x55f4821834bf]
K-trading-bot(+0x5116f6) [0x55f48221a6f6]
K-trading-bot(+0x511949) [0x55f48221a949]
K-trading-bot(RAND_DRBG_generate+0xad) [0x55f4821a3bc0]
K-trading-bot(RAND_DRBG_bytes+0x5d) [0x55f4821a3de9]
K-trading-bot(+0x49b5bb) [0x55f4821a45bb]
K-trading-bot(RAND_bytes+0x20) [0x55f4821a5083]
K-trading-bot(SSL_CTX_new+0x259) [0x55f482110a64]
K-trading-bot(+0x3ee4d4) [0x55f4820f74d4]
K-trading-bot(+0x3f1b27) [0x55f4820fab27]
K-trading-bot(+0x3cf8c7) [0x55f4820d88c7]
K-trading-bot(+0x3d5102) [0x55f4820de102]
K-trading-bot(+0x3d699b) [0x55f4820df99b]
K-trading-bot(+0x3dd10f) [0x55f4820e610f]
K-trading-bot(+0x3bdf76) [0x55f4820c6f76]
K-trading-bot(+0x3bf281) [0x55f4820c8281]
K-trading-bot(+0x3b9733) [0x55f4820c2733]
K-trading-bot(_ZN3฿5mREST4xferERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKl+0x113) [0x55f481f02ba3]
K-trading-bot(_ZN3฿14GwPoloniexData9getLevelsEv+0x11f) [0x55f481f4961f]
K-trading-bot(_ZN3฿14GwPoloniexData11sync_levelsEv+0x9e) [0x55f481f49f8e]
K-trading-bot(_ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultISt6vectorIN3฿7mLevelsESaISA_EEEES3_ENSt6thread8_InvokerISt5tupleIJZNS9_14GwExchangeData14askForSyncDataERKjEUlvE0_EEEESC_EEE9_M_invokeERKSt9_Any_data+0x28) [0x55f481f25dd8]
K-trading-bot(_ZNSt13__future_base13_State_baseV29_M_do_setEPSt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEEPb+0x1b) [0x55f481ebf67b]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf827) [0x7efec6096827]
K-trading-bot(_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZNSt13__future_base17_Async_state_implINS1_IS2_IJZN3฿14GwExchangeData14askForSyncDataERKjEUlvE0_EEEESt6vectorINS5_7mLevelsESaISD_EEEC4EOSB_EUlvE_EEEEE6_M_runEv+0x109) [0x55f481f2f9a9]
K-trading-bot(+0x5d59df) [0x55f4822de9df]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7efec608e6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7efec5db788f]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new
