### ISSUE TITLE
Poloniex segfault

### ISSUE THREAD

**Issue by Cointechltd** [ctubio/Krypto-trading-bot#852]
Errrror: Segmentation fault (Three-Headed Monkey found):
- exchange: POLONIEX
- currency: USDC_BTC
- lastbeat: 14874
- binbuild: K-trading-bot x86_64-linux-gnu
- tracelog: 
K-trading-bot(_ZN3฿6Ending3wtfEi+0x553) [0x55b2dd80d813]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f3094e65f20]
K-trading-bot(EVP_CipherInit_ex+0xce) [0x55b2dda8aa1e]
K-trading-bot(+0x50e9f2) [0x55b2ddb219f2]
K-trading-bot(+0x50eae6) [0x55b2ddb21ae6]
K-trading-bot(RAND_DRBG_generate+0xad) [0x55b2ddaaad90]
K-trading-bot(RAND_DRBG_bytes+0x5d) [0x55b2ddaaafb9]
K-trading-bot(+0x49878b) [0x55b2ddaab78b]
K-trading-bot(RAND_bytes+0x20) [0x55b2ddaac253]
K-trading-bot(ssl_fill_hello_random+0xa2) [0x55b2dda0e49c]
K-trading-bot(tls_construct_client_hello+0x18b) [0x55b2dda2ba62]
K-trading-bot(+0x4182d6) [0x55b2dda2b2d6]
K-trading-bot(ossl_statem_connect+0xe) [0x55b2dda2b7a8]
K-trading-bot(SSL_do_handshake+0x43) [0x55b2dda185da]
K-trading-bot(SSL_connect+0x13) [0x55b2dda19838]
K-trading-bot(+0x3ea59d) [0x55b2dd9fd59d]
K-trading-bot(+0x3eeca0) [0x55b2dda01ca0]
K-trading-bot(+0x3cca97) [0x55b2dd9dfa97]
K-trading-bot(+0x3d22d2) [0x55b2dd9e52d2]
K-trading-bot(+0x3d3b6b) [0x55b2dd9e6b6b]
K-trading-bot(+0x3da2df) [0x55b2dd9ed2df]
K-trading-bot(+0x3bb146) [0x55b2dd9ce146]
K-trading-bot(+0x3bc451) [0x55b2dd9cf451]
K-trading-bot(+0x3b6903) [0x55b2dd9c9903]
K-trading-bot(_ZN3฿4Curl7performERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt8functionIFvPvEEb+0xe7) [0x55b2dd84e5c7]
K-trading-bot(_ZN3฿14GwPoloniexData11sync_ordersEv+0x367) [0x55b2dd867e37]
K-trading-bot(_ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultISt6vectorIN3฿6mOrderESaISA_EEEES3_ENSt6thread8_InvokerISt5tupleIJZNS9_14GwExchangeData14askForSyncDataERKjEUlvE_EEEESC_EEE9_M_invokeERKSt9_Any_data+0x28) [0x55b2dd8317a8]
K-trading-bot(_ZNSt13__future_base13_State_baseV29_M_do_setEPSt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEEPb+0x1b) [0x55b2dd7c8fab]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf827) [0x7f3095227827]
K-trading-bot(_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZNSt13__future_base17_Async_state_implINS1_IS2_IJZN3฿14GwExchangeData14askForSyncDataERKjEUlvE_EEEESt6vectorINS5_6mOrderESaISD_EEEC4EOSB_EUlvE_EEEEE6_M_runEv+0x109) [0x55b2dd838659]
K-trading-bot(+0x5d2baf) [0x55b2ddbe5baf]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f309521f6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f3094f4888f]

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

**Comment by nonkreon** [comment]
K-trading-bot(_ZN3à¸¿6Ending3wtfEi+0x553) [0x55d1e9cf2383]
        /lib64/libc.so.6(+0x34720) [0x7fa048249720]
                                                   K-trading-bot(EVP_CIPHER_CTX_reset+0x30) [0x55d1e9f6ea49]
                            K-trading-bot(EVP_CipherInit_ex+0x6b) [0x55d1e9f6f52b]
  K-trading-bot(+0x50f562) [0x55d1ea006562]
                                           K-trading-bot(+0x50f656) [0x55d1ea006656]
    K-trading-bot(RAND_DRBG_generate+0xad) [0x55d1e9f8f900]
                                                           K-trading-bot(RAND_DRBG_bytes+0x5d) [0x55d1e9f8fb29]
                               K-trading-bot(+0x4992fb) [0x55d1e9f902fb]
                                                                        K-trading-bot(RAND_bytes+0x20) [0x55d1e9f90dc3]
                                       K-trading-bot(ssl_fill_hello_random+0xa2) [0x55d1e9ef300c]
                 K-trading-bot(tls_construct_client_hello+0x18b) [0x55d1e9f105d2]
 K-trading-bot(+0x418e46) [0x55d1e9f0fe46]
                                          K-trading-bot(ossl_statem_connect+0xe) [0x55d1e9f10318]
                 K-trading-bot(SSL_do_handshake+0x43) [0x55d1e9efd14a]
                                                                      K-trading-bot(SSL_connect+0x13) [0x55d1e9efe3a8]
                                      K-trading-bot(+0x3eb10d) [0x55d1e9ee210d]
                                                                               K-trading-bot(+0x3ef810) [0x55d1e9ee6810]
                                        K-trading-bot(+0x3cd607) [0x55d1e9ec4607]
 K-trading-bot(+0x3d2e42) [0x55d1e9ec9e42]
                                          K-trading-bot(+0x3d46db) [0x55d1e9ecb6db]
   K-trading-bot(+0x3dae4f) [0x55d1e9ed1e4f]
                                            K-trading-bot(+0x3bbcb6) [0x55d1e9eb2cb6]
     K-trading-bot(+0x3bcfc1) [0x55d1e9eb3fc1]
                                              K-trading-bot(+0x3b7473) [0x55d1e9eae473]
       K-trading-bot(_ZN3à¸¿4Curl4xferERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKl+0x113) [0x55d1e9cf0c23]
                                        K-trading-bot(_ZN3à¸¿14GwPoloniexData9getLevelsEv+0x11f) [0x55d1e9d3623f]
                                 K-trading-bot(_ZN3à¸¿14GwPoloniexData11sync_levelsEv+0x9e) [0x55d1e9d36bae]
                            K-trading-bot(_ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultISt6vectorIN3à¸¿7mLevelsESaISA_EEEES3_ENSt6thread8_InvokerISt5tupleIJZNS9_14GwExchangeData14askForSyncDataERKjEUlvE0_EEEESC_EEE9_M_invokeERKSt9_Any_data+0x28) [0x55d1e9d13a48]
                       K-trading-bot(_ZNSt13__future_base13_State_baseV29_M_do_setEPSt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEEPb+0x1b) [0x55d1e9cadffb]
             /lib64/libpthread.so.0(+0xf267) [0x7fa0485da267]
                                                             K-trading-bot(_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZNSt13__future_base17_Async_state_implINS1_IS2_IJZN3à¸¿14GwExchangeData14askForSyncDataERKjEUlvE0_EEEESt6vectorINS5_7mLevelsESaISD_EEEC4EOSB_EUlvE_EEEEE6_M_runEv+0x109) [0x55d1e9d1d5c9]
                                                                     K-trading-bot(+0x5d371f) [0x55d1ea0ca71f]
                              /lib64/libpthread.so.0(+0x754b) [0x7fa0485d254b]
                                                                              /lib64/libc.so.6(clone+0x3f) [0x7fa04830a1af]

                                           Yikes!
                                                 please copy and paste the error above into a new github issue (noworry for duplicates).
                                                        If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new


                                                   12/07 14:38:47.993534 GW POLONIEX Quoting state changed to DISCONNECTED.
                                           12/07 14:38:47.993546 GW POLONIEX Attempting to cancel all open orders, please wait..
                                                double free or corruption (out)
                                                                               K exit code 1.
