### ISSUE TITLE
Krypto GDAX exchange

### ISSUE THREAD

**Issue by immanuelgerry** [ctubio/Krypto-trading-bot#853]
Hi there!
can i use GDAX coinbase pro exchange to test  my strategy using Krypto after i pay for the full unlocked version?

**Comment by ctubio** [comment]
yep, gdax is a [compatible exchange](https://github.com/ctubio/Krypto-trading-bot#compatible-exchanges)

**Comment by immanuelgerry** [comment]
i can't connect Krypto di GDAX public sandbox, it says that invalid API Keys. can you fix this?

**Comment by immanuelgerry** [comment]
Warrrrning: Unable to calculate quote, missing market data.
12/04 12:54:08.854478 GW COINBASE Warning {"message":"Invalid API Key"}.
12/04 12:54:09.854815 QE Warrrrning: Unable to calculate quote, missing market data.
12/04 12:54:10.855105 QE Warrrrning: Unable to calculate quote, missing market data.
12/04 12:54:11.855290 QE Warrrrning: Unable to calculate quote, missing market data.
12/04 12:54:12.855425 QE Warrrrning: Unable to calculate quote, missing market data.
12/04 12:54:13.556714 GW COINBASE FIX Logout, reconnecting in 7s..
12/04 12:54:14.556959 QE Warrrrning: Unable to calculate quote, missing market data.
12/04 12:54:14.800904 GW COINBASE WS Disconnected, reconnecting in 7s..

**Comment by immanuelgerry** [comment]
![whatsapp image 2018-12-04 at 7 54 14 pm](https://user-images.githubusercontent.com/44962291/49443543-59327400-f7ff-11e8-962e-dd793da60ad7.jpeg)
