### ISSUE TITLE
Can't cancel orders on FCoin

### ISSUE THREAD

**Issue by dcfinex** [ctubio/Krypto-trading-bot#856]
The bot couldn't orders on the FCoin even though the debug logs seem to be correct. 

> 
> 12/11 17:57:01.067266 DEBUG OG   saved  AOZLYcju7Uvl3Vaa:: [0]: 0.01000000 ETH at price 20.00000000 USDT.
> 12/11 17:57:01.067294 DEBUG OG memory 1.
> 12/11 17:57:01.477683 DEBUG OG   reply  AOZLYcju7Uvl3Vaa::gt7L-8RjLjufZZgEpVBANNPVHrogmzR2SomLjgZIPblaXVCv8rR46y8TOezIdMXg [1]: 0.01000000 ETH at price 20.00000000 USDT.
> 12/11 17:57:01.477720 DEBUG OG   saved  AOZLYcju7Uvl3Vaa::gt7L-8RjLjufZZgEpVBANNPVHrogmzR2SomLjgZIPblaXVCv8rR46y8TOezIdMXg [1]: 0.01000000 ETH at price 20.00000000 USDT.
> 12/11 17:57:01.477727 DEBUG OG memory 1.
> 12/11 17:57:11.298158 DEBUG OG  cancel  AOZLYcju7Uvl3Vaa::gt7L-8RjLjufZZgEpVBANNPVHrogmzR2SomLjgZIPblaXVCv8rR46y8TOezIdMXg [0]: 0.01000000 ETH at price 20.00000000 USDT.
> 12/11 17:57:13.558078 DEBUG OG   reply  AOZLYcju7Uvl3Vaa::gt7L-8RjLjufZZgEpVBANNPVHrogmzR2SomLjgZIPblaXVCv8rR46y8TOezIdMXg [2]: 0.00000000 ETH at price 0.00000000 USDT.
> 12/11 17:57:13.558114 DEBUG OG   saved  AOZLYcju7Uvl3Vaa::gt7L-8RjLjufZZgEpVBANNPVHrogmzR2SomLjgZIPblaXVCv8rR46y8TOezIdMXg [2]: 0.01000000 ETH at price 20.00000000 USDT.
> 12/11 17:57:13.558124 DEBUG OG memory 1.
> 12/11 17:57:13.558135 DEBUG OG   purge  AOZLYcju7Uvl3Vaa::gt7L-8RjLjufZZgEpVBANNPVHrogmzR2SomLjgZIPblaXVCv8rR46y8TOezIdMXg [2]: 0.01000000 ETH at price 20.00000000 USDT.
> 12/11 17:57:13.558145 DEBUG OG memory 0.

**Comment by halessi** [comment]
did you ever have any luck addressing this? facing same issue, maybe @asfbhero are u experiencing this

**Comment by asfbhero** [comment]
I didn't even bother buying another API key unlock for fcoin.  Without leverage it wasn't attractive enough to trade there.  Would you recommend them even without leverage?

**Comment by ctubio** [comment]
@halessi this was not fixed i believe, must be still happening

**Comment by halessi** [comment]
I'd like to explore it more @asfbhero, the rebates are super attractive and it trading volume (BTC) is ~1/3 GDAX. 

Unfortunately it's difficult to explore with the current glitch. I understand @ctubio if this isn't a priority. I'm incredibly busy with work and job apps right now, so v little time for coding + fun trading, but once school starts up (september) this (alongside the variable MA ranges) is on my list of things to maybe try and fix.

**Comment by ctubio** [comment]
:koala: i donno why i didnt fall in love with FCoin, i will retry soOn (now that seems that i will not be the only lover)

**Comment by asfbhero** [comment]
Well bequant now has maker fees and since getting margin accounts to work properly seems like it's very complicated, perhaps fcoin is the answer.  

@ctubio if you decide to work on this exchange let me know and I can do some testing for you.
