### ISSUE TITLE
Experimenting on Coinbase pro

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#857]
Hi Carles,

I'm back to Coinbase pro for some experiments, would you be so kind to re unlock my API ? :)

I'm not sure if I'm using a different one but I'm blocked again.
The BTC account is 354XBd6xneosZe62sps97971ieSNfhGY6y thank you !

Best regards,

Camille

**Comment by Camille92** [comment]
Well it's unlocked thank you :)

**Comment by Camille92** [comment]
Well some markets are unlocked (ETH/BTC) and other not (BTC/EUR), so idk what's up here :)

**Comment by ctubio** [comment]
sorry i missed this issue so long, i just unlocked it
