### ISSUE TITLE
Is it easier to integrate a new exchange with Krypto-bot than Tribeca?

### ISSUE THREAD

**Issue by gpoddar** [ctubio/Krypto-trading-bot#858]
I'm trying to setup a bot to market make on an exchange I'm launching to create liquidity. 

On Tribeca, theres a lot of manual things that could be written in a better manner to simplify adding a new exchange. Since you've added a bunch of new exchanges with Krypto, have you made any changes to Tribeca's gateway layer to make this easier?

PS: wish I had noticed this project earlier!!! See you have a lot of other cool new features over Tribeca (ex: ping-pong strategy has a lot more options. Also you can do market making with non-market neutral strategies).

**Comment by ctubio** [comment]
all classes related to exhange apis are at [/src/include/Krypto.ninja-apis.h](https://github.com/ctubio/Krypto-trading-bot/blob/master/src/include/Krypto.ninja-apis.h)

main change was to stop using javascript for the server
