### ISSUE TITLE
Bot not seeing the market @bitifnex

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#86]
Hello Carles,

I've seen this happening a couple of time it's fixed with a restart but I have no clue why it's happening and how often.

I thought I was being "rate limited" but I work well on other markets (even with the same ip).

So I don't know what could be the reason. When this happens trading is stopped.

I don't have logs because I don't know how to provoke it :S. Is there is a command to put the process forward in the console when it was started by npm start?

I wish I could come with more!

Market OMG/USD

![capture d ecran 2017-07-20 a 18 56 43](https://user-images.githubusercontent.com/6861590/28429739-0cbe27b6-6d7e-11e7-87e1-75db6a6109eb.png)

**Comment by ctubio** [comment]
im sorry im not interested into donate time to bitfinex (i dont use bitfinex currently); will look at it while migrating maaaaaybe (if the issue still exists)

**Comment by ctubio** [comment]
reopening to free it from the mind

**Comment by Camille92** [comment]
Hey it's a weird issue because it seems to happen only on OMG/USD.

Anyone else having the same?

**Comment by ctubio** [comment]
may be a bug of the app, cos seems ok that market (at https://www.websocket.org/echo.html try to connect to `wss://api.bitfinex.com/ws/2`  and send `{ "event": "subscribe","channel": "book", "symbol": "tOMGUSD", "prec": "P0", "freq": "F0"}`

**Comment by Camille92** [comment]
I did not see it happening again.

So ... I don't know ^^'
