### ISSUE TITLE
HitBTC Decimal Issue (Doge)

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#862]
Still having an issue with decimal places dropping. This time with Doge/BTC.

Web UI is showing proper bid/ask price but HitBTC UI is showing the wrong price.
https://i.imgur.com/qX1V5d2.png
https://i.imgur.com/rIipbQa.png

**Comment by ctubio** [comment]
im not sure that i understand it; you mean we should fix HitBTC UI?

**Comment by MiningInMySleep** [comment]
K Web interface is showing the proper decimal places, but orders submitted to HitBTC seem to be stripping the last 2 decimal places.

**Comment by ctubio** [comment]
oh the values send from K to HitBTC okok thanks for confirm

**Comment by ctubio** [comment]
sorry one more question just to be sure we are in the same situation, can you please share your minTick/minSize values displayed at the begining?
thanks''

**Comment by MiningInMySleep** [comment]
01/06 08:17:21.183862 GW HITBTC setup:
- gateway: https://api.hitbtc.com/api/2
- gateway: wss://api.hitbtc.com/api/2/ws
- autoBot: no
- symbols: DOGEBTC
- minTick: 0.0000000001
- minSize: 10.0000000000
- makeFee: 0.0000000000
- takeFee: 0.0000000000.

**Comment by ctubio** [comment]
many thanks for your help'' hope next commit does what you expect
