### ISSUE TITLE
[Bitfinex] Wrong balance

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#865]
Hi Carles! Look at screenshot. Wish i had such amount of btc and usd :)
Something wrong on latest commit.
![k-bitfinex-issue](https://user-images.githubusercontent.com/10449591/51263144-bc99ef00-19c4-11e9-8dad-729d766244d3.jpg)

**Comment by serzhiio** [comment]
...order price and size calculates normally.

**Comment by ctubio** [comment]
many thanks for the report''
lets remove the `*1000000` that we are applying to bitfinex values
