### ISSUE TITLE
Feature Request - Sleep Until Price

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#868]
It would be awesome if we could set the bot to not make any trades until a certain price is reached. Something similar is possible with EWMA_4, but being able to fine tune to specific price levels would be even better.

**Comment by ctubio** [comment]
thanks for the suggestion'¡

liiiike, while having red big button, allow to auto go green if price is greater or lower than X?

**Comment by boogey100** [comment]
I think min and max price options would work here too as per https://github.com/ctubio/Krypto-trading-bot/issues/789

**Comment by ctubio** [comment]
@MiningInMySleep lets do this at #789, hope you agree :dancer:

the plan on #789 is still to not trade until a specific price is reached, let me know if you think that is not the very same as this issue; thank you'''
