### ISSUE TITLE
TRX/BTC HitBTC Ping Size Issue

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#870]
- symbols: TRXBTC
- minTick: 0.0000000001

Currently ping/pong width is limited to 8 decimal places. Should be at 10 for this pair.

**Comment by ctubio** [comment]
let me see why is not that way

many thanks for the report''''

**Comment by ctubio** [comment]
:koala: need to replace everywhere `1e-8` by `minTick` or `minSize`, but `gateway` is not yet accessible everywhere; soOn''

**Comment by ctubio** [comment]
after next commit `widthPing` and `withPong` are based on `minTick` and `sizeBuy` and `sizeSell` are based on `minSize`

that was like 2 years since we are trying to do this :D many thanks again for insist'¡
