### ISSUE TITLE
Bid/Ask % Less Than 1

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#871]
Thanks for the latest commit! In addition, would it be possible to have Bid/Ask % less than 1? such as .1% or .01% of total stack? 1% can end up being a lot to risk when aiming to profit from trading volume alone. But percent mode is very useful for scaling based on remaining funds. Thanks!

**Comment by ctubio** [comment]
that value comes from the exchange, and cannot place orders smaller than what the minSize set by the exchange

hope it helps'''

**Comment by ctubio** [comment]
using decimals is possible to set any value **greater than** minSize because https://github.com/ctubio/Krypto-trading-bot/blob/dfae1e548ce969b75480fb33131befcc987ddaac/src/lib/Krypto.ninja-data.h#L2443-L2460

**Comment by MiningInMySleep** [comment]
Trying to set .1% on the interface automatically sets it to 1% instead.
For example, a 100BTC account trading 60 BTC pairs would be extremely high risk at 1%. .1 or even .001 would be useful depending on the situation.
