### ISSUE TITLE
Weird bid/askSize Issue

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#873]
This is for the non-% mode.

Currently have BTC orders set to 0.00015 bid/ask but exchange interface shows 0.00014 for normal orders and 0.00029 for SOP. Same thing for ETH with 0.0045 on K interface but 0.0044/0.0089 on exchange.

This is running latest commit and it has been doing this since https://github.com/ctubio/Krypto-trading-bot/commit/a2917f52276dceb76946aa4224bd1d20ab62a72e.

Edit: Setting ETH to 0.0046 in K interface shows up properly on exchange but setting it back to 0.0045 in K interface causes it to show as 0.0044 in exchange again.

**Comment by ctubio** [comment]
that may be because `applyRoundSize()` is still using `floor()`; lemem review it :S

**Comment by ctubio** [comment]
i still wanna centralize the roundings of size and price, but for now after next commit we will not missing decimals

lets do like this never happened :D

![triplefacepalm](https://user-images.githubusercontent.com/1634027/52234201-646a5480-28c1-11e9-8983-6a9b106e39f6.jpg)

**Comment by ctubio** [comment]
btw, just to mess it more, latest version is still v0.4.12+14 (im sorry i failed the +1)
