### ISSUE TITLE
Compile with Slackware (wifislax)

### ISSUE THREAD

**Issue by juaxix** [ctubio/Krypto-trading-bot#876]
Hello again :) i'm trying to compile it with slackware (wifislax64 1.1) but I think the Makefile is not ready for it, because it tries to use apt-get instead of slackpkg ,following the instructions to install from zip -manually-:

```
wifislax64 Krypto-trading-bot-master # curl https://raw.githubusercontent.com/ctubio/Krypto-trading-bot/master/Makefile > Makefile 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15073  100 15073    0     0  24108      0 --:--:-- --:--:-- --:--:-- 24548
wifislax64 Krypto-trading-bot-master # make install
test -n "`command -v apt-get`" && sudo apt-get -y install g++ build-essential automake autoconf libtool libxml2 libxml2-dev zlib1g-dev python curl gzip screen doxygen graphviz \
|| (test -n "`command -v yum`" && sudo yum -y install gcc-c++ automake autoconf libtool libxml2 libxml2-devel python curl gzip screen) \
|| (test -n "`command -v brew`" && (xcode-select --install || :) && (brew install automake autoconf libxml2 zlib python curl gzip screen proctools doxygen graphviz || brew upgrade || :)) \
|| (test -n "`command -v pacman`" && sudo pacman --noconfirm -S --needed base-devel libxml2 zlib curl python gzip screen)
Makefile:168: fallo en las instrucciones para el objetivo 'packages'
make: *** [packages] Error 1
wifislax64 Krypto-trading-bot-master # 

```

I installed the requeriments by myself using this slackpkg command, and then just a make but

`wifislax64 Krypto-trading-bot-master # make
Building hello-world..
make  src KSRC=hello-world
make[1]: se entra en el directorio '/mnt/live/k/Krypto-trading-bot-master'
Building trading-bot..
make assets src KSRC=trading-bot
make[1]: se entra en el directorio '/mnt/live/k/Krypto-trading-bot-master'
Building hello-world src ..
Building trading-bot assets..
/bin/sh: -g: opción inválida
Modo de empleo: /bin/sh [opción GNU larga] [opción] ...
        /bin/sh [opción GNU larga] [opción] guión-del-shell
Opciones GNU largas:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --rcfile
        --restricted
        --verbose
        --version
Opciones del shell:
        -ilrsD or -c command or -O shopt_option         (invocation only)
        -abefhkmnptuvxBCHP o -o opción
g++ (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
Esto es software libre; vea el código para las condiciones de copia.  NO hay
garantía; ni siquiera para MERCANTIBILIDAD o IDONEIDAD PARA UN PROPÓSITO EN
PARTICULAR

make -C src/bin/trading-bot KASSETS=/mnt/live/k/Krypto-trading-bot-master/build-/local/assets
make[2]: se entra en el directorio '/mnt/live/k/Krypto-trading-bot-master/src/bin/trading-bot'
Building trading-bot src ..
make Linux CHOST=
/bin/sh: -g: opción inválida
Modo de empleo: /bin/sh [opción GNU larga] [opción] ...
        /bin/sh [opción GNU larga] [opción] guión-del-shell
Opciones GNU largas:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --rcfile
        --restricted
        --verbose
        --version
Opciones del shell:
        -ilrsD or -c command or -O shopt_option         (invocation only)
        -abefhkmnptuvxBCHP o -o opción
make[2]: se entra en el directorio '/mnt/live/k/Krypto-trading-bot-master'
make[3]: se entra en el directorio '/mnt/live/k/Krypto-trading-bot-master'
g++ (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
Esto es software libre; vea el código para las condiciones de copia.  NO hay
garantía; ni siquiera para MERCANTIBILIDAD o IDONEIDAD PARA UN PROPÓSITO EN
PARTICULAR

make[2]: *** No hay ninguna regla para construir el objetivo '/var/lib/K/node_modules/.bin', necesario para 'js'.  Alto.
make[2]: *** Se espera a que terminen otras tareas....
g++ -DNDEBUG -o build-/local/bin/K-hello-world \
  -DHAVE_STD_UNIQUE_PTR -DUWS_THREADSAFE         \
  -static-libstdc++ -static-libgcc -rdynamic     \
  src/bin/hello-world/hello-world.cxx -pthread -std=c++17 -O3 -I/mnt/live/k/Krypto-trading-bot-master/src/lib -DK_BUILD='""' -DK_SOURCE='"K-hello-world"' -DK_0_GIT='"HEAD"' -DK_STAMP='"2019-02-09 12:11:39"' -DK_0_DAY='"v0.4.12+19"' -Ibuild-/local/include         build-/local/include/uWS/*.cpp build-/local/lib/K-.a build-/local/lib/libquickfix.a build-/local/lib/libsqlite3.a build-/local/lib/libz.a        build-/local/lib/libcurl.a build-/local/lib/libssl.a      build-/local/lib/libcrypto.a build-/local/lib/libncurses.a  -ldl
sed: no hay ficheros de entrada
Makefile:115: fallo en las instrucciones para el objetivo 'src'
make[1]: [src] Error 123 (no tiene efecto)
make Linux CHOST=
/bin/sh: /var/lib/K/package.json: No existe el fichero o el directorio
Makefile:93: fallo en las instrucciones para el objetivo 'package.json'
make[2]: *** [package.json] Error 1
make[2]: se sale del directorio '/mnt/live/k/Krypto-trading-bot-master/src/bin/trading-bot'
Makefile:98: fallo en las instrucciones para el objetivo 'assets'
make[1]: *** [assets] Error 2
make[1]: *** Se espera a que terminen otras tareas....
make[2]: se entra en el directorio '/mnt/live/k/Krypto-trading-bot-master'
g++: error: build-/local/include/uWS/*.cpp: No existe el fichero o el directorio
g++: error: build-/local/lib/K-.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libquickfix.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libsqlite3.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libz.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libcurl.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libssl.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libcrypto.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libncurses.a: No existe el fichero o el directorio
Makefile:132: fallo en las instrucciones para el objetivo 'Linux'
make[3]: [Linux] Error 1 (no tiene efecto)
make[3]: se sale del directorio '/mnt/live/k/Krypto-trading-bot-master'
make[2]: se sale del directorio '/mnt/live/k/Krypto-trading-bot-master'
chmod: no se puede acceder a 'build-/local/bin/K-hello-world*': No existe el fichero o el directorio
Makefile:115: fallo en las instrucciones para el objetivo 'src'
make[1]: *** [src] Error 1
make[1]: se sale del directorio '/mnt/live/k/Krypto-trading-bot-master'
Makefile:94: fallo en las instrucciones para el objetivo 'hello-world'
make: *** [hello-world] Error 2
make: *** Se espera a que terminen otras tareas....
make[3]: se entra en el directorio '/mnt/live/k/Krypto-trading-bot-master'
g++ -DNDEBUG -o build-/local/bin/K-trading-bot \
  -DHAVE_STD_UNIQUE_PTR -DUWS_THREADSAFE         \
  -static-libstdc++ -static-libgcc -rdynamic     \
  src/bin/trading-bot/trading-bot.cxx -pthread -std=c++17 -O3 -I/mnt/live/k/Krypto-trading-bot-master/src/lib -DK_BUILD='""' -DK_SOURCE='"K-trading-bot"' -DK_0_GIT='"HEAD"' -DK_STAMP='"2019-02-09 12:11:39"' -DK_0_DAY='"v0.4.12+19"' -Ibuild-/local/include         build-/local/include/uWS/*.cpp build-/local/lib/K-.a build-/local/lib/libquickfix.a build-/local/lib/libsqlite3.a build-/local/lib/libz.a        build-/local/lib/libcurl.a build-/local/lib/libssl.a      build-/local/lib/libcrypto.a build-/local/lib/libncurses.a  -ldl
g++: error: build-/local/include/uWS/*.cpp: No existe el fichero o el directorio
g++: error: build-/local/lib/K-.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libquickfix.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libsqlite3.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libz.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libcurl.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libssl.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libcrypto.a: No existe el fichero o el directorio
g++: error: build-/local/lib/libncurses.a: No existe el fichero o el directorio
Makefile:132: fallo en las instrucciones para el objetivo 'Linux'
make[3]: [Linux] Error 1 (no tiene efecto)
make[3]: se sale del directorio '/mnt/live/k/Krypto-trading-bot-master'
make[2]: se sale del directorio '/mnt/live/k/Krypto-trading-bot-master'
sed: no hay ficheros de entrada
Makefile:115: fallo en las instrucciones para el objetivo 'src'
make[1]: [src] Error 123 (no tiene efecto)
chmod: no se puede acceder a 'build-/local/bin/K-trading-bot*': No existe el fichero o el directorio
Makefile:115: fallo en las instrucciones para el objetivo 'src'
make[1]: *** [src] Error 1
make[1]: se sale del directorio '/mnt/live/k/Krypto-trading-bot-master'
Makefile:94: fallo en las instrucciones para el objetivo 'trading-bot'
make: *** [trading-bot] Error 2`

do you have any compiled version or should i just change my distro?

**Comment by ctubio** [comment]
compiled versions are provided at https://github.com/ctubio/Krypto-trading-bot/releases, the arch supported are:
* linux-x86_64
* linux-aarch64
* linux-arm
* apple-x86_64
* win64-x86_64

about the packages installed by `apt-get`, you can commit a modification to the packages target of the Makefile to add your favorite package manager; meanwhile your favorite package manager is not supported by `make packages`, the only solution is to use a distro compatible with `apt-get`, `yum` or `brew` (That is debian based, centos based or macOS based currently). If you ask me i recomend you to use Debian Buster.

hope this helps'''

**Comment by ctubio** [comment]
feel free to join the IRC channel if you have questions (were conversations may be more effective)
