### ISSUE TITLE
Pongs in Memory

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#881]
At the bottom of the K interface, there is a stat for "Pings in Memory".
Can we have one for pongs - in other words, completed trades that have a Kdiff?
It'll be useful to gauge performance during the memory timeframe without having to scroll or dive into stats/exchange reports. And sometimes exchange reports aren't even functioning *cough*hitbtc*cough*.

Edit: Actually, having an option to print total pings / pongs to console whenever a trade is made would be super useful (at least for me).

**Comment by ctubio** [comment]
morniiing''
will consider soOn; many thanks for the suggestion''

**Comment by ctubio** [comment]
note that K acumulates trades of the same price, so the total count of trades in history is not the total amount of orders completed

**Comment by ctubio** [comment]
hope for it on next commit'¡ many thanks for the suggestion againz'''

about the log messages: the old counter of pings and now the new counter of pongs are only counted in the UI, thats why i didnt added any console log, cos the server does not count pings or pongs currently.
