### ISSUE TITLE
Limit max account value to be used by bot

### ISSUE THREAD

**Issue by CooleRnax** [ctubio/Krypto-trading-bot#883]
**Problem:**
Currently running multiple bots with different symbols on single account doesn't work correctly.
Wallet-limit was designed to solve it, but the approach was a little bit wrong.

**I see two ways to solve it:**
**1. Best from my point of view, but harder to implement.**
@ctubio previously mentioned that this approach is not implemented because of the performance issues, but i think it is possible.

- Limit account value based on % of all available funds.
- Available funds update period

So the bot will update full account value once per 5-10 minute.
Performance should be fine in such approach.

**2. Easier to implement, but requires periodically update bots by the user.**
Or we can limit max account value this way:
- Limit max account value to COIN
- Limit max account value to CURRENCY
- Limit max account value to USD (this should be good if you have different currency pairs (USD, EUR, BTC, JPY, GPB) on single account)

This option should be available from GUI without need of restarting the bot.

**Main benefit in my approach, if limits are set correctly, every instance will behave as a different account because it has dedicated value from the main account.**
You will not need to tweak order size, target base position, position div every time you change amount of running bots, just change max account value.

**Comment by CooleRnax** [comment]
I have realized, that there is also a third way:
Implement both

**Comment by ctubio** [comment]
we really dont want to read all wallets for trade into 1 single pair, maybe once we are able to trade on multiple curriencies with a single bot instance
