### ISSUE TITLE
Bitfinex --wallet-limit bugs

### ISSUE THREAD

**Issue by CooleRnax** [ctubio/Krypto-trading-bot#886]
@ctubio thanks for tha update.
We bacame nearer to the working version.
But there are some issues.

**First bug**
At start it is somehow works but actual value is more than limit.
Live example LTC/USD limit is 2.8869098 which is around 142.5 USD.
![image](https://user-images.githubusercontent.com/980180/53695476-3c411900-3dcd-11e9-8bb5-5d84576e8506.png)
Here you can see that actual account limit is 1.94+(143.16/49.5)=4.83 which is bigger than 2.8869098

**Second bug**
Than after a while something happens (probably a trade), and USD value becomes unlimited.
![image](https://user-images.githubusercontent.com/980180/53695334-32b6b180-3dcb-11e9-8af5-8cf7bd908287.png)

**Third bug**
Actual account value is higher than 2.8869098 LTC (~142.5 USD)
I think this bug is because of bug number 2.
![image](https://user-images.githubusercontent.com/980180/53695334-32b6b180-3dcb-11e9-8af5-8cf7bd908287.png)

**Comment by ctubio** [comment]
lemme see bitfinex; i was testing with coinbase and hitbtc the fix (but bitfinex should be the same :S will review soOn'')

**Comment by ctubio** [comment]
because you are running the latest version, right?

**Comment by CooleRnax** [comment]
let me check

**Comment by ctubio** [comment]
note that `git` commands do not update nothing, `make latest` or `make  install` is required for upgrade

**Comment by ctubio** [comment]
on boot should say as of today:
```
v0.4.13+6 (0day).
```

**Comment by CooleRnax** [comment]
I made sure that I have the latest version.
I have recorded a video.
https://www.dropbox.com/s/ems54przscpxlbn/2019-03-03%2016.45.38.mp4?dl=0

**Comment by ctubio** [comment]
confirmed only happens on Bitfinex gateway, mostly possible cos bitfienx sends wallets one by one instead of both together

**Comment by ctubio** [comment]
confirmed² `ws` messages comes together but `wu` comes 1 by 1 :( will fix soOn''

**Comment by CooleRnax** [comment]
great!

**Comment by ctubio** [comment]
many thanks for insist on this issue''

![giphy-downsized](https://user-images.githubusercontent.com/1634027/53700184-f47fb900-3def-11e9-9db2-413beeb2f28c.gif)

**Comment by CooleRnax** [comment]
Still doesn't work for me.
Here is what i get with --wallet-limit 3.28905959
![image](https://user-images.githubusercontent.com/980180/53700522-6bbf4800-3e04-11e9-9db8-95a773ea0bb2.png)

**Comment by CooleRnax** [comment]
I this case:
I expect USD to be limited up to ~19.55
And value to be limited up to 3.289 LTC (~160 USD)

**Comment by ctubio** [comment]
held values cannot be limited, only available values, and available usd in your image is 9.428, so less than 19.55; looks all fine to me. cancel the orders to release the funds and to allow them to be limited once they are available

**Comment by CooleRnax** [comment]
Total account value is still not limited, this is the main problem.
It causes issues with order sizes and target positions when % is used.

I see two ways to solve:
1. Limit CURRENCY held
or
2. Limit COIN and CURRENCY values

**Comment by CooleRnax** [comment]
here is what I get when I limit COIN and CURRENCY values
![image](https://user-images.githubusercontent.com/980180/53705391-341cc400-3e35-11e9-8194-9bdafa565f6d.png)

**Comment by CooleRnax** [comment]
I do it this way.
``
      void calcValues() {
        if (K.arg<double>("wallet-limit")) {
          if (base.total > K.arg<double>("wallet-limit"))
            base.total = K.arg<double>("wallet-limit");
          if (quote.total > K.arg<double>("wallet-limit") * fairValue)
            quote.total = K.arg<double>("wallet-limit") * fairValue;
        }

        base.value  = (quote.total / fairValue) + base.total;
        quote.value = (base.total * fairValue) + quote.total;
        
        if (K.arg<double>("wallet-limit")) {
          if (base.value > K.arg<double>("wallet-limit"))
            base.value = K.arg<double>("wallet-limit");
          if (quote.value > K.arg<double>("wallet-limit") * fairValue)
            quote.value = K.arg<double>("wallet-limit") * fairValue;
        }
      };
``

**Comment by ctubio** [comment]
the total is an implicit sum of held + amount

first set your unreal amounts, and later sum your real helds (cos you cannot set helds to unreal values)

as well as helds, do not set totals to unreal values, cos it really doesnt makes sense.

you may see the values that you want in the UI, but somehow what you want is not real

**Comment by ctubio** [comment]
also, calcValues() is called from everywhere; are you sure you dot want just to limit the data coming from the gateway?

**Comment by ctubio** [comment]
and you are applying the limit to each side individualy, so your totals should be x2, but you are not doing any x2 in your totals.

you are missing to understand this:
base total = quote held + quote available + base held + base available in base currency
quote total = quote held + quote available + base held + base available in quote currency

**Comment by CooleRnax** [comment]
Bot is very complex. I can't limit data from gateway yet.

**Comment by CooleRnax** [comment]
quote held + quote available + base held + base available in base currency <= limit

**Comment by CooleRnax** [comment]
if it will be true i will be able to setup every bot as a single instance

**Comment by ctubio** [comment]
yea, and that formula you said should also consider that the held amounts are held and cannot be limited, and that the quote amount can be limited ONLY after the base amount (cos the quote amount is somewhat also held (from the base point of view)

**Comment by CooleRnax** [comment]
yep base is main here

**Comment by CooleRnax** [comment]
why held can't be limited?

**Comment by ctubio** [comment]
so, if there is a held amount, values can be bigger than limit, cos only available values can be limites. maybe thats what is breaking you?

**Comment by CooleRnax** [comment]
my version is actually work as expected

**Comment by ctubio** [comment]
becaaause held is held, it exists. it is in circulation already for that wallet. is not a elastic asset, cannot be limited without hidding part of the reality (like quote amounts)

available amount is not existent yet in the market. can be bigger or smaller at any time without making your finances unreal, is a elastic asset, allows to be limited

**Comment by CooleRnax** [comment]
Do we actually need Currency that is held in other markets?

**Comment by CooleRnax** [comment]
this held breaks limits

**Comment by ctubio** [comment]
if yours works as you want, i would say then to leave it as is, but i cannot include it in the general sources

i do belive you want something similar but not exactly to the same of what was expected with --wallet-limit

anyway, thanks for pointing the bugs of --wallet-limit :D

**Comment by ctubio** [comment]
yea, held is expected to break limits, cos cannot be limited (in the general bot; donno in your version :D)

**Comment by CooleRnax** [comment]
lets implement this as value limit

**Comment by CooleRnax** [comment]
my version of this

**Comment by CooleRnax** [comment]
so we will have versions that fits all use cases.

**Comment by CooleRnax** [comment]
and in my vision it would be more logical to limit to currency instead of base

**Comment by CooleRnax** [comment]
I saw other people asked for this too...

**Comment by ctubio** [comment]
i dont understand the sentence "limit to currency instead of base"

we have base currency and quote currency, and both have available amount and held amount, that becomes total amount and value amount

what means "currency" alone? and base alone?

**Comment by CooleRnax** [comment]
quote

**Comment by CooleRnax** [comment]
I mean for my case it is better to specify limit in quote currency

**Comment by CooleRnax** [comment]
today I will fix x2 in my code

**Comment by CooleRnax** [comment]
I was able to achieve correct held.
But it only works when order is alive. Maybe you can take a look?
![image](https://user-images.githubusercontent.com/980180/53753736-08e0b600-3ec3-11e9-89fb-62f23edba6d3.png)
```
      void calcValues() {
        if (K.arg<double>("wallet-limit")) {
          if (base.total > K.arg<double>("wallet-limit")) {
            base.total = K.arg<double>("wallet-limit");
            quote.total = 0;
          }
          else if (quote.total / fairValue + base.total > K.arg<double>("wallet-limit")) {
            quote.total = (K.arg<double>("wallet-limit") - base.total) * fairValue;
          }
        }

        base.value  = (quote.total / fairValue) + base.total;
        quote.value = (base.total * fairValue) + quote.total;
      };
```

**Comment by CooleRnax** [comment]
My current goal is to make bot ignore all held except current symbol.
As i understood it happens here:
```
      const double heldAmount(const Side &side) const {
        double held = 0;
        for (const auto &it : orders)
          if (it.second.side == side)
            held += (
              it.second.side == Side::Ask
                ? it.second.quantity
                : it.second.quantity * it.second.price
            );
        return held;
```

**Comment by ctubio** [comment]
yea, i think you want to call something like:
```
base.held = orders.heldAmount(Side::Ask)
quote.held = orders.heldAmount(Side::Bid)
```
and let the totals be calculated as usual

**Comment by CooleRnax** [comment]
> yea, i think you want to call something like:
> 
> ```
> base.held = orders.heldAmount(Side::Ask)
> quote.held = orders.heldAmount(Side::Bid)
> ```
> and let the totals be calculated as usual

yep i wanted to keep totals and values untouched.
