### ISSUE TITLE
WARNING : HitBTC is changing its fees ! no more rebate

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#887]
Hi guys,

Just to let you know that hitbtc will no longer offer a rebate (unless you trade the ridiculous amount of 6K BTC a month).

So maybe think about going to another exchange :)

**Comment by flfsbr** [comment]
I agree with you. It will be difficult to make a profit that way. What other exchange do you think would be interesting?

**Comment by Camille92** [comment]
I think Coinbase pro is the best option!

**Comment by flfsbr** [comment]
I'm from Brazil, Coinbase Pro is not available here.

**Comment by flfsbr** [comment]
HitBTC has released Bequant.io which will keep the current fee and rebate. The volumes of the coins are the same in both exchanges and the api is also the same. It can be a good option to escape the new fees.

**Comment by Camille92** [comment]
That sounds like a very good idea!

So we just need to change the api address and it would work?

**Comment by flfsbr** [comment]
No. You need a new registration and create a new API.
I created a topic asking Carles to evaluate the possibility.

**Comment by Camille92** [comment]
Yes of course but I mean technically, it's the same no?

**Comment by flfsbr** [comment]
the only practical change I'm seeing is the change from api.htbtc.com to api.bequant.io the rest remains the same.

**Comment by Camille92** [comment]
Sounds perfect !

**Comment by ctubio** [comment]
it may be just a proxy cos same api keys works

**Comment by Camille92** [comment]
So you think it would work if I put just my data from their account ?

Le mar. 5 mars 2019 à 21:00, Carles Tubio <notifications@github.com> a
écrit :

**Comment by ctubio** [comment]
yea, same login/pass/api

**Comment by MiningInMySleep** [comment]
I'm a little worried that the fees may not be avoided since the funds and API key are still apart of HitBTC and don't show up on bequant.io at all. Would be a very useful trick if it works.

**Comment by Camille92** [comment]
Can someone please check and keep the rest updated. I would not have time
tonight :/

Le mer. 6 mars 2019 à 16:04, MiningInMySleep <notifications@github.com> a
écrit :

**Comment by ctubio** [comment]
hitbtc and bequant use the engine of https://multiexchange.com/

to me look the very same all of them; same users/orders/fees; diff domains only

**Comment by Camille92** [comment]
Hi everyone,

I've put some test funds on a bequant account and I'm pleased to announce you that there's still the rebate at bequant !

![capture d ecran 2019-03-07 a 10 16 57](https://user-images.githubusercontent.com/6861590/53945578-36e01900-40c2-11e9-9264-270f8566fff0.png)
![capture d ecran 2019-03-07 a 10 17 07](https://user-images.githubusercontent.com/6861590/53945585-3ba4cd00-40c2-11e9-95d8-83e78f623610.png)

**Comment by ctubio** [comment]
niiiice

**Comment by Camille92** [comment]
Yep !

if you don't mind unlocking :p 3LkVhtXLtxWRp8fBEuunmrgZDdM3CS4Vnd
I think I'll move there!
