### ISSUE TITLE
Add support for Bequant.io

### ISSUE THREAD

**Issue by flfsbr** [ctubio/Krypto-trading-bot#888]
Hi Carles, What do you think of adding HitBTC's new exchange support? Bequant.io

It seems to me that api is the same.

**Comment by ctubio** [comment]
but that is for institutions, nope? im not sure that i can register there :S

**Comment by ctubio** [comment]
oh, seems they have INDIVIDUAL accounts too
well, thanks for suggest it; i will loOk at it soOn''

**Comment by Camille92** [comment]
So apparently they are partner exchange with hitbtc, not the same company.

But they share the same book with lower fees ;)

**Comment by ctubio** [comment]
the latency of Bequant is quite amazing, looks like we are in the same server to me xDD

**Comment by Camille92** [comment]
Yes ? Where are you based :p ?

**Comment by ctubio** [comment]
dreamhost for the win :D
