### ISSUE TITLE
Bot ping but not pong on poloniex exchange + others poloniex informations

### ISSUE THREAD

**Issue by yepla** [ctubio/Krypto-trading-bot#89]
Hello,
I have try the bot on poloniex echange but something is wrong.
The bot only Ping it doesn't Pong !
It will be great if the bot will work on poloniex because even if fees are more expensive than on gdax on poloniex we can trade with a small minimal volume.
Note than the minimum volume on poloniex are 0.0001 btc not 0.01 and price is set to more or less 0.00000001 not 0.01.
Note too than taker fees is 0.25% not 0.2% and maker fees are 0.15% not 0.1% like i have seen in code !
If someone ca fix it it will be so nice.
Thanks.

**Comment by ctubio** [comment]
there is no difference ina ping or a pong, both are completed orders.
if it pings it pongs too, and if it doesnt pongs it neither pings.
i cant imagine why it can ping and not pong.

**Comment by yepla** [comment]
Really dont know but i was using LongPingFair the bot ping and never pong even if the rate is so much less under the Ping
