### ISSUE TITLE
Bequant.io API w/HitBTC API/Funds Is Not Fee-less

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#892]
Just checked the trade reports after the new system went live (UTC 20:00) and fees are definitely being applied with Bequant API + HitBTC API Key/Funds.

https://i.imgur.com/FoQbTbR.png

Edit: If we are looking for a possible new exchange to support in replacement, I would like to put in a(nother) request for Binance. Volume and coin support is as good as it gets on spot exchanges.

**Comment by ctubio** [comment]
i reopened #606 but ws data of Binance is not yet about place/cancel orders, just about market data

**Comment by Camille92** [comment]
Hey I've had no fees on bequant website, manual trading.
