### ISSUE TITLE
Kraken websocket support

### ISSUE THREAD

**Issue by nshopik** [ctubio/Krypto-trading-bot#893]
Kraken recently added websocket support for their public API, would be nice to have it in K

https://www.kraken.com/features/websocket-api

**Comment by ctubio** [comment]
thanks for the suggestion; i had planned to do this but didnt found time yet; soOn''¡

**Comment by ctubio** [comment]
kraken ws is only about book levels, it doesnt have place/cancel orders yet so im not implementing until orders are also included in the ws (i hope for it)

**Comment by nshopik** [comment]
yeah, they will extend support support for private calls soon (within 6-8 weeks)

**Comment by nshopik** [comment]
https://support.kraken.com/hc/en-us/articles/360034298312-Kraken-WebSockets-API-Private-Beta-Feeds-Available
@ctubio

**Comment by ctubio** [comment]
<a href="https://www.youtube.com/watch?v=ppcqWpZUrK4"><img src="https://user-images.githubusercontent.com/1634027/66076886-0d577500-e55f-11e9-9227-db4f99cd2b73.jpg"></a>


yaYyy'¡ i see now `addOrder` and `cancelOrder` functions at https://www.kraken.com/features/websocket-api-beta

many thanks for the notice'¡!

:koala: will be done next once i recover from my non-commit protest (im waiting for listen the sentence of the judge over of the 9 jailed somday this month)

**Comment by ctubio** [comment]
:koala: seems the api is no more in beta; let get hands dirty'¡
