### ISSUE TITLE
Kraken no wallet data

### ISSUE THREAD

**Issue by nshopik** [ctubio/Krypto-trading-bot#895]
Trying to configure Kraken, but I've got no wallet data show. am I missing something or its bug? 

![image](https://user-images.githubusercontent.com/4439311/54056082-161ddd80-4200-11e9-95c7-bf8a5d37ede0.png)

**Comment by boogey100** [comment]
I have the same on Kraken. I have some error debug messages, but nothing useful i think.

04/10 20:28:52.398006 GW KRAKEN Quoting state changed to CONNECTED.
04/10 20:28:52.398142 QE Warrrrning: Unable to calculate quote, missing market data.
04/10 20:28:53.236729 DEBUG KRAKEN <<< {"error":["EAPI:Invalid nonce"]}.
04/10 20:28:53.399039 QE Warrrrning: Unable to calculate quote, missing market data.
04/10 20:28:54.175009 DEBUG KRAKEN <<< {"error":[],"result":{"BCHEUR":{"asks":[["272.500000","0.013",1554928.
04/10 20:28:55.427082 UI 1 client connected, last connection was from 2a01:4b00:f02d:a600:e5bf:9321:7001:20e0.
04/10 20:28:59.722750 DEBUG KRAKEN <<< {"error":[],"result":{"BCHEUR":{"asks":[["272.500000","0.013",1554928.

**Comment by grhangelone** [comment]
Same here.
I wanted to try Kraken, since this is one of the only exchanges with very lttle washtrading.
https://www.blockchaintransparency.org/reports
So this could be interesting.
Sadly it doesn't work :)

**Comment by ctubio** [comment]
:koala: thank for the patience'''
finally i got  unlazy and fixed kraken symbols; im not sure that i understood why kraken have multiple ids for the same asset (XBT and XXBT or EUR and ZEUR), but anyway we now support it :D

about the websocket of kraken, im still waiting to implement it cos it just streams book levels, it does not have yet any method to place/cancel orders

**Comment by nshopik** [comment]
When i worked with their API, they prepend X to all crypto pairs and Z to fiat pair

**Comment by ctubio** [comment]
yep but my confusion is because they dont do this to all, but to some (most) pairs; seems inconsitent to me

**Comment by nonkreon** [comment]
so kraken alive now? :champagne:

**Comment by ctubio** [comment]
i hope so, but still is REST 100% (see https://github.com/ctubio/Krypto-trading-bot/issues/893)

**Comment by nshopik** [comment]
```
03/26 18:55:56.240545 GW KRAKEN Warrrrning: Error message: {"error":["EGeneral:Invalid arguments"]}.
03/26 18:55:56.526497 GW KRAKEN WS streaming [orders|trades|levels|wallet].
03/26 18:55:56.526810 GW KRAKEN network state changed to CONNECTED.
03/26 18:55:56.858676 UI 1 client connected, last connection was from 192.168.1.104.
03/26 18:56:14.515149 QE Warrrrning: Unable to calculate TBP, missing wallet data.
```
Not sure if this is new, decided to try again
