### ISSUE TITLE
make fails on ubuntus

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#900]
see travis outputs and https://github.com/ctubio/Krypto-trading-bot/pull/899

**Comment by xloem** [comment]
It looks like you are setting the c++ ABI based on the libc version.  The libc version is not necessarily related to the C++ ABI in any way, unfortunately.  In 21c146b8951356ca1beac80394c708429eaeae7d the C++ ABI is checked for directly (I'm fuzzyTew).

**Comment by ctubio** [comment]
i was wrong yea :P
with your nice check i found it failing somewhere, thats why i avoided it; let me understand why was failing on my tests and i will recover your nice 21c146b

**Comment by ctubio** [comment]
just saying, i can't find any OS where the following code returns nothing:
```
echo '\#include <string>' | x86_64-linux-gnu-g++ -x c++ -std=c++0x -dM -E - | grep '_GLIBCXX_USE_CXX11_ABI 1' || echo compat
```

all return `compat` and i was expecting to catch in advance (or not) those linking errors

are you telling me that all OS need to be compat? (i was expecting for example Debian 8 to need a downgrade but Debian 10 to be all fine as-is)

**Comment by ctubio** [comment]
ok i think thiz snipped workz better:
```
 echo -e '#include <string>\nstd::string foo __attribute__ ((visibility ("default")));' | g++ -std=c++17 -x c++ -dM -E -
```

**Comment by ctubio** [comment]
oh well, finally somewhat like:
```
echo '#include <string>' | g++ -std=c++17 -x c++ -dM -E -
```

seems the problem was the prefixed `\` :D

**Comment by ctubio** [comment]
many many thanks for your explanaitons, took me like 6 months to understand thiz linking errors :dancer:
