### ISSUE TITLE
[Bitfinex] Wrong takers data in stats

### ISSUE THREAD

**Issue by CooleRnax** [ctubio/Krypto-trading-bot#903]
There is a lot of fake volume in stats GUI for Bitfinex exchange.
![image](https://user-images.githubusercontent.com/980180/54958180-f4de2080-4f65-11e9-8d10-fa6969351778.png)

**Comment by ctubio** [comment]
values should be lower yea, donno why will need to look into it (hope is a bitfinex-only issue)

**Comment by ctubio** [comment]
i was reading also `tu` msgs but there are more than 1 for each trade, so data was dupe or tripe :D
