### ISSUE TITLE
Poloniex precision

### ISSUE THREAD

**Issue by nonkreon** [ctubio/Krypto-trading-bot#904]
Hi,

Can't believe haven't noticed this before but apparently this occurs on many currencies. The bot cannot identify the number of decimals in the prices. See the attached screenshots:
![image](https://user-images.githubusercontent.com/3709448/54959973-48824700-4f31-11e9-8e1e-9eea93f7935b.png)
![image](https://user-images.githubusercontent.com/3709448/54960000-66e84280-4f31-11e9-906f-53cc1150c8b1.png)
I know you don't like to update REST xchanges, but there should be an easy fix, don't you think :-(

**Comment by ctubio** [comment]
you mean that is missing (truncating) some (3) decimals at the end of the prices?

:koala: lemme see why (hope is a poloniex-only issue)

**Comment by nonkreon** [comment]
exactly, i'm kind of injured so can't write clearly, thought a picture worth thousand words and you got it:-D

**Comment by ctubio** [comment]
i think i will set all poloniex market to `8` decimals, cos i cannot find any suggestion or formula for calculate the minum price increment (or amount of decimals in price values) of different poloniex markets

**Comment by nonkreon** [comment]
I think that makes sense, apparently even btc_usd pair has 8 decimals :+1:

**Comment by ctubio** [comment]
:koala: many thanks for your help''¡

![well](https://user-images.githubusercontent.com/1634027/55282576-bfab4700-5346-11e9-86aa-17547d624317.jpg)
