### ISSUE TITLE
Corrupt Tradehistory When Optimization Enabled

### ISSUE THREAD

**Issue by xloem** [ctubio/Krypto-trading-bot#909]
I'm finding my trade history is getting corrupt under some conditions, only when I build with KARGS including the default `-O3`, but not if I bump it down to `-O1`.

I've copied my logfile into a test case and am submitting a PR with the test.

**Comment by ctubio** [comment]
im not sure what is going on there, cos i never had corrupted nothing no matter what :S

**Comment by ctubio** [comment]
feel free if you consider to share screenshots/logs in case you need help (but i know you dont need help xD)

**Comment by xloem** [comment]
ctubio, see #910 .  When I replay a certain sequence of trades, the trading engine forms a pong with a ping that results in a loss, and the loss is recorded as a positive Kdiff.  The test in a0947617af046b0cf8c0193c57bf9c98f778211a creates this scenario.  The trade that causes this appears to be the one for 141.55 USD.

**Comment by ctubio** [comment]
thanks for the info, will follow at  #911

**Comment by ctubio** [comment]
the fix is in the PR above, (:koala: if interested)
