### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by crack00r** [ctubio/Krypto-trading-bot#92]
root@j314617:~# git clone ssh://git@github.com/ctubio/Krypto-trading-bot K
Cloning into 'K'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by CarlitoGrey** [comment]
Use https instead of ssh.

**Comment by ctubio** [comment]
https://help.github.com/articles/error-permission-denied-publickey/ :dancer:
