### ISSUE TITLE
Report reason for failed trades

### ISSUE THREAD

**Issue by xloem** [ctubio/Krypto-trading-bot#920]
It would be great to be able to get the server's information on why a trade was rejected.  It would really help in debugging the bot.

In order to get this I have sometimes added some debugging hooks to the dependency libraries, but it's really incredibly awkward.  It would be great to get failure information via the API.

**Comment by xloem** [comment]
@ctubio mentioned in #918 

> P.D. im not interested into track or log Rejected orders, but if you really need it i can set this isRejected var from the gateway based on gateway msgs and print the log if bool (or combined condition) is true, if you really want it please just open a new issue with a link to this PR and i will do soOn (cos the gateways are private and i think there is the best place to detect if an order is rejected)

This would be really incredible.  I'm currently working on injecting hooks into the binary lib to get this information, which is kinda of difficult.  I'm getting a lot of rejected orders and coinbase complained to me about it, but it's difficult to tell the reason.

**Comment by ctubio** [comment]
is `--debug-secret` not helpful?

in what exchange are you missing more raw messages from the exchange while using `--debug-secret`? in coinbase? (if so i can stringify to debug the fix messages when using `--debug-secret` eaSy)

**Comment by ctubio** [comment]
:koala: feel free to comment even if the issue if closed

**Comment by xloem** [comment]
Since I'm not using coinbase for now, turns out `--debug-secret` covers it.  Thanks so much.  Users might find it easier to report problems if 'error' messages are output by default some day I suppose.

**Comment by ctubio** [comment]
you are right, with my focus to keep logs clean we miss important and very variable messages from gateways.

my plan for them is to keep them silent unless some argument is set like `--report-reject-reasons` or something similar (to make them visible but also hidden if wanted); hope for it someday'¡
