### ISSUE TITLE
Bequant : Bot is disconnected from the exchange after 24h+ of running

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#924]
Hi Carles and everyone,

I've noticed that the bot gets disconnected from the exchange after running for over 24h.
Then it stays in a "connecting to the exchange" phase without succeeding.

Maybe it would be better to stop and restart the bot automatically when this happens.
It would also be good for pingpoing/pingpong mode to save last buy and last sell before said restart!

Here are some logs :
04/09 09:56:23.238893 QE Warrrrning: Unable to calculate quote, missing 
  market data.
04/09 09:56:24.218222 GW BEQUANT Warrrrning: WS Error, reconnecting in 7
  s..

**Comment by ctubio** [comment]
i donno nothing yet, im still trying to reproduce it :S

does it happens to you everyday? or somedays it survives longer than a day?

note that a reconnect is a successfull survival, im looking for the app not reconnecting as expected (hope i understood you correctly)

**Comment by zbanga** [comment]
I think sometimes stale orders are on the market due to "missing data". This happens way more often than 24 hours? Need to manually turn off bot and turn on again to avoid the issue.

**Comment by Camille92** [comment]
Thanks for the replies guys, maybe a solution would be to have an argument to automatically kill an instance after X minutes of running and start it up again.

Manually turning off and on is not very efficient :/

**Comment by ctubio** [comment]
just saying, the whole websocket integration was replaced at 972abea428d33e4a5988db107b8a1c16be668e54

**Comment by ctubio** [comment]
let me close thiz issue cos after long runs i just got a few:
```
GW BEQUANT Warrrrning: Error or ignored response: {"error":{"code":500,"description":"","message":"Internal Server Error"},"id":504,"jsonrpc":"2.0"}.
```
but i dont see the need of restart :S it seems it survives nice after this warnings

**Comment by Camille92** [comment]
Yes I think it works now :)

Le dim. 2 juin 2019 à 21:25, Carles Tubio <notifications@github.com> a
écrit :
