### ISSUE TITLE
uWebsockets v0.15: 33% performance enhancement

### ISSUE THREAD

**Issue by xloem** [ctubio/Krypto-trading-bot#929]
Krypto-trading-bot appears to value speed highly.

I noticed that the uWebSockets library used is a major revision out of date.

At https://github.com/uNetworking/uWebSockets/blob/v0.14/README.md, uWebsockets advertises over 33% performance gain upgrading to v0.15 .

**Comment by ctubio** [comment]
yea starts to be the time by now

:koala: i was waiting a few minor versions cos he did some fixes after v0.15

**Comment by ctubio** [comment]
:koala: still not usable (https://github.com/uNetworking/uWebSockets/issues/872) but soOn'

**Comment by ctubio** [comment]
well fuck it, lets use https://github.com/uNetworking/uSockets/archive/f1cae03ecdc0539f4155b964726065288b15c7a4.tar.gz xD

**Comment by ctubio** [comment]
well xD uWS dropped client support (so we cannot connect to exchanges with it)

see https://github.com/uNetworking/uWebSockets/search?q=client&type=Issues

what we can do with the server support is server the UI, a useless thing if you ask me xD

**Comment by xloem** [comment]
Dang, I'm sorry.  Thank you so much for the time spent figuring that out.

**Comment by ctubio** [comment]
sure, ima contact coinbase to see if they wanna support ws client in uWS :D

thanks to you for your time'¡

**Comment by ctubio** [comment]
i would love to use https://github.com/uNetworking/uSockets/blob/master/src/internal/networking/bsd.h directly; i may consider soOn :P

**Comment by ctubio** [comment]
ima go with curl send/recv for the gateway apis ;D, theres nothing more neat and is pretty lovely fast too

**Comment by ctubio** [comment]
curl implementation is almost done :D just testing if/how it crashes on log runs :D
