### ISSUE TITLE
Need help with settings, bot not making trades

### ISSUE THREAD

**Issue by untamedone** [ctubio/Krypto-trading-bot#93]
I got everything installed and the api connected. It reads market data but never submits orders. I tried messing with some of the settings based on the what I could find in the manual but I still have no idea what most of the settings do.

**Comment by ctubio** [comment]
what exchange? maybe is something interesting in the logs?

**Comment by untamedone** [comment]
Coinbase ETH/BTC (Box is green)

**Comment by ctubio** [comment]
ok, that means is connected

**Comment by untamedone** [comment]
Ok, I think I figured out what was going on. I had all the currency on one side of the market, once I manually split it 50/50 the bot started submitting orders.
