### ISSUE TITLE
CoinBase Getting Orders Rejected Due To Stale Orderbook

### ISSUE THREAD

**Issue by xloem** [ctubio/Krypto-trading-bot#934]
I'm getting a lot of orders rejected with the error "post only".  I can see this only because I'm using my log hack from #920; it appears on the interface just as an empty box, with the order refusing to place.

I visited the official Coinbase interface and it looks like the orderbook the bot has is really out of date.  The bot still thinks the price is 167.72, but it has risen to 168.01.  The bot is now repeatedly trying to place sells at 167.79 and every single one is getting rejected with "post only".

FIX actually got disconnected and reconnected, but the market data stayed stale, with the same flurry of rejections.

Restarting the bot resolves the issue.

Is there anything that would help here?

EDIT: this started getting really noticeable when I bumped up to 5 bots on the same api key; maybe that is related

EDIT: it doesn't seem related to # of bots or api keys; stil getting this issue when running only 1 bot

**Comment by boogey100** [comment]
I'm 99% sure this is an issue with CB. It happens all the time when the exchange gets busy. There are a few issues reporting this on the nodejs lib. e.g. https://github.com/coinbase/coinbase-pro-node/issues/280

**Comment by xloem** [comment]
Given the bot syncs properly when it boots up, it seems there must be some way to get a new order table in order to get up to speed, without having to reboot the bot, but unfortunately the code is all inside the private lib.

It sounds like the easiest workaround is to migrate to a different exchange, thanks =)

**Comment by xloem** [comment]
I was doing something similar based on rejected orders, but ran into a race condition in the FIX code that often prevented shutdown from completing and ended up just calling out with `system()` to force the process to close.  It unfortunately creates a lot of disk i/o to frequently reboot the process.

It turns out Poloniex has lower fees, though, and I already use it for other things, so I'm migrating off of coinbase now, myself.

**Comment by ctubio** [comment]
im sorry im not able to reproduce this issue; coinbase is my main exchange and never saw this (i had experiencied heavy data delays only on websocket poloniex [the rest api was all fine at all times])

@boogey100 nice snippet'¡ :D

@xloem allow me to close thiz issue cos i have no idea what the fix can be (since is OK for me :()
