### ISSUE TITLE
Bequant/HitBTC FIX API

### ISSUE THREAD

**Issue by flfsbr** [ctubio/Krypto-trading-bot#936]
Hi Carles, is it possible to integrate the FIX API from Bequant and HitBTC with K?

https://hitbtc.com/fix-spec

**Comment by ctubio** [comment]
but but is that public? they dont seems to share the OpenVPN endpoint

**Comment by flfsbr** [comment]
It is made available to anyone who fills out the form.
https://hitbtc.com/fix

**Comment by ctubio** [comment]
iSee, many thanks for the links; then should be possible yea

**Comment by ctubio** [comment]
lemme fill the form :dancer:

:koala: will post here if i get access or not; just to let you know

thanks again'¡

**Comment by anthonyxvg** [comment]
https://bequant.io/fix

Someone from the bequant staff offered me a 1 month free trial of their FIX data which normally costs 2000$ monthly.

**Comment by ctubio** [comment]
i didnt got an answer yet but if thats gonna be the answer better if they dont allow me to reply xD

**Comment by anthonyxvg** [comment]
It would be great if Bequant FIX Api support gets integrated. Since 2 days there is co-location and cross connections available but it's only working via FIX.

**Comment by ctubio** [comment]
im not getting any answer; will comment or reopen thiz issue if i ever get an answer with some fix credentials
