### ISSUE TITLE
Fcoin order issue

### ISSUE THREAD

**Issue by boogey100** [ctubio/Krypto-trading-bot#940]
05/25 10:42:51.353060 DEBUG QE [!] 6:4 {"ask":{"price":8017.5,"size":0.02},"bid":{"price":0.0}}.
05/25 10:42:52.431607 GW FCOIN Notice: limit amount decimal: 4.

**Comment by ctubio** [comment]
im a bit lazy against fcoin because i dont make use of it personally

**Comment by boogey100** [comment]
Is there any way someone could help maintain these other exchanges?  I have tried a few that have issues that make them unusable (fcoin, poloniex and kraken)

**Comment by ctubio** [comment]
im currently rewriting all exchange integrations with curl; if goes nice i will be happily forced to rereview carefully fcoin as well as all others, so hope for this issue to be fixed then'¡

**Comment by ctubio** [comment]
sorry what currency pair had this error on fcoin?

thanks''
