### ISSUE TITLE
Incredibly high CPU utilizations driving >1000ms latencies

### ISSUE THREAD

**Issue by halessi** [ctubio/Krypto-trading-bot#942]
Hey,

I think the latest upgrade has worsened my CPU utilization problems -- this morning K has been absolutely maxing out two separate cores, leading to latencies of up to 1500ms (typically 
 ~20ms). I'm on BTC/USD, with market levels set to 321|321. I've tried with database=:memory: and without. 

The behavior is sporadic: it will drop to 100% then back up to 200% (full two cores). I can tell in the UI when it's maxing out, as this is when the latencies spike (computational backlog somehow?).  

<img width="793" alt="Screen Shot 2019-05-31 at 1 24 21 PM" src="https://user-images.githubusercontent.com/34874946/58729761-807d8e80-83a7-11e9-82f8-5e267df3ab06.png">

How can I downgrade to the previous commit? Or do you have any further ideas on troubleshooting? I can swap to ETH/USD or other pairs and see if the problem persists.

Thanks.

**Comment by ctubio** [comment]
sorry what exchange are you using?

:koala: thanks for the report'''

**Comment by halessi** [comment]
Hi, using coinbase.

**Comment by ctubio** [comment]
umf, for me was all nice with coinbase; let me try to debug a bit before consider a rollback

any other info you may have will be very welcome¡' (to allow me to reproduce your very same situation)

**Comment by halessi** [comment]
My K.sh file has pretty much everything standard (api key, secret, passphrase, exchange) with OPTIONAL_ARGUMENTS="                                                                                                                                                                   
    --database=:memory:                                                                                                                                                            
    --maker-fee=0.15                                                                                                                                                               
     --taker-fee=0.25"    

Thanks for the link, I'll keep toying around and see if I can troubleshoot anything before reverting.

**Comment by ctubio** [comment]
i can notice some high cpu too; let me try a fix or otherwise i will rollback the release meanwhile fixing locally

many thanks for the quick report''' and sorry for the trouble''

**Comment by halessi** [comment]
no worries! i'm happy it wasn't just me. thanks for your quick working to fix it!!

**Comment by ctubio** [comment]
![e67977a005f638980128ef069f47ca07_gif-02-manos-ala-obra-gif_450-360](https://user-images.githubusercontent.com/1634027/58740977-a2f9c100-8414-11e9-82c5-f15e08643747.gif)

is suposed now that the cpu should be around 2% with max spikes of 6%; but feel free to comment in case you still have some offensive values.

meanwhile allow me to close the issue and turn the bug of today as a improvement for tomorrow; on next days i will try to go a bit lower without increasing latency; as is now latency is niiiice :D but cpu is still a liiiil high (1~3%) compared to previous commits

thanks for your (cpu) time''' :dancer:

**Comment by halessi** [comment]
this worked! my cpu utilization is lower than it has ever been. thank you.
