### ISSUE TITLE
EWMA apModes TBP upper and lower limits 

### ISSUE THREAD

**Issue by nonkreon** [ctubio/Krypto-trading-bot#944]
if I'm not misunderstanding pDivMin incorrectly, it's not respected, maybe in some configs. like if I have pDivMin=20%, if apr calculates TBP=0, shouldn't 20% of total value still be in asset? most of the time I have 0 asset and all base currency if TBP=0, or I may also have all asset and 0 currency in the opposite scenario. shouldn't pDivMin prevent this?
I'm using Depth quoting, AK-47, TradesSize sops, LMS and EWMAwidth. does any of them make K irrespectable of pDivMin?

**Comment by ctubio** [comment]
is quite simple the pDiv function:
https://github.com/ctubio/Krypto-trading-bot/blob/352db3e1d3c51c82f771b82790e8dbba18d89c40/src/lib/Krypto.ninja-user.h#L1696-L1711

on last lines is where pDivMin is used; maybe reading them helps you understand how pDivMin is used?

pDivMin is not used anywhere else, so you can be sure you are looking at 100% of the related codes

**Comment by nonkreon** [comment]
hmm I see what you're saying Carles, thanks for pointing out :smile: 

then let me revert the question to the other way around, any way to instruct the bot to never let the base asset fall below and go above a certain percentage (say symmetrically 20-80 for simplicity) in nonmanual apMode?

**Comment by ctubio** [comment]
is suposed that pDiv and TBP avoids the base currency to go over or below certain values, for example, having TBP 50% and pDiv 5%, the base currency should be always between 45% and 55%; in the same way, a TBP of 0% and pDiv of 5% will just limit between 0% and 5%, (cos cannot go negative)

so is suposed that configurable upper and lower limits are already supported

when the base currency goes below or over the limit, the `TBP Held` msg is suposed to be displayed in the UI

i believe a possible way for the bot to ignore the limit is in the case of too fast concurrent trades, where the secondary comming trades where placed before knowing about the first coming trades (this only have the solution of delaying orders as much seconds as the current latency with the exchange :S a solution not implemented currently).

is also possible that i didnt understood correctly your question; maybe on irc works better? :D

**Comment by nonkreon** [comment]
morning Carles :sun_with_face: , isn't it midnight there?

everything you say makes sense and I see that having 0 base is mathematically correct in our current TBP and pDiv definitions. then let's say the question is closed and convert this thread to an improvement suggestion of adding TBP upper and lower limits to accompany EWMA APs :rocket: 

if we set APMode to manual we have that control but EWMA APModes scale all the way from 0-100, losing us that ability.

**Comment by ctubio** [comment]
yea is midnight :D

oh i see what you mean; that requires adding more settings so let me prospone it (since getting hands dirty with the settings is a pending task for the near future)

**Comment by ctubio** [comment]
:koala: your time is much appreciated nonkreon'¡ thanks for selffixing it'''
