### ISSUE TITLE
GLIBC Version mismatch

### ISSUE THREAD

**Issue by grhangelone** [ctubio/Krypto-trading-bot#947]
I just apt-get upgraded my ubuntu and bot.
Now I have another glibc mismatch

K-trading-bot: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by K-trading-bot)

I'm on Ubuntu 18.04.2 LTS
Linux server2 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

The newest gllibc I can get is 2.27

**Comment by grhangelone** [comment]
I just downgraded back to 5.1
But I would love to use the newest version.

My Ubuntu is just 4 months old and the state of the art LTS release.
I should be able to use it Carles :)

**Comment by ctubio** [comment]
morning'''
maybe `make dist K` helps?

**Comment by grhangelone** [comment]
Never tried it, but makes sense.
Sadly the build fails.


> Building hello-world..
> make  src KSRC=hello-world
> make[1]: Entering directory '/home/angelone/ramdisk/Krypto-trading-bot'
> Building hello-world src x86_64-linux-gnu..
> x86_64-linux-gnu-g++ (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
> Copyright (C) 2017 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> sed: no input files
> Makefile:121: recipe for target 'src' failed
> make[1]: [src] Error 123 (ignored)
> make Linux CHOST=x86_64-linux-gnu
> make[2]: Entering directory '/home/angelone/ramdisk/Krypto-trading-bot'
> make[3]: Entering directory '/home/angelone/ramdisk/Krypto-trading-bot'
> x86_64-linux-gnu-g++ -DNDEBUG -o build-linux-x86_64/local/bin/K-hello-world \
>   -DHAVE_STD_UNIQUE_PTR -DUWS_THREADSAFE         \
>   -static-libstdc++ -static-libgcc -rdynamic     \
>   src/bin/hello-world/hello-world.cxx -std=c++17 -O3 -pthread -DK_0_GIT='"c164a36be37e3bf718ff22e33af33ab2ae7694d2"' -DK_STAMP='"2019-06-12 14:57:55"' -DK_0_DAY='"v0.5.2+4"' -DK_BUILD='"linux-x86_64"'      -DK_SOURCE='"K-hello-world"' -Ibuild-linux-x86_64/local/include         -I/home/angelone/ramdisk/Krypto-trading-bot/src/lib build-linux-x86_64/local/include/uWS/*.cpp build-linux-x86_64/local/lib/K-linux-x86_64.1.a build-linux-x86_64/local/lib/libsqlite3.a  build-linux-x86_64/local/lib/libncurses.a build-linux-x86_64/local/lib/libz.a        build-linux-x86_64/local/lib/libcurl.a build-linux-x86_64/local/lib/libssl.a      build-linux-x86_64/local/lib/libcrypto.a build-linux-x86_64/local/lib/libcares.a -ldl
> x86_64-linux-gnu-g++: error: build-linux-x86_64/local/lib/K-linux-x86_64.1.a: No such file or directory
> Makefile:140: recipe for target 'Linux' failed
> make[3]: *** [Linux] Error 1
> make[3]: Leaving directory '/home/angelone/ramdisk/Krypto-trading-bot'
> Makefile:138: recipe for target 'Linux' failed
> make[2]: *** [Linux] Error 2
> make[2]: Leaving directory '/home/angelone/ramdisk/Krypto-trading-bot'
> Makefile:121: recipe for target 'src' failed
> make[1]: *** [src] Error 2
> make[1]: Leaving directory '/home/angelone/ramdisk/Krypto-trading-bot'
> Makefile:98: recipe for target 'hello-world' failed
> make: *** [hello-world] Error 2

**Comment by grhangelone** [comment]
make dist works flawlessly
building the npm stuff, too
make trading-bot fails with above error

> sed: no input files
> Makefile:121: recipe for target 'src' failed
> make[1]: [src] Error 123 (ignored)

and 

> x86_64-linux-gnu-g++: error: build-linux-x86_64/local/lib/K-linux-x86_64.1.a: No such file or directory

**Comment by grhangelone** [comment]
nvm. i'm using the old version
you should really consider using a stable linux for your development
this way the rest of the world can use your binaries

**Comment by ctubio** [comment]
thanks for the suggestion; will try to downgrade back to 2.25 (and keep without upgrade) soOn''

**Comment by grhangelone** [comment]
No :)
But using Ubuntu LTS might help. 
That's one of the Most important distros for servers and they are in 2.27. Just like 90% of the other ones.
Buster ist officially "Testing" and therefore mit that widespread :)
But I just got the compiling done.
I tried to compile the gut repo, which doesn't work. Compiling the zip release worked

**Comment by ctubio** [comment]
yea because the zip contains the lib file, but the git repo just the public sources

i really dont like ubuntu, and i really love testing stuff; so im confused xD anyway happy to know that you could recompile locally for now (hope for a fix soOn').

**Comment by ctubio** [comment]
so lets kill:
```
0000000000000000  w   DF *UND*  0000000000000000  GLIBC_2.25  getentropy
0000000000000000      DF *UND*  0000000000000000  GLIBC_2.28  fcntl64
```
and cross fingers to be back at 2.24 or higher; will try laterzZzzzz''

**Comment by ctubio** [comment]
is suposed that you will not need to recompile anymore even if using an old ubuntu (that they may call "new release" even if they are effectively providing old libs :dancer: see https://sourceware.org/glibc/wiki/Glibc%20Timeline to understand how much "new" is that "new release" of ubuntu [more like 3 years out of date i would say])
