### ISSUE TITLE
K crashed: exit code 141 - actual release

### ISSUE THREAD

**Issue by zmbbmz** [ctubio/Krypto-trading-bot#950]
**the bots on hitbtc (like 5 on one machine) are crashing after several minutes with this code:**

_06/23 13:07:26.073513 PG TBP: 0% = 0 DGTX, pDiv: 5% = 252 DGTX.
06/23 13:07:28.333421 PG TBP: 0% = 0 DGTX, pDiv: 4% = 251 DGTX.
06/23 13:14:56.815849 PG TBP: 0% = 0 DGTX, pDiv: 4% = 238 DGTX.
K crashed with exit code 141.. Respawning..
K-trading-bot linux-x86_64 2019-06-22 04:34:14.
v0.5.3+7 (0day)._

**:~# cat /etc/issue**
Debian GNU/Linux 10 \n \l

**runtime examples:**

SMART/USDT
06/23 13:00:49.522503 GW HITBTC cached handshake
06/23 13:17:53.538282 PG TBP: 0% = 0 SMART, pDiv: 4% = 1125 SMART.
K crashed with exit code 141.. Respawning..

MESSE/USDT
06/23 12:50:19.903612 GW HITBTC cached handshake:
06/23 13:40:32.249520 PG TBP: 0% = 0 MESSE, pDiv: 4% = 834 MESSE.
K crashed with exit code 141.. Respawning..

ICX/USDT
06/23 12:53:15.901331 GW HITBTC cached handshake:
06/23 13:40:58.149079 PG TBP: 0% = 0.0 ICX, pDiv: 5% = 51.5 ICX.
K crashed with exit code 141.. Respawning..

**any hints / solutions for this?**

**Comment by ctubio** [comment]
do you get any error msg? try running with `--naked` to see more logs

**Comment by zmbbmz** [comment]
log with --naked:

xxx:/kbot# ./test.sh --naked
K-trading-bot linux-x86_64 2019-06-22 04:34:14.
v0.5.3+7 (0day).
06/23 14:12:16.540073 CF Outbound IP address is 62.224.179.183.
06/23 14:12:16.541780 GW HITBTC cached handshake:
- gateway: https://api.hitbtc.com/api/2
- gateway: wss://api.hitbtc.com/api/2/ws
- autoBot: no
- symbols: DGTX/BTC (1/0.000000001)
- minSize: 1 DGTX
- makeFee: 0.10%
- takeFee: 0.20%.
06/23 14:12:16.545229 DB loaded OK from /var/lib/K/db/K-trading-bot.HITBTC.DGTX.BTC.db.
06/23 14:12:16.551268 DB loaded last Quoting Parameters OK.
06/23 14:12:16.552660 DB loaded last EWMA Values OK.
06/23 14:12:16.553699 DB loaded 172 historical Fair Values.
06/23 14:12:16.554555 DB loaded TBP = 0.000000 DGTX.
06/23 14:12:16.555372 DB loaded 35 historical Trades.
06/23 14:12:16.557040 DB loaded 462 historical Profits.
06/23 14:12:16.557756 UI Warrrrning: Connected web clients will enjoy unsecure SSL encryption..
(because the private key is visible in the source!). See --help argument to setup your own SSL.
06/23 14:12:16.558334 UI ready at https://62.224.179.183:3999.
06/23 14:12:17.159446 GW HITBTC WS Streaming book levels and orders.
06/23 14:12:38.650680 UI authorization attempt from 192.168.111.187.
06/23 14:12:42.100558 UI authorization success from 192.168.111.187.
06/23 14:12:43.686079 UI 1 client connected, last connection was from 192.168.111.187.
06/23 14:12:48.054712 GW HITBTC Quoting state changed to CONNECTED.
06/23 14:16:26.002566 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.004309 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.005688 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.006883 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.008055 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.009299 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.010416 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.011621 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.012901 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.014026 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.015070 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.015777 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.016353 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.016719 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.017086 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.017449 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.031516 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.033013 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.033581 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.034086 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.034741 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.035241 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.047403 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.047703 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005389 BTC (value 0.000053890 BTC).
06/23 14:16:26.047893 GW HITBTC PING TRADE BUY  1 DGTX at price 0.000005389 BTC (value 0.000005389 BTC).
06/23 14:16:27.009205 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005387 BTC (value 0.000053870 BTC).
06/23 14:16:27.009820 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005387 BTC (value 0.000053870 BTC).
06/23 14:16:27.010490 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005387 BTC (value 0.000053870 BTC).
06/23 14:16:27.010935 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005387 BTC (value 0.000053870 BTC).
06/23 14:16:27.011417 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005387 BTC (value 0.000053870 BTC).
06/23 14:16:27.012204 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005387 BTC (value 0.000053870 BTC).
06/23 14:16:27.012764 GW HITBTC PING TRADE BUY  10 DGTX at price 0.000005387 BTC (value 0.000053870 BTC).
06/23 14:26:59.984375 GW HITBTC PONG TRADE SELL 311 DGTX at price 0.000005419 BTC (value 0.001685309 BTC).
06/23 14:27:31.810794 GW HITBTC PONG TRADE BUY  233 DGTX at price 0.000005387 BTC (value 0.001255171 BTC).
06/23 14:27:32.441670 GW HITBTC PONG TRADE BUY  9 DGTX at price 0.000005387 BTC (value 0.000048483 BTC).
06/23 14:27:32.548171 GW HITBTC PONG TRADE BUY  1 DGTX at price 0.000005386 BTC (value 0.000005386 BTC).
06/23 14:27:32.548538 GW HITBTC PONG TRADE BUY  2 DGTX at price 0.000005386 BTC (value 0.000010772 BTC).
06/23 14:27:32.548765 GW HITBTC PONG TRADE BUY  4 DGTX at price 0.000005386 BTC (value 0.000021544 BTC).
06/23 14:27:32.549211 GW HITBTC PONG TRADE BUY  8 DGTX at price 0.000005386 BTC (value 0.000043088 BTC).
06/23 14:27:32.560420 GW HITBTC PONG TRADE BUY  16 DGTX at price 0.000005386 BTC (value 0.000086176 BTC).
06/23 14:27:32.561341 GW HITBTC PONG TRADE BUY  32 DGTX at price 0.000005386 BTC (value 0.000172352 BTC).
06/23 14:27:32.624917 GW HITBTC PONG TRADE BUY  1 DGTX at price 0.000005386 BTC (value 0.000005386 BTC).
06/23 14:27:32.625618 GW HITBTC PONG TRADE BUY  2 DGTX at price 0.000005386 BTC (value 0.000010772 BTC).
06/23 14:27:32.626576 GW HITBTC PONG TRADE BUY  4 DGTX at price 0.000005386 BTC (value 0.000021544 BTC).
06/23 14:27:32.627228 GW HITBTC PONG TRADE BUY  8 DGTX at price 0.000005386 BTC (value 0.000043088 BTC).
06/23 14:33:56.831191 GW HITBTC PONG TRADE SELL 72 DGTX at price 0.000005431 BTC (value 0.000391032 BTC).
06/23 14:33:57.144928 GW HITBTC PONG TRADE SELL 1 DGTX at price 0.000005431 BTC (value 0.000005431 BTC).
06/23 14:34:00.028339 GW HITBTC PONG TRADE SELL 10 DGTX at price 0.000005446 BTC (value 0.000054460 BTC).
06/23 14:36:31.311786 GW HITBTC PONG TRADE SELL 123 DGTX at price 0.000005446 BTC (value 0.000669858 BTC).
06/23 14:36:31.341083 GW HITBTC PONG TRADE SELL 114 DGTX at price 0.000005446 BTC (value 0.000620844 BTC).
K crashed with exit code 141.. Respawning..
K-trading-bot linux-x86_64 2019-06-22 04:34:14.
v0.5.3+7 (0day).
06/23 15:47:57.488525 CF Outbound IP address is 62.224.179.183.
06/23 15:47:57.488699 GW HITBTC cached handshake:
- gateway: https://api.hitbtc.com/api/2
- gateway: wss://api.hitbtc.com/api/2/ws
- autoBot: no
- symbols: DGTX/BTC (1/0.000000001)
- minSize: 1 DGTX
- makeFee: 0.10%
- takeFee: 0.20%.

**Comment by zmbbmz** [comment]
hm, its still there :(

```
06/23 18:04:24.560438 GW HITBTC Quoting state changed to CONNECTED.
K crashed with exit code 141.. Respawning..
K-trading-bot linux-x86_64 2019-06-23 15:07:12.
v0.5.3+8 (0day).
```

**Comment by ctubio** [comment]
many thanks for your help on irc'¡

**Comment by zmbbmz** [comment]
works fine! thx!
