### ISSUE TITLE
Poloniex nonce issue, TBP and width empty

### ISSUE THREAD

**Issue by nonkreon** [ctubio/Krypto-trading-bot#952]
Hai Carles and all :sun_with_face: 
I've realized that my polo bot (single bot, not bots) didn't make any trades since June 6. I used to run multibot party, but now I run a single bot with a key that is not used elsewhere, so I'm sure it's not a multibot issue. The bot can read my wallet balances and the orderbook (albeit VERY infrequent, interestingly), but I'm constantly getting `GW POLONIEX Nonce must be greater than 1561387909662. You provided 1561387909662...`

EDIT: Sometimes the order state says MissingData for both bid and ask, other times I may get something like this: 
![image](https://user-images.githubusercontent.com/3709448/60285033-0aebdc00-98db-11e9-85e5-8cbaa15cc34c.png)

On the terminal, I see that balances are read and quotes are calculated, but at the end of every quote calculation I get a `DEBUG POLONIEX <<< [].`, which I don't remember getting before.

Poloniex API webpage shows me that the last time the API was accessed is the current time, if I close the bot last accessed stays constant at the time I closed.

**Comment by ctubio** [comment]
:koala: i think i will remove poloniex instead of fix it; unless somebody really things that is worth to fix it

**Comment by xloem** [comment]
Please don’t remove.  Is there another exchange for currencies like BSV and NEM?  I’m running an old version on poloniex and would like to upgrade some day.

**Comment by ctubio** [comment]
well in that case will just close the issue cos i belive poloniex and kraken were lately fixed

**Comment by nonkreon** [comment]
>  i think i will remove poloniex instead of fix it; unless somebody really things that is worth to fix it

I'm thinking of jumping in but I'm not getting anything useful to debug other than [] and nonce error, do you have like a guideline Carles that I can follow?

**Comment by ctubio** [comment]
nope, you think is broken? if so i would need to debug it and im a bit lazy cos im not a daily user of poloniex (note that i just got happy after seen a nice handshake yesterday, so maybe is still super broken the trading at poloniex :S can you confirm?)

**Comment by nonkreon** [comment]
> nope just --debug argument, you think is broken? if so i would need to debug it and im a bit lazy cos im not a daily user of poloniex (note that i just got happy after seen a nice handshake yesterday, so maybe is still super broken the trading at poloniex :S can you confirm?)
> 
>  poloniex handshake was fixed at [7790e2d](https://github.com/ctubio/Krypto-trading-bot/commit/7790e2d62f929cc327a7de383853c6ecd8c4922d)

yayy fixed you right :fireworks:
