### ISSUE TITLE
Remote/telnet interface?

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#953]
There was some discussion a while ago (see #598 for example) about an interface to control K remotely (i.e. when running naked) so that one can at least connect/disconnect K with an easy telnet command (or similar). 

What about that, is this still planned?

**Comment by xloem** [comment]
Can use web socket for quick hacks or prototypes - https://github.com/ctubio/Krypto-trading-bot/issues/811#issuecomment-485596189

**Comment by Pat71** [comment]
Doesn't work  (commented it in #811  )

**Comment by ctubio** [comment]
`kill -9 K-trading-bot` doesn helps to restart?

**Comment by Pat71** [comment]
Yes it does, but what does that help in connecting via wscat? 

I'd like to read out the params (or set them) from the cmdline, not from the gui... so the wscat way (#811) would be very nice...

**Comment by ctubio** [comment]
i had added some comments at https://github.com/ctubio/Krypto-trading-bot/issues/811#issuecomment-505400614  about wscat, hope ot helps'''

**Comment by ctubio** [comment]
closing this cos as a "remote/telnet interface" nothing needs to be done because the websocket is already public

**Comment by Pat71** [comment]
Hm, ok now I can read/set the params, but I can't check or set the state (connected/disconnected) via wscat, can I?

**Comment by xloem** [comment]
@Pat71 you can change the state with `-d{"agree":0}` and `-d{"agree":1}`.  As I said in the edit of the linked comment, you can quickly see the websocket messages of all the buttons by reviewing the messages sent in the gui.
1. navigate to gui
2. open web developer tools (ctrl+shift+I on chrome)
3. hit 'network' pane of developer tools
4. reload gui to capture network messages
5. once site loads, a network stream will be loaded with type = websocket, status = 101 (and likely name = 127.0.0.1).  click this item in the list in the developer tools.
6. details on the item will load in a new pane to the right.  click the 'messages' subpane.
7. hit a button on the interface and you can see the message that is sent

**Comment by Pat71** [comment]
Great, thanks!

**Comment by ctubio** [comment]
:bulb: i usualy use: `wscat -c ws://address:port --auth user:pass`

**Comment by ctubio** [comment]
for example, to read quoting parametrs use:  `wscat -c ws://address:port --auth user:pass -x "=f"`
