### ISSUE TITLE
Segmentation fault (Three-Headed Monkey found):

### ISSUE THREAD

**Issue by Utfard** [ctubio/Krypto-trading-bot#956]
- exchange: BITFINEX_MARGIN
- currency: BTC .. USD
- binbuild: K-trading-bot linux-x86_64
- lastbeat: 15.751104
- tracelog: 
  7: K-trading-bot(_start+0x2a) [0x55da758af90a]
  6: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fadf8e88b97]
  5: K-trading-bot(main+0x3c7) [0x55da758ae827]
  4: K-trading-bot(_ZNK3₿9WebServer8Frontend6ioHttpMUlvE_clEv+0x1f) [0x55da758cdaaf]
  3: K-trading-bot(_ZN3₿9WebServer8Frontend2ioEv+0x99) [0x55da758c7009]
  2: K-trading-bot(SSL_get_error+0x65) [0x55da75a9c2c5]
  1: /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fadf8ea5f20]
  0: K-trading-bot(_ZN3₿6Ending3wtfEi+0x419) [0x55da7590da29]

**Comment by ctubio** [comment]
thanks for the report, hope for it to be fixed after next commit
