### ISSUE TITLE
Bitfinex WS Error {"code":10100,"event":"error","msg":"auth: invalid"}.

### ISSUE THREAD

**Issue by Utfard** [ctubio/Krypto-trading-bot#957]
Not able to authenticate with WS.
Generated new pairs, no success.
The wallet ammount is read ok, just the WS auth has issues. As a result, in the web page I have the DISCONNECTED staus .

**Comment by Utfard** [comment]
The same API Key pair is working fine under K-0.4.13.46-linux-x86_64

**Comment by ctubio** [comment]
:koala: no auth means the apikey or the secret are wrong :S double check if there are extra characters or extra spaces in your config file

**Comment by Utfard** [comment]
Unfortunately there’s no mistake in the api key/secret, triple checked. Would you be able to run a quick check on Bitfinex ? My key had full permissions. I generated couple of them, no success.

**Comment by ctubio** [comment]
umf iSee, not sure since when but i must had broke bitfinex handshake, will fix on next commit

many thanks for insist on this'''

**Comment by ctubio** [comment]
:koala: thanks again for your time''' and sorry for the trouble

**Comment by Utfard** [comment]
Thank you for your quick reply, highly appreciated !
Cheers,

**Comment by Utfard** [comment]
There are still some issues here . Apparently the ws gets connected now but in the web interface the status is "Disconnected".


K-trading-bot linux-x86_64 2019-07-05 01:36:57.
v0.5.3+32 (0day).
07/05 08:42:43.505252 CF Outbound IP address is 
07/05 08:42:44.174203 GW BITFINEX cached handshake:
- gateway: https://api.bitfinex.com/v1
- gateway: wss://api.bitfinex.com/ws/2
- autoBot: no
- symbols: BTC/USD (0.00000001/1)
- minSize: 0.00040000 BTC
- makeFee: 0.00% (please use --maker-fee argument!)
- takeFee: 0.00% (please use --taker-fee argument!).
07/05 08:42:44.179044 DB loaded OK from /var/lib/K/db/K-trading-bot.BITFINEX.BTC.USD.db.
07/05 08:42:44.188751 DB Warrrrning: using default values for Quoting Parameters.
07/05 08:42:44.188991 DB Warrrrning: consider to warm up some EWMA Values.
07/05 08:42:44.189272 DB loaded 78 historical Fair Values.
07/05 08:42:44.189484 DB loaded TBP = 0.000000 BTC.
07/05 08:42:44.190224 UI Warrrrning: Connected web clients will enjoy unsecure SSL encryption..
(because the private key is visible in the source!). See --help argument to setup your own SSL.
07/05 08:42:44.190289 UI ready at https://:3000.
07/05 08:42:45.077802 GW BITFINEX WS Info {"event":"info","platform":{"status":1},"serverId":"53fa36bf-fb5a-4f20-ad9a-2fe0ef8bca81","version":2}.
07/05 08:42:45.127616 GW BITFINEX WS Streaming wallet and orders OK 0:"auth".
07/05 08:42:45.128820 GW BITFINEX WS Streaming channel 8:trades.
07/05 08:42:46.483635 GW BITFINEX WS Streaming channel 30:book.
07/05 08:42:52.443055 UI authorization success from

**Comment by ctubio** [comment]
i think the problem now is with the wallet data; at least in my bitfinex bot i dont see the amounts of my funds on each currency in the pair.

hope you are having the same issue cos the wallet data is what will try to fix next;

please let me know if you think that your wallet data is OK but your issue is somewhere else; thanks'''''

**Comment by Utfard** [comment]
Actually I can not see the wallet data or anything else, the browser shows only "Disconnected" message as I would not be authenticated. Although, acording to the logs it seems to be authenticated.

07/05 08:42:45.077802 GW BITFINEX WS Info {"event":"info","platform":{"status":1},"serverId":"53fa36bf-fb5a-4f20-ad9a-2fe0ef8bca81","version":2}.
07/05 08:42:45.127616 GW BITFINEX WS Streaming wallet and orders OK 0:"auth".
