### ISSUE TITLE
Feature Request: Fcoin Margin Support? Leverage + Maker Rebates

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#960]
Been testing some different settings and markets, finally got my settings dialed in and am looking to turn up the leverage.   Looks like Fcoin is the way to go, but it doesn't look like there's a way to trade fcoin margin the same as with bitfinex. 

Could this support be added?

**Comment by ctubio** [comment]
im not curently interested into support FCoin but maaaybe someday

**Comment by asfbhero** [comment]
Sigh, I suppose I will just have to make money more slowly then lol.
Appreciate your great work!

**Comment by ctubio** [comment]
![maxresdefault2](https://user-images.githubusercontent.com/1634027/61190552-50abf100-a69e-11e9-914a-6abdc5f425fa.jpg)

**Comment by ctubio** [comment]
:bulb: would be nice to fix first https://github.com/ctubio/Krypto-trading-bot/issues/856

**Comment by nonkreon** [comment]
i think we can close this since fcoin rekt

**Comment by ctubio** [comment]
xDD iSee, thanks for the note'¡
