### ISSUE TITLE
Can See Quoting Data With --Debug, nothing on Web UI

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#962]
Thanks for the quick fix before, got another issue now.

On XBT/USD I have nothing showing in quotes, but I see trades happening, but it is showing that pongs happened even when they didn't. 

As for EOS/U19, I see the quotes streaming in when I use the --debug switch, but nothing in the ui at all, turning it on does nothing.

![image](https://user-images.githubusercontent.com/6736484/61596947-d74d5a80-abd7-11e9-80b5-2851115af6a8.png)

**Comment by ctubio** [comment]
refreshing the page helps?

this is currently expected if the UI is loaded before the server have data (on server re/start)

if thi s is the case, is planned to be fixed someday soOn with low priority cos is only a UI issue

**Comment by asfbhero** [comment]
Refreshing doesn't help.  I don't think it's anything globally with the new changes since I can connect to my other exchanges just fine.  What is really weird is that the issue is different with EOS, the pair i'm actually trying to trade, that shows nothing and doesn't create orders at all or even show the balance as it does with the XBT pair.

![image](https://user-images.githubusercontent.com/6736484/61597763-2dbf9680-abe2-11e9-9193-f3f4ac7bf18b.png)

**Comment by ctubio** [comment]
thanks for the info, lemme see whats going on at EOS/U19

**Comment by ctubio** [comment]
umf, there was a possible division by 0 at: https://github.com/ctubio/Krypto-trading-bot/blob/060c02993eaada1f3c239dfe10f80db852efd280/src/lib/Krypto.ninja-user.h#L1057

many thanks for report it'¡

:koala: btw the other issue i was talking about was also fixed, so market data is expected to be visible always no matter what
