### ISSUE TITLE
So Close!! Says Disconnected and Not Reading Account Balance

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#963]
Tried placing trades manually on the exchange to wake it up somehow, that didn't work.
Tried turning off leverage and that didn't work either.
Your previous fix completely fixed the other issues though.
Still EOS/U19, perhaps something about the U19 is confusing it, just guessing though.

![image](https://user-images.githubusercontent.com/6736484/61600313-04146880-abfe-11e9-839a-c26db406388d.png)

**Comment by ctubio** [comment]
Disconnect status means no wallet data or no market levels data; lemme fix BitMEX altcoin wallet on next commit

**Comment by asfbhero** [comment]
I thing something is backwards, I got negative numbers of balance and depleted funds on both bid and ask.  Then after reboot, got this:
  what():  [json.exception.type_error.302] type must be number, but is null
07/22 03:49:06.674350 Errrror: Aborted (Three-Headed Monkey found):
- exchange: BITMEX
- currency: EOS/U19
- binbuild: K-trading-bot linux-x86_64
- lastbeat: 0.066362
- tracelog:
  15: K-trading-bot(_start+0x2a) [0x55a994eb09fa]
  14: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f162c269b6b]
  13: K-trading-bot(main+0x22) [0x55a994eaf502]
  12: K-trading-bot(_ZN3₿11KryptoNinja4mainEiPPc+0x52f) [0x55a994eafe3f]
  11: K-trading-bot(_ZN3₿6Sqlite7backupsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_+0x5be) [0x55a994efdf1e]
  10: K-trading-bot(_ZN3₿6Sqlite12StructBackupINS_7mTargetEE4pullERKN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS4_14adl_serializerEEE+0x11b) [0x55a994f012fb]
  9: K-trading-bot(_ZNK8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEE5valueIdLi0EEET_RKS8_RKSC_+0x73) [0x55a994ef7d23]
  8: K-trading-bot(_ZN8nlohmann6detail20get_arithmetic_valueINS_10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEEEdLi0EEEvRKT_RT0_+0x122) [0x55a994ef7c22]
  7: K-trading-bot(+0x4e2e54) [0x55a995222e54]
  6: K-trading-bot(+0x4e2f11) [0x55a995222f11]
  5: K-trading-bot(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x55a995222ed6]
  4: K-trading-bot(+0x16c97d) [0x55a994eac97d]
  3: /lib/x86_64-linux-gnu/libc.so.6(abort+0x121) [0x7f162c268535]
  2: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7f162c286ed7]
  1: /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f162c286f60]
  0: K-trading-bot(_ZN3₿6Ending3wtfEi+0x419) [0x55a994f0fbe9]

**Comment by ctubio** [comment]
:bulb: will be fixed at https://github.com/ctubio/Krypto-trading-bot/issues/964
