### ISSUE TITLE
Depleted Funds Still An Issue

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#965]
Not sure if you're done with the fix yet, I don't want to sound like I'm pestering you with  all these issues, but in case you aren't aware, there is still an issue with  how the bot is reading the U19 side of things.  That should be the value in EOS.

Not sure if that's what's causing the issue with depleted funds, but it seems that way.

**Comment by ctubio** [comment]
:bulb: quick link to parent issue: https://github.com/ctubio/Krypto-trading-bot/issues/964
