### ISSUE TITLE
BitMex Order Book Lag - Not Urgent - Real Time Data

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#966]
I noticed the order book can get pretty laggy.

Not sure about everyone else, but I would prefer real time data over a deeper book.
Not sure if this is what's giving 1000ms+ lag time on orders, or if it's something else, but it's a good place to start.  I opened a VPS in AWS and my pings to bitmex are sub 1ms, so that is quite a difference.

https://www.bitmex.com/app/wsAPI#Subscriptions
If you wish to get real-time order book data, we recommend you use the orderBookL2_25 subscription. orderBook10 pushes the top 10 levels on every tick, but transmits much more data. orderBookL2 pushes the full L2 order book, but the payload can get very large. orderbookL2_25 provides a subset of the full L2 orderbook, but is throttled. In the future, orderBook10 may be throttled, so use orderBookL2 in any latency-sensitive application. For those curious, the id on an orderBookL2_25 or orderBookL2 entry is a composite of price and symbol, and is always unique for any given price level. It should be used to apply update and delete actions.

There is certainly profit to be made on this exchange, with the leverage forcing liquidations I imagine you will get some nice trades off.  Granted we will also be fighting against the bitmex internal market making team, but I'm happy to take their crumbs.

**Comment by ctubio** [comment]
ok thanks for the info; we are currently using `orderBookL2` will consider to change it thiz afternoOn
