### ISSUE TITLE
Bitmex - Thinks Every Trade Is a Pong

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#967]
![image](https://user-images.githubusercontent.com/6736484/61761708-84250480-ad9d-11e9-9b0a-2a27882a1062.png)

Endlessly buys and sells, I don't see the orders in the UI, I have it set to max trades 1/60 seconds but it will just keep buying/selling at whatever level the market is at.

**Comment by ctubio** [comment]
i dont see nothing wrong here; this looks like a consequence of another issue, not a issue by itself

since bitmex wallet is already in progress to be fixed, lemme mark this as a duplicate (hoping that the underlying issue here is the yet unfixed wallet)

**Comment by asfbhero** [comment]
I think this is due to  orders getting stuck on the exchange somehow or not updated properly.  In the latest release right around the same time as it started accumulating a bunch of orders I see that it got a failed to modify order error from the API. Right when that happened it didn't even see those as pings, just bought 20x times at one level.

![image](https://user-images.githubusercontent.com/6736484/61841349-75ecec00-ae62-11e9-9843-f017a43e055f.png)
