### ISSUE TITLE
Bitmex: With % Bid size is always 1, With Manual Values TBP Is Always 10

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#968]
When I'm using TA to dynamically adjust position I get a TBP of 10 no matter what tbp min, max, and pdiv values I use.  When I have % on the dynamic TBP works as it should, but the bid size is always 1. 

As for the TBP always getting set to 10, this happens to me on other exchanges as well, only it never mattered before because I always just used % instead of setting the values manually.

Also, do you think you could do a release with the fastest possible order book updates, orderBook10?

As for the wallet data it appears to be working perfectly now. Thanks!

![image](https://user-images.githubusercontent.com/6736484/61840975-075b5e80-ae61-11e9-82e6-dfbbb924a8be.png)

**Comment by asfbhero** [comment]
Not sure if this is a bug, or I'm doing something stupid.  Since this happens on other exchanges that are known to be working (unless this is an existing bug I'm not aware of), maybe I'm not setting things up right.  

My understanding is that using % with Value selected sets each variable to a % of total balance in the first currency in the pair.  For example, on bequant, eos/btc,  if I set the settings to say bid 5%, ask 5%, tbpmin 20%  tbpmax 80% pdiv20% pdivmin 10%, with an account value of 100EOS, the values should be, 5 eos, 5eos, 20eos, 80eos, 20eos, 10eos respectively.  

But if I set the values to those number of eos manually, TBP is always set to 10 EOS.

Now on Bitmex, the same pair's tbp values are listed in XBT, which is the second value in the currency pair.  I'm not sure what this does to the TBP calculation, does this reverse things?

Also how should TBP function in a margin account, where instead of 50% being flat, 0% would be flat.  Maybe I'm wrong about this, but it seems for margin accounts that there would need to be some kind of modification of the way TBP is calculated.  Or i'm wrong lol.

**Comment by ctubio** [comment]
TBP values on BitMEX are always XBT currency (that is the currency of the available wallet)

about the wrong values, im not sure that i understand your issue cos to me the values looks fine

**Comment by asfbhero** [comment]
With the percentages setting on tbp dynamically adjusts based on the moving
averages, when I set tbp min and max with xbt values tbp is always set to
10xbt no matter what values I assign to tbp min max.

Maybe I’m doing something wrong or misunderstanding something, I’ll play
with this a bit more and get back to you.

**Comment by asfbhero** [comment]
Ah, 1 contact is 1 eos, which looks correct then. Ok, cool I’ll get this
running later today.

**Comment by asfbhero** [comment]
I must be missing something.  

Say I have 0.01 XBT in my account, I set TBPMin to 0.01XBT, and TBP Max to 0.02XBT, PDIV is 0.005.

How can TBP every be 100XBT, I can't figure out where these tbp numbers are coming from.

Also, if I'm using %, and I set bid/ask size to 100% of account value, the bid/ask size is 1 EOS.

Maybe I'm just being stupid lol Any advice would be appreciated.

**Comment by ctubio** [comment]
just to help me understand, cos im not brave against maths; can you confirm that on XBTUSD the TBP calcs are OK? but on EOSU19 are wrong?

if both markets are wrong, then im totally lost and need to rethink again
if only EOSU19 is wrong i may know the solution already

many thanks for all you time reporting issues''¡

**Comment by asfbhero** [comment]
I believe it was happening on both pairs.  Though, since the last commit to fix the post only issue the bot crashes on startup regardless of the pair traded.

One theory of mine is that it's because of the way account value is reported with margin.  In a cash account we have 1/2 XBT 1/2 BTC, so if you are flat, having no position, you want TBP at 50%. 

But in a leveraged account with XBT as the margined currency, being flat is having no position at all, tbp of 0%.

Or all of that is totally wrong, since if I set the bot to manual mode tbp functions closer to how I would expect it to, only when introducing the moving averages does it set itself to a latge round number, 10XBT, or 100 XBT no matter what values I choose.

**Comment by ctubio** [comment]
makes sense that both are wrong cos both are using calculations from cash (`Spot`) markets (and should be `Inverted` or `Linear` for each; like in other wallet calculations)

**Comment by ctubio** [comment]
this issue happens also on Coinbase and all other exchanges, i mean, i not related to BitMEX but to all exchanges

**Comment by asfbhero** [comment]
Would it be possible to just do some math to transform 0tbp in a margin
account into the same as a 50%tbp as is n a spot account and keep the rest
of the math the same?

There must be a correct way to do this documented somewhere on the
internet. I will be in an airport for the next few hrs with nothing to do.
I’ll do some research.

**Comment by ctubio** [comment]
can you maybe elaborate to allow me to understand why 0tbp is the 50% of a margin account?

if you have 0 funds in a margin account, doesn't this means that all your funds are held in open positions? (if all funds are held, i would call that 0% not 50%)

so i didnt understood yet why you call 0tbp as "no position", to me is exactly the opposite

**Comment by asfbhero** [comment]
I suppose we are saying the same thing, your way just avoids negative numbers.  My visions was 0 being flat, -100% being no margin left while holding short positions, and +100% being no margin left holding long positions.

I imagine it matters how the existing code decides what side to set to tbpheld. If the bot only knows that i've used 50% of my margin, how does it know to stop buying or stop selling?  

I'm a bit weak in terms of the mechanics of automated position management, so I wouldn't put too much stock in my ideas about how this stuff should work on the back end.  My background is in manual HFT from my previous career and in IT.

So strategy and ideas for features that would help increase profitability, and troubleshooting things would be my strong suit.

**Comment by asfbhero** [comment]
For example, right now the bot thinks that tbp should be held on the bid side until the account gets to 1/2 of its starting amount of margin, only then will it start trading at both the bid and the ask.
