### ISSUE TITLE
Bitmex: Post-Only Doesn't Appear To Be Working

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#969]
The issue with the pongs is fixed, you're the greatest!

Unfortunately I've found another issue lol

The majority of orders look to be going in as a taker and paying the full 0.25% fee.  Not sure if there are any logs that can help with this, it's probably just a tweak with the API.

Thanks again.

**Comment by ctubio** [comment]
umf, lemme rereview all the attributes that we are sending

post-only is supposed (in all exchanges) to be auto set (without any way to be removed unless using the manual Submit Order form that is supposed to allow taker orders)

**Comment by asfbhero** [comment]
I think it's a combo of two things, the post order issue, and the order book not updating fast enough and the limits getting placed above the bid/below the ask.  I think we should try using the order book subscription that only has the first 10 levels, but updates on every tick.  

That will hurt strategies that use things like Hamelin Rat, but I would vastly prefer more accurate and faster pricing for market making than a deeper book.  Perhaps it could be set with a variable and a switch to be used at the command line when loading the bot to allow the user to customize and set the subscription that works best for their strategy.

**Comment by ctubio** [comment]
thanks for the suggestion'''
soo after next commit we can make use of `--market-limit 10` for example; other possible values are:
a value greater than 25 will use `orderBookL2`
a value greater than 10 will use `orderBookL2_25`
a value of 10 (that is the minimum allowed) will use `orderBook10`

about the postOnly attribute, is already OK

**Comment by asfbhero** [comment]
Kk, I’ll try this out with the order book 10 settings and let you know if I still am getting charged the taker fees on trades. Though if post only is working correctly it shouldn’t matter if the book is lagging, the orders should just not get executed if they are on the wrong side of the book.

Thanks for the update!

**Comment by asfbhero** [comment]
Post only is working... sometimes, which I don't get.
![image](https://user-images.githubusercontent.com/6736484/62013936-0af02d80-b160-11e9-80dd-57b43bdb598e.png)

Are there any logs you can recommend I look at to try to figure out what's going on?

**Comment by ctubio** [comment]
you are right, will fix postonly on next commit

**Comment by ctubio** [comment]
i had missunderstood my own condition to place the post-only flag :(

**Comment by asfbhero** [comment]
Now I get this when running it, 
![image](https://user-images.githubusercontent.com/6736484/62015767-10f00980-b174-11e9-93eb-21789d8551c7.png)

the first run it worked but I saw some strange behavior with the bid/ask quote, though that might just have been because the bquote wasn't wide enough to trade against.

**Comment by ctubio** [comment]
that must be a temporal error from the server side; here im not able to reproduce it

do you still have it as of now? or is already gone?

**Comment by asfbhero** [comment]
Seems fine now, you're right.
