### ISSUE TITLE
LTC/USD doesn't work on HitBTC

### ISSUE THREAD

**Issue by rok-povsic** [ctubio/Krypto-trading-bot#97]
Hi,

LTC/USD doesn't seem to work on HitBTC but BTC/USD works.

For LTC/USD, only market trades are displayed but there's no order book. BTC/USD displays both market trades and the order book.

Any idea what could be wrong? Tribeca works for both of them.

Thanks

**Comment by ctubio** [comment]
feel free to run `node K` and paste any log msg
