### ISSUE TITLE
BitMex: Pings Showing Up As Pongs Again

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#970]
![image](https://user-images.githubusercontent.com/6736484/62145914-4dca1680-b2c2-11e9-8a08-551f5cb87cd0.png)
![image](https://user-images.githubusercontent.com/6736484/62145929-54f12480-b2c2-11e9-823f-22e03704f8d3.png)
They show up as pings in the UI, but they trade like pongs in that they aren't being limted by trades/s.

They also aren't being added to the average entry price calculation for averagepingagressive.

**Comment by ctubio** [comment]
that was using Boomerang? or what mode?

**Comment by asfbhero** [comment]
boomerang, averagepingaggressive

**Comment by asfbhero** [comment]
I think I know why this is happening. It seems to happen only on one side.  Since fair value is being calculated incorrectly, either at the bid or the ask, depending on the settings.  The pings are being read as pongs on the side that is set as the fair value.

For example, if the bid is 2 and the ask is 4, the fair value should be 3.  However the bot thinks that the fair value is 2.  In this case the buy pings will be read as pongs.

If the bot thinks that the fair value is 4, then the sell pings will be read as pongs.

**Comment by asfbhero** [comment]
lol, well my fix for this very much did not work, account that knows the difference between pings and pongs = profitable overnight.  Bitmex account = now empty.

Just test funds, so no big deal, but still.  How difficult do you think it would be for me to undo the trades/sec change where it only applies to pings?

**Comment by asfbhero** [comment]
Fixed by increasing the price precision.

**Comment by asfbhero** [comment]
Well, I was wrong about adding additional decimal places fixing this issue.  I now have no idea what's causing it.

**Comment by ctubio** [comment]
as far as i had tested i believe this is not happening anymore; lemme close it

**Comment by asfbhero** [comment]
@ctubio seems to still be happening. Where is the code that determines pings vs pongs? Everything i've tried changing hasn't had an effect.
