### ISSUE TITLE
Need an extra decimal point

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#971]
![image](https://user-images.githubusercontent.com/6736484/62159958-e8d1e900-b2e0-11e9-8001-5d469b5f1b55.png)
I think the fair value is getting rounded up.  should be 0.000006355

**Comment by asfbhero** [comment]
Looks like bitmex provides support for getting bots to work with their API, the link to their support is here, https://www.bitmex.com/app/automatedTradingEngines

**Comment by ctubio** [comment]
that is not support, that is language-specific implementations (that they published instead of properly documenting the meaning of each attribute)

i have seen useless documentation pages, but https://www.bitmex.com/app/wsAPI is the most useless one; just listing channel names

**Comment by ctubio** [comment]
about the rounding decimals, these are the same as the displayed decimals, so for TBP the rounding is of 8 decimals; cannot have moar

**Comment by asfbhero** [comment]
Is there any way we can get the Fair Value to be in between the bid and the ask, instead of setting FV at the ask?

**Comment by ctubio** [comment]
umm let me investigate this situation of the fair value

**Comment by ctubio** [comment]
here you have exemplified the issue http://cpp.sh/3ppc6

happens at: https://github.com/ctubio/Krypto-trading-bot/blob/d2e08305bf4d23414ab1b2488aa8c59179d52981/src/lib/Krypto.ninja-user.h#L980-L981

and can be set to match the bid value if instear of round() you call floor() at: https://github.com/ctubio/Krypto-trading-bot/blob/d2e08305bf4d23414ab1b2488aa8c59179d52981/src/lib/Krypto.ninja-user.h#L997

**Comment by asfbhero** [comment]
I'm a bit new to compiling things in linux, I tried just editing the source file then running make, but it seems to not make any sort of difference.  I'm sure I'm doing something wrong.

**Comment by ctubio** [comment]
before `make` works, you need to build the distributed dependencies, that is `make dist`

once you have the dependencies, no need to run `make dist` anymore unless you remove them manually  with `rm -rf build-*`

**Comment by ctubio** [comment]
see https://github.com/ctubio/Krypto-trading-bot#build-notes

**Comment by asfbhero** [comment]
Thanks, not sure if this change is doing exactly what I want, but now that I know where to look and hot to get it to compile I can play with the math a bit mroe and see what I can come up with.

Thanks again!

**Comment by Camille92** [comment]
Yes, stream precision needs to be 9 instead of 8 in that particular example.

Yes, the general stream precision for this pair should be 8 (for minimal increment etc), however, FV needs to be in between the two values  at 0.00000635**5**.

Hope it helps,
Camille

**Comment by ctubio** [comment]
i would say there is no need to limit precision (most of the time while doing calculations)

precision only needs to be limiterd to 8 when displaying values to the final user

**Comment by asfbhero** [comment]
Is this value hard coded somewhere, I can find the variable, but I don't see where it's pulling it's value from.

**Comment by ctubio** [comment]
i think you are looking for: https://github.com/ctubio/Krypto-trading-bot/blob/9fe9cdbec0be8ea12847adb7d0e5b02b3c2520cd/src/lib/Krypto.ninja-apis.h#L315-L318

this sets the precision for each type of decimals

fairvalue uses `price` type

**Comment by asfbhero** [comment]
Perfect! Thanks!
Now I can start trying to shoehorn KAMA into EWMAPrice.  That should allow profitable trading on more volatile, and also more liquid pairs like XBT/USD.

**Comment by ctubio** [comment]
hope for this issue to be fixed at https://github.com/ctubio/Krypto-trading-bot/issues/984
