### ISSUE TITLE
program automatically suspends transactions

### ISSUE THREAD

**Issue by gohigh2313** [ctubio/Krypto-trading-bot#973]
After running for a period of time, the program automatically suspends transactions and needs to log in to the virtual machine and press ESC key.

description
please, consider to add all possible details (if any) about your new feature request or bug report

---
```
app exchange: HITBTC/ZEC/ETH
app version: undisclosed
OS distro: undisclosed
```
![300px-spock_vulcan-salute3](https://cloud.githubusercontent.com/assets/1634027/22077151/4110e73e-ddb3-11e6-9d84-358e9f133d34.png)

**Comment by ctubio** [comment]
i donno what is going on without some logs; consider to use  `--naked` argument and share some logs if you agree
