### ISSUE TITLE
question regarding position and order placement 

### ISSUE THREAD

**Issue by Corfucinas** [ctubio/Krypto-trading-bot#974]
![image](https://user-images.githubusercontent.com/53630064/62404527-8a9a5400-b5c7-11e9-90a5-d9bcaf8dca12.png)

![image](https://user-images.githubusercontent.com/53630064/62404574-e4028300-b5c7-11e9-87a0-b8fda418f102.png)

![image](https://user-images.githubusercontent.com/53630064/62404615-22983d80-b5c8-11e9-83f8-144eccc9b502.png)

Currently, my entry price is $10,280, 

Why is the buy order above that? I wish for the bot to only place an opposite order if it is at a profit, otherwise, I just wish to keep accumulating in one direction and wait for a trend change.
That is, for my sell order to be on top of $10,280, and any buy order below $10,280 (or of any price level which is profitable after the entry level moves)

**Comment by ctubio** [comment]
i think that is consequence of the PingAt = BothSides and Boomerang mode; consider PingAt olny one side maybe? and TBP to 0% or 100% as you consider

hope  this helps'' (otherwise feel free to coninue the conversation on IRC)

**Comment by Corfucinas** [comment]
Gracias por la respuesta

I want it to Ping at both sides, but only "if and only if"im actually in profit considering the Entry Level.
Setting TBP to 0% stopped the bids

![image](https://user-images.githubusercontent.com/53630064/62405797-a6582700-b5d4-11e9-8b34-c51fc1c458a6.png)


But now it seems I can't buy more than "1' contract

**Comment by ctubio** [comment]
hope was solved on irc'''
