### ISSUE TITLE
Coinbase websocket subscribe error

### ISSUE THREAD

**Issue by boogey100** [ctubio/Krypto-trading-bot#977]
I've just started getting this error from coinbase, running on an old version I've been running for months.  I just updated to the latest version and I'm still getting it. Any ideas?

K-trading-bot linux-arm 2019-08-06 18:55:40.
v0.5.3+67 (0day).
08/06 19:31:30.350875 GW COINBASE cached handshake:
- gateway: https://api.pro.coinbase.com
- gateway: wss://ws-feed.pro.coinbase.com
- gateway: fix.pro.coinbase.com:4198
- autoBot: no
- symbols: BTC/GBP (0.00000001/0.01)
- minSize: 0.00100000 BTC
- makeFee: 0.00% (please use --maker-fee argument!)
- takeFee: 0.00% (please use --taker-fee argument!).
08/06 19:31:30.351743 DB loaded OK from /var/krypto/db/ram/BTC.GBP.db.
08/06 19:31:30.360079 DB Warrrrning: using default values for Quoting Parameters.
08/06 19:31:30.360651 DB loaded last EWMA Values OK.
08/06 19:31:30.361092 DB loaded 9 historical Fair Values.
08/06 19:31:30.365281 DB loaded 202 STDEV Periods.
08/06 19:31:31.295144 GW COINBASE FIX success Logon, streaming orders.
08/06 19:31:31.295509 GW COINBASE WS Streaming book levels.
08/06 19:31:32.095827 DEBUG COINBASE <<< {"message":"Failed to subscribe","reason":"No channels provided","type":"error"}.
08/06 19:31:32.097206 GW COINBASE info msg {"message":"Failed to subscribe","reason":"No channels provided","type":"error"}.

**Comment by ctubio** [comment]
![596](https://user-images.githubusercontent.com/1634027/62571311-52c63180-b891-11e9-8861-b4c9062bc741.gif)

**Comment by boogey100** [comment]
Haha exactly!

**Comment by ctubio** [comment]
Coinbase does not defaults anymore to `full` channel, so it needs to be set explicit

:koala: incoming committtt'''

thanks for the report'''

**Comment by boogey100** [comment]
YES!!! You're the best!!! Thank you 💃
