### ISSUE TITLE
Safety improvement - Bitmex - remove automatic 1x leverage 

### ISSUE THREAD

**Issue by Corfucinas** [ctubio/Krypto-trading-bot#979]
![inkedremoveleverage](https://user-images.githubusercontent.com/53630064/62598522-358a7500-b91c-11e9-9ff2-355a004531ca.jpg)

Hi,
Just a simple request.
When the WS is disconnected for some reason, the bot automatically boots up and on the initial cycle its programmed to set the leverage to 1x on Bitmex - usually it will just fail if you have enough contracts already and dont have enough margin left 

But if you're running it on Cross - while building your position - if it shifts to 1x and you dont have access to monitor it during a restart, you will run into a higher risk OR not beign able to continue bids/asks.

Would it be possible to leave the automatic "leverage" setting on Bitmex on "Cross"? The user can just adjust it on the exchange side to fits his strategy

As always, thanks

**Comment by ctubio** [comment]
see --help, use --leverage

**Comment by Corfucinas** [comment]
thank you!
