### ISSUE TITLE
Multiple instances configuration problems

### ISSUE THREAD

**Issue by Jorman** [ctubio/Krypto-trading-bot#98]
Hi, always me, I'm trying to run multiple instance but I've some question

For my organization on /etc folder I wanna have only the configuration in a "specific" format so all my configuration is like that:
`poloniex-btc-xrp-3000.json`
For me is easy to understand what configuration I need

So I removed all from /etc folder and I've put on it only my .json files but without the K.json file I can't start the bot with
npm run startall, seems to start but no instance start

Any idea? I miss some?

**Comment by ctubio** [comment]
i just fixed yesterday the `npm run startall` command; if instead you wanna run a single instance the command may be:
`KCONFIG=poloniex-btc-xrp-3000 node K`
or
`npm start --K.js:config=poloniex-btc-xrp-3000`

both do the same, and sure there are more ways to do the same
