### ISSUE TITLE
Executed orders not showing up as Pings

### ISSUE THREAD

**Issue by Corfucinas** [ctubio/Krypto-trading-bot#980]
Hi

Noticed that sometimes when an order get's executed on Bitmex its not showing up on the bot memory, it's been like this a few days, but just wanted to point it out since it messes with my protection TS .

Order executed on Bitmex

![ordernonexecution](https://user-images.githubusercontent.com/53630064/62674324-7ba30f80-b9d4-11e9-9c9d-9dee9e1969e6.jpg)

Orders in memory (also noticed theres another order at 6:56:45 AM and 6:34:44 AM missing)
![sellts](https://user-images.githubusercontent.com/53630064/62674375-b5741600-b9d4-11e9-99cb-cf759745e862.jpg)

Bot log

![klogs](https://user-images.githubusercontent.com/53630064/62674421-dd637980-b9d4-11e9-940f-894d8220cb6f.jpg)

Let me know if those screenshots are useful or need something else

**Comment by ctubio** [comment]
you can't compare the history of K with the history of bitmex; they are totally unrelated

about many other behaviours, they are unrelated becase orders on K are accumulated by price

**Comment by ctubio** [comment]
SelTS must be 0 because of the settings; consider to double check the value set at `trades/sec`

**Comment by Corfucinas** [comment]
thank you @ctubio

**Comment by ctubio** [comment]
excuse me, but thanks to you for all the reports and suggestions :dancer:

**Comment by ctubio** [comment]
:koala: hope for thiz issue to be fixed at https://github.com/ctubio/Krypto-trading-bot/issues/989
