### ISSUE TITLE
Bitmex: Limit Number Of API Calls - Getting IP Banned Every Few Min

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#982]
So, now that I got the bot trading on bitmex in a way that is functional to by setting trades/s to apply to both pings and pongs, I'm now running into an issue where I'm getting IP banned for 1hr due to too many API requests.  

Is there a part of the code where I can set a hard limit on the number of API calls per minute?

This is so frustrating, we have an exchange that offers maker rebates and leverage, an ideal situation for market making, yet they make it so hard to actually do market making on their platform.

Looks like it has to do with the number of errors thrown, not sure how to tell what is causing these errors.  I ran in debug mode and didn't see anything weird.

https://www.bitmex.com/app/restAPI :
Be very careful about the number of errors your tools throw! If a large number of 4xx or 5xx responses are delivered in a short period of time, your IP may be banned for an hour. Multiple bans in a short time will result in a week ban.

**Comment by ctubio** [comment]
see --help argument
use --lifetime

**Comment by asfbhero** [comment]
Thanks, I can’t believe I didn’t see that. I’ll give it a shot when I get home.

Appreciate it
