### ISSUE TITLE
Bitmex - Working Settings

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#984]
For anyone who has been messing with bitmex, I have been able to get it usable by setting trades/sec to apply to both pings and pongs since it thinks almost everything is a pong.  You can't just increace the price precision to fix the fairvalue issue, because then your orders get rejected due to invalid tick size.  You can get the FV right in the middle of  the bid/ask by setting FV to BBO, and changing the fair value code in users.h to fairvalue = fairvalue, decoupling it from the price precision, which has to be at the default values.

I'm sure there is a better way to do it than this, but this is what has worked for me.

**Comment by ctubio** [comment]
make sense, lemme see that doesnt have unwanted side effects before include it in the build

**Comment by asfbhero** [comment]
@ctubio Perhaps I was wrong.  I appear to have gotten banned for spam orders for 24 hrs.  Which is better than getting banned every few min for an hr, maybe we need some kind of error handling. 

What's weird is that this didn't throw any errors in the logs. Not sure how this happened, I have it set with a lifetime of 2000, and was using 0.025XBT order size.  Which seems to be within their parameters.

I'm at a bit of a loss.

**Comment by ctubio** [comment]
errr have no relation the spamming of orders with the rounding of the fair value

maybe the last comments of https://github.com/ctubio/Krypto-trading-bot/issues/987 helps?

**Comment by asfbhero** [comment]
It was just their documentation being wrong. You just have to trade bigger, then they don’t care.
