### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by wuminzhe** [ctubio/Krypto-trading-bot#985]
When I run 'make install', I got this error:

    /bin/sh: x86_64-apple-darwin17-g++: command not found

But my mac has already installed lastest "Command Line Tools", and g++ command is ok.

My system is macos mojave 10.14.2 (18C54)

**Comment by ctubio** [comment]
morning'''

if you have any g++ maybe can you create a symlink at `/usr/bin/x86_64-apple-darwin17-g++` pointing to your g++?

**Comment by wuminzhe** [comment]
El Capitan's new System Integrity Protection feature prevents changes to several core parts of OS X, including  /usr/bin, even by root.
so when I do:
```sudo ln -s /usr/bin/g++ /usr/bin/x86_64-apple-darwin17-g++```
I got:
```ln: /usr/bin/x86_64-apple-darwin17-g++: Operation not permitted```

**Comment by ctubio** [comment]
and at `/usr/local/bin`? or at any other folder that is already in your path and doesn't feels dirty?

the plan is to make exitent somewhere in the path a symblin named `x86_64-apple-darwin17-g++` pointing to a `g++`  v7 or v8 executable

**Comment by ctubio** [comment]
i was able todayto reproduce it, will be fixed on next commit

:koala: thanks for the report'''
