### ISSUE TITLE
MinTick at Bitfinex is not always respected

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#99]
Hey Carles,

I realized that now the minTick at Bitfinex is not always respected:

Example with the IOT/ETH market:

![capture d ecran 2017-07-25 a 12 41 48](https://user-images.githubusercontent.com/6861590/28568601-bca69972-7136-11e7-9c8f-c50b7cf7c8ed.png)

I guess there is an error between the new and old formula no?
```
        if (k.find("last_price") != k.end()) {
          istringstream os(string("1e-").append(to_string(5-k["last_price"].get<string>().find("."))));
          os >> minTick;
          minSize = 0.01; 


gwSetMinTick(parseFloat('1e-'+precisePrice.substr(0, precisePrice.length-1).concat('1').replace(/^-?\d*\.?|0+$/g, '').length));
```

I remember you had to change the formula because in the case of the last price finishing by 0 it was not giving the good result. maybe it's that no?

**Comment by ctubio** [comment]
i totally rewrite the function to get minTick from bitfinex (so now doesnt have the issue of the trailing 0), but anyway i may had write shit for non-USD markets (you know im maybe too much focused in BTC/EUR/USD as happened also before)

will try my best to put brain in place of alternative currencies and refix the bitfinex minTIck soOn

sorry for the mess

**Comment by ctubio** [comment]
what will be really helpful is if can you please give me a list or a link to a list of some expected minTIck values for some bitfinex markets? (this way i would be able to validate the formula, currently im just validating BTC/USD cos i know for sure the minTick is 0.1 in bitfinex)

**Comment by ctubio** [comment]
the current formula knows that bitfinex price precision in all markets is 5, so it just substract from 5 the amount of digits at the LEFT side of the decimal point.

That may be not tru for alternative markets :(

**Comment by Camille92** [comment]
Yes sure

https://docs.bitfinex.com/docs/readme
Price Precision
The precision level of all trading prices is calculated based on significant figures.

For all pairs on Bitfinex we use 5 significant digits. Examples of five significant digits would be 12.123, 1.1234, 123.43, and 1234.5.

This mimics how traditional global markets dynamically handle precision of small, medium, and larger values. The rationale behind this is that the higher the amount the less relevant the number of decimals becomes. The corollary is true for very small amounts, where more precision is more useful.

Note: API will truncate price with precision > 5

**Comment by Camille92** [comment]
Okay I think I have the problem:

If the last price is not with 5 numbers, then it's not replaced by 0 but by nothing. That can explain the mistake no?

**Comment by ctubio** [comment]
so looks like the theory of the formula is OK but really is wrongly applicated? will investigate it laterz thiz afternoOn'¡ (many thanks for confirm'')

**Comment by Camille92** [comment]
I found an example:

Here in ETC/USD, the last price has only 4 values instead of 5 because the last one is a 0.

How can I try the formula ?

![capture d ecran 2017-07-25 a 14 16 08](https://user-images.githubusercontent.com/6861590/28571593-df1c6f38-7143-11e7-91da-46299ef39ce2.png)

**Comment by ctubio** [comment]
in javascirpt may be something liiiiike https://jsfiddle.net/med9462k/ catch you laterz'¡ (5 is the supposed price precision that is 5 for all markets, and you can play with the number later i think)

**Comment by ctubio** [comment]
you mean there are prices without the symbol `. `? so the formula fails?

**Comment by Camille92** [comment]
I'm on IRC it should be easier to talk there :)

**Comment by Camille92** [comment]
I found the issue -> For all small numbers the minimum min tick is 0.0001 and it can not get lower than that.

So it's an issue for all BTC and ETH denominated markets !

**Comment by ctubio** [comment]
![itsover1000](https://user-images.githubusercontent.com/1634027/28586206-3d62e4c6-7173-11e7-9e0b-b18e3f528b60.jpg)
