### ISSUE TITLE
COINBASE - Weird Server Reply

### ISSUE THREAD

**Issue by JakeFit** [ctubio/Krypto-trading-bot#991]
After unsuccessfully being able to use Kraken effectively, I am attempting to you Coinbase. However, I receive the below error and it has been happening for at least 4 hours.

![image](https://user-images.githubusercontent.com/20308435/63776644-1ed8ac00-c925-11e9-9700-c370d87eeb84.png)

**Comment by ctubio** [comment]
works by now; maybe 3h ago coinbase was really fucked

**Comment by ctubio** [comment]
for next time, since usualy https://status.pro.coinbase.com/ lies with all green,  you can double check it with `wscat` like:
```
$ wscat -c wss://ws-feed.pro.coinbase.com
```
