### ISSUE TITLE
Zombie [nation] - CPU usage over 100% and bot stops

### ISSUE THREAD

**Issue by Corfucinas** [ctubio/Krypto-trading-bot#992]
Hi,

For the past three weeks I been experiencing sudden and unexplained spikes in CPU usage by K.
I though I might need a higher CPU core to deal with a normal part of the process, so I migrated servers and got a 3.2 GHz-no avail. 
Once it reaches 100% it just stops sending orders, the last orders submitted will stay in place ignoring FV until they get executed, then the position just hangs.

![Annotation 2019-08-28 092056](https://user-images.githubusercontent.com/53630064/63822701-cdabd500-c983-11e9-856f-07f7782c813e.jpg)

![Annotation 2019-08-28 092323](https://user-images.githubusercontent.com/53630064/63822706-d13f5c00-c983-11e9-8606-f4776bdb4858.jpg)

Three times only this week

![Annotation 2019-08-28 092817](https://user-images.githubusercontent.com/53630064/63822738-e61bef80-c983-11e9-91f3-f8817abcfbd3.jpg)

Quick fix - something like Monit to monitor and if it goes over n%> allowed CPU just restart (by restarting the process it behaves normally and doesn't go over 6% usage).

But if somebody doesnt have access to the server for any reason (they go out for the weekend) then they would get basically find themselves with a stucked position which is dangerous.
Also, if you use the server for any other process they would basically crashed (mine just crashed and had to hard restart it on this occasion).

---

**Comment by ctubio** [comment]
what exchange are you using? bitmex? or hitbtc/bequant?

are you on linux? or macos? or winy?

**Comment by ctubio** [comment]
coOl'' i believe then is bitmex spamming buncha information (filled market trades) every now and then

lemme in rereview bitmex data carefully for a few to see if some event is firing nonstop every millisecond (like market trades)

thanks for the report'''

**Comment by ctubio** [comment]
i got all info already ty''' just i need to identify and amend the situation; many thanks for your help'¡

:koala: sorry ima leave this here to be used meanwhile debugging:
https://www.youtube.com/watch?v=Ayq_I1NU2Q8

**Comment by Corfucinas** [comment]
Happened again, just when BTC dropped, woke up with frozen orders since 1am (UTC+8)

![cpu](https://user-images.githubusercontent.com/53630064/63904964-46269a80-ca45-11e9-9c27-1a524dcda8e7.jpg)

**Comment by asfbhero** [comment]
This might be happening for me too. Seems to be during fast movements, so bitmex spamming us with fast orders and the bot getting overloaded somehow makes sense.

**Comment by Corfucinas** [comment]
Hey, just following up on stale comments/issues from the past. Any ideas what might be causing this? ¿Alguna forma que pueda ayudar?

**Comment by nonkreon** [comment]
I have been experiencing this since forever, let me try to identify the cause using the symptoms; one question to everyone experiencing this: do you have super opportunities enabled or disabled?

**Comment by Corfucinas** [comment]
> I have been experiencing this since forever, let me try to identify the cause using the symptoms; one question to everyone experiencing this: do you have things that focus on putting in multiple orders like super opportunities or safeties enabled or disabled? if you're using ak-47 safety, how many bullets did you allow?

@nonkreon 

Nope. Never used that setting. Using ping pong with aggressive. No SOP either. Also, no EMAs, just manual.

**Comment by ctubio** [comment]
lets fix this at https://github.com/ctubio/Krypto-trading-bot/issues/1031 (i do belive is the same issue)
also will add rejected messages to the output

**Comment by Corfucinas** [comment]
@ctubio Gracias
