### ISSUE TITLE
Only send orders if the quote is at the top of the market.

### ISSUE THREAD

**Issue by asfbhero** [ctubio/Krypto-trading-bot#993]
I've been getting api ban warnings for having too low of a quote to fill ratio on bitmex.

I'm using Hamelinrat, and while the bot is placing orders how I want it to, but my QFR is too low as it's sending orders that will never get executed.

The only orders that actually matter are the ones where the largest size is at the very top of the market.  

I'm trying to figure out a way to have the bot only place an order if it's at the top of the book.  I'm sure there is a way to do this, maybe by writing a function that says something like, if quote price = bbo, send order, otherwise set to TBP held.  

Not looking for a pretty solution, any tips of where to look in the code, or someone saying that it would be way too difficult and wouldn't be worth the effort lol

**Comment by ctubio** [comment]
errr just use the smallest possible width and disable all protections
